CREATE ROLE [AA_CONFIGURABLE_R]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [AA_CONFIGURABLE_R] ADD MEMBER [AA_CONFIGURABLE_AR];


GO
ALTER ROLE [AA_CONFIGURABLE_R] ADD MEMBER [DASHBOARD];


GO
ALTER ROLE [AA_CONFIGURABLE_R] ADD MEMBER [Despatch5];


GO
ALTER ROLE [AA_CONFIGURABLE_R] ADD MEMBER [Despatch1];


GO
ALTER ROLE [AA_CONFIGURABLE_R] ADD MEMBER [Despatch2];


GO
ALTER ROLE [AA_CONFIGURABLE_R] ADD MEMBER [Despatch3];


GO
ALTER ROLE [AA_CONFIGURABLE_R] ADD MEMBER [Despatch4];


GO
ALTER ROLE [AA_CONFIGURABLE_R] ADD MEMBER [CORPORATE\Steven.Lundlarsen];

