CREATE ROLE [AA_DIMENSIONS_R]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [AA_DIMENSIONS_AR];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [DASHBOARD];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Adam ThomasA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [internet access];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [internet accessA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch5];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch5A];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch1];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch1A];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Tech labels];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Tech labelsA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch2];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch2A];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Byron Sun];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Byron SunA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch3];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch3A];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Jon HandfordA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch4];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch4A];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Roland Seiksts];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Roland SeikstsA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Lene BuddA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [JCC Ningbo Unlock];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Oliver CrossA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [xiaochen.liA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Louise.HumesA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Warehouse Returns];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Warehouse ReturnsA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Warehouse Invoices];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Warehouse InvoicesA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [JCC Ningbo UnlockA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Janet Holmes - UnlockA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Henry LiA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Claire Maull - Purch2A];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Lee Lambourne - UnlockA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Lin Thomas];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Lin ThomasA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Access UserA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch6];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch6A];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch7];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch7A];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch8];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Despatch8A];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [CORPORATE\Steven.Lundlarsen];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Connor.Mathers - Purch2A];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Graeme Priest];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Graeme PriestA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [temp];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [tempA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Zak];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [ZakA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Goods-In];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Goods-InA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Stephanie TangA];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Adam.Thomas];


GO
ALTER ROLE [AA_DIMENSIONS_R] ADD MEMBER [Paul.King];

