CREATE ROLE [MSReplPAL_13_1]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [MSReplPAL_13_1] ADD MEMBER [WEB];


GO
ALTER ROLE [MSReplPAL_13_1] ADD MEMBER [CORPORATE\Steven.Lundlarsen];


GO
ALTER ROLE [MSReplPAL_13_1] ADD MEMBER [Adam.Thomas];

