CREATE PROCEDURE [dbo].[AA_AOI_WMM_CHECK_INVOICE_SECURITY_S]
@UID VARCHAR (4) NULL, @OPTION INT NULL, @GRANTED INT NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


