CREATE PROCEDURE [dbo].[AA_AOI_INXL_SYS_BUDGETS_GET_LATEST_REVNBR]
@nomcode VARCHAR (25) NULL, @year INT NULL, @B_RECORD_TYPE VARCHAR (1) NULL, @B_BUDGET_TYPE VARCHAR (1) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


