CREATE PROCEDURE [dbo].[AA_AOI_SALES_ORDER]
@USERID VARCHAR (10) NULL, @S_CUSTOMER VARCHAR (10) NULL, @S_ORDERREFERENCE VARCHAR (20) NULL, @S_DATE DATETIME NULL, @S_REQUIREDDATE DATETIME NULL, @S_BATCHREFERENCE VARCHAR (10) NULL, @S_STOCKCODE VARCHAR (25) NULL, @S_SUBANALYSIS VARCHAR (25) NULL, @S_PRICECODE VARCHAR (16) NULL, @S_DETAILTEXT VARCHAR (240) NULL, @S_ANLAYSIS VARCHAR (25) NULL, @S_VATCODE VARCHAR (1) NULL, @S_VATAMOUNT FLOAT (53) NULL, @S_LINEDISCOUNT FLOAT (53) NULL, @S_QUANTITY FLOAT (53) NULL, @S_PRICE FLOAT (53) NULL, @S_SOURCE VARCHAR (5) NULL, @S_BATCH VARCHAR (1) NULL, @LINENUMBER FLOAT (53) NULL, @S_ORDERTYPE VARCHAR (3) NULL, @S_PROJECT VARCHAR (10) NULL, @S_COSTCENTRE VARCHAR (10) NULL, @S_CURRENCY VARCHAR (5) NULL, @S_STOCK_ANALYSIS VARCHAR (25) NULL, @PS_TRAN_ID INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


