CREATE PROCEDURE [dbo].[AA_AOI_NOMINALJNL]
@USERID VARCHAR (25) NULL, @NL_CreditDebit VARCHAR (5) NULL, @NL_Code VARCHAR (25) NULL, @NL_Value DECIMAL (24, 8) NULL, @NL_Period INT NULL, @NL_Year VARCHAR (1) NULL, @NL_Contra VARCHAR (25) NULL, @NL_VATContra VARCHAR (25) NULL, @NL_Date DATETIME NULL, @NL_Reference VARCHAR (10) NULL, @NL_Currency VARCHAR (5) NULL, @NL_VATCode VARCHAR (5) NULL, @NL_IMPORT_EXPORT_CODE VARCHAR (5) NULL, @NL_BATCH_REF VARCHAR (10) NULL, @NL_PROJECT VARCHAR (10) NULL, @NL_COSTCENTRE VARCHAR (10) NULL, @NL_DESCRIPTION VARCHAR (200) NULL, @NL_DIMENSION1 VARCHAR (20) NULL, @NL_DIMENSION2 VARCHAR (20) NULL, @NL_DIMENSION3 VARCHAR (20) NULL, @NL_DETAIL VARCHAR (240) NULL, @NL_DO_NOT_BATCH INT NULL, @LINENUMBER INT NULL, @PS_TRAN_ID INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


