CREATE PROCEDURE [dbo].[AA_AOI_INXL_GET_NOMINAL_COST_TO_GROUP]
@GUID VARCHAR (36) NULL, @dt_code VARCHAR (6) NULL, @NMAJORHEADCODE INT NULL, @NCATEGORYCODE1 VARCHAR (6) NULL, @NCATEGORYCODE2 VARCHAR (6) NULL, @NCATEGORYCODE3 VARCHAR (6) NULL, @NCATEGORYCODE4 VARCHAR (6) NULL, @NCATEGORYCODE5 VARCHAR (6) NULL, @NCATEGORYCODE6 VARCHAR (6) NULL, @NCATEGORYCODE7 VARCHAR (6) NULL, @NCATEGORYCODE8 VARCHAR (6) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


