CREATE PROCEDURE [dbo].[AA_AOI_INXL2_DELETEGUID_FROMCOSTINGBUDGETSELLVOLUMESTABLE]
@GUID VARCHAR (36) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


