CREATE PROCEDURE [dbo].[AA_AOI_ADVANCED_BUY_ONE_GET_ONE_FREE_PRICE_MATRIX]
@P_PRICELISTTYPE VARCHAR (3) NULL, @P_PRICELISTNAME VARCHAR (40) NULL, @P_EFFECTIVEFROM DATETIME NULL, @P_EFFECTIVETO DATETIME NULL, @P_CRYSTALREPORTNAME VARCHAR (200) NULL, @P_CURRENCY VARCHAR (5) NULL, @P_ACTIVE TINYINT NULL, @P_PRIORTITY INT NULL, @P_SORTKEY VARCHAR (20) NULL, @P_NOTES VARCHAR (MAX) NULL, @P_SUBANALYSISFILTER TINYINT NULL, @P_SUBANALYSISSTRING VARCHAR (MAX) NULL, @P_CUSTOMERLIST VARCHAR (MAX) NULL, @P_PRODUCTCATEGORYTYPE VARCHAR (1) NULL, @P_PRODUCTCATEGORY VARCHAR (25) NULL, @P_EXCLUDEPRODUCT TINYINT NULL, @P_SINGLEORQUANTITY TINYINT NULL, @P_QUANTITYFROM FLOAT (53) NULL, @P_QUANTITYTO FLOAT (53) NULL, @P_METHOD VARCHAR (1) NULL, @P_VALUE FLOAT (53) NULL, @P_DISCOUNTPERCENTAGE FLOAT (53) NULL, @P_CASHDISCOUNT FLOAT (53) NULL, @P_CHAINEDDISCOUNT FLOAT (53) NULL, @P_BUYONEGETONEFREETYPE TINYINT NULL, @P_BUYQUANTITY FLOAT (53) NULL, @P_FREEQUANTITY FLOAT (53) NULL, @P_MAXIMUMALLOWANCE FLOAT (53) NULL, @P_MINIMUMQUANTITY FLOAT (53) NULL, @P_APPLYTOSALESORDERS VARCHAR (3) NULL, @P_APPLYTOCREDITNOTES VARCHAR (3) NULL, @P_MATCHALLCUSTOMERCRITERIA VARCHAR (3) NULL, @P_MATCHALLPRODUCTCRITERIA VARCHAR (3) NULL, @P_APPLYTOALLCUSTOMERS VARCHAR (3) NULL, @P_APPLYTOALLPRODUCTS VARCHAR (3) NULL, @P_GROSSPRICES VARCHAR (3) NULL, @P_DISPLAYPROMPTSOPUSERS VARCHAR (3) NULL, @P_OVERRIDESTANDARDPRICING VARCHAR (3) NULL, @P_USESUBANALYSISASSIGNPRICEMETHODS VARCHAR (3) NULL, @PS_TRAN_ID INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


