CREATE PROCEDURE [dbo].[AA_AOI_CREATE_TIMESHEETS]
@USERID VARCHAR (4) NULL, @TM_PRJ_CODE VARCHAR (10) NULL, @TM_CST_CODE VARCHAR (10) NULL, @TM_RES_CODE VARCHAR (16) NULL, @TM_WK_NO INT NULL, @TM_PAY_TYPE VARCHAR (20) NULL, @TM_YEAR VARCHAR (1) NULL, @TM_STATUS VARCHAR (1) NULL, @TM_REFERENCE VARCHAR (10) NULL, @TM_PERIOD INT NULL, @TM_RATE FLOAT (53) NULL, @TM_HOURS FLOAT (53) NULL, @TM_DATE_ENTERED DATETIME NULL, @TM_SOURCE VARCHAR (1) NULL, @TM_BATCH INT NULL, @TM_BATCH_REF VARCHAR (10) NULL, @PS_TRAN_ID INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


