CREATE PROCEDURE [dbo].[AA_AOI_INXL_FP_BUDGET_LOCK_DEFAULT]
@lock BIT NULL, @active BIT NULL, @code1 VARCHAR (25) NULL, @code2 VARCHAR (25) NULL, @revision INT NULL, @B_RECORD_TYPE VARCHAR (1) NULL, @B_BUDGET_TYPE VARCHAR (1) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


