CREATE PROCEDURE [dbo].[AA_AOI_PURCHASE_INVOICE_CREDIT_TABLE_BASED]
@P_SUPPLIER VARCHAR (10) NULL, @P_ORDERREFERENCE VARCHAR (25) NULL, @P_DATE DATETIME NULL, @P_BATCHREFERENCE VARCHAR (10) NULL, @P_DUEDATE DATETIME NULL, @P_ANALYSIS VARCHAR (25) NULL, @P_DESCRIPTION VARCHAR (30) NULL, @P_DETAIL VARCHAR (240) NULL, @P_VATCODE VARCHAR (3) NULL, @P_VATAMOUNT FLOAT (53) NULL, @P_NET FLOAT (53) NULL, @P_GROSS FLOAT (53) NULL, @PS_User_ID VARCHAR (10) NULL, @P_SOURCE VARCHAR (5) NULL, @P_BATCH VARCHAR (1) NULL, @P_ORDERTYPE VARCHAR (5) NULL, @LINENUMBER FLOAT (53) NULL, @P_PROJECT VARCHAR (10) NULL, @P_COSTCENTRE VARCHAR (10) NULL, @P_CURRENCY VARCHAR (6) NULL, @P_SUBLEDGER VARCHAR (10) NULL, @P_TRANKEY1 VARCHAR (10) NULL, @P_TRANKEY2 VARCHAR (10) NULL, @P_TRANKEY3 VARCHAR (10) NULL, @PS_TRAN_ID INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


