CREATE PROCEDURE [dbo].[AA_AOI_STOCK_MOVE]
@SM_STOCK VARCHAR (25) NULL, @SM_TYPE VARCHAR (1) NULL, @SM_TRAN_STATUS VARCHAR (1) NULL, @SM_REFERENCE VARCHAR (10) NULL, @SM_DATE DATETIME NULL, @SM_BATCH_REFERENCE VARCHAR (10) NULL, @SM_STOCK_ANALYSIS VARCHAR (25) NULL, @SM_SUB_ANALYSIS VARCHAR (25) NULL, @SM_DETAIL VARCHAR (240) NULL, @SM_SERIALNUMBER VARCHAR (25) NULL, @SM_COST FLOAT (53) NULL, @SM_VAT FLOAT (53) NULL, @SM_QUANTITY FLOAT (53) NULL, @USERID VARCHAR (10) NULL, @LINENUMBER FLOAT (53) NULL, @SM_DO_NOT_BATCH VARCHAR (1) NULL, @SM_PRICE FLOAT (53) NULL, @SM_PROJECT VARCHAR (10) NULL, @SM_COSTCENTRE VARCHAR (10) NULL, @PS_TRAN_ID INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


