CREATE PROCEDURE [dbo].[AA_AOI_BUDGET_LATEST_REVISION]
@B_ACCOUNT_CODE VARCHAR (25) NULL, @B_PERIOD TINYINT NULL, @B_YEAR VARCHAR (5) NULL, @B_REVISION_NUMBER DECIMAL (24, 8) NULL, @B_LATEST BIT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


