CREATE PROCEDURE [dbo].[AA_AOI_UPDATE_BUDGETS_YEAR_POINTER]
@B_ACCOUNT_CODE VARCHAR (25) NULL, @B_RECORD_TYPE VARCHAR (2) NULL, @B_BUDGET_TYPE VARCHAR (1) NULL, @B_VALUE DECIMAL (24, 8) NULL, @B_PERIOD TINYINT NULL, @B_YEAR VARCHAR (5) NULL, @B_SOURCE VARCHAR (1) NULL, @B_DATE_ENTERED VARCHAR (25) NULL, @B_SECONDARY_CODE VARCHAR (25) NULL, @B_USERID VARCHAR (4) NULL, @B_REVISION_NUMBER DECIMAL (24, 8) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


