CREATE PROCEDURE [dbo].[AA_AOI_UPDATE_MATRIX]
@MAT_TYPE VARCHAR (1) NULL, @MAT_PERC INT NULL, @MAT_USER_EDITED VARCHAR (4) NULL, @MAT_USER_PUTIN VARCHAR (4) NULL, @MAT_DATE_EDITED VARCHAR (25) NULL, @MAT_DATE_PUTIN VARCHAR (25) NULL, @MAT_PRICE FLOAT (53) NULL, @MAT_CUSTOMER VARCHAR (20) NULL, @MAT_STOCK_KEY VARCHAR (25) NULL, @MAT_PERCENT1 FLOAT (53) NULL, @MAT_PERCENT2 FLOAT (53) NULL, @MAT_PERCENT3 FLOAT (53) NULL, @MAT_PERCENT4 FLOAT (53) NULL, @MAT_PERCENT5 FLOAT (53) NULL, @MAT_PERCENT6 FLOAT (53) NULL, @MAT_PERCENT7 FLOAT (53) NULL, @MAT_PERCENT8 FLOAT (53) NULL, @MAT_PERCENT9 FLOAT (53) NULL, @MAT_PERCENT10 FLOAT (53) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


