CREATE PROCEDURE [dbo].[AA_CHECK_SERIAL_NO_S]
@PS_Stock_Code VARCHAR (25) NULL, @PS_Default_String VARCHAR (50) NULL, @PS_Serial_No VARCHAR (40) NULL OUTPUT, @PS_SubAnalysis VARCHAR (25) NULL OUTPUT, @PS_Direction VARCHAR (3) NULL, @PS_Module VARCHAR (3) NULL, @PS_SubAnalysisStockItem TINYINT NULL, @PS_Quantity INT NULL, @PS_OutputMethod INT NULL, @PS_SerialTempID INT NULL, @PS_Error_Status INT NULL OUTPUT, @PS_DetailPrimary INT NULL, @PS_SerialPrimary INT NULL OUTPUT, @PS_SerialLinkPrimary INT NULL OUTPUT, @PS_LotNumber VARCHAR (20) NULL OUTPUT, @PS_Renew_Date DATETIME NULL OUTPUT, @PS_SortKey VARCHAR (20) NULL OUTPUT, @PS_ExcludeFromSOP TINYINT NULL OUTPUT, @PS_SerialUserDate1 DATETIME NULL OUTPUT, @PS_SerialUserDate2 DATETIME NULL OUTPUT, @PS_SerialUserDate3 DATETIME NULL OUTPUT, @PS_DateReceived DATETIME NULL OUTPUT, @PS_OrderRef VARCHAR (20) NULL OUTPUT, @PS_AccountRef VARCHAR (20) NULL OUTPUT, @PS_BatchFlag TINYINT NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


