CREATE PROCEDURE [dbo].[AA_CST_UNRECOVERABLE_EXTRA_WORK_CANCEL_S]
@PS_ErrorHandlingMethod INT NULL, @PS_UserID NVARCHAR (4) NULL, @PS_GUID UNIQUEIDENTIFIER NULL OUTPUT, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ClearMode TINYINT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


