CREATE PROCEDURE [dbo].[AA_CST_WIP_RELEASE_LIST_S]
@PS_UserID NVARCHAR (4) NULL, @PS_MaxRecords INT NULL, @PS_CalledFrom INT NULL, @PS_StartValue SQL_VARIANT NULL, @PS_StartPrimary INT NULL, @PS_OrderByDescending TINYINT NULL, @PS_OrderByFieldName [sysname] NULL, @PS_TotalRecordCount INT NULL OUTPUT, @PS_AdvancedResponse TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_GetMinPrimary BIT NULL, @PS_MinPrimaryValue INT NULL OUTPUT, @PS_PrimaryFrom INT NULL, @PS_PrimarySearch TINYINT NULL, @PS_PrimaryTo INT NULL, @PS_ProjectCode NVARCHAR (10) NULL, @PS_CentreCodeFrom NVARCHAR (10) NULL, @PS_CentreCodeSearch TINYINT NULL, @PS_CentreCodeTo NVARCHAR (10) NULL, @PS_ResourceCodeFrom NVARCHAR (16) NULL, @PS_ResourceCodeSearch TINYINT NULL, @PS_ResourceCodeTo NVARCHAR (16) NULL, @PS_YearPeriodFrom NVARCHAR (3) NULL, @PS_YearPeriodSearch TINYINT NULL, @PS_YearPeriodTo NVARCHAR (3) NULL, @PS_CreatedDateFrom DATETIME NULL, @PS_CreatedDateSearch TINYINT NULL, @PS_CreatedDateTo DATETIME NULL, @PS_ReferenceFrom NVARCHAR (10) NULL, @PS_ReferenceSearch TINYINT NULL, @PS_ReferenceTo NVARCHAR (10) NULL, @PS_DescriptionFrom NVARCHAR (20) NULL, @PS_DescriptionSearch TINYINT NULL, @PS_DescriptionTo NVARCHAR (20) NULL, @PS_UserChar1From NVARCHAR (20) NULL, @PS_UserChar1Search TINYINT NULL, @PS_UserChar1To NVARCHAR (20) NULL, @PS_UserChar2From NVARCHAR (20) NULL, @PS_UserChar2Search TINYINT NULL, @PS_UserChar2To NVARCHAR (20) NULL, @PS_UserChar3From NVARCHAR (100) NULL, @PS_UserChar3Search TINYINT NULL, @PS_UserChar3To NVARCHAR (100) NULL, @PS_UserChar4From NVARCHAR (100) NULL, @PS_UserChar4Search TINYINT NULL, @PS_UserChar4To NVARCHAR (100) NULL, @PS_UserNum1From FLOAT (53) NULL, @PS_UserNum1Search TINYINT NULL, @PS_UserNum1To FLOAT (53) NULL, @PS_UserNum2From FLOAT (53) NULL, @PS_UserNum2Search TINYINT NULL, @PS_UserNum2To FLOAT (53) NULL, @PS_UserDate1From DATETIME NULL, @PS_UserDate1Search TINYINT NULL, @PS_UserDate1To DATETIME NULL, @PS_UserDate2From DATETIME NULL, @PS_UserDate2Search TINYINT NULL, @PS_UserDate2To DATETIME NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


