CREATE PROCEDURE [dbo].[AA_CST_BATCH_DETAIL_LIST_S]
@PS_UserID VARCHAR (4) NULL, @PS_MaxRecords INT NULL, @PS_CalledFrom INT NULL, @PS_StartValue SQL_VARIANT NULL, @PS_StartPrimary INT NULL, @PS_OrderByDescending TINYINT NULL, @PS_OrderByFieldName [sysname] NULL, @PS_TotalRecordCount INT NULL OUTPUT, @PS_AdvancedResponse TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_GetMinPrimary BIT NULL, @PS_MinPrimaryValue INT NULL OUTPUT, @PS_ProjectCodeFrom VARCHAR (10) NULL, @PS_ProjectCodeSearch TINYINT NULL, @PS_ProjectCodeTo VARCHAR (10) NULL, @PS_ProjectNameFrom VARCHAR (40) NULL, @PS_ProjectNameSearch TINYINT NULL, @PS_ProjectNameTo VARCHAR (40) NULL, @PS_CostCentreCodeFrom VARCHAR (10) NULL, @PS_CostCentreCodeSearch TINYINT NULL, @PS_CostCentreCodeTo VARCHAR (10) NULL, @PS_CostCentreNameFrom VARCHAR (40) NULL, @PS_CostCentreNameSearch TINYINT NULL, @PS_CostCentreNameTo VARCHAR (40) NULL, @PS_ResourceCodeFrom VARCHAR (16) NULL, @PS_ResourceCodeSearch TINYINT NULL, @PS_ResourceCodeTo VARCHAR (16) NULL, @PS_ResourceNameFrom VARCHAR (40) NULL, @PS_ResourceNameSearch TINYINT NULL, @PS_ResourceNameTo VARCHAR (40) NULL, @PS_HeaderReferenceFrom VARCHAR (10) NULL, @PS_HeaderReferenceSearch TINYINT NULL, @PS_HeaderReferenceTo VARCHAR (10) NULL, @PS_BatchReferenceFrom VARCHAR (10) NULL, @PS_BatchReferenceSearch TINYINT NULL, @PS_BatchReferenceTo VARCHAR (10) NULL, @PS_TransactionDateFrom DATETIME NULL, @PS_TransactionDateSearch TINYINT NULL, @PS_TransactionDateTo DATETIME NULL, @PS_YearPeriodFrom VARCHAR (3) NULL, @PS_YearPeriodSearch TINYINT NULL, @PS_YearPeriodTo VARCHAR (3) NULL, @PS_YearWeekFrom VARCHAR (3) NULL, @PS_YearWeekSearch TINYINT NULL, @PS_YearWeekTo VARCHAR (3) NULL, @PS_WeekFrom TINYINT NULL, @PS_WeekSearch TINYINT NULL, @PS_WeekTo TINYINT NULL, @PS_CustomerCodeFrom VARCHAR (10) NULL, @PS_CustomerCodeSearch TINYINT NULL, @PS_CustomerCodeTo VARCHAR (10) NULL, @PS_PeopleCodeFrom VARCHAR (10) NULL, @PS_PeopleCodeSearch TINYINT NULL, @PS_PeopleCodeTo VARCHAR (10) NULL, @PS_DepartmentFrom VARCHAR (20) NULL, @PS_DepartmentSearch TINYINT NULL, @PS_DepartmentTo VARCHAR (20) NULL, @PS_EmployeeCodeFrom VARCHAR (10) NULL, @PS_EmployeeCodeSearch TINYINT NULL, @PS_EmployeeCodeTo VARCHAR (10) NULL, @PS_EnteredByFrom VARCHAR (4) NULL, @PS_EnteredBySearch TINYINT NULL, @PS_EnteredByTo VARCHAR (4) NULL, @PS_TransactionSubTypeFrom VARCHAR (10) NULL, @PS_TransactionSubTypeSearch TINYINT NULL, @PS_TransactionSubTypeTo VARCHAR (10) NULL, @PS_IncludeCostType TINYINT NULL, @PS_IncludeIncomeType TINYINT NULL, @PS_IncludeTimesheetType TINYINT NULL, @PS_IncludeActive TINYINT NULL, @PS_IncludeEstimate TINYINT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


