CREATE PROCEDURE [dbo].[AA_CST_WIP_INV_SALES_ORDER_CANCEL_S]
@PS_ErrorHandlingMethod INT NULL, @PS_UserID NVARCHAR (4) NULL, @PS_Batch_GUID UNIQUEIDENTIFIER NULL OUTPUT, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ClearMode TINYINT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


