CREATE PROCEDURE [dbo].[AA_CST_PROJECT_LIST_S]
@PS_UserID NVARCHAR (4) NULL, @PS_MaxRecords INT NULL, @PS_CalledFrom INT NULL, @PS_StartValue SQL_VARIANT NULL, @PS_StartPrimary INT NULL, @PS_OrderByDescending TINYINT NULL, @PS_OrderByFieldName [sysname] NULL, @PS_TotalRecordCount INT NULL OUTPUT, @PS_AdvancedResponse TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_GetMinPrimary BIT NULL, @PS_MinPrimaryValue INT NULL OUTPUT, @PS_CreatedDateFrom DATETIME NULL, @PS_CreatedDateSearch TINYINT NULL, @PS_CreatedDateTo DATETIME NULL, @PS_ModifiedDateFrom DATETIME NULL, @PS_ModifiedDateSearch TINYINT NULL, @PS_ModifiedDateTo DATETIME NULL, @PS_PrimaryFrom INT NULL, @PS_PrimarySearch TINYINT NULL, @PS_PrimaryTo INT NULL, @PS_CodeFrom NVARCHAR (10) NULL, @PS_CodeSearch TINYINT NULL, @PS_CodeTo NVARCHAR (10) NULL, @PS_NameFrom NVARCHAR (40) NULL, @PS_NameSearch TINYINT NULL, @PS_NameTo NVARCHAR (40) NULL, @PS_IncludeEstimate TINYINT NULL, @PS_IncludeActive TINYINT NULL, @PS_IncludeSuspended TINYINT NULL, @PS_IncludeReopened TINYINT NULL, @PS_IncludeCancelled TINYINT NULL, @PS_IncludeCompleted TINYINT NULL, @PS_IncludeNoLongerUse TINYINT NULL, @PS_CustomerCodeFrom NVARCHAR (10) NULL, @PS_CustomerCodeSearch TINYINT NULL, @PS_CustomerCodeTo NVARCHAR (10) NULL, @PS_CustSortKeyFrom NVARCHAR (20) NULL, @PS_CustSortKeySearch TINYINT NULL, @PS_CustSortKeyTo NVARCHAR (20) NULL, @PS_SortKeyFrom NVARCHAR (20) NULL, @PS_SortKeySearch TINYINT NULL, @PS_SortKeyTo NVARCHAR (20) NULL, @PS_UserField1From NVARCHAR (20) NULL, @PS_UserField1Search TINYINT NULL, @PS_UserField1To NVARCHAR (20) NULL, @PS_UserField2From NVARCHAR (20) NULL, @PS_UserField2Search TINYINT NULL, @PS_UserField2To NVARCHAR (20) NULL, @PS_UserField3From NVARCHAR (20) NULL, @PS_UserField3Search TINYINT NULL, @PS_UserField3To NVARCHAR (20) NULL, @PS_UserField4From NVARCHAR (20) NULL, @PS_UserField4Search TINYINT NULL, @PS_UserField4To NVARCHAR (20) NULL, @PS_UserField5From NVARCHAR (20) NULL, @PS_UserField5Search TINYINT NULL, @PS_UserField5To NVARCHAR (20) NULL, @PS_UserField6From NVARCHAR (20) NULL, @PS_UserField6Search TINYINT NULL, @PS_UserField6To NVARCHAR (20) NULL, @PS_DeadlineDateFrom DATETIME NULL, @PS_DeadlineDateSearch TINYINT NULL, @PS_DeadlineDateTo DATETIME NULL, @PS_RequiredDateFrom DATETIME NULL, @PS_RequiredDateSearch TINYINT NULL, @PS_RequiredDateTo DATETIME NULL, @PS_ProjLeaderFrom NVARCHAR (30) NULL, @PS_ProjLeaderSearch TINYINT NULL, @PS_ProjLeaderTo NVARCHAR (30) NULL, @PS_ProjStructFrom INT NULL, @PS_ProjStructSearch TINYINT NULL, @PS_ProjStructTo INT NULL, @PS_CompletedDateFrom DATETIME NULL, @PS_CompletedDateSearch TINYINT NULL, @PS_CompletedDateTo DATETIME NULL, @PS_NextMilestoneFrom DATETIME NULL, @PS_NextMilestoneSearch TINYINT NULL, @PS_NextMilestoneTo DATETIME NULL, @PS_StartDate DATETIME NULL, @PS_CustomerCode NVARCHAR (10) NULL, @PS_StructurePrimary INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


