CREATE PROCEDURE [dbo].[AA_CST_RESOURCE_RATE_CHANGE_RATE_TEMP_INSERT_S]
@PS_UserId VARCHAR (4) NULL, @PS_BatchGuid UNIQUEIDENTIFIER NULL, @PS_ResourceLink INT NULL, @PS_RateNumber TINYINT NULL, @PS_FieldNumber TINYINT NULL, @PS_Value FLOAT (53) NULL, @PS_Method TINYINT NULL, @PS_Type BIT NULL, @PS_DeleteFlag BIT NULL, @PS_ErrorInstanceId BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod TINYINT NULL, @PS_ObjectGuid UNIQUEIDENTIFIER NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


