CREATE PROCEDURE [dbo].[AA_CST_PROJECT_STRUCTURE_INSERT_EDIT_S]
@PS_DefaultString NVARCHAR (100) NULL, @PS_Mode NVARCHAR (1) NULL, @PS_ValidateOnly BIT NULL, @PS_ErrorHandlingMethod INT NULL, @PS_UserID VARCHAR (4) NULL, @PS_Primary INT NULL OUTPUT, @PS_Code VARCHAR (10) NULL, @PS_Name VARCHAR (40) NULL, @PS_SortKey VARCHAR (20) NULL, @PS_NodesGUID UNIQUEIDENTIFIER NULL, @PS_Source NVARCHAR (1) NULL, @PS_Shared BIT NULL, @PS_Exclude BIT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


