CREATE PROCEDURE [dbo].[AA_CALC_FIFO_FOR_SUB_NON_SERIAL_STOCK_S]
@PS_Stock_Code VARCHAR (25) NULL, @PS_SubAnalysis VARCHAR (25) NULL, @PS_FIFO_Value DECIMAL (24, 8) NULL OUTPUT, @PS_FIFO_Pointer INT NULL OUTPUT, @PS_FIFO_Failed BIT NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


