CREATE PROCEDURE [dbo].[AA_CST_WIP_CORRECT_RELEASED_LIST_S]
@PS_UserID NVARCHAR (4) NULL, @PS_MaxRecords INT NULL, @PS_CalledFrom INT NULL, @PS_StartValue SQL_VARIANT NULL, @PS_StartPrimary INT NULL, @PS_OrderByDescending TINYINT NULL, @PS_OrderByFieldName [sysname] NULL, @PS_TotalRecordCount INT NULL OUTPUT, @PS_AdvancedResponse TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_GetMinPrimary BIT NULL, @PS_MinPrimaryValue INT NULL OUTPUT, @PS_PrimaryFrom INT NULL, @PS_PrimarySearch TINYINT NULL, @PS_PrimaryTo INT NULL, @PS_ProjectCode NVARCHAR (10) NULL, @PS_TransYearPeriodFrom NVARCHAR (3) NULL, @PS_TransYearPeriodSearch TINYINT NULL, @PS_TransYearPeriodTo NVARCHAR (3) NULL, @PS_ReleasedDateFrom DATETIME NULL, @PS_ReleasedDateSearch TINYINT NULL, @PS_ReleasedDateTo DATETIME NULL, @PS_TransReferenceFrom NVARCHAR (10) NULL, @PS_TransReferenceSearch TINYINT NULL, @PS_TransReferenceTo NVARCHAR (10) NULL, @PS_TransDateFrom DATETIME NULL, @PS_TransDateSearch TINYINT NULL, @PS_TransDateTo DATETIME NULL, @PS_TransValueFrom FLOAT (53) NULL, @PS_TransValueSearch TINYINT NULL, @PS_TransValueTo FLOAT (53) NULL, @PS_DescriptionFrom NVARCHAR (20) NULL, @PS_DescriptionSearch TINYINT NULL, @PS_DescriptionTo NVARCHAR (20) NULL, @PS_ReferenceFrom NVARCHAR (10) NULL, @PS_ReferenceSearch TINYINT NULL, @PS_ReferenceTo NVARCHAR (10) NULL, @PS_ReleasedByFrom NVARCHAR (4) NULL, @PS_ReleasedBySearch TINYINT NULL, @PS_ReleasedByTo NVARCHAR (4) NULL, @PS_UserChar1From NVARCHAR (20) NULL, @PS_UserChar1Search TINYINT NULL, @PS_UserChar1To NVARCHAR (20) NULL, @PS_UserChar2From NVARCHAR (20) NULL, @PS_UserChar2Search TINYINT NULL, @PS_UserChar2To NVARCHAR (20) NULL, @PS_UserChar3From NVARCHAR (100) NULL, @PS_UserChar3Search TINYINT NULL, @PS_UserChar3To NVARCHAR (100) NULL, @PS_UserChar4From NVARCHAR (100) NULL, @PS_UserChar4Search TINYINT NULL, @PS_UserChar4To NVARCHAR (100) NULL, @PS_UserNum1From FLOAT (53) NULL, @PS_UserNum1Search TINYINT NULL, @PS_UserNum1To FLOAT (53) NULL, @PS_UserNum2From FLOAT (53) NULL, @PS_UserNum2Search TINYINT NULL, @PS_UserNum2To FLOAT (53) NULL, @PS_UserDate1From DATETIME NULL, @PS_UserDate1Search TINYINT NULL, @PS_UserDate1To DATETIME NULL, @PS_UserDate2From DATETIME NULL, @PS_UserDate2Search TINYINT NULL, @PS_UserDate2To DATETIME NULL, @PS_HeaderPrimaryFrom INT NULL, @PS_HeaderPrimarySearch TINYINT NULL, @PS_HeaderPrimaryTo INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


