CREATE PROCEDURE [dbo].[AA_IR_VALIDATE_APPROVERS_S]
@PS_DefaultString VARCHAR (100) NULL, @PS_UserID VARCHAR (4) NULL, @PS_Type VARCHAR (2) NULL, @PS_Approver_1 VARCHAR (4) NULL OUTPUT, @PS_Approver_2 VARCHAR (4) NULL OUTPUT, @PS_Approver_3 VARCHAR (4) NULL OUTPUT, @PS_PT_INVREG_OVERIDE VARCHAR (4) NULL OUTPUT, @PS_PT_INVREG_STATUS CHAR (1) NULL OUTPUT, @PS_PT_INVREG_APPROVER1 VARCHAR (4) NULL OUTPUT, @PS_PT_INVREG_APPROVER2 VARCHAR (4) NULL OUTPUT, @PS_PT_INVREG_APPROVER3 VARCHAR (4) NULL OUTPUT, @PS_PT_INVREG_APPROVEKEY1 VARCHAR (1) NULL OUTPUT, @PS_PT_INVREG_APPROVEKEY2 VARCHAR (1) NULL OUTPUT, @PS_PT_INVREG_APPROVEKEY3 VARCHAR (1) NULL OUTPUT, @PS_PT_INVREG_APPROVEDATE1 DATETIME NULL OUTPUT, @PS_PT_INVREG_APPROVEDATE2 DATETIME NULL OUTPUT, @PS_PT_INVREG_APPROVEDATE3 DATETIME NULL OUTPUT, @PS_PT_INVREG_MATCHEDUSER VARCHAR (4) NULL OUTPUT, @PS_PT_INVREG_MATCHEDDATE DATETIME NULL OUTPUT, @PS_PT_INVREG_MATCHEDKEY CHAR (1) NULL OUTPUT, @PS_PT_INVREG_APPROVESTATUS VARCHAR (3) NULL OUTPUT, @PS_PT_Type VARCHAR (2) NULL, @PS_SU_IR_APPROVER1 VARCHAR (4) NULL, @PS_SU_IR_APPROVER2 VARCHAR (4) NULL, @PS_SU_IR_APPROVER3 VARCHAR (4) NULL, @PS_SU_IR_APPROVER_GROUP1_LINK INT NULL, @PS_SU_IR_APPROVER_GROUP2_LINK INT NULL, @PS_SU_IR_APPROVER_GROUP3_LINK INT NULL, @PS_INVREG_ROUTE_MASK_PL VARCHAR (10) NULL, @PS_INVREG_ROUTE_MASK_POP VARCHAR (10) NULL, @PS_USER_INVREG_OVERIDE TINYINT NULL OUTPUT, @PS_Mode VARCHAR (1) NULL, @PS_CalledFrom TINYINT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


