CREATE PROCEDURE [dbo].[AA_NL_BALANCE_SHEET_ENQUIRY_S]
@PS_UserID NVARCHAR (4) NULL, @PS_CalledFrom INT NULL, @PS_OrderByDescending TINYINT NULL, @PS_OrderByFieldName [sysname] NULL, @PS_TotalRecordCount INT NULL OUTPUT, @PS_AdvancedResponse TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_GetMinPrimary BIT NULL, @PS_MinPrimaryValue INT NULL OUTPUT, @PS_CatCodeToUse INT NULL, @PS_NodePrimary INT NULL, @PS_DisplayLevel TINYINT NULL, @PS_ExpandAll BIT NULL, @PS_ShowZeroBalance BIT NULL, @PS_InclRelTableDefs TINYINT NULL, @PS_RevisionNumber TINYINT NULL, @PS_HeaderMaxRecords INT NULL, @PS_HeaderStartValue SQL_VARIANT NULL, @PS_HeaderStartPrimary INT NULL, @PS_HeaderOrderByFieldName [sysname] NULL, @PS_CategoryMaxRecords INT NULL, @PS_CategoryStartValue SQL_VARIANT NULL, @PS_CategoryStartPrimary INT NULL, @PS_CategoryOrderByFieldName [sysname] NULL, @PS_DetailMaxRecords INT NULL, @PS_DetailStartValue SQL_VARIANT NULL, @PS_DetailStartPrimary INT NULL, @PS_DetailOrderByFieldName [sysname] NULL, @PS_YearPeriod NVARCHAR (3) NULL, @PS_Currency NVARCHAR (4) NULL, @PS_MajorHeadingCodeFrom TINYINT NULL, @PS_MajorHeadingCodeSearch TINYINT NULL, @PS_MajorHeadingCodeTo TINYINT NULL, @PS_CatCode1From VARCHAR (13) NULL, @PS_CatCode1Search TINYINT NULL, @PS_CatCode1To VARCHAR (13) NULL, @PS_CatCode2From VARCHAR (13) NULL, @PS_CatCode2Search TINYINT NULL, @PS_CatCode2To VARCHAR (13) NULL, @PS_CatCode3From VARCHAR (13) NULL, @PS_CatCode3Search TINYINT NULL, @PS_CatCode3To VARCHAR (13) NULL, @PS_CatCode4From VARCHAR (13) NULL, @PS_CatCode4Search TINYINT NULL, @PS_CatCode4To VARCHAR (13) NULL, @PS_CatCode5From VARCHAR (13) NULL, @PS_CatCode5Search TINYINT NULL, @PS_CatCode5To VARCHAR (13) NULL, @PS_CatCode6From VARCHAR (13) NULL, @PS_CatCode6Search TINYINT NULL, @PS_CatCode6To VARCHAR (13) NULL, @PS_CatCode7From VARCHAR (13) NULL, @PS_CatCode7Search TINYINT NULL, @PS_CatCode7To VARCHAR (13) NULL, @PS_CatCode8From VARCHAR (13) NULL, @PS_CatCode8Search TINYINT NULL, @PS_CatCode8To VARCHAR (13) NULL, @PS_NominalNameFrom VARCHAR (40) NULL, @PS_NominalNameSearch TINYINT NULL, @PS_NominalNameTo VARCHAR (40) NULL, @PS_NominalCodeFrom VARCHAR (25) NULL, @PS_NominalCodeSearch TINYINT NULL, @PS_NominalCodeTo VARCHAR (25) NULL, @PS_LinkPrimary INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


