CREATE PROCEDURE [dbo].[AA_NET_STK_SUBANALYSIS_LIST_S]
@PS_UserID VARCHAR (4) NULL, @PS_MaxRecords INT NULL, @PS_CalledFrom TINYINT NULL, @PS_Type TINYINT NULL, @PS_StartCode VARCHAR (50) NULL, @PS_StartPrimary VARCHAR (50) NULL, @PS_OrderByField TINYINT NULL, @PS_OrderByFieldName VARCHAR (30) NULL OUTPUT, @PS_TotalRecordCount FLOAT (53) NULL OUTPUT, @PS_CreatedDateFrom DATETIME NULL, @PS_CreatedDateSearch TINYINT NULL, @PS_CreatedDateTo DATETIME NULL, @PS_ModifiedDateFrom DATETIME NULL, @PS_ModifiedDateSearch TINYINT NULL, @PS_ModifiedDateTo DATETIME NULL, @PS_ParentCodeFrom VARCHAR (25) NULL, @PS_ParentCodeSearch TINYINT NULL, @PS_ParentCodeTo VARCHAR (25) NULL, @PS_ParentNameFrom VARCHAR (80) NULL, @PS_ParentNameSearch TINYINT NULL, @PS_ParentNameTo VARCHAR (80) NULL, @PS_CodeFrom VARCHAR (25) NULL, @PS_CodeSearch TINYINT NULL, @PS_CodeTo VARCHAR (25) NULL, @PS_NameFrom VARCHAR (40) NULL, @PS_NameSearch TINYINT NULL, @PS_NameTo VARCHAR (40) NULL, @PS_UserField1From VARCHAR (20) NULL, @PS_UserField1Search TINYINT NULL, @PS_UserField1To VARCHAR (20) NULL, @PS_UserField2From VARCHAR (20) NULL, @PS_UserField2Search TINYINT NULL, @PS_UserField2To VARCHAR (20) NULL, @PS_UserField3From VARCHAR (20) NULL, @PS_UserField3Search TINYINT NULL, @PS_UserField3To VARCHAR (20) NULL, @PS_UserField4From VARCHAR (20) NULL, @PS_UserField4Search TINYINT NULL, @PS_UserField4To VARCHAR (20) NULL, @PS_UserField5From VARCHAR (20) NULL, @PS_UserField5Search TINYINT NULL, @PS_UserField5To VARCHAR (20) NULL, @PS_UserField6From VARCHAR (20) NULL, @PS_UserField6Search TINYINT NULL, @PS_UserField6To VARCHAR (20) NULL, @PS_UserDate1From DATETIME NULL, @PS_UserDate1Search TINYINT NULL, @PS_UserDate1To DATETIME NULL, @PS_UserDate2From DATETIME NULL, @PS_UserDate2Search TINYINT NULL, @PS_UserDate2To DATETIME NULL, @PS_UserDate3From DATETIME NULL, @PS_UserDate3Search TINYINT NULL, @PS_UserDate3To DATETIME NULL, @PS_BinNumberFrom VARCHAR (15) NULL, @PS_BinNumberSearch TINYINT NULL, @PS_BinNumberTo VARCHAR (15) NULL, @PS_BelowMinimumQuantity TINYINT NULL, @PS_QuantityNotEqualToZero TINYINT NULL, @PS_ExcludeCompleted TINYINT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


