CREATE PROCEDURE [dbo].[AA_NL_TRANSACTION_OPTIONS_EDIT_S]
@PS_USER_ID VARCHAR (4) NULL, @PS_TRAN_TYPE VARCHAR (4) NULL, @PS_POST_BALANCE_TO_CONTRA BIT NULL, @PS_MULTIPLE_CONTRAS BIT NULL, @PS_ENTER_CURRENCY_AMOUNTS BIT NULL, @PS_ARCHIVE_TRANSACTION BIT NULL, @PS_BATCH_TRANSACTION BIT NULL, @PS_RECURRING_JOURNAL BIT NULL, @PS_BYPASS_COSTING BIT NULL, @PS_CalledFrom INT NULL, @PS_MakeDefaultOptions BIT NULL, @PS_ErrorHandlingMethod TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


