CREATE PROCEDURE [dbo].[AA_NL_ACCOUNT_INSERT_EDIT_S]
@PS_Default_String VARCHAR (70) NULL, @PS_Insert_Flag BIT NULL, @PS_Validate_Only BIT NULL, @PS_User_Id VARCHAR (4) NULL, @PS_Majorhead_Code TINYINT NULL, @PS_Account_Code VARCHAR (25) NULL OUTPUT, @PS_Account_Type CHAR (1) NULL, @PS_Account_Name VARCHAR (40) NULL, @PS_Currency_Code VARCHAR (4) NULL, @PS_Category_1 VARCHAR (6) NULL, @PS_Category_2 VARCHAR (6) NULL, @PS_Category_3 VARCHAR (6) NULL, @PS_Category_4 VARCHAR (6) NULL, @PS_Category_5 VARCHAR (6) NULL, @PS_Category_6 VARCHAR (6) NULL, @PS_Category_7 VARCHAR (6) NULL, @PS_Category_8 VARCHAR (6) NULL, @PS_Year_End_Account VARCHAR (25) NULL, @PS_Profile_Level INT NULL, @PS_Exclude_Transaction BIT NULL, @PS_Exclude_Record BIT NULL, @PS_Centralised BIT NULL, @PS_Compulsory_Cost BIT NULL, @PS_Notes TEXT NULL, @PS_User_Char1 VARCHAR (20) NULL, @PS_User_Char2 VARCHAR (20) NULL, @PS_User_Char5 VARCHAR (20) NULL, @PS_User_Char6 VARCHAR (30) NULL, @PS_User_Char7 VARCHAR (30) NULL, @PS_User_Char8 VARCHAR (30) NULL, @PS_User_Date1 DATETIME NULL, @PS_User_Date2 DATETIME NULL, @PS_User_Date3 DATETIME NULL, @PS_User_Flag1 BIT NULL, @PS_User_Flag2 BIT NULL, @PS_User_Flag3 BIT NULL, @PS_User_Number1 DECIMAL (24, 8) NULL, @PS_User_Number2 DECIMAL (24, 8) NULL, @PS_User_Number3 DECIMAL (24, 8) NULL, @PS_Account_Primary INT NULL OUTPUT, @PS_Source VARCHAR (1) NULL, @PS_ErrorHandlingMethod TINYINT NULL, @PS_InstanceID BIGINT NULL OUTPUT, @PS_ObjectGuid UNIQUEIDENTIFIER NULL, @PS_Allow_Zero_Budgets BIT NULL, @PS_Append_To_Notes TEXT NULL, @PS_Create_Auto_Analysis TINYINT NULL, @PS_LastSaveDateTime DATETIME NULL, @PS_ApplyConcurrencyCheck BIT NULL, @PS_ConcurrentUser VARCHAR (4) NULL OUTPUT, @PS_DuplicationPrimary INT NULL, @PS_User_Char3 VARCHAR (100) NULL, @PS_User_Char4 VARCHAR (100) NULL, @PS_Overdraft DECIMAL (24, 8) NULL, @PS_ExcludeFromLists BIT NULL, @PS_AccountForCarbonEmissions BIT NULL, @PS_EmissionsGroupCode CHAR (2) NULL, @PS_ClassificationCode CHAR (4) NULL, @PS_EmissionsGroupLink INT NULL, @PS_ClassificationLink INT NULL, @PS_UpdateProfileChild BIT NULL, @PS_ChildClassWarning BIT NULL OUTPUT, @PS_DefaultCostCentre VARCHAR (10) NULL, @PS_ReportingCode SMALLINT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


