CREATE PROCEDURE [dbo].[AA_NL_PROFIT_LOSS_CAT_S]
@PS_UserID NVARCHAR (4) NULL, @PS_MaxRecords INT NULL, @PS_CalledFrom INT NULL, @PS_StartValue SQL_VARIANT NULL, @PS_StartPrimary INT NULL, @PS_OrderByDescending TINYINT NULL, @PS_OrderByFieldName [sysname] NULL, @PS_TotalRecordCount INT NULL OUTPUT, @PS_AdvancedResponse TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_GetMinPrimary BIT NULL, @PS_MinPrimaryValue INT NULL OUTPUT, @PS_CatCodeToUse INT NULL, @PS_DisplayLevel INT NULL, @PS_ExpandAll INT NULL, @PS_ShowZeroBalance BIT NULL, @PS_NodePrimary INT NULL, @PS_RevisionNumber TINYINT NULL, @PS_SQLOnly BIT NULL, @PS_SQLStatement NVARCHAR (4000) NULL OUTPUT, @PS_YearPeriodFrom NVARCHAR (3) NULL, @PS_YearPeriodSearch TINYINT NULL, @PS_YearPeriodTo NVARCHAR (3) NULL, @PS_CatCode1From NVARCHAR (6) NULL, @PS_CatCode1Search TINYINT NULL, @PS_CatCode1To NVARCHAR (6) NULL, @PS_CatCode2From NVARCHAR (6) NULL, @PS_CatCode2Search TINYINT NULL, @PS_CatCode2To NVARCHAR (6) NULL, @PS_CatCode3From NVARCHAR (6) NULL, @PS_CatCode3Search TINYINT NULL, @PS_CatCode3To NVARCHAR (6) NULL, @PS_CatCode4From NVARCHAR (6) NULL, @PS_CatCode4Search TINYINT NULL, @PS_CatCode4To NVARCHAR (6) NULL, @PS_CatCode5From NVARCHAR (6) NULL, @PS_CatCode5Search TINYINT NULL, @PS_CatCode5To NVARCHAR (6) NULL, @PS_CatCode6From NVARCHAR (6) NULL, @PS_CatCode6Search TINYINT NULL, @PS_CatCode6To NVARCHAR (6) NULL, @PS_CatCode7From NVARCHAR (6) NULL, @PS_CatCode7Search TINYINT NULL, @PS_CatCode7To NVARCHAR (6) NULL, @PS_CatCode8From NVARCHAR (6) NULL, @PS_CatCode8Search TINYINT NULL, @PS_CatCode8To NVARCHAR (6) NULL, @PS_MajorHeadingCodeFrom TINYINT NULL, @PS_MajorHeadingCodeSearch TINYINT NULL, @PS_MajorHeadingCodeTo TINYINT NULL, @PS_CurrencyFrom NVARCHAR (4) NULL, @PS_CurrencySearch TINYINT NULL, @PS_CurrencyTo NVARCHAR (4) NULL, @PS_NominalNameFrom NVARCHAR (40) NULL, @PS_NominalNameSearch TINYINT NULL, @PS_NominalNameTo NVARCHAR (40) NULL, @PS_NominalCodeFrom NVARCHAR (25) NULL, @PS_NominalCodeSearch TINYINT NULL, @PS_NominalCodeTo NVARCHAR (25) NULL, @PS_LinkPrimaryFrom INT NULL, @PS_LinkPrimarySearch TINYINT NULL, @PS_LinkPrimaryTo INT NULL, @PS_PrimaryFrom INT NULL, @PS_PrimarySearch TINYINT NULL, @PS_PrimaryTo INT NULL, @PS_HeaderSQLStatement NVARCHAR (1000) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


