CREATE PROCEDURE [dbo].[AA_NL_MJHEADING_DEFAULTS_S]
@PS_Code TINYINT NULL, @PS_Name VARCHAR (40) NULL OUTPUT, @PS_Type VARCHAR (1) NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


