CREATE PROCEDURE [dbo].[AA_NL_ADVANCED_CHART_OF_ACCOUNTS_INSERT_EDIT_S]
@PS_DefaultString VARCHAR (100) NULL, @PS_Mode VARCHAR (1) NULL, @PS_ValidateOnly BIT NULL, @PS_UserId VARCHAR (4) NULL, @PS_CurrencySymbol VARCHAR (4) NULL OUTPUT, @PS_Level1CategoryCode VARCHAR (6) NULL, @PS_Level2CategoryCode VARCHAR (6) NULL, @PS_Level3CategoryCode VARCHAR (6) NULL, @PS_Level4CategoryCode VARCHAR (6) NULL, @PS_Level5CategoryCode VARCHAR (6) NULL, @PS_Level6CategoryCode VARCHAR (6) NULL, @PS_Level7CategoryCode VARCHAR (6) NULL, @PS_Level8CategoryCode VARCHAR (6) NULL, @PS_AbsolutePositionInCOA INT NULL, @PS_PositionWithinBranch INT NULL, @PS_BuildNominal TINYINT NULL OUTPUT, @PS_NominalName VARCHAR (40) NULL OUTPUT, @PS_CreateSalesAnalysis BIT NULL OUTPUT, @PS_CreateSalesStockAnalysis BIT NULL OUTPUT, @PS_CreateSalesDiscountAnalysis BIT NULL OUTPUT, @PS_CreateSalesBankAnalysis BIT NULL OUTPUT, @PS_CreatePurchaseAnalysis BIT NULL OUTPUT, @PS_CreatePurchaseStockAnalysis BIT NULL OUTPUT, @PS_CreatePurchaseDiscountAnalysis BIT NULL OUTPUT, @PS_CreatePurchaseBankAnalysis BIT NULL OUTPUT, @PS_SalesAnalysisDescription VARCHAR (40) NULL OUTPUT, @PS_PurchaseAnalysisDescription VARCHAR (40) NULL OUTPUT, @PS_AnalysisSalesControlAccount VARCHAR (25) NULL OUTPUT, @PS_AnalysisPurchaseControlAccount VARCHAR (25) NULL OUTPUT, @PS_AnalysisVatControlAccount VARCHAR (25) NULL OUTPUT, @PS_AnalysisStockControlAccount VARCHAR (25) NULL OUTPUT, @PS_DefaultSales BIT NULL, @PS_DefaultSalesDiscount BIT NULL, @PS_DefaultPurchase BIT NULL, @PS_DefaultPurchaseDiscount BIT NULL, @PS_DefaultCostOfSalesLabour BIT NULL, @PS_DefaultWriteOffMaterials BIT NULL, @PS_DefaultExchangeDifference BIT NULL, @PS_DefaultSalesControl BIT NULL, @PS_DefaultBank BIT NULL, @PS_DefaultPurchaseControl BIT NULL, @PS_DefaultYearEnd BIT NULL, @PS_DefaultCurrencyRounding BIT NULL, @PS_DefaultVatControl BIT NULL, @PS_DefaultSuspense BIT NULL, @PS_DefaultAccruedIncome BIT NULL, @PS_DefaultCostOfGoodsSold BIT NULL, @PS_DefaultStockAdjustments BIT NULL, @PS_DefaultGoodsReceivedNotInvoiced BIT NULL, @PS_DefaultStockControl BIT NULL, @PS_DefaultStockAdjustmentsBS BIT NULL, @PS_DefaultAccruedIncomeBS BIT NULL, @PS_Source VARCHAR (1) NULL OUTPUT, @PS_COA_Primary INT NULL OUTPUT, @PS_NominalPrimary INT NULL OUTPUT, @PS_NominalCode VARCHAR (25) NULL OUTPUT, @PS_YearEndCode VARCHAR (25) NULL OUTPUT, @PS_Cat1Code VARCHAR (6) NULL OUTPUT, @PS_Cat2Code VARCHAR (6) NULL OUTPUT, @PS_Cat3Code VARCHAR (6) NULL OUTPUT, @PS_Cat4Code VARCHAR (6) NULL OUTPUT, @PS_Cat5Code VARCHAR (6) NULL OUTPUT, @PS_Cat6Code VARCHAR (6) NULL OUTPUT, @PS_Cat7Code VARCHAR (6) NULL OUTPUT, @PS_Cat8Code VARCHAR (6) NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


