CREATE PROCEDURE [dbo].[AA_ORDER_DOC_HEADER_INSERT_S]
@PS_DOH_ORDER_LINK INT NULL, @PS_DOH_PRIMARY INT NULL OUTPUT, @PS_DOH_USER_ID VARCHAR (4) NULL, @PS_DOH_DOC_TYPE VARCHAR (3) NULL, @PS_DOH_DOC_DATE DATETIME NULL, @PS_DOH_DOC_DUEDATE DATETIME NULL, @PS_DOH_VAT_CODE1 VARCHAR (4) NULL, @PS_DOH_VAT_CODE2 VARCHAR (4) NULL, @PS_DOH_VAT_CODE3 VARCHAR (4) NULL, @PS_DOH_VAT_CODE4 VARCHAR (4) NULL, @PS_DOH_VAT_CODE5 VARCHAR (4) NULL, @PS_DOH_VAT_NET1 DECIMAL (24, 8) NULL, @PS_DOH_VAT_NET2 DECIMAL (24, 8) NULL, @PS_DOH_VAT_NET3 DECIMAL (24, 8) NULL, @PS_DOH_VAT_NET4 DECIMAL (24, 8) NULL, @PS_DOH_VAT_NET5 DECIMAL (24, 8) NULL, @PS_DOH_VAT_VALUE1 DECIMAL (24, 8) NULL, @PS_DOH_VAT_VALUE2 DECIMAL (24, 8) NULL, @PS_DOH_VAT_VALUE3 DECIMAL (24, 8) NULL, @PS_DOH_VAT_VALUE4 DECIMAL (24, 8) NULL, @PS_DOH_VAT_VALUE5 DECIMAL (24, 8) NULL, @PS_DOH_EXTRA_ADDRESS VARCHAR (250) NULL, @PS_DOH_DOC_NUMBER VARCHAR (10) NULL, @PS_DOH_SYS_LINK TINYINT NULL, @PS_DOH_OPTION1 VARCHAR (3) NULL, @PS_DOH_OPTION2 VARCHAR (3) NULL, @PS_Error_Number INT NULL OUTPUT, @PS_DOH_FAX_HEADER VARCHAR (1000) NULL, @PS_DOH_COMP_ADDRESS VARCHAR (1000) NULL, @PS_LanguageCode VARCHAR (10) NULL, @PS_DOH_ORDER_NOTES VARCHAR (MAX) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


