CREATE PROCEDURE [dbo].[AA_ORDER_DOC_DETAIL_INSERT_S]
@PS_DOD_HEADER_LINK INT NULL, @PS_DOD_ORDER_LINK INT NULL, @PS_DOD_PRIMARY INT NULL OUTPUT, @PS_DOD_USER_ID VARCHAR (4) NULL, @PS_DOD_QUANTITY DECIMAL (24, 8) NULL, @PS_DOD_QUANTITY_OS DECIMAL (24, 8) NULL, @PS_DOD_NET_BASE1 DECIMAL (24, 8) NULL, @PS_DOD_NET_BASE2 DECIMAL (24, 8) NULL, @PS_DOD_NET_FOREIGN DECIMAL (24, 8) NULL, @PS_DOD_NET_DOC DECIMAL (24, 8) NULL, @PS_DOD_VAT_BASE1 DECIMAL (24, 8) NULL, @PS_DOD_VAT_BASE2 DECIMAL (24, 8) NULL, @PS_DOD_VAT_FOREIGN DECIMAL (24, 8) NULL, @PS_DOD_VAT_DOC DECIMAL (24, 8) NULL, @PS_DOD_LINEDISC_BASE1 DECIMAL (24, 8) NULL, @PS_DOD_LINEDISC_BASE2 DECIMAL (24, 8) NULL, @PS_DOD_LINEDISC_FOREIGN DECIMAL (24, 8) NULL, @PS_DOD_LINEDISC_DOC DECIMAL (24, 8) NULL, @PS_DOD_TOTDISC_BASE1 DECIMAL (24, 8) NULL, @PS_DOD_TOTDISC_BASE2 DECIMAL (24, 8) NULL, @PS_DOD_TOTDISC_FOREIGN DECIMAL (24, 8) NULL, @PS_DOD_TOTDISC_DOC DECIMAL (24, 8) NULL, @PS_DOD_BIN_NUMBER VARCHAR (15) NULL, @PS_DOD_SUB_GROUP VARCHAR (90) NULL, @PS_DOD_UNITCST_BASE1 DECIMAL (24, 8) NULL, @PS_DOD_UNITCST_BASE2 DECIMAL (24, 8) NULL, @PS_DOD_UNITCST_FOREIGN DECIMAL (24, 8) NULL, @PS_DOD_UNITCST_DOC DECIMAL (24, 8) NULL, @PS_Error_Number INT NULL OUTPUT, @PS_DOD_SERIAL_NO VARCHAR (4000) NULL, @PS_DOD_SUBANALYSIS VARCHAR (25) NULL, @PS_DOD_REVERSE_VAT_BASE1 DECIMAL (24, 8) NULL, @PS_DOD_REVERSE_VAT_BASE2 DECIMAL (24, 8) NULL, @PS_DOD_REVERSE_VAT_FOREIGN DECIMAL (24, 8) NULL, @PS_DOD_REVERSE_VAT_DOC DECIMAL (24, 8) NULL, @PS_DOD_MOVEMENT_DETAIL_TEXT VARCHAR (240) NULL, @PS_DOD_EC_TYPE VARCHAR (1) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


