CREATE PROCEDURE [dbo].[AA_POP_STK_MOVEMENT_INSERT_S]
@PS_Stock_Code VARCHAR (25) NULL, @PS_Serial_Number VARCHAR (40) NULL OUTPUT, @PS_Sub_Analysis_Code VARCHAR (25) NULL, @PS_Quantity_To_Deliver DECIMAL (24, 8) NULL OUTPUT, @PS_Batch_Detail_Inv_Quantity DECIMAL (24, 8) NULL, @PS_Batch_Detail_Net DECIMAL (24, 8) NULL, @PS_Batch_Detail_Net_Curr DECIMAL (24, 8) NULL, @PS_Header_Transaction_Type CHAR (1) NULL, @PS_Header_Description VARCHAR (30) NULL, @PS_Header_Account_Code VARCHAR (10) NULL, @PS_Header_Currency_Symbol VARCHAR (4) NULL, @PS_Header_Last_Used_Del_Note INT NULL, @PS_Detail_Net_Value DECIMAL (24, 8) NULL, @PS_Detail_Net_Value_Curr DECIMAL (24, 8) NULL, @PS_Detail_Quantity_Unit DECIMAL (24, 8) NULL, @PS_Detail_Quantity_Ordered DECIMAL (24, 8) NULL, @PS_Detail_Quantity_Reserved DECIMAL (24, 8) NULL OUTPUT, @PS_Detail_Unit_Cost_Home DECIMAL (24, 8) NULL, @PS_Detail_Unit_Cost_Curr DECIMAL (24, 8) NULL, @PS_Detail_Unit_Cost_Base2 DECIMAL (24, 8) NULL, @PS_Detail_Line_Discount_Percent DECIMAL (24, 8) NULL, @PS_Detail_Total_Disc_Value DECIMAL (24, 8) NULL, @PS_Detail_Total_Disc_Curr_Value DECIMAL (24, 8) NULL, @PS_Detail_Required_Date DATETIME NULL, @PS_Detail_CostHeader VARCHAR (10) NULL, @PS_Detail_CostCentre VARCHAR (10) NULL, @PS_Detail_Information VARCHAR (240) NULL, @PS_Detail_Table_Code VARCHAR (3) NULL, @PS_Detail_PrimaryKey INT NULL, @PS_Stock_Negative_Values TINYINT NULL, @PS_Post_Origin TINYINT NULL, @PS_User_ID VARCHAR (4) NULL, @PS_Order_Number VARCHAR (10) NULL, @PS_Delivery_Year CHAR (1) NULL, @PS_Delivery_Period TINYINT NULL, @PS_Delivery_Date DATETIME NULL, @PS_Update_Stock_Price TINYINT NULL, @PS_Batched_Transaction TINYINT NULL, @PS_Archive_Transaction TINYINT NULL, @PS_Detail_Net_Base2 DECIMAL (24, 8) NULL, @PS_Detail_Total_Disc_Base2_Value DECIMAL (24, 8) NULL, @PS_Base2_Rate DECIMAL (24, 8) NULL, @PS_Detail_Quantity_Delivered DECIMAL (24, 8) NULL, @PS_Blank_Field VARCHAR (20) NULL OUTPUT, @PS_Update_Fixed BIT NULL, @PS_Source VARCHAR (1) NULL, @PS_Originally_Empty_Location TINYINT NULL, @PS_Primary INT NULL OUTPUT, @PS_Serial_Link INT NULL, @PS_Total_Discount_Percentage DECIMAL (16, 2) NULL, @PS_Line_Discount_Value DECIMAL (24, 8) NULL, @PS_Line_Discount_Curr_Value DECIMAL (24, 8) NULL, @PS_MovementValue DECIMAL (24, 8) NULL OUTPUT, @PS_MovementCurrencyValue DECIMAL (24, 8) NULL OUTPUT, @PS_MovementBase2Value DECIMAL (24, 8) NULL OUTPUT, @PS_MovementCostPrice DECIMAL (24, 8) NULL OUTPUT, @PS_MovementCurrencyCostPrice DECIMAL (24, 8) NULL OUTPUT, @PS_MovementBase2CostPrice DECIMAL (24, 8) NULL OUTPUT, @PS_Revalue_Currency TINYINT NULL, @PS_Currency_Rate DECIMAL (16, 6) NULL, @PS_POP_StockAnalysis VARCHAR (25) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


