CREATE PROCEDURE [dbo].[AA_PL_TRANSACTION_OPTIONS_EDIT_S]
@PS_USER_ID VARCHAR (4) NULL, @PS_TRAN_TYPE VARCHAR (3) NULL, @PS_MAKE_PAYMENT_NOW BIT NULL, @PS_ALLOCATE_TRANSACTION_NOW BIT NULL, @PS_ENTER_GROSS_CURRENCY_AMOUNTS BIT NULL, @PS_ARCHIVE_TRANSACTION BIT NULL, @PS_BATCH_TRANSACTION BIT NULL, @PS_ENTER_DUE_DATE_AND_RECEIPT_DATE BIT NULL, @PS_REMEMBER_SUPPLIER_DETAILS BIT NULL, @PS_PUT_INVOICES_ON_DISPUTE BIT NULL, @PS_BYPASS_COSTING BIT NULL, @PS_CalledFrom INT NULL, @PS_MakeDefaultOptions BIT NULL, @PS_ErrorHandlingMethod TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


