CREATE PROCEDURE [dbo].[AA_POP_ORDER_DELETE_S]
@PS_Validate_Only BIT NULL, @PS_User_Id VARCHAR (4) NULL, @PS_Order_Number VARCHAR (10) NULL, @PS_Primary INT NULL, @PS_Warn_Override BIT NULL, @PS_Warn_Message VARCHAR (3000) NULL OUTPUT, @PS_Source VARCHAR (1) NULL, @PS_ErrorHandlingMethod TINYINT NULL, @PS_InstanceID BIGINT NULL OUTPUT, @PS_ObjectGuid UNIQUEIDENTIFIER NULL, @PS_POH_STATUS TINYINT NULL, @PS_POH_TYPE VARCHAR (1) NULL, @PS_POH_ARCHIVE TINYINT NULL, @PS_POH_MU_STATUS VARCHAR (1) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


