CREATE PROCEDURE [dbo].[AA_PLTRN_EDIT_CHECK_ACCOUNT_S]
@PS_DefaultString VARCHAR (15) NULL, @PS_SuppCode VARCHAR (10) NULL, @PS_Def_EC_Terms VARCHAR (3) NULL, @PS_Def_EC_Nature VARCHAR (2) NULL, @PS_Def_EC_Mode VARCHAR (2) NULL, @PS_Def_Delivery_Address_No INT NULL, @PS_Def_Invoice_Address_No INT NULL, @PS_Def_Line_Discount DECIMAL (16, 2) NULL, @PS_Def_Total_Discount DECIMAL (16, 2) NULL, @PS_Def_Settlement_Disc1 DECIMAL (16, 2) NULL, @PS_Def_Settlement_Disc2 DECIMAL (16, 2) NULL, @PS_Def_Settlement_Days1 INT NULL, @PS_Def_Settlement_Days2 INT NULL, @PS_Def_PriceKey TINYINT NULL, @PS_Def_Delivery_Charge DECIMAL (24, 8) NULL, @PS_Def_Delivery_Charge_Pcnt DECIMAL (16, 2) NULL, @PS_Def_Delivery_Method VARCHAR (20) NULL, @PS_Def_Order_Terms VARCHAR (40) NULL, @PS_Def_Minimum_Order_Val DECIMAL (24, 8) NULL, @PS_Def_A_P_Days INT NULL, @PS_Def_Due_Days INT NULL, @PS_Def_User_Sort1 VARCHAR (20) NULL, @PS_Def_User_Sort2 VARCHAR (20) NULL, @PS_Def_User_Sort3 VARCHAR (20) NULL, @PS_Def_Delivery_Address_Type VARCHAR (2) NULL, @PS_EC_Terms VARCHAR (3) NULL OUTPUT, @PS_EC_Nature VARCHAR (2) NULL OUTPUT, @PS_EC_Mode VARCHAR (2) NULL OUTPUT, @PS_Delivery_Address_No INT NULL OUTPUT, @PS_Invoice_Address_No INT NULL OUTPUT, @PS_Line_Discount DECIMAL (16, 2) NULL OUTPUT, @PS_Total_Discount DECIMAL (16, 2) NULL OUTPUT, @PS_Settlement_Disc1 DECIMAL (16, 2) NULL OUTPUT, @PS_Settlement_Disc2 DECIMAL (16, 2) NULL OUTPUT, @PS_Settlement_Days1 INT NULL OUTPUT, @PS_Settlement_Days2 INT NULL OUTPUT, @PS_PriceKey TINYINT NULL OUTPUT, @PS_Delivery_Charge DECIMAL (24, 8) NULL OUTPUT, @PS_Delivery_Charge_Pcnt DECIMAL (16, 2) NULL OUTPUT, @PS_Delivery_Method VARCHAR (20) NULL OUTPUT, @PS_Order_Terms VARCHAR (40) NULL OUTPUT, @PS_Minimum_Order_Val DECIMAL (24, 8) NULL OUTPUT, @PS_A_P_Days INT NULL OUTPUT, @PS_Due_Days INT NULL OUTPUT, @PS_User_Sort1 VARCHAR (20) NULL OUTPUT, @PS_User_Sort2 VARCHAR (20) NULL OUTPUT, @PS_User_Sort3 VARCHAR (20) NULL OUTPUT, @PS_Delivery_Address_Type VARCHAR (2) NULL OUTPUT, @PS_Vat_Registration_No VARCHAR (21) NULL OUTPUT, @PS_User_Id VARCHAR (4) NULL, @PS_VAT_Status VARCHAR (1) NULL, @PS_Transaction_Type VARCHAR (3) NULL, @PS_SupplierCIS BIT NULL OUTPUT, @PS_CIS_Business_Type TINYINT NULL OUTPUT, @PS_SubContractorInactive BIT NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


