CREATE PROCEDURE [dbo].[AA_PL_ADDRESS_LIST_S]
@PS_UserID NVARCHAR (4) NULL, @PS_MaxRecords INT NULL, @PS_CalledFrom INT NULL, @PS_StartValue SQL_VARIANT NULL, @PS_StartPrimary INT NULL, @PS_OrderByDescending TINYINT NULL, @PS_OrderByFieldName [sysname] NULL OUTPUT, @PS_TotalRecordCount INT NULL OUTPUT, @PS_AdvancedResponse TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_GetMinPrimary BIT NULL, @PS_MinPrimaryValue INT NULL OUTPUT, @PS_CreatedDateFrom DATETIME NULL, @PS_CreatedDateSearch TINYINT NULL, @PS_CreatedDateTo DATETIME NULL, @PS_ModifiedDateFrom DATETIME NULL, @PS_ModifiedDateSearch TINYINT NULL, @PS_ModifiedDateTo DATETIME NULL, @PS_PrimaryFrom INT NULL, @PS_PrimarySearch TINYINT NULL, @PS_PrimaryTo INT NULL, @PS_SupplierCodeFrom NVARCHAR (10) NULL, @PS_SupplierCodeSearch TINYINT NULL, @PS_SupplierCodeTo NVARCHAR (10) NULL, @PS_AddressNoFrom INT NULL, @PS_AddressNoSearch TINYINT NULL, @PS_AddressNoTo INT NULL, @PS_IncludeNotUsed TINYINT NULL, @PS_IncludeOrderDefault TINYINT NULL, @PS_IncludeNonOrderDefault TINYINT NULL, @PS_IncludeDeliveryDefault TINYINT NULL, @PS_IncludeNonDeliveryDefault TINYINT NULL, @PS_IncludeStatement TINYINT NULL, @PS_IncludeNonStatement TINYINT NULL, @PS_IncludeRemittance TINYINT NULL, @PS_IncludeNonRemittance TINYINT NULL, @PS_IncludeDeliveryAddress TINYINT NULL, @PS_ContactFrom NVARCHAR (30) NULL, @PS_ContactSearch TINYINT NULL, @PS_ContactTo NVARCHAR (30) NULL, @PS_AddressFrom NVARCHAR (160) NULL, @PS_AddressSearch TINYINT NULL, @PS_AddressTo NVARCHAR (160) NULL, @PS_TownFrom NVARCHAR (30) NULL, @PS_TownSearch TINYINT NULL, @PS_TownTo NVARCHAR (30) NULL, @PS_CountyFrom NVARCHAR (30) NULL, @PS_CountySearch TINYINT NULL, @PS_CountyTo NVARCHAR (30) NULL, @PS_PostcodeFrom NVARCHAR (12) NULL, @PS_PostcodeSearch TINYINT NULL, @PS_PostcodeTo NVARCHAR (12) NULL, @PS_CountryFrom NVARCHAR (35) NULL, @PS_CountrySearch TINYINT NULL, @PS_CountryTo NVARCHAR (35) NULL, @PS_PhoneFrom NVARCHAR (20) NULL, @PS_PhoneSearch TINYINT NULL, @PS_PhoneTo NVARCHAR (20) NULL, @PS_FaxFrom NVARCHAR (20) NULL, @PS_FaxSearch TINYINT NULL, @PS_FaxTo NVARCHAR (20) NULL, @PS_EMailFrom NVARCHAR (64) NULL, @PS_EMailSearch TINYINT NULL, @PS_EMailTo NVARCHAR (64) NULL, @PS_CCEMailFrom NVARCHAR (64) NULL, @PS_CCEMailSearch TINYINT NULL, @PS_CCEMailTo NVARCHAR (64) NULL, @PS_AnalysisFrom NVARCHAR (25) NULL, @PS_AnalysisSearch TINYINT NULL, @PS_AnalysisTo NVARCHAR (25) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


