CREATE PROCEDURE [dbo].[AA_POP_PRINT_ORDER_S]
@PS_Header_Link INT NULL, @PS_Order_Primary INT NULL, @PS_VALIDATE_ONLY BIT NULL, @PS_USER_ID VARCHAR (4) NULL, @PS_Quantity DECIMAL (24, 8) NULL, @PS_Quantity_OutStanding DECIMAL (24, 8) NULL, @PS_UNITCST_BASE1 DECIMAL (24, 8) NULL, @PS_UNITCST_BASE2 DECIMAL (24, 8) NULL, @PS_UNITCST_FOREIGN DECIMAL (24, 8) NULL, @PS_LINEDISC_BASE1 DECIMAL (24, 8) NULL, @PS_LINEDISC_BASE2 DECIMAL (24, 8) NULL, @PS_LINEDISC_FOREIGN DECIMAL (24, 8) NULL, @PS_NET_BASE1 DECIMAL (24, 8) NULL, @PS_NET_BASE2 DECIMAL (24, 8) NULL, @PS_NET_FOREIGN DECIMAL (24, 8) NULL, @PS_VAT_BASE1 DECIMAL (24, 8) NULL, @PS_VAT_BASE2 DECIMAL (24, 8) NULL, @PS_VAT_FOREIGN DECIMAL (24, 8) NULL, @PS_TOTDISC_BASE1 DECIMAL (24, 8) NULL, @PS_TOTDISC_BASE2 DECIMAL (24, 8) NULL, @PS_TOTDISC_FOREIGN DECIMAL (24, 8) NULL, @PS_Currency_Symbol VARCHAR (4) NULL, @PS_Error_Number INT NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


