CREATE PROCEDURE [dbo].[AA_PL_STATEMENTS_GET_DEST_TABLE_S]
@PS_ErrorHandlingMethod INT NULL, @PS_UserID VARCHAR (4) NULL, @PS_Batch_GUID UNIQUEIDENTIFIER NULL OUTPUT, @PS_ErrorInstanceID BIGINT NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


