CREATE PROCEDURE [dbo].[AA_POP_POST_INV_VAT_ROUNDING_S]
@PS_PT_PRIMARY INT NULL, @PS_User_Id VARCHAR (4) NULL, @PS_DET_VAT DECIMAL (24, 8) NULL, @PS_DET_CURR_TAX DECIMAL (24, 8) NULL, @PS_DET_VAT_BASE2 DECIMAL (24, 8) NULL, @PS_DET_PL_ACQ_TAX DECIMAL (24, 8) NULL, @PS_DET_PL_ACQ_TAX_C DECIMAL (24, 8) NULL, @PS_DET_PL_ACQUISTN_BASE2 DECIMAL (24, 8) NULL, @PS_VATcode VARCHAR (4) NULL, @PS_SubLedgerCode VARCHAR (10) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


