CREATE PROCEDURE [dbo].[AA_REP_NL_TRIAL_BALANCE_SEARCH_S]
@PS_UserID NVARCHAR (4) NULL, @PS_CalledFrom INT NULL, @PS_PrimarySortFieldName [sysname] NULL, @PS_PrimaryOrderByDesc BIT NULL, @PS_TotalRecordCount INT NULL OUTPUT, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_ViewName [sysname] NULL, @PS_Source NVARCHAR (1) NULL, @PS_OrderByFieldName1 [sysname] NULL, @PS_OrderByDescending1 TINYINT NULL, @PS_OrderByFieldName2 [sysname] NULL, @PS_OrderByDescending2 TINYINT NULL, @PS_OrderByFieldName3 [sysname] NULL, @PS_OrderByDescending3 TINYINT NULL, @PS_OrderByFieldName4 [sysname] NULL, @PS_OrderByDescending4 TINYINT NULL, @PS_OrderByFieldName5 [sysname] NULL, @PS_OrderByDescending5 TINYINT NULL, @PS_OrderByFieldName6 [sysname] NULL, @PS_OrderByDescending6 TINYINT NULL, @PS_OrderByFieldName7 [sysname] NULL, @PS_OrderByDescending7 TINYINT NULL, @PS_OrderByFieldName8 [sysname] NULL, @PS_OrderByDescending8 TINYINT NULL, @PS_OrderByFieldName9 [sysname] NULL, @PS_OrderByDescending9 TINYINT NULL, @PS_AccountCodeFrom NVARCHAR (25) NULL, @PS_AccountCodeSearch TINYINT NULL, @PS_AccountCodeTo NVARCHAR (25) NULL, @PS_AccountNameFrom NVARCHAR (40) NULL, @PS_AccountNameSearch TINYINT NULL, @PS_AccountNameTo NVARCHAR (40) NULL, @PS_MajorHeadingFrom TINYINT NULL, @PS_MajorHeadingSearch TINYINT NULL, @PS_MajorHeadingTo TINYINT NULL, @PS_CurrencyCode NVARCHAR (4) NULL, @PS_Category1From NVARCHAR (6) NULL, @PS_Category1Search TINYINT NULL, @PS_Category1To NVARCHAR (6) NULL, @PS_Category2From NVARCHAR (6) NULL, @PS_Category2Search TINYINT NULL, @PS_Category2To NVARCHAR (6) NULL, @PS_Category3From NVARCHAR (6) NULL, @PS_Category3Search TINYINT NULL, @PS_Category3To NVARCHAR (6) NULL, @PS_Category4From NVARCHAR (6) NULL, @PS_Category4Search TINYINT NULL, @PS_Category4To NVARCHAR (6) NULL, @PS_Category5From NVARCHAR (6) NULL, @PS_Category5Search TINYINT NULL, @PS_Category5To NVARCHAR (6) NULL, @PS_Category6From NVARCHAR (6) NULL, @PS_Category6Search TINYINT NULL, @PS_Category6To NVARCHAR (6) NULL, @PS_Category7From NVARCHAR (6) NULL, @PS_Category7Search TINYINT NULL, @PS_Category7To NVARCHAR (6) NULL, @PS_Category8From NVARCHAR (6) NULL, @PS_Category8Search TINYINT NULL, @PS_Category8To NVARCHAR (6) NULL, @PS_YearPeriod NVARCHAR (3) NULL, @PS_IncludeBudgetFigures BIT NULL, @PS_IncludeZeroBalances BIT NULL, @PS_IncludeCommittedCosts BIT NULL, @PS_CurrencyReport BIT NULL, @PS_RevaluationSymbol VARCHAR (4) NULL, @PS_RevaluationRate DECIMAL (24, 8) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


