CREATE PROCEDURE [dbo].[AA_REP_NL_PROFIT_LOSS_PERIOD_SEARCH_S]
@PS_UserID NVARCHAR (4) NULL, @PS_CalledFrom INT NULL, @PS_PrimarySortFieldName [sysname] NULL, @PS_PrimaryOrderByDesc BIT NULL, @PS_TotalRecordCount INT NULL OUTPUT, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_ViewName [sysname] NULL, @PS_OrderByFieldName1 [sysname] NULL, @PS_OrderByDescending1 TINYINT NULL, @PS_OrderByFieldName2 [sysname] NULL, @PS_OrderByDescending2 TINYINT NULL, @PS_OrderByFieldName3 [sysname] NULL, @PS_OrderByDescending3 TINYINT NULL, @PS_OrderByFieldName4 [sysname] NULL, @PS_OrderByDescending4 TINYINT NULL, @PS_OrderByFieldName5 [sysname] NULL, @PS_OrderByDescending5 TINYINT NULL, @PS_OrderByFieldName6 [sysname] NULL, @PS_OrderByDescending6 TINYINT NULL, @PS_OrderByFieldName7 [sysname] NULL, @PS_OrderByDescending7 TINYINT NULL, @PS_OrderByFieldName8 [sysname] NULL, @PS_OrderByDescending8 TINYINT NULL, @PS_OrderByFieldName9 [sysname] NULL, @PS_OrderByDescending9 TINYINT NULL, @PS_CurrencyCode NVARCHAR (4) NULL, @PS_Category1CodeFrom NVARCHAR (10) NULL, @PS_Category1CodeSearch TINYINT NULL, @PS_Category1CodeTo NVARCHAR (10) NULL, @PS_Category2CodeFrom NVARCHAR (10) NULL, @PS_Category2CodeSearch TINYINT NULL, @PS_Category2CodeTo NVARCHAR (10) NULL, @PS_Category3CodeFrom NVARCHAR (10) NULL, @PS_Category3CodeSearch TINYINT NULL, @PS_Category3CodeTo NVARCHAR (10) NULL, @PS_Category4CodeFrom NVARCHAR (10) NULL, @PS_Category4CodeSearch TINYINT NULL, @PS_Category4CodeTo NVARCHAR (10) NULL, @PS_Category5CodeFrom NVARCHAR (10) NULL, @PS_Category5CodeSearch TINYINT NULL, @PS_Category5CodeTo NVARCHAR (10) NULL, @PS_Category6CodeFrom NVARCHAR (10) NULL, @PS_Category6CodeSearch TINYINT NULL, @PS_Category6CodeTo NVARCHAR (10) NULL, @PS_Category7CodeFrom NVARCHAR (10) NULL, @PS_Category7CodeSearch TINYINT NULL, @PS_Category7CodeTo NVARCHAR (10) NULL, @PS_Category8CodeFrom NVARCHAR (10) NULL, @PS_Category8CodeSearch TINYINT NULL, @PS_Category8CodeTo NVARCHAR (10) NULL, @PS_Year TINYINT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


