CREATE PROCEDURE [dbo].[AA_RTP_BATCH_DETAIL_S]
@PS_Validate_Only TINYINT NULL, @PS_Default_String VARCHAR (200) NULL, @PS_User_Id VARCHAR (4) NULL, @PS_Header_Primary INT NULL OUTPUT, @PS_Detail_Primary INT NULL OUTPUT, @PS_Source VARCHAR (1) NULL, @PS_RTP_Number VARCHAR (10) NULL OUTPUT, @PS_Account VARCHAR (10) NULL, @PS_Request_Date DATETIME NULL, @PS_Request_Year VARCHAR (1) NULL, @PS_Request_Period TINYINT NULL, @PS_Date_Required DATETIME NULL, @PS_Supplier_Ref VARCHAR (20) NULL, @PS_Batch_Ref VARCHAR (10) NULL, @PS_Description VARCHAR (30) NULL, @PS_Currencycode VARCHAR (6) NULL, @PS_Currencysymbol VARCHAR (4) NULL, @PS_Currencytype CHAR (1) NULL, @PS_Currency_Rate DECIMAL (16, 6) NULL, @PS_Euro_To_Home_Rate FLOAT (53) NULL, @PS_Price_Key TINYINT NULL, @PS_Archive_Flag TINYINT NULL, @PS_Allow_Empty_Subanalysis BIT NULL, @PS_Allow_Empty_Serial_No BIT NULL, @PS_Entry_Type VARCHAR (1) NULL, @PS_Item_Code VARCHAR (25) NULL, @PS_Serial_Number VARCHAR (40) NULL, @PS_Sub_Analysis VARCHAR (25) NULL, @PS_Quantity FLOAT (53) NULL, @PS_Price_Line TINYINT NULL, @PS_Quantity_Unit FLOAT (53) NULL, @PS_Home_Unit_Cost FLOAT (53) NULL, @PS_Line_Detail VARCHAR (240) NULL, @PS_Line_Required_Date DATETIME NULL, @PS_Transaction_User_Key1 VARCHAR (20) NULL, @PS_Transaction_User_Key2 VARCHAR (20) NULL, @PS_Transaction_User_Key3 VARCHAR (20) NULL, @PS_Tran_Options VARCHAR (30) NULL, @PS_Header_User_Char1 VARCHAR (20) NULL, @PS_Header_User_Char2 VARCHAR (20) NULL, @PS_Header_User_Char3 VARCHAR (100) NULL, @PS_Header_User_Char4 VARCHAR (100) NULL, @PS_Header_User_Flag1 TINYINT NULL, @PS_Header_User_Flag2 TINYINT NULL, @PS_Header_User_Date1 DATETIME NULL, @PS_Header_User_Date2 DATETIME NULL, @PS_Header_User_Number1 FLOAT (53) NULL, @PS_Header_User_Number2 FLOAT (53) NULL, @PS_Detail_User_Char1 VARCHAR (20) NULL, @PS_Detail_User_Char2 VARCHAR (20) NULL, @PS_Detail_User_Char3 VARCHAR (100) NULL, @PS_Detail_User_Char4 VARCHAR (100) NULL, @PS_Detail_User_Flag1 TINYINT NULL, @PS_Detail_User_Flag2 TINYINT NULL, @PS_Detail_User_Date1 DATETIME NULL, @PS_Detail_User_Date2 DATETIME NULL, @PS_Detail_User_Number1 FLOAT (53) NULL, @PS_Detail_User_Number2 FLOAT (53) NULL, @PS_Serial_Temp_ID INT NULL, @PS_Service BIT NULL, @PS_CostHeader VARCHAR (10) NULL, @PS_CostCentre VARCHAR (10) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


