CREATE PROCEDURE [dbo].[AA_STK_MOVEMENT_INSERT_S]
@PS_Stock_Code VARCHAR (25) NULL, @PS_Stock_Location_Code VARCHAR (25) NULL, @PS_Stock_Move_Req_Date DATETIME NULL, @PS_Stock_Move_Qty_Unit DECIMAL (24, 8) NULL, @PS_Stock_Move_Costprice DECIMAL (24, 8) NULL OUTPUT, @PS_Order_Pricecode CHAR (3) NULL, @PS_Stock_Move_Description VARCHAR (30) NULL, @PS_Stock_Move_CostHeader VARCHAR (10) NULL, @PS_Stock_Move_CostCentre VARCHAR (10) NULL, @PS_Order_Detail VARCHAR (240) NULL, @PS_Order_Account VARCHAR (10) NULL, @PS_Delivery_Year CHAR (1) NULL, @PS_Order_Nett DECIMAL (24, 8) NULL, @PS_Order_Total_Line_Disc DECIMAL (24, 8) NULL, @PS_Order_Nett_Curr DECIMAL (24, 8) NULL, @PS_Order_Total_Line_Disc_Curr DECIMAL (24, 8) NULL, @PS_Order_Serial_Track TINYINT NULL, @PS_Order_Serial_Number VARCHAR (40) NULL, @PS_Order_Qty DECIMAL (24, 8) NULL, @PS_Order_Type CHAR (1) NULL, @PS_Delivery_Date DATETIME NULL, @PS_Delivery_Period TINYINT NULL, @PS_Order_Deliv_Note_Num INT NULL, @PS_Order_Currency_Code VARCHAR (4) NULL, @PS_Order_Number INT NULL, @PS_Order_Printed DECIMAL (24, 8) NULL OUTPUT, @PS_Order_Delivered DECIMAL (24, 8) NULL, @PS_Order_Archive TINYINT NULL, @PS_User_Id VARCHAR (5) NULL, @PS_Order_Reserved DECIMAL (24, 8) NULL OUTPUT, @PS_Quantity_To_Deliver DECIMAL (24, 8) NULL, @PS_Order_Primary INT NULL, @PS_Stock_Physical DECIMAL (24, 8) NULL, @PS_Stock_Qty_Printed DECIMAL (24, 8) NULL, @PS_Stock_Avg_Value DECIMAL (24, 8) NULL, @PS_Stock_SerialTrack TINYINT NULL, @PS_Stock_Multi_Location TINYINT NULL, @PS_Stock_Reserve_Out DECIMAL (24, 8) NULL, @PS_Stock_Reserve_ASM DECIMAL (24, 8) NULL, @PS_Stock_In DECIMAL (24, 8) NULL, @PS_Stock_Loc_Physical DECIMAL (24, 8) NULL, @PS_Stock_Loc_Reserve_Out DECIMAL (24, 8) NULL, @PS_Stock_Loc_Order_In DECIMAL (24, 8) NULL, @PS_Stock_Loc_Reserve_ASM DECIMAL (24, 8) NULL, @PS_Stock_Loc_Qty_Print DECIMAL (24, 8) NULL, @PS_Stock_Loc_Avg_Value DECIMAL (24, 8) NULL, @PS_Stock_Loc_Code VARCHAR (50) NULL, @PS_Stock_Loc_Primary INT NULL, @PS_Order_Net_Base2 DECIMAL (24, 8) NULL, @PS_Order_Total_Disc_Base2 DECIMAL (24, 8) NULL, @PS_Order_Base2_Costprice DECIMAL (24, 8) NULL OUTPUT, @PS_Order_Base2_Rate DECIMAL (24, 8) NULL, @PS_Stock_Wapu_Value DECIMAL (24, 8) NULL, @PS_Stock_Loc_Wapu_Quantity DECIMAL (24, 8) NULL, @PS_Stock_Loc_Wapu_Value DECIMAL (24, 8) NULL, @PS_Actual_Landed_Cost DECIMAL (24, 8) NULL, @PS_Update_Fixed BIT NULL, @PS_Stock_CostPrice DECIMAL (24, 8) NULL, @PS_Stock_Loc_CostPrice DECIMAL (24, 8) NULL, @PS_SM_PROFIT_COST_TYPE VARCHAR (2) NULL, @PS_Source VARCHAR (1) NULL, @PS_Primary INT NULL OUTPUT, @PS_Serial_Link INT NULL, @PS_Commited_Costprice DECIMAL (24, 8) NULL, @PS_Update_Landed_Costs BIT NULL, @PS_StockUpNominalAnalysis VARCHAR (25) NULL, @PS_SubAnalUseStockCost BIT NULL, @PS_LastPrimary INT NULL OUTPUT, @PS_StockBuyUnit1 DECIMAL (24, 8) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


