CREATE PROCEDURE [dbo].[AA_SYS_COMPANY_RECORD_EDIT_S]
@PS_Default_String VARCHAR (100) NULL, @PS_Validate_Only BIT NULL, @PS_User_Id VARCHAR (4) NULL, @PS_Source VARCHAR (1) NULL, @PS_Name VARCHAR (40) NULL, @PS_Branch_ID VARCHAR (3) NULL, @PS_Address VARCHAR (160) NULL, @PS_Town VARCHAR (30) NULL, @PS_County VARCHAR (30) NULL, @PS_Postcode VARCHAR (12) NULL, @PS_Country VARCHAR (35) NULL, @PS_Phone VARCHAR (20) NULL, @PS_Fax VARCHAR (20) NULL, @PS_Reg_Number VARCHAR (20) NULL, @PS_VAT_Number VARCHAR (15) NULL, @PS_Email VARCHAR (64) NULL, @PS_User_Field1 VARCHAR (20) NULL, @PS_User_Field2 VARCHAR (20) NULL, @PS_User_Field3 VARCHAR (20) NULL, @PS_Factoring_Message VARCHAR (240) NULL, @PS_Replace_Notes TEXT NULL, @PS_Append_Notes TEXT NULL, @PS_Bank_Sort_Code VARCHAR (10) NULL, @PS_Bank_Account_Number VARCHAR (15) NULL, @PS_Bank_Account_Name VARCHAR (25) NULL, @PS_ISDN_Number VARCHAR (20) NULL, @PS_Website VARCHAR (100) NULL, @PS_Telex VARCHAR (15) NULL, @PS_User_Char1 VARCHAR (20) NULL, @PS_User_Char2 VARCHAR (20) NULL, @PS_User_Char3 VARCHAR (20) NULL, @PS_User_Char4 VARCHAR (30) NULL, @PS_User_Char5 VARCHAR (30) NULL, @PS_User_Char6 VARCHAR (30) NULL, @PS_User_Date1 DATETIME NULL, @PS_User_Date2 DATETIME NULL, @PS_User_Date3 DATETIME NULL, @PS_User_Flag1 BIT NULL, @PS_User_Flag2 BIT NULL, @PS_User_Flag3 BIT NULL, @PS_User_Number1 DECIMAL (24, 8) NULL, @PS_User_Number2 DECIMAL (24, 8) NULL, @PS_User_Number3 DECIMAL (24, 8) NULL, @PS_ErrorHandlingMethod TINYINT NULL, @PS_InstanceID BIGINT NULL OUTPUT, @PS_ObjectGuid UNIQUEIDENTIFIER NULL, @PS_Bank_IBAN_Number VARCHAR (34) NULL, @PS_Bank_BACS_Reference VARCHAR (18) NULL, @PS_BACS_Export_Format TINYINT NULL, @PS_BIC_Code VARCHAR (11) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


