CREATE PROCEDURE [dbo].[AA_SYS_ATTACHMENTS_LIST_S]
@PS_UserID NVARCHAR (4) NULL, @PS_MaxRecords INT NULL, @PS_CalledFrom INT NULL, @PS_StartValue SQL_VARIANT NULL, @PS_StartPrimary INT NULL, @PS_OrderByDescending TINYINT NULL, @PS_OrderByFieldName [sysname] NULL, @PS_TotalRecordCount INT NULL OUTPUT, @PS_AdvancedResponse TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_GetMinPrimary BIT NULL, @PS_MinPrimaryValue INT NULL OUTPUT, @PS_PrimaryFrom INT NULL, @PS_PrimarySearch TINYINT NULL, @PS_PrimaryTo INT NULL, @PS_CodeFrom NVARCHAR (40) NULL, @PS_CodeSearch TINYINT NULL, @PS_CodeTo NVARCHAR (40) NULL, @PS_FilenameFrom NVARCHAR (256) NULL, @PS_FilenameSearch TINYINT NULL, @PS_FilenameTo NVARCHAR (256) NULL, @PS_DescriptionFrom NVARCHAR (1024) NULL, @PS_DescriptionSearch TINYINT NULL, @PS_DescriptionTo NVARCHAR (1024) NULL, @PS_AuditNoFrom INT NULL, @PS_AuditNoSearch TINYINT NULL, @PS_AuditNoTo INT NULL, @PS_UserCreatedFrom NVARCHAR (4) NULL, @PS_UserCreatedSearch TINYINT NULL, @PS_UserCreatedTo NVARCHAR (4) NULL, @PS_UserEditedFrom NVARCHAR (4) NULL, @PS_UserEditedSearch TINYINT NULL, @PS_UserEditedTo NVARCHAR (4) NULL, @PS_CreatedDateFrom DATETIME NULL, @PS_CreatedDateSearch TINYINT NULL, @PS_CreatedDateTo DATETIME NULL, @PS_ModifiedDateFrom DATETIME NULL, @PS_ModifiedDateSearch TINYINT NULL, @PS_ModifiedDateTo DATETIME NULL, @PS_IncludeSalesLedger TINYINT NULL, @PS_IncludePurchaseLedger TINYINT NULL, @PS_IncludeNominalLedger TINYINT NULL, @PS_IncludeCashBook TINYINT NULL, @PS_IncludeSalesOrders TINYINT NULL, @PS_IncludePurchaseOrders TINYINT NULL, @PS_IncludeStockControl TINYINT NULL, @PS_IncludeCosting TINYINT NULL, @PS_IncludeSystemControl TINYINT NULL, @PS_IncludeGeneral TINYINT NULL, @PS_IncludeCRM TINYINT NULL, @PS_IncludeCustomerRecords TINYINT NULL, @PS_IncludeSupplierRecords TINYINT NULL, @PS_IncludeNominalAccounts TINYINT NULL, @PS_IncludeSalesAnalysis TINYINT NULL, @PS_IncludePurchaseAnalysis TINYINT NULL, @PS_IncludeSOPInvoices TINYINT NULL, @PS_IncludePLRemittances TINYINT NULL, @PS_IncludeSLReceipts TINYINT NULL, @PS_IncludeSLStatements TINYINT NULL, @PS_IncludePLStatements TINYINT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


