CREATE PROCEDURE [dbo].[AA_SL_CHECK_ADDRESS_S]
@PS_CustCode VARCHAR (10) NULL, @PS_AddCode DECIMAL (24, 8) NULL, @PS_AddType VARCHAR (1) NULL, @PS_VAT_RegNumber VARCHAR (21) NULL OUTPUT, @PS_ExportCode VARCHAR (1) NULL OUTPUT, @PS_CountryCode VARCHAR (4) NULL OUTPUT, @PS_Analysis VARCHAR (25) NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


