CREATE PROCEDURE [dbo].[AA_SYS_ANL_OPTIONS_EDIT_S]
@PS_NL_USE_ADVANCED BIT NULL, @PS_ANL_NOM_SEPARATOR VARCHAR (1) NULL, @PS_ANL_NUMBER_OF_CAT_LEVELS TINYINT NULL, @PS_ANL_CAT_DETAIL_LEVEL TINYINT NULL, @PS_ANL_CAT_LEVEL1_SETUP TINYINT NULL, @PS_ANL_CAT_LEVEL2_SETUP TINYINT NULL, @PS_ANL_CAT_LEVEL3_SETUP TINYINT NULL, @PS_ANL_CAT_LEVEL4_SETUP TINYINT NULL, @PS_ANL_CAT_LEVEL5_SETUP TINYINT NULL, @PS_ANL_CAT_LEVEL6_SETUP TINYINT NULL, @PS_ANL_CAT_LEVEL7_SETUP TINYINT NULL, @PS_ANL_CAT_LEVEL8_SETUP TINYINT NULL, @PS_ANL_CAT_LEVEL1_ENTRY TINYINT NULL, @PS_ANL_CAT_LEVEL2_ENTRY TINYINT NULL, @PS_ANL_CAT_LEVEL3_ENTRY TINYINT NULL, @PS_ANL_CAT_LEVEL4_ENTRY TINYINT NULL, @PS_ANL_CAT_LEVEL5_ENTRY TINYINT NULL, @PS_ANL_CAT_LEVEL6_ENTRY TINYINT NULL, @PS_ANL_CAT_LEVEL7_ENTRY TINYINT NULL, @PS_ANL_CAT_LEVEL8_ENTRY TINYINT NULL, @PS_ANL_CAT_LEVEL1_LENGTH TINYINT NULL, @PS_ANL_CAT_LEVEL2_LENGTH TINYINT NULL, @PS_ANL_CAT_LEVEL3_LENGTH TINYINT NULL, @PS_ANL_CAT_LEVEL4_LENGTH TINYINT NULL, @PS_ANL_CAT_LEVEL5_LENGTH TINYINT NULL, @PS_ANL_CAT_LEVEL6_LENGTH TINYINT NULL, @PS_ANL_CAT_LEVEL7_LENGTH TINYINT NULL, @PS_ANL_CAT_LEVEL8_LENGTH TINYINT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


