CREATE PROCEDURE [dbo].[AA_SOP_BATCH_EDIT_CREDIT_CARD_VALIDATION_S]
@PS_Defs VARCHAR (200) NULL, @PS_Mail_Order TINYINT NULL OUTPUT, @PS_Authorise_Code VARCHAR (10) NULL OUTPUT, @PS_Credit_Card_No VARCHAR (20) NULL OUTPUT, @PS_Card_Expiry_Date VARCHAR (5) NULL OUTPUT, @PS_MailOrder_Bank_Analysis VARCHAR (25) NULL OUTPUT, @PS_User_Id VARCHAR (4) NULL OUTPUT, @PS_Switch_Issue_Number VARCHAR (2) NULL OUTPUT, @PS_Switch_Issue_Date VARCHAR (5) NULL OUTPUT, @PS_Bank_Ref VARCHAR (4) NULL OUTPUT, @PS_Card_Type VARCHAR (1) NULL OUTPUT, @PS_CardHolderName VARCHAR (40) NULL OUTPUT, @PS_CardVisibleDigits VARCHAR (4) NULL OUTPUT, @PS_CardEncryptedDigits VARBINARY (256) NULL OUTPUT, @PS_CardSecurityDigits VARBINARY (256) NULL OUTPUT, @PS_LS_MAIL_ORDER_ON BIT NULL OUTPUT, @PS_LS_OH_CURRENCYCODE VARCHAR (4) NULL OUTPUT, @PS_LS_OH_NORMAL_ORD TINYINT NULL OUTPUT, @PS_LS_OH_AUTHORISE VARCHAR (10) NULL OUTPUT, @PS_LS_OH_CREDIT_CARD VARCHAR (20) NULL OUTPUT, @PS_LS_OH_CARD_EXPIRY VARCHAR (5) NULL OUTPUT, @PS_LS_OH_BANK_ANLYSIS VARCHAR (25) NULL OUTPUT, @PS_LS_OH_SWITCH_ISSUE_NO VARCHAR (2) NULL OUTPUT, @PS_LS_OH_SWITCH_ISSUE_DATE VARCHAR (5) NULL OUTPUT, @PS_LS_OH_NATWEST_REF VARCHAR (4) NULL OUTPUT, @PS_LS_OH_CARD_TYPE VARCHAR (1) NULL OUTPUT, @PS_LS_OH_CARDHOLDER_NAME VARCHAR (40) NULL OUTPUT, @PS_LS_OH_CARD_VISIBLE_DIGITS VARCHAR (4) NULL OUTPUT, @PS_LS_OH_CARD_ENCRYPTED_DIGITS VARBINARY (256) NULL OUTPUT, @PS_LS_OH_CARD_SECURITY_DIGITS VARBINARY (256) NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


