create view AA_ACD_GOODSRECEIVED_REPRINT_VIEW
/*
** Written     :  19/08/2008 CW
** Last Amended:
** Comments    :  Returns POP Goods Received Note information for crystal reports
*/
as
select
   DOC_ORDER_HEADER.DOH_ORDER_LINK
,  DOC_ORDER_HEADER.DOH_DOC_DATE
,  DOC_ORDER_HEADER.DOH_DOC_TYPE
,  DOC_ORDER_HEADER.DOH_FAX_HEADER
,  DOC_ORDER_HEADER.DOH_COMP_ADDRESS
,  DOC_ORDER_HEADER.DOH_FAX_FOOTER
,  DOC_ORDER_HEADER.DOH_USER_ID
,  DOC_ORDER_HEADER.DOH_SYS_LINK
,  DOC_ORDER_HEADER.DOH_PRIMARY

,  POP_HEADER.POH_ORDER_REF
,  POP_HEADER.POH_ORDER_NUMBR
,  POP_HEADER.POH_REQUIRED
,  POP_HEADER.POH_CURR_CODE
,  POP_HEADER.POH_DISC_TOT_P
,  POP_HEADER.POH_L_DISCVAL
,  POP_HEADER.POH_L_DISCVAL_C
,  POP_HEADER.POH_DEL_ADD
,  POP_HEADER.POH_BUDGET_STATUS
,  POP_HEADER.POH_AUTHORISER_ID
,  POP_HEADER.POH_PRIORITY
,  POP_HEADER.POH_ACCOUNT
,  POP_HEADER.POH_PRIMARY

,  DOC_ORDER_DETAIL.DOD_QUANTITY
,  DOC_ORDER_DETAIL.DOD_LINEDISC_DOC
,  DOC_ORDER_DETAIL.DOD_NET_DOC
,  DOC_ORDER_DETAIL.DOD_TOTDISC_DOC
,  DOC_ORDER_DETAIL.DOD_VAT_DOC
,  DOC_ORDER_DETAIL.DOD_NET_BASE2
,  DOC_ORDER_DETAIL.DOD_VAT_BASE2
,  DOC_ORDER_DETAIL.DOD_TOTDISC_BASE2
,  DOC_ORDER_DETAIL.DOD_HEADER_LINK
,  DOC_ORDER_DETAIL.DOD_PRIMARY
,  DOC_ORDER_DETAIL.DOD_SERIAL_NO
,  DOC_ORDER_DETAIL.DOD_USER_ID
,  DOC_ORDER_DETAIL.DOD_QUANTITY_OS
,  DOC_ORDER_DETAIL.DOD_ORDER_LINK

,  POP_DETAIL.POD_ENTRY_TYPE
,  POP_DETAIL.POD_DETAIL
,  POP_DETAIL.POD_REQDATE
,  POP_DETAIL.POD_UNITCST_C
,  POP_DETAIL.POD_UNITCST
,  POP_DETAIL.POD_STOCK_CODE
,  POP_DETAIL.POD_SERIALTRACK
,  POP_DETAIL.POD_QTYUNIT
,  POP_DETAIL.POD_TABLECODE
,  POP_DETAIL.POD_LOCATN
,  POP_DETAIL.POD_PRIMARY

,  PL_ACCOUNTS.SUCODE
,  PL_ACCOUNTS.SU_IMPORT_CODE
,  PL_ACCOUNTS.SU_VAT_REG_NO

,  SYS_DATAINFO2.TRI_VAL_ON_INVOICES
,  SYS_DATAINFO2.BASE2_CURR_SYMBOL
,  SYS_DATAINFO2.STK_POP_COPY_DESC
,  SYS_DATAINFO2.SYS_PRIMARY_2

,  SYS_DATAINFO.HOME_CURR_SYMBL
,  SYS_DATAINFO.POP_SHOW_STKCDE
,  SYS_DATAINFO.SHOW_SUP_STKCDE
,  SYS_DATAINFO.SYS_PRIMARY

,  STK_STOCK.STKCODE
,  STK_STOCK.STKNAME

,  STK_STOCK_2.STK_BUY_NAME1
,  STK_STOCK_2.STK_BUY_NAME2
,  STK_STOCK_2.STK_BUY_NAME3
,  STK_STOCK_2.STK_BUY_NAME4
,  STK_STOCK_2.STK_BUY_NAME5
,  STK_STOCK_2.STK_BUY_NAME6
,  STK_STOCK_2.STK_BUY_NAME7
,  STK_STOCK_2.STK_BUY_NAME8
,  STK_STOCK_2.STK_BUY_NAME9
,  STK_STOCK_2.STK_BUY_NAME10
,  STK_STOCK_2.STK_SUPSTKCDE1
,  STK_STOCK_2.STK_SUPSTKCDE2
,  STK_STOCK_2.STK_SUPSTKCDE3
,  STK_STOCK_2.STK_SUPSTKCDE4
,  STK_STOCK_2.STK_SUPSTKCDE5
,  STK_STOCK_2.STK_SUPSTKCDE6
,  STK_STOCK_2.STK_SUPSTKCDE7
,  STK_STOCK_2.STK_SUPSTKCDE8
,  STK_STOCK_2.STK_SUPSTKCDE9
,  STK_STOCK_2.STK_SUPSTKCDE10
,  STK_STOCK_2.STKCODE2


,  SYS_CURRENCY_REC.CURREC_EURO_CURRENCY

,  SYS_DEL_HISTORY_HEADER.DHH_INVOICE_ADDRESS
,  SYS_DEL_HISTORY_HEADER.DHH_DELIVERY_ADDRESS
,  SYS_DEL_HISTORY_HEADER.DHH_DEL_METHOD        as POH_DEL_METHOD
,  SYS_DEL_HISTORY_HEADER.DHH_DELIVERYNOTE_NO
,  SYS_DEL_HISTORY_HEADER.DHH_ACCOUNT
,  SYS_DEL_HISTORY_HEADER.DHH_ORDER_NO

   from
      DOC_ORDER_HEADER with(nolock)
         inner join  POP_HEADER              with(nolock)   on       POH_PRIMARY          = DOH_ORDER_LINK
         inner join  PL_ACCOUNTS             with(nolock)   on       SUCODE               = POH_ACCOUNT
         inner join  SYS_DEL_HISTORY_HEADER  with(nolock)   on       DHH_ORDER_NO         = POH_ORDER_NUMBR
                                                               and   DHH_ORIGIN           like 'P%'
                                                               and   DHH_DELIVERYNOTE_NO  = cast(DOH_DOC_NUMBER as int)
         inner join  DOC_ORDER_DETAIL        with(nolock)   on       DOD_HEADER_LINK      = DOH_PRIMARY
         inner join  POP_DETAIL                             on       POD_PRIMARY          = DOD_ORDER_LINK
         inner join  SYS_DATAINFO            with(nolock)   on       SYS_PRIMARY          = 1
         inner join  SYS_DATAINFO2           with(nolock)   on       SYS_PRIMARY_2        = SYS_PRIMARY
         inner join  SYS_CURRENCY_REC        with(nolock)   on       CURREC_SYMBOL        = POH_CURR_CODE
         left  join  STK_STOCK               with(nolock)   on       STKCODE              = POD_STOCK_CODE
         left  join  STK_STOCK_2             with(nolock)   on       STK_PRIMARY_2        = STK_PRIMARY