create view AA_ACD_DELIVERY_VIEW
as
select
   DOC_ORDER_HEADER.DOH_PRIMARY
,  DOC_ORDER_HEADER.DOH_ORDER_LINK
,  DOC_ORDER_HEADER.DOH_DOC_TYPE
,  DOC_ORDER_HEADER.DOH_DOC_DATE
,  DOC_ORDER_HEADER.DOH_DOC_NUMBER
,  DOC_ORDER_HEADER.DOH_COMP_ADDRESS
,  DOC_ORDER_HEADER.DOH_USER_ID

,  ORD_HEADER.OH_ORDER_REF
,  ORD_HEADER.OH_DEL_METHOD
,  ORD_HEADER.OH_ORDER_NUMBER
,  ORD_HEADER.OH_ACCOUNT_DELIVERY

,  DEL_ACCOUNT.CUNAME                  as DEL_ACCOUNT__CUNAME

,  DEL_ADDRESS.AD_ADDRESS              as DEL_ADDRESS__AD_ADDRESS
,  DEL_ADDRESS.AD_POSTCODE             as DEL_ADDRESS__AD_POSTCODE
,  DEL_ADDRESS.AD_ACCOUNTNAME          as DEL_ADDRESS__AD_ACCOUNTNAME
,  DEL_ADDRESS.AD_ADDRESS_USER1        as DEL_ADDRESS__AD_ADDRESS_USER1
,  DEL_ADDRESS.AD_ADDRESS_USER2        as DEL_ADDRESS__AD_ADDRESS_USER2
,  DEL_ADDRESS.AD_COUNTRY              as DEL_ADDRESS__AD_COUNTRY

,  ORD_ACCOUNT.CUNAME                  as ORD_ACCOUNT__CUNAME

,  INV_ADDRESS.AD_ADDRESS              as INV_ADDRESS__AD_ADDRESS
,  INV_ADDRESS.AD_POSTCODE             as INV_ADDRESS__AD_POSTCODE
,  INV_ADDRESS.AD_ACCOUNTNAME          as INV_ADDRESS__AD_ACCOUNTNAME
,  INV_ADDRESS.AD_ADDRESS_USER1        as INV_ADDRESS__AD_ADDRESS_USER1
,  INV_ADDRESS.AD_ADDRESS_USER2        as INV_ADDRESS__AD_ADDRESS_USER2
,  INV_ADDRESS.AD_COUNTRY              as INV_ADDRESS__AD_COUNTRY

,  DOC_ORDER_DETAIL.DOD_PRIMARY
,  DOC_ORDER_DETAIL.DOD_HEADER_LINK
,  DOC_ORDER_DETAIL.DOD_QUANTITY
,  DOC_ORDER_DETAIL.DOD_QUANTITY_OS
,  DOC_ORDER_DETAIL.DOD_SERIAL_NO

,  ORD_DETAIL.OD_ENTRY_TYPE
,  ORD_DETAIL.OD_DETAIL
,  ORD_DETAIL.OD_QTYORD
,  ORD_DETAIL.OD_QTYUNIT
,  ORD_DETAIL.OD_TABLECODE
,  ORD_DETAIL.OD_SERIALTRACK
,  ORD_DETAIL.OD_LOCATN
,  ORD_DETAIL.OD_STOCK_CODE
,  ORD_DETAIL.OD_PRICE_CODE
,  ORD_DETAIL.OD_DELIVERY_CHARGE_FLAG

,  STK_STOCK.STKNAME

,  STK_STOCK_2.STK_SELL_NAME1
,  STK_STOCK_2.STK_SELL_NAME2
,  STK_STOCK_2.STK_SELL_NAME3
,  STK_STOCK_2.STK_SELL_NAME4
,  STK_STOCK_2.STK_SELL_NAME5
,  STK_STOCK_2.STK_SELL_NAME6
,  STK_STOCK_2.STK_SELL_NAME7
,  STK_STOCK_2.STK_SELL_NAME8
,  STK_STOCK_2.STK_SELL_NAME9
,  STK_STOCK_2.STK_SELL_NAME10

,  SYS_DATAINFO.SHOW_STOCK_CODE

,  SYS_DATAINFO2.STK_SOP_COPY_DESC
,  DEL_ADDRESS.AD_DELIVERY_ROUTE       as DEL_ADDRESS__AD_DELIVERY_ROUTE
   from
      DOC_ORDER_HEADER with(nolock)
         inner join  ORD_HEADER                       with(nolock)   on ORD_HEADER.OH_PRIMARY            = DOC_ORDER_HEADER.DOH_ORDER_LINK
         inner join  SL_ACCOUNTS       as DEL_ACCOUNT with(nolock)   on DEL_ACCOUNT.CUCODE               = ORD_HEADER.OH_ACCOUNT_DELIVERY
         inner join  SL_ADDRESSES      as DEL_ADDRESS with(nolock)   on DEL_ADDRESS.AD_CON_CODE          = convert(char(10),ORD_HEADER.OH_ACCOUNT_DELIVERY)+convert(varchar,ORD_HEADER.OH_DEL_ADD)
         inner join  SL_ACCOUNTS       as ORD_ACCOUNT with(nolock)   on ORD_ACCOUNT.CUCODE               = ORD_HEADER.OH_ACCOUNT
         inner join  SL_ADDRESSES      as INV_ADDRESS with(nolock)   on INV_ADDRESS.AD_CON_CODE          = convert(char(10),ORD_HEADER.OH_ACCOUNT)+convert(varchar,ORD_HEADER.OH_INV_ADD)
         inner join  DOC_ORDER_DETAIL                 with(nolock)   on DOC_ORDER_DETAIL.DOD_HEADER_LINK = DOC_ORDER_HEADER.DOH_PRIMARY
         inner join  ORD_DETAIL                       with(nolock)   on ORD_DETAIL.OD_PRIMARY            = DOC_ORDER_DETAIL.DOD_ORDER_LINK
         inner join  SYS_DATAINFO                     with(nolock)   on SYS_DATAINFO.SYS_PRIMARY         = DOC_ORDER_HEADER.DOH_SYS_LINK
         inner join  SYS_DATAINFO2                    with(nolock)   on SYS_DATAINFO2.SYS_PRIMARY_2      = SYS_DATAINFO.SYS_PRIMARY
         left  join  STK_STOCK                        with(nolock)   on STK_STOCK.STKCODE                = ORD_DETAIL.OD_STOCK_CODE
         left  join  STK_STOCK_2                      with(nolock)   on STK_STOCK_2.STK_PRIMARY_2        = STK_STOCK.STK_PRIMARY