Create view AA_ACD_WO_DOCKET_VIEW_SUB
as

SELECT
   DOC_WO_HEADER.DWH_PRIMARY,
   DOC_WO_HEADER.DWH_USER_ID, 
   DOC_WO_HEADER.DWH_WO_ORDER_NUMBER,
   DOC_WO_HEADER.DWH_DOC_TYPE,
   ORD_DETAIL.OD_ORDER_NUMBER,
   ORD_DETAIL.OD_ACCOUNT,
   ORD_HEADER.OH_ORDER_REF,
   SL_ACCOUNTS.CUNAME

FROM
   DOC_WO_HEADER DOC_WO_HEADER 
     LEFT OUTER JOIN WO_ORDERS WO_ORDERS     ON DOC_WO_HEADER.DWH_WO_ORDER_NUMBER = WO_ORDERS.WO_ORDER_NUMBER
     LEFT OUTER JOIN ORD_DETAIL  ORD_DETAIL  ON OD_WO_NUMBER                      = WO_ORDERS.WO_ORDER_NUMBER
     LEFT OUTER JOIN ORD_HEADER  ORD_HEADER  ON OH_ORDER_NUMBER                   = ORD_DETAIL.OD_ORDER_NUMBER
     LEFT OUTER JOIN SL_ACCOUNTS SL_ACCOUNTS ON CUCODE                            = ORD_HEADER.OH_ACCOUNT_ORDER
