CREATE view AA_ACD_WO_KITTING_LIST_VIEW2
--View developed to cope with Kitting list where the 
--Works Order Number has not been created yet

as

SELECT DWH_START_DATE,DWH_END_DATE,DWH_ROUTE,DWH_QUANTITY_ORDERED, 
DWH_DOC_TYPE,DWH_MAIN_STOCKCODE,DWH_MAIN_STOCKNAME,DWH_PRIMARY, DWH_USER_ID,
DWD_LEVEL,DWD_COMP_CODE_NAME,DWD_COMP_QTY_REQU,DWD_COMP_QTY_ISSUED,
DWD_COMP_QTY_ALLOC,DWD_COMP_QTY_NEEDED,DWD_COMP_QTY_AVAIL,DWD_LINE_TYPE,DWD_SORT,
DWD_COMP_LABOUR_FLAG,DWD_COMP_BACKFLUSH_FLAG,DWD_COMP_RTP_FLAG

FROM  DOC_WO_HEADER, DOC_WO_DETAIL where DWH_PRIMARY = DWD_HEADER_LINK
                    

