CREATE VIEW [dbo].[AA_AOI_INXL_OFFLINE_GET_NLREPORTATTS_View] (
    [NCODE],
    [NL_MAJORCODE],
    [NCATCODE1],
    [NCATNAME1],
    [NCATCODE2],
    [NCATNAME2],
    [NCATCODE3],
    [NCATNAME3],
    [NCATCODE4],
    [NCATNAME4],
    [NCATCODE5],
    [NCATNAME5],
    [NCATCODE6],
    [NCATNAME6],
    [NCATCODE7],
    [NCATNAME7],
    [NCATCODE8],
    [NCATNAME8],
    [LINKED_CAT_CODE],
    [LINKED_CAT_NAME],
    [LINKED_CAT_LEVEL],
    [LINKED_CAT_USED],
    [NATT_PRIMARY],
    [NATT_CATEGORY_NUMBER],
    [NATT_CODE],
    [NATT_DESCRIPTION],
    [NATV_PRIMARY],
    [NATV_CODE],
    [NATV_NAME],
    [NATV_ORDER]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

