Create view AA_ACD_WO_DOCKET_VIEW_MAIN
as

SELECT
   DOC_WO_HEADER.DWH_PRIMARY,
   DOC_WO_HEADER.DWH_USER_ID, 
   DOC_WO_HEADER.DWH_WO_ORDER_NUMBER,
   DOC_WO_HEADER.DWH_DOC_TYPE,
   DOC_WO_DETAIL.DWD_PRIMARY, 
   DOC_WO_DETAIL.DWD_WC_ORDER_NUMBER,
   DOC_WO_DETAIL.DWD_LEVEL,
   DOC_WO_DETAIL.DWD_SORT,
   
   WO_ORDERS.WO_PARENT_ORDER_NUMBER, 
   WO_ORDERS.WO_TOP_LEVEL_ORDER_NUMBER, 
   WO_ORDERS.WO_START_DATE, 
   WO_ORDERS.WO_END_DATE,
   WO_ORDERS.WO_PRIORITY WO_PRIORITY,
   WO_ORDERS.WO_NOTES,
   WO_ORDER_STK_STOCK.STKCODE WO_STKCODE, 
   WO_ORDER_STK_STOCK.STKNAME WO_STKNAME,
   WO_ORDERS_ROUTES.WR_ROUTE,
   WO_ORDERS.WO_QUANTITY WO_QUANTITY,

   SUB_WO_ORDERS.WO_QUANTITY SUB_WO_QUANTITY,
   SUB_WO_ORDERS.WO_QUANTITY_ISSUED SUB_WO_QUANTITY_ISSUED,
      
   COMPONENT_WO_ORDERS.WO_PARENT_ORDER_NUMBER COMPONENT_WO_PARENT_ORDER_NUMBER, 
   COMPONENT_WO_ORDERS.WO_QUANTITY COMPONENT_WO_QUANTITY, 
   
   COMPONENT_STK_STOCK.STKCODE      COMPONENT_STKCODE, 
   COMPONENT_STK_STOCK.STKNAME      COMPONENT_STKNAME,
   COMPONENT_PRC_PRICE_RECS.PRCODE  COMPONENT_PRCODE, 
   COMPONENT_PRC_PRICE_RECS.PRNAME  COMPONENT_PRNAME,
   WO_COMPONENTS.WC_TYPE            COMPONENT_TYPE, 
   WO_COMPONENTS.WC_TEXT            COMPONENT_TEXT,

   WO_COMPONENTS.WC_QUANTITY_REQUIRED COMPONENT_QUANTITY_REQUIRED,
   WO_COMPONENTS.WC_QUANTITY_ISSUED   COMPONENT_QUANTITY_ISSUED,
   WO_COMPONENTS.WC_QUANTITY_ALLOC    COMPONENT_QUANTITY_ALLOC,
   WO_COMPONENTS.WC_LABOUR            COMPONENT_LABOUR,
   WO_COMPONENTS.WC_BACKFLUSH         COMPONENT_BACKFLUSH,
   WO_COMPONENTS.WC_RTP_FLAG          COMPONENT_RTP_FLAG,
      
   WC_ORDER_STK_STOCK.STKCODE WC_ORDER_STKCODE, 
   WC_ORDER_STK_STOCK.STKNAME WC_ORDER_STKNAME

FROM
   DOC_WO_HEADER DOC_WO_HEADER 
     LEFT OUTER JOIN WO_ORDERS WO_ORDERS ON DOC_WO_HEADER.DWH_WO_ORDER_NUMBER = WO_ORDERS.WO_ORDER_NUMBER
        
     LEFT OUTER JOIN DOC_WO_DETAIL DOC_WO_DETAIL ON DOC_WO_HEADER.DWH_PRIMARY = DOC_WO_DETAIL.DWD_HEADER_LINK
     LEFT OUTER JOIN WO_ORDERS COMPONENT_WO_ORDERS ON DOC_WO_DETAIL.DWD_WC_ORDER_NUMBER = COMPONENT_WO_ORDERS.WO_ORDER_NUMBER
     LEFT OUTER JOIN WO_COMPONENTS WO_COMPONENTS ON DOC_WO_DETAIL.DWD_WC_LINK = WO_COMPONENTS.WC_PRIMARY
     LEFT OUTER JOIN WO_ROUTES WO_ORDERS_ROUTES ON WO_ORDERS.WO_ROUTE_LINK = WO_ORDERS_ROUTES.WR_PRIMARY
     LEFT OUTER JOIN STK_STOCK WO_ORDER_STK_STOCK ON WO_ORDERS.WO_STOCK_LINK = WO_ORDER_STK_STOCK.STK_PRIMARY
     LEFT OUTER JOIN STK_STOCK COMPONENT_STK_STOCK ON WO_COMPONENTS.WC_PART_LINK = COMPONENT_STK_STOCK.STK_PRIMARY and WO_COMPONENTS.WC_TYPE='S'
     LEFT OUTER JOIN PRC_PRICE_RECS COMPONENT_PRC_PRICE_RECS ON WO_COMPONENTS.WC_PART_LINK = COMPONENT_PRC_PRICE_RECS.PR_PRIMARY and WO_COMPONENTS.WC_TYPE='P'
     LEFT OUTER JOIN STK_STOCK WC_ORDER_STK_STOCK ON COMPONENT_WO_ORDERS.WO_STOCK_LINK = WC_ORDER_STK_STOCK.STK_PRIMARY
     LEFT OUTER JOIN WO_ORDERS SUB_WO_ORDERS  ON DWD_WC_ORDER_NUMBER = SUB_WO_ORDERS.WO_ORDER_NUMBER
   