create view AA_ACD_PURCHASE_ORDER_VIEW
as
select
   DOC_ORDER_HEADER.DOH_PRIMARY
,  DOC_ORDER_HEADER.DOH_COMP_ADDRESS
,  DOC_ORDER_HEADER.DOH_DOC_DATE
,  DOC_ORDER_HEADER.DOH_DOC_TYPE
,  DOC_ORDER_HEADER.DOH_FAX_HEADER
,  DOC_ORDER_HEADER.DOH_FAX_FOOTER
,  DOC_ORDER_HEADER.DOH_OPTION1
,  DOC_ORDER_HEADER.DOH_ORDER_LINK
,  DOC_ORDER_HEADER.DOH_USER_ID
,  DOC_ORDER_HEADER.DOH_VAT_CURR_VALUE1
,  DOC_ORDER_HEADER.DOH_VAT_CURR_VALUE2
,  DOC_ORDER_HEADER.DOH_VAT_CURR_VALUE3
,  DOC_ORDER_HEADER.DOH_VAT_CURR_VALUE4
,  DOC_ORDER_HEADER.DOH_VAT_CURR_VALUE5
,  DOC_ORDER_HEADER.DOH_VAT_BASE2_VALUE1
,  DOC_ORDER_HEADER.DOH_VAT_BASE2_VALUE2
,  DOC_ORDER_HEADER.DOH_VAT_BASE2_VALUE3
,  DOC_ORDER_HEADER.DOH_VAT_BASE2_VALUE4
,  DOC_ORDER_HEADER.DOH_VAT_BASE2_VALUE5

,  SYS_DATAINFO.COMP_ADDRESS
,  SYS_DATAINFO.COMP_ADDRESS_USER1
,  SYS_DATAINFO.COMP_ADDRESS_USER2
,  SYS_DATAINFO.COMP_POSTCODE
,  SYS_DATAINFO.COMP_COUNTRY
,  SYS_DATAINFO.COMP_VATNUMBER
,  SYS_DATAINFO.COMPANY_NAME
,  SYS_DATAINFO.HOME_CURR_SYMBL
,  SYS_DATAINFO.POP_SHOW_STKCDE
,  SYS_DATAINFO.SHOW_SUP_STKCDE
,  SYS_DATAINFO.VALUE_DPS

,  SYS_DATAINFO2.BASE2_CURR_SYMBOL
,  SYS_DATAINFO2.STK_POP_COPY_DESC
,  SYS_DATAINFO2.TRI_VAL_ON_INVOICES

,  POP_HEADER.POH_AUTHORISER_ID
,  POP_HEADER.POH_BUDGET_STATUS
,  POP_HEADER.POH_CURR_CODE
,  POP_HEADER.POH_DEL_ADD
,  POP_HEADER.POH_DEL_ADD_POINT
,  POP_HEADER.POH_DEL_METHOD
,  POP_HEADER.POH_DISC_TOT_P
,  POP_HEADER.POH_ORDER_NUMBR
,  POP_HEADER.POH_ORDER_REF
,  POP_HEADER.POH_PRIORITY
,  POP_HEADER.POH_REQUIRED

,  PL_ACCOUNTS.SU_IMPORT_CODE
,  PL_ACCOUNTS.SU_VAT_REG_NO
,  PL_ACCOUNTS.SUCODE
,  PL_ACCOUNTS.SUNAME

,  SL_ADDRESSES.AD_ADDRESS
,  SL_ADDRESSES.AD_ADDRESS_USER1
,  SL_ADDRESSES.AD_ADDRESS_USER2
,  SL_ADDRESSES.AD_POSTCODE
,  SL_ADDRESSES.AD_COUNTRY
,  SL_ADDRESSES.AD_ACCOUNTNAME

,  SL_ACCOUNTS.CUNAME

,  SYS_COMP_ADDRESS.COAD_ADDRESS
,  SYS_COMP_ADDRESS.COAD_ADDRESS_USER1
,  SYS_COMP_ADDRESS.COAD_ADDRESS_USER2
,  SYS_COMP_ADDRESS.COAD_NAME
,  SYS_COMP_ADDRESS.COAD_POSTCODE
,  SYS_COMP_ADDRESS.COAD_COUNTRY

,  SYS_CURRENCY_REC.CURREC_EURO_CURRENCY

,  PL_ADDRESSES_DELIVERY.PL_AD_ADDRESS       PL_AD_ADDRESS_DELIVERY
,  PL_ADDRESSES_DELIVERY.PL_AD_ADDRESS_USER1 PL_AD_ADDRESS_USER1_DELIVERY
,  PL_ADDRESSES_DELIVERY.PL_AD_ADDRESS_USER2 PL_AD_ADDRESS_USER2_DELIVERY
,  PL_ADDRESSES_DELIVERY.PL_AD_CONTACT       PL_AD_CONTACT_DELIVERY
,  PL_ADDRESSES_DELIVERY.PL_AD_POSTCODE      PL_AD_POSTCODE_DELIVERY
,  PL_ADDRESSES_DELIVERY.PL_AD_COUNTRY       PL_AD_COUNTRY_DELIVERY

,  PL_ADDRESSES_INVOICE.PL_AD_ADDRESS        PL_AD_ADDRESS_INVOICE
,  PL_ADDRESSES_INVOICE.PL_AD_ADDRESS_USER1  PL_AD_ADDRESS_USER1_INVOICE
,  PL_ADDRESSES_INVOICE.PL_AD_ADDRESS_USER2  PL_AD_ADDRESS_USER2_INVOICE
,  PL_ADDRESSES_INVOICE.PL_AD_POSTCODE       PL_AD_POSTCODE_INVOICE
,  PL_ADDRESSES_INVOICE.PL_AD_COUNTRY        PL_AD_COUNTRY_INVOICE

,  DOC_ORDER_DETAIL.DOD_PRIMARY
,  DOC_ORDER_DETAIL.DOD_HEADER_LINK
,  DOC_ORDER_DETAIL.DOD_LINEDISC_DOC
,  DOC_ORDER_DETAIL.DOD_NET_BASE2
,  DOC_ORDER_DETAIL.DOD_NET_DOC
,  DOC_ORDER_DETAIL.DOD_NET_FOREIGN
,  DOC_ORDER_DETAIL.DOD_QUANTITY
,  DOC_ORDER_DETAIL.DOD_SERIAL_NO
,  DOC_ORDER_DETAIL.DOD_TOTDISC_BASE2
,  DOC_ORDER_DETAIL.DOD_TOTDISC_DOC
,  DOC_ORDER_DETAIL.DOD_VAT_BASE2
,  DOC_ORDER_DETAIL.DOD_VAT_DOC

,  POP_DETAIL.POD_DETAIL
,  POP_DETAIL.POD_ENTRY_TYPE
,  POP_DETAIL.POD_QTYDELVD
,  POP_DETAIL.POD_QTYINVD
,  POP_DETAIL.POD_QTYORD
,  POP_DETAIL.POD_REQDATE
,  POP_DETAIL.POD_SERIALTRACK
,  POP_DETAIL.POD_STOCK_CODE
,  POP_DETAIL.POD_PRICE_CODE
,  POP_DETAIL.POD_TABLECODE
,  POP_DETAIL.POD_UNITCST
,  POP_DETAIL.POD_UNITCST_C

,  STK_STOCK.STKNAME

,  STK_STOCK_2.STK_SUPSTKCDE1
,  STK_STOCK_2.STK_SUPSTKCDE2
,  STK_STOCK_2.STK_SUPSTKCDE3
,  STK_STOCK_2.STK_SUPSTKCDE4
,  STK_STOCK_2.STK_SUPSTKCDE5
,  STK_STOCK_2.STK_SUPSTKCDE6
,  STK_STOCK_2.STK_SUPSTKCDE7
,  STK_STOCK_2.STK_SUPSTKCDE8
,  STK_STOCK_2.STK_SUPSTKCDE9
,  STK_STOCK_2.STK_SUPSTKCDE10
,  DOC_ORDER_HEADER.DOH_DESCRIPTION

from
   DOC_ORDER_HEADER
      inner join SYS_DATAINFO                               on       SYS_DATAINFO.SYS_PRIMARY               = DOC_ORDER_HEADER.DOH_SYS_LINK
      inner join SYS_DATAINFO2                              on       SYS_DATAINFO2.SYS_PRIMARY_2            = SYS_DATAINFO.SYS_PRIMARY
      inner join POP_HEADER                                 on       POP_HEADER.POH_PRIMARY                 = DOC_ORDER_HEADER.DOH_ORDER_LINK
      inner join PL_ACCOUNTS                                on       PL_ACCOUNTS.SUCODE                     = POP_HEADER.POH_ACCOUNT
      left  join SL_ADDRESSES                               on       SL_ADDRESSES.SL_AD_PRIMARY             = POP_HEADER.POH_DEL_ADD
      left  join SL_ACCOUNTS                                on       SL_ACCOUNTS.CUCODE                     = SL_ADDRESSES.AD_ACC_CODE
      left  join SYS_COMP_ADDRESS                           on       SYS_COMP_ADDRESS.COAD_PRIMARY          = POP_HEADER.POH_DEL_ADD
      left  join SYS_CURRENCY_REC                           on       SYS_CURRENCY_REC.CURREC_SYMBOL         = POP_HEADER.POH_CURR_CODE
      inner join PL_ADDRESSES       PL_ADDRESSES_INVOICE    on       PL_ADDRESSES_INVOICE.PL_AD_CON_CODE    = cast(POP_HEADER.POH_ACCOUNT as char(10))+convert(varchar,POP_HEADER.POH_INV_ADD)
      left  join PL_ADDRESSES       PL_ADDRESSES_DELIVERY   on       PL_ADDRESSES_DELIVERY.PL_AD_CON_CODE   = cast(POP_HEADER.POH_ACCOUNT as char(10))+convert(varchar,POP_HEADER.POH_DEL_ADD)

      inner join DOC_ORDER_DETAIL                           on       DOC_ORDER_DETAIL.DOD_HEADER_LINK       = DOC_ORDER_HEADER.DOH_PRIMARY
      inner join POP_DETAIL                                 on       POP_DETAIL.POD_PRIMARY                 = DOC_ORDER_DETAIL.DOD_ORDER_LINK
      left  join STK_STOCK                                  on       STK_STOCK.STKCODE                      = POP_DETAIL.POD_STOCK_CODE
      left  join STK_STOCK_2                                on       STK_STOCK_2.STK_PRIMARY_2              = STK_STOCK.STK_PRIMARY