CREATE VIEW AA_DASHBOARD_STK_INV_LIFE_VIEW

/*
**       
**  Written:	   Taken from AOI source code as at 25/10/07  
**  Last Amended:  N/A
*/

AS

SELECT     TOP 10 dbo.STK_STOCK.STK_PRIMARY, dbo.STK_STOCK.STKCODE, dbo.STK_STOCK.STKNAME, 

                      CASE WHEN (dbo.STK_STOCK.STK_MOVEOUT_C1 + dbo.STK_STOCK.STK_MOVEOUT_C2 + dbo.STK_STOCK.STK_MOVEOUT_C3 + dbo.STK_STOCK.STK_MOVEOUT_C4

                       + dbo.STK_STOCK.STK_MOVEOUT_C5 + dbo.STK_STOCK.STK_MOVEOUT_C6 + dbo.STK_STOCK.STK_MOVEOUT_C7 + dbo.STK_STOCK.STK_MOVEOUT_C8

                       + dbo.STK_STOCK.STK_MOVEOUT_C9 + dbo.STK_STOCK.STK_MOVEOUT_C10 + dbo.STK_STOCK.STK_MOVEOUT_C11 + dbo.STK_STOCK.STK_MOVEOUT_C12 + dbo.STK_STOCK.STK_MOVEOUT_C13)

                       > 0 THEN dbo.STK_STOCK.STK_PHYSICAL / ((dbo.STK_STOCK.STK_MOVEOUT_C1 + dbo.STK_STOCK.STK_MOVEOUT_C2 + dbo.STK_STOCK.STK_MOVEOUT_C3

                       + dbo.STK_STOCK.STK_MOVEOUT_C4 + dbo.STK_STOCK.STK_MOVEOUT_C5 + dbo.STK_STOCK.STK_MOVEOUT_C6 + dbo.STK_STOCK.STK_MOVEOUT_C7

                       + dbo.STK_STOCK.STK_MOVEOUT_C8 + dbo.STK_STOCK.STK_MOVEOUT_C9 + dbo.STK_STOCK.STK_MOVEOUT_C10 + dbo.STK_STOCK.STK_MOVEOUT_C11

                       + dbo.STK_STOCK.STK_MOVEOUT_C12 +  dbo.STK_STOCK.STK_MOVEOUT_C13) / dbo.SYS_DATAINFO.SALES_PERIOD) ELSE 9999999 END AS AVMOVEMENT, 

                      dbo.STK_STOCK.STK_PHYSICAL,dbo.STK_STOCK.STK_LEVEL, dbo.STK_STOCK.STK_SORT_KEY, 

                      dbo.STK_STOCK.STK_SORT_KEY1, dbo.STK_STOCK.STK_SORT_KEY2, dbo.STK_STOCK.STK_SORT_KEY3

FROM         dbo.STK_STOCK CROSS JOIN

                      dbo.SYS_DATAINFO

WHERE     STK_PHYSICAL > 0

ORDER BY AVMOVEMENT DESC, dbo.STK_STOCK.STKCODE