CREATE VIEW AA_DELIVERY_HISTORY_VIEW
/*
** View to combine delivery history records with either the SOP or POP order header fields
**
** Written:			19/8/2003 RL
** Last Amended:	19/8/2003 RL, 20/8/2003 RL, 15/10/2003 MIH, 8/12/2003 RL, 30/01/04 NC
*/
( DHH_ORIGIN
, DHH_ORDER_NO
, DHH_DELIVERYNOTE_NO
, DHH_SUPP_DELNOTE_NO
, DHH_ACCOUNT
, DHH_DATE_UPDATED
, DHH_DELIVERY_ADDRESS
, DHH_INVOICE_ADDRESS
, DHH_USER
, DHH_PRIMARY
, Year
, Period
, DHH_DATE_REQUIRED
, Quantity_OS
, Delivery_Note
, Account_Level
)
as
(
select
DHH_ORIGIN
, DHH_ORDER_NO
, DHH_DELIVERYNOTE_NO
, DHH_SUPP_DELNOTE_NO
, DHH_ACCOUNT
, DHH_DATE_UPDATED
, DHH_DELIVERY_ADDRESS
, DHH_INVOICE_ADDRESS
, DHH_USER
, DHH_PRIMARY
, OH_YEAR
, OH_PERIOD
, DHH_DATE_REQUIRED
, sum(DHD_QTY_OUTSTANDING)
, convert(varchar(15), DHH_DELIVERYNOTE_NO)
, CU_LEVEL
from SYS_DEL_HISTORY_HEADER, ORD_HEADER, SYS_DEL_HISTORY_DETAIL, SL_ACCOUNTS2
where DHH_ORIGIN like 'SO%' and convert(varchar(15), convert(decimal(16,0), OH_ORDER_NUMBER)) = DHH_ORDER_NO and DHD_HEADER_LINK = DHH_PRIMARY and CUCODE2 = OH_ACCOUNT_DELIVERY
group by DHH_ORIGIN
, DHH_ORDER_NO
, DHH_DELIVERYNOTE_NO
, DHH_SUPP_DELNOTE_NO
, DHH_ACCOUNT
, DHH_DATE_UPDATED
, DHH_DELIVERY_ADDRESS
, DHH_INVOICE_ADDRESS
, DHH_USER
, DHH_PRIMARY
, OH_YEAR
, OH_PERIOD
, DHH_DATE_REQUIRED
, CU_LEVEL
)
union ALL
(
select
DHH_ORIGIN
, DHH_ORDER_NO
, DHH_DELIVERYNOTE_NO
, DHH_SUPP_DELNOTE_NO
, DHH_ACCOUNT
, DHH_DATE_UPDATED
, DHH_DELIVERY_ADDRESS
, DHH_INVOICE_ADDRESS
, DHH_USER
, DHH_PRIMARY
, POH_YEAR
, POH_PERIOD
, DHH_DATE_REQUIRED
, sum(DHD_QTY_OUTSTANDING)
, DHH_SUPP_DELNOTE_NO
, SU_LEVEL
from SYS_DEL_HISTORY_HEADER, POP_HEADER, SYS_DEL_HISTORY_DETAIL, PL_ACCOUNTS2
where DHH_ORIGIN like 'PO%' and POH_ORDER_NUMBR = DHH_ORDER_NO and DHD_HEADER_LINK = DHH_PRIMARY and SUCODE2 = POH_ACCOUNT
group by DHH_ORIGIN
, DHH_ORDER_NO
, DHH_DELIVERYNOTE_NO
, DHH_SUPP_DELNOTE_NO
, DHH_ACCOUNT
, DHH_DATE_UPDATED
, DHH_DELIVERY_ADDRESS
, DHH_INVOICE_ADDRESS
, DHH_USER
, DHH_PRIMARY
, POH_YEAR
, POH_PERIOD
, DHH_DATE_REQUIRED
, SU_LEVEL
)
