CREATE VIEW AA_ED_POP_DETAIL_ANALYSIS_VIEW
AS
SELECT 	POD_ACCOUNT,
	SUNAME,
	SUSORT,
	SUUSER1,
	SUUSER2,
	SUUSER3,
	POH_SUSORT,
	POH_USER1,
	POH_USER2,
	POH_USER3,
	POH_BATCH_FLAG,
	POH_STATUS,
	POH_TYPE,
	POH_DATE,
	POH_REQUIRED,
	POD_STATUS,
	POD_ENTRY_TYPE,
	POD_REQDATE,
	POD_ANALYSIS,
	PANAME,
	CASE POH_TYPE
		WHEN 'O' THEN
			CASE POD_QTYORD
				WHEN 0 THEN 1
				ELSE POD_QTYORD END
		WHEN 'C' THEN
			CASE POD_QTYORD
				WHEN 0 THEN -1
				ELSE POD_QTYORD*-1 END
		END
AS QTYORDERED,
	CASE POH_TYPE
		WHEN 'O' THEN POD_QTYDELVD
		WHEN 'C' THEN POD_QTYDELVD*-1 END AS QTYDELIVERED,
	CASE POH_TYPE
		WHEN 'O' THEN POD_QTYINVD
		WHEN 'C' THEN POD_QTYINVD*-1 END AS QTYINVOICED,
	CASE POH_TYPE
		WHEN 'O' THEN POD_NETT
		WHEN 'C' THEN POD_NETT*-1 END AS COSTVALUE,
	CASE POH_TYPE
		WHEN 'O' THEN POD_VATAMNT
		WHEN 'C' THEN POD_VATAMNT*-1 END AS VATVALUE,
	CASE POH_TYPE
		WHEN 'O' THEN POD_GROSS
		WHEN 'C' THEN POD_GROSS*-1 END AS GROSSVALUE,
	CASE POH_TYPE
		WHEN 'O' THEN POD_L_DISCVAL
		WHEN 'C' THEN POD_L_DISCVAL*-1 END AS LINEDISCOUNT,
	CASE POH_TYPE
		WHEN 'O' THEN POD_T_DISCVAL
		WHEN 'C' THEN POD_T_DISCVAL*-1 END AS TOTALDISCOUNT,
	CASE POD_ENTRY_TYPE
		WHEN 'S' THEN POD_STOCK_CODE
		WHEN 'P' THEN POD_PRICE_CODE
		WHEN 'T' THEN SUBSTRING(POD_DETAIL,1,25) END AS PRODUCT_CODE,
	CASE POD_ENTRY_TYPE
		WHEN 'S' THEN Stock.STKNAME
		WHEN 'P' THEN Price.PRNAME
		WHEN 'T' THEN POD_DETAIL END as PRODUCT_NAME,
	CASE POD_ENTRY_TYPE
		WHEN 'S' THEN Stock.STK_SORT_KEY
		WHEN 'P' THEN Price.PR_SORT_KEY
		WHEN 'T' THEN '' END as PRODUCT_SORT_KEY,
	CASE POD_ENTRY_TYPE
		WHEN 'S' THEN Stock.STK_SORT_KEY1
		WHEN 'P' THEN Price.PR_SORT_KEY1
		WHEN 'T' THEN '' END as PRODUCT_SORT_KEY1,
	CASE POD_ENTRY_TYPE
		WHEN 'S' THEN Stock.STK_SORT_KEY2
		WHEN 'P' THEN Price.PR_SORT_KEY2
		WHEN 'T' THEN '' END as PRODUCT_SORT_KEY2,
	CASE POD_ENTRY_TYPE
		WHEN 'S' THEN Stock.STK_SORT_KEY3
		WHEN 'P' THEN Price.PR_SORT_KEY3
		WHEN 'T' THEN '' END as PRODUCT_SORT_KEY3,
POD_COSTHEADER,CH_NAME,POD_PRIMARY,POH_PRIMARY,POD_LOCATN,POD_ORDER_NO,POD_BATCH_FLAG
FROM POP_DETAIL
RIGHT JOIN POP_HEADER ON POD_ORDER_NO=POH_ORDER_NUMBR
RIGHT JOIN PL_ACCOUNTS ON POH_ACCOUNT=SUCODE
RIGHT JOIN PL_ANALYSIS ON POD_ANALYSIS=PACODE
LEFT OUTER JOIN STK_STOCK Stock ON POD_STOCK_CODE=Stock.STKCODE
LEFT OUTER JOIN PRC_PRICE_RECS Price ON POD_PRICE_CODE=Price.PRCODE
LEFT OUTER JOIN CST_COSTHEADER ON POD_COSTHEADER=CH_CODE
WHERE POD_PRIMARY IS NOT NULL