create VIEW AA_ED_NOMINAL_RECS_PR_VIEW
AS
SELECT  dbo.AA_NET_NL_RECORD_VIEW.NMAJORHEADCODE,
 dbo.AA_NET_NL_RECORD_VIEW.NCODE,
 dbo.AA_NET_NL_RECORD_VIEW.NTYPE, 
        dbo.AA_NET_NL_RECORD_VIEW.NNAME,
 CASE NL_ACCOUNTS.NCATEGORYCODE1
  WHEN '' THEN ''
  WHEN NULL THEN ''
  ELSE NL_ACCOUNTS.NCATEGORYCODE1 END
 AS NCATEGORYCODE1,
 CASE NL_ACCOUNTS.NCATEGORYCODE2
  WHEN '' THEN ''
  WHEN NULL THEN ''
  ELSE NL_ACCOUNTS.NCATEGORYCODE2 END
 AS NCATEGORYCODE2,
 CASE NL_ACCOUNTS.NCATEGORYCODE3
  WHEN '' THEN ''
  WHEN NULL THEN ''
  ELSE NL_ACCOUNTS.NCATEGORYCODE3 END
 AS NCATEGORYCODE3,
 CASE NL_ACCOUNTS.NCATEGORYCODE4
  WHEN '' THEN ''
  WHEN NULL THEN ''
  ELSE NL_ACCOUNTS.NCATEGORYCODE4 END
 AS NCATEGORYCODE4,
 CASE NL_ACCOUNTS.NCATEGORYCODE5
  WHEN '' THEN ''
  WHEN NULL THEN ''
  ELSE NL_ACCOUNTS.NCATEGORYCODE5 END
 AS NCATEGORYCODE5,
 CASE NL_ACCOUNTS.NCATEGORYCODE6
  WHEN '' THEN ''
  WHEN NULL THEN ''
  ELSE NL_ACCOUNTS.NCATEGORYCODE6 END
 AS NCATEGORYCODE6,
 CASE NL_ACCOUNTS.NCATEGORYCODE7
  WHEN '' THEN ''
  WHEN NULL THEN ''
  ELSE NL_ACCOUNTS.NCATEGORYCODE7 END
 AS NCATEGORYCODE7,
 CASE NL_ACCOUNTS.NCATEGORYCODE8
  WHEN '' THEN ''
  WHEN NULL THEN ''
  ELSE NL_ACCOUNTS.NCATEGORYCODE8 END
 AS NCATEGORYCODE8,
 dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME1, 
        dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME2,
 dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME3, 
        dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME4,
 dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME5, 
        dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME6,
 dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME7, 
        dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME8,
 dbo.NL_ACCOUNTS.NOPENBALANCELY,
 dbo.NL_ACCOUNTS.NOPENBALYEAR, 
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1
  ELSE NTURNOVER_C1
 END AS NAPROJD_C1,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2
  ELSE NTURNOVER_C1+NTURNOVER_C2
 END AS NAPROJD_C2,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3
 END AS NAPROJD_C3,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3+NBUDGET_C4
  WHEN 4 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NBUDGET_C4
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4
 END AS NAPROJD_C4,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5
  WHEN 4 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NBUDGET_C4+NBUDGET_C5
  WHEN 5 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NBUDGET_C5
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5
 END AS NAPROJD_C5,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6
  WHEN 4 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6
  WHEN 5 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NBUDGET_C5+NBUDGET_C6
  WHEN 6 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NBUDGET_C6  
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6
 END AS NAPROJD_C6,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7
  WHEN 4 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7
  WHEN 5 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7
  WHEN 6 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NBUDGET_C6+NBUDGET_C7
  WHEN 7 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NBUDGET_C7  
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7
 END AS NAPROJD_C7,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8
  WHEN 4 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8
  WHEN 5 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8
  WHEN 6 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8
  WHEN 7 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NBUDGET_C7+NBUDGET_C8  
  WHEN 8 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NBUDGET_C8  
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8
 END AS NAPROJD_C8,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9
  WHEN 4 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9
  WHEN 5 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9
  WHEN 6 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9
  WHEN 7 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9  
  WHEN 8 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NBUDGET_C8+NBUDGET_C9  
  WHEN 9 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NBUDGET_C9  
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9
 END AS NAPROJD_C9,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10
  WHEN 4 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10
  WHEN 5 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10
  WHEN 6 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10
  WHEN 7 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10 
  WHEN 8 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10 
  WHEN 9 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NBUDGET_C9+NBUDGET_C10
  WHEN 10 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NBUDGET_C10  
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10
 END AS NAPROJD_C10,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11
  WHEN 4 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11
  WHEN 5 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11
  WHEN 6 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11
  WHEN 7 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11 
  WHEN 8 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11 
  WHEN 9 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11  
  WHEN 10 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NBUDGET_C10+NBUDGET_C11
  WHEN 11 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10+NBUDGET_C11  
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10+NTURNOVER_C11
 
 END AS NAPROJD_C11,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12
  WHEN 4 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12
  WHEN 5 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12
  WHEN 6 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12
  WHEN 7 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12 
  WHEN 8 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12 
  WHEN 9 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12  
  WHEN 10 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12 
  WHEN 11 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10+NBUDGET_C11+NBUDGET_C12
  WHEN 12 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10+NTURNOVER_C11+NBUDGET_C12 
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10+NTURNOVER_C11+NTURNOVER_C12
 END AS NAPROJD_C12,
 CASE NOMINAL_PERIOD
  WHEN 1 THEN NBUDGET_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13
  WHEN 2 THEN NTURNOVER_C1+NBUDGET_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13
  WHEN 3 THEN NTURNOVER_C1+NTURNOVER_C2+NBUDGET_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13
  WHEN 4 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NBUDGET_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13
  WHEN 5 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NBUDGET_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13
  WHEN 6 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NBUDGET_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13
  WHEN 7 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NBUDGET_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13 
  WHEN 8 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NBUDGET_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13 
  WHEN 9 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NBUDGET_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13  
  WHEN 10 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NBUDGET_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13 
  WHEN 11 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10+NBUDGET_C11+NBUDGET_C12+NBUDGET_C13 
  WHEN 12 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10+NTURNOVER_C11+NBUDGET_C12+NBUDGET_C13
  WHEN 13 THEN NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10+NTURNOVER_C11+NTURNOVER_C12+NBUDGET_C13   
  ELSE NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10+NTURNOVER_C11+NTURNOVER_C12+NTURNOVER_C13
 END AS NAPROJD_C13,
        dbo.NL_ACCOUNTS.NBUDGET_C1 AS NBCCUML_C1, 
 dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2 AS NBCCUML_C2,
 dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3 AS NBCCUML_C3, 
        dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4 AS NBCCUML_C4,
 dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5 AS NBCCUML_C5,
 dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6 AS NBCCUML_C6, 
        dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7 AS NBCCUML_C7,
 dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8 AS NBCCUML_C8,
 dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8+dbo.NL_ACCOUNTS.NBUDGET_C9 AS NBCCUML_C9, 
        dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8+dbo.NL_ACCOUNTS.NBUDGET_C9+dbo.NL_ACCOUNTS.NBUDGET_C10 AS NBCCUML_C10,
 dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8+dbo.NL_ACCOUNTS.NBUDGET_C9+dbo.NL_ACCOUNTS.NBUDGET_C10+dbo.NL_ACCOUNTS.NBUDGET_C11 AS NBCCUML_C11,
 dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8+dbo.NL_ACCOUNTS.NBUDGET_C9+dbo.NL_ACCOUNTS.NBUDGET_C10+dbo.NL_ACCOUNTS.NBUDGET_C11+dbo.NL_ACCOUNTS.NBUDGET_C12 AS NBCCUML_C12,
        dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8+dbo.NL_ACCOUNTS.NBUDGET_C9+dbo.NL_ACCOUNTS.NBUDGET_C10+dbo.NL_ACCOUNTS.NBUDGET_C11+dbo.NL_ACCOUNTS.NBUDGET_C12+dbo.NL_ACCOUNTS.NBUDGET_C13 AS NBCCUML_C13
 

FROM         dbo.AA_NET_NL_RECORD_VIEW INNER JOIN
                      dbo.NL_ACCOUNTS ON dbo.AA_NET_NL_RECORD_VIEW.N_PRIMARY = dbo.NL_ACCOUNTS.N_PRIMARY
     inner join SYS_DATAINFO on sys_primary = 1
