CREATE VIEW dbo.AA_ED_SL_ANA_RECS_VIEW
AS
select SACODE,SANAME,SATYPE_S_B_D,SASORT,SAUSER1,SAUSER2,SAUSER3,
CAST(
CASE SALES_PERIOD
	WHEN 1 THEN SATURNOVR_C1
	WHEN 2 THEN SATURNOVR_C2
	WHEN 3 THEN SATURNOVR_C3
	WHEN 4 THEN SATURNOVR_C4
	WHEN 5 THEN SATURNOVR_C5
	WHEN 6 THEN SATURNOVR_C6
	WHEN 7 THEN SATURNOVR_C7
	WHEN 8 THEN SATURNOVR_C8
	WHEN 9 THEN SATURNOVR_C9
	WHEN 10 THEN SATURNOVR_C10
	WHEN 11 THEN SATURNOVR_C11
	WHEN 12 THEN SATURNOVR_C12
	WHEN 13 THEN SATURNOVR_C13
END as float) AS PTD_CURRENT_YEAR,
CAST(CASE SALES_PERIOD
	WHEN 1 THEN SATURNOVR_L1
	WHEN 2 THEN SATURNOVR_L2
	WHEN 3 THEN SATURNOVR_L3
	WHEN 4 THEN SATURNOVR_L4
	WHEN 5 THEN SATURNOVR_L5
	WHEN 6 THEN SATURNOVR_L6
	WHEN 7 THEN SATURNOVR_L7
	WHEN 8 THEN SATURNOVR_L8
	WHEN 9 THEN SATURNOVR_L9
	WHEN 10 THEN SATURNOVR_L10
	WHEN 11 THEN SATURNOVR_L11
	WHEN 12 THEN SATURNOVR_L12
	WHEN 13 THEN SATURNOVR_L13
END AS FLOAT) AS PTD_LAST_YEAR,
CAST(CASE SALES_PERIOD
	WHEN 1 THEN SATURNOVR_O1
	WHEN 2 THEN SATURNOVR_O2
	WHEN 3 THEN SATURNOVR_O3
	WHEN 4 THEN SATURNOVR_O4
	WHEN 5 THEN SATURNOVR_O5
	WHEN 6 THEN SATURNOVR_O6
	WHEN 7 THEN SATURNOVR_O7
	WHEN 8 THEN SATURNOVR_O8
	WHEN 9 THEN SATURNOVR_O9
	WHEN 10 THEN SATURNOVR_O10
	WHEN 11 THEN SATURNOVR_O11
	WHEN 12 THEN SATURNOVR_O12
	WHEN 13 THEN SATURNOVR_O13
END AS FLOAT) AS PTD_PREV_YEAR,
CAST(CASE SALES_PERIOD
	WHEN 1 THEN SATURNOVR_C1
	WHEN 2 THEN SATURNOVR_C1+SATURNOVR_C2
	WHEN 3 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3
	WHEN 4 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3+SATURNOVR_C4
	WHEN 5 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3+SATURNOVR_C4+SATURNOVR_C5
	WHEN 6 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3+SATURNOVR_C4+SATURNOVR_C5+SATURNOVR_C6
	WHEN 7 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3+SATURNOVR_C4+SATURNOVR_C5+SATURNOVR_C6+SATURNOVR_C7
	WHEN 8 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3+SATURNOVR_C4+SATURNOVR_C5+SATURNOVR_C6+SATURNOVR_C7+SATURNOVR_C8
	WHEN 9 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3+SATURNOVR_C4+SATURNOVR_C5+SATURNOVR_C6+SATURNOVR_C7+SATURNOVR_C8+SATURNOVR_C9
	WHEN 10 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3+SATURNOVR_C4+SATURNOVR_C5+SATURNOVR_C6+SATURNOVR_C7+SATURNOVR_C8+SATURNOVR_C9+SATURNOVR_C10
	WHEN 11 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3+SATURNOVR_C4+SATURNOVR_C5+SATURNOVR_C6+SATURNOVR_C7+SATURNOVR_C8+SATURNOVR_C9+SATURNOVR_C10+SATURNOVR_C11
	WHEN 12 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3+SATURNOVR_C4+SATURNOVR_C5+SATURNOVR_C6+SATURNOVR_C7+SATURNOVR_C8+SATURNOVR_C9+SATURNOVR_C10+SATURNOVR_C11+SATURNOVR_C12
	WHEN 13 THEN SATURNOVR_C1+SATURNOVR_C2+SATURNOVR_C3+SATURNOVR_C4+SATURNOVR_C5+SATURNOVR_C6+SATURNOVR_C7+SATURNOVR_C8+SATURNOVR_C9+SATURNOVR_C10+SATURNOVR_C11+SATURNOVR_C12+SATURNOVR_C13
END AS FLOAT) AS YTD_CURRENT_YEAR,
CAST(CASE SALES_PERIOD
	WHEN 1 THEN SATURNOVR_L1
	WHEN 2 THEN SATURNOVR_L1+SATURNOVR_L2
	WHEN 3 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3
	WHEN 4 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3+SATURNOVR_L4
	WHEN 5 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3+SATURNOVR_L4+SATURNOVR_L5
	WHEN 6 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3+SATURNOVR_L4+SATURNOVR_L5+SATURNOVR_L6
	WHEN 7 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3+SATURNOVR_L4+SATURNOVR_L5+SATURNOVR_L6+SATURNOVR_L7
	WHEN 8 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3+SATURNOVR_L4+SATURNOVR_L5+SATURNOVR_L6+SATURNOVR_L7+SATURNOVR_L8
	WHEN 9 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3+SATURNOVR_L4+SATURNOVR_L5+SATURNOVR_L6+SATURNOVR_L7+SATURNOVR_L8+SATURNOVR_L9
	WHEN 10 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3+SATURNOVR_L4+SATURNOVR_L5+SATURNOVR_L6+SATURNOVR_L7+SATURNOVR_L8+SATURNOVR_L9+SATURNOVR_L10
	WHEN 11 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3+SATURNOVR_L4+SATURNOVR_L5+SATURNOVR_L6+SATURNOVR_L7+SATURNOVR_L8+SATURNOVR_L9+SATURNOVR_L10+SATURNOVR_L11
	WHEN 12 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3+SATURNOVR_L4+SATURNOVR_L5+SATURNOVR_L6+SATURNOVR_L7+SATURNOVR_L8+SATURNOVR_L9+SATURNOVR_L10+SATURNOVR_L11+SATURNOVR_L12
	WHEN 13 THEN SATURNOVR_L1+SATURNOVR_L2+SATURNOVR_L3+SATURNOVR_L4+SATURNOVR_L5+SATURNOVR_L6+SATURNOVR_L7+SATURNOVR_L8+SATURNOVR_L9+SATURNOVR_L10+SATURNOVR_L11+SATURNOVR_L12+SATURNOVR_L13
END AS FLOAT) AS YTD_LAST_YEAR,
CAST(CASE SALES_PERIOD
	WHEN 1 THEN SATURNOVR_O1
	WHEN 2 THEN SATURNOVR_O1+SATURNOVR_O2
	WHEN 3 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3
	WHEN 4 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3+SATURNOVR_O4
	WHEN 5 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3+SATURNOVR_O4+SATURNOVR_O5
	WHEN 6 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3+SATURNOVR_O4+SATURNOVR_O5+SATURNOVR_O6
	WHEN 7 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3+SATURNOVR_O4+SATURNOVR_O5+SATURNOVR_O6+SATURNOVR_O7
	WHEN 8 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3+SATURNOVR_O4+SATURNOVR_O5+SATURNOVR_O6+SATURNOVR_O7+SATURNOVR_O8
	WHEN 9 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3+SATURNOVR_O4+SATURNOVR_O5+SATURNOVR_O6+SATURNOVR_O7+SATURNOVR_O8+SATURNOVR_O9
	WHEN 10 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3+SATURNOVR_O4+SATURNOVR_O5+SATURNOVR_O6+SATURNOVR_O7+SATURNOVR_O8+SATURNOVR_O9+SATURNOVR_O10
	WHEN 11 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3+SATURNOVR_O4+SATURNOVR_O5+SATURNOVR_O6+SATURNOVR_O7+SATURNOVR_O8+SATURNOVR_O9+SATURNOVR_O10+SATURNOVR_O11
	WHEN 12 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3+SATURNOVR_O4+SATURNOVR_O5+SATURNOVR_O6+SATURNOVR_O7+SATURNOVR_O8+SATURNOVR_O9+SATURNOVR_O10+SATURNOVR_O11+SATURNOVR_O12
	WHEN 13 THEN SATURNOVR_O1+SATURNOVR_O2+SATURNOVR_O3+SATURNOVR_O4+SATURNOVR_O5+SATURNOVR_O6+SATURNOVR_O7+SATURNOVR_O8+SATURNOVR_O9+SATURNOVR_O10+SATURNOVR_O11+SATURNOVR_O12+SATURNOVR_O13
END AS FLOAT) AS YTD_PREV_YEAR
FROM SL_ANALYSIS join SYS_DATAINFO on sys_primary = 1