CREATE VIEW AA_ED_SL_DET_ANA_YEAR_VIEW
AS
SELECT 	DET_ANALYSIS,
	SANAME,
	SASORT,
	SAUSER1,
	SAUSER2,
	SAUSER3,
	DET_ACCOUNT,
	CUNAME,
	CUSTOMER_SORT_KEY,
	CUSTOMER_SORT_KEY1,
	CUSTOMER_SORT_KEY2,
	CUSTOMER_SORT_KEY3,
CASE DET_PERIODNUMBR
	WHEN 1 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY1,
CASE DET_PERIODNUMBR
	WHEN 2 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY2,
CASE DET_PERIODNUMBR
	WHEN 3 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY3,
CASE DET_PERIODNUMBR
	WHEN 4 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY4,
CASE DET_PERIODNUMBR
	WHEN 5 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY5,
CASE DET_PERIODNUMBR
	WHEN 6 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY6,
CASE DET_PERIODNUMBR
	WHEN 7 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY7,
CASE DET_PERIODNUMBR
	WHEN 8 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY8,
CASE DET_PERIODNUMBR
	WHEN 9 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY9,
CASE DET_PERIODNUMBR
	WHEN 10 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY10,
CASE DET_PERIODNUMBR
	WHEN 11 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY11,
CASE DET_PERIODNUMBR
	WHEN 12 THEN TRAN_QUANTITY
	ELSE 0 END AS PERIODQTY12,
CASE DET_PERIODNUMBR
	WHEN 1 THEN TRAN_NET
	ELSE 0 END AS PERIODNET1,
CASE DET_PERIODNUMBR
	WHEN 2 THEN TRAN_NET
	ELSE 0 END AS PERIODNET2,
CASE DET_PERIODNUMBR
	WHEN 3 THEN TRAN_NET
	ELSE 0 END AS PERIODNET3,
CASE DET_PERIODNUMBR
	WHEN 4 THEN TRAN_NET
	ELSE 0 END AS PERIODNET4,
CASE DET_PERIODNUMBR
	WHEN 5 THEN TRAN_NET
	ELSE 0 END AS PERIODNET5,
CASE DET_PERIODNUMBR
	WHEN 6 THEN TRAN_NET
	ELSE 0 END AS PERIODNET6,
CASE DET_PERIODNUMBR
	WHEN 7 THEN TRAN_NET
	ELSE 0 END AS PERIODNET7,
CASE DET_PERIODNUMBR
	WHEN 8 THEN TRAN_NET
	ELSE 0 END AS PERIODNET8,
CASE DET_PERIODNUMBR
	WHEN 9 THEN TRAN_NET
	ELSE 0 END AS PERIODNET9,
CASE DET_PERIODNUMBR
	WHEN 10 THEN TRAN_NET
	ELSE 0 END AS PERIODNET10,
CASE DET_PERIODNUMBR
	WHEN 11 THEN TRAN_NET
	ELSE 0 END AS PERIODNET11,
CASE DET_PERIODNUMBR
	WHEN 12 THEN TRAN_NET
	ELSE 0 END AS PERIODNET12
FROM AA_ED_SALES_DETAIL_ANALYSIS_ANA_VIEW WHERE (DET_PERIOD_SORT>=14 and DET_PERIOD_SORT<=26)