CREATE VIEW dbo.AA_ED_PROJECT_RECS_VIEW
AS
SELECT     CH_CODE, CH_NAME, CH_PRIMARY, CH_ACTUAL_COST, CH_COMITT_COST, CH_ACTUAL_SALES, CH_COMITT_SALES, CH_STATUS, CH_SORT, 
                      CH_USER_COST1, CH_USER_COST2, CH_WIP, CH_WIP_UPLIFT, CH_COST_CNTUPV, CH_COST_RESUPV, CH_SALE_INVTD, CH_TIMECOSTINV, 
                      CH_GENCOSTINV, CH_DATE_USER1, CH_DATE_USER2, CH_DATE_USER3, CH_DATE_EST, CH_DATE_REQ, CH_DURATION, CH_DUR_TYPE, 
                      CH_USER1, CH_USER2, CH_USER3, CH_USER4, CH_USER5, CH_USER6, CH_ACCOUNT, CUNAME, CH_COST_INVTD, CH_COST_PAYTD, 
                      CH_COST_OBUDG1, CH_COST_RBUDG2, CH_COST_O_1, CH_COST_O_2, CH_COST_O_3, CH_COST_O_4, CH_COST_O_5, CH_COST_O_6, 
                      CH_COST_O_7, CH_COST_O_8, CH_COST_O_9, CH_COST_O_10, CH_COST_O_11, CH_COST_O_12, CH_COST_O_13, CH_COST_L_1, CH_COST_L_2, 
                      CH_COST_L_3, CH_COST_L_4, CH_COST_L_5, CH_COST_L_6, CH_COST_L_7, CH_COST_L_8, CH_COST_L_9, CH_COST_L_10, CH_COST_L_11, 
                      CH_COST_L_12, CH_COST_L_13, CH_COST_C_1, CH_COST_C_2, CH_COST_C_3, CH_COST_C_4, CH_COST_C_5, CH_COST_C_6, CH_COST_C_7, 
                      CH_COST_C_8, CH_COST_C_9, CH_COST_C_10, CH_COST_C_11, CH_COST_C_12, CH_COST_C_13, CASE WHEN isnull(CH_COST_RBUDG2, 0) 
                      = 0 THEN CH_COST_OBUDG1 ELSE CH_COST_RBUDG2 END AS CURRENT_CBUDGET, CASE WHEN isnull(CH_SALE_RBUDG2, 0) 
                      = 0 THEN CH_SALE_OBUDG1 ELSE CH_SALE_RBUDG2 END AS CURRENT_SBUDGET, DATEDIFF(d, getdate(), CH_DATE_REQ) AS SHORTFALL
FROM         CST_COSTHEADER LEFT JOIN
                      AA_ED_CUSTOMER_PROSPECT_VIEW ON CH_ACCOUNT = CUSTOMER_CODE AND isnull(CH_ACCOUNT, '') <> ''
