CREATE VIEW dbo.AA_ED_CUSTOMER_RECS_VIEW
AS
select CUCODE,CUNAME,CUSORT,CUUSER1,CUUSER2,CUUSER3,CUPOSTCODE,CUPHONE,CUFAX,CUCONTACT,CUBALANCE,
CAST(
CASE SALES_PERIOD
	WHEN 1 THEN CUTURNOVR_C1
	WHEN 2 THEN CUTURNOVR_C2
	WHEN 3 THEN CUTURNOVR_C3
	WHEN 4 THEN CUTURNOVR_C4
	WHEN 5 THEN CUTURNOVR_C5
	WHEN 6 THEN CUTURNOVR_C6
	WHEN 7 THEN CUTURNOVR_C7
	WHEN 8 THEN CUTURNOVR_C8
	WHEN 9 THEN CUTURNOVR_C9
	WHEN 10 THEN CUTURNOVR_C10
	WHEN 11 THEN CUTURNOVR_C11
	WHEN 12 THEN CUTURNOVR_C12
	WHEN 13 THEN CUTURNOVR_C13
END as float) AS PTD_CURRENT_YEAR,
CAST(CASE SALES_PERIOD
	WHEN 1 THEN CUTURNOVR_L1
	WHEN 2 THEN CUTURNOVR_L2
	WHEN 3 THEN CUTURNOVR_L3
	WHEN 4 THEN CUTURNOVR_L4
	WHEN 5 THEN CUTURNOVR_L5
	WHEN 6 THEN CUTURNOVR_L6
	WHEN 7 THEN CUTURNOVR_L7
	WHEN 8 THEN CUTURNOVR_L8
	WHEN 9 THEN CUTURNOVR_L9
	WHEN 10 THEN CUTURNOVR_L10
	WHEN 11 THEN CUTURNOVR_L11
	WHEN 12 THEN CUTURNOVR_L12
	WHEN 13 THEN CUTURNOVR_L13
END AS FLOAT) AS PTD_LAST_YEAR,
CAST(CASE SALES_PERIOD
	WHEN 1 THEN CUTURNOVR_O1
	WHEN 2 THEN CUTURNOVR_O2
	WHEN 3 THEN CUTURNOVR_O3
	WHEN 4 THEN CUTURNOVR_O4
	WHEN 5 THEN CUTURNOVR_O5
	WHEN 6 THEN CUTURNOVR_O6
	WHEN 7 THEN CUTURNOVR_O7
	WHEN 8 THEN CUTURNOVR_O8
	WHEN 9 THEN CUTURNOVR_O9
	WHEN 10 THEN CUTURNOVR_O10
	WHEN 11 THEN CUTURNOVR_O11
	WHEN 12 THEN CUTURNOVR_O12
	WHEN 13 THEN CUTURNOVR_O13
END AS FLOAT) AS PTD_PREV_YEAR,
CAST(CASE SALES_PERIOD
	WHEN 1 THEN CUTURNOVR_C1
	WHEN 2 THEN CUTURNOVR_C1+CUTURNOVR_C2
	WHEN 3 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3
	WHEN 4 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3+CUTURNOVR_C4
	WHEN 5 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3+CUTURNOVR_C4+CUTURNOVR_C5
	WHEN 6 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3+CUTURNOVR_C4+CUTURNOVR_C5+CUTURNOVR_C6
	WHEN 7 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3+CUTURNOVR_C4+CUTURNOVR_C5+CUTURNOVR_C6+CUTURNOVR_C7
	WHEN 8 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3+CUTURNOVR_C4+CUTURNOVR_C5+CUTURNOVR_C6+CUTURNOVR_C7+CUTURNOVR_C8
	WHEN 9 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3+CUTURNOVR_C4+CUTURNOVR_C5+CUTURNOVR_C6+CUTURNOVR_C7+CUTURNOVR_C8+CUTURNOVR_C9
	WHEN 10 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3+CUTURNOVR_C4+CUTURNOVR_C5+CUTURNOVR_C6+CUTURNOVR_C7+CUTURNOVR_C8+CUTURNOVR_C9+CUTURNOVR_C10
	WHEN 11 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3+CUTURNOVR_C4+CUTURNOVR_C5+CUTURNOVR_C6+CUTURNOVR_C7+CUTURNOVR_C8+CUTURNOVR_C9+CUTURNOVR_C10+CUTURNOVR_C11
	WHEN 12 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3+CUTURNOVR_C4+CUTURNOVR_C5+CUTURNOVR_C6+CUTURNOVR_C7+CUTURNOVR_C8+CUTURNOVR_C9+CUTURNOVR_C10+CUTURNOVR_C11+CUTURNOVR_C12
	WHEN 13 THEN CUTURNOVR_C1+CUTURNOVR_C2+CUTURNOVR_C3+CUTURNOVR_C4+CUTURNOVR_C5+CUTURNOVR_C6+CUTURNOVR_C7+CUTURNOVR_C8+CUTURNOVR_C9+CUTURNOVR_C10+CUTURNOVR_C11+CUTURNOVR_C12+CUTURNOVR_C13
END AS FLOAT) AS YTD_CURRENT_YEAR,
CAST(CASE SALES_PERIOD
	WHEN 1 THEN CUTURNOVR_L1
	WHEN 2 THEN CUTURNOVR_L1+CUTURNOVR_L2
	WHEN 3 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3
	WHEN 4 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3+CUTURNOVR_L4
	WHEN 5 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3+CUTURNOVR_L4+CUTURNOVR_L5
	WHEN 6 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3+CUTURNOVR_L4+CUTURNOVR_L5+CUTURNOVR_L6
	WHEN 7 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3+CUTURNOVR_L4+CUTURNOVR_L5+CUTURNOVR_L6+CUTURNOVR_L7
	WHEN 8 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3+CUTURNOVR_L4+CUTURNOVR_L5+CUTURNOVR_L6+CUTURNOVR_L7+CUTURNOVR_L8
	WHEN 9 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3+CUTURNOVR_L4+CUTURNOVR_L5+CUTURNOVR_L6+CUTURNOVR_L7+CUTURNOVR_L8+CUTURNOVR_L9
	WHEN 10 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3+CUTURNOVR_L4+CUTURNOVR_L5+CUTURNOVR_L6+CUTURNOVR_L7+CUTURNOVR_L8+CUTURNOVR_L9+CUTURNOVR_L10
	WHEN 11 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3+CUTURNOVR_L4+CUTURNOVR_L5+CUTURNOVR_L6+CUTURNOVR_L7+CUTURNOVR_L8+CUTURNOVR_L9+CUTURNOVR_L10+CUTURNOVR_L11
	WHEN 12 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3+CUTURNOVR_L4+CUTURNOVR_L5+CUTURNOVR_L6+CUTURNOVR_L7+CUTURNOVR_L8+CUTURNOVR_L9+CUTURNOVR_L10+CUTURNOVR_L11+CUTURNOVR_L12
	WHEN 13 THEN CUTURNOVR_L1+CUTURNOVR_L2+CUTURNOVR_L3+CUTURNOVR_L4+CUTURNOVR_L5+CUTURNOVR_L6+CUTURNOVR_L7+CUTURNOVR_L8+CUTURNOVR_L9+CUTURNOVR_L10+CUTURNOVR_L11+CUTURNOVR_L12+CUTURNOVR_L13
END AS FLOAT) AS YTD_LAST_YEAR,
CAST(CASE SALES_PERIOD
	WHEN 1 THEN CUTURNOVR_O1
	WHEN 2 THEN CUTURNOVR_O1+CUTURNOVR_O2
	WHEN 3 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3
	WHEN 4 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3+CUTURNOVR_O4
	WHEN 5 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3+CUTURNOVR_O4+CUTURNOVR_O5
	WHEN 6 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3+CUTURNOVR_O4+CUTURNOVR_O5+CUTURNOVR_O6
	WHEN 7 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3+CUTURNOVR_O4+CUTURNOVR_O5+CUTURNOVR_O6+CUTURNOVR_O7
	WHEN 8 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3+CUTURNOVR_O4+CUTURNOVR_O5+CUTURNOVR_O6+CUTURNOVR_O7+CUTURNOVR_O8
	WHEN 9 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3+CUTURNOVR_O4+CUTURNOVR_O5+CUTURNOVR_O6+CUTURNOVR_O7+CUTURNOVR_O8+CUTURNOVR_O9
	WHEN 10 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3+CUTURNOVR_O4+CUTURNOVR_O5+CUTURNOVR_O6+CUTURNOVR_O7+CUTURNOVR_O8+CUTURNOVR_O9+CUTURNOVR_O10
	WHEN 11 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3+CUTURNOVR_O4+CUTURNOVR_O5+CUTURNOVR_O6+CUTURNOVR_O7+CUTURNOVR_O8+CUTURNOVR_O9+CUTURNOVR_O10+CUTURNOVR_O11
	WHEN 12 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3+CUTURNOVR_O4+CUTURNOVR_O5+CUTURNOVR_O6+CUTURNOVR_O7+CUTURNOVR_O8+CUTURNOVR_O9+CUTURNOVR_O10+CUTURNOVR_O11+CUTURNOVR_O12
	WHEN 13 THEN CUTURNOVR_O1+CUTURNOVR_O2+CUTURNOVR_O3+CUTURNOVR_O4+CUTURNOVR_O5+CUTURNOVR_O6+CUTURNOVR_O7+CUTURNOVR_O8+CUTURNOVR_O9+CUTURNOVR_O10+CUTURNOVR_O11+CUTURNOVR_O12+CUTURNOVR_O13
END AS FLOAT) AS YTD_PREV_YEAR
FROM SL_ACCOUNTS join SYS_DATAINFO on SYS_PRIMARY = 1



