create VIEW AA_ED_CUSTOMER_PROSPECT_VIEW
AS
SELECT  CASE ISNULL(CUCODE,'')
 WHEN '' THEN CUPROSCODE
 ELSE CUCODE END AS CUSTOMER_CODE,
 CASE ISNULL(CUCODE,'')
 WHEN '' THEN 'Prospect'
 ELSE 'Customer' END AS CUSTOMER_TYPE,
 CUNAME,
 CUCONTACT,
 CUPOSTCODE,
 CUSORT,
 CUUSER1,
 CUUSER2,
 CUPHONE,
 CUFAX,
 CU_PRIMARY,
 CU_DEALERCODE,
 CU_DATE_PUTIN,
 CUUSER3
FROM SL_ACCOUNTS
