CREATE VIEW AA_ED_NOMINAL_RECS_AC_VIEW
AS
SELECT  dbo.AA_NET_NL_RECORD_VIEW.NMAJORHEADCODE,
	dbo.AA_NET_NL_RECORD_VIEW.NCODE,
	dbo.AA_NET_NL_RECORD_VIEW.NTYPE, 
        dbo.AA_NET_NL_RECORD_VIEW.NNAME,
	CASE NL_ACCOUNTS.NCATEGORYCODE1
		WHEN '' THEN ''
		WHEN NULL THEN ''
		ELSE NL_ACCOUNTS.NCATEGORYCODE1 END
	AS NCATEGORYCODE1,
	CASE NL_ACCOUNTS.NCATEGORYCODE2
		WHEN '' THEN ''
		WHEN NULL THEN ''
		ELSE NL_ACCOUNTS.NCATEGORYCODE2 END
	AS NCATEGORYCODE2,
	CASE NL_ACCOUNTS.NCATEGORYCODE3
		WHEN '' THEN ''
		WHEN NULL THEN ''
		ELSE NL_ACCOUNTS.NCATEGORYCODE3 END
	AS NCATEGORYCODE3,
	CASE NL_ACCOUNTS.NCATEGORYCODE4
		WHEN '' THEN ''
		WHEN NULL THEN ''
		ELSE NL_ACCOUNTS.NCATEGORYCODE4 END
	AS NCATEGORYCODE4,
	CASE NL_ACCOUNTS.NCATEGORYCODE5
		WHEN '' THEN ''
		WHEN NULL THEN ''
		ELSE NL_ACCOUNTS.NCATEGORYCODE5 END
	AS NCATEGORYCODE5,
	CASE NL_ACCOUNTS.NCATEGORYCODE6
		WHEN '' THEN ''
		WHEN NULL THEN ''
		ELSE NL_ACCOUNTS.NCATEGORYCODE6 END
	AS NCATEGORYCODE6,
	CASE NL_ACCOUNTS.NCATEGORYCODE7
		WHEN '' THEN ''
		WHEN NULL THEN ''
		ELSE NL_ACCOUNTS.NCATEGORYCODE7 END
	AS NCATEGORYCODE7,
	CASE NL_ACCOUNTS.NCATEGORYCODE8
		WHEN '' THEN ''
		WHEN NULL THEN ''
		ELSE NL_ACCOUNTS.NCATEGORYCODE8 END
	AS NCATEGORYCODE8,
	dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME1, 
        dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME2,
	dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME3, 
        dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME4,
	dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME5, 
        dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME6,
	dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME7, 
        dbo.AA_NET_NL_RECORD_VIEW.CATEGORY_NAME8,
	dbo.NL_ACCOUNTS.NOPENBALANCELY,
	dbo.NL_ACCOUNTS.NOPENBALYEAR, 
        dbo.NL_ACCOUNTS.NTURNOVER_L1 AS NACCUML_L1, 
	dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2 AS NACCUML_L2,
	dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3 AS NACCUML_L3, 
        dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3+dbo.NL_ACCOUNTS.NTURNOVER_L4 AS NACCUML_L4,
	dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3+dbo.NL_ACCOUNTS.NTURNOVER_L4+dbo.NL_ACCOUNTS.NTURNOVER_L5 AS NACCUML_L5,
	dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3+dbo.NL_ACCOUNTS.NTURNOVER_L4+dbo.NL_ACCOUNTS.NTURNOVER_L5+dbo.NL_ACCOUNTS.NTURNOVER_L6 AS NACCUML_L6, 
        dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3+dbo.NL_ACCOUNTS.NTURNOVER_L4+dbo.NL_ACCOUNTS.NTURNOVER_L5+dbo.NL_ACCOUNTS.NTURNOVER_L6+dbo.NL_ACCOUNTS.NTURNOVER_L7 AS NACCUML_L7,
	dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3+dbo.NL_ACCOUNTS.NTURNOVER_L4+dbo.NL_ACCOUNTS.NTURNOVER_L5+dbo.NL_ACCOUNTS.NTURNOVER_L6+dbo.NL_ACCOUNTS.NTURNOVER_L7+dbo.NL_ACCOUNTS.NTURNOVER_L8 AS NACCUML_L8,
	dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3+dbo.NL_ACCOUNTS.NTURNOVER_L4+dbo.NL_ACCOUNTS.NTURNOVER_L5+dbo.NL_ACCOUNTS.NTURNOVER_L6+dbo.NL_ACCOUNTS.NTURNOVER_L7+dbo.NL_ACCOUNTS.NTURNOVER_L8+dbo.NL_ACCOUNTS.NTURNOVER_L9 AS NACCUML_L9, 
        dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3+dbo.NL_ACCOUNTS.NTURNOVER_L4+dbo.NL_ACCOUNTS.NTURNOVER_L5+dbo.NL_ACCOUNTS.NTURNOVER_L6+dbo.NL_ACCOUNTS.NTURNOVER_L7+dbo.NL_ACCOUNTS.NTURNOVER_L8+dbo.NL_ACCOUNTS.NTURNOVER_L9+dbo.NL_ACCOUNTS.NTURNOVER_L10 AS NACCUML_L10,
	dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3+dbo.NL_ACCOUNTS.NTURNOVER_L4+dbo.NL_ACCOUNTS.NTURNOVER_L5+dbo.NL_ACCOUNTS.NTURNOVER_L6+dbo.NL_ACCOUNTS.NTURNOVER_L7+dbo.NL_ACCOUNTS.NTURNOVER_L8+dbo.NL_ACCOUNTS.NTURNOVER_L9+dbo.NL_ACCOUNTS.NTURNOVER_L10+dbo.NL_ACCOUNTS.NTURNOVER_L11 AS NACCUML_L11,
	dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3+dbo.NL_ACCOUNTS.NTURNOVER_L4+dbo.NL_ACCOUNTS.NTURNOVER_L5+dbo.NL_ACCOUNTS.NTURNOVER_L6+dbo.NL_ACCOUNTS.NTURNOVER_L7+dbo.NL_ACCOUNTS.NTURNOVER_L8+dbo.NL_ACCOUNTS.NTURNOVER_L9+dbo.NL_ACCOUNTS.NTURNOVER_L10+dbo.NL_ACCOUNTS.NTURNOVER_L11+dbo.NL_ACCOUNTS.NTURNOVER_L12 AS NACCUML_L12,
        dbo.NL_ACCOUNTS.NTURNOVER_L1+dbo.NL_ACCOUNTS.NTURNOVER_L2+Dbo.NL_ACCOUNTS.NTURNOVER_L3+dbo.NL_ACCOUNTS.NTURNOVER_L4+dbo.NL_ACCOUNTS.NTURNOVER_L5+dbo.NL_ACCOUNTS.NTURNOVER_L6+dbo.NL_ACCOUNTS.NTURNOVER_L7+dbo.NL_ACCOUNTS.NTURNOVER_L8+dbo.NL_ACCOUNTS.NTURNOVER_L9+dbo.NL_ACCOUNTS.NTURNOVER_L10+dbo.NL_ACCOUNTS.NTURNOVER_L11+dbo.NL_ACCOUNTS.NTURNOVER_L12+dbo.NL_ACCOUNTS.NTURNOVER_L13 AS NACCUML_L13,
        dbo.NL_ACCOUNTS.NBUDGET_L1 AS NBCCUML_L1, 
	dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2 AS NBCCUML_L2,
	dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3 AS NBCCUML_L3, 
        dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3+dbo.NL_ACCOUNTS.NBUDGET_L4 AS NBCCUML_L4,
	dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3+dbo.NL_ACCOUNTS.NBUDGET_L4+dbo.NL_ACCOUNTS.NBUDGET_L5 AS NBCCUML_L5,
	dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3+dbo.NL_ACCOUNTS.NBUDGET_L4+dbo.NL_ACCOUNTS.NBUDGET_L5+dbo.NL_ACCOUNTS.NBUDGET_L6 AS NBCCUML_L6, 
        dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3+dbo.NL_ACCOUNTS.NBUDGET_L4+dbo.NL_ACCOUNTS.NBUDGET_L5+dbo.NL_ACCOUNTS.NBUDGET_L6+dbo.NL_ACCOUNTS.NBUDGET_L7 AS NBCCUML_L7,
	dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3+dbo.NL_ACCOUNTS.NBUDGET_L4+dbo.NL_ACCOUNTS.NBUDGET_L5+dbo.NL_ACCOUNTS.NBUDGET_L6+dbo.NL_ACCOUNTS.NBUDGET_L7+dbo.NL_ACCOUNTS.NBUDGET_L8 AS NBCCUML_L8,
	dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3+dbo.NL_ACCOUNTS.NBUDGET_L4+dbo.NL_ACCOUNTS.NBUDGET_L5+dbo.NL_ACCOUNTS.NBUDGET_L6+dbo.NL_ACCOUNTS.NBUDGET_L7+dbo.NL_ACCOUNTS.NBUDGET_L8+dbo.NL_ACCOUNTS.NBUDGET_L9 AS NBCCUML_L9, 
        dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3+dbo.NL_ACCOUNTS.NBUDGET_L4+dbo.NL_ACCOUNTS.NBUDGET_L5+dbo.NL_ACCOUNTS.NBUDGET_L6+dbo.NL_ACCOUNTS.NBUDGET_L7+dbo.NL_ACCOUNTS.NBUDGET_L8+dbo.NL_ACCOUNTS.NBUDGET_L9+dbo.NL_ACCOUNTS.NBUDGET_L10 AS NBCCUML_L10,
	dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3+dbo.NL_ACCOUNTS.NBUDGET_L4+dbo.NL_ACCOUNTS.NBUDGET_L5+dbo.NL_ACCOUNTS.NBUDGET_L6+dbo.NL_ACCOUNTS.NBUDGET_L7+dbo.NL_ACCOUNTS.NBUDGET_L8+dbo.NL_ACCOUNTS.NBUDGET_L9+dbo.NL_ACCOUNTS.NBUDGET_L10+dbo.NL_ACCOUNTS.NBUDGET_L11 AS NBCCUML_L11,
	dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3+dbo.NL_ACCOUNTS.NBUDGET_L4+dbo.NL_ACCOUNTS.NBUDGET_L5+dbo.NL_ACCOUNTS.NBUDGET_L6+dbo.NL_ACCOUNTS.NBUDGET_L7+dbo.NL_ACCOUNTS.NBUDGET_L8+dbo.NL_ACCOUNTS.NBUDGET_L9+dbo.NL_ACCOUNTS.NBUDGET_L10+dbo.NL_ACCOUNTS.NBUDGET_L11+dbo.NL_ACCOUNTS.NBUDGET_L12 AS NBCCUML_L12,
        dbo.NL_ACCOUNTS.NBUDGET_L1+dbo.NL_ACCOUNTS.NBUDGET_L2+Dbo.NL_ACCOUNTS.NBUDGET_L3+dbo.NL_ACCOUNTS.NBUDGET_L4+dbo.NL_ACCOUNTS.NBUDGET_L5+dbo.NL_ACCOUNTS.NBUDGET_L6+dbo.NL_ACCOUNTS.NBUDGET_L7+dbo.NL_ACCOUNTS.NBUDGET_L8+dbo.NL_ACCOUNTS.NBUDGET_L9+dbo.NL_ACCOUNTS.NBUDGET_L10+dbo.NL_ACCOUNTS.NBUDGET_L11+dbo.NL_ACCOUNTS.NBUDGET_L12+dbo.NL_ACCOUNTS.NBUDGET_L13 AS NBCCUML_L13,
        dbo.NL_ACCOUNTS.NTURNOVER_C1 AS NACCUML_C1, 
	dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2 AS NACCUML_C2,
	dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3 AS NACCUML_C3, 
        dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3+dbo.NL_ACCOUNTS.NTURNOVER_C4 AS NACCUML_C4,
	dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3+dbo.NL_ACCOUNTS.NTURNOVER_C4+dbo.NL_ACCOUNTS.NTURNOVER_C5 AS NACCUML_C5,
	dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3+dbo.NL_ACCOUNTS.NTURNOVER_C4+dbo.NL_ACCOUNTS.NTURNOVER_C5+dbo.NL_ACCOUNTS.NTURNOVER_C6 AS NACCUML_C6, 
        dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3+dbo.NL_ACCOUNTS.NTURNOVER_C4+dbo.NL_ACCOUNTS.NTURNOVER_C5+dbo.NL_ACCOUNTS.NTURNOVER_C6+dbo.NL_ACCOUNTS.NTURNOVER_C7 AS NACCUML_C7,
	dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3+dbo.NL_ACCOUNTS.NTURNOVER_C4+dbo.NL_ACCOUNTS.NTURNOVER_C5+dbo.NL_ACCOUNTS.NTURNOVER_C6+dbo.NL_ACCOUNTS.NTURNOVER_C7+dbo.NL_ACCOUNTS.NTURNOVER_C8 AS NACCUML_C8,
	dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3+dbo.NL_ACCOUNTS.NTURNOVER_C4+dbo.NL_ACCOUNTS.NTURNOVER_C5+dbo.NL_ACCOUNTS.NTURNOVER_C6+dbo.NL_ACCOUNTS.NTURNOVER_C7+dbo.NL_ACCOUNTS.NTURNOVER_C8+dbo.NL_ACCOUNTS.NTURNOVER_C9 AS NACCUML_C9, 
        dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3+dbo.NL_ACCOUNTS.NTURNOVER_C4+dbo.NL_ACCOUNTS.NTURNOVER_C5+dbo.NL_ACCOUNTS.NTURNOVER_C6+dbo.NL_ACCOUNTS.NTURNOVER_C7+dbo.NL_ACCOUNTS.NTURNOVER_C8+dbo.NL_ACCOUNTS.NTURNOVER_C9+dbo.NL_ACCOUNTS.NTURNOVER_C10 AS NACCUML_C10,
	dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3+dbo.NL_ACCOUNTS.NTURNOVER_C4+dbo.NL_ACCOUNTS.NTURNOVER_C5+dbo.NL_ACCOUNTS.NTURNOVER_C6+dbo.NL_ACCOUNTS.NTURNOVER_C7+dbo.NL_ACCOUNTS.NTURNOVER_C8+dbo.NL_ACCOUNTS.NTURNOVER_C9+dbo.NL_ACCOUNTS.NTURNOVER_C10+dbo.NL_ACCOUNTS.NTURNOVER_C11 AS NACCUML_C11,
	dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3+dbo.NL_ACCOUNTS.NTURNOVER_C4+dbo.NL_ACCOUNTS.NTURNOVER_C5+dbo.NL_ACCOUNTS.NTURNOVER_C6+dbo.NL_ACCOUNTS.NTURNOVER_C7+dbo.NL_ACCOUNTS.NTURNOVER_C8+dbo.NL_ACCOUNTS.NTURNOVER_C9+dbo.NL_ACCOUNTS.NTURNOVER_C10+dbo.NL_ACCOUNTS.NTURNOVER_C11+dbo.NL_ACCOUNTS.NTURNOVER_C12 AS NACCUML_C12,
        dbo.NL_ACCOUNTS.NTURNOVER_C1+dbo.NL_ACCOUNTS.NTURNOVER_C2+Dbo.NL_ACCOUNTS.NTURNOVER_C3+dbo.NL_ACCOUNTS.NTURNOVER_C4+dbo.NL_ACCOUNTS.NTURNOVER_C5+dbo.NL_ACCOUNTS.NTURNOVER_C6+dbo.NL_ACCOUNTS.NTURNOVER_C7+dbo.NL_ACCOUNTS.NTURNOVER_C8+dbo.NL_ACCOUNTS.NTURNOVER_C9+dbo.NL_ACCOUNTS.NTURNOVER_C10+dbo.NL_ACCOUNTS.NTURNOVER_C11+dbo.NL_ACCOUNTS.NTURNOVER_C12+dbo.NL_ACCOUNTS.NTURNOVER_C13 AS NACCUML_C13,
        dbo.NL_ACCOUNTS.NBUDGET_N1 AS NBCCUML_N1, 
	dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2 AS NBCCUML_N2,
	dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3 AS NBCCUML_N3, 
        dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3+dbo.NL_ACCOUNTS.NBUDGET_N4 AS NBCCUML_N4,
	dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3+dbo.NL_ACCOUNTS.NBUDGET_N4+dbo.NL_ACCOUNTS.NBUDGET_N5 AS NBCCUML_N5,
	dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3+dbo.NL_ACCOUNTS.NBUDGET_N4+dbo.NL_ACCOUNTS.NBUDGET_N5+dbo.NL_ACCOUNTS.NBUDGET_N6 AS NBCCUML_N6, 
        dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3+dbo.NL_ACCOUNTS.NBUDGET_N4+dbo.NL_ACCOUNTS.NBUDGET_N5+dbo.NL_ACCOUNTS.NBUDGET_N6+dbo.NL_ACCOUNTS.NBUDGET_N7 AS NBCCUML_N7,
	dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3+dbo.NL_ACCOUNTS.NBUDGET_N4+dbo.NL_ACCOUNTS.NBUDGET_N5+dbo.NL_ACCOUNTS.NBUDGET_N6+dbo.NL_ACCOUNTS.NBUDGET_N7+dbo.NL_ACCOUNTS.NBUDGET_N8 AS NBCCUML_N8,
	dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3+dbo.NL_ACCOUNTS.NBUDGET_N4+dbo.NL_ACCOUNTS.NBUDGET_N5+dbo.NL_ACCOUNTS.NBUDGET_N6+dbo.NL_ACCOUNTS.NBUDGET_N7+dbo.NL_ACCOUNTS.NBUDGET_N8+dbo.NL_ACCOUNTS.NBUDGET_N9 AS NBCCUML_N9, 
        dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3+dbo.NL_ACCOUNTS.NBUDGET_N4+dbo.NL_ACCOUNTS.NBUDGET_N5+dbo.NL_ACCOUNTS.NBUDGET_N6+dbo.NL_ACCOUNTS.NBUDGET_N7+dbo.NL_ACCOUNTS.NBUDGET_N8+dbo.NL_ACCOUNTS.NBUDGET_N9+dbo.NL_ACCOUNTS.NBUDGET_N10 AS NBCCUML_N10,
	dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3+dbo.NL_ACCOUNTS.NBUDGET_N4+dbo.NL_ACCOUNTS.NBUDGET_N5+dbo.NL_ACCOUNTS.NBUDGET_N6+dbo.NL_ACCOUNTS.NBUDGET_N7+dbo.NL_ACCOUNTS.NBUDGET_N8+dbo.NL_ACCOUNTS.NBUDGET_N9+dbo.NL_ACCOUNTS.NBUDGET_N10+dbo.NL_ACCOUNTS.NBUDGET_N11 AS NBCCUML_N11,
	dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3+dbo.NL_ACCOUNTS.NBUDGET_N4+dbo.NL_ACCOUNTS.NBUDGET_N5+dbo.NL_ACCOUNTS.NBUDGET_N6+dbo.NL_ACCOUNTS.NBUDGET_N7+dbo.NL_ACCOUNTS.NBUDGET_N8+dbo.NL_ACCOUNTS.NBUDGET_N9+dbo.NL_ACCOUNTS.NBUDGET_N10+dbo.NL_ACCOUNTS.NBUDGET_N11+dbo.NL_ACCOUNTS.NBUDGET_N12 AS NBCCUML_N12,
        dbo.NL_ACCOUNTS.NBUDGET_N1+dbo.NL_ACCOUNTS.NBUDGET_N2+Dbo.NL_ACCOUNTS.NBUDGET_N3+dbo.NL_ACCOUNTS.NBUDGET_N4+dbo.NL_ACCOUNTS.NBUDGET_N5+dbo.NL_ACCOUNTS.NBUDGET_N6+dbo.NL_ACCOUNTS.NBUDGET_N7+dbo.NL_ACCOUNTS.NBUDGET_N8+dbo.NL_ACCOUNTS.NBUDGET_N9+dbo.NL_ACCOUNTS.NBUDGET_N10+dbo.NL_ACCOUNTS.NBUDGET_N11+dbo.NL_ACCOUNTS.NBUDGET_N12+dbo.NL_ACCOUNTS.NBUDGET_N13 AS NBCCUML_N13,
        dbo.NL_ACCOUNTS.NTURNOVER_N1 AS NACCUML_N1, 
	dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2 AS NACCUML_N2,
	dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3 AS NACCUML_N3, 
        dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3+dbo.NL_ACCOUNTS.NTURNOVER_N4 AS NACCUML_N4,
	dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3+dbo.NL_ACCOUNTS.NTURNOVER_N4+dbo.NL_ACCOUNTS.NTURNOVER_N5 AS NACCUML_N5,
	dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3+dbo.NL_ACCOUNTS.NTURNOVER_N4+dbo.NL_ACCOUNTS.NTURNOVER_N5+dbo.NL_ACCOUNTS.NTURNOVER_N6 AS NACCUML_N6, 
        dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3+dbo.NL_ACCOUNTS.NTURNOVER_N4+dbo.NL_ACCOUNTS.NTURNOVER_N5+dbo.NL_ACCOUNTS.NTURNOVER_N6+dbo.NL_ACCOUNTS.NTURNOVER_N7 AS NACCUML_N7,
	dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3+dbo.NL_ACCOUNTS.NTURNOVER_N4+dbo.NL_ACCOUNTS.NTURNOVER_N5+dbo.NL_ACCOUNTS.NTURNOVER_N6+dbo.NL_ACCOUNTS.NTURNOVER_N7+dbo.NL_ACCOUNTS.NTURNOVER_N8 AS NACCUML_N8,
	dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3+dbo.NL_ACCOUNTS.NTURNOVER_N4+dbo.NL_ACCOUNTS.NTURNOVER_N5+dbo.NL_ACCOUNTS.NTURNOVER_N6+dbo.NL_ACCOUNTS.NTURNOVER_N7+dbo.NL_ACCOUNTS.NTURNOVER_N8+dbo.NL_ACCOUNTS.NTURNOVER_N9 AS NACCUML_N9, 
        dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3+dbo.NL_ACCOUNTS.NTURNOVER_N4+dbo.NL_ACCOUNTS.NTURNOVER_N5+dbo.NL_ACCOUNTS.NTURNOVER_N6+dbo.NL_ACCOUNTS.NTURNOVER_N7+dbo.NL_ACCOUNTS.NTURNOVER_N8+dbo.NL_ACCOUNTS.NTURNOVER_N9+dbo.NL_ACCOUNTS.NTURNOVER_N10 AS NACCUML_N10,
	dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3+dbo.NL_ACCOUNTS.NTURNOVER_N4+dbo.NL_ACCOUNTS.NTURNOVER_N5+dbo.NL_ACCOUNTS.NTURNOVER_N6+dbo.NL_ACCOUNTS.NTURNOVER_N7+dbo.NL_ACCOUNTS.NTURNOVER_N8+dbo.NL_ACCOUNTS.NTURNOVER_N9+dbo.NL_ACCOUNTS.NTURNOVER_N10+dbo.NL_ACCOUNTS.NTURNOVER_N11 AS NACCUML_N11,
	dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3+dbo.NL_ACCOUNTS.NTURNOVER_N4+dbo.NL_ACCOUNTS.NTURNOVER_N5+dbo.NL_ACCOUNTS.NTURNOVER_N6+dbo.NL_ACCOUNTS.NTURNOVER_N7+dbo.NL_ACCOUNTS.NTURNOVER_N8+dbo.NL_ACCOUNTS.NTURNOVER_N9+dbo.NL_ACCOUNTS.NTURNOVER_N10+dbo.NL_ACCOUNTS.NTURNOVER_N11+dbo.NL_ACCOUNTS.NTURNOVER_N12 AS NACCUML_N12,
        dbo.NL_ACCOUNTS.NTURNOVER_N1+dbo.NL_ACCOUNTS.NTURNOVER_N2+Dbo.NL_ACCOUNTS.NTURNOVER_N3+dbo.NL_ACCOUNTS.NTURNOVER_N4+dbo.NL_ACCOUNTS.NTURNOVER_N5+dbo.NL_ACCOUNTS.NTURNOVER_N6+dbo.NL_ACCOUNTS.NTURNOVER_N7+dbo.NL_ACCOUNTS.NTURNOVER_N8+dbo.NL_ACCOUNTS.NTURNOVER_N9+dbo.NL_ACCOUNTS.NTURNOVER_N10+dbo.NL_ACCOUNTS.NTURNOVER_N11+dbo.NL_ACCOUNTS.NTURNOVER_N12+dbo.NL_ACCOUNTS.NTURNOVER_N13 AS NACCUML_N13,
        dbo.NL_ACCOUNTS.NBUDGET_C1 AS NBCCUML_C1, 
	dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2 AS NBCCUML_C2,
	dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3 AS NBCCUML_C3, 
        dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4 AS NBCCUML_C4,
	dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5 AS NBCCUML_C5,
	dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6 AS NBCCUML_C6, 
        dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7 AS NBCCUML_C7,
	dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8 AS NBCCUML_C8,
	dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8+dbo.NL_ACCOUNTS.NBUDGET_C9 AS NBCCUML_C9, 
        dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8+dbo.NL_ACCOUNTS.NBUDGET_C9+dbo.NL_ACCOUNTS.NBUDGET_C10 AS NBCCUML_C10,
	dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8+dbo.NL_ACCOUNTS.NBUDGET_C9+dbo.NL_ACCOUNTS.NBUDGET_C10+dbo.NL_ACCOUNTS.NBUDGET_C11 AS NBCCUML_C11,
	dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8+dbo.NL_ACCOUNTS.NBUDGET_C9+dbo.NL_ACCOUNTS.NBUDGET_C10+dbo.NL_ACCOUNTS.NBUDGET_C11+dbo.NL_ACCOUNTS.NBUDGET_C12 AS NBCCUML_C12,
        dbo.NL_ACCOUNTS.NBUDGET_C1+dbo.NL_ACCOUNTS.NBUDGET_C2+Dbo.NL_ACCOUNTS.NBUDGET_C3+dbo.NL_ACCOUNTS.NBUDGET_C4+dbo.NL_ACCOUNTS.NBUDGET_C5+dbo.NL_ACCOUNTS.NBUDGET_C6+dbo.NL_ACCOUNTS.NBUDGET_C7+dbo.NL_ACCOUNTS.NBUDGET_C8+dbo.NL_ACCOUNTS.NBUDGET_C9+dbo.NL_ACCOUNTS.NBUDGET_C10+dbo.NL_ACCOUNTS.NBUDGET_C11+dbo.NL_ACCOUNTS.NBUDGET_C12+dbo.NL_ACCOUNTS.NBUDGET_C13 AS NBCCUML_C13

FROM         dbo.AA_NET_NL_RECORD_VIEW INNER JOIN
                      dbo.NL_ACCOUNTS ON dbo.AA_NET_NL_RECORD_VIEW.N_PRIMARY = dbo.NL_ACCOUNTS.N_PRIMARY