CREATE VIEW AA_ED_SOP_DETAIL_ANALYSIS_VIEW
AS
SELECT 	CUSTOMER_CODE AS OD_ACCOUNT,
	CUNAME,
	CUSORT,
	CUUSER1,
	CUUSER2,
	CUUSER3,
	OH_CUSORT,
	OH_USER1,
	OH_USER2,
	OH_USER3,
	OH_WORK_STATUS,
	OH_BATCH_FLAG,
	OH_STATUS,
	OH_TYPE,
	OH_PRIORITY,
	OH_URGENT_FLAG,
	OH_DATE,
	OH_REQUIREDDATE,
	OD_STATUS,
	OD_ENTRY_TYPE,
	OD_REQDATE,
	OD_WORK_STATUS,
	OD_ANALYSIS,
	SANAME,
	CASE OH_TYPE
		WHEN 'O' THEN
			CASE OD_QTYORD
				WHEN 0 THEN 1
				ELSE OD_QTYORD END
		WHEN 'C' THEN
			CASE OD_QTYORD
				WHEN 0 THEN -1
				ELSE OD_QTYORD*-1 END
		END
AS QTYORDERED,
	CASE OH_TYPE
		WHEN 'O' THEN OD_QTYDELVD
		WHEN 'C' THEN OD_QTYDELVD*-1 END AS QTYDELIVERED,
	CASE OH_TYPE
		WHEN 'O' THEN OD_QTYINVD
		WHEN 'C' THEN OD_QTYINVD*-1 END AS QTYINVOICED,
	CASE OH_TYPE
		WHEN 'O' THEN OD_NETT
		WHEN 'C' THEN OD_NETT*-1 END AS SALESVALUE,
	CASE OH_TYPE
		WHEN 'O' THEN OD_VATAMNT
		WHEN 'C' THEN OD_VATAMNT*-1 END AS VATVALUE,
	CASE OH_TYPE
		WHEN 'O' THEN OD_GROSS
		WHEN 'C' THEN OD_GROSS*-1 END AS GROSSVALUE,
	CASE OH_TYPE
		WHEN 'O' THEN OD_COSTPRICE
		WHEN 'C' THEN OD_COSTPRICE*-1 END AS COSTPRICE,
	CASE OH_TYPE
		WHEN 'O' THEN OD_L_DISCVAL
		WHEN 'C' THEN OD_L_DISCVAL*-1 END AS LINEDISCOUNT,
	CASE OH_TYPE
		WHEN 'O' THEN OD_T_DISCVAL
		WHEN 'C' THEN OD_T_DISCVAL*-1 END AS TOTALDISCOUNT,
	CASE OD_ENTRY_TYPE
		WHEN 'S' THEN OD_STOCK_CODE
		WHEN 'P' THEN OD_PRICE_CODE
		WHEN 'T' THEN SUBSTRING(OD_DETAIL,1,25) END AS PRODUCT_CODE,
	CASE OD_ENTRY_TYPE
		WHEN 'S' THEN Stock.STKNAME
		WHEN 'P' THEN Price.PRNAME
		WHEN 'T' THEN OD_DETAIL END as PRODUCT_NAME,
	CASE OD_ENTRY_TYPE
		WHEN 'S' THEN Stock.STK_SORT_KEY
		WHEN 'P' THEN Price.PR_SORT_KEY
		WHEN 'T' THEN '' END as PRODUCT_SORT_KEY,
	CASE OD_ENTRY_TYPE
		WHEN 'S' THEN Stock.STK_SORT_KEY1
		WHEN 'P' THEN Price.PR_SORT_KEY1
		WHEN 'T' THEN '' END as PRODUCT_SORT_KEY1,
	CASE OD_ENTRY_TYPE
		WHEN 'S' THEN Stock.STK_SORT_KEY2
		WHEN 'P' THEN Price.PR_SORT_KEY2
		WHEN 'T' THEN '' END as PRODUCT_SORT_KEY2,
	CASE OD_ENTRY_TYPE
		WHEN 'S' THEN Stock.STK_SORT_KEY3
		WHEN 'P' THEN Price.PR_SORT_KEY3
		WHEN 'T' THEN '' END as PRODUCT_SORT_KEY3,
OD_COSTHEADER,CH_NAME,OD_PRIMARY,OH_PRIMARY,OD_LOCATN,OD_ORDER_NUMBER,OD_BATCH_FLAG
FROM ORD_DETAIL
RIGHT JOIN ORD_HEADER ON OD_ORDER_NUMBER=OH_ORDER_NUMBER
RIGHT JOIN AA_ED_CUSTOMER_PROSPECT_VIEW ON OH_ACCOUNT=CUSTOMER_CODE
RIGHT JOIN SL_ANALYSIS ON OD_ANALYSIS=SACODE
LEFT OUTER JOIN STK_STOCK Stock ON OD_STOCK_CODE=Stock.STKCODE
LEFT OUTER JOIN PRC_PRICE_RECS Price ON OD_PRICE_CODE=Price.PRCODE
LEFT OUTER JOIN CST_COSTHEADER ON OD_COSTHEADER=CH_CODE
WHERE OD_PRIMARY IS NOT NULL