CREATE VIEW AA_NET_WO_ORDERS_VIEW
AS
SELECT 
WO_ORDER_NUMBER,
WO_STOCK_LINK,
STKCODE AS STOCKCODE,
STKNAME AS STOCKDESCRIPTION,
WO_ROUTE_LINK,
WR_ROUTE AS ROUTECODE,
WR_DESCRIPTION AS ROUTEDESCRIPTION,
WO_QUANTITY,
WO_START_DATE, 
WO_END_DATE, 
WO_PRIORITY,
WO_NOTES,
WO_SORT_KEY
FROM WO_ORDERS INNER JOIN STK_STOCK ON (WO_STOCK_LINK=STK_PRIMARY)
			   INNER JOIN WO_ROUTES ON (WO_ROUTE_LINK=WR_PRIMARY)