CREATE VIEW AA_NET_SL_ANALYSIS_VIEW
/*
** Written:        09/12/02 ROBB
** Last Amended:   20/12/02 ROBB; 15/01/03 SRB; 16/01/03 SRB
*/
AS
select 
SACODE,
SANAME,
SASORT,
SAVATCODE,
dbo.AA_VALUE_DPS_F(VAT_RATE) AS VAT_RATE,
SACURRENCYSYMBL,
CURREC_DESCRIPTION,
SANOMINALDR,
NominalOne.NNAME
as
SANOMINALDRNAME,
SANOMINALCR,
NominalTwo.NNAME
as
SANOMINALCRNAME,
SANOMINALVAT,
NominalThree.NNAME
as
SANOMINALVATNAME,

SATYPE_S_B_D,
case
	when (SATYPE_S_B_D = 'B' AND SADEFAULT_BANK = 1) 
		then 1
	when (SATYPE_S_B_D = 'S' AND SADEFAULT_SALES = 1) 
		then 1
	else 0
end 
as
SADEFAULT,
SA_LEVEL,
SA_DATE_PUTIN,
SA_DATE_EDITED,
SA_FORCE_COSTING,
SA_ANALYSIS_MATRIX,
SANOTES,
SATURNOVERPTD,
SATURNOVERYTD,
SA_USRCHAR1,
SA_USRCHAR2,
SA_USRCHAR5,
SA_USRCHAR6,
SA_USRCHAR7,
SA_USRCHAR8,
SA_USRDATE1,
SA_USRDATE2,
SA_USRDATE3,
SA_USRFLAG1,
SA_USRFLAG2,
SA_USRFLAG3,
SA_USRNUM1,
SA_USRNUM2,
SA_USRNUM3,
SA_PRIMARY,
SAUSED,
SADEFAULT_ROUNDING

from SL_ANALYSIS
	left outer join SL_ANALYSIS2
	on SL_ANALYSIS.SACODE = SL_ANALYSIS2.SACODE2
	left outer join SYS_VATCONTROL
	on SL_ANALYSIS.SAVATCODE = SYS_VATCONTROL.VAT_CODE
	inner join SYS_CURRENCY_REC
	on SL_ANALYSIS.SACURRENCYSYMBL = SYS_CURRENCY_REC.CURREC_SYMBOL
	left outer join NL_ACCOUNTS NominalOne 
	on SL_ANALYSIS.SANOMINALDR = NominalOne.NCODE
	left outer join NL_ACCOUNTS NominalTwo 
	on SL_ANALYSIS.SANOMINALCR = NominalTwo.NCODE
	left outer join NL_ACCOUNTS NominalThree 
	on SL_ANALYSIS.SANOMINALVAT = NominalThree.NCODE


