CREATE VIEW AA_NET_SL_ADDRESSES_LIST_VIEW
/*
** Returns a table to be used specifically with AA_NET_SL_ADDRESSES_LIST_VIEW
** Written:      29/04/03 SRB
** Last Amended: 
**
*/
AS

SELECT 
TYPE = 'CUSTOMER'
,ALLOCATEDUSER.USER_NAME AS ALLOCATEDUSERNAME
,ENTEREDBYUSER.USER_NAME AS ENTEREDBYUSERNAME
,AD_CON_CODE
,AD_CON_CODE as [PRIMARY]
,AD_LEVEL as PROFILELEVEL
,AD_ACC_CODE as PARENT
,AD_CODE as CHILD
,COALESCE(AD_ACC_CODE,'') AS AD_ACC_CODE
,CUNAME AS PARENTNAME
,AD_DATE_PUTIN
,AD_DATE_EDITED
,AD_USER_ALOC
,AD_USER_PUTIN
,AD_USER_EDITED
,AD_CON_TITLE AS TITLE
,AD_CON_INITIALS AS INITIALS
,COALESCE(AD_CON_SURNAME,'') AS SURNAME
,COALESCE(AD_ADDRESS,'') AS ADDRESS
,COALESCE(AD_ADDRESS_USER1,'') AS TOWN
,COALESCE(AD_POSTCODE,'') AS POSTCODE
,AD_COUNTRY AS COUNTRY
,AD_DEALERCODE
--Distinguish if a Defualt Invoice Address
,CASE WHEN (AD_CODE=CU_INV_ADD_CDE) THEN 
	1 
 ELSE 
	0 
 END

 AS INVOICEADDRESS 

--Distinguish if a Defualt Delivery Address
,CASE WHEN (AD_CODE=CU_DEL_ADD_CDE) THEN 
	1 
 ELSE 
	0 
 END 

 AS DEFAULTDELIVERYADDRESS 

--Distinguish if a Delivery Address
,CASE WHEN (AD_DEL_ADDRESS_2=1) THEN 
	1 
 ELSE 
	0 
 END 

 AS DELIVERYADDRESS
,AD_STAT_ADDRESS AS STATEMENTADDRESS
,AD_DEL_ADDRESS As DEFAULTADDRESS

,AD_PHONE as PHONE
,AD_USERTEXT1
,AD_USERTEXT2
,AD_USERTEXT3
,AD_USERTEXT4
,AD_USERTEXT5
,AD_USERTEXT6
,AD_USERTEXT7
,AD_USERTEXT8
,AD_USERTEXT9
,AD_USERTEXT10
,AD_USERNUM1
,AD_USERNUM2
,AD_USERNUM3
,AD_USERDATE1
,AD_USERDATE2
,AD_USERDATE3
,COALESCE(AD_DO_NOT_USE,0) as DO_NOT_USE

FROM 
SL_ADDRESSES 

INNER JOIN SL_ACCOUNTS ON 
CUCODE = AD_ACC_CODE

LEFT JOIN SL_ADDRESSES2 ON 
SL_AD_PRIMARY = AD_PRIMARY_2

LEFT JOIN SYS_USER ALLOCATEDUSER ON
AD_USER_ALOC = ALLOCATEDUSER.USER_ID

LEFT JOIN SYS_USER ENTEREDBYUSER ON
AD_USER_ALOC = ENTEREDBYUSER.USER_ID

WHERE (CUCODE IS NOT NULL OR CUCODE != '') 


