CREATE VIEW AA_NET_PL_DETAIL_TRAN_VIEW
/*
** Written:     
** Last Amended: 06/05/2003 ROBB; 28/05/2003 ROBB  
** Comments: Returns detail line info for purchase ledger transactions
*/
AS

SELECT     
DET_ANALYSIS,
DET_VATCODE,
dbo.AA_PRICE_DPS_F(DET_NETT) AS DET_NETT,

(case when DET_VATCODE in ('A','R')
then
	dbo.AA_PRICE_DPS_F(DET_PL_ACQ_TAX)
else
	dbo.AA_PRICE_DPS_F(DET_VAT)
end) AS DET_VAT,

(CASE -- Only return the Gross value for Home currency transactions
	WHEN PT_CURR_TYPE = 'H' THEN
		dbo.AA_PRICE_DPS_F(DET_GROSS) 
	ELSE
		dbo.AA_PRICE_DPS_F(DET_CURR_GROSS)
END) AS CURRENCY_GROSS,
dbo.AA_PRICE_DPS_F(DET_CURR_TAX) AS DET_CURR_TAX,
DET_COSTHEADER,
DET_COSTCENTRE,
DET_DESCRIPTION,
DET_DIMENSION1,
DET_DIMENSION2,
DET_DIMENSION3,
DET_PRIMARY,
dbo.AA_TWO_DPS_F(SYS_VATCONTROL.VAT_RATE) AS VAT_RATE,
PANAME,
PA_FORCE_COSTING,
DET_HEADER_KEY,
CC_NAME,
CH_NAME,
DET_USRCHAR1,
DET_USRCHAR2,
DET_USRCHAR3,
DET_USRCHAR4,
DET_USRFLAG1,
DET_USRFLAG2,
DET_USRDATE1,
DET_USRDATE2,
DET_USRNUM1,
DET_USRNUM2

FROM         
SL_PL_NL_DETAIL
INNER JOIN AA_NET_PL_ANALYSIS_VIEW ON SL_PL_NL_DETAIL.DET_ANALYSIS = AA_NET_PL_ANALYSIS_VIEW.PACODE 
LEFT OUTER JOIN PL_TRANSACTIONS ON SL_PL_NL_DETAIL.DET_HEADER_KEY = PL_TRANSACTIONS.PT_HEADER_KEY  
LEFT OUTER JOIN SYS_VATCONTROL ON SL_PL_NL_DETAIL.DET_VATCODE = SYS_VATCONTROL.VAT_CODE
LEFT OUTER JOIN SL_PL_NL_DETAIL2 ON SL_PL_NL_DETAIL.DET_PRIMARY = SL_PL_NL_DETAIL2.DET_PRIMARY_2
LEFT OUTER JOIN CST_COSTCENTRE ON COALESCE (CONVERT(char(10), SL_PL_NL_DETAIL.DET_COSTHEADER) + CONVERT(varchar,SL_PL_NL_DETAIL.DET_COSTCENTRE),'') = CST_COSTCENTRE.CC_CONCAT_CODES 
LEFT OUTER JOIN CST_COSTHEADER ON COALESCE (SL_PL_NL_DETAIL.DET_COSTHEADER,'') = CST_COSTHEADER.CH_CODE