CREATE VIEW AA_NET_CST_COSTCENTRE_LIST_VIEW
/*
** Returns a table to be used specifically with AA_NET_CST_COSTCENTRE_LIST_S
** Written:      21/02/03 SRB
** Last Amended: 
**
*/
AS
SELECT 

CC_CONCAT_CODES AS [PRIMARY]
,CC_CONCAT_CODES
,CC_CODE
,CH_LEVEL AS PROFILELEVEL
,COALESCE(CC_ANALYSIS ,'') as CC_ANALYSIS
,CC_CHRG_VALUE
,CC_CHRG_LINE
,CC_COPYHEADER
,CC_DATE_EDITED
,CC_DATE_PUTIN
,CC_DATE_REQ
,COALESCE(CC_DATE_REQ,'') AS REQUIREDDATESORT
,CC_LEVEL
,CH_ACCOUNT
,COALESCE(CC_NAME ,'') as CC_NAME
,CC_STATUS
,CC_USER_SUBTOT
,CH_CODE as PARENT
,CC_CODE as CHILD
,CH_NAME

FROM CST_COSTCENTRE inner join dbo.CST_COSTHEADER
on CC_COPYHEADER = CH_CODE



