CREATE VIEW AA_NL_TRIAL_BALANCE_CAT_VIEW
AS
/*
**
** Intended to be called by AA_NL_TRIAL_BALANCE_CAT_S which will perform aggregate calculations and grouping on the data.
** The following fields are intended to be displayed:
**          Category             - DESCRIPTION
**          Category Name        - NCATNAME
**          Category Code        - NCATCODE
**          Debit (home)         - DEBIT
**          Credit (home)        - CREDIT
**          Debit (Currency)     - DEBIT_CURR
**          Credit (Currency)    - CREDIT_CURR
**
** The following fields are required for searching:
**          Nominal Account Code - NCODE
**          Nominal Account Name - NNAME
**          Currency Code        - NCURRCODE
**          Category Codes       - NCATCODE1-NCATCODE8
**          Major Heading Code   - NMAJORCODE
**          Major Heading Name   - NMAJORNAME
**          Category To View     - CATEGORY
**          Year (L,C,N)         - YEAR
**          Period (1-13)        - PERIOD
**
**          [PRIMARY] identifies a row in the result set
**          LINK_PRIMARY relates to a [PRIMARY] in the corresponding Header view
**
** The list will be sorted by PRIMARY with any other supplied order by field
**
** Written:      20/09/2005 SB
** Last Amended: 06/10/2005 SB, 20/10/2005 SB, 10/11/2005 SB, 19/01/06 SB, 21/03/05 MC, 03/11/2006 SB
*/
select
   cast( cast(MH.NM_PRIMARY + 10 as nvarchar) + '0' +
   case
      when CATEGORY = 1 then case when isnull(C1.NC_PRIMARY,0) > 9 then cast(isnull(C1.NC_PRIMARY,0) as nvarchar) else '0' + cast(isnull(C1.NC_PRIMARY,0) as nvarchar) end
      when CATEGORY = 2 then case when isnull(C2.NC_PRIMARY,0) > 9 then cast(isnull(C2.NC_PRIMARY,0) as nvarchar) else '0' + cast(isnull(C2.NC_PRIMARY,0) as nvarchar) end
      when CATEGORY = 3 then case when isnull(C3.NC_PRIMARY,0) > 9 then cast(isnull(C3.NC_PRIMARY,0) as nvarchar) else '0' + cast(isnull(C3.NC_PRIMARY,0) as nvarchar) end
      when CATEGORY = 4 then case when isnull(C4.NC_PRIMARY,0) > 9 then cast(isnull(C4.NC_PRIMARY,0) as nvarchar) else '0' + cast(isnull(C4.NC_PRIMARY,0) as nvarchar) end
      when CATEGORY = 5 then case when isnull(C5.NC_PRIMARY,0) > 9 then cast(isnull(C5.NC_PRIMARY,0) as nvarchar) else '0' + cast(isnull(C5.NC_PRIMARY,0) as nvarchar) end
      when CATEGORY = 6 then case when isnull(C6.NC_PRIMARY,0) > 9 then cast(isnull(C6.NC_PRIMARY,0) as nvarchar) else '0' + cast(isnull(C6.NC_PRIMARY,0) as nvarchar) end
      when CATEGORY = 7 then case when isnull(C7.NC_PRIMARY,0) > 9 then cast(isnull(C7.NC_PRIMARY,0) as nvarchar) else '0' + cast(isnull(C7.NC_PRIMARY,0) as nvarchar) end
      when CATEGORY = 8 then case when isnull(C8.NC_PRIMARY,0) > 9 then cast(isnull(C8.NC_PRIMARY,0) as nvarchar) else '0' + cast(isnull(C8.NC_PRIMARY,0) as nvarchar) end
      end  as float) [PRIMARY]
   ,cast(V.NMAJORHEADCODE as float) LINK_PRIMARY
   ,V.NCODE
   ,V.NNAME
   ,V.NCURRENCYCODE NCURRCODE
   ,case
      when CATEGORY = 1 then isnull(C1.NL_CATEGORYNAME,'')
      when CATEGORY = 2 then isnull(C2.NL_CATEGORYNAME,'')
      when CATEGORY = 3 then isnull(C3.NL_CATEGORYNAME,'')
      when CATEGORY = 4 then isnull(C4.NL_CATEGORYNAME,'')
      when CATEGORY = 5 then isnull(C5.NL_CATEGORYNAME,'')
      when CATEGORY = 6 then isnull(C6.NL_CATEGORYNAME,'')
      when CATEGORY = 7 then isnull(C7.NL_CATEGORYNAME,'')
      when CATEGORY = 8 then isnull(C8.NL_CATEGORYNAME,'') end NCATNAME
   ,case
      when CATEGORY = 1 then isnull(V.NCATEGORYCODE1,'')
      when CATEGORY = 2 then isnull(V.NCATEGORYCODE2,'')
      when CATEGORY = 3 then isnull(V.NCATEGORYCODE3,'')
      when CATEGORY = 4 then isnull(V.NCATEGORYCODE4,'')
      when CATEGORY = 5 then isnull(V.NCATEGORYCODE5,'')
      when CATEGORY = 6 then isnull(V.NCATEGORYCODE6,'')
      when CATEGORY = 7 then isnull(V.NCATEGORYCODE7,'')
      when CATEGORY = 8 then isnull(V.NCATEGORYCODE8,'') end NCATCODE
   ,case
      when CATEGORY = 1 and isnull(V.NCATEGORYCODE1, '') <> '' and isnull(C1.NL_CATEGORYNAME, '') <> ''
      then isnull(V.NCATEGORYCODE1, '') + '/' + isnull(C1.NL_CATEGORYNAME, '')
      when CATEGORY = 2 and isnull(V.NCATEGORYCODE2, '') <> '' and isnull(C2.NL_CATEGORYNAME, '') <> ''
      then isnull(V.NCATEGORYCODE2, '') + '/' + isnull(C2.NL_CATEGORYNAME, '')
      when CATEGORY = 3 and isnull(V.NCATEGORYCODE3, '') <> '' and isnull(C3.NL_CATEGORYNAME, '') <> ''
      then isnull(V.NCATEGORYCODE3, '') + '/' + isnull(C3.NL_CATEGORYNAME, '')
      when CATEGORY = 4 and isnull(V.NCATEGORYCODE4, '') <> '' and isnull(C4.NL_CATEGORYNAME, '') <> ''
      then isnull(V.NCATEGORYCODE4, '') + '/' + isnull(C4.NL_CATEGORYNAME, '')
      when CATEGORY = 5 and isnull(V.NCATEGORYCODE5, '') <> '' and isnull(C5.NL_CATEGORYNAME, '') <> ''
      then isnull(V.NCATEGORYCODE5, '') + '/' + isnull(C5.NL_CATEGORYNAME, '')
      when CATEGORY = 6 and isnull(V.NCATEGORYCODE6, '') <> '' and isnull(C6.NL_CATEGORYNAME, '') <> ''
      then isnull(V.NCATEGORYCODE6, '') + '/' + isnull(C6.NL_CATEGORYNAME, '')
      when CATEGORY = 7 and isnull(V.NCATEGORYCODE7, '') <> '' and isnull(C7.NL_CATEGORYNAME, '') <> ''
      then isnull(V.NCATEGORYCODE7, '') + '/' + isnull(C7.NL_CATEGORYNAME, '')
      when CATEGORY = 8 and isnull(V.NCATEGORYCODE8, '') <> '' and isnull(C8.NL_CATEGORYNAME, '') <> ''
      then isnull(V.NCATEGORYCODE8, '') + '/' + isnull(C8.NL_CATEGORYNAME, '')
      else ''
      end DESCRIPTION
   ,V.NCATEGORYCODE1 NCATCODE1
   ,V.NCATEGORYCODE2 NCATCODE2
   ,V.NCATEGORYCODE3 NCATCODE3
   ,V.NCATEGORYCODE4 NCATCODE4
   ,V.NCATEGORYCODE5 NCATCODE5
   ,V.NCATEGORYCODE6 NCATCODE6
   ,V.NCATEGORYCODE7 NCATCODE7
   ,V.NCATEGORYCODE8 NCATCODE8
   ,V.NMAJORHEADCODE NMAJORCODE
   ,MH.NL_MAJORNAME NMAJORNAME
   ,V.PERIOD PERIOD
   ,V.YEAR YEAR
   ,V.CATEGORY CATEGORY
   ,dbo.AA_VALUE_DPS_F(case when sign(VALUE) = 1 then VALUE else 0 end) DEBIT
   ,dbo.AA_VALUE_DPS_F(case when sign(VALUE) = -1 then VALUE*-1 else 0 end) CREDIT
   ,dbo.AA_VALUE_DPS_F(case when sign(CURRENCY_VALUE) = 1 then CURRENCY_VALUE else 0 end) CURR_DEBIT
   ,dbo.AA_VALUE_DPS_F(case when sign(CURRENCY_VALUE) = -1 then CURRENCY_VALUE*-1 else 0 end) CURR_CREDIT
from dbo.NL_MAJORHEADING MH inner join
(select
   isnull(NCATEGORYCODE1,'') NCATEGORYCODE1
   ,isnull(NCATEGORYCODE2,'') NCATEGORYCODE2
   ,isnull(NCATEGORYCODE3,'') NCATEGORYCODE3
   ,isnull(NCATEGORYCODE4,'') NCATEGORYCODE4
   ,isnull(NCATEGORYCODE5,'') NCATEGORYCODE5
   ,isnull(NCATEGORYCODE6,'') NCATEGORYCODE6
   ,isnull(NCATEGORYCODE7,'') NCATEGORYCODE7
   ,isnull(NCATEGORYCODE8,'') NCATEGORYCODE8
   ,isnull(NCODE,'') NCODE
   ,isnull(NNAME,'') NNAME
   ,NMAJORHEADCODE
   ,isnull(NCURRENCYCODE,'') NCURRENCYCODE
   ,case
      when PERIOD = 1 and YEAR ='C'
      then NOPENBALYEAR + NTURNOVER_C1
      when PERIOD = 2 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2
      when PERIOD = 3 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3
      when PERIOD = 4 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4
      when PERIOD = 5 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5
      when PERIOD = 6 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6
      when PERIOD = 7 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7
      when PERIOD = 8 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8
      when PERIOD = 9 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9
      when PERIOD = 10 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10
      when PERIOD = 11 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11
      when PERIOD = 12 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12
      when PERIOD = 13 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 1 and [YEAR] ='L'
      then NOPENBALANCELY + NTURNOVER_L1
      when PERIOD = 2 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2
      when PERIOD = 3 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3
      when PERIOD = 4 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4
      when PERIOD = 5 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5
      when PERIOD = 6 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6
      when PERIOD = 7 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7
      when PERIOD = 8 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8
      when PERIOD = 9 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9
      when PERIOD = 10 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10
      when PERIOD = 11 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10 + NTURNOVER_L11
      when PERIOD = 12 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10 + NTURNOVER_L11 + NTURNOVER_L12
      when PERIOD = 13 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10 + NTURNOVER_L11 + NTURNOVER_L12 + NTURNOVER_L13
      when PERIOD = 1 and [YEAR] ='N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 2 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 3 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 4 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 5 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 6 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 7 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 8 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 9 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 10 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 11 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_N11 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 12 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_N11 + NTURNOVER_N12 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 13 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_N11 + NTURNOVER_N12 + NTURNOVER_N13 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      else 0
   end VALUE
   ,case
      when PERIOD = 1 and YEAR ='C'
      then NOPENBALYR_C + NTURNOVER_C1_C
      when PERIOD = 2 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C
      when PERIOD = 3 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C
      when PERIOD = 4 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C
      when PERIOD = 5 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C
      when PERIOD = 6 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C
      when PERIOD = 7 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C
      when PERIOD = 8 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C
      when PERIOD = 9 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C
      when PERIOD = 10 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C
      when PERIOD = 11 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C
      when PERIOD = 12 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C
      when PERIOD = 13 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 1 and [YEAR] ='L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C
      when PERIOD = 2 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C
      when PERIOD = 3 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C
      when PERIOD = 4 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C
      when PERIOD = 5 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C
      when PERIOD = 6 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C
      when PERIOD = 7 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C
      when PERIOD = 8 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C
      when PERIOD = 9 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C + NTURNOVER_L9_C
      when PERIOD = 10 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C + NTURNOVER_L9_C + NTURNOVER_L10_C
      when PERIOD = 11 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C + NTURNOVER_L9_C + NTURNOVER_L10_C + NTURNOVER_L11_C
      when PERIOD = 12 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C + NTURNOVER_L9_C + NTURNOVER_L10_C + NTURNOVER_L11_C + NTURNOVER_L12_C
      when PERIOD = 13 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C + NTURNOVER_L9_C + NTURNOVER_L10_C + NTURNOVER_L11_C + NTURNOVER_L12_C + NTURNOVER_L13_C
      when PERIOD = 1 and [YEAR] ='N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 2 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 3 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 4 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 5 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 6 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 7 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 8 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 9 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_N9_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 10 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_N9_C + NTURNOVER_N10_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 11 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_N9_C + NTURNOVER_N10_C + NTURNOVER_N11_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 12 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_N9_C + NTURNOVER_N10_C + NTURNOVER_N11_C + NTURNOVER_N12_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 13 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_N9_C + NTURNOVER_N10_C + NTURNOVER_N11_C + NTURNOVER_N12_C + NTURNOVER_N13_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      else 0
   end CURRENCY_VALUE
      --,isnull(MH.NL_MAJORNAME,'') NL_MAJORNAME
      ,PERIOD
      ,YEAR
      ,CATEGORY
   from  NL_ACCOUNTS N1
   ,(select 1 as PERIOD union select 2 as PERIOD union select 3 as PERIOD
         union select 4 as PERIOD union select 5 as PERIOD
         union select 6 as PERIOD union select 7 as PERIOD union select 8 as PERIOD
         union select 9 as PERIOD union select 10 as PERIOD
         union select 11 as PERIOD union select 12 as PERIOD union select 13 as PERIOD
       ) PERIODS
   ,(select 'L' as Year union select 'C' as Year union select 'N' as Year) YEARS
   ,(select 1 as CATEGORY union select 2 as CATEGORY union select 3 as CATEGORY
         union select 4 as CATEGORY union select 5 as CATEGORY
         union select 6 as CATEGORY union select 7 as CATEGORY union select 8 as CATEGORY
       ) CATEGORIES   ) V  on V.NMAJORHEADCODE = MH.NL_MAJORCODE
   left outer join NL_CATEGORY C1 on C1.NL_CAT_SORTCODE = '1' + V.NCATEGORYCODE1
   left outer join NL_CATEGORY C2 on C2.NL_CAT_SORTCODE = '2' + V.NCATEGORYCODE2
   left outer join NL_CATEGORY C3 on C3.NL_CAT_SORTCODE = '3' + V.NCATEGORYCODE3
   left outer join NL_CATEGORY C4 on C4.NL_CAT_SORTCODE = '4' + V.NCATEGORYCODE4
   left outer join NL_CATEGORY C5 on C5.NL_CAT_SORTCODE = '5' + V.NCATEGORYCODE5
   left outer join NL_CATEGORY C6 on C6.NL_CAT_SORTCODE = '6' + V.NCATEGORYCODE6
   left outer join NL_CATEGORY C7 on C7.NL_CAT_SORTCODE = '7' + V.NCATEGORYCODE7
   left outer join NL_CATEGORY C8 on C8.NL_CAT_SORTCODE = '8' + V.NCATEGORYCODE8
