create VIEW AA_NET_NL_HEADER_TRAN_VIEW
AS
SELECT DISTINCT 
      NL_GROSS_CONTRA.NNAME AS CONTRANAME, NL_VAT_CONTRA.NNAME AS VATCONTRANAME, dbo.NL_TRANSACTIONS.NT_TRANTYPE, 
      dbo.NL_TRANSACTIONS.NT_IMPEXP_CODE, dbo.NL_TRANSACTIONS.NT_SUB_LEDGER, dbo.NL_TRANSACTIONS.NT_GROSS_CONTRA, 
      dbo.NL_TRANSACTIONS.NT_VAT_CONTRA, dbo.NL_TRANSACTIONS.NT_HEADER_REF, dbo.NL_TRANSACTIONS.NT_EC_DEL_TERM, 
      dbo.NL_TRANSACTIONS.NT_EC_T_NATURE, dbo.NL_TRANSACTIONS.NT_EC_T_MODE, dbo.NL_TRANSACTIONS.NT_CURRENCYSYMB, 
      dbo.NL_TRANSACTIONS.NT_CURRENCYCODE, dbo.NL_TRANSACTIONS.NT_CURR_TYPE, 
      (CASE WHEN NT_CURR_TYPE = 'E' THEN NT_TRI_RATE1 ELSE NT_CURRENCYRATE END) AS NT_CURRENCYRATE, 
      dbo.NL_TRANSACTIONS.NT_TRI_RATE2, dbo.NL_TRANSACTIONS.NT_DATE, dbo.NL_TRANSACTIONS.NT_BATCH_REF, 
      dbo.NL_TRANSACTIONS.NT_FIRST_DATE, dbo.NL_TRANSACTIONS.NT_MAX_POSTINGS, dbo.NL_TRANSACTIONS.NT_YEAR, 
      dbo.NL_TRANSACTIONS.NT_PERIODNUMBER, dbo.NL_TRANSACTIONS.NT_POSTINGS_PER, dbo.NL_TRANSACTIONS.NT_POSTINGS_FRQ, 
      dbo.NL_TRANSACTIONS.NT_REVERSE_FLAG, dbo.NL_TRANSACTIONS.NT_DESCRIPTION, dbo.NL_TRANSACTIONS.NT_CONTRA_FLAG, 
      dbo.NL_TRANSACTIONS.NT_MULTI_CONTRA, dbo.NL_TRANSACTIONS.NT_ARCHIVE_FLAG, dbo.NL_TRANSACTIONS.NT_BATCH_FLAG, 
      dbo.NL_TRANSACTIONS.NT_RECUR_FLAG, dbo.NL_TRANSACTIONS.NT_HEADER_KEY, dbo.NL_TRANSACTIONS.NT_PRIMARY, 
      dbo.NL_TRANSACTIONS.NT_TRAN_OPTIONS, dbo.NL_TRANSACTIONS.NT_SOURCE, dbo.NL_TRANSACTIONS.NT_MU_STATUS, 
      dbo.NL_TRANSACTIONS2.NT_USRCHAR1, dbo.NL_TRANSACTIONS2.NT_USRCHAR2, dbo.NL_TRANSACTIONS2.NT_USRCHAR3, 
      dbo.NL_TRANSACTIONS2.NT_USRCHAR4, dbo.NL_TRANSACTIONS2.NT_USRFLAG1, dbo.NL_TRANSACTIONS2.NT_USRFLAG2, 
      dbo.NL_TRANSACTIONS2.NT_USRDATE1, dbo.NL_TRANSACTIONS2.NT_USRDATE2, dbo.NL_TRANSACTIONS2.NT_USRNUM1, 
      dbo.NL_TRANSACTIONS2.NT_USRNUM2, (CASE WHEN substring(NT_TRAN_OPTIONS, 3, 1) IS NULL THEN 0 ELSE substring(NT_TRAN_OPTIONS, 3, 1) 
      END) AS GROSSENTRY, (CASE WHEN substring(NT_TRAN_OPTIONS, 3, 1) IS NULL THEN 0 ELSE substring(NT_TRAN_OPTIONS, 3, 1) END) 
      AS CURRENCYENTRY, dbo.SL_PL_NL_DETAIL.DET_LEDGER AS DET_ORIGIN
FROM  dbo.NL_TRANSACTIONS LEFT OUTER JOIN
      dbo.NL_TRANSACTIONS2 ON dbo.NL_TRANSACTIONS.NT_PRIMARY = dbo.NL_TRANSACTIONS2.NT_PRIMARY_2 INNER JOIN
      dbo.SL_PL_NL_DETAIL ON dbo.NL_TRANSACTIONS.NT_HEADER_KEY = dbo.SL_PL_NL_DETAIL.DET_HEADER_KEY LEFT OUTER JOIN
      dbo.NL_ACCOUNTS AS NL_GROSS_CONTRA ON dbo.NL_TRANSACTIONS.NT_GROSS_CONTRA = NL_GROSS_CONTRA.NCODE LEFT OUTER JOIN
      dbo.NL_ACCOUNTS AS NL_VAT_CONTRA ON dbo.NL_TRANSACTIONS.NT_VAT_CONTRA = NL_VAT_CONTRA.NCODE

