CREATE VIEW AA_NET_PL_HEADER_TRAN_VIEW
/*
** Written:        
** Last Amended: 20/03/03 ROBB; 06/05/03 ROBB
*/
AS

SELECT     
SUNAME,
SU_ON_STOP,
SU_MULTI_CURR,
dbo.AA_PRICE_DPS_F(SU_CREDIT_LIMIT) AS SU_CREDIT_LIMIT, 
dbo.AA_PRICE_DPS_F(SUBALANCE) AS SUBALANCE,
dbo.AA_PRICE_DPS_F(SUTURNOVERYTD) AS SUTURNOVERYTD,
SU_A_P_DAYS,
SU_VAT_REG_NO,
SU_TERMS,
SU_DUE_DAYS,
SU_DUEDATE_TYPE,
SU_NOTES,
PL_AD_ADDRESS,
PL_AD_ADDRESS_USER1,
PL_AD_ADDRESS_USER2,
PL_AD_POSTCODE,
PL_AD_COUNTRY,
PL_AD_EMAIL,
PL_AD_PHONE,
PL_AD_FAX,
PL_AD_CONTACT, 
PT_TRANTYPE,
PT_COPYSUPP,
PT_CURRENCYCODE,
(case when PT_CURR_TYPE ='E'
	then
		PT_TRI_RATE1
	else
		PT_CURRENCYRATE
	end) 
as PT_CURRENCYRATE,
PT_CURR_TYPE, 
PT_TRI_RATE2,
PT_IMPORT_CODE,
PT_EC_DEL_TERMS,
PT_EC_T_NATURE, 
PT_EC_T_MODE,
PT_SETT_DISC1,
PT_SETT_DAYS1, 
PT_SETT_DISC2,
PT_SETT_DAYS2,
PT_HEADER_REF,
PT_BATCH_REF, 
PT_DATE,
PT_YEAR,
PT_PERIODNUMBER, 
PT_DUEDATE,
PT_ANTICPAYDATE,
PT_DESCRIPTION, 
PT_QUERY_FLAG,
PT_ARCHIVE_FLAG,
PT_HEADER_KEY,
PT_BATCH_FLAG,
PT_MU_STATUS,
PT_SUB_LEDGER,
PT_INTERNAL_REF,
PT_PRIMARY,
PT_TRAN_OPTIONS,
PT_USRCHAR1,
PT_USRCHAR2,
PT_USRCHAR3,
PT_USRCHAR4,
PT_USRFLAG1,
PT_USRFLAG2,
PT_USRDATE1,
PT_USRDATE2,
PT_USRNUM1,
PT_USRNUM2,
(case when substring(PT_TRAN_OPTIONS,3,1) is null then 0 else substring(PT_TRAN_OPTIONS,3,1) end) as GROSSENTRY,
(case when substring(PT_TRAN_OPTIONS,3,1) is null then 0 else substring(PT_TRAN_OPTIONS,3,1) end) as CURRENCYENTRY,
(case when substring(PT_TRAN_OPTIONS,6,1) is null then 0 else substring(PT_TRAN_OPTIONS,6,1) end) as DUERECEIPTDATEENTRY

FROM         
PL_TRANSACTIONS
LEFT OUTER JOIN PL_TRANSACTIONS2 ON PL_TRANSACTIONS.PT_PRIMARY = PL_TRANSACTIONS2.PT_PRIMARY_2
LEFT OUTER JOIN PL_ACCOUNTS ON PL_TRANSACTIONS.PT_COPYSUPP = PL_ACCOUNTS.SUCODE
LEFT OUTER JOIN PL_ADDRESSES ON CONVERT(char(10),PL_ACCOUNTS.SUCODE) + '1' = PL_ADDRESSES.PL_AD_CON_CODE 


