CREATE VIEW AA_NET_NL_DETAIL_TRAN_VIEW
/*
** Written:        
** Last Amended: 07/05/03 ROBB
*/
AS


SELECT
DET_TYPE,
(case when DET_NOMINALDR IS NULL OR DET_NOMINALDR=''
		then
			'CR'
		else
			'DR'
		end)
as DETAILTYPE,
(case when DET_NOMINALDR IS NULL OR DET_NOMINALDR=''
		then
			DET_NOMINALCR
		else
			DET_NOMINALDR
		end) 
as NOMINALACCOUNTCODE,
(case when DET_NOMINALDR IS NULL OR DET_NOMINALDR=''
		then
			NL_ACCOUNTS_CREDIT.NNAME
		else
			NL_ACCOUNTS_DEBIT.NNAME
		end) 
as NOMINALACCOUNTNAME,
(case when DET_NOMINALDR IS NULL OR DET_NOMINALDR=''
		then
			NL_ACCOUNTS_DEBIT.N_FORCE_COSTING
		else
			NL_ACCOUNTS_CREDIT.N_FORCE_COSTING
		end) 
as FORCECOSTING,
DET_NOMINALVAT,
DET_DATE,    
DET_ANALYSIS,
DET_VATCODE,
dbo.AA_PRICE_DPS_F(DET_NETT) AS DET_NETT,
(CASE -- Only return the Gross value for Home currency transactions
	WHEN NT_CURR_TYPE = 'H' THEN
		dbo.AA_PRICE_DPS_F(DET_GROSS) 
	ELSE
		dbo.AA_PRICE_DPS_F(DET_CURR_GROSS)
END) AS CURRENCY_GROSS,
--DET_GROSS,
dbo.AA_PRICE_DPS_F(DET_VAT) AS DET_VAT,
--DET_CURR_GROSS,
dbo.AA_PRICE_DPS_F(DET_CURR_TAX) AS DET_CURR_TAX,
DET_COSTHEADER,
DET_COSTCENTRE,
DET_DESCRIPTION,
DET_DIMENSION1,
DET_DIMENSION2,
DET_DIMENSION3,
DET_PRIMARY,
dbo.AA_TWO_DPS_F(SYS_VATCONTROL.VAT_RATE) AS VAT_RATE,
DET_JNL_LINEREF,
DET_HEADER_KEY,
CC_NAME,
CH_NAME,
DET_USRCHAR1,
DET_USRCHAR2,
DET_USRCHAR3,
DET_USRCHAR4,
DET_USRFLAG1,
DET_USRFLAG2,
DET_USRDATE1,
DET_USRDATE2,
DET_USRNUM1,
DET_USRNUM2

FROM         
SL_PL_NL_DETAIL
LEFT OUTER JOIN NL_TRANSACTIONS ON SL_PL_NL_DETAIL.DET_HEADER_KEY = NL_TRANSACTIONS.NT_HEADER_REF  
LEFT OUTER JOIN SYS_VATCONTROL ON SL_PL_NL_DETAIL.DET_VATCODE = SYS_VATCONTROL.VAT_CODE
LEFT OUTER JOIN NL_ACCOUNTS As NL_ACCOUNTS_DEBIT ON SL_PL_NL_DETAIL.DET_NOMINALDR = NL_ACCOUNTS_DEBIT.NCODE
LEFT OUTER JOIN NL_ACCOUNTS As NL_ACCOUNTS_CREDIT ON SL_PL_NL_DETAIL.DET_NOMINALCR = NL_ACCOUNTS_CREDIT.NCODE
LEFT OUTER JOIN SL_PL_NL_DETAIL2 ON SL_PL_NL_DETAIL.DET_PRIMARY = SL_PL_NL_DETAIL2.DET_PRIMARY_2
LEFT OUTER JOIN CST_COSTCENTRE ON COALESCE (CONVERT(char(10), SL_PL_NL_DETAIL.DET_COSTHEADER) + CONVERT(varchar,SL_PL_NL_DETAIL.DET_COSTCENTRE),'') = CST_COSTCENTRE.CC_CONCAT_CODES 
LEFT OUTER JOIN CST_COSTHEADER ON COALESCE (SL_PL_NL_DETAIL.DET_COSTHEADER,'') = CST_COSTHEADER.CH_CODE
WHERE SL_PL_NL_DETAIL.DET_BATCH_FLAG=1