CREATE VIEW AA_NL_TRIAL_BALANCE_HEADER_VIEW
AS
/*
**
** Intended to be called by AA_NL_TRIAL_BALANCE_HEADER_S which will perform aggregate calculations and grouping on the data.
** The following fields are intended to be displayed:
**          Major Heading Name   - NMAJORNAME
**          Debit (home)         - DEBIT
**          Credit (home)        - CREDIT
**          Debit (Currency)     - DEBIT_CURR
**          Credit (Currency)    - CREDIT_CURR
**
** The following fields are required for searching:
**          Nominal Account Code - NCODE
**          Nominal Account Name - NNAME
**          Currency Code        - NCURRCODE
**          Category Codes       - NCATCODE1-NCATCODE8
**          Major Heading Code   - NMAJORCODE
**          Category To View     - CATEGORY
**          Year (L,C,N)         - YEAR
**          Period (1-13)        - PERIOD
**
**          [PRIMARY] identifies a row in the result set
**          HEADCODE is intended to allow the client to rearrange the data layout in a grid
**
** The list will be sorted by PRIMARY with any other supplied order by field
**
** Written:      20/09/2005 SB
** Last Amended: 05/10/2005 SB, 19/01/06 SB, 03/11/2006
*/
select
   V.[PRIMARY]
   ,V.HEADCODE
   ,V.NCODE NCODE
   ,V.NNAME NNAME
   ,V.NCATEGORYCODE1 NCATCODE1
   ,V.NCATEGORYCODE2 NCATCODE2
   ,V.NCATEGORYCODE3 NCATCODE3
   ,V.NCATEGORYCODE4 NCATCODE4
   ,V.NCATEGORYCODE5 NCATCODE5
   ,V.NCATEGORYCODE6 NCATCODE6
   ,V.NCATEGORYCODE7 NCATCODE7
   ,V.NCATEGORYCODE8 NCATCODE8
   ,V.NMAJORHEADCODE NMAJORCODE
   ,V.NL_MAJORNAME NMAJORNAME
   ,V.NCURRENCYCODE NCURRCODE
   ,V.PERIOD PERIOD
   ,V.YEAR YEAR
   ,dbo.AA_VALUE_DPS_F(case when sign(VALUE) = 1 then VALUE else 0 end) DEBIT
   ,dbo.AA_VALUE_DPS_F(case when sign(VALUE) = -1 then VALUE*-1 else 0 end) CREDIT
   ,dbo.AA_VALUE_DPS_F(case when sign(CURRENCY_VALUE) = 1 then CURRENCY_VALUE else 0 end) CURR_DEBIT
   ,dbo.AA_VALUE_DPS_F(case when sign(CURRENCY_VALUE) = -1 then CURRENCY_VALUE*-1 else 0 end) CURR_CREDIT
from(
   select NM_PRIMARY [PRIMARY]
   ,cast(NM_PRIMARY as decimal(16,1)) HEADCODE
   ,NCODE
   ,isnull(NNAME,'') NNAME
   ,isnull(NCATEGORYCODE1,'') NCATEGORYCODE1
   ,isnull(NCATEGORYCODE2,'') NCATEGORYCODE2
   ,isnull(NCATEGORYCODE3,'') NCATEGORYCODE3
   ,isnull(NCATEGORYCODE4,'') NCATEGORYCODE4
   ,isnull(NCATEGORYCODE5,'') NCATEGORYCODE5
   ,isnull(NCATEGORYCODE6,'') NCATEGORYCODE6
   ,isnull(NCATEGORYCODE7,'') NCATEGORYCODE7
   ,isnull(NCATEGORYCODE8,'') NCATEGORYCODE8
   ,NMAJORHEADCODE
   ,NCURRENCYCODE
   ,case
      when PERIOD = 1 and YEAR ='C'
      then NOPENBALYEAR + NTURNOVER_C1
      when PERIOD = 2 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2
      when PERIOD = 3 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3
      when PERIOD = 4 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4
      when PERIOD = 5 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5
      when PERIOD = 6 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6
      when PERIOD = 7 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7
      when PERIOD = 8 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8
      when PERIOD = 9 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9
      when PERIOD = 10 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10
      when PERIOD = 11 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11
      when PERIOD = 12 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12
      when PERIOD = 13 and YEAR = 'C'
      then NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 1 and [YEAR] ='L'
      then NOPENBALANCELY + NTURNOVER_L1
      when PERIOD = 2 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2
      when PERIOD = 3 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3
      when PERIOD = 4 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4
      when PERIOD = 5 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5
      when PERIOD = 6 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6
      when PERIOD = 7 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7
      when PERIOD = 8 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8
      when PERIOD = 9 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9
      when PERIOD = 10 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10
      when PERIOD = 11 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10 + NTURNOVER_L11
      when PERIOD = 12 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10 + NTURNOVER_L11 + NTURNOVER_L12
      when PERIOD = 13 and YEAR = 'L'
      then NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10 + NTURNOVER_L11 + NTURNOVER_L12 + NTURNOVER_L13
      when PERIOD = 1 and [YEAR] ='N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 2 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 3 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 4 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 5 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 6 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 7 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 8 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 9 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 10 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 11 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_N11 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 12 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_N11 + NTURNOVER_N12 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      when PERIOD = 13 and YEAR = 'N'
      then NOPENBALYEAR + NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_N11 + NTURNOVER_N12 + NTURNOVER_N13 + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13
      else 0
   end VALUE
   ,case
      when PERIOD = 1 and YEAR ='C'
      then NOPENBALYR_C + NTURNOVER_C1_C
      when PERIOD = 2 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C
      when PERIOD = 3 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C
      when PERIOD = 4 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C
      when PERIOD = 5 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C
      when PERIOD = 6 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C
      when PERIOD = 7 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C
      when PERIOD = 8 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C
      when PERIOD = 9 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C
      when PERIOD = 10 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C
      when PERIOD = 11 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C
      when PERIOD = 12 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C
      when PERIOD = 13 and YEAR = 'C'
      then NOPENBALYR_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 1 and [YEAR] ='L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C
      when PERIOD = 2 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C
      when PERIOD = 3 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C
      when PERIOD = 4 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C
      when PERIOD = 5 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C
      when PERIOD = 6 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C
      when PERIOD = 7 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C
      when PERIOD = 8 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C
      when PERIOD = 9 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C + NTURNOVER_L9_C
      when PERIOD = 10 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C + NTURNOVER_L9_C + NTURNOVER_L10_C
      when PERIOD = 11 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C + NTURNOVER_L9_C + NTURNOVER_L10_C + NTURNOVER_L11_C
      when PERIOD = 12 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C + NTURNOVER_L9_C + NTURNOVER_L10_C + NTURNOVER_L11_C + NTURNOVER_L12_C
      when PERIOD = 13 and YEAR = 'L'
      then NOPENBALANCLY_C + NTURNOVER_L1_C + NTURNOVER_L2_C + NTURNOVER_L3_C + NTURNOVER_L4_C + NTURNOVER_L5_C + NTURNOVER_L6_C + NTURNOVER_L7_C + NTURNOVER_L8_C + NTURNOVER_L9_C + NTURNOVER_L10_C + NTURNOVER_L11_C + NTURNOVER_L12_C + NTURNOVER_L13_C
      when PERIOD = 1 and [YEAR] ='N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 2 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 3 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 4 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 5 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 6 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 7 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 8 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 9 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_N9_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 10 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_N9_C + NTURNOVER_N10_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 11 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_N9_C + NTURNOVER_N10_C + NTURNOVER_N11_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 12 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_N9_C + NTURNOVER_N10_C + NTURNOVER_N11_C + NTURNOVER_N12_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      when PERIOD = 13 and YEAR = 'N'
      then NOPENBALYR_C + NTURNOVER_N1_C + NTURNOVER_N2_C + NTURNOVER_N3_C + NTURNOVER_N4_C + NTURNOVER_N5_C + NTURNOVER_N6_C + NTURNOVER_N7_C + NTURNOVER_N8_C + NTURNOVER_N9_C + NTURNOVER_N10_C + NTURNOVER_N11_C + NTURNOVER_N12_C + NTURNOVER_N13_C + NTURNOVER_C1_C + NTURNOVER_C2_C + NTURNOVER_C3_C + NTURNOVER_C4_C + NTURNOVER_C5_C + NTURNOVER_C6_C + NTURNOVER_C7_C + NTURNOVER_C8_C + NTURNOVER_C9_C + NTURNOVER_C10_C + NTURNOVER_C11_C + NTURNOVER_C12_C + NTURNOVER_C13_C
      else 0
   end CURRENCY_VALUE
      ,isnull(dbo.NL_MAJORHEADING.NL_MAJORNAME,'') NL_MAJORNAME
      ,PERIOD
      ,YEAR
   from NL_ACCOUNTS N1 inner join dbo.NL_MAJORHEADING on NMAJORHEADCODE = dbo.NL_MAJORHEADING.NL_MAJORCODE
      ,(select 1 as PERIOD union select 2 as PERIOD union select 3 as PERIOD
         union select 4 as PERIOD union select 5 as PERIOD
         union select 6 as PERIOD union select 7 as PERIOD union select 8 as PERIOD
         union select 9 as PERIOD union select 10 as PERIOD
         union select 11 as PERIOD union select 12 as PERIOD union select 13 as PERIOD
       ) PERIODS
       ,(select 'L' as Year union select 'C' as Year union select 'N' as Year) YEARS
   ) V

