CREATE VIEW AA_NET_STK_SUBANALYSIS_VIEW
/*
** Written:        09/12/02 SRB
** Amended:   	   10/12/02 ROBB
** Last Amended:   23/12/02 ROBB, 06/01/03 NC, 30/01/03 SRB, 04/06/04 NC
*/
AS

SELECT
LOC_CONCATCODE,
LOC_STOCK_CODE,
STKNAME,
LOC_CODE,
LOC_USERSORT1,
LOC_USERSORT2,
LOC_USERSORT3,
LOC_USERSORT4,
LOC_USERSORT5,
LOC_USERSORT6,
LOC_NAME,
dbo.AA_QUANTITY_DPS_F(LOC_MIN_QTY) as LOC_MIN_QTY,
dbo.AA_QUANTITY_DPS_F(LOC_MAX_QTY) as LOC_MAX_QTY,
LOC_BIN_NUMBER,
LOC_SANALYSIS,
SANAME,
LOC_PANALYSIS,
PANAME,
dbo.AA_PRICE_DPS_F(LOC_COSTPRICE) as LOC_COSTPRICE,
LOC_NOTES,
dbo.AA_VALUE_DPS_F(LOC_PHYSICAL) as LOC_PHYSICAL,
dbo.AA_QUANTITY_DPS_F(LOC_QTYPRINTED) as LOC_QTYPRINTED,
dbo.AA_VALUE_DPS_F(LOC_ORDER_IN) as LOC_ORDER_IN,
dbo.AA_VALUE_DPS_F(LOC_RESERVE_OUT) as LOC_RESERVE_OUT,
LOC_DATE_PUTIN,
LOC_DATE_EDITED,
LOC_USERTEXT1,
LOC_USERTEXT2,
LOC_USERTEXT3,
LOC_USERTEXT4,
LOC_USERTEXT5,
LOC_USERTEXT6,
LOC_USERDATE1,
LOC_USERDATE2,
LOC_USERDATE3,
LOC_USERFLAG1,
LOC_USERFLAG2,
LOC_USERFLAG3,
LOC_USERVALUE1,
LOC_USERVALUE2,
LOC_USERVALUE3,
LOC_STNDRD_COST,
LOC_SOPCHECK,
LOC_POPCHECK,
LOC_LANDED_COMPLETE,
LOC_LANDED_NAME1,
case
	when LOC_LANDED1_TYPE1 = 0 then 
		'V'
	when LOC_LANDED1_TYPE1 = 1 then 
		'P'
	when LOC_LANDED1_TYPE1 = 2 then
		'T'
	when LOC_LANDED1_TYPE1 = 3 then
		'F'
end as
LOC_LANDED1_TYPE1,
dbo.AA_VALUE_DPS_F(LOC_LANDED_VALUE1) as LOC_LANDED_VALUE1,
LOC_LANDED_NAME2,
case
	when LOC_LANDED1_TYPE2 = 0 then 
		'V'
	when LOC_LANDED1_TYPE2 = 1 then 
		'P'
	when LOC_LANDED1_TYPE2 = 2 then
		'T'
	when LOC_LANDED1_TYPE2 = 3 then
		'F'
end as
LOC_LANDED1_TYPE2,
dbo.AA_VALUE_DPS_F(LOC_LANDED_VALUE2) as LOC_LANDED_VALUE2,
LOC_LANDED_NAME3,
case
	when LOC_LANDED1_TYPE3 = 0 then 
		'V'
	when LOC_LANDED1_TYPE3 = 1 then 
		'P'
	when LOC_LANDED1_TYPE3 = 2 then
		'T'
	when LOC_LANDED1_TYPE3 = 3 then
		'F'
end as
LOC_LANDED1_TYPE3,
dbo.AA_VALUE_DPS_F(LOC_LANDED_VALUE3) as LOC_LANDED_VALUE3,
LOC_LANDED_NAME4,
case
	when LOC_LANDED1_TYPE4 = 0 then 
		'V'
	when LOC_LANDED1_TYPE4 = 1 then 
		'P'
	when LOC_LANDED1_TYPE4 = 2 then
		'T'
	when LOC_LANDED1_TYPE4 = 3 then
		'F'
end as
LOC_LANDED1_TYPE4,
dbo.AA_VALUE_DPS_F(LOC_LANDED_VALUE4) as LOC_LANDED_VALUE4,
LOC_LANDED_NAME5,
case
	when LOC_LANDED1_TYPE5 = 0 then 
		'V'
	when LOC_LANDED1_TYPE5 = 1 then 
		'P'
	when LOC_LANDED1_TYPE5 = 2 then
		'T'
	when LOC_LANDED1_TYPE5 = 3 then
		'F'
end as
LOC_LANDED1_TYPE5,
dbo.AA_VALUE_DPS_F(LOC_LANDED_VALUE5) as LOC_LANDED_VALUE5,
LOC_LANDED_NAME6,
case
	when LOC_LANDED1_TYPE6 = 0 then 
		'V'
	when LOC_LANDED1_TYPE6 = 1 then 
		'P'
	when LOC_LANDED1_TYPE6 = 2 then
		'T'
	when LOC_LANDED1_TYPE6 = 3 then
		'F'
end as
LOC_LANDED1_TYPE6,
dbo.AA_VALUE_DPS_F(LOC_LANDED_VALUE6) as LOC_LANDED_VALUE6,
LOC_LANDED_NAME7,
case
	when LOC_LANDED1_TYPE7 = 0 then 
		'V'
	when LOC_LANDED1_TYPE7 = 1 then 
		'P'
	when LOC_LANDED1_TYPE7 = 2 then
		'T'
	when LOC_LANDED1_TYPE7 = 3 then
		'F'
end as
LOC_LANDED1_TYPE7,
dbo.AA_VALUE_DPS_F(LOC_LANDED_VALUE7) as LOC_LANDED_VALUE7,
LOC_LANDED_NAME8,
case
	when LOC_LANDED1_TYPE8 = 0 then 
		'V'
	when LOC_LANDED1_TYPE8 = 1 then 
		'P'
	when LOC_LANDED1_TYPE8 = 2 then
		'T'
	when LOC_LANDED1_TYPE8 = 3 then
		'F'
end as
LOC_LANDED1_TYPE8,
dbo.AA_VALUE_DPS_F(LOC_LANDED_VALUE8) as LOC_LANDED_VALUE8,
LOC_LANDED_NAME9,
case
	when LOC_LANDED1_TYPE9 = 0 then 
		'V'
	when LOC_LANDED1_TYPE9 = 1 then 
		'P'
	when LOC_LANDED1_TYPE9 = 2 then
		'T'
	when LOC_LANDED1_TYPE9 = 3 then
		'F'
end as
LOC_LANDED1_TYPE9,
dbo.AA_VALUE_DPS_F(LOC_LANDED_VALUE9) as LOC_LANDED_VALUE9,
LOC_LANDED_NAME10,
case
	when LOC_LANDED1_TYPE10 = 0 then 
		'V'
	when LOC_LANDED1_TYPE10 = 1 then 
		'P'
	when LOC_LANDED1_TYPE10 = 2 then
		'T'
	when LOC_LANDED1_TYPE10 = 3 then
		'F'
end as
LOC_LANDED1_TYPE10,
dbo.AA_VALUE_DPS_F(LOC_LANDED_VALUE10) as LOC_LANDED_VALUE10,
LOC_PRIMARY,

dbo.AA_VALUE_DPS_F(LOC_LANDED_TOTAL1) as LOC_LANDED_TOTAL1,
dbo.AA_VALUE_DPS_F(LOC_LANDED_TOTAL2) as LOC_LANDED_TOTAL2,
dbo.AA_VALUE_DPS_F(LOC_LANDED_TOTAL3) as LOC_LANDED_TOTAL3,
dbo.AA_VALUE_DPS_F(LOC_LANDED_TOTAL4) as LOC_LANDED_TOTAL4,
dbo.AA_VALUE_DPS_F(LOC_LANDED_TOTAL5) as LOC_LANDED_TOTAL5,
dbo.AA_VALUE_DPS_F(LOC_LANDED_TOTAL6) as LOC_LANDED_TOTAL6,
dbo.AA_VALUE_DPS_F(LOC_LANDED_TOTAL7) as LOC_LANDED_TOTAL7,
dbo.AA_VALUE_DPS_F(LOC_LANDED_TOTAL8) as LOC_LANDED_TOTAL8,
dbo.AA_VALUE_DPS_F(LOC_LANDED_TOTAL9) as LOC_LANDED_TOTAL9,
dbo.AA_VALUE_DPS_F(LOC_LANDED_TOTAL10) as LOC_LANDED_TOTAL10,
dbo.AA_VALUE_DPS_F(LOC_LANDED_COMMITTED1) as LOC_LANDED_COMMITTED1,
dbo.AA_VALUE_DPS_F(LOC_LANDED_COMMITTED2) as LOC_LANDED_COMMITTED2,
dbo.AA_VALUE_DPS_F(LOC_LANDED_COMMITTED3) as LOC_LANDED_COMMITTED3,
dbo.AA_VALUE_DPS_F(LOC_LANDED_COMMITTED4) as LOC_LANDED_COMMITTED4,
dbo.AA_VALUE_DPS_F(LOC_LANDED_COMMITTED5) as LOC_LANDED_COMMITTED5,
dbo.AA_VALUE_DPS_F(LOC_LANDED_COMMITTED6) as LOC_LANDED_COMMITTED6,
dbo.AA_VALUE_DPS_F(LOC_LANDED_COMMITTED7) as LOC_LANDED_COMMITTED7,
dbo.AA_VALUE_DPS_F(LOC_LANDED_COMMITTED8) as LOC_LANDED_COMMITTED8,
dbo.AA_VALUE_DPS_F(LOC_LANDED_COMMITTED9) as LOC_LANDED_COMMITTED9,
dbo.AA_VALUE_DPS_F(LOC_LANDED_COMMITTED10) as LOC_LANDED_COMMITTED10,

/* need calculations */
STOCKFREE,
STKVALUE,
VALUATION,
VALUATIONWITHLANDEDCOSTS,
STANDARDVALUE,
STANDARDVALUEWITHLANDEDCOSTS,
COMMITTEDLANDEDCOSTS,

ACTUALLANDEDCOSTS,

dbo.AA_VALUE_DPS_F((ACTUALLANDEDCOSTS / QUANTITYOUTSTANDINGFORCALC))
AS
ACTUALLANDEDCOSTSEACH,

dbo.AA_VALUE_DPS_F((STKVALUE / QUANTITYOUTSTANDINGFORCALC))
AS
STKVALUATIONEACH,
dbo.AA_VALUE_DPS_F((VALUATIONWITHLANDEDCOSTS / QUANTITYOUTSTANDINGFORCALC))
AS
STKVALUATIONWITHLANDEDCOSTSEACH,
dbo.AA_VALUE_DPS_F((STANDARDVALUE / QUANTITYOUTSTANDINGFORCALC))
AS
STANDARDVALUEEACH,
dbo.AA_VALUE_DPS_F((STANDARDVALUEWITHLANDEDCOSTS / QUANTITYOUTSTANDINGFORCALC))
AS
STANDARDVALUEWITHLANDEDCOSTSEACH,

dbo.AA_QUANTITY_DPS_F(LOC_BACK_ORDER_QTY) as LOC_BACK_ORDER_QTY

from STK_LOCATION 
	inner join STK_STOCK_2 ON STKCODE2 = LOC_STOCK_CODE
	inner join STK_LOCATION2 ON    LOC_CONCATCODE2 = LOC_CONCATCODE
	inner join AA_NET_STK_SUBANALYSIS_CALCS_VIEW on LOC_CONCATCODE = CONCATCODE
	inner join STK_STOCK
	on STK_LOCATION.LOC_STOCK_CODE = STK_STOCK.STKCODE
 	left outer join SL_ANALYSIS
	on STK_LOCATION.LOC_SANALYSIS = SL_ANALYSIS.SACODE
	left outer join PL_ANALYSIS
	on STK_LOCATION.LOC_PANALYSIS = PL_ANALYSIS.PACODE
	join sys_datainfo2 on sys_primary_2=1 
	join sys_datainfo on sys_primary=1  



