CREATE VIEW AA_NET_PL_ADDRESS_VIEW
AS 
SELECT 
PL_AD_CON_CODE,
PL_AD_ACCCODE,
SUNAME,
CURR_SYMBOL,
PL_AD_CODE,
PL_AD_ADDRESS,
PL_AD_ADDRESS_USER1,
PL_AD_ADDRESS_USER2,
PL_AD_POSTCODE,
PL_AD_CONTACT,
PL_AD_PHONE,
PL_AD_FAX,
PL_AD_EMAIL,
PL_AD_INV_ADD,
PL_AD_DEL_ADD,
PL_AD_STAT_ADD,
PL_AD_DEL_ADDRESS_2,
PL_AD_REM_ADD,
PL_AD_CON_TITLE,
PL_AD_CON_INITS,
PL_AD_CON_SNAME,
PL_AD_CON_FNAME,
PL_AD_CON_JOB,
PL_AD_CONT_SAL,
PL_AD_NOTE,
PL_AD_ANALYSIS,
PL_AD_CC_EMAIL,
PL_AD_COUNTRY
FROM PL_ADDRESSES
INNER JOIN PL_ACCOUNTS ON SUCODE = PL_AD_ACCCODE
JOIN SYS_CURRENCY ON SUCURRENCYCODE = CURR_CODE
