CREATE VIEW AA_NET_SL_ACCOUNTS_LIST_VIEW
/*
** Returns a table to be used specifically with AA_NET_SL_ACCOUNTS_LIST_VIEW
** Written:      28/04/03 SRB
** Last Amended: 04/07/03 SRB
**
*/
AS

SELECT

CUCODE as [PRIMARY]
,CU_LEVEL as PROFILELEVEL
,CU_DATE_PUTIN
,CU_DATE_EDITED
,CUCODE
,CUCODE AS CHILD
,COALESCE(CUNAME, '') as CUNAME
,CU_ADDRESS_USER1
,CUPHONE
,CUPOSTCODE
,CUCONTACT
,COALESCE(CUCURRENCYCODE, '') as CUCURRENCYCODE
,COALESCE(CUBALANCE, '0') as CUBALANCE
,CU_CREDIT_LIMIT
,COALESCE(CUSORT, '') as CUSORT
,COALESCE(CUUSER1, '') as CUUSER1
,COALESCE(CUUSER2, '') as CUUSER2
,COALESCE(CUUSER3, '') as CUUSER3
,CU_EMAIL
,CU_ON_STOP
,CURR_SYMBOL
 --Need to ensure the field is populated as every customer is related to a country, by defatult the home.
,case COALESCE(CU_COUNTRY_CODE,'')
	when '' then HOME_COUNTRY
	else CU_COUNTRY_CODE
end 

as
CU_COUNTRY_CODE

--Over Credit Limit
,CASE WHEN CU_CREDIT_LIMIT > 0  and (CUBALANCE>CU_CREDIT_LIMIT) THEN
	1
ELSE
	0

END

as 

OVERCREDITLIMIT
	
FROM SL_ACCOUNTS

LEFT JOIN SL_ACCOUNTS2 ON
	CU_PRIMARY = CU_PRIMARY_2
JOIN  SYS_DATAINFO ON SYS_PRIMARY = 1
LEFT JOIN SYS_CURRENCY ON
	CURR_CODE = CUCURRENCYCODE
	
WHERE CUCODE IS NOT NULL and CUCODE != '' 

