CREATE VIEW AA_NET_CST_RESOURCE_LIST_VIEW
/*
** Returns a table to be used specifically with AA_NET_CST_RESOURCE_LIST_S
** Written:      13/03/03 ROBB
** Last Amended: 
**
*/

AS

SELECT 

PRCODE AS [PRIMARY],
PR_LEVEL AS PROFILELEVEL,
PRCODE,
COALESCE(PRNAME,'') AS PRNAME,
PR_DATE_PUTIN,
PR_DATE_EDITED,
COALESCE(PR_SORT_KEY,'') AS PR_SORT_KEY,
PR_SORT_KEY1,
PR_SORT_KEY2,
PR_SORT_KEY3,
PR_SORT_KEY4,
PR_SORT_KEY5,
PR_SORT_KEY6

FROM PRC_PRICE_RECS
WHERE PR_TYPE = 'R'
