CREATE VIEW AA_NET_NL_RECORD_VIEW_CALCS
/*
** Written:        10/12/02 SRB
** Last Amended: 
*/
AS

select 
NCODE AS NOMINALCODE,
CASE WHEN len(NOM_BUDG_SUSPENSE)>0 THEN
	NBUDGETPTD	
ELSE
	 CASE 
	WHEN NOMINAL_PERIOD = 1 THEN 
		NBUDGET_C1	
	WHEN NOMINAL_PERIOD = 2 THEN 
		NBUDGET_C2 
	WHEN NOMINAL_PERIOD = 3  THEN 
		NBUDGET_C3	
	WHEN NOMINAL_PERIOD=4 THEN 
		NBUDGET_C4 
	WHEN NOMINAL_PERIOD=5 THEN 
		NBUDGET_C5 
	WHEN NOMINAL_PERIOD=6 THEN 
		NBUDGET_C6 
	WHEN NOMINAL_PERIOD=7 THEN 
		NBUDGET_C7 
	WHEN NOMINAL_PERIOD=8 THEN 
		NBUDGET_C8 
	WHEN NOMINAL_PERIOD=9 THEN 
		NBUDGET_C9 
	WHEN NOMINAL_PERIOD=10 THEN 
		NBUDGET_C10 
	WHEN NOMINAL_PERIOD=11 THEN 
		NBUDGET_C11 
	WHEN NOMINAL_PERIOD=12 THEN 
		NBUDGET_C12 
	WHEN NOMINAL_PERIOD=13 THEN 
		NBUDGET_C13 
     END 	
END 
AS
BUDGETPTD,

CASE WHEN len(NOM_BUDG_SUSPENSE)>0 THEN
     NBUDGETYTD

ELSE
     NBUDGET_C1 +
     CASE 
	WHEN NOMINAL_PERIOD = 1 THEN 
		0 		
	WHEN NOMINAL_PERIOD = 2 THEN 
		NBUDGET_C2 

	WHEN NOMINAL_PERIOD = 3  THEN 
		NBUDGET_C2 + NBUDGET_C3
	
	WHEN NOMINAL_PERIOD=4 THEN 
		NBUDGET_C2 + NBUDGET_C3 + NBUDGET_C4 
	
	WHEN NOMINAL_PERIOD=5 THEN 
		NBUDGET_C2 + NBUDGET_C3 + NBUDGET_C4 + NBUDGET_C5 

	WHEN NOMINAL_PERIOD=6 THEN 
		NBUDGET_C2 + NBUDGET_C3 + NBUDGET_C4 + NBUDGET_C5 +
		NBUDGET_C6 

	WHEN NOMINAL_PERIOD=7 THEN 
		NBUDGET_C2 + NBUDGET_C3 + NBUDGET_C4 + NBUDGET_C5 +
		NBUDGET_C6 + NBUDGET_C7 

	WHEN NOMINAL_PERIOD=8 THEN 
		NBUDGET_C2 + NBUDGET_C3 + NBUDGET_C4 + NBUDGET_C5 +
		NBUDGET_C6 + NBUDGET_C7 + NBUDGET_C8 

	WHEN NOMINAL_PERIOD=9 THEN 
		NBUDGET_C2 + NBUDGET_C3 + NBUDGET_C4 + NBUDGET_C5 +
		NBUDGET_C6 + NBUDGET_C7 + NBUDGET_C8 + NBUDGET_C9 

	WHEN NOMINAL_PERIOD=10 THEN 
		NBUDGET_C2 + NBUDGET_C3 + NBUDGET_C4 + NBUDGET_C5 +
		NBUDGET_C6 + NBUDGET_C7 + NBUDGET_C8 + NBUDGET_C9 +
		NBUDGET_C10 

	WHEN NOMINAL_PERIOD=11 THEN 
		NBUDGET_C2 + NBUDGET_C3 + NBUDGET_C4 + NBUDGET_C5 +
		NBUDGET_C6 + NBUDGET_C7 + NBUDGET_C8 + NBUDGET_C9 +
		NBUDGET_C10 + NBUDGET_C11 

	WHEN NOMINAL_PERIOD=12 THEN 
		NBUDGET_C2 + NBUDGET_C3 + NBUDGET_C4 + NBUDGET_C5 +
		NBUDGET_C6 + NBUDGET_C7 + NBUDGET_C8 + NBUDGET_C9 +
		NBUDGET_C10 + NBUDGET_C11 + NBUDGET_C12 

	WHEN NOMINAL_PERIOD=13 THEN 
		NBUDGET_C2 + NBUDGET_C3 + NBUDGET_C4 + NBUDGET_C5 +
		NBUDGET_C6 + NBUDGET_C7 + NBUDGET_C8 + NBUDGET_C9 +
		NBUDGET_C10 + NBUDGET_C11 + NBUDGET_C12 + NBUDGET_C13 
     END 
	
		
END 
AS
BUDGETYTD

FROM 

NL_ACCOUNTS
join sys_datainfo on sys_primary=1 
join sys_datainfo2 on sys_primary_2=1 

