CREATE VIEW AA_NET_STK_RECORD_VIEW
/*
** Written:			10/12/02 ROBB
** Last Amended:	15/01/03 SRB; 20/01/03 SRB, 11/02/03 ROBB, 04/06/04 NC
*/
AS

select 
STKCODE,
STKNAME,
STK_MULTILOCATN,
STK_SERIALTRACK,
case 
	when STK_ASSEMBLY = 'A' Then
		1		
	Else			
		0
end
as 
ASSEMBLY,
case 
	when STK_ASSEMBLY = 'C' Then
		1		
	Else			
		0
end
as 
COMPONENT,
STK_ALTERNATIVE_FLAG,
STK_LINK_FLAG,
STK_TEMPLATE,
STK_RTP_FLAG,
STK_SORT_KEY,
STK_SORT_KEY1,
STK_SORT_KEY2,
STK_SORT_KEY3,
dbo.AA_QUANTITY_DPS_F(STK_MIN_QTY) AS STK_MIN_QTY,
dbo.AA_QUANTITY_DPS_F(STK_MAX_QTY) AS STK_MAX_QTY,
STK_BIN_NUMBER,
dbo.AA_QUANTITY_DPS_F(STK_PHYSICAL) AS STK_PHYSICAL,
dbo.AA_QUANTITY_DPS_F(STK_QTYPRINTED) AS STK_QTYPRINTED,
dbo.AA_QUANTITY_DPS_F(STK_ORDER_IN) AS STK_ORDER_IN,
dbo.AA_QUANTITY_DPS_F(STK_RESERVE_OUT) AS STK_RESERVE_OUT,

dbo.AA_QUANTITY_DPS_F((STK_PHYSICAL + STK_QTYPRINTED +

CASE 
	WHEN STK_FREE_METHOD='F' THEN
		STK_ORDER_IN	
	ELSE
		0
END 

-STK_RESERVE_OUT+STK_RESERVE_ASM))
AS 
STOCKFREE,

dbo.AA_VALUE_DPS_F(
COALESCE(
CASE STK_USR_VALUATN
	WHEN 'F' THEN
		STK_FIFO_VALU
	WHEN 'A' THEN
		STK_AV_VALU
	WHEN 'W' THEN
		0
	ELSE 
		(STK_PHYSICAL+STK_QTYPRINTED)*

		(STK_COSTPRICE/
		CASE 
			--Needed to stop a divide by zero
			STK_BUY_UNIT1 
				WHEN 0 THEN 
					1
				ELSE
					STK_BUY_UNIT1
				END 
		)
	END 

,0)
)
AS VALUATION,
STK_NOTES,
STK_OLDCODE,
STK_DATE_PUTIN,
STK_DATE_EDITED,
STK_LEVEL,
PIC_PATHNAME,
dbo.AA_FOUR_DPS_F(STK_P_WEIGHT) AS STK_P_WEIGHT,
STK_P_WGHT_NAME,
dbo.AA_FOUR_DPS_F(STK_S_WEIGHT) AS STK_S_WEIGHT,
STK_S_WGHT_NAME,
dbo.AA_PRICE_DPS_F(STK_BASEPRICE) AS STK_BASEPRICE,
dbo.AA_PRICE_DPS_F(STK_COSTPRICE) AS STK_COSTPRICE,
dbo.AA_PRICE_DPS_F(STK_STNDRD_COST) AS STK_STNDRD_COST,
STK_WWW_PUBLISH,
STK_SPECIAL_PRICE_DATE,
STK_EC_KILOS,
STK_EC_ORIGIN,
STK_EC_COM_CODE,
STK_EC_SUP_UNIT,
STK_USRCHAR1,
STK_USRCHAR2,
STK_USRCHAR5,
STK_USRCHAR6,
STK_USRCHAR7,
STK_USRCHAR8,
STK_USRDATE1,
STK_USRDATE2,
STK_USRDATE3,
STK_USRFLAG1,
STK_USRFLAG2,
STK_USRFLAG3,
STK_USRNUM1,
STK_USRNUM2,
STK_USRNUM3,
STK_PRIMARY,
STK_USED,
dbo.AA_QUANTITY_DPS_F(STK_BACK_ORDER_QTY) as STK_BACK_ORDER_QTY

from STK_STOCK 
	JOIN SYS_DATAINFO2 
		ON SYS_PRIMARY_2=1
	left outer join STK_STOCK3 
		on STK_STOCK.STKCODE = STK_STOCK3.STKCODE3
	left outer join STK_PICTURE
		on STK_STOCK.STKCODE = STK_PICTURE.PIC_STK_CODE
	inner join stk_stock_2 
		on STKCODE = STKCODE2
	join sys_datainfo 
		on sys_primary=1 



