CREATE VIEW AA_NET_CST_COSTCENTRE_VIEW
/*
** Written:        09/12/02 ROBB
** Last Amended:  15/01/03 SRB; 14/03/03 ROBB; 17/03/03 ROBB
*/
as
select 
CC_CONCAT_CODES,
CC_COPYHEADER,
CH_NAME,
CC_CODE,
CC_NAME,
CC_USER_SUBTOT,
CC_CHRG_RATE,
dbo.AA_PRICE_DPS_F(CC_CHRG_VALUE) as CC_CHRG_VALUE,
CC_CHRG_LINE,
CC_UPLIFT_TYPE,
dbo.AA_VALUE_DPS_F(CC_COST_UPLIFTP) as CC_COST_UPLIFTP,
CC_DATE_REQ,
CC_DUR_TYPE,
CC_DURATION,
CC_ANALYSIS,
SANAME,
CC_NOTES,
CC_STATUS,
CC_LEVEL,
CC_LEVELPOINTER,
CC_LEVELSEQ,
CC_USRCHAR1,
CC_USRCHAR2,
CC_USRCHAR5,
CC_USRCHAR6,
CC_USRCHAR7,
CC_USRCHAR8,
CC_USRDATE1,
CC_USRDATE2,
CC_USRDATE3,
CC_USRFLAG1,
CC_USRFLAG2,
CC_USRFLAG3,
CC_USRNUM1,
CC_USRNUM2,
CC_USRNUM3,
CC_PRIMARY,
CC_USED,
CC_DATE_PUTIN,
CC_DATE_EDITED


from CST_COSTCENTRE
	left outer join CST_COSTCENTRE2
		on CST_COSTCENTRE.CC_CONCAT_CODES = CST_COSTCENTRE2.CC_CONCAT_CODES2
	inner join CST_COSTHEADER
		on CST_COSTCENTRE.CC_COPYHEADER = CST_COSTHEADER.CH_CODE
	left outer join SL_ANALYSIS
		on CST_COSTCENTRE.CC_ANALYSIS = SL_ANALYSIS.SACODE