CREATE VIEW AA_NET_POP_HEADER_TRAN_VIEW
/*
** Written:        
** Last Amended: 09/12/02 SRB; 20/03/03 ROBB; 30/04/03 ROBB; 06/05/03 ROBB
*/

AS

SELECT
POH_ACCOUNT,
SUNAME,
SU_ON_STOP,
SU_MULTI_CURR,
dbo.AA_PRICE_DPS_F(SU_CREDIT_LIMIT) AS SU_CREDIT_LIMIT,
dbo.AA_PRICE_DPS_F(SUBALANCE) AS SUBALANCE,
dbo.AA_PRICE_DPS_F(SUTURNOVERYTD) AS SUTURNOVERYTD,
SU_TAX_CODE,
SYS_VATCONTROL.VAT_RATE AS VAT_RATE,
SYS_VATCONTROL.EC_TYPE,
SU_ANALYSIS,
PURCHASE_ANALYSIS_LINK.PACURRENCYSYMBL AS SUPPLIERANALYSISCURRSYMBOL,
PURCHASE_ANALYSIS_LINK.PANAME AS SUPPLIERANALYSISDESCRIPTION,
PURCHASE_ANALYSIS_LINK.PA_FORCE_COSTING AS SUPPLIERANALYSISCOMPCOSTING,
PURCHASE_ANALYSIS_LINK.VAT_CODE AS SUPPLIERANALYSISVATCODE,
PURCHASE_ANALYSIS_LINK.VAT_RATE AS SUPPLIERANALYSISVATRATE,
PURCHASE_ANALYSIS_LINK.EC_TYPE AS SUPPLIERANALYSISVATECTYPE,
POH_ORDER_NUMBR,
POH_STATUS,
POH_ORDER_REF,
POH_BATCH_REF,
POH_DESCRIPTION,
POH_YEAR,
POH_PERIOD,
POH_DATE,
POH_REQUIRED,
POH_DISC_LINE_P,
POH_DISC_TOT_P, 
POH_SETT_DISC_1, 
POH_SETT_DISC_2, 
POH_SETT_DAYS_1, 
POH_SETT_DAYS_2, 
POH_CURR_TYPE,
(case when POH_CURR_TYPE ='E'
		then
			POH_TRI_RATE1
		else
			POH_CURR_RATE
		end) 
as POH_CURR_RATE ,
POH_CURR_CODE, 
SYS_CURRENCY_REC.CURREC_PURCH_AN AS CURRENCYANALYSIS,
CURRENCY_ANALYSIS_LINK.PANAME AS CURRENCYANALYSISDESCRIPTION,
CURRENCY_ANALYSIS_LINK.PA_FORCE_COSTING AS CURRENCYANALYSISCOMPCOSTING,
CURRENCY_ANALYSIS_LINK.VAT_CODE AS CURRENCYANALYSISVATCODE,
CURRENCY_ANALYSIS_LINK.VAT_RATE AS CURRENCYANALYSISVATRATE,
CURRENCY_ANALYSIS_LINK.EC_TYPE AS CURRENCYANALYSISVATECTYPE,
POH_TRI_RATE2 AS EUROTOHOMERATE,
POH_IMPEXP_CODE,
POH_EC_DEL_TERM,
POH_EC_T_NATURE,
POH_EC_T_MODE,
SU_VAT_REG_NO,
dbo.AA_PRICE_DPS_F(POH_DEL_CHARGE) AS POH_DEL_CHARGE,
POH_DEL_CHG_PCT,
POH_DEL_METHOD,
dbo.AA_PRICE_DPS_F(POH_MIN_VAL) AS POH_MIN_VAL,
SU_DUEDATE_TYPE,
POH_DUE_DAYS,
POH_A_P_DAYS,
POH_TERMS,
POH_PRICE_KEY,
POH_DEL_ADD AS DELIVERYADDRESSNUMBER,
POH_DEL_ADD_POINT,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_LINK.PL_AD_ADDRESS
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_ADDRESS
			else
				DELIVERY_CU_ADDRESS_LINK.AD_ADDRESS
			end) 
	end) 
as DELIVERYADDRESS ,

(case when POH_DEL_ADD_POINT ='SU'
	then
		SUNAME
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_NAME
			else
				(SELECT CUNAME FROM SL_ACCOUNTS WHERE CUCODE = DELIVERY_CU_ADDRESS_LINK.AD_ACC_CODE)
			end) 
	end) 
as DELIVERYNAME ,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_LINK.PL_AD_ADDRESS_USER1
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_ADDRESS_USER1
			else
				DELIVERY_CU_ADDRESS_LINK.AD_ADDRESS_USER1
			end) 
	end) 
as DELIVERYTOWN ,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_LINK.PL_AD_ADDRESS_USER2
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_ADDRESS_USER2
			else
				DELIVERY_CU_ADDRESS_LINK.AD_ADDRESS_USER2
			end) 
	end) 
as DELIVERYCOUNTY ,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_LINK.PL_AD_COUNTRY
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_COUNTRY
			else
				DELIVERY_CU_ADDRESS_LINK.AD_COUNTRY
			end) 
	end) 
as DELIVERYCOUNTRY ,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_LINK.PL_AD_POSTCODE
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_POSTCODE
			else
				DELIVERY_CU_ADDRESS_LINK.AD_POSTCODE
			end) 
	end) 
as DELIVERYPOSTCODE ,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_LINK.PL_AD_EMAIL
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_EMAIL
			else
				DELIVERY_CU_ADDRESS_LINK.AD_E_MAIL
			end) 
	end) 
as DELIVERYEMAIL,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_LINK.PL_AD_PHONE
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_PHONE
			else
				DELIVERY_CU_ADDRESS_LINK.AD_PHONE
			end) 
	end) 
as DELIVERYPHONE,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_LINK.PL_AD_FAX
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_FAX
			else
				DELIVERY_CU_ADDRESS_LINK.AD_FAX
			end) 
	end) 
as DELIVERYFAX,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_LINK.PL_AD_CONTACT
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_CONTACT
			else
				DELIVERY_CU_ADDRESS_LINK.AD_CONTACT
			end) 
	end) 
as DELIVERYCONTACT,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_LINK.PL_AD_ANALYSIS
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_LINK.COAD_ANALYSIS
			else
				DELIVERY_CU_ADDRESS_LINK.AD_ANALYSIS
			end) 
	end) 
as DELIVERYANALYSIS,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_ANALYSIS_LINK.PACURRENCYSYMBL
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_ANALYSIS_LINK.PACURRENCYSYMBL
			else
				DELIVERY_CU_ADDRESS_ANALYSIS_LINK.PACURRENCYSYMBL
			end) 
	end) 
as DELIVERYANALYSISCURRENCY,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_ANALYSIS_LINK.PANAME
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_ANALYSIS_LINK.PANAME
			else
				DELIVERY_CU_ADDRESS_ANALYSIS_LINK.PANAME
			end) 
	end) 
as DELIVERYANALYSISDESCRIPTION,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_ANALYSIS_LINK.PA_FORCE_COSTING
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_ANALYSIS_LINK.PA_FORCE_COSTING
			else
				DELIVERY_CU_ADDRESS_ANALYSIS_LINK.PA_FORCE_COSTING
			end) 
	end) 
as DELIVERYANALYSISCOMPCOSTING,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_ANALYSIS_LINK.VAT_CODE
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_ANALYSIS_LINK.VAT_CODE
			else
				DELIVERY_CU_ADDRESS_ANALYSIS_LINK.VAT_CODE
			end) 
	end) 
as DELIVERYANALYSISVATCODE,

(case when POH_DEL_ADD_POINT ='SU'
	then
		dbo.AA_TWO_DPS_F(DELIVERY_SU_ADDRESS_ANALYSIS_LINK.VAT_RATE)
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				dbo.AA_TWO_DPS_F(DELIVERY_CO_ADDRESS_ANALYSIS_LINK.VAT_RATE)
			else
				dbo.AA_TWO_DPS_F(DELIVERY_CU_ADDRESS_ANALYSIS_LINK.VAT_RATE)
			end) 
	end) 
as DELIVERYANALYSISVATRATE,

(case when POH_DEL_ADD_POINT ='SU'
	then
		DELIVERY_SU_ADDRESS_ANALYSIS_LINK.EC_TYPE
	else
		(case when POH_DEL_ADD_POINT ='CO'
			then
				DELIVERY_CO_ADDRESS_ANALYSIS_LINK.EC_TYPE
			else
				DELIVERY_CU_ADDRESS_ANALYSIS_LINK.EC_TYPE
			end) 
	end) 
as DELIVERYANALYSISVATECTYPE,

POH_INV_ADD AS ORDERADDRESSNUMBER,
ORDER_ADDRESS_LINK.PL_AD_ADDRESS AS ORDERADDRESS,
ORDER_ADDRESS_LINK.PL_AD_ADDRESS_USER1 AS ORDERTOWN,
ORDER_ADDRESS_LINK.PL_AD_ADDRESS_USER2 AS ORDERCOUNTY,
ORDER_ADDRESS_LINK.PL_AD_COUNTRY AS ORDERCOUNTRY,
ORDER_ADDRESS_LINK.PL_AD_POSTCODE AS ORDERPOSTCODE,
ORDER_ADDRESS_LINK.PL_AD_EMAIL AS ORDEREMAIL,
ORDER_ADDRESS_LINK.PL_AD_PHONE AS ORDERPHONE,
ORDER_ADDRESS_LINK.PL_AD_FAX AS ORDERFAX,
ORDER_ADDRESS_LINK.PL_AD_CONTACT AS ORDERCONTACT,
ORDER_ADDRESS_LINK.PL_AD_DO_NOT_USE AS ORDEREXCLUDENAME,
ORDER_ADDRESS_ANALYSIS_LINK.PACODE AS ORDERANALYSIS,
ORDER_ADDRESS_ANALYSIS_LINK.PACURRENCYSYMBL AS ORDERANALYSISCURRENCY,
ORDER_ADDRESS_ANALYSIS_LINK.PANAME AS ORDERANALYSISDESCRIPTION,
ORDER_ADDRESS_ANALYSIS_LINK.PA_FORCE_COSTING AS ORDERANALYSISCOMPCOSTING,
ORDER_ADDRESS_ANALYSIS_LINK.VAT_CODE AS ORDERANALYSISVATCODE,
dbo.AA_TWO_DPS_F(ORDER_ADDRESS_ANALYSIS_LINK.VAT_RATE) AS ORDERANALYSISVATRATE,
ORDER_ADDRESS_ANALYSIS_LINK.EC_TYPE AS ORDERANALYSISVATECTYPE,

POH_ARCHIVE,
POH_USER1,
POH_USER2,
POH_USER3,
POH_SUB_LEDGER,
POH_USRCHAR1, 
POH_USRCHAR2, 
POH_USRCHAR3, 
POH_USRCHAR4, 
POH_USRFLAG1, 
POH_USRFLAG2, 
POH_USRDATE1, 
POH_USRDATE2, 
POH_USRNUM1, 
POH_USRNUM2,
SU_NOTES,
POH_PRIORITY,
POH_PRIMARY,
POH_BATCH_FLAG,
POH_MU_STATUS,
POH_TRAN_OPTIONS,
(case when substring(POH_TRAN_OPTIONS,(case when POH_TYPE = 'O' then 9 else 7 end),1) is null then 0 
	else substring(POH_TRAN_OPTIONS,(case when POH_TYPE = 'O' then 9 else 7 end),1) end) as CURRENCYENTRY,
(case when substring(POH_TRAN_OPTIONS,(case when POH_TYPE = 'O' then 8 else 6 end),1) is null then 0 
	else substring(POH_TRAN_OPTIONS,(case when POH_TYPE = 'O' then 8 else 6 end),1) end) as GROSSENTRY,
(case when substring(POH_TRAN_OPTIONS,2,1) is null then 0 
	else substring(POH_TRAN_OPTIONS,2,1) end) as UPDATESTOCKONORDER,
(case when substring(POH_TRAN_OPTIONS,(case when POH_TYPE = 'O' then 17 else 15 end),1) is null then 0 
	else substring(POH_TRAN_OPTIONS,(case when POH_TYPE = 'O' then 17 else 15 end),1) end) as ALLOWEMPTYSUBANALYSIS,
(case when substring(POH_TRAN_OPTIONS,(case when POH_TYPE = 'O' then 19 else 17 end),1) is null then 0 
	else substring(POH_TRAN_OPTIONS,(case when POH_TYPE = 'O' then 19 else 17 end),1) end) as ALLOWEMPTYSERIALNUMBER,
(case when POH_TYPE='C'
	then 
		'CRN'
	else		
		'ORD'
	end)
AS POH_ORDER_TYPE

FROM
POP_HEADER
JOIN SYS_DATAINFO ON SYS_PRIMARY=1
JOIN PL_ACCOUNTS ON POP_HEADER.POH_ACCOUNT = PL_ACCOUNTS.SUCODE
JOIN PL_ADDRESSES ORDER_ADDRESS_LINK ON ORDER_ADDRESS_LINK.PL_AD_CON_CODE = CONVERT(char(10),POH_ACCOUNT) + convert(varchar,POH_INV_ADD)

LEFT OUTER JOIN PL_ADDRESSES DELIVERY_SU_ADDRESS_LINK ON DELIVERY_SU_ADDRESS_LINK.PL_AD_CON_CODE = CONVERT(char(10),POH_ACCOUNT) + convert(varchar,POH_DEL_ADD)
LEFT OUTER JOIN SL_ADDRESSES DELIVERY_CU_ADDRESS_LINK ON DELIVERY_CU_ADDRESS_LINK.SL_AD_PRIMARY = POH_DEL_ADD
LEFT OUTER JOIN SYS_COMP_ADDRESS DELIVERY_CO_ADDRESS_LINK ON DELIVERY_CO_ADDRESS_LINK.COAD_PRIMARY = POH_DEL_ADD
LEFT OUTER JOIN AA_NET_PL_ANALYSIS_TRAN_VIEW DELIVERY_SU_ADDRESS_ANALYSIS_LINK ON COALESCE(DELIVERY_SU_ADDRESS_LINK.PL_AD_ANALYSIS,'') = DELIVERY_SU_ADDRESS_ANALYSIS_LINK.PACODE
LEFT OUTER JOIN AA_NET_PL_ANALYSIS_TRAN_VIEW DELIVERY_CU_ADDRESS_ANALYSIS_LINK ON COALESCE(DELIVERY_CU_ADDRESS_LINK.AD_ANALYSIS,'') = DELIVERY_CU_ADDRESS_ANALYSIS_LINK.PACODE
LEFT OUTER JOIN AA_NET_PL_ANALYSIS_TRAN_VIEW DELIVERY_CO_ADDRESS_ANALYSIS_LINK ON COALESCE(DELIVERY_CO_ADDRESS_LINK.COAD_ANALYSIS,'') = DELIVERY_CO_ADDRESS_ANALYSIS_LINK.PACODE
LEFT OUTER JOIN POP_HEADER2 ON POP_HEADER.POH_PRIMARY = POP_HEADER2.POH_PRIMARY_2
LEFT OUTER JOIN AA_NET_PL_ANALYSIS_TRAN_VIEW ORDER_ADDRESS_ANALYSIS_LINK ON COALESCE(ORDER_ADDRESS_LINK.PL_AD_ANALYSIS,'') = ORDER_ADDRESS_ANALYSIS_LINK.PACODE
LEFT OUTER JOIN AA_NET_PL_ANALYSIS_TRAN_VIEW PURCHASE_ANALYSIS_LINK ON COALESCE(PL_ACCOUNTS.SU_ANALYSIS,'') = PURCHASE_ANALYSIS_LINK.PACODE
LEFT OUTER JOIN SYS_CURRENCY_REC ON POP_HEADER.POH_CURR_CODE = SYS_CURRENCY_REC.CURREC_SYMBOL
LEFT OUTER JOIN AA_NET_PL_ANALYSIS_TRAN_VIEW CURRENCY_ANALYSIS_LINK ON COALESCE(SYS_CURRENCY_REC.CURREC_PURCH_AN,'') = CURRENCY_ANALYSIS_LINK.PACODE
LEFT OUTER JOIN SYS_VATCONTROL ON COALESCE(PL_ACCOUNTS.SU_TAX_CODE,'') = SYS_VATCONTROL.VAT_CODE
