CREATE VIEW AA_NET_STK_RECORD_LIST_VIEW
/*
** Returns a table to be used specifically with AA_NET_STK_RECORD_LIST_S
** Written:      13/03/03 ROBB
** Last Amended: 
**
*/
as

SELECT 

STKCODE as [PRIMARY],
STK_LEVEL as PROFILELEVEL,
STKCODE,
COALESCE(STKNAME,'') as STKNAME,
COALESCE(STK_SORT_KEY,'') as STK_SORT_KEY,
COALESCE(STK_SORT_KEY1,'') as STK_SORT_KEY1,
COALESCE(STK_SORT_KEY2,'') as STK_SORT_KEY2,
COALESCE(STK_SORT_KEY3,'') as STK_SORT_KEY3,
STK_ASSEMBLY,
STK_TEMPLATE,
STK_LINK_FLAG,
STK_ALTERNATIVE_FLAG,
STK_SERIALTRACK,
STK_MULTILOCATN,
STK_BIN_NUMBER,
dbo.AA_QUANTITY_DPS_F(COALESCE(STK_PHYSICAL,0)) as STK_PHYSICAL,
dbo.AA_PRICE_DPS_F(COALESCE(STK_BASEPRICE,0)) as STK_BASEPRICE,
dbo.AA_PRICE_DPS_F(COALESCE(STK_COSTPRICE,0)) as STK_COSTPRICE,      
dbo.AA_QUANTITY_DPS_F(COALESCE(STK_MIN_QTY,0)) as STK_MIN_QTY,
dbo.AA_QUANTITY_DPS_F(COALESCE(STK_MAX_QTY,0)) as STK_MAX_QTY

FROM STK_STOCK


