CREATE VIEW AA_NET_CST_RESOURCE_VIEW
/*
** Written:        09/12/02 ROBB
** Last Amended:  15/01/03 SRB; 22/01/03 SRB; 26/03/03 ROBB
*/
AS
select 
PRCODE,
PRNAME,
PR_TEXT,
PR_SORT_KEY,
PR_SORT_KEY1,
PR_SORT_KEY2,
PR_SORT_KEY3,
PR_SORT_KEY4,
PR_SORT_KEY5,
PR_SORT_KEY6,
PR_DATE_USER1,
PR_DATE_USER2,
PR_DATE_USER3,
PR_NOTES,
PR_EMPLOYEE_CODE,
PAYRES_PAYTYPE, 
dbo.AA_QUANTITY_DPS_F(PAYRES_PAYRATE) AS PAYRES_PAYRATE,

--Price Line Home Price
dbo.AA_PRICE_DPS_F(PR_COST_1) as PR_COST_1,
dbo.AA_PRICE_DPS_F(PR_COST_2) as PR_COST_2,
dbo.AA_PRICE_DPS_F(PR_COST_3) as PR_COST_3,
dbo.AA_PRICE_DPS_F(PR_COST_4) as PR_COST_4,
dbo.AA_PRICE_DPS_F(PR_COST_5) as PR_COST_5,
dbo.AA_PRICE_DPS_F(PR_COST_6) as PR_COST_6,
dbo.AA_PRICE_DPS_F(PR_COST_7) as PR_COST_7,
dbo.AA_PRICE_DPS_F(PR_COST_8) as PR_COST_8,
dbo.AA_PRICE_DPS_F(PR_COST_9) as PR_COST_9,
dbo.AA_PRICE_DPS_F(PR_COST_10) as PR_COST_10,

--Price Uplift Percentages
dbo.AA_TWO_DPS_F(PR_UPLIFT_P1) as PR_UPLIFT_P1,
dbo.AA_TWO_DPS_F(PR_UPLIFT_P2) as PR_UPLIFT_P2,
dbo.AA_TWO_DPS_F(PR_UPLIFT_P3) as PR_UPLIFT_P3,
dbo.AA_TWO_DPS_F(PR_UPLIFT_P4) as PR_UPLIFT_P4,
dbo.AA_TWO_DPS_F(PR_UPLIFT_P5) as PR_UPLIFT_P5,
dbo.AA_TWO_DPS_F(PR_UPLIFT_P6) as PR_UPLIFT_P6,
dbo.AA_TWO_DPS_F(PR_UPLIFT_P7) as PR_UPLIFT_P7,
dbo.AA_TWO_DPS_F(PR_UPLIFT_P8) as PR_UPLIFT_P8,
dbo.AA_TWO_DPS_F(PR_UPLIFT_P9) as PR_UPLIFT_P9,
dbo.AA_TWO_DPS_F(PR_UPLIFT_P10) as PR_UPLIFT_P10,

--Price Upllift Value
dbo.AA_PRICE_DPS_F(PR_UPLIFT_V1) as PR_UPLIFT_V1,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_V2) as PR_UPLIFT_V2,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_V3) as PR_UPLIFT_V3,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_V4) as PR_UPLIFT_V4,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_V5) as PR_UPLIFT_V5,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_V6) as PR_UPLIFT_V6,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_V7) as PR_UPLIFT_V7,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_V8) as PR_UPLIFT_V8,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_V9) as PR_UPLIFT_V9,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_V10) as PR_UPLIFT_V10,

--Price Currency Symbol
PR_CURR_1,
PR_CURR_2,
PR_CURR_3,
PR_CURR_4,
PR_CURR_5,
PR_CURR_6,
PR_CURR_7,
PR_CURR_8,
PR_CURR_9,
PR_CURR_10,

--Price Currency Symbol
CURR1.CURR_SYMBOL AS PR_CURR_SYMBOL1,
CURR2.CURR_SYMBOL AS PR_CURR_SYMBOL2,
CURR3.CURR_SYMBOL AS PR_CURR_SYMBOL3,
CURR4.CURR_SYMBOL AS PR_CURR_SYMBOL4,
CURR5.CURR_SYMBOL AS PR_CURR_SYMBOL5,
CURR6.CURR_SYMBOL AS PR_CURR_SYMBOL6,
CURR7.CURR_SYMBOL AS PR_CURR_SYMBOL7,
CURR8.CURR_SYMBOL AS PR_CURR_SYMBOL8,
CURR9.CURR_SYMBOL AS PR_CURR_SYMBOL9,
CURR10.CURR_SYMBOL AS PR_CURR_SYMBOL10,

--Price Line Cost
dbo.AA_PRICE_DPS_F(PR_COST_C_1) as PR_COST_C_1,
dbo.AA_PRICE_DPS_F(PR_COST_C_2) as PR_COST_C_2,
dbo.AA_PRICE_DPS_F(PR_COST_C_3) as PR_COST_C_3,
dbo.AA_PRICE_DPS_F(PR_COST_C_4) as PR_COST_C_4,
dbo.AA_PRICE_DPS_F(PR_COST_C_5) as PR_COST_C_5,
dbo.AA_PRICE_DPS_F(PR_COST_C_6) as PR_COST_C_6,
dbo.AA_PRICE_DPS_F(PR_COST_C_7) as PR_COST_C_7,
dbo.AA_PRICE_DPS_F(PR_COST_C_8) as PR_COST_C_8,
dbo.AA_PRICE_DPS_F(PR_COST_C_9) as PR_COST_C_9,
dbo.AA_PRICE_DPS_F(PR_COST_C_10) as PR_COST_C_10,

--Price Line Uplift 
dbo.AA_PRICE_DPS_F(PR_UPLIFT_C_V1) as PR_UPLIFT_C_V1,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_C_V2) as PR_UPLIFT_C_V2,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_C_V3) as PR_UPLIFT_C_V3,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_C_V4) as PR_UPLIFT_C_V4,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_C_V5) as PR_UPLIFT_C_V5,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_C_V6) as PR_UPLIFT_C_V6,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_C_V7) as PR_UPLIFT_C_V7,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_C_V8) as PR_UPLIFT_C_V8,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_C_V9) as PR_UPLIFT_C_V9,
dbo.AA_PRICE_DPS_F(PR_UPLIFT_C_V10) as PR_UPLIFT_C_V10,

PR_LEVEL,
PR_DATE_PUTIN,
PR_DATE_EDITED,
PR_USRCHAR1,
PR_USRCHAR2,
PR_USRCHAR3,
PR_USRCHAR4,
PR_USRCHAR5,
PR_USRCHAR6,
PR_USRDATE1,
PR_USRDATE2,
PR_USRDATE3,
PR_USRFLAG1,
PR_USRFLAG2,
PR_USRFLAG3,
PR_USRNUM1,
PR_USRNUM2,
PR_USRNUM3,
PR_PRIMARY,
PR_USED

from  PRC_PRICE_RECS
	left outer join PRC_PRICE_RECS2
	on PRC_PRICE_RECS.PRCODE = PRC_PRICE_RECS2.PRCODE2 
	left outer join SYS_CURRENCY CURR1
	ON CURR1.CURR_CODE = PR_CURR_1
	left outer join SYS_CURRENCY CURR2
	ON CURR2.CURR_CODE = PR_CURR_2
	left outer join SYS_CURRENCY CURR3
	ON CURR3.CURR_CODE = PR_CURR_3
	left outer join SYS_CURRENCY CURR4
	ON CURR4.CURR_CODE = PR_CURR_4
	left outer join SYS_CURRENCY CURR5
	ON CURR5.CURR_CODE = PR_CURR_5
	left outer join SYS_CURRENCY CURR6
	ON CURR6.CURR_CODE = PR_CURR_6
	left outer join SYS_CURRENCY CURR7
	ON CURR7.CURR_CODE = PR_CURR_7
	left outer join SYS_CURRENCY CURR8
	ON CURR8.CURR_CODE = PR_CURR_8
	left outer join SYS_CURRENCY CURR9
	ON CURR9.CURR_CODE = PR_CURR_9
	left outer join SYS_CURRENCY CURR10
	ON CURR10.CURR_CODE = PR_CURR_10
	left outer join PAY_RESOURC_LNK 
	on PRCODE = PAYRES_RESOURCE
where PR_TYPE = 'R' AND (PAYRES_DEFAULT=1 OR PAYRES_DEFAULT IS NULL)

