Create VIEW AA_NET_STK_DETAIL_TRAN_VIEW 

AS

SELECT 
 SM_PRIMARY
,TRANSACTION_TYPE = 'MV'
,SM_TYPE 
,SM_REFERENCE
,SM_DETAIL
,SM_DATE
,SM_YEAR
,SM_PERIODNUM
,SM_STOCK_CODE
,SM_SERIALNUMBER
,SM_LOCATION
,dbo.AA_QUANTITY_DPS_F(SM_QUANTITY) AS SM_QUANTITY
,SM_PRICECODE
,dbo.AA_PRICE_DPS_F(SM_COSTPRICE) AS SM_COSTPRICE
,dbo.AA_VALUE_DPS_F(SM_VALUE) AS SM_VALUE
,SM_COSTHEADER
,SM_COSTCENTRE
,SM_DESCRIPTION
,SM_LC_LINE
,SM_ARCHIVE
,SM_BATCH_FLAG
,UPDATECOSTPRICE = substring(SM_TRAN_OPTIONS,6,1)
,USECURRENCYPRICE = substring(SM_TRAN_OPTIONS,7,1)
,IGNOREQUANTITYCHECK = substring(SM_TRAN_OPTIONS,8,1)
,LANDEDCOSTLINE = substring(SM_TRAN_OPTIONS,9,1)
,SM_LOT_NUMBER
,SM_RENEW_DATE
,SM_SERIAL_SORT
,SM_SNO_DATE1
,SM_SNO_DATE2
,SM_SNO_DATE3
,SM_SNO_NOTES
,SM_ACCOUNT
,SM_ORDER_REF

FROM
STK_MOVEMENTS

WHERE
SM_BATCH_FLAG=1


