CREATE VIEW AA_NET_STK_SUBANALYSIS_LIST_VIEW
/*
** Returns a table to be used specifically with AA_NET_STK_SUBANALYSIS_LIST_S
** Written:      21/02/03 SRB
** Last Amended: 24/02/03 SRB 25/02/03 SRB, 11/03/03 ROBB
**
*/
as


SELECT 

LOC_CONCATCODE AS [PRIMARY]
,LOC_CONCATCODE
,STK_LEVEL AS PROFILELEVEL
,LOC_DATE_PUTIN
,LOC_DATE_EDITED
,LOC_STOCK_CODE
,STKNAME
,LOC_CODE
,COALESCE(LOC_NAME ,'') as LOC_NAME
,COALESCE(LOC_USERSORT1,'') as LOC_USERSORT1
,COALESCE(LOC_USERSORT2,'') as LOC_USERSORT2
,COALESCE(LOC_USERSORT3,'') as LOC_USERSORT3
,COALESCE(LOC_USERSORT4,'') as LOC_USERSORT4
,COALESCE(LOC_USERSORT5,'') as LOC_USERSORT5
,COALESCE(LOC_USERSORT6,'') as LOC_USERSORT6
,LOC_USERDATE1
,LOC_USERDATE2
,LOC_USERDATE3
,LOC_BIN_NUMBER
,dbo.AA_QUANTITY_DPS_F(COALESCE(LOC_PHYSICAL,0)) as LOC_PHYSICAL
,dbo.AA_QUANTITY_DPS_F(COALESCE(LOC_MIN_QTY,0)) as LOC_MIN_QTY
,dbo.AA_QUANTITY_DPS_F(COALESCE(LOC_MAX_QTY,0)) as LOC_MAX_QTY
,LOC_LANDED_COMPLETE
,LOC_SOPCHECK
,LOC_POPCHECK
,STKCODE as PARENT
,LOC_CODE as CHILD

FROM STK_LOCATION  INNER JOIN STK_STOCK
ON LOC_STOCK_CODE = STKCODE
INNER JOIN STK_LOCATION2
ON LOC_CONCATCODE = LOC_CONCATCODE2

