CREATE VIEW AA_NOMINAL_TRAN_VIEW
/*
** Written:
** Last Amended: 22/10/02, 01/12/03 SR, 24/05/05 SR 31/5/05chw, 6/9/2007 RL, 20/10/2010 CC   
**
*/
(
DET_PRIMARY,UNIQUE_KEY,DET_BATCH_REF,DET_SUB_LEDGER,DET_DATE,DET_NOM_PERSORT,DET_HEADER_REF,DET_CURR_CODE,DET_HEADER_KEY,DET_BATCH_FLAG,
DET_RECUR_FLAG,DET_CURR_RATE,DET_JNL_LINEREF,DET_ORIGIN,DET_TYPE,DET_NOM_PERIOD,DET_NOM_YEAR,DET_USER_PUTIN,
DET_DATE_PUTIN,DET_VAT_RULES,DET_NOMINALDR,DET_NOMINALCR,DET_NOMINALVAT,DET_ACCOUNT,DET_ANALYSIS,DET_COSTCENTRE,
DET_COSTHEADER,DET_GROSS,DET_VAT,DET_NETT,DET_CURR_TAX,DET_CURR_NETT,DET_ANALTYPE,DET_CHEQUE_PAYEE,
DET_TRI_RATE1,DET_TRI_RATE2,DET_DESCRIPTION,DET_NETT_BASE2,DET_VAT_BASE2,DET_GROSS_BASE2,DET_RECON_REF,DET_PL_INTERNAL,
DET_TRI_RATECHNG1,DET_TRI_RATECHNG2,DET_CURR_RTEFLG,DET_HEADER_REF2,DET_ORDER_LINK,DET_RECONCILED,DET_STOCK_CODE,DET_PRICE_CODE,
HOME_DEBIT,CURRENCY_DEBIT,BASE2_DEBIT,HOME_CREDIT,CURRENCY_CREDIT,BASE2_CREDIT,NOMINAL_TYPE,
NCODE,NNAME,NCURRENCYCODE,NTYPE,NCATEGORYCODE5,NCATEGORYCODE6,NCATEGORYCODE7,NCATEGORYCODE8,NCATEGORYCODE4,NCATEGORYCODE1,
NCATEGORYCODE2,NCATEGORYCODE3,NMAJORHEADCODE,N_EXCLUDE_TRNREP,DET_QUANTITY,DET_DIMENSION1,DET_DIMENSION2,DET_DIMENSION3,DET_ARCHIVE_FLG,
N_DO_NOT_USE,DET_VATCODE
)
as select 
TRANS_PRIMARY,convert(char(25),NCODE)+convert(char(5),convert(int,isnull(DET_DATE,0)))+convert(char(3),DET_NOM_PERSORT)+convert(char(10),DET_HEADER_KEY),DET_BATCH_REF,DET_SUB_LEDGER,DET_DATE,DET_NOM_PERSORT,DET_HEADER_REF,DET_CURR_CODE,DET_HEADER_KEY,DET_BATCH_FLAG,
DET_RECUR_FLAG,DET_CURR_RATE,DET_JNL_LINEREF,DET_ORIGIN,DET_TYPE,DET_NOM_PERIOD,DET_NOM_YEAR,DET_USER_PUTIN,
DET_DATE_PUTIN,DET_VAT_RULES,DET_NOMINALDR,DET_NOMINALCR,DET_NOMINALVAT,DET_ACCOUNT,DET_ANALYSIS,DET_COSTCENTRE,
DET_COSTHEADER,DET_GROSS,DET_VAT,DET_NETT,DET_CURR_TAX,DET_CURR_NETT,DET_ANALTYPE,DET_CHEQUE_PAYEE,
DET_TRI_RATE1,DET_TRI_RATE2,DET_DESCRIPTION,DET_NETT_BASE2,DET_VAT_BASE2,DET_GROSS_BASE2,DET_RECON_REF,DET_PL_INTERNAL,
DET_TRI_RATECHNG1,DET_TRI_RATECHNG2,DET_CURR_RTEFLG,DET_HEADER_REF2,DET_ORDER_LINK,DET_RECONCILED,DET_STOCK_CODE,DET_PRICE_CODE,
HOME_DEBIT_VALUE,CURRENCY_DEBIT_VALUE,BASE2_DEBIT_VALUE,HOME_CREDIT_VALUE,CURRENCY_CREDIT_VALUE,
BASE2_CREDIT_VALUE,NOMINAL_TYPE,NCODE,NNAME,NCURRENCYCODE,NTYPE,NCATEGORYCODE5,NCATEGORYCODE6,NCATEGORYCODE7,NCATEGORYCODE8,
NCATEGORYCODE4,NCATEGORYCODE1,NCATEGORYCODE2,NCATEGORYCODE3,NMAJORHEADCODE,N_EXCLUDE_TRNREP,DET_QUANTITY,DET_DIMENSION1,DET_DIMENSION2,
DET_DIMENSION3,DET_ARCHIVE_FLG,isnull(N_DO_NOT_USE,0),DET_VATCODE
from NL_ACCOUNTS, NOM_DET_DEBIT_LEVEL1
where NOM_DET_DEBIT_LEVEL1.NOMINAL_CODE = NL_ACCOUNTS.NCODE
union select
TRANS_PRIMARY,convert(char(25),NCODE)+convert(char(5),convert(int,isnull(DET_DATE,0)))+convert(char(3),DET_NOM_PERSORT)+convert(char(10),DET_HEADER_KEY),DET_BATCH_REF,DET_SUB_LEDGER,DET_DATE,DET_NOM_PERSORT,DET_HEADER_REF,DET_CURR_CODE,DET_HEADER_KEY,DET_BATCH_FLAG,
DET_RECUR_FLAG,DET_CURR_RATE,DET_JNL_LINEREF,DET_ORIGIN,DET_TYPE,DET_NOM_PERIOD,DET_NOM_YEAR,DET_USER_PUTIN,
DET_DATE_PUTIN,DET_VAT_RULES,DET_NOMINALDR,DET_NOMINALCR,DET_NOMINALVAT,DET_ACCOUNT,DET_ANALYSIS,DET_COSTCENTRE,
DET_COSTHEADER,DET_GROSS,DET_VAT,DET_NETT,DET_CURR_TAX,DET_CURR_NETT,DET_ANALTYPE,DET_CHEQUE_PAYEE,
DET_TRI_RATE1,DET_TRI_RATE2,DET_DESCRIPTION,DET_NETT_BASE2,DET_VAT_BASE2,DET_GROSS_BASE2,DET_RECON_REF,DET_PL_INTERNAL,
DET_TRI_RATECHNG1,DET_TRI_RATECHNG2,DET_CURR_RTEFLG,DET_HEADER_REF2,DET_ORDER_LINK,DET_RECONCILED,DET_STOCK_CODE,DET_PRICE_CODE,
HOME_DEBIT_VALUE,CURRENCY_DEBIT_VALUE,BASE2_DEBIT_VALUE,HOME_CREDIT_VALUE,CURRENCY_CREDIT_VALUE,
BASE2_CREDIT_VALUE,NOMINAL_TYPE,NCODE,NNAME,NCURRENCYCODE,NTYPE,NCATEGORYCODE5,NCATEGORYCODE6,NCATEGORYCODE7,NCATEGORYCODE8,
NCATEGORYCODE4,NCATEGORYCODE1,NCATEGORYCODE2,NCATEGORYCODE3,NMAJORHEADCODE,N_EXCLUDE_TRNREP,DET_QUANTITY,DET_DIMENSION1,DET_DIMENSION2,
DET_DIMENSION3,DET_ARCHIVE_FLG,isnull(N_DO_NOT_USE,0),DET_VATCODE
from NL_ACCOUNTS,NOM_DET_CREDIT_LEVEL1
where NOM_DET_CREDIT_LEVEL1.NOMINAL_CODE = NL_ACCOUNTS.NCODE
union select
TRANS_PRIMARY,convert(char(25),NCODE)+convert(char(5),convert(int,isnull(DET_DATE,0)))+convert(char(3),DET_NOM_PERSORT)+convert(char(10),DET_HEADER_KEY),DET_BATCH_REF,DET_SUB_LEDGER,DET_DATE,DET_NOM_PERSORT,DET_HEADER_REF,DET_CURR_CODE,DET_HEADER_KEY,DET_BATCH_FLAG,
DET_RECUR_FLAG,DET_CURR_RATE,DET_JNL_LINEREF,DET_ORIGIN,DET_TYPE,DET_NOM_PERIOD,DET_NOM_YEAR,DET_USER_PUTIN,
DET_DATE_PUTIN,DET_VAT_RULES,DET_NOMINALDR,DET_NOMINALCR,DET_NOMINALVAT,DET_ACCOUNT,DET_ANALYSIS,DET_COSTCENTRE,
DET_COSTHEADER,DET_GROSS,DET_VAT,DET_NETT,DET_CURR_TAX,DET_CURR_NETT,DET_ANALTYPE,DET_CHEQUE_PAYEE,
DET_TRI_RATE1,DET_TRI_RATE2,DET_DESCRIPTION,DET_NETT_BASE2,DET_VAT_BASE2,DET_GROSS_BASE2,DET_RECON_REF,DET_PL_INTERNAL,
DET_TRI_RATECHNG1,DET_TRI_RATECHNG2,DET_CURR_RTEFLG,DET_HEADER_REF2,DET_ORDER_LINK,DET_RECONCILED,DET_STOCK_CODE,DET_PRICE_CODE,
HOME_DEBIT_VALUE,CURRENCY_DEBIT_VALUE,BASE2_DEBIT_VALUE,HOME_CREDIT_VALUE,CURRENCY_CREDIT_VALUE,
BASE2_CREDIT_VALUE,NOMINAL_TYPE,NCODE,NNAME,NCURRENCYCODE,NTYPE,NCATEGORYCODE5,NCATEGORYCODE6,NCATEGORYCODE7,NCATEGORYCODE8,
NCATEGORYCODE4,NCATEGORYCODE1,NCATEGORYCODE2,NCATEGORYCODE3,NMAJORHEADCODE,N_EXCLUDE_TRNREP,DET_QUANTITY,DET_DIMENSION1,DET_DIMENSION2,
DET_DIMENSION3,DET_ARCHIVE_FLG,isnull(N_DO_NOT_USE,0),DET_VATCODE
from NL_ACCOUNTS,NOM_DET_VAT_LEVEL1 
where NOM_DET_VAT_LEVEL1.NOMINAL_CODE = NL_ACCOUNTS.NCODE
