CREATE VIEW AA_NET_SL_ANALYSIS_TRAN_VIEW
/*
** Written:   11/04/01 SC     
** Last Amended: 09/12/02 SRB
*/
AS
SELECT
SL_ANALYSIS.SACODE,
SL_ANALYSIS.SANAME,
SL_ANALYSIS.SACURRENCYSYMBL,
SL_ANALYSIS.SA_FORCE_COSTING,
SYS_CURRENCY_REC.CURREC_SALES_AN,
SYS_VATCONTROL.VAT_CODE,
SYS_VATCONTROL.VAT_RATE,
SYS_VATCONTROL.EC_TYPE
FROM SL_ANALYSIS
LEFT OUTER JOIN SYS_CURRENCY_REC ON SL_ANALYSIS.SACURRENCYSYMBL = SYS_CURRENCY_REC.CURREC_SYMBOL
LEFT OUTER JOIN SYS_VATCONTROL ON SL_ANALYSIS.SAVATCODE = SYS_VATCONTROL.VAT_CODE

