CREATE VIEW AA_NET_SOP_DETAIL_TRAN_VIEW
/*
** Create the necessary information for a Dimensions.NET Sales Order Detail Line
** Written:      
** Last Amended: 03/07/03 SRB; 04/07/03 ROBB
**
*/
AS
SELECT
OD_ENTRY_TYPE,
OD_STATUS,
OD_STOCK_CODE,
OD_PRICE_CODE,
(case when OD_ENTRY_TYPE in ('S','P')
then
	case when OD_ENTRY_TYPE ='S'
		then
			STKNAME
		else
			PRNAME
		end
else
	''
end) AS ITEMDESCRIPTION,
(case when OD_GROSS_MEMO <> 0
then
	1
else
	0
end) as GROSSENTRYMODE,
(case when coalesce(charindex(upper('Delivery Charge'),upper(OD_DETAIL)),0) > 0
then
	1
else
	0
end) as DELIVERYLINE,
dbo.AA_PRICE_DPS_F(OD_COSTPRICE) as OD_COSTPRICE,
OD_SERIALNO,
OD_LOCATN,
dbo.AA_QUANTITY_DPS_F(OD_QTYORD) as OD_QTYORD,
dbo.AA_QUANTITY_DPS_F(OD_QTYUNIT) as OD_QTYUNIT,
dbo.AA_PRICE_DPS_F((case when OD_GROSS_MEMO <> 0
then
	OD_GROSS_MEMO
else
	OD_UNITCST
end)) as UNITCOST,
dbo.AA_VALUE_DPS_F((case when OD_GROSS_MEMO <> 0
then
	OD_UNITCST
else
	0
end)) as NETUNITCOST,
dbo.AA_PRICE_DPS_F(OD_UNITCST_C) as OD_UNITCST_C,
dbo.AA_VALUE_DPS_F(OD_NETT) as OD_NETT,
dbo.AA_VALUE_DPS_F(OD_NETT_C) as OD_NETT_C,
dbo.AA_VALUE_DPS_F(OD_VATAMNT) as OD_VATAMNT,
dbo.AA_VALUE_DPS_F(OD_TAX_C) as OD_TAX_C,
dbo.AA_VALUE_DPS_F(OD_GROSS) as OD_GROSS,
dbo.AA_VALUE_DPS_F(OD_GROSS_C) as OD_GROSS_C,
dbo.AA_PRICE_DPS_F(CAST(OD_QTYORD * (case when OD_GROSS_MEMO <> 0
then
	OD_GROSS_MEMO
else
	OD_UNITCST
end) as float)) as PRICE,
dbo.AA_PRICE_DPS_F(CAST(OD_QTYORD * OD_UNITCST_C as float)) as CURRENCY_PRICE,
OD_ANALYSIS,
OD_DETAIL,
OD_VATCODE,
VAT_RATE,
dbo.AA_TWO_DPS_F(OD_LINEDISC) as OD_LINEDISC,
dbo.AA_VALUE_DPS_F(OD_L_DISCVAL) as OD_L_DISCVAL,
dbo.AA_VALUE_DPS_F(OD_T_DISCVAL) as OD_T_DISCVAL,
dbo.AA_VALUE_DPS_F(OD_L_DISCVAL_C) as OD_L_DISCVAL_C,
OD_COSTHEADER,
CH_NAME,
OD_COSTCENTRE,
CC_NAME,
OD_REQDATE,
(case when OD_TABLECODE is null then 1 else CAST(SUBSTRING(OD_TABLECODE,2,2) as varchar) end) as OD_TABLECODE,
OD_RTP_FLAG,
(case when OD_ENTRY_TYPE in ('S','P')
then
	case when OD_ENTRY_TYPE ='S'
		then
			STK_RTP_FLAG
		else
			PR_RTP_FLAG
		end
else
	0
end) AS RTPITEM,
OD_WORK_STATUS,
OD_WORK_NOTE,
OD_DIMENSION1,
OD_DIMENSION2,
OD_DIMENSION3,
STK_PHYSICAL,
SANAME,
SA_FORCE_COSTING,
OD_SERIALTRACK,
(case when OD_ENTRY_TYPE = 'S'
then
	STK_MULTILOCATN
else
	0
end) AS SUBANALYSISITEM,
OD_USRCHAR1, 
OD_USRCHAR2, 
OD_USRCHAR3, 
OD_USRCHAR4, 
OD_USRFLAG1, 
OD_USRFLAG2, 
OD_USRDATE1, 
OD_USRDATE2, 
OD_USRNUM1, 
OD_USRNUM2,
OD_ORDER_NUMBER,
OD_PRIMARY


FROM
ORD_DETAIL
JOIN SYS_VATCONTROL ON ORD_DETAIL.OD_VATCODE = SYS_VATCONTROL.VAT_CODE
JOIN SL_ANALYSIS ON ORD_DETAIL.OD_ANALYSIS = SL_ANALYSIS.SACODE
LEFT OUTER JOIN ORD_DETAIL2 ON ORD_DETAIL.OD_PRIMARY = ORD_DETAIL2.OD_PRIMARY_2
LEFT OUTER JOIN PRC_PRICE_RECS ON COALESCE(ORD_DETAIL.OD_PRICE_CODE,'') = PRC_PRICE_RECS.PRCODE
LEFT OUTER JOIN STK_STOCK ON COALESCE(ORD_DETAIL.OD_STOCK_CODE,'') = STK_STOCK.STKCODE
LEFT OUTER JOIN CST_COSTCENTRE ON COALESCE(CONVERT(char(10),ORD_DETAIL.OD_COSTHEADER) + convert(varchar,ORD_DETAIL.OD_COSTCENTRE),'') = CST_COSTCENTRE.CC_CONCAT_CODES
LEFT OUTER JOIN CST_COSTHEADER ON COALESCE(ORD_DETAIL.OD_COSTHEADER,'') = CST_COSTHEADER.CH_CODE
