CREATE VIEW AA_NET_SOP_HEADER_TRAN_VIEW
/*
** Written:        
** Last Amended: 09/12/02 SRB; 20/03/03 ROBB; 30/04/03; 07/07/03 SRB;  09/07/03 SRB, 04/06/04 NC
*/
AS

SELECT
OH_ACCOUNT,
CUNAME,
CU_ON_STOP,
CU_MULTI_CURR,
CU_CREDIT_LIMIT,
CUBALANCE,
CUTURNOVERYTD,
CU_TAX_CODE,
SYS_VATCONTROL.VAT_RATE,
SYS_VATCONTROL.EC_TYPE,
CU_EXPORT_CODE,
CU_BANK_ANALYS,
BANK_ANALYSIS_LINK.SACURRENCYSYMBL AS CUSTOMERBANKANALYSISCURRSYMBOL,
CU_ANALYSIS,
SALES_ANALYSIS_LINK.SACURRENCYSYMBL AS CUSTOMERANALYSISCURRSYMBOL,
SALES_ANALYSIS_LINK.SANAME AS CUSTOMERANALYSISDESCRIPTION,
SALES_ANALYSIS_LINK.SA_FORCE_COSTING AS CUSTOMERANALYSISCOMPCOSTING,
SALES_ANALYSIS_LINK.VAT_CODE AS CUSTOMERANALYSISVATCODE,
SALES_ANALYSIS_LINK.VAT_RATE AS CUSTOMERANALYSISVATRATE,
SALES_ANALYSIS_LINK.EC_TYPE AS CUSTOMERANALYSISVATECTYPE,
OH_ORDER_REF,
OH_BATCH_REF,
OH_DESCRIPTION,
OH_YEAR,
OH_PERIOD,
OH_DATE,
OH_REQUIREDDATE,
OH_WORK_STATUS,
OH_DISC_LINE_P,
OH_DISC_TOTAL_P, 
OH_SETT_DISC_1, 
OH_SETT_DISC_2, 
OH_SETT_DAYS_1, 
OH_SETT_DAYS_2, 
OH_CURR_TYPE,
(case when OH_CURR_TYPE ='E'
		then
			OH_TRI_RATE1
		else
			OH_CURRENCYRATE
		end) 
as OH_CURRENCYRATE ,
OH_CURRENCYCODE, 
SYS_CURRENCY_REC.CURREC_SALES_AN AS CURRENCYANALYSIS,
CURRENCY_ANALYSIS_LINK.SANAME AS CURRENCYANALYSISDESCRIPTION,
CURRENCY_ANALYSIS_LINK.SA_FORCE_COSTING AS CURRENCYANALYSISCOMPCOSTING,
CURRENCY_ANALYSIS_LINK.VAT_CODE AS CURRENCYANALYSISVATCODE,
CURRENCY_ANALYSIS_LINK.VAT_RATE AS CURRENCYANALYSISVATRATE,
CURRENCY_ANALYSIS_LINK.EC_TYPE AS CURRENCYANALYSISVATECTYPE,
OH_TRI_RATE2 AS EUROTOHOMERATE,
OH_EXPORT_CODE, 
OH_EC_DEL_TERMS, 
OH_EC_T_NATURE, 
OH_EC_T_MODE,
CU_VAT_REG_NO,
NORMAL_DAYS,
URGENT_DAYS,
OH_DEL_CHARGE,
OH_DEL_CHG_PCNT,
OH_DEL_METHOD,
OH_MIN_VAL,
CU_DUEDATE_TYPE,
OH_DUE_DAYS,
OH_A_P_DAYS,
OH_TERMS,
OH_PRICE_KEY,
OH_INV_ADD AS INVOICEADDRESSNUMBER,
INVOICE_ADDRESS_LINK.AD_ADDRESS AS INVOICEADDRESS,
INVOICE_ADDRESS_LINK.AD_ADDRESS_USER1 AS INVOICETOWN,
INVOICE_ADDRESS_LINK.AD_ADDRESS_USER2 AS INVOICECOUNTY,
INVOICE_ADDRESS_LINK.AD_COUNTRY AS INVOICECOUNTRY,
INVOICE_ADDRESS_LINK.AD_POSTCODE AS INVOICEPOSTCODE,
INVOICE_ADDRESS_LINK.AD_E_MAIL AS INVOICEEMAIL,
INVOICE_ADDRESS_LINK.AD_PHONE AS INVOICEPHONE,
INVOICE_ADDRESS_LINK.AD_FAX AS INVOICEFAX,
INVOICE_ADDRESS_LINK.AD_CONTACT AS INVOICECONTACT,
INVOICE_ADDRESS_LINK.AD_ACCOUNTNAME AS INVOICEEXCLUDENAME,
INVOICE_ADDRESS_ANALYSIS_LINK.SACODE AS INVOICEANALYSIS,
INVOICE_ADDRESS_ANALYSIS_LINK.SACURRENCYSYMBL AS INVOICEANALYSISCURRENCY,
INVOICE_ADDRESS_ANALYSIS_LINK.SANAME AS INVOICEANALYSISDESCRIPTION,
INVOICE_ADDRESS_ANALYSIS_LINK.SA_FORCE_COSTING AS INVOICEANALYSISCOMPCOSTING,
INVOICE_ADDRESS_ANALYSIS_LINK.VAT_CODE AS INVOICEANALYSISVATCODE,
INVOICE_ADDRESS_ANALYSIS_LINK.VAT_RATE AS INVOICEANALYSISVATRATE,
INVOICE_ADDRESS_ANALYSIS_LINK.EC_TYPE AS INVOICEANALYSISVATECTYPE,
OH_DEL_ADD AS DELIVERYADDRESSNUMBER,
DELIVERY_ADDRESS_LINK.AD_ADDRESS AS DELIVERYADDRESS,
DELIVERY_ADDRESS_LINK.AD_ADDRESS_USER1 AS DELIVERYTOWN,
DELIVERY_ADDRESS_LINK.AD_ADDRESS_USER2 AS DELIVERYCOUNTY,
DELIVERY_ADDRESS_LINK.AD_COUNTRY AS DELIVERYCOUNTRY,
DELIVERY_ADDRESS_LINK.AD_POSTCODE AS DELIVERYPOSTCODE,
DELIVERY_ADDRESS_LINK.AD_E_MAIL AS DELIVERYEMAIL,
DELIVERY_ADDRESS_LINK.AD_PHONE AS DELIVERYPHONE,
DELIVERY_ADDRESS_LINK.AD_FAX AS DELIVERYFAX,
DELIVERY_ADDRESS_LINK.AD_CONTACT AS DELIVERYCONTACT,
DELIVERY_ADDRESS_LINK.AD_ACCOUNTNAME AS DELIVERYEXCLUDENAME,

DELIVERY_ADDRESS_ANALYSIS_LINK.SACODE AS DELIVERYANALYSIS,
DELIVERY_ADDRESS_ANALYSIS_LINK.SACURRENCYSYMBL AS DELIVERYANALYSISCURRENCY,
DELIVERY_ADDRESS_ANALYSIS_LINK.SANAME AS DELIVERYANALYSISDESCRIPTION,
DELIVERY_ADDRESS_ANALYSIS_LINK.SA_FORCE_COSTING AS DELIVERYANALYSISCOMPCOSTING,
DELIVERY_ADDRESS_ANALYSIS_LINK.VAT_CODE AS DELIVERYANALYSISVATCODE,
DELIVERY_ADDRESS_ANALYSIS_LINK.VAT_RATE AS DELIVERYANALYSISVATRATE,
DELIVERY_ADDRESS_ANALYSIS_LINK.EC_TYPE AS DELIVERYANALYSISVATECTYPE,
OH_AUTHORISE,
OH_CREDIT_CARD,
OH_CARD_EXPIRY,
OH_BANK_ANLYSIS,
(case when OH_NORMAL_ORD ='0' and SYS_DATAINFO2.MAIL_ORDER_ON='1'
		then
			1  --Mail Ordering has been used
		else
			0  --Mail Ordering has been ignored or not posted when Mail Order was not switched 
		end) 
as MAILORDER,
OH_NO_PARTDEL,
OH_ARCHIVE,
OH_PRIORITY,
(case when OH_PRIORITY=0
		then
			(case when OH_TYPE='C'
				then 
					'CRN'
				else		
					'ORD'
				end)
		else
			(case when OH_PRIORITY=3
				then
					'PRF'
				else
					(case when OH_PRIORITY=4
						then
							'EST'
						else
							'PRC'
					end)
			end)
		end) 
as OH_ORDER_TYPE,
OH_INTERNL_NOTE,
OH_CUSORT,
OH_USER1,
OH_USER2,
OH_USER3,
OH_PROBABILITY,
OH_PROFORM_DATE,
OH_SUB_LEDGER,
OH_URGENT_FLAG,
CU_NOTES,
OH_USRCHAR1, 
OH_USRCHAR2, 
OH_USRCHAR3, 
OH_USRCHAR4, 
OH_USRFLAG1, 
OH_USRFLAG2, 
OH_USRDATE1, 
OH_USRDATE2, 
OH_USRNUM1, 
OH_USRNUM2,
OH_ORDER_NUMBER,
OH_BATCH_FLAG,
OH_MU_STATUS,
OH_MU_LOCK,
OH_TRAN_OPTIONS,


(case when substring(OH_TRAN_OPTIONS,9,1) is null then 0 else substring(OH_TRAN_OPTIONS,9,1) end) as GROSSENTRY,
--Due to Sales Orders and Credit Notes having different Transaction Options it is 
--necessary to do seperate substrings 
--Currency
case when OH_TYPE='C' --Credit Note
	then 
		(case when substring(OH_TRAN_OPTIONS,16,1) is null then 0 else substring(OH_TRAN_OPTIONS,16,1) end)
	else		
		(case when substring(OH_TRAN_OPTIONS,21,1) is null then 0 else substring(OH_TRAN_OPTIONS,21,1) end)
	end
as CURRENCYENTRY,

--Reserve Stock does not exist for Credit Notes
case when OH_TYPE='C' --Credit Note
	then 
		0
	else		
		(case when substring(OH_TRAN_OPTIONS,2,1) is null then 0 else substring(OH_TRAN_OPTIONS,2,1) end) 
	end
as RESERVESTOCK,

--Update Stock does not exist for Credit Notes
case when OH_TYPE='C' --Credit Note
	then 
		(case when substring(OH_TRAN_OPTIONS,2,1) is null then 0 else substring(OH_TRAN_OPTIONS,2,1) end) 
	else		
		0
	end
as DONOTUPDATESTOCK,
--Allow Empty Sub Analysis
case when OH_TYPE='C' --Credit Note
	then 
		(case when substring(OH_TRAN_OPTIONS,13,1) is null then 0 else substring(OH_TRAN_OPTIONS,13,1) end) 
	else		
		(case when substring(OH_TRAN_OPTIONS,17,1) is null then 0 else substring(OH_TRAN_OPTIONS,17,1) end) 
	end
as ALLOWEMPTYSUBANALYSIS,

--Allow Empty Serial Number
case when OH_TYPE='C' --Credit Note
	then 
		(case when substring(OH_TRAN_OPTIONS,15,1) is null then 0 else substring(OH_TRAN_OPTIONS,15,1) end) 
	else		
		(case when substring(OH_TRAN_OPTIONS,20,1) is null then 0 else substring(OH_TRAN_OPTIONS,20,1) end) 
	end
as ALLOWEMPTYSERIALNUMBER,
OH_ACCOUNT_ORDER,
OH_ACCOUNT_DELIVERY
FROM
ORD_HEADER
JOIN SYS_DATAINFO ON SYS_PRIMARY=1
JOIN SYS_DATAINFO2 ON SYS_PRIMARY_2=1
JOIN SL_ACCOUNTS ON ORD_HEADER.OH_ACCOUNT = SL_ACCOUNTS.CUCODE
JOIN SL_ADDRESSES INVOICE_ADDRESS_LINK ON INVOICE_ADDRESS_LINK.AD_CON_CODE = CONVERT(char(10),OH_ACCOUNT) + convert(varchar,OH_INV_ADD)
JOIN SL_ADDRESSES DELIVERY_ADDRESS_LINK ON DELIVERY_ADDRESS_LINK.AD_CON_CODE = CONVERT(char(10),OH_ACCOUNT_DELIVERY) + convert(varchar,OH_DEL_ADD)
LEFT OUTER JOIN ORD_HEADER2 ON ORD_HEADER.OH_PRIMARY = ORD_HEADER2.OH_PRIMARY_2
LEFT OUTER JOIN AA_NET_SL_ANALYSIS_TRAN_VIEW INVOICE_ADDRESS_ANALYSIS_LINK ON COALESCE(INVOICE_ADDRESS_LINK.AD_ANALYSIS,'') = INVOICE_ADDRESS_ANALYSIS_LINK.SACODE
LEFT OUTER JOIN AA_NET_SL_ANALYSIS_TRAN_VIEW DELIVERY_ADDRESS_ANALYSIS_LINK ON COALESCE(DELIVERY_ADDRESS_LINK.AD_ANALYSIS,'') = DELIVERY_ADDRESS_ANALYSIS_LINK.SACODE
LEFT OUTER JOIN AA_NET_SL_ANALYSIS_TRAN_VIEW BANK_ANALYSIS_LINK ON COALESCE(SL_ACCOUNTS.CU_BANK_ANALYS,'') = BANK_ANALYSIS_LINK.SACODE
LEFT OUTER JOIN AA_NET_SL_ANALYSIS_TRAN_VIEW SALES_ANALYSIS_LINK ON COALESCE(SL_ACCOUNTS.CU_ANALYSIS,'') = SALES_ANALYSIS_LINK.SACODE
LEFT OUTER JOIN SYS_CURRENCY_REC ON ORD_HEADER.OH_CURRENCYCODE = SYS_CURRENCY_REC.CURREC_SYMBOL
LEFT OUTER JOIN AA_NET_SL_ANALYSIS_TRAN_VIEW CURRENCY_ANALYSIS_LINK ON COALESCE(SYS_CURRENCY_REC.CURREC_SALES_AN,'') = CURRENCY_ANALYSIS_LINK.SACODE
LEFT OUTER JOIN SYS_VATCONTROL ON COALESCE(SL_ACCOUNTS.CU_TAX_CODE,'') = SYS_VATCONTROL.VAT_CODE
