CREATE VIEW AA_NET_SYS_COMPANYADDRESSES_LIST_VIEW
/*
** Returns a table to be used specifically with AA_NET_SYS_COMPANYADDRESSES_LIST_VIEW
** Written:      01/05/03 SRB
** Last Amended: 22/07/03 SRB
**
*/
AS

SELECT 

COAD_PRIMARY AS [PRIMARY]
,TYPE = 'COMPANY'
,COAD_PRIMARY
,COAD_USER_PUTIN
,COAD_DATE_PUTIN
,COAD_USER_EDITED
,COAD_DATE_EDITED
,COAD_CODE as CHILD
,COALESCE(COAD_CONTACT,'') AS CONTACT
,COALESCE(COAD_ADDRESS,'') AS ADDRESS
,COALESCE(COAD_ADDRESS_USER1,'') AS TOWN
,COALESCE(COAD_POSTCODE,'') AS POSTCODE
,COAD_COUNTRY
,COAD_DEFAULT AS DEFAULTADDRESS
,COAD_PHONE as PHONE

FROM 
SYS_COMP_ADDRESS

