CREATE VIEW AA_NET_CST_RECORD_VIEW
/*
** Written:        09/12/02 ROBB
** Last Amended:   08/01/03 ROBB; 14/01/03 SRB; 21/02/03 SRB; 22/09/03 SRB
*/
AS

SELECT 

CH_CODE,
CH_NAME,
CH_DESCRIPTION,
CH_STATUS,
CH_ACCOUNT,
SL_ACCOUNTS.CUNAME,
SL_ACCOUNTS.CUCONTACT,
CH_DURATION,
CH_DUR_TYPE,
CH_SORT,
CH_USER1,
CH_USER2,
CH_USER3,
CH_USER4,
CH_USER5,
CH_USER6,
CH_NOTES,
CH_DATE_REQ,
CH_DATE_USER1,
CH_DATE_USER2,
CH_DATE_USER3,
CH_DATE_INV,
CH_DATE_PAY,
CH_DATE_COMP,
CH_DATE_STAT,
CH_DATE_PUTIN,
CH_DATE_EDITED,
CH_USRCHAR1,
CH_USRCHAR2,
CH_USRCHAR5,
CH_USRCHAR6,
CH_USRCHAR7,
CH_USRCHAR8,
CH_USRDATE1,
CH_USRDATE2,
CH_USRDATE3,
CH_USRFLAG1,
CH_USRFLAG2,
CH_USRFLAG3,
CH_USRNUM1,
CH_USRNUM2,
CH_USRNUM3,
CH_LEVEL,
CH_CHRG_RATE,
CH_CHRG_LINE,
CH_CHRG_VALUE,
CH_PRIMARY,
CH_USED

from CST_COSTHEADER 
	left outer join CST_COSTHEADER2
	on CST_COSTHEADER.CH_CODE = CST_COSTHEADER2.CH_CODE2
	left outer join SL_ACCOUNTS
	on CST_COSTHEADER.CH_ACCOUNT = SL_ACCOUNTS.CUCODE  AND (CH_ACCOUNT IS NOT NULL AND CH_ACCOUNT <>'')

