CREATE VIEW AA_NL_BALANCE_SHEET_HEADER_VIEW
AS 
/*
** 
** Intended to be called by AA_NL_BALANCE_SHEET_HEADER_S
** The following fields are intended to be displayed:
**          Major Heading Name               - NMAJORNAME
**          Actual YTD (home)                - ACT_YTD
**          Last Year Actual YTD (home)      - ACT_YTD_L
**          Actual YTD (Currency)            - ACT_YTD_C
**          Budget YTD (Currency)            - BUD_YTD_C (always 0)
**          Difference YTD (Currency)        - DIFF_YTD_C (always 0)
**          Difference YTD Percent (Currency)- DIFF_YTD_PC_C (always 0)
**          Last Year Actual YTD (Currency)  - ACT_YTD_L_C
**          Last Year Budget YTD (Currency)  - BUD_YTD_L_C (always 0)
**
** The following fields are required for searching:
**          Nominal Account Code             - NCODE
**          Nominal Account Name             - NNAME
**          Currency Code                    - NCURRCODE
**          Category Codes                   - NCATCODE1-NCATCODE8
**          Major Heading Code               - NMAJORCODE
**          Category To View                 - CATEGORY
**          Year (L,C,N)                     - YEAR
**          Period (1-13)                    - PERIOD
**
** The following fields have been moved to AA_NL_BS_YTD_HEADER_VIEW which is intended to be used with this one
**          Budget YTD (home)                - BUD_YTD
**          Last Year Budget YTD (home)      - BUD_YTD_L
**          Difference YTD (home)            - DIFF_YTD
**          Difference YTD Percent (home)    - DIFF_YTD_PC
**
**          [PRIMARY] identifies a row in the result set
**          LINK_PRIMARY relates to a [PRIMARY] in either the corresponding Header or Category view
**          HEADCODE is intended to allow the client to rearrange the data layout in a grid
**
** The list will be sorted by PRIMARY with any other supplied order by field
**
** Written:      22/09/2005 SB
** Last Amended: 05/10/2005 SB, 13/10/2005 SB, 29/10/2005 SB, 20/01/2006 SB
*/
select     
   V.[PRIMARY]
   ,V.HEADCODE
   ,V.NCODE NCODE
   ,V.NNAME NNAME
   ,V.NCATEGORYCODE1 NCATCODE1
   ,V.NCATEGORYCODE2 NCATCODE2
   ,V.NCATEGORYCODE3 NCATCODE3
   ,V.NCATEGORYCODE4 NCATCODE4
   ,V.NCATEGORYCODE5 NCATCODE5
   ,V.NCATEGORYCODE6 NCATCODE6
   ,V.NCATEGORYCODE7 NCATCODE7
   ,V.NCATEGORYCODE8 NCATCODE8
   ,V.NMAJORHEADCODE NMAJORCODE
   ,V.NL_MAJORNAME NMAJORNAME
   ,V.NCURRENCYCODE NCURRCODE
   ,V.PERIOD PERIOD
   ,V.YEAR YEAR
   --£ Actual YTD 
   ,dbo.AA_VALUE_DPS_F(case NMAJORHEADCODE when 1 then -NBALANCE_YTD when 3 then -NBALANCE_YTD when 10 then -NBALANCE_YTD when 11 then -NBALANCE_YTD when 12 then -NBALANCE_YTD else NBALANCE_YTD end) ACT_YTD
   --£ Last Year Actual YTD 
   ,dbo.AA_VALUE_DPS_F(case NMAJORHEADCODE when 1 then -NBALANCE_YTD_L when 3 then -NBALANCE_YTD_L when 10 then -NBALANCE_YTD_L when 11 then -NBALANCE_YTD_L when 12 then -NBALANCE_YTD_L else NBALANCE_YTD_L end) ACT_YTD_L
   --Currency Actual YTD
   ,dbo.AA_VALUE_DPS_F(case NMAJORHEADCODE when 1 then -NBALANCE_YTD_CURR when 3 then -NBALANCE_YTD_CURR when 10 then -NBALANCE_YTD_CURR when 11 then -NBALANCE_YTD_CURR when 12 then -NBALANCE_YTD_CURR else NBALANCE_YTD_CURR end) ACT_YTD_C
   --Currency Budget YTD
   ,dbo.AA_VALUE_DPS_F(0) BUD_YTD_C
   --Currency Difference YTD
   ,dbo.AA_VALUE_DPS_F(0) DIFF_YTD_C
   --Currency Difference YTD %
   ,dbo.AA_VALUE_DPS_F(0) DIFF_YTD_PC_C 
   --Currency Last Year Actual YTD 
   ,dbo.AA_VALUE_DPS_F(case NMAJORHEADCODE when 1 then -NBALANCE_YTD_L_C when 3 then -NBALANCE_YTD_L_C when 10 then -NBALANCE_YTD_L_C when 11 then -NBALANCE_YTD_L_C when 12 then -NBALANCE_YTD_L_C else NBALANCE_YTD_L_C end) ACT_YTD_L_C
   --Currency Last Year Budget YTD
   ,dbo.AA_VALUE_DPS_F(0 ) BUD_YTD_L_C
   ,dbo.AA_VALUE_DPS_F(V.NTURNOVER_YTD) NTURNOVER_YTD
from( select NM_PRIMARY [PRIMARY]
      ,cast(NM_PRIMARY as decimal(16,1)) HEADCODE
      ,NCODE 
      ,isnull(NNAME,'') NNAME
      ,isnull(NCURRENCYCODE,'') NCURRENCYCODE
      ,isnull(NCATEGORYCODE1,'') NCATEGORYCODE1
      ,isnull(NCATEGORYCODE2,'') NCATEGORYCODE2
      ,isnull(NCATEGORYCODE3,'') NCATEGORYCODE3
      ,isnull(NCATEGORYCODE4,'') NCATEGORYCODE4
      ,isnull(NCATEGORYCODE5,'') NCATEGORYCODE5
      ,isnull(NCATEGORYCODE6,'') NCATEGORYCODE6
      ,isnull(NCATEGORYCODE7,'') NCATEGORYCODE7
      ,isnull(NCATEGORYCODE8,'') NCATEGORYCODE8
      ,NMAJORHEADCODE 
      ,isnull(dbo.NL_MAJORHEADING.NL_MAJORNAME,'') NL_MAJORNAME
      ,cast(case
         when PERIOD = 1 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 -- BALANCES used by BALANCE SHEET  TRIAL BALANCE... BalanceYearToC1 ETC
         when PERIOD = 2 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2
         when PERIOD = 3 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3
         when PERIOD = 4 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4
         when PERIOD = 5 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5
         when PERIOD = 6 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6
         when PERIOD = 7 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7
         when PERIOD = 8 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8
         when PERIOD = 9 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9
         when PERIOD = 10 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10
         when PERIOD = 11 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11
         when PERIOD = 12 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12
         when PERIOD = 13 and YEAR = 'C' then N1.NOPENBALYEAR + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 1 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1
         when PERIOD = 2 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2
         when PERIOD = 3 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3
         when PERIOD = 4 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4
         when PERIOD = 5 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5
         when PERIOD = 6 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6
         when PERIOD = 7 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7
         when PERIOD = 8 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8
         when PERIOD = 9 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9
         when PERIOD = 10 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10
         when PERIOD = 11 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10 + N1.NTURNOVER_L11
         when PERIOD = 12 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10 + N1.NTURNOVER_L11 + N1.NTURNOVER_L12
         when PERIOD = 13 and YEAR = 'L' then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10 + N1.NTURNOVER_L11 + N1.NTURNOVER_L12 + N1.NTURNOVER_L13
         when PERIOD = 1 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 2 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 3 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 4 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 5 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 6 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 7 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 8 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 9 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 10 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9 + N1.NTURNOVER_N10 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 11 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9 + N1.NTURNOVER_N10 + N1.NTURNOVER_N11 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 12 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9 + N1.NTURNOVER_N10 + N1.NTURNOVER_N11 + N1.NTURNOVER_N12 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 13 and YEAR = 'N' then N1.NOPENBALYEAR + N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9 + N1.NTURNOVER_N10 + N1.NTURNOVER_N11 + N1.NTURNOVER_N12 + N1.NTURNOVER_N13 + N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         else 0 end as decimal(24,8)) NBALANCE_YTD  
      ,cast(case
         when PERIOD = 1 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C
         when PERIOD = 2 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C
         when PERIOD = 3 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C
         when PERIOD = 4 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C
         when PERIOD = 5 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C
         when PERIOD = 6 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C
         when PERIOD = 7 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C
         when PERIOD = 8 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C
         when PERIOD = 9 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C
         when PERIOD = 10 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C
         when PERIOD = 11 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C
         when PERIOD = 12 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C
         when PERIOD = 13 and YEAR = 'C' then N1.NOPENBALYR_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 1 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C
         when PERIOD = 2 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C
         when PERIOD = 3 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C
         when PERIOD = 4 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C
         when PERIOD = 5 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C
         when PERIOD = 6 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C
         when PERIOD = 7 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C
         when PERIOD = 8 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C
         when PERIOD = 9 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C
         when PERIOD = 10 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C
         when PERIOD = 11 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C + N1.NTURNOVER_L11_C
         when PERIOD = 12 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C + N1.NTURNOVER_L11_C + N1.NTURNOVER_L12_C
         when PERIOD = 13 and YEAR = 'L' then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C + N1.NTURNOVER_L11_C + N1.NTURNOVER_L12_C + N1.NTURNOVER_L13_C
         when PERIOD = 1 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 2 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 3 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 4 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 5 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 6 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 7 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 8 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 9 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 10 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C + N1.NTURNOVER_N10_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 11 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C + N1.NTURNOVER_N10_C + N1.NTURNOVER_N11_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 12 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C + N1.NTURNOVER_N10_C + N1.NTURNOVER_N11_C + N1.NTURNOVER_N12_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 13 and YEAR = 'N' then N1.NOPENBALYR_C + N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C + N1.NTURNOVER_N10_C + N1.NTURNOVER_N11_C + N1.NTURNOVER_N12_C + N1.NTURNOVER_N13_C + N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C     
         else 0 end as decimal(24,8)) NBALANCE_YTD_CURR
      ,cast(case
         when PERIOD = 1 and YEAR ='C' then N1.NTURNOVER_C1
         when PERIOD = 2 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2
         when PERIOD = 3 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3
         when PERIOD = 4 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4
         when PERIOD = 5 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5
         when PERIOD = 6 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6
         when PERIOD = 7 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7
         when PERIOD = 8 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8
         when PERIOD = 9 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9
         when PERIOD = 10 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10
         when PERIOD = 11 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11
         when PERIOD = 12 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12
         when PERIOD = 13 and YEAR ='C' then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
         when PERIOD = 1 and YEAR ='L' then N1.NTURNOVER_L1
         when PERIOD = 2 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2
         when PERIOD = 3 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3
         when PERIOD = 4 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4
         when PERIOD = 5 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5
         when PERIOD = 6 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6
         when PERIOD = 7 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7
         when PERIOD = 8 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8
         when PERIOD = 9 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9
         when PERIOD = 10 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10
         when PERIOD = 11 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10 + N1.NTURNOVER_L11
         when PERIOD = 12 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10 + N1.NTURNOVER_L11 + N1.NTURNOVER_L12
         when PERIOD = 13 and YEAR ='L' then N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10 + N1.NTURNOVER_L11 + N1.NTURNOVER_L12 + N1.NTURNOVER_L13
         when PERIOD = 1 and YEAR ='N' then N1.NTURNOVER_N1
         when PERIOD = 2 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2
         when PERIOD = 3 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3
         when PERIOD = 4 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4
         when PERIOD = 5 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5
         when PERIOD = 6 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6
         when PERIOD = 7 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7
         when PERIOD = 8 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8
         when PERIOD = 9 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9
         when PERIOD = 10 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9 + N1.NTURNOVER_N10
         when PERIOD = 11 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9 + N1.NTURNOVER_N10 + N1.NTURNOVER_N11
         when PERIOD = 12 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9 + N1.NTURNOVER_N10 + N1.NTURNOVER_N11 + N1.NTURNOVER_N12
         when PERIOD = 13 and YEAR ='N' then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9 + N1.NTURNOVER_N10 + N1.NTURNOVER_N11 + N1.NTURNOVER_N12 + N1.NTURNOVER_N13
         else 0 end as decimal(24,8)) NTURNOVER_YTD  
      ,cast(case
         when PERIOD = 1 and YEAR ='C' then N1.NTURNOVER_C1_C
         when PERIOD = 2 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C
         when PERIOD = 3 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C
         when PERIOD = 4 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C
         when PERIOD = 5 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C
         when PERIOD = 6 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C
         when PERIOD = 7 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C
         when PERIOD = 8 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C
         when PERIOD = 9 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C
         when PERIOD = 10 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C
         when PERIOD = 11 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C
         when PERIOD = 12 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C
         when PERIOD = 13 and YEAR ='C' then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
         when PERIOD = 1 and YEAR ='L' then N1.NTURNOVER_L1_C
         when PERIOD = 2 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C
         when PERIOD = 3 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C
         when PERIOD = 4 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C
         when PERIOD = 5 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C
         when PERIOD = 6 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C
         when PERIOD = 7 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C
         when PERIOD = 8 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C
         when PERIOD = 9 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C
         when PERIOD = 10 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C
         when PERIOD = 11 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C + N1.NTURNOVER_L11_C
         when PERIOD = 12 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C + N1.NTURNOVER_L11_C + N1.NTURNOVER_L12_C
         when PERIOD = 13 and YEAR ='L' then N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C + N1.NTURNOVER_L11_C + N1.NTURNOVER_L12_C + N1.NTURNOVER_L13_C      
         when PERIOD = 1 and YEAR ='N' then N1.NTURNOVER_N1_C
         when PERIOD = 2 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C
         when PERIOD = 3 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C
         when PERIOD = 4 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C
         when PERIOD = 5 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C
         when PERIOD = 6 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C
         when PERIOD = 7 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C
         when PERIOD = 8 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C
         when PERIOD = 9 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C
         when PERIOD = 10 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C + N1.NTURNOVER_N10_C
         when PERIOD = 11 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C + N1.NTURNOVER_N10_C + N1.NTURNOVER_N11_C
         when PERIOD = 12 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C + N1.NTURNOVER_N10_C + N1.NTURNOVER_N11_C + N1.NTURNOVER_N12_C
         when PERIOD = 13 and YEAR ='N' then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C + N1.NTURNOVER_N10_C + N1.NTURNOVER_N11_C + N1.NTURNOVER_N12_C + N1.NTURNOVER_N13_C
         else 0 end as decimal(24,8)) NTURNOVER_YTD_CURR
      ,cast(0 as decimal(24,8)) NBUDGET_YTD_CURR
      ,cast(case
         when PERIOD = 1 then N1.NOPENBALANCELY + N1.NTURNOVER_L1
         when PERIOD = 2 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2
         when PERIOD = 3 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3
         when PERIOD = 4 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4
         when PERIOD = 5 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5
         when PERIOD = 6 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6
         when PERIOD = 7 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7
         when PERIOD = 8 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8
         when PERIOD = 9 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9
         when PERIOD = 10 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10
         when PERIOD = 11 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10 + N1.NTURNOVER_L11
         when PERIOD = 12 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10 + N1.NTURNOVER_L11 + N1.NTURNOVER_L12
         when PERIOD = 13 then N1.NOPENBALANCELY + N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10 + N1.NTURNOVER_L11 + N1.NTURNOVER_L12 + N1.NTURNOVER_L13
         else 0 end as decimal(24,8)) NBALANCE_YTD_L  
      ,cast(case
         when PERIOD = 1 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C
         when PERIOD = 2 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C
         when PERIOD = 3 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C
         when PERIOD = 4 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C
         when PERIOD = 5 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C
         when PERIOD = 6 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C
         when PERIOD = 7 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C
         when PERIOD = 8 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C
         when PERIOD = 9 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C
         when PERIOD = 10 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C
         when PERIOD = 11 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C + N1.NTURNOVER_L11_C
         when PERIOD = 12 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C + N1.NTURNOVER_L11_C + N1.NTURNOVER_L12_C
         when PERIOD = 13 then N1.NOPENBALANCLY_C + N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C + N1.NTURNOVER_L11_C + N1.NTURNOVER_L12_C + N1.NTURNOVER_L13_C
         else 0 end as decimal(24,8)) NBALANCE_YTD_L_C
      ,cast(0 as decimal(24,8)) NBUDGET_YTD_L_C
      ,PERIOD
      ,YEAR
   from NL_ACCOUNTS N1 with (index(NMAJORHEADCODE))
   inner join dbo.NL_MAJORHEADING on NMAJORHEADCODE = dbo.NL_MAJORHEADING.NL_MAJORCODE
      ,(select 1 as PERIOD union select 2 as PERIOD union select 3 as PERIOD
         union select 4 as PERIOD union select 5 as PERIOD
         union select 6 as PERIOD union select 7 as PERIOD union select 8 as PERIOD
         union select 9 as PERIOD union select 10 as PERIOD
         union select 11 as PERIOD union select 12 as PERIOD union select 13 as PERIOD
       ) PERIODS
       ,(select 'L' as Year union select 'C' as Year union select 'N' as Year) YEARS
   where isnull(dbo.NL_MAJORHEADING.NL_MAJORCODE,0) between 7 and 12
   ) V