CREATE VIEW AA_NET_STK_SUBANALYSIS_CALCS_VIEW
/*
** Written:        09/12/02 SRB
** Last Amended: 
*/
AS

select 
LOC.LOC_CONCATCODE AS CONCATCODE,
dbo.AA_VALUE_DPS_F(
	COALESCE(
		(LOC_PHYSICAL + LOC_QTYPRINTED +
			CASE STK_FREE_METHOD
				WHEN 'F' THEN
					LOC_ORDER_IN
				ELSE
					0	
			END
		)
		 - LOC_RESERVE_OUT

	,0)
)
AS

STOCKFREE,

--Creates the Valuation chosen within Stock Options
--If Null the value returned will be 0.
dbo.AA_VALUE_DPS_F(
COALESCE(
CASE STK_USR_VALUATN
	WHEN 'F' THEN
		LOC_FIFO_VALU
	WHEN 'A' THEN
		LOC_AV_VALU
	WHEN 'W' THEN
		0
	ELSE 
		(LOC_PHYSICAL+LOC_QTYPRINTED)*

		(LOC_COSTPRICE/
		CASE 
			--Needed to stop a divide by zero
			STK_BUY_UNIT1 
				WHEN 0 THEN 
					1
				ELSE
					STK_BUY_UNIT1
				END 
		)
	END 

,0)
)
AS

STKVALUE,
dbo.AA_VALUE_DPS_F(
COALESCE(
	CASE STK_USR_VALUATN
		WHEN 'L' THEN
			(LOC_PHYSICAL + LOC_QTYPRINTED)* 
			(LOC_COSTPRICE /
			--Needed to stop a divide by zero
			CASE STK_BUY_UNIT1 
				WHEN 0 THEN 
					1
				ELSE
					STK_BUY_UNIT1
				END 
			)
		WHEN 'F' THEN
			LOC_FIFO_VALU 
		WHEN 'A' THEN
			LOC_AV_VALU 
		WHEN 'W' THEN
			

		CASE 
		WHEN COALESCE(LOC_WAPU_QUANTITY,LOC_WAPU_QUANTITY,0) > 0 THEN

	
			(LOC_PHYSICAL+LOC_QTYPRINTED)*(LOC_WAPU_VALUE/LOC_WAPU_QUANTITY)

			
		ELSE
			0
		END 
		
	END
	
,0)
)

AS
VALUATION,
dbo.AA_VALUE_DPS_F(
COALESCE(
	CASE STK_USR_VALUATN
		WHEN 'L' THEN
			(LOC_PHYSICAL + LOC_QTYPRINTED)* 
			(LOC_COSTPRICE /
			--Needed to stop a divide by zero
			CASE STK_BUY_UNIT1 
				WHEN 0 THEN 
					1
				ELSE
					STK_BUY_UNIT1
				END 
			)  + LOC_ACTUAL_LC
		WHEN 'F' THEN
			LOC_FIFO_VALU  + LOC_ACTUAL_LC
		WHEN 'A' THEN
			LOC_AV_VALU + LOC_ACTUAL_LC
		WHEN 'W' THEN
			

		CASE 
		WHEN COALESCE(LOC_WAPU_QUANTITY,LOC_WAPU_QUANTITY,0) > 0 THEN

	
			(LOC_PHYSICAL+LOC_QTYPRINTED)*(LOC_WAPU_VALUE/LOC_WAPU_QUANTITY)

			
		ELSE
			0
		END 
		
	END
	
,0)
)

AS
VALUATIONWITHLANDEDCOSTS,
dbo.AA_VALUE_DPS_F(
COALESCE(	
	(LOC_PHYSICAL+LOC_QTYPRINTED)*LOC_STNDRD_COST
	/
	CASE 
		WHEN STK_BUY_UNIT1 IS NULL THEN
			1
		WHEN STK_BUY_UNIT1 = 0 THEN
			1
		ELSE
			STK_BUY_UNIT1
	END
,0)
)

as

STANDARDVALUE,
dbo.AA_VALUE_DPS_F(
COALESCE(	
	(LOC_PHYSICAL+LOC_QTYPRINTED)*LOC_STNDRD_COST
	/(
	CASE 
		WHEN STK_BUY_UNIT1 IS NULL THEN
			1
		WHEN STK_BUY_UNIT1 = 0 THEN
			1
		ELSE
			STK_BUY_UNIT1
	END
	)
	+ LOC_ACTUAL_LC
,0)
)

as

STANDARDVALUEWITHLANDEDCOSTS,

(LOC_LANDED_COMMITTED1+LOC_LANDED_COMMITTED2+LOC_LANDED_COMMITTED3+LOC_LANDED_COMMITTED4+
LOC_LANDED_COMMITTED5+LOC_LANDED_COMMITTED6+LOC_LANDED_COMMITTED7+LOC_LANDED_COMMITTED8+
LOC_LANDED_COMMITTED8+LOC_LANDED_COMMITTED9+LOC_LANDED_COMMITTED10)
AS

COMMITTEDLANDEDCOSTS,


	CASE 	
		WHEN (LOC_PHYSICAL+LOC_QTYPRINTED) = 0 THEN
			1
		ELSE
			LOC_PHYSICAL+LOC_QTYPRINTED

	END

as

QUANTITYOUTSTANDINGFORCALC,

dbo.AA_VALUE_DPS_F(LOC_ACTUAL_LC)

as

ACTUALLANDEDCOSTS
from STK_LOCATION LOC
inner join STK_STOCK_2 ON STKCODE2 = LOC_STOCK_CODE
inner join STK_LOCATION2 ON    LOC_CONCATCODE2 = LOC.LOC_CONCATCODE
join sys_datainfo2 on sys_primary_2=1 
join sys_datainfo on sys_primary=1  

