CREATE VIEW AA_NET_CST_DETAIL_TRAN_VIEW
/*
** Written:    13/01/03 SRB    
** Last Amended: 15/01/03 SRB; 16/01/03 SRB; 18/09/03 ROBB; 06/10/03 ROBB
*/
AS

SELECT 
CT_PRIMARY,
CT_STATUS,
COALESCE(CT_TRANTYPE ,'') as CT_TRANTYPE,
COALESCE(CT_HEADER_REF ,'') as CT_HEADER_REF,
COALESCE(CT_BATCH_REF ,'') as CT_BATCH_REF,
CT_DATE,
CT_WEEK_NO,
CT_YEAR,
CT_PERIODNUMBR,
CT_DESCRIPTION,
COALESCE(CT_COSTHEADER ,'') as CT_COSTHEADER,
CH_NAME,
COALESCE(CT_COSTCENTRE ,'') as CT_COSTCENTRE,
CC_NAME,
COALESCE(CT_RESOURCE ,'') as CT_RESOURCE,
PRNAME,
CT_RESLINE,
CT_CURR_CODE,
CT_QUANTITY,
CT_NETT,
CT_PRICE,
CT_CURR_PRICE,
CT_CENTRE_UPLP,
CT_CENTRE_UPLV,
CT_CURR_CNTUPLV,
CT_PAYTYPE_CODE,
CT_DETAIL,
CT_ARCHIVE_FLG,
CT_BATCH_FLAG,
CT_MU_STATUS,
CT_USRCHAR1 , 
CT_RES_UPLV,
CT_CURR_RESUPLV,
CT_USER_PUTIN,
CT_USRCHAR2, 
CT_USRCHAR3, 
CT_USRCHAR4, 
CT_USRFLAG1, 
CT_USRFLAG2, 
CT_USRDATE1, 
CT_USRDATE2, 
CT_USRNUM1, 
CT_USRNUM2

from CST_DETAIL LEFT OUTER JOIN CST_DETAIL2 ON CST_DETAIL.CT_PRIMARY = CST_DETAIL2.CT_PRIMARY_2

LEFT OUTER JOIN CST_COSTCENTRE ON COALESCE (CONVERT(char(10), CT_COSTHEADER) + CONVERT(varchar,CT_COSTCENTRE),'') = CST_COSTCENTRE.CC_CONCAT_CODES 
LEFT OUTER JOIN CST_COSTHEADER ON COALESCE (CT_COSTHEADER,'') = CST_COSTHEADER.CH_CODE
LEFT OUTER JOIN PRC_PRICE_RECS ON COALESCE (CT_RESOURCE,'') = PRC_PRICE_RECS.PRCODE
