CREATE VIEW AA_NET_STK_SELLPRICE_VIEW
/*
** Retrieves all the necessary data to populate the .NET XML Schema
**
** Written:14/01/2003 SRB
** Last Amended: 15/01/03 NC
**
*/
as

select 

STKCODE2,
STKNAME,
'S' As
PRICETYPE,
dbo.AA_PRICE_DPS_F(STK_SELLPRICE1) AS STK_SELLPRICE1,
STK_S_CURRCDE1,
dbo.AA_PRICE_DPS_F(STK_S_CURRPRC1) AS STK_S_CURRPRC1,
dbo.AA_PRICE_DPS_F(STK_S_BASE2PRC1) AS STK_S_BASE2PRC1,
COALESCE(STK_SANALYSIS1,ANALYSISDEFAULT.SACODE) AS STK_SANALYSIS1,
COALESCE(SL_ANALYSIS1.SANAME,ANALYSISDEFAULT.SANAME) AS STK_SANALYSIS1NAME,
dbo.AA_QUANTITY_DPS_F(STK_SELL_UNIT1) AS STK_SELL_UNIT1,
COALESCE(STK_SELL_NAME1,'Each') AS STK_SELL_NAME1,
PRICEMETHOD1 = 
case 
	when len(STK_PRICEMETH1) = 3 then substring(STK_PRICEMETH1, 1, 2)
	else STK_PRICEMETH1
end,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_FROM1) AS STK_SQTY_FROM1,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_TO1) AS STK_SQTY_TO1,
dbo.AA_TWO_DPS_F(STK_S_PERCENT1) AS STK_S_PERCENT1,
UPLIFTFROMCOST1 = 
case 
	when len(STK_PRICEMETH1) = 3 and substring(STK_PRICEMETH1, 3, 1) = 'B' then
		0
	when len(STK_PRICEMETH1) = 3 and substring(STK_PRICEMETH1, 3, 1) = 'C' then
		1
end,
STK_PRICEMETH1,

dbo.AA_PRICE_DPS_F(STK_SELLPRICE2) AS STK_SELLPRICE2,
STK_S_CURRCDE2,
dbo.AA_PRICE_DPS_F(STK_S_CURRPRC2) AS STK_S_CURRPRC2,
dbo.AA_PRICE_DPS_F(STK_S_BASE2PRC2) AS STK_S_BASE2PRC2,
COALESCE(STK_SANALYSIS2,ANALYSISDEFAULT.SACODE) AS STK_SANALYSIS2,
COALESCE(SL_ANALYSIS2.SANAME,ANALYSISDEFAULT.SANAME) AS STK_SANALYSIS2NAME,
dbo.AA_QUANTITY_DPS_F(STK_SELL_UNIT2) AS STK_SELL_UNIT2,
COALESCE(STK_SELL_NAME2,'Each') AS STK_SELL_NAME2,
PRICEMETHOD2 = 
case 
	when len(STK_PRICEMETH2) = 3 then substring(STK_PRICEMETH2, 1, 2)
	else STK_PRICEMETH2
end,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_FROM2) AS STK_SQTY_FROM2,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_TO2) AS STK_SQTY_TO2,
dbo.AA_TWO_DPS_F(STK_S_PERCENT2) AS STK_S_PERCENT2,
UPLIFTFROMCOST2 = 
case 
	when len(STK_PRICEMETH2) = 3 and substring(STK_PRICEMETH2, 3, 1) = 'B' then
		0
	when len(STK_PRICEMETH2) = 3 and substring(STK_PRICEMETH2, 3, 1) = 'C' then
		1
end,

dbo.AA_PRICE_DPS_F(STK_SELLPRICE3) AS STK_SELLPRICE3,
STK_S_CURRCDE3,
dbo.AA_PRICE_DPS_F(STK_S_CURRPRC3) AS STK_S_CURRPRC3,
dbo.AA_PRICE_DPS_F(STK_S_BASE2PRC3) AS STK_S_BASE2PRC3,
COALESCE(STK_SANALYSIS3,ANALYSISDEFAULT.SACODE) AS STK_SANALYSIS3,
COALESCE(SL_ANALYSIS3.SANAME,ANALYSISDEFAULT.SANAME) AS STK_SANALYSIS3NAME,
dbo.AA_QUANTITY_DPS_F(STK_SELL_UNIT3) AS STK_SELL_UNIT3,
COALESCE(STK_SELL_NAME3,'Each') AS STK_SELL_NAME3,
PRICEMETHOD3 = 
case 
	when len(STK_PRICEMETH3) = 3 then substring(STK_PRICEMETH3, 1, 2)
	else STK_PRICEMETH3
end,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_FROM3) AS STK_SQTY_FROM3,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_TO3) AS STK_SQTY_TO3,
dbo.AA_TWO_DPS_F(STK_S_PERCENT3) AS STK_S_PERCENT3,
UPLIFTFROMCOST3 = 
case 
	when len(STK_PRICEMETH3) = 3 and substring(STK_PRICEMETH3, 3, 1) = 'B' then
		0
	when len(STK_PRICEMETH3) = 3 and substring(STK_PRICEMETH3, 3, 1) = 'C' then
		1
end,

dbo.AA_PRICE_DPS_F(STK_SELLPRICE4) AS STK_SELLPRICE4,
STK_S_CURRCDE4,
dbo.AA_PRICE_DPS_F(STK_S_CURRPRC4) AS STK_S_CURRPRC4,
dbo.AA_PRICE_DPS_F(STK_S_BASE2PRC4) AS STK_S_BASE2PRC4,
COALESCE(STK_SANALYSIS4,ANALYSISDEFAULT.SACODE) AS STK_SANALYSIS4,
COALESCE(SL_ANALYSIS4.SANAME,ANALYSISDEFAULT.SANAME) AS STK_SANALYSIS4NAME,
dbo.AA_QUANTITY_DPS_F(STK_SELL_UNIT4) AS STK_SELL_UNIT4,
COALESCE(STK_SELL_NAME4,'Each') AS STK_SELL_NAME4,
PRICEMETHOD4 = 
case 
	when len(STK_PRICEMETH4) = 3 then substring(STK_PRICEMETH4, 1, 2)
	else STK_PRICEMETH4
end,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_FROM4) AS STK_SQTY_FROM4,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_TO4) AS STK_SQTY_TO4,
dbo.AA_TWO_DPS_F(STK_S_PERCENT4) AS STK_S_PERCENT4,
UPLIFTFROMCOST4 = 
case 
	when len(STK_PRICEMETH4) = 3 and substring(STK_PRICEMETH4, 3, 1) = 'B' then
		0
	when len(STK_PRICEMETH4) = 3 and substring(STK_PRICEMETH4, 3, 1) = 'C' then
		1
end,

dbo.AA_PRICE_DPS_F(STK_SELLPRICE5) AS STK_SELLPRICE5,
STK_S_CURRCDE5,
dbo.AA_PRICE_DPS_F(STK_S_CURRPRC5) AS STK_S_CURRPRC5,
dbo.AA_PRICE_DPS_F(STK_S_BASE2PRC5) AS STK_S_BASE2PRC5,
COALESCE(STK_SANALYSIS5,ANALYSISDEFAULT.SACODE) AS STK_SANALYSIS5,
COALESCE(SL_ANALYSIS5.SANAME,ANALYSISDEFAULT.SANAME) AS STK_SANALYSIS5NAME,
dbo.AA_QUANTITY_DPS_F(STK_SELL_UNIT5) AS STK_SELL_UNIT5,
COALESCE(STK_SELL_NAME5,'Each') AS STK_SELL_NAME5,
PRICEMETHOD5 = 
case 
	when len(STK_PRICEMETH5) = 3 then substring(STK_PRICEMETH5, 1, 2)
	else STK_PRICEMETH5
end,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_FROM5) AS STK_SQTY_FROM5,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_TO5) AS STK_SQTY_TO5,
dbo.AA_TWO_DPS_F(STK_S_PERCENT5) AS STK_S_PERCENT5,
UPLIFTFROMCOST5 = 
case 
	when len(STK_PRICEMETH5) = 3 and substring(STK_PRICEMETH5, 3, 1) = 'B' then
		0
	when len(STK_PRICEMETH5) = 3 and substring(STK_PRICEMETH5, 3, 1) = 'C' then
		1
end,

dbo.AA_PRICE_DPS_F(STK_SELLPRICE6) AS STK_SELLPRICE6,
STK_S_CURRCDE6,
dbo.AA_PRICE_DPS_F(STK_S_CURRPRC6) AS STK_S_CURRPRC6,
dbo.AA_PRICE_DPS_F(STK_S_BASE2PRC6) AS STK_S_BASE2PRC6,
COALESCE(STK_SANALYSIS6,ANALYSISDEFAULT.SACODE) AS STK_SANALYSIS6,
COALESCE(SL_ANALYSIS6.SANAME,ANALYSISDEFAULT.SANAME) AS STK_SANALYSIS6NAME,
dbo.AA_QUANTITY_DPS_F(STK_SELL_UNIT6) AS STK_SELL_UNIT6,
COALESCE(STK_SELL_NAME6,'Each') AS STK_SELL_NAME6,
PRICEMETHOD6 = 
case 
	when len(STK_PRICEMETH6) = 3 then substring(STK_PRICEMETH6, 1, 2)
	else STK_PRICEMETH6
end,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_FROM6) AS STK_SQTY_FROM6,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_TO6) AS STK_SQTY_TO6,
dbo.AA_TWO_DPS_F(STK_S_PERCENT6) AS STK_S_PERCENT6,
UPLIFTFROMCOST6 = 
case 
	when len(STK_PRICEMETH6) = 3 and substring(STK_PRICEMETH6, 3, 1) = 'B' then
		0
	when len(STK_PRICEMETH6) = 3 and substring(STK_PRICEMETH6, 3, 1) = 'C' then
		1
end,

dbo.AA_PRICE_DPS_F(STK_SELLPRICE7) AS STK_SELLPRICE7,
STK_S_CURRCDE7,
dbo.AA_PRICE_DPS_F(STK_S_CURRPRC7) AS STK_S_CURRPRC7,
dbo.AA_PRICE_DPS_F(STK_S_BASE2PRC7) AS STK_S_BASE2PRC7,
COALESCE(STK_SANALYSIS7,ANALYSISDEFAULT.SACODE) AS STK_SANALYSIS7,
COALESCE(SL_ANALYSIS7.SANAME,ANALYSISDEFAULT.SANAME) AS STK_SANALYSIS7NAME,
dbo.AA_QUANTITY_DPS_F(STK_SELL_UNIT7) AS STK_SELL_UNIT7,
COALESCE(STK_SELL_NAME7,'Each') AS STK_SELL_NAME7,
PRICEMETHOD7 = 
case 
	when len(STK_PRICEMETH7) = 3 then substring(STK_PRICEMETH7, 1, 2)
	else STK_PRICEMETH7
end,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_FROM7) AS STK_SQTY_FROM7,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_TO7) AS STK_SQTY_TO7,
dbo.AA_TWO_DPS_F(STK_S_PERCENT7) AS STK_S_PERCENT7,
UPLIFTFROMCOST7 = 
case 
	when len(STK_PRICEMETH7) = 3 and substring(STK_PRICEMETH7, 3, 1) = 'B' then
		0
	when len(STK_PRICEMETH7) = 3 and substring(STK_PRICEMETH7, 3, 1) = 'C' then
		1
end,

dbo.AA_PRICE_DPS_F(STK_SELLPRICE8) AS STK_SELLPRICE8,
STK_S_CURRCDE8,
dbo.AA_PRICE_DPS_F(STK_S_CURRPRC8) AS STK_S_CURRPRC8,
dbo.AA_PRICE_DPS_F(STK_S_BASE2PRC8) AS STK_S_BASE2PRC8,
COALESCE(STK_SANALYSIS8,ANALYSISDEFAULT.SACODE) AS STK_SANALYSIS8,
COALESCE(SL_ANALYSIS8.SANAME,ANALYSISDEFAULT.SANAME) AS STK_SANALYSIS8NAME,
dbo.AA_QUANTITY_DPS_F(STK_SELL_UNIT8) AS STK_SELL_UNIT8,
COALESCE(STK_SELL_NAME8,'Each') AS STK_SELL_NAME8,
PRICEMETHOD8 = 
case 
	when len(STK_PRICEMETH8) = 3 then substring(STK_PRICEMETH8, 1, 2)
	else STK_PRICEMETH8
end,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_FROM8) AS STK_SQTY_FROM8,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_TO8) AS STK_SQTY_TO8,
dbo.AA_TWO_DPS_F(STK_S_PERCENT8) AS STK_S_PERCENT8,
UPLIFTFROMCOST8 = 
case 
	when len(STK_PRICEMETH8) = 3 and substring(STK_PRICEMETH8, 3, 1) = 'B' then
		0
	when len(STK_PRICEMETH8) = 3 and substring(STK_PRICEMETH8, 3, 1) = 'C' then
		1
end,

dbo.AA_PRICE_DPS_F(STK_SELLPRICE9) AS STK_SELLPRICE9,
STK_S_CURRCDE9,
dbo.AA_PRICE_DPS_F(STK_S_CURRPRC9) AS STK_S_CURRPRC9,
dbo.AA_PRICE_DPS_F(STK_S_BASE2PRC9) AS STK_S_BASE2PRC9,
COALESCE(STK_SANALYSIS9,ANALYSISDEFAULT.SACODE) AS STK_SANALYSIS9,
COALESCE(SL_ANALYSIS9.SANAME,ANALYSISDEFAULT.SANAME) AS STK_SANALYSIS9NAME,
dbo.AA_QUANTITY_DPS_F(STK_SELL_UNIT9) AS STK_SELL_UNIT9,
COALESCE(STK_SELL_NAME9,'Each') AS STK_SELL_NAME9,
PRICEMETHOD9 = 
case 
	when len(STK_PRICEMETH9) = 3 then substring(STK_PRICEMETH9, 1, 2)
	else STK_PRICEMETH9
end,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_FROM9) AS STK_SQTY_FROM9,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_TO9) AS STK_SQTY_TO9,
dbo.AA_TWO_DPS_F(STK_S_PERCENT9) AS STK_S_PERCENT9,
UPLIFTFROMCOST9 = 
case 
	when len(STK_PRICEMETH9) = 3 and substring(STK_PRICEMETH9, 3, 1) = 'B' then
		0
	when len(STK_PRICEMETH9) = 3 and substring(STK_PRICEMETH9, 3, 1) = 'C' then
		1
end,

dbo.AA_PRICE_DPS_F(STK_SELLPRICE10) AS STK_SELLPRICE10,
STK_S_CURRCDE10,
dbo.AA_PRICE_DPS_F(STK_S_CURRPRC10) AS STK_S_CURRPRC10,
dbo.AA_PRICE_DPS_F(STK_S_BASE2PRC10) AS STK_S_BASE2PRC10,
COALESCE(STK_SANALYSIS10,ANALYSISDEFAULT.SACODE) AS STK_SANALYSIS10,
COALESCE(SL_ANALYSIS10.SANAME,ANALYSISDEFAULT.SANAME) AS STK_SANALYSIS10NAME,
dbo.AA_QUANTITY_DPS_F(STK_SELL_UNIT10) AS STK_SELL_UNIT10,
COALESCE(STK_SELL_NAME10,'Each') AS STK_SELL_NAME10,
PRICEMETHOD10 = 
case 
	when len(STK_PRICEMETH10) = 3 then substring(STK_PRICEMETH10, 1, 2)
	else STK_PRICEMETH10
end,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_FROM10) AS STK_SQTY_FROM10,
dbo.AA_QUANTITY_DPS_F(STK_SQTY_TO10) AS STK_SQTY_TO10,
dbo.AA_TWO_DPS_F(STK_S_PERCENT10) AS STK_S_PERCENT10,
UPLIFTFROMCOST10 = 
case 
	when len(STK_PRICEMETH10) = 3 and substring(STK_PRICEMETH10, 3, 1) = 'B' then
		0
	when len(STK_PRICEMETH10) = 3 and substring(STK_PRICEMETH10, 3, 1) = 'C' then
		1
end

from STK_STOCK_2
	inner join STK_STOCK
	on STK_PRIMARY_2 = STK_PRIMARY
	inner join STK_STOCK4
	on STK_PRIMARY_2 = STK_PRIMARY_4

	left join SL_ANALYSIS AS SL_ANALYSIS1
	on STK_PANALYSIS1 = SL_ANALYSIS1.SACODE

	left join SL_ANALYSIS AS SL_ANALYSIS2
	on STK_PANALYSIS2 = SL_ANALYSIS2.SACODE

	left join SL_ANALYSIS AS SL_ANALYSIS3
	on STK_PANALYSIS3 = SL_ANALYSIS3.SACODE

	left join SL_ANALYSIS AS SL_ANALYSIS4
	on STK_PANALYSIS4 = SL_ANALYSIS4.SACODE

	left join SL_ANALYSIS AS SL_ANALYSIS5
	on STK_PANALYSIS5 = SL_ANALYSIS5.SACODE

	left join SL_ANALYSIS AS SL_ANALYSIS6
	on STK_PANALYSIS6 = SL_ANALYSIS6.SACODE

	left join SL_ANALYSIS AS SL_ANALYSIS7
	on STK_PANALYSIS7 = SL_ANALYSIS7.SACODE

	left join SL_ANALYSIS AS SL_ANALYSIS8
	on STK_PANALYSIS8 = SL_ANALYSIS8.SACODE

	left join SL_ANALYSIS AS SL_ANALYSIS9
	on STK_PANALYSIS9 = SL_ANALYSIS9.SACODE

	left join SL_ANALYSIS AS SL_ANALYSIS10
	on STK_PANALYSIS10 = SL_ANALYSIS10.SACODE

	join SL_ANALYSIS AS ANALYSISDEFAULT
	
	on ANALYSISDEFAULT.SADEFAULT_SALES='1'