CREATE VIEW AA_NET_PL_ADDRESSES_LIST_VIEW
/*
** Returns a table to be used specifically with AA_NET_PL_ADDRESSES_LIST_VIEW
** Written:      29/04/03 SRB
** Last Amended: 
**
*/
AS


SELECT 
TYPE = 'SUPPLIER'
,PL_AD_CON_CODE
,PL_AD_CON_CODE as [PRIMARY]
,SU_LEVEL as PROFILELEVEL
,PL_AD_ACCCODE as PARENT
,PL_AD_ACCCODE 
,PL_AD_CODE as CHILD
,COALESCE(SUNAME,'') AS PARENTNAME
,PL_AD_CON_TITLE AS TITLE
,PL_AD_CON_INITS AS INITIALS
,COALESCE(PL_AD_CON_SNAME,'') AS SURNAME
,COALESCE(PL_AD_ADDRESS,'') AS ADDRESS
,COALESCE(PL_AD_ADDRESS_USER1,'') AS TOWN
,COALESCE(PL_AD_POSTCODE,'') AS POSTCODE
,PL_AD_COUNTRY
--Distinguish if a Delivery Address
,CASE WHEN (PL_AD_DEL_ADDRESS_2=1) THEN 
	1 
 ELSE 
	0 
 END 

 AS DELIVERYADDRESS
,PL_AD_INV_ADD AS INVOICEADDRESS 
,PL_AD_REM_ADD AS REMMITANCEADDRESS
,PL_AD_STAT_ADD AS STATEMENTADDRESS
,PL_AD_DEL_ADD As DEFAULTADDRESS

,PL_AD_PHONE as PHONE
,COALESCE(PL_AD_DO_NOT_USE,0) AS DO_NOT_USE

FROM 
PL_ADDRESSES 

INNER JOIN  PL_ACCOUNTS ON 
PL_AD_ACCCODE = SUCODE

LEFT JOIN PL_ACCOUNTS2 ON
SU_PRIMARY = SU_PRIMARY_2