CREATE VIEW AA_NET_RTP_HEADER_TRAN_VIEW
/*
** Written:        23/04/03 ROBB
** Last Amended:   09/07/03 SRB
*/
AS

SELECT 

RPH_ACCOUNT,
SUNAME,
SU_ON_STOP,
SU_MULTI_CURR,
SU_CREDIT_LIMIT,
SUBALANCE,
SUTURNOVERYTD,
RPH_ORDER_NUMBR,
RPH_ORDER_REF,
RPH_BATCH_REF,
RPH_DESCRIPTION,
RPH_YEAR,
RPH_PERIOD,
RPH_DATE,
RPH_REQUIRED,
SU_LINE_DISC,
SU_TOT_DISC,
SU_SETT_DISC1,
SU_SETT_DISC2,
SU_SETT_DAYS1,
SU_SETT_DAYS2,
RPH_CURR_TYPE,
(case when RPH_CURR_TYPE ='E'
		then
			RPH_TRI_RATE1
		else
			RPH_CURR_RATE
		end) 
as RPH_CURR_RATE ,
RPH_CURR_CODE,
RPH_TRI_RATE2,
RPH_IMPEXP_CODE,
RPH_DEL_METHOD,
SU_MIN_ORDR,
SU_DUEDATE_TYPE,
SU_DUE_DAYS,
SU_A_P_DAYS,
SU_TERMS,
RPH_PRICE_KEY,

(case when DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD = 1
	then
		DELIVERY_ADDRESS_LINK.PL_AD_ADDRESS
	else
		DELIVERY_CO_ADDRESS_LINK.COAD_ADDRESS
	end) 
as D_ADD_ADDRESS ,

(case when DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD = 1
	then
		SUNAME
	else
		DELIVERY_CO_ADDRESS_LINK.COAD_NAME
	end) 
as D_ADD_NAME ,


(case when DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD = 1
	then
		DELIVERY_ADDRESS_LINK.PL_AD_ADDRESS_USER1
	else
		DELIVERY_CO_ADDRESS_LINK.COAD_ADDRESS_USER1
	end) 
as D_ADD_TOWN ,

(case when DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD = 1
	then
		DELIVERY_ADDRESS_LINK.PL_AD_ADDRESS_USER2
	else
		DELIVERY_CO_ADDRESS_LINK.COAD_ADDRESS_USER2
	end) 
as D_ADD_COUNTY ,

(case when DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD = 1
	then
		DELIVERY_ADDRESS_LINK.PL_AD_COUNTRY
	else
		DELIVERY_CO_ADDRESS_LINK.COAD_COUNTRY
	end) 
as D_ADD_COUNTRY ,

(case when DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD = 1
	then
		DELIVERY_ADDRESS_LINK.PL_AD_POSTCODE
	else
		DELIVERY_CO_ADDRESS_LINK.COAD_POSTCODE
	end) 
as D_ADD_POSTCODE ,

(case when DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD = 1
	then
		DELIVERY_ADDRESS_LINK.PL_AD_EMAIL
	else
		DELIVERY_CO_ADDRESS_LINK.COAD_EMAIL
	end) 
as D_ADD_EMAIL,

(case when DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD = 1
	then
		DELIVERY_ADDRESS_LINK.PL_AD_PHONE
	else
		DELIVERY_CO_ADDRESS_LINK.COAD_PHONE
	end) 
as D_ADD_PHONE,

(case when DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD = 1
	then
		DELIVERY_ADDRESS_LINK.PL_AD_FAX
	else
		DELIVERY_CO_ADDRESS_LINK.COAD_FAX
	end) 
as D_ADD_FAX,

(case when DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD = 1
	then
		DELIVERY_ADDRESS_LINK.PL_AD_CONTACT
	else
		DELIVERY_CO_ADDRESS_LINK.COAD_CONTACT		
	end) 
as D_ADD_CONTACT,

ORDER_ADDRESS_LINK.PL_AD_ADDRESS as O_ADD_ADDRESS,
ORDER_ADDRESS_LINK.PL_AD_ADDRESS_USER1 as O_ADD_TOWN,
ORDER_ADDRESS_LINK.PL_AD_ADDRESS_USER2 as O_ADD_COUNTY,
ORDER_ADDRESS_LINK.PL_AD_COUNTRY as O_ADD_COUNTRY,
ORDER_ADDRESS_LINK.PL_AD_POSTCODE as O_ADD_POSTCODE,
ORDER_ADDRESS_LINK.PL_AD_EMAIL as O_ADD_EMAIL,
ORDER_ADDRESS_LINK.PL_AD_PHONE as O_ADD_PHONE,
ORDER_ADDRESS_LINK.PL_AD_FAX as O_ADD_FAX,
ORDER_ADDRESS_LINK.PL_AD_CONTACT as O_ADD_CONTACT,
ORDER_ADDRESS_LINK.PL_AD_DO_NOT_USE as O_ADD_EXCLUDENAME,

RPH_ARCHIVE,
substring(RPH_TRAN_OPTIONS,5,1) as ALLOW_EMPTY_SUB_ANALYSIS,
substring(RPH_TRAN_OPTIONS,7,1) as ALLOW_EMPTY_SERIAL_NO,
RPH_USRCHAR1,
RPH_USRCHAR2,
RPH_USRCHAR3,
RPH_USRCHAR4,
RPH_USRFLAG1,
RPH_USRFLAG2,
RPH_USRDATE1,
RPH_USRDATE2,
RPH_USRNUM1,
RPH_USRNUM2,
SU_NOTES,
RPH_PRIMARY

FROM RTP_HEADER

LEFT OUTER JOIN PL_ACCOUNTS ON RTP_HEADER.RPH_ACCOUNT = PL_ACCOUNTS.SUCODE
LEFT OUTER JOIN RTP_HEADER2 ON RTP_HEADER.RPH_PRIMARY = RTP_HEADER2.RPH_PRIMARY_2

LEFT OUTER JOIN PL_ADDRESSES ORDER_ADDRESS_LINK ON ( (ORDER_ADDRESS_LINK.PL_AD_ACCCODE = RPH_ACCOUNT) and (ORDER_ADDRESS_LINK.PL_AD_INV_ADD=1))
LEFT OUTER JOIN PL_ADDRESSES DELIVERY_ADDRESS_LINK ON ( (DELIVERY_ADDRESS_LINK.PL_AD_ACCCODE = RPH_ACCOUNT) and (DELIVERY_ADDRESS_LINK.PL_AD_DEL_ADD=1))
LEFT OUTER JOIN SYS_COMP_ADDRESS DELIVERY_CO_ADDRESS_LINK ON DELIVERY_CO_ADDRESS_LINK.COAD_DEFAULT = 1