CREATE VIEW AA_NET_NL_RECORD_LIST_VIEW
/*
** Returns a table to be used specifically with AA_NET_SL_ANALYSIS_LIST_S
** Written:      27/02/03 SRB
** Last Amended: 13/03/03 ROBB; 25/03/03 SRB
**
*/
AS

select 

NCODE as [PRIMARY]
,N_LEVEL as PROFILELEVEL
,NCODE
,COALESCE(NNAME,'') as NNAME
,NTYPE
,N_DATE_EDITED
,N_DATE_PUTIN
,NMAJORHEADCODE
,COALESCE(NL_MAJORNAME,'') as NL_MAJORNAME
,COALESCE(NCURRENCYCODE,'') as NCURRENCYCODE
,COALESCE(NCATEGORYCODE1,'') as NCATEGORYCODE1
,COALESCE(NCATEGORYCODE2,'') as NCATEGORYCODE2
,COALESCE(NCATEGORYCODE3,'') as NCATEGORYCODE3
,COALESCE(NCATEGORYCODE4,'') as NCATEGORYCODE4
,COALESCE(NCATEGORYCODE5,'') as NCATEGORYCODE5
,COALESCE(NCATEGORYCODE6,'') as NCATEGORYCODE6
,COALESCE(NCATEGORYCODE7,'') as NCATEGORYCODE7
,COALESCE(NCATEGORYCODE8,'') as NCATEGORYCODE8
,N_PROFILE_REC

from NL_ACCOUNTS inner join NL_ACCOUNTS2 
	on N_PRIMARY = N_PRIMARY_2
inner join NL_MAJORHEADING 
	on NMAJORHEADCODE  = NL_MAJORCODE


