CREATE VIEW AA_NET_SL_HEADER_TRAN_VIEW
/*
** Written:        
** Last Amended: 20/03/03 ROBB; 02/05/03 ROBB; 08/05/03 ROBB
*/

AS

SELECT     
CUNAME,
CU_ON_STOP,
CU_MULTI_CURR,
dbo.AA_PRICE_DPS_F(CU_CREDIT_LIMIT) AS CU_CREDIT_LIMIT, 
dbo.AA_PRICE_DPS_F(CUBALANCE) AS CUBALANCE,
dbo.AA_PRICE_DPS_F(CUTURNOVERYTD) AS CUTURNOVERYTD,
CU_A_P_DAYS,
CU_VAT_REG_NO,
CU_NOTES,
CU_TERMS,
CU_DUE_DAYS,
CU_DUEDATE_TYPE,
AD_ADDRESS,
AD_ADDRESS_USER1,
AD_ADDRESS_USER2,
AD_POSTCODE,
AD_COUNTRY,
AD_E_MAIL,
AD_PHONE,
AD_FAX,
AD_CONTACT, 
AD_ACCOUNTNAME,
ST_TRANTYPE,
ST_COPYCUST,
ST_CURRENCYCODE,
(case when ST_CURR_TYPE ='E'
	then
		ST_TRI_RATE1
	else
		ST_CURRENCYRATE
	end) 
as ST_CURRENCYRATE,
ST_CURR_TYPE, 
ST_TRI_RATE2,
ST_EXPORT_CODE,
ST_EC_DEL_TERMS,
ST_EC_T_NATURE, 
ST_EC_T_MODE,
ST_SETT_DISC_1,
ST_SETT_DAYS_1, 
ST_SETT_DISC_2,
ST_SETT_DAYS_2,
ST_HEADER_REF,
ST_BATCH_REF, 
ST_DATE,
ST_YEAR,
ST_PERIODNUMBER, 
ST_DUEDATE,
ST_ANTICPAYDATE,
ST_DESCRIPTION, 
ST_QUERY_FLAG,
ST_ARCHIVE_FLAG,
ST_HEADER_KEY,
ST_BATCH_FLAG,
ST_MU_STATUS,
ST_SUB_LEDGER,
ST_TRAN_OPTIONS,
ST_PRIMARY,
STT_USRCHAR1,
ST_USRCHAR2,
ST_USRCHAR3,
ST_USRCHAR4,
ST_USRFLAG1,
ST_USRFLAG2,
ST_USRDATE1,
ST_USRDATE2,
ST_USRNUM1,
ST_USRNUM2,
(case when substring(ST_TRAN_OPTIONS,3,1) is null then 0 else substring(ST_TRAN_OPTIONS,3,1) end) as GROSSENTRY,
(case when substring(ST_TRAN_OPTIONS,3,1) is null then 0 else substring(ST_TRAN_OPTIONS,3,1) end) as CURRENCYENTRY,
(case when substring(ST_TRAN_OPTIONS,6,1) is null then 0 else substring(ST_TRAN_OPTIONS,6,1) end) as DUERECEIPTDATEENTRY

FROM         
SL_TRANSACTIONS
LEFT OUTER JOIN SL_TRANSACTIONS2 ON SL_TRANSACTIONS.ST_PRIMARY = SL_TRANSACTIONS2.ST_PRIMARY_2
LEFT OUTER JOIN SL_ACCOUNTS ON SL_TRANSACTIONS.ST_COPYCUST = SL_ACCOUNTS.CUCODE
LEFT OUTER JOIN SL_ADDRESSES ON CONVERT(char(10),SL_ACCOUNTS.CUCODE) + '1' = SL_ADDRESSES.AD_CON_CODE  