CREATE VIEW AA_NET_PL_ANALYSIS_TRAN_VIEW
/*
** Written:   16/07/01 SC     
** Last Amended: 09/12/02 SRB
*/
AS

SELECT
PL_ANALYSIS.PACODE,
PL_ANALYSIS.PANAME,
PL_ANALYSIS.PACURRENCYSYMBL,
PL_ANALYSIS.PA_FORCE_COSTING,
SYS_CURRENCY_REC.CURREC_PURCH_AN,
SYS_VATCONTROL.VAT_CODE,
SYS_VATCONTROL.VAT_RATE,
SYS_VATCONTROL.EC_TYPE
FROM PL_ANALYSIS
LEFT OUTER JOIN SYS_CURRENCY_REC ON PL_ANALYSIS.PACURRENCYSYMBL = SYS_CURRENCY_REC.CURREC_SYMBOL
LEFT OUTER JOIN SYS_VATCONTROL ON PL_ANALYSIS.PAVATCODE = SYS_VATCONTROL.VAT_CODE
