create view AA_PL_BATCH_HEADER_ADVANCED_VIEW
/*
** Written:      
** Last Amended: 01/03/2005 SR, 03/03/2005 SH, 23/08/2005 SH, 26/10/2005 JC
*/
as

select
 PT_PRIMARY as [PRIMARY]
,PT_COPYSUPP
,isnull(SUNAME,'') as SUNAME
,PT_DATE
,PT_TRANTYPE
,isnull(PT_HEADER_REF,'') as PT_HEADER_REF
,dbo.AA_VALUE_DPS_F(PT_GROSS) as PT_GROSS
,dbo.AA_VALUE_DPS_F(PT_GROSS) * case when PT_TRANTYPE in ('INV','ACR','JCR') then 1 else -1 end as SIGN_PT_GROSS
,PT_DUEDATE
,isnull(PT_DESCRIPTION,'') as PT_DESCRIPTION
,isnull(PT_BATCH_REF,'') as PT_BATCH_REF
,PT_ANTICPAYDATE
,dbo.AA_VALUE_DPS_F(PT_CURR_VALU) * case when PT_TRANTYPE in ('INV','ACR','JCR') then 1 else -1 end as PT_CURR_VALU	
,PT_CURRENCYRATE
,PT_PRIMARY
,PT_YEAR
,PT_PERIODNUMBER
,PT_USER_PUTIN
,PT_CURRENCYCODE

from PL_TRANSACTIONS 
join PL_ACCOUNTS on PT_COPYSUPP = SUCODE 
where PT_BATCH_FLAG = 1 and (PT_ORIGIN<>'PO' or PT_SRV_STATUS=0) 
and (PT_INVREG_FLAG <> 1 or PT_INVREG_FLAG is null) 
and ((PT_INVREG_STATUS <> 'W' and PT_INVREG_STATUS <> 'R') or (PT_INVREG_STATUS is null))

