create view AA_PL_ALLOCATION_TRANSACTION_VIEW
/*
** Returns a table to be used specifically with AA_PL_ALLOCATION_TRANSACTION_LIST_S
** Written: 12/01/2005 SH
** Last Amended: 23/03/2005 SH; 19/05/05 SRB; 16/08/2005 SRB, 27/09/2005 SRB
**
*/

as

select PT_COPYSUPP,
	SUNAME,
	SU_MULTI_CURR,
	PT_ALOC_POINTER,
	PT_DATE,
	PT_YEAR,
	PT_DATE_PUTIN,
	PT_PERIODNUMBER,
	PT_HEADER_REF,
	PT_TRANTYPE,
	case PT_TRANTYPE
		when 'INV' then 0
		when 'CRN' then 1
		when 'PAY' then 2
		when 'ADR' then 3
		when 'ACR' then 4
	end as TRANSACTION_TYPE,
	PT_PRIMARY as [PRIMARY],
	dbo.AA_VALUE_DPS_F(PT_CURR_UNAL) as PT_CURR_UNAL,
	dbo.AA_VALUE_DPS_F(PT_CURR_VALU) as PT_CURR_VALU,
	PT_CURRENCYCODE,
	dbo.AA_VALUE_DPS_F(PT_UNALLOCATED) as PT_UNALLOCATED,
	PT_DESCRIPTION,
	dbo.AA_VALUE_DPS_F(PT_GROSS) as PT_GROSS,
	PT_YEAR + CAST(PT_PERIODNUMBER as varchar(2)) as PERIODYEAR,
	PT_QUERY_FLAG,
	PT_USRCHAR1,
	PT_USRCHAR2,
	PT_USRCHAR3,
	PT_USRCHAR4,
	PT_USRDATE1,
	PT_USRDATE2,
	PT_USRFLAG1,
	PT_USRFLAG2,
	PT_USRNUM1,
	PT_USRNUM2,
	PT_USER1,
	PT_USER2,
	PT_USER3,
	PT_SUB_LEDGER,
	PT_INTERNAL_REF

from PL_TRANSACTIONS P
	left join PL_TRANSACTIONS2 P2 on P2.PT_PRIMARY_2 = P.PT_PRIMARY
	inner join PL_ACCOUNTS S on S.SUCODE = P.PT_COPYSUPP

where P.PT_BATCH_FLAG <> 1 -- Process stored procedure filters out fully allocated lines

 
