CREATE VIEW AA_REP_POP_BATCHED_ORDERS_VIEW
/*
** Written:     16/01/2006 RV   
** Last Amended: 
** Comments: returns batched purchase orders for self audit crystal reports
*/
AS
SELECT
     
POP_DETAIL.POD_ORDER_NO, 
POP_DETAIL.POD_DATE, 
POP_DETAIL.POD_ACCOUNT, 
POP_DETAIL.POD_TYPE,                      
POP_DETAIL.POD_ORDER_REF, 
POP_DETAIL.POD_ANALYSIS, 
POP_DETAIL.POD_STOCK_CODE, 
POP_DETAIL.POD_PRICE_CODE,                       
POP_DETAIL.POD_NETT, 
POP_DETAIL.POD_ENTRY_TYPE, 
POP_DETAIL.POD_QTYORD,                      
POP_DETAIL.POD_QTYINVD, 
POP_DETAIL.POD_UNITCST,

POP_HEADER.POH_STATUS, 
POP_HEADER.POH_PRIORITY,                       
POP_HEADER.POH_BATCH_REF,
POP_HEADER.POH_YEAR,
POP_HEADER.POH_PERIOD,
POP_HEADER.POH_SUB_LEDGER,

PL_ACCOUNTS.SUNAME,

'ENGLISH   ' As LANGUAGE_LINK

FROM POP_HEADER 
	
	INNER JOIN POP_DETAIL 
	ON POP_HEADER.POH_ORDER_NUMBR = POP_DETAIL.POD_ORDER_NO 

	INNER JOIN PL_ACCOUNTS 
	ON POP_HEADER.POH_ACCOUNT = PL_ACCOUNTS.SUCODE

WHERE (POP_HEADER.POH_STATUS < 2) AND (POP_HEADER.POH_PRIORITY < 3)
