CREATE VIEW AA_REP_NOMINAL_AUDITORS_EXPORT_VIEW
/*
** Written:     06/12/2005 RV   
** Last Amended: 
** Comments: returns nominal account turnover for the nominal export report for crystal reports
*/
AS
SELECT     

NTURNOVERPTD, 
NOPENBALYEAR+NTURNOVER_C1+NTURNOVER_C2+NTURNOVER_C3+NTURNOVER_C4+NTURNOVER_C5+NTURNOVER_C6+NTURNOVER_C7+NTURNOVER_C8+NTURNOVER_C9+NTURNOVER_C10+NTURNOVER_C11+NTURNOVER_C12+NTURNOVER_C13 AS NTURNOVER_WHOLE_YEAR, 
NCODE, 
NNAME

FROM NL_ACCOUNTS

