CREATE VIEW AA_REP_PURCHASE_VAT_DETAIL_VIEW
/*
** Written:     15/12/2005 RV   
** Last Amended: 16/12/2005 RV, 09/01/2006 RV
** Comments: returns purchase transaction details for self audit crystal reports
*/
AS
SELECT     

Cast (SL_PL_NL_DETAIL.DET_BATCH_FLAG As Bit) As DET_BATCH_FLAG,
SL_PL_NL_DETAIL.DET_ACCOUNT, 
SL_PL_NL_DETAIL.DET_HEADER_REF,
SL_PL_NL_DETAIL.DET_DATE,
SL_PL_NL_DETAIL.DET_YEAR, 
SL_PL_NL_DETAIL.DET_PERIODNUMBR,    
SL_PL_NL_DETAIL.DET_DESCRIPTION, 
SL_PL_NL_DETAIL.DET_ANALYSIS,                       
SL_PL_NL_DETAIL.DET_NETT, 
SL_PL_NL_DETAIL.DET_VAT, 
SL_PL_NL_DETAIL.DET_VATCODE, 
SL_PL_NL_DETAIL.DET_GROSS, 
SL_PL_NL_DETAIL.DET_PRIMARY,
SL_PL_NL_DETAIL.DET_SUB_LEDGER,
SL_PL_NL_DETAIL.DET_TYPE,
SL_PL_NL_DETAIL.DET_ORIGIN,
SL_PL_NL_DETAIL.DET_IMPEXP_CODE,

SYS_VATCONTROL.VAT_RATE,
SYS_VATCONTROL.EC_TYPE, 

'ENGLISH   ' As LANGUAGE_LINK

                     
FROM  SL_PL_NL_DETAIL 

  INNER JOIN SYS_VATCONTROL 
  on SL_PL_NL_DETAIL.DET_VATCODE = SYS_VATCONTROL.VAT_CODE

WHERE (SL_PL_NL_DETAIL.DET_TYPE IN ('INV', 'CRN'))
	And DET_ORIGIN Like ('P%')
	And EC_TYPE <> 'A'
