CREATE VIEW AA_REP_WO_WORK_TO_LIST_VIEW

/*
** Written     :  02/03/2006 RV
** Last Amended:
**
** Used by     :  Work To List Report.rpt
*/
AS

SELECT

WO_ORDERS.WO_PARENT_ORDER_NUMBER,
WO_ORDERS.WO_QUANTITY,
WO_ORDERS.WO_END_DATE,
WO_ORDERS.WO_TOP_LEVEL_ORDER_NUMBER,
WO_ORDERS.WO_SORT_KEY,
case when WO_PARENT_ORDER_NUMBER= 0 then
   (case when WO_PRIORITY = 0 then 99
    else WO_PRIORITY
    end
   )
else 0
end as WO_PRIORITY,

STK_STOCK.STKCODE,
STK_STOCK.STKNAME,

WO_ROUTES.WR_ROUTE,
WO_STAGES.WS_TEXT,
WO_STAGE_QUANTITIES.WQ_ORDER_NUMBER,
WO_STAGE_QUANTITIES.WQ_QUANTITY,

'ENGLISH   ' As LANGUAGE_LINK

from WO_STAGE_QUANTITIES

   LEFT OUTER JOIN WO_STAGES
   ON WS_PRIMARY=WQ_STAGE_LINK

   LEFT OUTER JOIN WO_ROUTES
   ON WR_PRIMARY=WS_ROUTE_LINK

   LEFT OUTER JOIN WO_ORDERS
   ON WO_ORDER_NUMBER=WQ_ORDER_NUMBER

   LEFT OUTER JOIN STK_STOCK
   ON STK_PRIMARY=WO_STOCK_LINK


