CREATE VIEW AA_REP_WO_WRITE_OFF_ANALYSIS_VIEW

/*
** Written     :  08/03/2006 RV
** Last Amended:  15/03/2006 RV, 11/04/2006 RV, 31/05/2006 RV, 19/07/2006 RV
**
** Used by     :  Write Off Analysis Report.rpt
*/
AS

select

WC_ORDER_NUMBER,
WC_TOP_LEVEL_ORDER_NUMBER,
SM_QUANTITY_WRITTEN_OFF,
WI_QUANTITY_WRITTEN_OFF,
WC_TYPE,
WC_PART_LINK,
case  when WC_TYPE='S' then STKCODE
   when WC_TYPE='P' then PRCODE
   else 'Text Item'
end as 'StockCode',
STKCODE,

case  when WC_TYPE='S' then STKNAME
   when WC_TYPE='P' then PRNAME
   else WC_TEXT
end as 'StockName',

SM_COSTPRICE,
WI_ACTUAL_PRICE,
SM_PRIMARY,
isnull(SM_LOCATION,'') As SM_LOCATION,
SM_SERIALNUMBER,

case  when WC_TYPE='S' then pa1.PACODE
   else pa2.PACODE
end as 'Analysis',
pa1.PACODE,

case  when WC_TYPE='S' then pa1.PANOMINALDR
   else pa2.PANOMINALDR
end as 'Nominal',
pa1.PANOMINALDR,

case  when WC_TYPE='S' then ct1.CC_COPYHEADER
   else ct2.CC_COPYHEADER
end as 'Project',
ct1.CC_COPYHEADER,

case  when WC_TYPE='S' then ct1.CC_CODE
   else ct2.CC_CODE
end as 'CostCentre',
ct1.CC_CODE,

'ENGLISH   ' As LANGUAGE_LINK

from WO_COMPONENTS

   INNER JOIN WO_ORDERS
   ON WO_ORDER_NUMBER = WC_ORDER_NUMBER

   LEFT OUTER JOIN STK_STOCK
   ON STK_PRIMARY = WC_PART_LINK

   LEFT OUTER JOIN WO_COMPONENT_ISSUES
   ON WI_COMPONENT_LINK = WC_PRIMARY and isnull(WI_QUANTITY_WRITTEN_OFF,0)>0

   LEFT OUTER JOIN PRC_PRICE_RECS
   ON PR_PRIMARY = WC_PART_LINK

   LEFT OUTER JOIN STK_MOVEMENTS
   ON SM_WO_NUMBER = WC_ORDER_NUMBER and SM_STOCK_CODE = STKCODE and WC_TYPE = 'S' And isnull(SM_QUANTITY_WRITTEN_OFF,0)>0

   LEFT OUTER JOIN PL_ANALYSIS pa1
   ON pa1.PACODE = SM_ANALYSIS

   LEFT OUTER JOIN PL_ANALYSIS pa2
   ON pa2.PA_PRIMARY = WI_ANALYSIS_LINK

   LEFT OUTER JOIN CST_COSTCENTRE ct1
   ON ct1.CC_CODE = SM_COSTCENTRE and ct1.CC_COPYHEADER = SM_COSTHEADER

   LEFT OUTER JOIN CST_COSTCENTRE ct2
   ON ct2.CC_PRIMARY = WI_COSTCENTRE_LINK and ct2.CC_COPYHEADER = WI_COSTHEADER_LINK

where  (WO_STATUS = 10 or WO_STATUS = 15) and isnull(WC_QUANTITY_WRITTEN_OFF,0) > 0

