CREATE VIEW AA_REP_SL_CASH_VAT_VIEW
/*
** Written     :  21/12/2005 RV
** Last Amended:  03/01/2006 RV, 31/01/2006 RV, 25/01/2007 RV
** Comments    :  Returns sales transactions for cash VAT crystal reports
**
** Used by     :  Sales Ledger - Cash VAT Guidance Report.rpt
*/
(
PAY_ST_VAT,
PAY_ST_GROSS,
PAY_ST_UNALLOCATED,
PAY_ST_BATCH_FLAG,
PAY_ST_DATE,
PAY_ST_TRANTYPE,
PAY_ST_COPYCUST,
PAY_ST_PRIMARY,
PAY_ST_HEADER_KEY,
PAY_ST_HEADER_REF,
PAY_ST_CURRENCYCODE,
PAY_ST_CURR_VALU,
PAY_ST_CURR_UNAL,
PAY_ST_CURR_TAX,
PAY_S_AL_VALUE_HOME,
PAY_S_AL_VALUE_CURR,
PAY_S_AL_REFERENCE,
PAY_S_AL_DATE,
PAY_S_AL_YEAR,
PAY_S_AL_PERIOD,
PAY_S_AL_PRIMARY,

INV_ST_VAT,
INV_ST_GROSS,
INV_ST_UNALLOCATED,
INV_ST_BATCH_FLAG,
INV_ST_DATE,
INV_ST_TRANTYPE,
INV_ST_COPYCUST,
INV_ST_PRIMARY,
INV_ST_HEADER_KEY,
INV_ST_HEADER_REF,
INV_ST_CURRENCYCODE,
INV_ST_CURR_VALU,
INV_ST_CURR_UNAL,
INV_ST_CURR_TAX,
INV_S_AL_VALUE_HOME,
INV_S_AL_VALUE_CURR,
INV_S_AL_REFERENCE,
INV_S_AL_DATE,
INV_S_AL_YEAR,
INV_S_AL_PERIOD,
VAT_ALERT,
INV_S_AL_PRIMARY

)
As
Select
SL_PAY.ST_VAT,
SL_PAY.ST_GROSS,
SL_PAY.ST_UNALLOCATED,
SL_PAY.ST_BATCH_FLAG,
SL_PAY.ST_DATE,
SL_PAY.ST_TRANTYPE,
SL_PAY.ST_COPYCUST,
SL_PAY.ST_PRIMARY,
SL_PAY.ST_HEADER_KEY,
SL_PAY.ST_HEADER_REF,
SL_PAY.ST_CURRENCYCODE,
SL_PAY.ST_CURR_VALU,
SL_PAY.ST_CURR_UNAL,
SL_PAY.ST_CURR_TAX,
ALLOC_PAY.S_AL_VALUE_HOME,
ALLOC_PAY.S_AL_VALUE_CURR,
ALLOC_PAY.S_AL_REFERENCE,
ALLOC_PAY.S_AL_DATE,
ALLOC_PAY.S_AL_YEAR,
ALLOC_PAY.S_AL_PERIOD,
ALLOC_PAY.S_AL_PRIMARY,

'', -- INV_ST_VAT,
'', -- INV_ST_GROSS,
'', -- INV_ST_UNALLOCATED,
'', -- INV_ST_BATCH_FLAG,
'', -- INV_ST_DATE,
'', -- INV_ST_TRANTYPE,
'', -- INV_ST_COPYCUST,
'', -- INV_ST_PRIMARY,
'', -- INV_ST_HEADER_KEY,
'', -- INV_ST_HEADER_REF,
'', -- INV_ST_CURRENCYCODE,
'', -- INV_ST_CURR_VALU,
'', -- INV_ST_CURR_UNAL,
'', -- INV_ST_CURR_TAX,
'', -- INV_S_AL_VALUE_HOME,
'', -- INV_S_AL_VALUE_CURR,
'', -- INV_S_AL_REFERENCE,
'', -- INV_S_AL_DATE,
'', -- INV_S_AL_YEAR,
'', -- INV_S_AL_PERIOD,
0,
''  -- INV_S_AL_PRIMARY

FROM SL_TRANSACTIONS SL_PAY

   Inner JOIN SL_ALLOC_HISTORY ALLOC_PAY
   ON SL_PAY.ST_HEADER_KEY = ALLOC_PAY.S_AL_HEADER_KEY And (SL_PAY.ST_TRANTYPE = 'PAY'
                         And  SL_PAY.ST_BATCH_FLAG <> 1
                         And  ALLOC_PAY.S_AL_REFERENCE = 0
                         And  SL_PAY.ST_GROSS > 0)


Union all
Select
SL_PAY.ST_VAT,
SL_PAY.ST_GROSS,
SL_PAY.ST_UNALLOCATED,
SL_PAY.ST_BATCH_FLAG,
SL_PAY.ST_DATE,
SL_PAY.ST_TRANTYPE,
SL_PAY.ST_COPYCUST,
SL_PAY.ST_PRIMARY,
SL_PAY.ST_HEADER_KEY,
SL_PAY.ST_HEADER_REF,
SL_PAY.ST_CURRENCYCODE,
SL_PAY.ST_CURR_VALU,
SL_PAY.ST_CURR_UNAL,
SL_PAY.ST_CURR_TAX,
ALLOC_PAY.S_AL_VALUE_HOME,
ALLOC_PAY.S_AL_VALUE_CURR,
ALLOC_PAY.S_AL_REFERENCE,
ALLOC_PAY.S_AL_DATE,
ALLOC_PAY.S_AL_YEAR,
ALLOC_PAY.S_AL_PERIOD,
ALLOC_PAY.S_AL_PRIMARY,

SL_INV.ST_VAT,
SL_INV.ST_GROSS,
SL_INV.ST_UNALLOCATED,
SL_INV.ST_BATCH_FLAG,
SL_INV.ST_DATE,
Isnull(SL_INV.ST_TRANTYPE,''),
SL_INV.ST_COPYCUST,
SL_INV.ST_PRIMARY,
SL_INV.ST_HEADER_KEY,
SL_INV.ST_HEADER_REF,
SL_INV.ST_CURRENCYCODE,
SL_INV.ST_CURR_VALU,
SL_INV.ST_CURR_UNAL,
SL_INV.ST_CURR_TAX,
ALLOC_INV.S_AL_VALUE_HOME,
ALLOC_INV.S_AL_VALUE_CURR,
ALLOC_INV.S_AL_REFERENCE,
ALLOC_INV.S_AL_DATE,
ALLOC_INV.S_AL_YEAR,
ALLOC_INV.S_AL_PERIOD,
isnull((select top 1 1 from SL_PL_NL_DETAIL where SL_INV.ST_HEADER_KEY = DET_HEADER_KEY and DET_VATCODE in ('10', '11', '12')),0),
ALLOC_INV.S_AL_PRIMARY

FROM SL_TRANSACTIONS SL_PAY


   Inner JOIN SL_ALLOC_HISTORY ALLOC_PAY
   ON SL_PAY.ST_HEADER_KEY = ALLOC_PAY.S_AL_HEADER_KEY And (SL_PAY.ST_TRANTYPE = 'PAY'
                         And  SL_PAY.ST_BATCH_FLAG <> 1
                         And  ALLOC_PAY.S_AL_REFERENCE <> 0
                         And  SL_PAY.ST_GROSS > 0)

   Inner Join SL_ALLOC_HISTORY ALLOC_INV
   On ALLOC_PAY.S_AL_REFERENCE = ALLOC_INV.S_AL_REFERENCE And (ALLOC_INV.S_AL_ACCOUNT_CODE = ALLOC_PAY.S_AL_ACCOUNT_CODE)
                            And ALLOC_INV.S_AL_REFERENCE <> 0
                            And SL_PAY.ST_UNALLOCATED <> SL_PAY.ST_GROSS

   Inner Join SL_TRANSACTIONS SL_INV
   ON (SL_INV.ST_HEADER_KEY = ALLOC_INV.S_AL_HEADER_KEY And SL_INV.ST_TRANTYPE Not In ('PAY','ADR','ACR')) Or
      (SL_INV.ST_HEADER_KEY = ALLOC_INV.S_AL_HEADER_KEY And SL_INV.ST_TRANTYPE = 'PAY' And SL_INV.ST_GROSS <= 0)



