CREATE VIEW dbo.AA_REP_CUSTOMER_DETAIL_NOTES_VIEW
/*
** Written:     24/02/2005 RV   
** Last Amended: 28/02/05 RV Added date inv and paid fields
** Comments: returns sales ledger customer record details with notes for crystal reports
*/
AS
SELECT     
AA_REP_CUSTOMER_DETAIL_VIEW.*, 
SL_ACCOUNTS.CU_USER_PUTIN AS CU_USER_PUTIN, 
SL_ACCOUNTS.CU_DATE_PUTIN AS CU_DATE_PUTIN, 
SL_ACCOUNTS.CU_DATE_EDITED AS CU_DATE_EDITED, 
SL_ACCOUNTS.CU_USER_EDITED AS CU_USER_EDITED,
SL_ACCOUNTS.CU_DATE_INV AS CU_DATE_INV,
SL_ACCOUNTS.CU_DATE_PAY AS CU_DATE_PAY, 
SL_ACCOUNTS.CU_NOTES AS CU_NOTES

FROM AA_REP_CUSTOMER_DETAIL_VIEW 
	
  INNER JOIN SL_ACCOUNTS 
  ON AA_REP_CUSTOMER_DETAIL_VIEW.CU_PRIMARY = SL_ACCOUNTS.CU_PRIMARY
