CREATE VIEW AA_REP_SALES_VAT_DETAIL_VIEW
/*
** Written:     16/12/2005 RV   
** Last Amended: 09/01/2006 RV
** Comments: returns sales transaction details for self audit crystal reports
*/
AS

SELECT     

DET_DATE, 
DET_ACCOUNT, 
DET_HEADER_REF, 
DET_TYPE, 
DET_NETT, 
DET_VAT, 
DET_PRIMARY, 
DET_BATCH_FLAG, 
DET_YEAR,                      
DET_PERIODNUMBR, 
DET_DESCRIPTION, 
DET_ANALYSIS, 
DET_ORIGIN,

SYS_VATCONTROL.VAT_RATE, 

'ENGLISH   ' As LANGUAGE_LINK

FROM  SL_PL_NL_DETAIL

	INNER JOIN SYS_VATCONTROL 
	On SL_PL_NL_DETAIL.DET_VATCODE = SYS_VATCONTROL.VAT_CODE

WHERE DET_ORIGIN like 'S%' And DET_TYPE In ('CRN', 'INV') 