create view AA_REP_NL_REVALUE_ACCOUNTS_VIEW
as
select
   NL_ACCOUNTS.NCODE
,  NL_ACCOUNTS.NTYPE
,  NL_ACCOUNTS.NCURRENCYCODE
,  NL_ACCOUNTS.NMAJORHEADCODE
,  NL_ACCOUNTS.NBALANCE
,  NL_ACCOUNTS.NBALANCE_C

from
   NL_ACCOUNTS
      inner join SYS_DATAINFO on SYS_PRIMARY = 1
where
   HOME_CURR_SYMBL <> NCURRENCYCODE
