create view AA_REP_NOMINAL_LANG_VIEW
/*
** Written     :  06/10/2005 RV
** Last Amended:  10/10/2005 RV, 07/04/2006 RV
** Comments    :  Returns all language labels for dimensions nominal transactions crystal reports
**
** Used by     :  Input Tax by Nominal Code.rpt
**                Large Input Tax Transactions.rpt
**                NL Cash VAT Guidance Report.rpt
**                Non Cash VAT Transactions Report.rpt
*/
as
select

SYS_DATAINFO.COMPANY_NAME,
SYS_DATAINFO.COMP_VATNUMBER,
SYS_DATAINFO.HOME_TAXNAME,
SYS_DATAINFO.NOMINAL_PERIOD,

LANG_REPORTS_R.UNALLOCATED_REP,
LANG_REPORTS_R.TOTALFOR_REP,
LANG_REPORTS_R.LANGCODE_REP_1,
LANG_REPORTS_R.REGNO_ABBREV_REP,
LANG_REPORTS_R.KEY_TXT_REP,
LANG_REPORTS_R.LEDGER_REP,
LANG_REPORTS_R.NOMINAL_REP,
LANG_REPORTS_R.INVOICE_REP,
LANG_REPORTS_R.CREDIT_NOTE_REP,

LANG_REPORTS_R3.VAT_RETURN,
LANG_REPORTS_R3.OUTPUTS_TEXT,
LANG_REPORTS_R3.EXCLUDING_TEXT,
LANG_REPORTS_R3.INPUTS_TEXT,
LANG_REPORTS_R3.ON_OUTPUTS,
LANG_REPORTS_R3.ON_INPUTS,

LANG_REPORTS_R4.ACCOUNT_REP,
LANG_REPORTS_R4.AUDIT_NO_REP,
LANG_REPORTS_R4.BALANCE_REP,
LANG_REPORTS_R4.DATE_TEXT_REP,
LANG_REPORTS_R4.DESCRIPTION_REP,
LANG_REPORTS_R4.CUSTOMER_CODE_REP,
LANG_REPORTS_R4.GROSS_REP,
LANG_REPORTS_R4.NET_REP,
LANG_REPORTS_R4.REFERENCE_REP,
LANG_REPORTS_R4.REF_REP,
LANG_REPORTS_R4.PURCHASE_REP,
LANG_REPORTS_R4.SOP_ORDER_REP,
LANG_REPORTS_R4.NL_JOURNALS_REP,
LANG_REPORTS_R4.PERIOD_REP,
LANG_REPORTS_R4.RECORDS_REP,
LANG_REPORTS_R4.RATE_REP,
LANG_REPORTS_R4.ANALYSISTEXT_REP,

LANG_REPORTS_R5.TRANSACTIONS_TEXT_REP,
LANG_REPORTS_R5.TYPE_REP,

LANG_REPORTS_R6.NOMINAL_NAME_REP

FROM  LANG_REPORTS_R5

INNER JOIN LANG_REPORTS_R3 ON
LANG_REPORTS_R5.LANGCODE_REP5 = LANG_REPORTS_R3.LANGCODE_REP3

INNER JOIN LANG_REPORTS_R4 ON
LANG_REPORTS_R5.LANGCODE_REP5 = LANG_REPORTS_R4.LANGCODE_REP4

INNER JOIN LANG_REPORTS_R ON
LANG_REPORTS_R4.LANGCODE_REP4 = LANG_REPORTS_R.LANGCODE_REP_1

INNER JOIN LANG_REPORTS_R6 ON
LANG_REPORTS_R4.LANGCODE_REP4 = LANG_REPORTS_R6.LANGCODE_REP6

Inner join SYS_DATAINFO on SYS_PRIMARY = 1