CREATE VIEW AA_REP_OUTSTANDING_SALES_TRANS_VIEW
/*
** Written     :  06/10/2005 RV
** Last Amended:
** Comments    :  Returns all outstanding posted sales transactions for crystal reports
**
** Used by     :  Customer Debts Over 6 Months Old.rpt
*/
AS
SELECT DISTINCT
SL_ACCOUNTS.CUCODE,
SL_ACCOUNTS.CUNAME,
SL_ACCOUNTS.CUSORT,

SL_TRANSACTIONS.ST_DATE,
SL_TRANSACTIONS.ST_YEAR,
SL_TRANSACTIONS.ST_PERIODNUMBER,
SL_TRANSACTIONS.ST_TRANTYPE,
SL_TRANSACTIONS.ST_HEADER_REF,
SL_TRANSACTIONS.ST_NETT,
SL_TRANSACTIONS.ST_VAT,
SL_TRANSACTIONS.ST_GROSS,
SL_TRANSACTIONS.ST_PRIMARY,
CAST (SL_TRANSACTIONS.ST_BATCH_FLAG AS BIT) AS ST_BATCH_FLAG,
SL_TRANSACTIONS.ST_UNALLOCATED,
SL_TRANSACTIONS.ST_ALOC_POINTER,
CAST (SL_TRANSACTIONS.ST_QUERY_FLAG AS BIT) AS ST_QUERY_FLAG,
CAST (SL_TRANSACTIONS.ST_DONOTCHASE AS BIT) AS ST_DONOTCHASE,
SL_TRANSACTIONS.ST_SUB_LEDGER,

SL_ACCOUNTS2.CU_LEVEL,
'ENGLISH' As LANGUAGE_LINK,   --used to link to language view for Dimensions ACR's.

SYS_TAX_AUDIT.TAXAUDIT_REF

FROM SL_ACCOUNTS

  INNER JOIN SL_TRANSACTIONS
  ON SL_ACCOUNTS.CUCODE = SL_TRANSACTIONS.ST_COPYCUST

  INNER JOIN SL_ACCOUNTS2
  ON SL_ACCOUNTS.CU_PRIMARY = SL_ACCOUNTS2.CU_PRIMARY_2

  INNER JOIN SL_PL_NL_DETAIL
  ON SL_TRANSACTIONS.ST_HEADER_KEY = SL_PL_NL_DETAIL.DET_HEADER_KEY

  LEFT OUTER JOIN SYS_TAX_AUDIT
  ON SL_PL_NL_DETAIL.DET_VAT_RETURN_PRIMARY = SYS_TAX_AUDIT.TAXAUDIT_PRIMARY

WHERE SL_TRANSACTIONS.ST_UNALLOCATED <> 0.00
   And SL_PL_NL_DETAIL.DET_TYPE = 'INV'
   And ST_BATCH_FLAG = 0