CREATE VIEW AA_REP_SALES_ANALYSIS_VIEW
/*
** Written:     08/03/2005 RV   
** Last Amended: 22/02/05 RV, 29/03/05 RV, 27/10/05 RV. 
** Comments: returns sales analysis records (by analysis code including budget by revision) for crystal reports
*/
AS
SELECT     
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.REVISION, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O1,                      
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O2, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O3,                      
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O4, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O5,                       
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O6, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O7,                      
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O8, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O9,                       
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O10, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O11,                       
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O12, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_O13,                       
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L1, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L2,                      
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L3, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L4,                       
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L5, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L6,                      
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L7, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L8,                       
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L9, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L10,                       
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L11, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L12,                       
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_L13, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C1,                      
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C2, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C3,                      
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C4, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C5,                       
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C6, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C7,                      
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C8, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C9,                      
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C10, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C11,                       
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C12, 
AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.BUD_C13, 

isnull( M.MAX_REVISION, 0 ) as MAX_REVISION,

SL_ANALYSIS.SACODE,                      
SL_ANALYSIS.SANAME, 
SL_ANALYSIS.SATYPE_S_B_D, 
SL_ANALYSIS.SATURNOVERYTD, 
SL_ANALYSIS.SATURNOVERPTD,                       
SL_ANALYSIS.SATURNOVR_YTD_C, 
SL_ANALYSIS.SATURNOVR_PTD_C, 
SL_ANALYSIS.SASORT, 
SL_ANALYSIS.SAUSER1,                       
SL_ANALYSIS.SAUSER2, 
SL_ANALYSIS.SAUSER3, 
SL_ANALYSIS.SATURNOVR_L1, 
SL_ANALYSIS.SATURNOVR_L2,                       
SL_ANALYSIS.SATURNOVR_L3, 
SL_ANALYSIS.SATURNOVR_L4, 
SL_ANALYSIS.SATURNOVR_L5, 
SL_ANALYSIS.SATURNOVR_L6,                       
SL_ANALYSIS.SATURNOVR_L7, 
SL_ANALYSIS.SATURNOVR_L8, 
SL_ANALYSIS.SATURNOVR_L9, 
SL_ANALYSIS.SATURNOVR_L10,                       
SL_ANALYSIS.SATURNOVR_L11, 
SL_ANALYSIS.SATURNOVR_L12, 
SL_ANALYSIS.SATURNOVR_L13, 
SL_ANALYSIS.SATURNOVR_C1,                       
SL_ANALYSIS.SATURNOVR_C2, 
SL_ANALYSIS.SATURNOVR_C3, 
SL_ANALYSIS.SATURNOVR_C4, 
SL_ANALYSIS.SATURNOVR_C5,                       
SL_ANALYSIS.SATURNOVR_C6, 
SL_ANALYSIS.SATURNOVR_C7, 
SL_ANALYSIS.SATURNOVR_C8, 
SL_ANALYSIS.SATURNOVR_C9,                       
SL_ANALYSIS.SATURNOVR_C10, 
SL_ANALYSIS.SATURNOVR_C11, 
SL_ANALYSIS.SATURNOVR_C12, 
SL_ANALYSIS.SATURNOVR_C13, 
SL_ANALYSIS.SATURNOVR_O1, 
SL_ANALYSIS.SATURNOVR_O2, 
SL_ANALYSIS.SATURNOVR_O3,
SL_ANALYSIS.SATURNOVR_O4, 
SL_ANALYSIS.SATURNOVR_O5, 
SL_ANALYSIS.SATURNOVR_O6, 
SL_ANALYSIS.SATURNOVR_O7,                       
SL_ANALYSIS.SATURNOVR_O8, 
SL_ANALYSIS.SATURNOVR_O9, 
SL_ANALYSIS.SATURNOVR_O10, 
SL_ANALYSIS.SATURNOVR_O11,                       
SL_ANALYSIS.SATURNOVR_O12, 
SL_ANALYSIS.SATURNOVR_O13, 
SL_ANALYSIS.SATURNOVR_L1_C,                      
SL_ANALYSIS.SATURNOVR_L2_C, 
SL_ANALYSIS.SATURNOVR_L3_C, 
SL_ANALYSIS.SATURNOVR_L4_C,                       
SL_ANALYSIS.SATURNOVR_L5_C, 
SL_ANALYSIS.SATURNOVR_L6_C, 
SL_ANALYSIS.SATURNOVR_L7_C,                       
SL_ANALYSIS.SATURNOVR_L8_C, 
SL_ANALYSIS.SATURNOVR_L9_C, 
SL_ANALYSIS.SATURNOVR_L10_C,                       
SL_ANALYSIS.SATURNOVR_L11_C, 
SL_ANALYSIS.SATURNOVR_L12_C, 
SL_ANALYSIS.SATURNOVR_L13_C,                       
SL_ANALYSIS.SATURNOVR_C1_C, 
SL_ANALYSIS.SATURNOVR_C2_C, 
SL_ANALYSIS.SATURNOVR_C3_C,                       
SL_ANALYSIS.SATURNOVR_C4_C, 
SL_ANALYSIS.SATURNOVR_C5_C, 
SL_ANALYSIS.SATURNOVR_C6_C,                      
SL_ANALYSIS.SATURNOVR_C7_C, 
SL_ANALYSIS.SATURNOVR_C8_C, 
SL_ANALYSIS.SATURNOVR_C9_C,                       
SL_ANALYSIS.SATURNOVR_C10_C, 
SL_ANALYSIS.SATURNOVR_C11_C, 
SL_ANALYSIS.SATURNOVR_C12_C,                      
SL_ANALYSIS.SATURNOVR_C13_C, 
SL_ANALYSIS.SATURNOVR_O1_C, 
SL_ANALYSIS.SATURNOVR_O2_C,                       
SL_ANALYSIS.SATURNOVR_O3_C, 
SL_ANALYSIS.SATURNOVR_O4_C, 
SL_ANALYSIS.SATURNOVR_O5_C,                       
SL_ANALYSIS.SATURNOVR_O6_C, 
SL_ANALYSIS.SATURNOVR_O7_C, 
SL_ANALYSIS.SATURNOVR_O8_C,                       
SL_ANALYSIS.SATURNOVR_O9_C, 
SL_ANALYSIS.SATURNOVR_O10_C, 
SL_ANALYSIS.SATURNOVR_O11_C,                      
SL_ANALYSIS.SATURNOVR_O12_C, 
SL_ANALYSIS.SATURNOVR_O13_C, 
SL_ANALYSIS.SANOTES, 
SL_ANALYSIS.SA_USER_EDITED,                       
SL_ANALYSIS.SA_USER_PUTIN, 
SL_ANALYSIS.SA_DATE_PUTIN, 
SL_ANALYSIS.SA_DATE_EDITED,                      
SL_ANALYSIS.SACURRENCYSYMBL, 
SL_ANALYSIS.SANOMINALDR, 
SL_ANALYSIS.SANOMINALCR, 
SL_ANALYSIS.SANOMINALVAT,                      
SL_ANALYSIS.SAVATCODE, 
SL_ANALYSIS.SA_LEVEL, 
CAST (isnull(SL_ANALYSIS.SADEFAULT_BANK,0) AS BIT) AS SADEFAULT_BANK, 
CAST (isnull(SL_ANALYSIS.SADEFAULT_SALES,0) AS BIT) AS SADEFAULT_SALES,                       
CAST (isnull(SL_ANALYSIS.SA_FORCE_COSTING,0) AS BIT) AS SA_FORCE_COSTING, 
CAST (isnull(SL_ANALYSIS.SA_ANALYSIS_MATRIX,0) AS BIT) AS SA_ANALYSIS_MATRIX,
SL_ANALYSIS.SA_PRIMARY,
 
SL_ANALYSIS2.SA_USRCHAR1,                       
SL_ANALYSIS2.SA_USRCHAR2,
SL_ANALYSIS2.SA_USRCHAR3, 
SL_ANALYSIS2.SA_USRCHAR4,  
SL_ANALYSIS2.SA_USRCHAR5, 
SL_ANALYSIS2.SA_USRCHAR6, 
SL_ANALYSIS2.SA_USRCHAR7,                      
SL_ANALYSIS2.SA_USRCHAR8, 
SL_ANALYSIS2.SA_USRNUM1, 
SL_ANALYSIS2.SA_USRNUM2, 
SL_ANALYSIS2.SA_USRNUM3,                       
SL_ANALYSIS2.SA_USRDATE1, 
SL_ANALYSIS2.SA_USRDATE2, 
SL_ANALYSIS2.SA_USRDATE3, 
CAST (isnull(SL_ANALYSIS2.SA_USRFLAG1,0) AS BIT) AS SA_USRFLAG1,                      
CAST (isnull(SL_ANALYSIS2.SA_USRFLAG2,0) AS BIT) AS SA_USRFLAG2, 
CAST (isnull(SL_ANALYSIS2.SA_USRFLAG3,0) AS BIT) AS SA_USRFLAG3,

SYS_VATCONTROL.VAT_RATE, 

NL_DR.NNAME AS DR_NAME,
                  
NL_CR.NNAME AS CR_NAME, 

NL_VAT.NNAME AS VAT_NAME
 
FROM SL_ANALYSIS

  INNER JOIN NL_ACCOUNTS NL_DR
  ON SL_ANALYSIS.SANOMINALDR = NL_DR.NCODE  

  INNER JOIN NL_ACCOUNTS NL_CR
  ON SL_ANALYSIS.SANOMINALCR = NL_CR.NCODE

  LEFT OUTER JOIN NL_ACCOUNTS NL_VAT
  ON SL_ANALYSIS.SANOMINALVAT = NL_VAT.NCODE

  LEFT OUTER JOIN SYS_VATCONTROL 
  ON SL_ANALYSIS.SAVATCODE = SYS_VATCONTROL.VAT_CODE

  LEFT OUTER JOIN SL_ANALYSIS2 
  ON SL_ANALYSIS.SA_PRIMARY = SL_ANALYSIS2.SA_PRIMARY_2

  LEFT OUTER JOIN AA_REP_SALES_ANALYSIS_BUDGETS_VIEW
  ON SL_ANALYSIS.SACODE = AA_REP_SALES_ANALYSIS_BUDGETS_VIEW.ANALYSIS

  LEFT join ( select B_ACCOUNT_CODE, max( B_REVISION_NUMBER ) as MAX_REVISION -- Obtain maximum revision number for account
						from SYS_BUDGETS
						where B_RECORD_TYPE = 'SA' and B_BUDGET_TYPE = 'B'
						group by B_ACCOUNT_CODE
					) M on M.B_ACCOUNT_CODE = SL_ANALYSIS.SACODE



