CREATE VIEW AA_REP_CUSTOMER_ADDRESSES_VIEW
/*
** Written:     24/02/2005 RV   
** Last Amended: 28/02/2005 RV added sort fields. 28/02/2005 RV added country name. 
**               02/03/2005 RV filtered out prospects. 03/03/2005 added customer balance.
**		 10/03/2005 RV added credit limit. 22/03/05 RV. 29/03/05 RV
** Comments: returns sales ledger customer address details for crystal reports
*/
AS
SELECT     
SL_ACCOUNTS.CUCODE, 
SL_ACCOUNTS.CUNAME, 
CAST (SL_ACCOUNTS.CU_ON_STOP AS BIT) AS CU_ON_STOP,
SL_ACCOUNTS.CUSORT,
SL_ACCOUNTS.CUUSER1,
SL_ACCOUNTS.CUUSER2,
SL_ACCOUNTS.CUUSER3,
SL_ACCOUNTS.CUBALANCE,
SL_ACCOUNTS.CUTURNOVERYTD,
SL_ACCOUNTS.CUCURRENCYCODE,
SL_ACCOUNTS.CU_CREDIT_LIMIT, 
SL_ADDRESSES.AD_CODE, 
SL_ADDRESSES.AD_ADDRESS, 
SL_ADDRESSES.AD_ADDRESS_USER1, 
SL_ADDRESSES.AD_ADDRESS_USER2, 
SL_ADDRESSES.AD_POSTCODE, 
SL_ADDRESSES.AD_COUNTRY, 
CAST (SL_ADDRESSES.AD_INV_ADDRESS AS BIT) AS AD_INV_ADDRESS, 
CAST (SL_ADDRESSES.AD_DEL_ADDRESS AS BIT) AS AD_DEL_ADDRESS, 
CAST (SL_ADDRESSES.AD_STAT_ADDRESS AS BIT) AS AD_STAT_ADDRESS, 
CAST (SL_ADDRESSES.AD_DEL_ADDRESS_2 AS BIT) AS AD_DEL_ADDRESS_2, 
SL_ADDRESSES.AD_ACCOUNTNAME, 
CAST (SL_ADDRESSES.AD_DO_NOT_USE AS BIT) AS AD_DO_NOT_USE, 
SL_ADDRESSES.AD_CONTACT, 
SL_ADDRESSES.AD_CON_TITLE, 
SL_ADDRESSES.AD_CON_INITIALS, 
SL_ADDRESSES.AD_CON_JOB, 
SL_ADDRESSES.AD_CON_FNAME,
SL_ADDRESSES.AD_CON_SURNAME, 
SL_ADDRESSES.AD_CONT_SALUTE, 
SL_ADDRESSES.AD_PHONE, 
SL_ADDRESSES.AD_E_MAIL, 
SL_ADDRESSES.AD_FAX, 
SL_ADDRESSES.AD_CC_EMAIL, 
SL_ADDRESSES.AD_MOBILE, 
SL_ADDRESSES.AD_ANALYSIS, 
SL_ADDRESSES.AD_NOTE, 
SL_ADDRESSES.AD_USER_EDITED, 
SL_ADDRESSES.AD_USER_PUTIN, 
SL_ADDRESSES.AD_DATE_PUTIN, 
SL_ADDRESSES.AD_DATE_EDITED, 
SL_ADDRESSES2.AD_USRCHAR1, 
SL_ADDRESSES2.AD_USRCHAR2,
SL_ADDRESSES2.AD_USRCHAR3,
SL_ADDRESSES2.AD_USRCHAR4, 
SL_ADDRESSES2.AD_USRCHAR5, 
SL_ADDRESSES2.AD_USRCHAR6, 
SL_ADDRESSES2.AD_USRCHAR7, 
SL_ADDRESSES2.AD_USRCHAR8, 
CAST (SL_ADDRESSES2.AD_USRFLAG1 AS BIT) AS AD_USRFLAG1, 
CAST (SL_ADDRESSES2.AD_USRFLAG2 AS BIT) AS AD_USRFLAG2, 
CAST (SL_ADDRESSES2.AD_USRFLAG3 AS BIT) AS AD_USRFLAG3, 
SL_ADDRESSES2.AD_USRDATE1, 
SL_ADDRESSES2.AD_USRDATE2, 
SL_ADDRESSES2.AD_USRDATE3, 
SL_ADDRESSES2.AD_USRNUM1, 
SL_ADDRESSES2.AD_USRNUM2, 
SL_ADDRESSES2.AD_USRNUM3, 
SL_ANALYSIS.SANAME,
SL_ADDRESSES.AD_BRANCH_ID, 
SL_ADDRESSES.AD_EXPORT_CODE, 
SL_ADDRESSES.AD_COUNTRY_CODE, 
SL_ADDRESSES.AD_VAT_REG_NO, 
SL_ADDRESSES.AD_EC_DELIVERY, 
SL_ADDRESSES.AD_EC_T_NATURE, 
SL_ADDRESSES.AD_EC_T_MODE,
SYS_COUNTRY.CO_NAME,
SYS_CURRENCY.CURR_SYMBOL

FROM SL_ACCOUNTS 

INNER JOIN SL_ADDRESSES 
ON SL_ACCOUNTS.CUCODE = SL_ADDRESSES.AD_ACC_CODE

INNER JOIN SL_ADDRESSES2 
ON SL_ADDRESSES.SL_AD_PRIMARY = SL_ADDRESSES2.AD_PRIMARY_2

LEFT OUTER JOIN SL_ANALYSIS
ON SL_ANALYSIS.SACODE = SL_ADDRESSES.AD_ANALYSIS

LEFT OUTER JOIN SYS_COUNTRY 
ON SL_ADDRESSES.AD_COUNTRY_CODE = SYS_COUNTRY.CO_CODE

inner join SYS_CURRENCY on SYS_CURRENCY.CURR_CODE = SL_ACCOUNTS.CUCURRENCYCODE

WHERE CUCODE IS NOT NULL AND CUCODE <> ''