CREATE VIEW AA_REP_SALES_TRAN_UPDATE_VIEW
/*
** Written:     10/03/2005 RV   
** Last Amended: 29/03/05 RV. 25/05/05 RV.
** Comments: returns selected sales transaction headers for Audit/NTP crystal reports
*/
AS
SELECT     

SL_TRANSACTIONS.ST_COPYCUST,
SL_TRANSACTIONS.ST_DATE, 
SL_TRANSACTIONS.ST_YEAR, 
SL_TRANSACTIONS.ST_PERIODNUMBER, 
SL_TRANSACTIONS.ST_TRANTYPE, 
SL_TRANSACTIONS.ST_HEADER_REF, 
SL_TRANSACTIONS.ST_NETT, 
SL_TRANSACTIONS.ST_VAT, 
SL_TRANSACTIONS.ST_GROSS, 
SL_TRANSACTIONS.ST_PRIMARY, 
CAST (SL_TRANSACTIONS.ST_BATCH_FLAG AS BIT) AS ST_BATCH_FLAG, 
SL_TRANSACTIONS.ST_UNALLOCATED, 
CAST (SL_TRANSACTIONS.ST_QUERY_FLAG AS BIT) AS ST_QUERY_FLAG, 
SL_TRANSACTIONS.ST_CURRENCYCODE, 
SL_TRANSACTIONS.ST_CURRENCYRATE, 
SL_TRANSACTIONS.ST_CURR_VALU, 
SL_TRANSACTIONS.ST_TRI_RATE1, 
SL_TRANSACTIONS.ST_TRI_RATE2, 
SL_TRANSACTIONS.ST_CURR_TYPE, 
SL_TRANSACTIONS.ST_CURR_UNAL, 
SL_TRANSACTIONS.ST_CURR_NETT, 
SL_TRANSACTIONS.ST_CURR_TAX, 
SL_TRANSACTIONS.ST_CURRENCYRTCH, 
SL_TRANSACTIONS.ST_TRI_RATECHNG2,
SL_TRANSACTIONS.ST_BATCH_POSTED,                       

SL_ACCOUNTS2.CU_LEVEL

FROM SL_TRANSACTIONS 

  INNER JOIN SL_ACCOUNTS 
  ON SL_TRANSACTIONS.ST_COPYCUST = SL_ACCOUNTS.CUCODE

  INNER JOIN SL_ACCOUNTS2 
  ON SL_ACCOUNTS.CU_PRIMARY = SL_ACCOUNTS2.CU_PRIMARY_2