CREATE VIEW AA_REP_NOMINAL_TURNOVER_VIEW
/*
** Written:     02/06/2005 RV
** Last Amended: 20/04/2006 SB, 11/09/2006 SB, 11/09/2006 RV
** Comments: returns all turnover and budget revisions for crystal reports
*/
as
select
-- Display Fields
   NL_ACCOUNTS.NCODE
,  NL_ACCOUNTS.NNAME
,  NL_ACCOUNTS.NBALANCE
,  NL_ACCOUNTS.NTURNOVERYTD
,  NL_ACCOUNTS.NCURRENCYCODE

,  NL_ACCOUNTS.NCATEGORYCODE1
,  NL_ACCOUNTS.NCATEGORYCODE2
,  NL_ACCOUNTS.NCATEGORYCODE3
,  NL_ACCOUNTS.NCATEGORYCODE4
,  NL_ACCOUNTS.NCATEGORYCODE5
,  NL_ACCOUNTS.NCATEGORYCODE6
,  NL_ACCOUNTS.NCATEGORYCODE7
,  NL_ACCOUNTS.NCATEGORYCODE8

,  NL_ACCOUNTS.NMAJORHEADCODE

,  NL_ACCOUNTS.NOPENBALANCELY
,  NL_ACCOUNTS.NTURNOVER_L1
,  NL_ACCOUNTS.NTURNOVER_L2
,  NL_ACCOUNTS.NTURNOVER_L3
,  NL_ACCOUNTS.NTURNOVER_L4
,  NL_ACCOUNTS.NTURNOVER_L5
,  NL_ACCOUNTS.NTURNOVER_L6
,  NL_ACCOUNTS.NTURNOVER_L7
,  NL_ACCOUNTS.NTURNOVER_L8
,  NL_ACCOUNTS.NTURNOVER_L9
,  NL_ACCOUNTS.NTURNOVER_L10
,  NL_ACCOUNTS.NTURNOVER_L11
,  NL_ACCOUNTS.NTURNOVER_L12
,  NL_ACCOUNTS.NTURNOVER_L13

,  NL_ACCOUNTS.NOPENBALYEAR
,  NL_ACCOUNTS.NTURNOVER_C1
,  NL_ACCOUNTS.NTURNOVER_C2
,  NL_ACCOUNTS.NTURNOVER_C3
,  NL_ACCOUNTS.NTURNOVER_C4
,  NL_ACCOUNTS.NTURNOVER_C5
,  NL_ACCOUNTS.NTURNOVER_C6
,  NL_ACCOUNTS.NTURNOVER_C7
,  NL_ACCOUNTS.NTURNOVER_C8
,  NL_ACCOUNTS.NTURNOVER_C9
,  NL_ACCOUNTS.NTURNOVER_C10
,  NL_ACCOUNTS.NTURNOVER_C11
,  NL_ACCOUNTS.NTURNOVER_C12
,  NL_ACCOUNTS.NTURNOVER_C13

,  NL_ACCOUNTS.NTURNOVER_N1
,  NL_ACCOUNTS.NTURNOVER_N2
,  NL_ACCOUNTS.NTURNOVER_N3
,  NL_ACCOUNTS.NTURNOVER_N4
,  NL_ACCOUNTS.NTURNOVER_N5
,  NL_ACCOUNTS.NTURNOVER_N6
,  NL_ACCOUNTS.NTURNOVER_N7
,  NL_ACCOUNTS.NTURNOVER_N8
,  NL_ACCOUNTS.NTURNOVER_N9
,  NL_ACCOUNTS.NTURNOVER_N10
,  NL_ACCOUNTS.NTURNOVER_N11
,  NL_ACCOUNTS.NTURNOVER_N12
,  NL_ACCOUNTS.NTURNOVER_N13

,  NL_ACCOUNTS.NOPENBALANCLY_C
,  NL_ACCOUNTS.NTURNOVER_L1_C
,  NL_ACCOUNTS.NTURNOVER_L2_C
,  NL_ACCOUNTS.NTURNOVER_L3_C
,  NL_ACCOUNTS.NTURNOVER_L4_C
,  NL_ACCOUNTS.NTURNOVER_L5_C
,  NL_ACCOUNTS.NTURNOVER_L6_C
,  NL_ACCOUNTS.NTURNOVER_L7_C
,  NL_ACCOUNTS.NTURNOVER_L8_C
,  NL_ACCOUNTS.NTURNOVER_L9_C
,  NL_ACCOUNTS.NTURNOVER_L10_C
,  NL_ACCOUNTS.NTURNOVER_L11_C
,  NL_ACCOUNTS.NTURNOVER_L12_C
,  NL_ACCOUNTS.NTURNOVER_L13_C

,  NL_ACCOUNTS.NOPENBALYR_C
,  NL_ACCOUNTS.NTURNOVER_C1_C
,  NL_ACCOUNTS.NTURNOVER_C2_C
,  NL_ACCOUNTS.NTURNOVER_C3_C
,  NL_ACCOUNTS.NTURNOVER_C4_C
,  NL_ACCOUNTS.NTURNOVER_C5_C
,  NL_ACCOUNTS.NTURNOVER_C6_C
,  NL_ACCOUNTS.NTURNOVER_C7_C
,  NL_ACCOUNTS.NTURNOVER_C8_C
,  NL_ACCOUNTS.NTURNOVER_C9_C
,  NL_ACCOUNTS.NTURNOVER_C10_C
,  NL_ACCOUNTS.NTURNOVER_C11_C
,  NL_ACCOUNTS.NTURNOVER_C12_C
,  NL_ACCOUNTS.NTURNOVER_C13_C

,  NL_ACCOUNTS.NTURNOVER_N1_C
,  NL_ACCOUNTS.NTURNOVER_N2_C
,  NL_ACCOUNTS.NTURNOVER_N3_C
,  NL_ACCOUNTS.NTURNOVER_N4_C
,  NL_ACCOUNTS.NTURNOVER_N5_C
,  NL_ACCOUNTS.NTURNOVER_N6_C
,  NL_ACCOUNTS.NTURNOVER_N7_C
,  NL_ACCOUNTS.NTURNOVER_N8_C
,  NL_ACCOUNTS.NTURNOVER_N9_C
,  NL_ACCOUNTS.NTURNOVER_N10_C
,  NL_ACCOUNTS.NTURNOVER_N11_C
,  NL_ACCOUNTS.NTURNOVER_N12_C
,  NL_ACCOUNTS.NTURNOVER_N13_C

,  NL_ACCOUNTS2.N_USRDATE1
,  NL_ACCOUNTS2.N_USRDATE2
,  NL_ACCOUNTS2.N_USRDATE3
,  NL_ACCOUNTS2.N_USRCHAR1
,  NL_ACCOUNTS2.N_USRCHAR2
,  NL_ACCOUNTS2.N_USRCHAR5
,  NL_ACCOUNTS2.N_USRCHAR6
,  NL_ACCOUNTS2.N_USRCHAR7
,  NL_ACCOUNTS2.N_USRCHAR8
,  NL_ACCOUNTS2.N_USRNUM1
,  NL_ACCOUNTS2.N_USRNUM2
,  NL_ACCOUNTS2.N_USRNUM3
,  NL_ACCOUNTS2.N_LEVEL

,  AA_REP_NOMINAL_BUDGETS_VIEW.REVISION

,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L1
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L2
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L3
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L4
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L5
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L6
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L7
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L8
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L9
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L10
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L11
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L12
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L13

,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C1
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C2
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C3
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C4
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C5
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C6
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C7
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C8
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C9
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C10
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C11
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C12
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C13

,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N1
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N2
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N3
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N4
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N5
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N6
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N7
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N8
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N9
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N10
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N11
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N12
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N13

,  isnull( M.MAX_REVISION, 0 ) as MAX_REVISION
from NL_ACCOUNTS

   left outer join AA_REP_NOMINAL_BUDGETS_VIEW
   on NL_ACCOUNTS.NCODE = AA_REP_NOMINAL_BUDGETS_VIEW.NOMINAL

   inner join NL_ACCOUNTS2
   on NL_ACCOUNTS.N_PRIMARY = NL_ACCOUNTS2.N_PRIMARY_2

   left join ( select B_ACCOUNT_CODE, max( B_REVISION_NUMBER ) as MAX_REVISION -- Obtain maximum revision number for account
                  from SYS_BUDGETS
                  where B_RECORD_TYPE = 'N' and B_BUDGET_TYPE = 'B'
                  group by B_ACCOUNT_CODE
               ) M on M.B_ACCOUNT_CODE = NL_ACCOUNTS.NCODE

where NL_ACCOUNTS.NCODE is not null and NL_ACCOUNTS.NCODE <> ''
