CREATE VIEW AA_REP_WO_KIT_ACTION_LIST_VIEW

/*
** Written     :  02/03/2006 RV
** Last Amended:  15/03/2006 RV
**
** Used by     :  Kit Action List Report.rpt
*/
AS

select
WC_TYPE,
Cast (WC_LABOUR As Bit) As WC_LABOUR,
WC_ORDER_NUMBER,
WC_TOP_LEVEL_ORDER_NUMBER,
WC_QUANTITY_REQUIRED,
WC_QUANTITY_ALLOC,
WC_QUANTITY_ISSUED,
WC_PART_LINK,
WC_TEXT,
WO_PARENT_ORDER_NUMBER,
WO_END_DATE,
case when WO_PARENT_ORDER_NUMBER= 0 then
   (case when WO_PRIORITY = 0 then 99
    else WO_PRIORITY
    end
   )
     else 0
end as WO_PRIORITY,

case when WC_TYPE='S' then STKCODE
     when WC_TYPE='P' then PRCODE
     else 'Text Item'
end as 'StockCode',

case when WC_TYPE='S' then STKNAME
     when WC_TYPE='P' then PRNAME
     else WC_TEXT
end as 'StockName',

isnull(STK_ASSEMBLY,'') As STK_ASSEMBLY,
STK_SORT_KEY,
STK_PHYSICAL,
STK_RESERVE_OUT,
STK_BACK_ORDER_QTY,
STK_WO_ALLOC_QUANTITY,
STK_WO_UNALLOC_QUANTITY,
STK_ORDER_IN,
STK_WO_FREE_WIP_QUANTITY,
STK_WO_WIP_SOP_QUANTITY,
case when STK_MULTILOCATN <> 1 then
   case when STK_USR_QTY = 'P' Then STK_PHYSICAL
   else case when STK_FREE_METHOD = 'P' Then
         (STK_PHYSICAL-(STK_RESERVE_OUT+STK_BACK_ORDER_QTY)+STK_ORDER_IN)
           when STK_FREE_METHOD = 'F' Then
         (STK_PHYSICAL-(STK_RESERVE_OUT+STK_BACK_ORDER_QTY))
        when STK_FREE_METHOD = 'O' Then
         (STK_PHYSICAL-STK_RESERVE_OUT+STK_ORDER_IN)
        when STK_FREE_METHOD = 'A' Then
         (STK_PHYSICAL-STK_RESERVE_OUT)
        end
   end

     when STK_MULTILOCATN = 1 then
   case when STK_USR_QTY = 'P' Then LOC_PHYSICAL
   else case when STK_FREE_METHOD = 'P' Then
         (LOC_PHYSICAL-(LOC_RESERVE_OUT+LOC_BACK_ORDER_QTY)+LOC_ORDER_IN)
             when STK_FREE_METHOD = 'F' Then
         (LOC_PHYSICAL-(LOC_RESERVE_OUT+LOC_BACK_ORDER_QTY))
        when STK_FREE_METHOD = 'O' Then
         (LOC_PHYSICAL-LOC_RESERVE_OUT+LOC_ORDER_IN)
        when STK_FREE_METHOD = 'A' Then
         (LOC_PHYSICAL-LOC_RESERVE_OUT)
        end
   end

end STOCK_FREE,

WR_ROUTE,

SYS_DATAINFO.STK_USR_QTY,
SYS_DATAINFO2.STK_FREE_METHOD,
'ENGLISH   ' As LANGUAGE_LINK

from WO_COMPONENTS

   LEFT OUTER JOIN WO_ORDERS
   ON WO_ORDER_NUMBER=WC_ORDER_NUMBER

   LEFT OUTER JOIN STK_STOCK
   ON STK_PRIMARY=WC_PART_LINK

   LEFT OUTER JOIN WO_ROUTES
   ON WR_PRIMARY=WO_ROUTE_LINK

   LEFT OUTER JOIN PRC_PRICE_RECS
   ON PR_PRIMARY=WC_PART_LINK

   Left outer join STK_LOCATION
   On WO_SUB_ANALYSIS_LINK = LOC_PRIMARY

   Join SYS_DATAINFO ON SYS_PRIMARY = 1
   Join SYS_DATAINFO2 ON SYS_PRIMARY_2 = 1
