CREATE VIEW AA_REP_SUPPLIER_DETAIL_NOTES_VIEW
/*
** Written:     12/04/2005 RV   
** Last Amended: 22/04/05 RV
** Comments: returns purchase ledger supplier record details with notes for crystal reports
*/
AS
SELECT     
AA_REP_SUPPLIER_DETAIL_VIEW.*, 
PL_ACCOUNTS.SU_USER_PUTIN AS SU_USER_PUTIN, 
PL_ACCOUNTS.SU_DATE_PUTIN AS SU_DATE_PUTIN, 
PL_ACCOUNTS.SU_USER_EDITED AS SU_USER_EDITED,
PL_ACCOUNTS.SU_USER_EDITED AS SU_DATE_EDITED,
PL_ACCOUNTS.SU_DATE_INV AS SU_DATE_INV,
PL_ACCOUNTS.SU_DATE_PAY AS SU_DATE_PAY, 
PL_ACCOUNTS.SU_NOTES AS SU_NOTES

FROM AA_REP_SUPPLIER_DETAIL_VIEW 
	
  INNER JOIN PL_ACCOUNTS 
  ON AA_REP_SUPPLIER_DETAIL_VIEW.SU_PRIMARY = PL_ACCOUNTS.SU_PRIMARY
