CREATE VIEW AA_REP_SUPPLIER_ADDRESSES_VIEW
/*
** Written:     12/04/2005 RV   
** Last Amended: 
** Comments: returns purchase ledger supplier address details for crystal reports
*/
AS
SELECT     
PL_ACCOUNTS.SUCODE, 
PL_ACCOUNTS.SUNAME, 
CAST (PL_ACCOUNTS.SU_ON_STOP AS BIT) AS SU_ON_STOP,
PL_ACCOUNTS.SUSORT,
PL_ACCOUNTS.SUUSER1,
PL_ACCOUNTS.SUUSER2,
PL_ACCOUNTS.SUUSER3,
PL_ACCOUNTS.SUBALANCE,
PL_ACCOUNTS.SUTURNOVERYTD,
PL_ACCOUNTS.SUCURRENCYCODE,
PL_ACCOUNTS.SU_CREDIT_LIMIT, 
PL_ADDRESSES.PL_AD_CODE, 
PL_ADDRESSES.PL_AD_ADDRESS, 
PL_ADDRESSES.PL_AD_ADDRESS_USER1, 
PL_ADDRESSES.PL_AD_ADDRESS_USER2, 
PL_ADDRESSES.PL_AD_POSTCODE, 
PL_ADDRESSES.PL_AD_COUNTRY, 
CAST (PL_ADDRESSES.PL_AD_INV_ADD AS BIT) AS PL_AD_INV_ADD, 
CAST (PL_ADDRESSES.PL_AD_DEL_ADD AS BIT) AS PL_AD_DEL_ADD, 
CAST (PL_ADDRESSES.PL_AD_STAT_ADD AS BIT) AS PL_AD_STAT_ADD, 
CAST (PL_ADDRESSES.PL_AD_REM_ADD AS BIT) AS PL_AD_REM_ADD,
CAST (PL_ADDRESSES.PL_AD_DEL_ADDRESS_2 AS BIT) AS PL_AD_DEL_ADDRESS_2,
CAST (PL_ADDRESSES.PL_AD_DO_NOT_USE AS BIT) AS PL_AD_DO_NOT_USE, 
PL_ADDRESSES.PL_AD_CONTACT, 
PL_ADDRESSES.PL_AD_CON_TITLE, 
PL_ADDRESSES.PL_AD_CON_INITS, 
PL_ADDRESSES.PL_AD_CON_JOB, 
PL_ADDRESSES.PL_AD_CON_FNAME,
PL_ADDRESSES.PL_AD_CON_SNAME, 
PL_ADDRESSES.PL_AD_CONT_SAL, 
PL_ADDRESSES.PL_AD_PHONE, 
PL_ADDRESSES.PL_AD_EMAIL, 
PL_ADDRESSES.PL_AD_FAX, 
PL_ADDRESSES.PL_AD_CC_EMAIL, 
PL_ADDRESSES.PL_AD_MOBILE, 
PL_ADDRESSES.PL_AD_ANALYSIS, 
PL_ADDRESSES.PL_AD_NOTE, 
PL_ADDRESSES.PL_AD_USER_EDITED, 
PL_ADDRESSES.PL_AD_USER_PUTIN, 
PL_ADDRESSES.PL_AD_DATE_PUTIN, 
PL_ADDRESSES.PL_AD_DATE_EDITED, 
PL_ADDRESSES.PL_AD_USRCHAR1, 
PL_ADDRESSES.PL_AD_USRCHAR2,
PL_ADDRESSES.PL_AD_USRCHAR3,
PL_ADDRESSES.PL_AD_USRCHAR4, 
PL_ADDRESSES.PL_AD_USRCHAR5, 
PL_ADDRESSES.PL_AD_USRCHAR6, 
PL_ADDRESSES.PL_AD_USRCHAR7, 
PL_ADDRESSES.PL_AD_USRCHAR8, 
CAST (PL_ADDRESSES.PL_AD_USRFLAG1 AS BIT) AS PL_AD_USRFLAG1, 
CAST (PL_ADDRESSES.PL_AD_USRFLAG2 AS BIT) AS PL_AD_USRFLAG2, 
CAST (PL_ADDRESSES.PL_AD_USRFLAG3 AS BIT) AS PL_AD_USRFLAG3, 
PL_ADDRESSES.PL_AD_USRDATE1, 
PL_ADDRESSES.PL_AD_USRDATE2, 
PL_ADDRESSES.PL_AD_USRDATE3, 
PL_ADDRESSES.PL_AD_USRNUM1, 
PL_ADDRESSES.PL_AD_USRNUM2, 
PL_ADDRESSES.PL_AD_USRNUM3, 
PL_ANALYSIS.PANAME,
SYS_CURRENCY.CURR_SYMBOL

FROM PL_ACCOUNTS 

INNER JOIN PL_ADDRESSES 
ON PL_ACCOUNTS.SUCODE = PL_ADDRESSES.PL_AD_ACCCODE

inner join SYS_CURRENCY on SYS_CURRENCY.CURR_CODE = PL_ACCOUNTS.SUCURRENCYCODE

LEFT OUTER JOIN PL_ANALYSIS
ON PL_ANALYSIS.PACODE = PL_ADDRESSES.PL_AD_ANALYSIS

WHERE SUCODE IS NOT NULL AND SUCODE <> ''