CREATE VIEW AA_REP_CRM_ORDER_WIP_VIEW
AS

SELECT

Case  When ORD_HEADER.OH_PRIORITY = 4
   Then ORD_HEADER.OH_DATE

   When ORD_HEADER.OH_PRIORITY = 0
   Then ORD_HEADER.OH_DATE

end As GroupDate,

Case  When ORD_HEADER.OH_PRIORITY = 4
   Then ORD_HEADER.OH_ACCOUNT_ORDER

   When ORD_HEADER.OH_PRIORITY = 0
   Then ORD_HEADER.OH_ACCOUNT

end As CUSTOMER_CODE,

Case  When ORD_HEADER.OH_PRIORITY = 4
   Then 'Estimate'

   When ORD_HEADER.OH_PRIORITY = 0
   Then 'Live'

end As STATUS,

isnull(ORD_HEADER.OH_ORDER_NUMBER,'') As OH_ORDER_NUMBER,
ORD_HEADER.OH_NETT,
ORD_HEADER.OH_CUSORT,
ORD_HEADER.OH_USER1,
ORD_HEADER.OH_USER2,
ORD_HEADER.OH_USER3,
ORD_HEADER.OH_EQ_STATUS,
ORD_HEADER.OH_DATE,
ORD_HEADER.OH_STATUS,
ORD_HEADER.OH_PRIORITY,
ORD_HEADER.OH_USER_PUTIN,
ORD_HEADER.OH_DATE_PUTIN,
ORD_HEADER.OH_EST_DATE,


isnull(SL_TRANSACTIONS.ST_NETT,0) As ST_NETT,
isnull(SL_TRANSACTIONS.ST_PRIMARY,0) As ST_PRIMARY,
SL_TRANSACTIONS.ST_DATE,

CRM_CAMPAIGN.CMP_CODE,
CRM_CAMPAIGN.CMP_DESCRIPTION,
'ENGLISH   ' As LANGUAGE_LINK

FROM ORD_HEADER

   LEFT OUTER JOIN SL_TRANSACTIONS
   ON ORD_HEADER.OH_ORDER_NUMBER = SL_TRANSACTIONS.ST_ORDER_NUMBER and month(OH_DATE) = month(ST_DATE) and year(OH_DATE) = year(ST_DATE)

   LEFT OUTER JOIN CRM_CAMPAIGN
   ON ORD_HEADER.OH_CAMPAIGN_LINK = CRM_CAMPAIGN.CMP_PRIMARY

WHERE ORD_HEADER.OH_PRIORITY = 4 Or (ORD_HEADER.OH_PRIORITY = 0 And ORD_HEADER.OH_EQ_STATUS in ('E','Q'))

Union all
select

Case  When ORD_HEADER.OH_STATUS = 2
   Then SL_TRANSACTIONS.ST_DATE

   When ORD_HEADER.OH_LINES_INVD > 0
   Then SL_TRANSACTIONS.ST_DATE

end As GroupDate,

Case  When ORD_HEADER.OH_PRIORITY = 0
   Then ORD_HEADER.OH_ACCOUNT

end As CUSTOMER_CODE,

Case  When ORD_HEADER.OH_PRIORITY = 0
   Then 'Live'

end As STATUS,

isnull(ORD_HEADER.OH_ORDER_NUMBER,'') As OH_ORDER_NUMBER,
ORD_HEADER.OH_NETT,
ORD_HEADER.OH_CUSORT,
ORD_HEADER.OH_USER1,
ORD_HEADER.OH_USER2,
ORD_HEADER.OH_USER3,
ORD_HEADER.OH_EQ_STATUS,
ORD_HEADER.OH_DATE,
ORD_HEADER.OH_STATUS,
ORD_HEADER.OH_PRIORITY,
ORD_HEADER.OH_USER_PUTIN,
ORD_HEADER.OH_DATE_PUTIN,
ORD_HEADER.OH_EST_DATE,

isnull(SL_TRANSACTIONS.ST_NETT,0) As ST_NETT,
isnull(SL_TRANSACTIONS.ST_PRIMARY,0) As ST_PRIMARY,
SL_TRANSACTIONS.ST_DATE,

CRM_CAMPAIGN.CMP_CODE,
CRM_CAMPAIGN.CMP_DESCRIPTION,

'ENGLISH   ' As LANGUAGE_LINK

FROM ORD_HEADER

   LEFT OUTER JOIN SL_TRANSACTIONS
   ON ORD_HEADER.OH_ORDER_NUMBER = SL_TRANSACTIONS.ST_ORDER_NUMBER

   LEFT OUTER JOIN CRM_CAMPAIGN
   ON ORD_HEADER.OH_CAMPAIGN_LINK = CRM_CAMPAIGN.CMP_PRIMARY

WHERE ORD_HEADER.OH_PRIORITY = 0 And ORD_HEADER.OH_STATUS > 0 And ORD_HEADER.OH_EQ_STATUS in ('E','Q')







