CREATE VIEW AA_REP_WO_USED_IN_WORKS_ORDERS_VIEW

/*
** Written     :  01/03/2006 RV
** Last Amended:  02/03/2006 RV, 11/04/2006 RV
**
** Used by     :  Used in Works Orders Report.rpt
*/
AS

SELECT

STK_STOCK.STKCODE,
STK_STOCK.STKNAME,
STK_STOCK.STK_PRIMARY,

WO_COMPONENTS.WC_ORDER_NUMBER,
WO_COMPONENTS.WC_QUANTITY_REQUIRED,
WO_COMPONENTS.WC_QUANTITY_ISSUED,
WO_COMPONENTS.WC_TYPE,

WO_ORDERS.WO_STATUS,
WO_ORDERS.WO_CURRENT_STAGE,
WO_ORDERS.WO_ROUTE_LINK,
WO_ORDERS.WO_ORDER_NUMBER,

WO_ROUTES.WR_ROUTE,
WO_ROUTES.WR_PRIMARY,

WO_STAGES.WS_TEXT,
WO_STAGES.WS_PRIMARY,
WO_STAGES.WS_ROUTE_LINK,

'ENGLISH   ' As LANGUAGE_LINK

FROM WO_COMPONENTS

   Left OUTER JOIN WO_ORDERS
   ON WO_COMPONENTS.WC_ORDER_NUMBER = WO_ORDERS.WO_ORDER_NUMBER

   Inner Join WO_ROUTES
   On WO_ROUTES.WR_PRIMARY = WO_ORDERS.WO_ROUTE_LINK

   Inner JOIN STK_STOCK
   ON WO_COMPONENTS.WC_PART_LINK = STK_STOCK.STK_PRIMARY

   Inner JOIN WO_STAGES
   ON WO_ORDERS.WO_ROUTE_LINK = WO_STAGES.WS_ROUTE_LINK and WO_ROUTES.WR_PRIMARY = WO_STAGES.WS_ROUTE_LINK

   Inner Join WO_STAGE_QUANTITIES
   ON WO_STAGE_QUANTITIES.WQ_STAGE_LINK = WO_STAGES.WS_PRIMARY And WO_STAGE_QUANTITIES.WQ_ORDER_NUMBER = WO_COMPONENTS.WC_ORDER_NUMBER

WHERE (WO_ORDERS.WO_STATUS = 5) AND (WO_COMPONENTS.WC_TYPE = 'S')
