create view AA_REP_SL_STATEMENTS_SEARCH_VIEW

/*
** Written     :  02/08/2005 DB
** Last Amended:  08/08/2005 DB, 13/04/2006 RV, 24/1/06 NC
** Comments    :  Returns selected sales transactions for statement reports
*/

as

select top 100 percent
   SL_ACCOUNTS.CUCODE
,  SL_ACCOUNTS.CUBALANCE
,  SL_ACCOUNTS.CUTURNOVERYTD
,  SL_ACCOUNTS.CUSORT
,  SL_ACCOUNTS.CUUSER1
,  SL_ACCOUNTS.CUUSER2
,  SL_ACCOUNTS.CUUSER3
,  SL_ACCOUNTS.CU_DATE_INV
,  SL_ACCOUNTS.CUCURRENCYCODE
,  SL_ACCOUNTS.CU_CREDIT_LIMIT
,  SL_ACCOUNTS.CU_ON_STOP
,  SL_ACCOUNTS2.CU_HEAD_OFFICE_CODE
,  SL_TRANSACTIONS.ST_PRIMARY
,  SL_TRANSACTIONS.ST_UNALLOCATED
,  SL_TRANSACTIONS.ST_CURRENCYCODE
,  SL_TRANSACTIONS.ST_DUEDATE
,  SL_TRANSACTIONS.ST_ALOC_POINTER
,  SL_TRANSACTIONS.ST_PERIODNUMBER
,  SL_TRANSACTIONS.ST_YEAR
,  SL_TRANSACTIONS.ST_DATE
,  SL_TRANSACTIONS.ST_HEADER_KEY
,  SL_TRANSACTIONS.ST_ALLOC_PERIOD
,  SL_TRANSACTIONS.ST_ALLOC_YEAR
   from
      SL_ACCOUNTS with (nolock)
            inner join SL_TRANSACTIONS on SL_TRANSACTIONS.ST_COPYCUST   = SL_ACCOUNTS.CUCODE
            inner join SL_ACCOUNTS2 with (nolock) on SL_ACCOUNTS2.CU_PRIMARY_2     = SL_ACCOUNTS.CU_PRIMARY
   where
      isnull(CUCODE,'') <> '' and isnull(ST_BATCH_FLAG,0)<>1
   order by
      SL_ACCOUNTS.CUCODE
   ,  ST_DATE
   ,  SL_TRANSACTIONS.ST_PRIMARY