CREATE VIEW AA_REP_CONTROL_NON_VAT_JNLS_VIEW
/*
** Written:     10/01/2006 RV   
** Last Amended: 
** Comments: returns non VAT journal lines posted to VAT control account for self audit crystal reports
*/
AS
SELECT     

DET_DATE, 
DET_NOM_YEAR, 
DET_NOM_PERIOD, 
DET_HEADER_REF, 
DET_TYPE, 
DET_NETT, 
DET_DESCRIPTION,
SL_PL_NL_DETAIL.DET_NOMINALDR,
SL_PL_NL_DETAIL.DET_NOMINALCR, 
DET_PRIMARY,                       
Cast (DET_BATCH_FLAG As Bit) As DET_BATCH_FLAG,
DET_USER_PUTIN,

SYS_DATAINFO.NOM_VAT_CNTRL,
'ENGLISH   ' As LANGUAGE_LINK

FROM SL_PL_NL_DETAIL

	Join SYS_DATAINFO On SYS_PRIMARY =1

WHERE (SL_PL_NL_DETAIL.DET_NOMINALDR = SYS_DATAINFO.NOM_VAT_CNTRL Or 
       SL_PL_NL_DETAIL.DET_NOMINALCR = SYS_DATAINFO.NOM_VAT_CNTRL) And
       DET_BATCH_FLAG <> 1 And 
       DET_TYPE = 'JNL'