CREATE VIEW AA_REP_SALES_VAT_ANALYSIS_VIEW
/*
** Written     :  12/10/2005 RV
** Last Amended:  14/10/2005, 04/03/2011 CC
** Comments    :  Returns sales transactions with non zero net values for self audit crystal reports
**
** Used by     :  Zero Rated Sales Report.rpt
*/
AS
SELECT

SL_PL_NL_DETAIL.DET_DATE,
SL_PL_NL_DETAIL.DET_YEAR,
SL_PL_NL_DETAIL.DET_PERIODNUMBR,
SL_PL_NL_DETAIL.DET_ANALYSIS,
SL_PL_NL_DETAIL.DET_NETT,
SL_PL_NL_DETAIL.DET_VAT,
SL_PL_NL_DETAIL.DET_DESCRIPTION,
SL_PL_NL_DETAIL.DET_PRIMARY,
SL_PL_NL_DETAIL.DET_VATCODE,
SL_PL_NL_DETAIL.DET_LEDGER,
SL_PL_NL_DETAIL.DET_ORIGIN,
SL_PL_NL_DETAIL.DET_ORDER_LINK,

Case  When DET_ORIGIN = 'SO' Then D2.AD_EXPORT_CODE
   When DET_ORIGIN = 'S' Then SL_ADDRESSES.AD_EXPORT_CODE
   Else SL_ADDRESSES.AD_EXPORT_CODE
End   As EXPORT_CODE,

Case  When DET_ORIGIN = 'SO' Then D2.AD_VAT_REG_NO
   When DET_ORIGIN = 'S' Then SL_ADDRESSES.AD_VAT_REG_NO
   Else SL_ADDRESSES.AD_VAT_REG_NO
End   As VAT_REG_NO,

Case  When DET_ORIGIN = 'SO' Then D2.AD_ADDRESS
   When DET_ORIGIN = 'S' Then SL_ADDRESSES.AD_ADDRESS
   Else SL_ADDRESSES.AD_ADDRESS
End   As ADDRESS,

SL_TRANSACTIONS.ST_HEADER_REF,
SL_TRANSACTIONS.ST_TRANTYPE,
SL_TRANSACTIONS.ST_COPYCUST,

SL_ACCOUNTS.CU_DEL_ADD_CDE,

ORD_HEADER.OH_INV_ADD,
ORD_HEADER.OH_DEL_ADD,
ORD_HEADER.OH_ACCOUNT_ORDER,
ORD_HEADER.OH_ACCOUNT_DELIVERY,

'ENGLISH   ' AS LANGUAGE_LINK,
Case DET_VAT_RATE When NULL then SYS_VATCONTROL.VAT_RATE
   Else SL_PL_NL_DETAIL.DET_VAT_RATE
End as DET_VAT_RATE

FROM SL_TRANSACTIONS

   INNER JOIN SL_PL_NL_DETAIL
   ON SL_PL_NL_DETAIL.DET_HEADER_KEY = SL_TRANSACTIONS.ST_HEADER_KEY And ST_TRANTYPE in ('INV','CRN')

   INNER JOIN SL_ACCOUNTS
   ON SL_TRANSACTIONS.ST_COPYCUST = SL_ACCOUNTS.CUCODE

   INNER JOIN SL_ADDRESSES
   ON SL_ACCOUNTS.CUCODE = SL_ADDRESSES.AD_ACC_CODE AND SL_ACCOUNTS.CU_DEL_ADD_CDE = SL_ADDRESSES.AD_CODE

   LEFT OUTER JOIN ORD_DETAIL
   ON ORD_DETAIL.OD_PRIMARY = SL_PL_NL_DETAIL.DET_ORDER_LINK and SL_PL_NL_DETAIL.DET_ORIGIN = 'SO'

   LEFT OUTER JOIN ORD_HEADER
   ON ORD_HEADER.OH_ORDER_NUMBER = ORD_DETAIL.OD_ORDER_NUMBER

   LEFT OUTER JOIN SL_ACCOUNTS D1
   ON ORD_HEADER.OH_ACCOUNT_DELIVERY = D1.CUCODE

   LEFT OUTER JOIN SL_ADDRESSES D2
   ON D1.CUCODE = D2.AD_ACC_CODE and ORD_HEADER.OH_DEL_ADD = D2.AD_CODE
   
   INNER JOIN SYS_VATCONTROL 
   ON SYS_VATCONTROL.VAT_CODE = SL_PL_NL_DETAIL.DET_VATCODE

WHERE     (SL_PL_NL_DETAIL.DET_NETT <> 0.00)

