CREATE VIEW AA_REP_PURCHASE_TRAN_UPDATE_VIEW
/*
** Written:     13/04/2005 RV   
** Last Amended: 26/04/05 RV. 25/05/05 RV.
** Comments: returns selected purchase transaction headers for Audit/NTP crystal reports
*/
AS
SELECT     

PL_TRANSACTIONS.PT_COPYSUPP,
PL_TRANSACTIONS.PT_DATE, 
PL_TRANSACTIONS.PT_YEAR, 
PL_TRANSACTIONS.PT_PERIODNUMBER, 
PL_TRANSACTIONS.PT_TRANTYPE, 
PL_TRANSACTIONS.PT_HEADER_REF, 
PL_TRANSACTIONS.PT_NETT, 
PL_TRANSACTIONS.PT_VAT, 
PL_TRANSACTIONS.PT_GROSS, 
PL_TRANSACTIONS.PT_PRIMARY, 
PL_TRANSACTIONS.PT_INTERNAL_REF,
CAST (PL_TRANSACTIONS.PT_BATCH_FLAG AS BIT) AS PT_BATCH_FLAG, 
PL_TRANSACTIONS.PT_UNALLOCATED, 
CAST (PL_TRANSACTIONS.PT_QUERY_FLAG AS BIT) AS PT_QUERY_FLAG, 
PL_TRANSACTIONS.PT_CURRENCYCODE, 
PL_TRANSACTIONS.PT_CURRENCYRATE, 
PL_TRANSACTIONS.PT_CURR_VALU, 
PL_TRANSACTIONS.PT_TRI_RATE1, 
PL_TRANSACTIONS.PT_TRI_RATE2, 
PL_TRANSACTIONS.PT_CURR_TYPE, 
PL_TRANSACTIONS.PT_CURR_UNAL, 
PL_TRANSACTIONS.PT_CURR_NETT, 
PL_TRANSACTIONS.PT_CURR_TAX, 
PL_TRANSACTIONS.PT_CURRENCYRTCH, 
PL_TRANSACTIONS.PT_TRI_RATECHNG2,
PL_TRANSACTIONS.PT_BATCH_POSTED,                       
PL_TRANSACTIONS.PT_ACQUISTN_TAX,

PL_ACCOUNTS2.SU_LEVEL

FROM PL_TRANSACTIONS 

   INNER JOIN PL_ACCOUNTS 
  ON PL_TRANSACTIONS.PT_COPYSUPP = PL_ACCOUNTS.SUCODE

  INNER JOIN PL_ACCOUNTS2 
  ON PL_ACCOUNTS.SU_PRIMARY = PL_ACCOUNTS2.SU_PRIMARY_2
