CREATE VIEW AA_REP_SALES_ALLOCATIONS_VIEW
/*
** Written:     15/08/2005 RV   
** Last Amended: 
** Comments: returns selected sales transaction headers with allocations crystal reports
*/
AS
SELECT     

SL_TRANSACTIONS.ST_TRANTYPE, 
SL_TRANSACTIONS.ST_DATE, 
SL_TRANSACTIONS.ST_GROSS,                       
CAST (SL_TRANSACTIONS.ST_BATCH_FLAG AS BIT) AS ST_BATCH_FLAG, 
SL_TRANSACTIONS.ST_COPYCUST, 
SL_TRANSACTIONS.ST_PRIMARY,                       
SL_TRANSACTIONS.ST_HEADER_KEY,                       
SL_TRANSACTIONS.ST_YEAR, 
SL_TRANSACTIONS.ST_PERIODNUMBER,
SL_TRANSACTIONS.ST_CURR_VALU, 
SL_TRANSACTIONS.ST_CURRENCYCODE,                      
SL_TRANSACTIONS.ST_ALOC_POINTER, 
SL_TRANSACTIONS.ST_UNALLOCATED, 
SL_TRANSACTIONS.ST_CURR_UNAL,
 
SL_ALLOC_HISTORY.S_AL_DATE,                       
SL_ALLOC_HISTORY.S_AL_YEAR, 
SL_ALLOC_HISTORY.S_AL_PERIOD, 
SL_ALLOC_HISTORY.S_AL_FULLALLOC_PD,                       
SL_ALLOC_HISTORY.S_AL_FULLALLOC_DATE,
SL_ALLOC_HISTORY.S_AL_USER_ID,
SL_ALLOC_HISTORY.S_AL_PRIMARY, 
SL_ALLOC_HISTORY.S_AL_VALUE_HOME,                       
SL_ALLOC_HISTORY.S_AL_REFERENCE, 
SL_ALLOC_HISTORY.S_AL_VALUE_CURR, 
SL_ALLOC_HISTORY.S_AL_HEADER_KEY, 

SL_ACCOUNTS.CUNAME


FROM         SL_TRANSACTIONS 

		INNER JOIN SL_ALLOC_HISTORY 
		ON SL_TRANSACTIONS.ST_HEADER_KEY = SL_ALLOC_HISTORY.S_AL_HEADER_KEY

		INNER JOIN SL_ACCOUNTS
		ON SL_TRANSACTIONS.ST_COPYCUST = SL_ACCOUNTS.CUCODE

WHERE     (SL_TRANSACTIONS.ST_BATCH_FLAG <> 1)

