CREATE VIEW AA_REP_PURCHASE_TRAN_DETAIL_VIEW
/*
** Written:     12/04/2005 RV   
** Last Amended: 21/04/05 RV. 12/05/05 RV.
** Comments: returns all purchase transaction details for crystal reports
*/
AS
SELECT     
PL_TRANSACTIONS.PT_COPYSUPP, 
PL_TRANSACTIONS.PT_DATE, 
PL_TRANSACTIONS.PT_YEAR, 
PL_TRANSACTIONS.PT_PERIODNUMBER, 
PL_TRANSACTIONS.PT_HEADER_REF,                       
PL_TRANSACTIONS.PT_NETT,
PL_TRANSACTIONS.PT_VAT, 
PL_TRANSACTIONS.PT_GROSS, 
PL_TRANSACTIONS.PT_PRIMARY, 
CAST (PL_TRANSACTIONS.PT_BATCH_FLAG AS BIT) AS PT_BATCH_FLAG, 
PL_TRANSACTIONS.PT_UNALLOCATED, 
PL_TRANSACTIONS.PT_ALOC_POINTER, 
CAST (PL_TRANSACTIONS.PT_QUERY_FLAG AS BIT) AS PT_QUERY_FLAG, 
CAST (PL_TRANSACTIONS.PT_DONOTCHASE AS BIT) AS PT_DONOTCHASE, 
PL_TRANSACTIONS.PT_BATCH_REF, 
PL_TRANSACTIONS.PT_CURRENCYRATE, 
PL_TRANSACTIONS.PT_CURR_TYPE, 
PL_TRANSACTIONS.PT_USER1, 
PL_TRANSACTIONS.PT_USER2, 
PL_TRANSACTIONS.PT_USER3, 
CAST (PL_TRANSACTIONS.PT_CENTRALISED AS BIT) AS PT_CENTRALISED,
PL_TRANSACTIONS.PT_HEADER_KEY, 
PL_TRANSACTIONS.PT_INTERNAL_REF,
PL_TRANSACTIONS.PT_ACQUISTN_TAX,

PL_ACCOUNTS.SUSORT,   
        
SL_PL_NL_DETAIL.DET_DESCRIPTION, 
SL_PL_NL_DETAIL.DET_STOCK_CODE, 
SL_PL_NL_DETAIL.DET_ANALYSIS,                       
SL_PL_NL_DETAIL.DET_NOMINALDR, 
SL_PL_NL_DETAIL.DET_NOMINALCR, 
SL_PL_NL_DETAIL.DET_NOMINALVAT,                       
SL_PL_NL_DETAIL.DET_CURR_CODE, 
SL_PL_NL_DETAIL.DET_CURR_RATE, 
SL_PL_NL_DETAIL.DET_CURR_NETT, 
SL_PL_NL_DETAIL.DET_CURR_TAX, 
SL_PL_NL_DETAIL.DET_CURR_GROSS, 
SL_PL_NL_DETAIL.DET_TRI_RATE1, 
SL_PL_NL_DETAIL.DET_TRI_RATE2, 
SL_PL_NL_DETAIL.DET_CURR_L_DISC, 
SL_PL_NL_DETAIL.DET_CURR_T_DISC, 
SL_PL_NL_DETAIL.DET_NETT_BASE2, 
SL_PL_NL_DETAIL.DET_VAT_BASE2, 
SL_PL_NL_DETAIL.DET_GROSS_BASE2, 
SL_PL_NL_DETAIL.DET_L_DISC_BASE2, 
SL_PL_NL_DETAIL.DET_T_DISC_BASE2, 
SL_PL_NL_DETAIL.DET_BASE2_RATE, 
SL_PL_NL_DETAIL.DET_CURR_RTEFLG, 
SL_PL_NL_DETAIL.DET_TRI_RATECHNG2, 
SL_PL_NL_DETAIL.DET_NETT, 
SL_PL_NL_DETAIL.DET_VAT, 
SL_PL_NL_DETAIL.DET_VATCODE, 
SL_PL_NL_DETAIL.DET_GROSS, 
SL_PL_NL_DETAIL.DET_PRIMARY,
SL_PL_NL_DETAIL.DET_L_DISCOUNT, 
SL_PL_NL_DETAIL.DET_T_DISCOUNT, 
SL_PL_NL_DETAIL.DET_DIMENSION1,
SL_PL_NL_DETAIL.DET_DIMENSION2, 
SL_PL_NL_DETAIL.DET_DIMENSION3, 
SL_PL_NL_DETAIL.DET_SUB_LEDGER,
SL_PL_NL_DETAIL.DET_TYPE,
SL_PL_NL_DETAIL.DET_PL_ACQ_TAX,
SL_PL_NL_DETAIL.DET_PL_ACQUISTN_BASE2,

PL_ANALYSIS.PACODE, 
PL_ANALYSIS.PANAME, 

STK_STOCK.STKCODE, 
STK_STOCK.STKNAME, 

PRC_PRICE_RECS.PRCODE, 
PRC_PRICE_RECS.PRNAME, 

CST_COSTHEADER.CH_CODE, 
CST_COSTHEADER.CH_NAME, 

CST_COSTCENTRE.CC_CODE, 
CST_COSTCENTRE.CC_NAME, 

NL_DR.NNAME AS DR_NAME, 
NL_DR.N_CENTRALISED AS DR_CENTRAL, 
                      
NL_CR.NNAME AS CR_NAME,
NL_CR.N_CENTRALISED AS CR_CENTRAL,

NL_VAT.NNAME AS VAT_NAME

                     
FROM  PL_TRANSACTIONS 

  INNER JOIN PL_ACCOUNTS 
  ON PL_TRANSACTIONS.PT_COPYSUPP = PL_ACCOUNTS.SUCODE

  INNER JOIN SL_PL_NL_DETAIL 
  ON PL_TRANSACTIONS.PT_HEADER_KEY = SL_PL_NL_DETAIL.DET_HEADER_KEY

  INNER JOIN PL_ANALYSIS 
  ON SL_PL_NL_DETAIL.DET_ANALYSIS = PL_ANALYSIS.PACODE

  INNER JOIN NL_ACCOUNTS NL_DR
  ON SL_PL_NL_DETAIL.DET_NOMINALDR = NL_DR.NCODE

  INNER JOIN NL_ACCOUNTS NL_CR 
  ON SL_PL_NL_DETAIL.DET_NOMINALCR = NL_CR.NCODE

  LEFT OUTER JOIN NL_ACCOUNTS NL_VAT 
  ON SL_PL_NL_DETAIL.DET_NOMINALVAT = NL_VAT.NCODE

  LEFT OUTER JOIN CST_COSTCENTRE 
  ON CC_CONCAT_CODES = DET_COSTHEADER + SPACE(10 - LEN(DET_COSTHEADER)) + DET_COSTCENTRE 

  LEFT OUTER JOIN CST_COSTHEADER
  ON SL_PL_NL_DETAIL.DET_COSTHEADER = CST_COSTHEADER.CH_CODE
  
  LEFT OUTER JOIN PRC_PRICE_RECS 
  ON SL_PL_NL_DETAIL.DET_PRICE_CODE = PRC_PRICE_RECS.PRCODE

  LEFT OUTER JOIN STK_STOCK
  ON SL_PL_NL_DETAIL.DET_STOCK_CODE = STK_STOCK.STKCODE

WHERE (SL_PL_NL_DETAIL.DET_TYPE NOT IN ('MIN', 'MPA', 'MAD', 'MAC', 'MCR'))
