CREATE VIEW AA_REP_SUPPLIER_TURNOVER_VIEW
/*
** Written:     12/04/2005 RV   
** Last Amended: 03/05/2006 RV
** Comments: returns all turnover and budget revisions for crystal reports
*/
AS
SELECT     
PL_ACCOUNTS.SUCODE, 
PL_ACCOUNTS.SUNAME, 
CAST (PL_ACCOUNTS.SU_ON_STOP AS BIT) AS SU_ON_STOP,
PL_ACCOUNTS.SUSORT, 
PL_ACCOUNTS.SUUSER1, 
PL_ACCOUNTS.SUUSER2, 
PL_ACCOUNTS.SUUSER3,
PL_ACCOUNTS.SUBALANCE, 
PL_ACCOUNTS.SUTURNOVERYTD, 
PL_ACCOUNTS.SUCURRENCYCODE,
PL_ACCOUNTS.SUPOSTCODE,
PL_ACCOUNTS.SU_CREDIT_LIMIT,
PL_ACCOUNTS.SU_ADDRESS_USER2, 
PL_ACCOUNTS.SU_COUNTRY, 
SYS_CURRENCY.CURR_SYMBOL,

PL_ACCOUNTS.SUTURNOVR_L1, 
PL_ACCOUNTS.SUTURNOVR_L2, 
PL_ACCOUNTS.SUTURNOVR_L3, 
PL_ACCOUNTS.SUTURNOVR_L4, 
PL_ACCOUNTS.SUTURNOVR_L5, 
PL_ACCOUNTS.SUTURNOVR_L6, 
PL_ACCOUNTS.SUTURNOVR_L7, 
PL_ACCOUNTS.SUTURNOVR_L8, 
PL_ACCOUNTS.SUTURNOVR_L9, 
PL_ACCOUNTS.SUTURNOVR_L10, 
PL_ACCOUNTS.SUTURNOVR_L11, 
PL_ACCOUNTS.SUTURNOVR_L12, 
PL_ACCOUNTS.SUTURNOVR_L13, 

PL_ACCOUNTS.SUTURNOVR_C1, 
PL_ACCOUNTS.SUTURNOVR_C2, 
PL_ACCOUNTS.SUTURNOVR_C3, 
PL_ACCOUNTS.SUTURNOVR_C4, 
PL_ACCOUNTS.SUTURNOVR_C5, 
PL_ACCOUNTS.SUTURNOVR_C6, 
PL_ACCOUNTS.SUTURNOVR_C7, 
PL_ACCOUNTS.SUTURNOVR_C8,
PL_ACCOUNTS.SUTURNOVR_C9, 
PL_ACCOUNTS.SUTURNOVR_C10, 
PL_ACCOUNTS.SUTURNOVR_C11, 
PL_ACCOUNTS.SUTURNOVR_C12, 
PL_ACCOUNTS.SUTURNOVR_C13, 

PL_ACCOUNTS.SUTURNOVR_O1, 
PL_ACCOUNTS.SUTURNOVR_O2, 
PL_ACCOUNTS.SUTURNOVR_O3, 
PL_ACCOUNTS.SUTURNOVR_O4, 
PL_ACCOUNTS.SUTURNOVR_O5, 
PL_ACCOUNTS.SUTURNOVR_O6, 
PL_ACCOUNTS.SUTURNOVR_O7, 
PL_ACCOUNTS.SUTURNOVR_O8, 
PL_ACCOUNTS.SUTURNOVR_O9, 
PL_ACCOUNTS.SUTURNOVR_O10, 
PL_ACCOUNTS.SUTURNOVR_O11, 
PL_ACCOUNTS.SUTURNOVR_O12, 
PL_ACCOUNTS.SUTURNOVR_O13, 

PL_ACCOUNTS.SUTURNOVR_L1_C, 
PL_ACCOUNTS.SUTURNOVR_L2_C, 
PL_ACCOUNTS.SUTURNOVR_L3_C, 
PL_ACCOUNTS.SUTURNOVR_L4_C, 
PL_ACCOUNTS.SUTURNOVR_L5_C, 
PL_ACCOUNTS.SUTURNOVR_L6_C, 
PL_ACCOUNTS.SUTURNOVR_L7_C, 
PL_ACCOUNTS.SUTURNOVR_L8_C, 
PL_ACCOUNTS.SUTURNOVR_L9_C, 
PL_ACCOUNTS.SUTURNOVR_L10_C, 
PL_ACCOUNTS.SUTURNOVR_L11_C, 
PL_ACCOUNTS.SUTURNOVR_L12_C, 
PL_ACCOUNTS.SUTURNOVR_L13_C, 

PL_ACCOUNTS.SUTURNOVR_C1_C, 
PL_ACCOUNTS.SUTURNOVR_C2_C, 
PL_ACCOUNTS.SUTURNOVR_C3_C, 
PL_ACCOUNTS.SUTURNOVR_C4_C, 
PL_ACCOUNTS.SUTURNOVR_C5_C, 
PL_ACCOUNTS.SUTURNOVR_C6_C, 
PL_ACCOUNTS.SUTURNOVR_C7_C, 
PL_ACCOUNTS.SUTURNOVR_C8_C, 
PL_ACCOUNTS.SUTURNOVR_C9_C, 
PL_ACCOUNTS.SUTURNOVR_C10_C, 
PL_ACCOUNTS.SUTURNOVR_C11_C, 
PL_ACCOUNTS.SUTURNOVR_C12_C, 
PL_ACCOUNTS.SUTURNOVR_C13_C, 

PL_ACCOUNTS.SUTURNOVR_O1_C, 
PL_ACCOUNTS.SUTURNOVR_O2_C, 
PL_ACCOUNTS.SUTURNOVR_O3_C, 
PL_ACCOUNTS.SUTURNOVR_O4_C, 
PL_ACCOUNTS.SUTURNOVR_O5_C, 
PL_ACCOUNTS.SUTURNOVR_O6_C, 
PL_ACCOUNTS.SUTURNOVR_O7_C, 
PL_ACCOUNTS.SUTURNOVR_O8_C, 
PL_ACCOUNTS.SUTURNOVR_O9_C, 
PL_ACCOUNTS.SUTURNOVR_O10_C, 
PL_ACCOUNTS.SUTURNOVR_O11_C, 
PL_ACCOUNTS.SUTURNOVR_O12_C, 
PL_ACCOUNTS.SUTURNOVR_O13_C, 

PL_ACCOUNTS2.SU_USRDATE1, 
PL_ACCOUNTS2.SU_USRDATE2,
PL_ACCOUNTS2.SU_USRDATE3, 
PL_ACCOUNTS2.SU_USRCHAR1, 
PL_ACCOUNTS2.SU_USRCHAR2,
PL_ACCOUNTS2.SU_USRCHAR5,
PL_ACCOUNTS2.SU_USRCHAR6, 
PL_ACCOUNTS2.SU_USRCHAR7, 
PL_ACCOUNTS2.SU_USRCHAR8,
PL_ACCOUNTS2.SU_USRNUM1, 
PL_ACCOUNTS2.SU_USRNUM2, 
PL_ACCOUNTS2.SU_USRNUM3, 
                      
AA_REP_SUPPLIER_BUDGETS_VIEW.REVISION,

isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O1,0) As BUD_O1,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O2,0) As BUD_O2,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O3,0) As BUD_O3,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O4,0) As BUD_O4,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O5,0) As BUD_O5,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O6,0) As BUD_O6,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O7,0) As BUD_O7,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O8,0) As BUD_O8,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O9,0) As BUD_O9,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O10,0) As BUD_O10,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O11,0) As BUD_O11,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O12,0) As BUD_O12,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_O13,0) As BUD_O13,

isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L1,0) As BUD_L1,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L2,0) As BUD_L2,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L3,0) As BUD_L3,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L4,0) As BUD_L4,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L5,0) As BUD_L5,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L6,0) As BUD_L6,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L7,0) As BUD_L7,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L8,0) As BUD_L8,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L9,0) As BUD_L9,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L10,0) As BUD_L10,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L11,0) As BUD_L11,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L12,0) As BUD_L12,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_L13,0) As BUD_L13,

isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C1,0) As BUD_C1,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C2,0) As BUD_C2,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C3,0) As BUD_C3,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C4,0) As BUD_C4,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C5,0) As BUD_C5,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C6,0) As BUD_C6,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C7,0) As BUD_C7,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C8,0) As BUD_C8,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C9,0) As BUD_C9,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C10,0) As BUD_C10,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C11,0) As BUD_C11,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C12,0) As BUD_C12,
isnull(AA_REP_SUPPLIER_BUDGETS_VIEW.BUD_C13,0) As BUD_C13,

isnull( M.MAX_REVISION, 0 ) as MAX_REVISION

FROM PL_ACCOUNTS 
	
   	LEFT OUTER JOIN AA_REP_SUPPLIER_BUDGETS_VIEW 
	ON PL_ACCOUNTS.SUCODE = AA_REP_SUPPLIER_BUDGETS_VIEW.SUPPLIER

	INNER JOIN PL_ACCOUNTS2 
	ON PL_ACCOUNTS.SU_PRIMARY = PL_ACCOUNTS2.SU_PRIMARY_2

   inner join SYS_CURRENCY on SYS_CURRENCY.CURR_CODE = PL_ACCOUNTS.SUCURRENCYCODE

	left join ( select B_ACCOUNT_CODE, max( B_REVISION_NUMBER ) as MAX_REVISION -- Obtain maximum revision number for account
						from SYS_BUDGETS
						where B_RECORD_TYPE = 'P' and B_BUDGET_TYPE = 'B'
						group by B_ACCOUNT_CODE
					) M on M.B_ACCOUNT_CODE = PL_ACCOUNTS.SUCODE
