CREATE view AA_REP_NOMINAL_DETAIL_TB_VIEW
/*
** Written     :  11/11/2005 RV
** Last Amended:  14/11/2005 RV, 16/11/2005 RV, 17/11/2005 RV, 17/05/2006 SB
** Comments    :  view to create list of detail lines for use in crystal detailed TB report
**
** Used by     :  Trial Balance as at.rpt
*/
(
NCODE,
NNAME,
NMAJORHEADCODE,

NOPENBALANCELY,
TURNOVER_TO_L1,
TURNOVER_TO_L2,
TURNOVER_TO_L3,
TURNOVER_TO_L4,
TURNOVER_TO_L5,
TURNOVER_TO_L6,
TURNOVER_TO_L7,
TURNOVER_TO_L8,
TURNOVER_TO_L9,
TURNOVER_TO_L10,
TURNOVER_TO_L11,
TURNOVER_TO_L12,
TURNOVER_TO_L13,

NOPENBALYEAR,
TURNOVER_TO_C1,
TURNOVER_TO_C2,
TURNOVER_TO_C3,
TURNOVER_TO_C4,
TURNOVER_TO_C5,
TURNOVER_TO_C6,
TURNOVER_TO_C7,
TURNOVER_TO_C8,
TURNOVER_TO_C9,
TURNOVER_TO_C10,
TURNOVER_TO_C11,
TURNOVER_TO_C12,
TURNOVER_TO_C13,

TURNOVER_TO_N1,
TURNOVER_TO_N2,
TURNOVER_TO_N3,
TURNOVER_TO_N4,
TURNOVER_TO_N5,
TURNOVER_TO_N6,
TURNOVER_TO_N7,
TURNOVER_TO_N8,
TURNOVER_TO_N9,
TURNOVER_TO_N10,
TURNOVER_TO_N11,
TURNOVER_TO_N12,
TURNOVER_TO_N13,

NTYPE,
N_EXCLUDE_TRNREP
)
as select
NCODE,
NNAME,
NMAJORHEADCODE,

NOPENBALANCELY,
NOPENBALANCELY + NTURNOVER_L1 as TURNOVER_TO_L1,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2 as TURNOVER_TO_L2,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 as TURNOVER_TO_L3,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 + NTURNOVER_L4 as TURNOVER_TO_L4,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 as TURNOVER_TO_L5,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 as TURNOVER_TO_L6,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 as TURNOVER_TO_L7,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 as TURNOVER_TO_L8,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 as TURNOVER_TO_L9,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10 as TURNOVER_TO_L10,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10 + NTURNOVER_L11 as TURNOVER_TO_L11,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10 + NTURNOVER_L11 + NTURNOVER_L12 as TURNOVER_TO_L12,
NOPENBALANCELY + NTURNOVER_L1 + NTURNOVER_L2  + NTURNOVER_L3 + NTURNOVER_L4 + NTURNOVER_L5 + NTURNOVER_L6 + NTURNOVER_L7 + NTURNOVER_L8 + NTURNOVER_L9 + NTURNOVER_L10 + NTURNOVER_L11 + NTURNOVER_L12 + NTURNOVER_L13 as TURNOVER_TO_L13,

NOPENBALYEAR,
NOPENBALYEAR + NTURNOVER_C1 as TURNOVER_TO_C1,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 as TURNOVER_TO_C2,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 as TURNOVER_TO_C3,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 as TURNOVER_TO_C4,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 as TURNOVER_TO_C5,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 as TURNOVER_TO_C6,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 as TURNOVER_TO_C7,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 as TURNOVER_TO_C8,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 as TURNOVER_TO_C9,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 as TURNOVER_TO_C10,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 as TURNOVER_TO_C11,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 as TURNOVER_TO_C12,
NOPENBALYEAR + NTURNOVER_C1 + NTURNOVER_C2 + NTURNOVER_C3 + NTURNOVER_C4 + NTURNOVER_C5 + NTURNOVER_C6 + NTURNOVER_C7 + NTURNOVER_C8 + NTURNOVER_C9 + NTURNOVER_C10 + NTURNOVER_C11 + NTURNOVER_C12 + NTURNOVER_C13 as TURNOVER_TO_C13,

NTURNOVER_N1 as TURNOVER_TO_N1,
NTURNOVER_N1 + NTURNOVER_N2 as TURNOVER_TO_N2,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 as TURNOVER_TO_N3,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 as TURNOVER_TO_N4,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 as TURNOVER_TO_N5,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 as TURNOVER_TO_N6,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 as TURNOVER_TO_N7,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 as TURNOVER_TO_N8,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 as TURNOVER_TO_N9,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 as TURNOVER_TO_N10,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_N11 as TURNOVER_TO_N11,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_N11 + NTURNOVER_N12 as TURNOVER_TO_N12,
NTURNOVER_N1 + NTURNOVER_N2 + NTURNOVER_N3 + NTURNOVER_N4 + NTURNOVER_N5 + NTURNOVER_N6 + NTURNOVER_N7 + NTURNOVER_N8 + NTURNOVER_N9 + NTURNOVER_N10 + NTURNOVER_N11 + NTURNOVER_N12 + NTURNOVER_N13 as TURNOVER_TO_N13,

NTYPE,
N_EXCLUDE_TRNREP

from NL_ACCOUNTS N

