CREATE VIEW AA_REP_SUPPLIER_DETAIL_VIEW
/*
** Written:     12/04/2005 RV   
** Last Amended: 
** Comments: returns purchase ledger supplier record details for crystal reports
*/
AS
SELECT     
PL_ACCOUNTS.SUCODE, 
PL_ACCOUNTS.SUNAME, 
CAST (PL_ACCOUNTS.SU_ON_STOP AS BIT) AS SU_ON_STOP,
PL_ACCOUNTS.SUBALANCE, 
PL_ACCOUNTS.SUBALANCE_C, 
PL_ACCOUNTS.SUTURNOVERYTD, 
PL_ACCOUNTS.SUTURNOVR_YTD_C, 
PL_ACCOUNTS.SUSORT, 
PL_ACCOUNTS.SUUSER1, 
PL_ACCOUNTS.SUUSER2, 
PL_ACCOUNTS.SUUSER3, 
PL_ACCOUNTS.SUADDRESS, 
PL_ACCOUNTS.SUPOSTCODE, 
PL_ACCOUNTS.SU_ADDRESS_USER1, 
PL_ACCOUNTS.SU_ADDRESS_USER2, 
PL_ACCOUNTS.SU_COUNTRY,
PL_ACCOUNTS.SU_REM_ADD_CDE, 
PL_ACCOUNTS.SU_INV_ADD_CDE, 
PL_ACCOUNTS.SU_DEL_ADD_CDE, 
PL_ACCOUNTS.SU_ST_ADD_CODE, 
PL_ACCOUNTS.SUPHONE, 
PL_ACCOUNTS.SUFAX, 
PL_ACCOUNTS.SUCONTACT, 
PL_ACCOUNTS.SUSALUTE, 
PL_ACCOUNTS.SU_EMAIL, 
PL_ACCOUNTS.SU_LINE_DISC, 
PL_ACCOUNTS.SU_TOT_DISC, 
PL_ACCOUNTS.SU_SETT_DISC1, 
PL_ACCOUNTS.SU_SETT_DISC2, 
PL_ACCOUNTS.SU_SETT_DAYS1, 
PL_ACCOUNTS.SU_SETT_DAYS2, 
PL_ACCOUNTS.SUCURRENCYCODE, 
PL_ACCOUNTS.SU_CREDIT_LIMIT, 
PL_ACCOUNTS.SU_TERMS, 
PL_ACCOUNTS.SU_DEL_CHARGE, 
PL_ACCOUNTS.SU_DEL_CHG_PCNT, 
PL_ACCOUNTS.SU_MIN_ORDR, 
PL_ACCOUNTS.SU_DUE_DAYS, 
PL_ACCOUNTS.SU_A_P_DAYS, 
PL_ACCOUNTS.SU_DUEDATE_TYPE, 
PL_ACCOUNTS.SU_PRICE_KEY, 
CAST (PL_ACCOUNTS.SU_MULTI_CURR AS BIT) AS SU_MULTI_CURR, 
PL_ACCOUNTS2.SU_USRDATE1, 
PL_ACCOUNTS2.SU_USRDATE2,
PL_ACCOUNTS2.SU_USRDATE3, 
CAST (PL_ACCOUNTS2.SU_USRFLAG1 AS BIT) AS SU_USRFLAG1, 
CAST (PL_ACCOUNTS2.SU_USRFLAG2 AS BIT) AS SU_USRFLAG2, 
CAST (PL_ACCOUNTS2.SU_USRFLAG3 AS BIT) AS SU_USRFLAG3, 
PL_ACCOUNTS2.SU_USRCHAR1, 
PL_ACCOUNTS2.SU_USRCHAR2,
PL_ACCOUNTS2.SU_USRCHAR3,
PL_ACCOUNTS2.SU_USRCHAR4, 
PL_ACCOUNTS2.SU_USRCHAR5,
PL_ACCOUNTS2.SU_USRCHAR6, 
PL_ACCOUNTS2.SU_USRCHAR7, 
PL_ACCOUNTS2.SU_USRCHAR8,
PL_ACCOUNTS2.SU_USRNUM1, 
PL_ACCOUNTS2.SU_USRNUM2, 
PL_ACCOUNTS2.SU_USRNUM3, 
PL_ACCOUNTS2.SU_ISDN_NUMBER, 
PL_ACCOUNTS2.SU_EDI_ANA, 
PL_ACCOUNTS2.SU_EDI_SUPPIDN, 
PL_ACCOUNTS.SU_BANK_SORT, 
PL_ACCOUNTS.SU_BANK_AC_NO, 
PL_ACCOUNTS.SU_BANK_AC_NAME, 
PL_ACCOUNTS.SU_BANK_BACSREF, 
PL_ACCOUNTS.SU_BANK_BANKNAME, 
PL_ACCOUNTS2.SU_IBAN_NO, 
PL_ACCOUNTS2.SU_OUR_ACCOUNT_CODE, 
PL_ACCOUNTS.SUAGED_1, 
PL_ACCOUNTS.SUAGED_2, 
PL_ACCOUNTS.SUAGED_3, 
PL_ACCOUNTS.SUAGED_4, 
PL_ACCOUNTS.SUAGED_UNALLOC, 
PL_ACCOUNTS.SU_DOC_DESTINATION,
PL_ACCOUNTS.SU_ANALYSIS, 
PL_ANALYSIS.PANAME AS PURCHASE_ANALYSIS_NAME, 
PL_ACCOUNTS.SU_TAX_CODE, 
PL_ACCOUNTS.SU_BANK_ANALYS, 
PL_ACCOUNTS.SU_IMPORT_CODE, 
PL_ACCOUNTS.SU_COUNTRY_CODE, 
SYS_COUNTRY.CO_NAME, 
PL_ACCOUNTS.SU_VAT_REG_NO, 
PL_ACCOUNTS.SU_EC_DELIVERY, 
PL_ACCOUNTS.SU_EC_T_NATURE, 
PL_ACCOUNTS.SU_EC_T_MODE, 
PL_ACCOUNTS2.SU_LANG_CODE, 
PL_ACCOUNTS2.SU_LEVEL, 
SYS_VATCONTROL.VAT_RATE, 
PL_ANAL1.PANAME AS BANK_ANALYSIS_NAME, 
PL_ACCOUNTS2.SU_CONTACT_JOB, 
PL_ACCOUNTS2.SU_MOBILE_NUMBER, 
PL_ACCOUNTS2.SU_WEBSITE_ADDRESS,
PL_ACCOUNTS.SU_PRIMARY,
SYS_CURRENCY.CURR_SYMBOL

FROM PL_ACCOUNTS 

  INNER JOIN PL_ACCOUNTS2 
  ON PL_ACCOUNTS.SU_PRIMARY = PL_ACCOUNTS2.SU_PRIMARY_2

  inner join SYS_CURRENCY on SYS_CURRENCY.CURR_CODE = PL_ACCOUNTS.SUCURRENCYCODE

  LEFT OUTER JOIN SYS_COUNTRY 
  ON PL_ACCOUNTS.SU_COUNTRY_CODE = SYS_COUNTRY.CO_CODE 

  LEFT OUTER JOIN PL_ANALYSIS PL_ANAL1 
  ON PL_ACCOUNTS.SU_BANK_ANALYS = PL_ANAL1.PACODE 

  LEFT OUTER JOIN SYS_VATCONTROL 
  ON PL_ACCOUNTS.SU_TAX_CODE = SYS_VATCONTROL.VAT_CODE 

  LEFT OUTER JOIN PL_ANALYSIS 
  ON PL_ACCOUNTS.SU_ANALYSIS = PL_ANALYSIS.PACODE 



