CREATE VIEW AA_REP_NOMINAL_TRANS_VIEW
/*
** Written:     01/07/2005 RV   
** Last Amended: 05/07/05 RV, 22/08/05 RV, 24/08/05 RV, 25/08/05 RV, 27/09/2005 SB, 28/09/2005
** Comments: returns selected nominal transaction headers and details for nominal voucher crystal reports
*/
AS
SELECT 
NL_TRANSACTIONS.NT_DATE,
CAST (NL_TRANSACTIONS.NT_BATCH_FLAG AS BIT) AS NT_BATCH_FLAG,
NL_TRANSACTIONS.NT_BATCH_REF,                       
NL_TRANSACTIONS.NT_TRANTYPE, 
NL_TRANSACTIONS.NT_HEADER_REF, 
NL_TRANSACTIONS.NT_FIRST_DATE,                       
NL_TRANSACTIONS.NT_NEXT_DATE, 
NL_TRANSACTIONS.NT_MAX_POSTINGS, 
NL_TRANSACTIONS.NT_POSTINGS_CNT,                       
NL_TRANSACTIONS.NT_POSTINGS_PER, 
NL_TRANSACTIONS.NT_POSTINGS_FRQ, 
NL_TRANSACTIONS.NT_POSTED_DATE,                       
NL_TRANSACTIONS.NT_DESCRIPTION, 
CAST (NL_TRANSACTIONS.NT_CONTRA_FLAG AS BIT) AS NT_CONTRA_FLAG, 
CAST (NL_TRANSACTIONS.NT_MULTI_CONTRA AS BIT) AS NT_MULTI_CONTRA,                
NL_TRANSACTIONS.NT_CURRENCYSYMB, 
NL_TRANSACTIONS.NT_YEAR, 
NL_TRANSACTIONS.NT_PERIODNUMBER,                       
CAST (SL_PL_NL_DETAIL.DET_RECUR_FLAG AS BIT) AS DET_RECUR_FLAG,
CAST (NL_TRANSACTIONS.NT_RECUR_FLAG AS BIT) AS NT_RECUR_FLAG, 
NL_TRANSACTIONS.NT_REVERSE_FLAG, 
NL_TRANSACTIONS.NT_PRIMARY,                       
NL_TRANSACTIONS.NT_SUB_LEDGER, 
NL_TRANSACTIONS.NT_CURR_TYPE,                       

CAST (SL_PL_NL_DETAIL.DET_BATCH_FLAG AS BIT) AS DET_BATCH_FLAG, 
SL_PL_NL_DETAIL.DET_NOM_YEAR,
SL_PL_NL_DETAIL.DET_NOM_PERIOD,
SL_PL_NL_DETAIL.DET_TRI_RATE2, 
SL_PL_NL_DETAIL.DET_TRI_RATE1, 
SL_PL_NL_DETAIL.DET_BASE2_RATE,  
SL_PL_NL_DETAIL.DET_NOMINALDR,                       
'' as DET_NOMINALCR,
SL_PL_NL_DETAIL.DET_NETT, 
SL_PL_NL_DETAIL.DET_CURR_NETT,                       
SL_PL_NL_DETAIL.DET_PRIMARY, 
SL_PL_NL_DETAIL.DET_DESCRIPTION,
SL_PL_NL_DETAIL.DET_DATE,
SL_PL_NL_DETAIL.DET_JNL_LINEREF,
CAST (SL_PL_NL_DETAIL.DET_TRI_RATECHNG1 AS BIT) AS DET_TRI_RATECHNG1, 
CAST (SL_PL_NL_DETAIL.DET_TRI_RATECHNG2 AS BIT) AS DET_TRI_RATECHNG2,
CAST (SL_PL_NL_DETAIL.DET_CURR_RTEFLG AS BIT) AS DET_CURR_RTEFLG,
SL_PL_NL_DETAIL.DET_CURR_CODE,
SL_PL_NL_DETAIL.DET_CURR_RATE,
SL_PL_NL_DETAIL.DET_NETT_BASE2,
SL_PL_NL_DETAIL.DET_DIMENSION1,
SL_PL_NL_DETAIL.DET_DIMENSION2,
SL_PL_NL_DETAIL.DET_DIMENSION3,

NL_ACCOUNTS.NCODE,
NL_ACCOUNTS.NNAME, 
NL_ACCOUNTS.NCATEGORYCODE1,
NL_ACCOUNTS.NCATEGORYCODE2,
NL_ACCOUNTS.NCATEGORYCODE3,
NL_ACCOUNTS.NCATEGORYCODE4,
NL_ACCOUNTS.NCATEGORYCODE5,
NL_ACCOUNTS.NCATEGORYCODE6,
NL_ACCOUNTS.NCATEGORYCODE7,
NL_ACCOUNTS.NCATEGORYCODE8,
                     
CST_COSTHEADER.CH_CODE, 
CST_COSTHEADER.CH_NAME, 
CST_COSTCENTRE.CC_CODE, 
CST_COSTCENTRE.CC_NAME,                       
NOM_VAT.NNAME AS VAT_NAME, 
NOM_VAT.NCODE AS VAT_NCODE, 
NOM_CONTRA.NCODE AS CONTRA_NCODE, 
NOM_CONTRA.NNAME AS CONTRA_NAME                       


FROM SL_PL_NL_DETAIL

INNER JOIN NL_TRANSACTIONS 
ON NL_TRANSACTIONS.NT_HEADER_KEY = SL_PL_NL_DETAIL.DET_HEADER_KEY

INNER JOIN NL_ACCOUNTS
ON DET_NOMINALDR = NCODE

LEFT OUTER JOIN NL_ACCOUNTS NOM_CONTRA
ON NOM_CONTRA.NCODE = NL_TRANSACTIONS.NT_GROSS_CONTRA   

LEFT OUTER JOIN  NL_ACCOUNTS NOM_VAT
ON NOM_VAT.NCODE = NL_TRANSACTIONS.NT_VAT_CONTRA  
     
LEFT OUTER JOIN CST_COSTCENTRE 
ON CC_CONCAT_CODES = DET_COSTHEADER + SPACE(10 - LEN(DET_COSTHEADER)) + DET_COSTCENTRE

LEFT OUTER JOIN CST_COSTHEADER 
ON  CST_COSTHEADER.CH_CODE = SL_PL_NL_DETAIL.DET_COSTHEADER

WHERE DET_NOMINALDR <> '' and DET_NOMINALDR IS NOT NULL

UNION ALL
SELECT 
NL_TRANSACTIONS.NT_DATE, 
CAST (NL_TRANSACTIONS.NT_BATCH_FLAG AS BIT) AS NT_BATCH_FLAG,
NL_TRANSACTIONS.NT_BATCH_REF,                       
NL_TRANSACTIONS.NT_TRANTYPE, 
NL_TRANSACTIONS.NT_HEADER_REF, 
NL_TRANSACTIONS.NT_FIRST_DATE,                       
NL_TRANSACTIONS.NT_NEXT_DATE, 
NL_TRANSACTIONS.NT_MAX_POSTINGS, 
NL_TRANSACTIONS.NT_POSTINGS_CNT,                       
NL_TRANSACTIONS.NT_POSTINGS_PER, 
NL_TRANSACTIONS.NT_POSTINGS_FRQ, 
NL_TRANSACTIONS.NT_POSTED_DATE,                       
NL_TRANSACTIONS.NT_DESCRIPTION, 
CAST (NL_TRANSACTIONS.NT_CONTRA_FLAG AS BIT) AS NT_CONTRA_FLAG, 
CAST (NL_TRANSACTIONS.NT_MULTI_CONTRA AS BIT) AS NT_MULTI_CONTRA,                      
NL_TRANSACTIONS.NT_CURRENCYSYMB, 
NL_TRANSACTIONS.NT_YEAR, 
NL_TRANSACTIONS.NT_PERIODNUMBER,                       
CAST (SL_PL_NL_DETAIL.DET_RECUR_FLAG AS BIT) AS DET_RECUR_FLAG, 
CAST (NL_TRANSACTIONS.NT_RECUR_FLAG AS BIT) AS NT_RECUR_FLAG,
NL_TRANSACTIONS.NT_REVERSE_FLAG, 
NL_TRANSACTIONS.NT_PRIMARY,                       
NL_TRANSACTIONS.NT_SUB_LEDGER, 
NL_TRANSACTIONS.NT_CURR_TYPE,           

CAST (SL_PL_NL_DETAIL.DET_BATCH_FLAG AS BIT) AS DET_BATCH_FLAG, 
SL_PL_NL_DETAIL.DET_NOM_YEAR,
SL_PL_NL_DETAIL.DET_NOM_PERIOD,
SL_PL_NL_DETAIL.DET_TRI_RATE2, 
SL_PL_NL_DETAIL.DET_TRI_RATE1, 
SL_PL_NL_DETAIL.DET_BASE2_RATE,  
'' as DET_NOMINALDR,                       
SL_PL_NL_DETAIL.DET_NOMINALCR, 
SL_PL_NL_DETAIL.DET_NETT, 
SL_PL_NL_DETAIL.DET_CURR_NETT,                       
SL_PL_NL_DETAIL.DET_PRIMARY, 
SL_PL_NL_DETAIL.DET_DESCRIPTION,
SL_PL_NL_DETAIL.DET_DATE,
SL_PL_NL_DETAIL.DET_JNL_LINEREF,
CAST (SL_PL_NL_DETAIL.DET_TRI_RATECHNG1 AS BIT) AS DET_TRI_RATECHNG1, 
CAST (SL_PL_NL_DETAIL.DET_TRI_RATECHNG2 AS BIT) AS DET_TRI_RATECHNG2,
CAST (SL_PL_NL_DETAIL.DET_CURR_RTEFLG AS BIT) AS DET_CURR_RTEFLG,
SL_PL_NL_DETAIL.DET_CURR_CODE,
SL_PL_NL_DETAIL.DET_CURR_RATE,
SL_PL_NL_DETAIL.DET_NETT_BASE2,
SL_PL_NL_DETAIL.DET_DIMENSION1,
SL_PL_NL_DETAIL.DET_DIMENSION2,
SL_PL_NL_DETAIL.DET_DIMENSION3,

NL_ACCOUNTS.NCODE,
NL_ACCOUNTS.NNAME, 
NL_ACCOUNTS.NCATEGORYCODE1,
NL_ACCOUNTS.NCATEGORYCODE2,
NL_ACCOUNTS.NCATEGORYCODE3,
NL_ACCOUNTS.NCATEGORYCODE4,
NL_ACCOUNTS.NCATEGORYCODE5,
NL_ACCOUNTS.NCATEGORYCODE6,
NL_ACCOUNTS.NCATEGORYCODE7,
NL_ACCOUNTS.NCATEGORYCODE8,
                       
CST_COSTHEADER.CH_CODE, 
CST_COSTHEADER.CH_NAME, 
CST_COSTCENTRE.CC_CODE, 
CST_COSTCENTRE.CC_NAME,                       
NOM_VAT.NNAME AS VAT_NAME, 
NOM_VAT.NCODE AS VAT_NCODE, 
NOM_CONTRA.NCODE AS CONTRA_NCODE, 
NOM_CONTRA.NNAME AS CONTRA_NAME                       

FROM SL_PL_NL_DETAIL

INNER JOIN NL_TRANSACTIONS 
ON NL_TRANSACTIONS.NT_HEADER_KEY = SL_PL_NL_DETAIL.DET_HEADER_KEY

INNER JOIN NL_ACCOUNTS
ON DET_NOMINALCR = NCODE

LEFT OUTER JOIN NL_ACCOUNTS NOM_CONTRA
ON NOM_CONTRA.NCODE = NL_TRANSACTIONS.NT_GROSS_CONTRA   

LEFT OUTER JOIN  NL_ACCOUNTS NOM_VAT
ON NOM_VAT.NCODE = NL_TRANSACTIONS.NT_VAT_CONTRA  
     
LEFT OUTER JOIN CST_COSTCENTRE 
ON CC_CONCAT_CODES = DET_COSTHEADER + SPACE(10 - LEN(DET_COSTHEADER)) + DET_COSTCENTRE

LEFT OUTER JOIN CST_COSTHEADER 
ON  CST_COSTHEADER.CH_CODE = SL_PL_NL_DETAIL.DET_COSTHEADER

WHERE DET_NOMINALCR <> '' and DET_NOMINALCR IS NOT NULL
