CREATE VIEW AA_REP_PURCHASE_ANALYSIS_VIEW
/*
** Written:     12/04/2005 RV   
** Last Amended: 27/10/05 RV
** Comments: returns purchase analysis records (by analysis code including budget by revision) for crystal reports
*/
AS
SELECT     
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.REVISION, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O1,                      
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O2, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O3,                      
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O4, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O5,                       
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O6, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O7,                      
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O8, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O9,                       
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O10, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O11,                       
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O12, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_O13,                       
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L1, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L2,                      
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L3, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L4,                       
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L5, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L6,                      
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L7, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L8,                       
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L9, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L10,                       
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L11, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L12,                       
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_L13, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C1,                      
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C2, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C3,                      
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C4, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C5,                       
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C6, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C7,                      
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C8, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C9,                      
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C10, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C11,                       
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C12, 
AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.BUD_C13, 

isnull( M.MAX_REVISION, 0 ) as MAX_REVISION,

PL_ANALYSIS.PACODE,                      
PL_ANALYSIS.PANAME, 
PL_ANALYSIS.PATYPE_P_B_D, 
PL_ANALYSIS.PATURNOVERYTD, 
PL_ANALYSIS.PATURNOVERPTD,                       
PL_ANALYSIS.PATURNOVR_YTD_C, 
PL_ANALYSIS.PATURNOVR_PTD_C, 
PL_ANALYSIS.PASORT, 
PL_ANALYSIS.PAUSER1,                       
PL_ANALYSIS.PAUSER2, 
PL_ANALYSIS.PAUSER3, 
PL_ANALYSIS.PATURNOVR_L1, 
PL_ANALYSIS.PATURNOVR_L2,                       
PL_ANALYSIS.PATURNOVR_L3, 
PL_ANALYSIS.PATURNOVR_L4, 
PL_ANALYSIS.PATURNOVR_L5, 
PL_ANALYSIS.PATURNOVR_L6,                       
PL_ANALYSIS.PATURNOVR_L7, 
PL_ANALYSIS.PATURNOVR_L8, 
PL_ANALYSIS.PATURNOVR_L9, 
PL_ANALYSIS.PATURNOVR_L10,                       
PL_ANALYSIS.PATURNOVR_L11, 
PL_ANALYSIS.PATURNOVR_L12, 
PL_ANALYSIS.PATURNOVR_L13, 
PL_ANALYSIS.PATURNOVR_C1,                       
PL_ANALYSIS.PATURNOVR_C2, 
PL_ANALYSIS.PATURNOVR_C3, 
PL_ANALYSIS.PATURNOVR_C4, 
PL_ANALYSIS.PATURNOVR_C5,                       
PL_ANALYSIS.PATURNOVR_C6, 
PL_ANALYSIS.PATURNOVR_C7, 
PL_ANALYSIS.PATURNOVR_C8, 
PL_ANALYSIS.PATURNOVR_C9,                       
PL_ANALYSIS.PATURNOVR_C10, 
PL_ANALYSIS.PATURNOVR_C11, 
PL_ANALYSIS.PATURNOVR_C12, 
PL_ANALYSIS.PATURNOVR_C13, 
PL_ANALYSIS.PATURNOVR_O1, 
PL_ANALYSIS.PATURNOVR_O2, 
PL_ANALYSIS.PATURNOVR_O3,
PL_ANALYSIS.PATURNOVR_O4, 
PL_ANALYSIS.PATURNOVR_O5, 
PL_ANALYSIS.PATURNOVR_O6, 
PL_ANALYSIS.PATURNOVR_O7,                       
PL_ANALYSIS.PATURNOVR_O8, 
PL_ANALYSIS.PATURNOVR_O9, 
PL_ANALYSIS.PATURNOVR_O10, 
PL_ANALYSIS.PATURNOVR_O11,                       
PL_ANALYSIS.PATURNOVR_O12, 
PL_ANALYSIS.PATURNOVR_O13, 
PL_ANALYSIS.PATURNOVR_L1_C,                      
PL_ANALYSIS.PATURNOVR_L2_C, 
PL_ANALYSIS.PATURNOVR_L3_C, 
PL_ANALYSIS.PATURNOVR_L4_C,                       
PL_ANALYSIS.PATURNOVR_L5_C, 
PL_ANALYSIS.PATURNOVR_L6_C, 
PL_ANALYSIS.PATURNOVR_L7_C,                       
PL_ANALYSIS.PATURNOVR_L8_C, 
PL_ANALYSIS.PATURNOVR_L9_C, 
PL_ANALYSIS.PATURNOVR_L10_C,                       
PL_ANALYSIS.PATURNOVR_L11_C, 
PL_ANALYSIS.PATURNOVR_L12_C, 
PL_ANALYSIS.PATURNOVR_L13_C,                       
PL_ANALYSIS.PATURNOVR_C1_C, 
PL_ANALYSIS.PATURNOVR_C2_C, 
PL_ANALYSIS.PATURNOVR_C3_C,                       
PL_ANALYSIS.PATURNOVR_C4_C, 
PL_ANALYSIS.PATURNOVR_C5_C, 
PL_ANALYSIS.PATURNOVR_C6_C,                      
PL_ANALYSIS.PATURNOVR_C7_C, 
PL_ANALYSIS.PATURNOVR_C8_C, 
PL_ANALYSIS.PATURNOVR_C9_C,                       
PL_ANALYSIS.PATURNOVR_C10_C, 
PL_ANALYSIS.PATURNOVR_C11_C, 
PL_ANALYSIS.PATURNOVR_C12_C,                      
PL_ANALYSIS.PATURNOVR_C13_C, 
PL_ANALYSIS.PATURNOVR_O1_C, 
PL_ANALYSIS.PATURNOVR_O2_C,                       
PL_ANALYSIS.PATURNOVR_O3_C, 
PL_ANALYSIS.PATURNOVR_O4_C, 
PL_ANALYSIS.PATURNOVR_O5_C,                       
PL_ANALYSIS.PATURNOVR_O6_C, 
PL_ANALYSIS.PATURNOVR_O7_C, 
PL_ANALYSIS.PATURNOVR_O8_C,                       
PL_ANALYSIS.PATURNOVR_O9_C, 
PL_ANALYSIS.PATURNOVR_O10_C, 
PL_ANALYSIS.PATURNOVR_O11_C,                      
PL_ANALYSIS.PATURNOVR_O12_C, 
PL_ANALYSIS.PATURNOVR_O13_C, 
PL_ANALYSIS.PANOTES, 
PL_ANALYSIS.PA_USER_EDITED,                       
PL_ANALYSIS.PA_USER_PUTIN, 
PL_ANALYSIS.PA_DATE_PUTIN, 
PL_ANALYSIS.PA_DATE_EDITED,                      
PL_ANALYSIS.PACURRENCYSYMBL, 
PL_ANALYSIS.PANOMINALDR, 
PL_ANALYSIS.PANOMINALCR, 
PL_ANALYSIS.PANOMINALVAT,                      
PL_ANALYSIS.PAVATCODE, 
PL_ANALYSIS.PA_LEVEL, 
CAST (isnull(PL_ANALYSIS.PADEFAULT_BANK,0) AS BIT) AS PADEFAULT_BANK, 
CAST (isnull(PL_ANALYSIS.PADEFAULT_PURCH,0) AS BIT) AS PADEFAULT_PURCH,                       
CAST (isnull(PL_ANALYSIS.PA_FORCE_COSTING,0) AS BIT) AS PA_FORCE_COSTING, 
CAST (isnull(PL_ANALYSIS.PA_ANALYSIS_MATRIX,0) AS BIT) AS PA_ANALYSIS_MATRIX,
PL_ANALYSIS.PA_PRIMARY,
 
PL_ANALYSIS2.PA_USRCHAR1,                       
PL_ANALYSIS2.PA_USRCHAR2,
PL_ANALYSIS2.PA_USRCHAR3, 
PL_ANALYSIS2.PA_USRCHAR4,  
PL_ANALYSIS2.PA_USRCHAR5, 
PL_ANALYSIS2.PA_USRCHAR6, 
PL_ANALYSIS2.PA_USRCHAR7,                      
PL_ANALYSIS2.PA_USRCHAR8, 
PL_ANALYSIS2.PA_USRNUM1, 
PL_ANALYSIS2.PA_USRNUM2, 
PL_ANALYSIS2.PA_USRNUM3,                       
PL_ANALYSIS2.PA_USRDATE1, 
PL_ANALYSIS2.PA_USRDATE2, 
PL_ANALYSIS2.PA_USRDATE3, 
CAST (isnull(PL_ANALYSIS2.PA_USRFLAG1,0) AS BIT) AS PA_USRFLAG1,                      
CAST (isnull(PL_ANALYSIS2.PA_USRFLAG2,0) AS BIT) AS PA_USRFLAG2, 
CAST (isnull(PL_ANALYSIS2.PA_USRFLAG3,0) AS BIT) AS PA_USRFLAG3,

SYS_VATCONTROL.VAT_RATE, 

NL_DR.NNAME AS DR_NAME,
                  
NL_CR.NNAME AS CR_NAME, 

NL_VAT.NNAME AS VAT_NAME
 
FROM PL_ANALYSIS

  INNER JOIN NL_ACCOUNTS NL_DR
  ON PL_ANALYSIS.PANOMINALDR = NL_DR.NCODE  

  INNER JOIN NL_ACCOUNTS NL_CR
  ON PL_ANALYSIS.PANOMINALCR = NL_CR.NCODE

  LEFT OUTER JOIN NL_ACCOUNTS NL_VAT
  ON PL_ANALYSIS.PANOMINALVAT = NL_VAT.NCODE

  LEFT OUTER JOIN SYS_VATCONTROL 
  ON PL_ANALYSIS.PAVATCODE = SYS_VATCONTROL.VAT_CODE

  LEFT OUTER JOIN PL_ANALYSIS2 
  ON PL_ANALYSIS.PA_PRIMARY = PL_ANALYSIS2.PA_PRIMARY_2

  LEFT OUTER JOIN AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW
  ON PL_ANALYSIS.PACODE = AA_REP_PURCHASE_ANALYSIS_BUDGETS_VIEW.ANALYSIS

  LEFT join ( select B_ACCOUNT_CODE, max( B_REVISION_NUMBER ) as MAX_REVISION -- Obtain maximum revision number for account
						from SYS_BUDGETS
						where B_RECORD_TYPE = 'PA' and B_BUDGET_TYPE = 'B'
						group by B_ACCOUNT_CODE
					) M on M.B_ACCOUNT_CODE = PL_ANALYSIS.PACODE



