create view AA_REP_REMITTANCES_VIEW

as

select
   DOC_LEDGER_HEADER.DLH_PRIMARY
,  DOC_LEDGER_HEADER.DLH_DOC_TYPE
,  DOC_LEDGER_HEADER.DLH_DOC_DATE
,  DOC_LEDGER_HEADER.DLH_TEXT
,  DOC_LEDGER_HEADER.DLH_CHEQUE_VALUE
,  DOC_LEDGER_HEADER.DLH_CHEQUE_WORD1
,  DOC_LEDGER_HEADER.DLH_CHEQUE_WORD2
,  DOC_LEDGER_HEADER.DLH_CHEQUE_WORD3
,  DOC_LEDGER_HEADER.DLH_CHEQUE_WORD4
,  DOC_LEDGER_HEADER.DLH_CHEQUE_WORD5
,  DOC_LEDGER_HEADER.DLH_CHEQUE_WORD6
,  DOC_LEDGER_HEADER.DLH_CHEQUE_WORD7
,  DOC_LEDGER_HEADER.DLH_CURRSYMBOL
,  DOC_LEDGER_HEADER.DLH_FAX_HEADER
,  DOC_LEDGER_HEADER.DLH_COMP_ADDRESS
,  DOC_LEDGER_DETAIL.DLD_HEADER_LINK
,  DOC_LEDGER_DETAIL.DLD_DRVAL_DOC
,  DOC_LEDGER_DETAIL.DLD_CRVAL_DOC
,  DOC_LEDGER_DETAIL.DLD_REMITVAL_DOC
,  DOC_LEDGER_DETAIL.DLD_OSVAL_DOC
,  PL_TRANSACTIONS.PT_TRANTYPE
,  PL_TRANSACTIONS.PT_HEADER_REF
,  PL_TRANSACTIONS.PT_DESCRIPTION
,  PL_TRANSACTIONS.PT_DATE
,  PL_TRANSACTIONS.PT_QUERY_FLAG
,  PL_TRANSACTIONS.PT_PRIMARY
,  PL_ACCOUNTS.SUCODE
,  PL_ACCOUNTS.SUNAME
,  PL_ACCOUNTS.SUSORT
,  PL_ACCOUNTS.SUUSER1
,  PL_ACCOUNTS.SUUSER2
,  PL_ACCOUNTS.SUUSER3
,  PL_ADDRESSES.PL_AD_ADDRESS
,  PL_ADDRESSES.PL_AD_POSTCODE
,  PL_ADDRESSES.PL_AD_ADDRESS_USER1
,  PL_ADDRESSES.PL_AD_ADDRESS_USER2
,  DOC_LEDGER_HEADER.DLH_CHEQUE_NO
,  DOC_LEDGER_DETAIL.DLD_SETDISC_DOC


from
   DOC_LEDGER_HEADER
      left outer join   DOC_LEDGER_DETAIL on DOC_LEDGER_HEADER.DLH_PRIMARY       = DOC_LEDGER_DETAIL.DLD_HEADER_LINK
         left outer join   PL_TRANSACTIONS   on DOC_LEDGER_DETAIL.DLD_TRAN_LINK     = PL_TRANSACTIONS.PT_PRIMARY
            left outer join   PL_ACCOUNTS       on PL_TRANSACTIONS.PT_COPYSUPP         = PL_ACCOUNTS.SUCODE
               left outer join   PL_ADDRESSES      on PL_ACCOUNTS.SUCODE                  = PL_ADDRESSES.PL_AD_ACCCODE and
                                                                                            PL_ACCOUNTS.SU_REM_ADD_CDE = PL_ADDRESSES.PL_AD_CODE

      