CREATE VIEW AA_REP_WO_PRODUCT_ROUTE_VIEW

/*
** Written     :  01/03/2006 RV
** Last Amended:
**
** Used by     :  Product by Route Report.rpt
*/
AS

SELECT

WO_ROUTES.WR_ROUTE,
isnull(STK_STOCK.STK_BOM_DURATION,0) As STK_BOM_DURATION,
isnull(STK_STOCK.STK_BOM_MIN_BUILD_QUANTITY,0) As STK_BOM_MIN_BUILD_QUANTITY,
isnull(STK_STOCK.STK_BOM_BATCH_QUANTITY,0) As STK_BOM_BATCH_QUANTITY,
isnull(STK_STOCK.STKCODE,'') As STKCODE,
isnull(STK_STOCK.STKNAME,'') As STKNAME,
'ENGLISH   ' As LANGUAGE_LINK

FROM WO_ROUTES

   Inner JOIN STK_STOCK
   ON WO_ROUTES.WR_PRIMARY = STK_STOCK.STK_BOM_ROUTE_LINK