create view AA_REP_NOMINAL_EXPORT_VIEW
/*
** Written:     28/10/2005 RV
** Last Amended: 31/10/2005 RV, 01/11/2005 RV, 19/04/2006 SB
** Comments: returns all turnover and budget revisions for export crystal reports
*/
as
select
-- Display Fields
   NL_ACCOUNTS.NCODE
,  NL_ACCOUNTS.NNAME

,  NL_ACCOUNTS.NCATEGORYCODE1
,  NL_ACCOUNTS.NCATEGORYCODE2
,  NL_ACCOUNTS.NCATEGORYCODE3
,  NL_ACCOUNTS.NCATEGORYCODE4
,  NL_ACCOUNTS.NCATEGORYCODE5
,  NL_ACCOUNTS.NCATEGORYCODE6
,  NL_ACCOUNTS.NCATEGORYCODE7
,  NL_ACCOUNTS.NCATEGORYCODE8

,  NL_ACCOUNTS.NMAJORHEADCODE
,  NL_MAJORHEADING.NL_MAJORNAME

,  CAT1.NL_CATEGORYNAME                as CAT1_NAME
,  CAT2.NL_CATEGORYNAME                as CAT2_NAME
,  CAT3.NL_CATEGORYNAME                as CAT3_NAME
,  CAT4.NL_CATEGORYNAME                as CAT4_NAME
,  CAT5.NL_CATEGORYNAME                as CAT5_NAME
,  CAT6.NL_CATEGORYNAME                as CAT6_NAME
,  CAT7.NL_CATEGORYNAME                as CAT7_NAME
,  CAT8.NL_CATEGORYNAME                as CAT8_NAME

,  NL_ACCOUNTS.NTURNOVER_L1
,  NL_ACCOUNTS.NTURNOVER_L2
,  NL_ACCOUNTS.NTURNOVER_L3
,  NL_ACCOUNTS.NTURNOVER_L4
,  NL_ACCOUNTS.NTURNOVER_L5
,  NL_ACCOUNTS.NTURNOVER_L6
,  NL_ACCOUNTS.NTURNOVER_L7
,  NL_ACCOUNTS.NTURNOVER_L8
,  NL_ACCOUNTS.NTURNOVER_L9
,  NL_ACCOUNTS.NTURNOVER_L10
,  NL_ACCOUNTS.NTURNOVER_L11
,  NL_ACCOUNTS.NTURNOVER_L12
,  NL_ACCOUNTS.NTURNOVER_L13

,  NL_ACCOUNTS.NTURNOVER_C1
,  NL_ACCOUNTS.NTURNOVER_C2
,  NL_ACCOUNTS.NTURNOVER_C3
,  NL_ACCOUNTS.NTURNOVER_C4
,  NL_ACCOUNTS.NTURNOVER_C5
,  NL_ACCOUNTS.NTURNOVER_C6
,  NL_ACCOUNTS.NTURNOVER_C7
,  NL_ACCOUNTS.NTURNOVER_C8
,  NL_ACCOUNTS.NTURNOVER_C9
,  NL_ACCOUNTS.NTURNOVER_C10
,  NL_ACCOUNTS.NTURNOVER_C11
,  NL_ACCOUNTS.NTURNOVER_C12
,  NL_ACCOUNTS.NTURNOVER_C13

,  NL_ACCOUNTS.NTURNOVER_N1
,  NL_ACCOUNTS.NTURNOVER_N2
,  NL_ACCOUNTS.NTURNOVER_N3
,  NL_ACCOUNTS.NTURNOVER_N4
,  NL_ACCOUNTS.NTURNOVER_N5
,  NL_ACCOUNTS.NTURNOVER_N6
,  NL_ACCOUNTS.NTURNOVER_N7
,  NL_ACCOUNTS.NTURNOVER_N8
,  NL_ACCOUNTS.NTURNOVER_N9
,  NL_ACCOUNTS.NTURNOVER_N10
,  NL_ACCOUNTS.NTURNOVER_N11
,  NL_ACCOUNTS.NTURNOVER_N12
,  NL_ACCOUNTS.NTURNOVER_N13

--,  NL_ACCOUNTS2.N_LEVEL

,  AA_REP_NOMINAL_BUDGETS_VIEW.REVISION

,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L1
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L2
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L3
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L4
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L5
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L6
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L7
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L8
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L9
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L10
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L11
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L12
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_L13

,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C1
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C2
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C3
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C4
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C5
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C6
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C7
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C8
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C9
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C10
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C11
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C12
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_C13

,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N1
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N2
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N3
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N4
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N5
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N6
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N7
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N8
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N9
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N10
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N11
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N12
,  AA_REP_NOMINAL_BUDGETS_VIEW.BUD_N13

,  isnull( M.MAX_REVISION, 0 ) as MAX_REVISION

from NL_ACCOUNTS

   left outer join AA_REP_NOMINAL_BUDGETS_VIEW
   on NL_ACCOUNTS.NCODE = AA_REP_NOMINAL_BUDGETS_VIEW.NOMINAL

   inner join NL_MAJORHEADING
   on NL_ACCOUNTS.NMAJORHEADCODE = NL_MAJORHEADING.NL_MAJORCODE

   left outer join NL_CATEGORY CAT1
   on CAT1.NL_CAT_SORTCODE = '1' + NL_ACCOUNTS.NCATEGORYCODE1

   left outer join NL_CATEGORY CAT2
   on CAT2.NL_CAT_SORTCODE = '2' + NL_ACCOUNTS.NCATEGORYCODE2

   left outer join NL_CATEGORY CAT3
   on CAT3.NL_CAT_SORTCODE = '3' + NL_ACCOUNTS.NCATEGORYCODE3

   left outer join NL_CATEGORY CAT4
   on CAT4.NL_CAT_SORTCODE = '4' + NL_ACCOUNTS.NCATEGORYCODE4

   left outer join NL_CATEGORY CAT5
   on CAT5.NL_CAT_SORTCODE = '5' + NL_ACCOUNTS.NCATEGORYCODE5

   left outer join NL_CATEGORY CAT6
   on CAT6.NL_CAT_SORTCODE = '6' + NL_ACCOUNTS.NCATEGORYCODE6

   left outer join NL_CATEGORY CAT7
   on CAT7.NL_CAT_SORTCODE = '7' + NL_ACCOUNTS.NCATEGORYCODE7

   left outer join NL_CATEGORY CAT8
   on CAT8.NL_CAT_SORTCODE = '8' + NL_ACCOUNTS.NCATEGORYCODE8

   inner join NL_ACCOUNTS2
   on NL_ACCOUNTS.N_PRIMARY = NL_ACCOUNTS2.N_PRIMARY_2

   left merge join (
                  select B_ACCOUNT_CODE, max( B_REVISION_NUMBER ) as MAX_REVISION -- Obtain maximum revision number for account
                  from SYS_BUDGETS
                  where B_RECORD_TYPE = 'N' and B_BUDGET_TYPE = 'B'
                  group by B_ACCOUNT_CODE
             ) M on M.B_ACCOUNT_CODE = NL_ACCOUNTS.NCODE

where NL_ACCOUNTS.NCODE is not null and NL_ACCOUNTS.NCODE <> ''


