CREATE VIEW AA_REP_AGED_CREDITORS_HEADER_VIEW
/*
** Written:     13/04/2005 RV   
** Last Amended: 25/04/05 RV, 03/05/05 RV, 01/07/05 RV.
** Comments: returns selected purchase transaction headers for Aged Debtors crystal reports
*/
AS
SELECT     
PL_TRANSACTIONS.PT_TRANTYPE, 
PL_TRANSACTIONS.PT_GROSS,                       
PL_TRANSACTIONS.PT_UNALLOCATED, 
CAST (PL_TRANSACTIONS.PT_BATCH_FLAG AS BIT) AS PT_BATCH_FLAG,                
PL_TRANSACTIONS.PT_CURRENCYCODE, 
PL_TRANSACTIONS.PT_CURR_VALU, 
PL_TRANSACTIONS.PT_CURR_UNAL,                       
PL_TRANSACTIONS.PT_YEAR, 
PL_TRANSACTIONS.PT_PERIODNUMBER,
PL_TRANSACTIONS.PT_DATE,
PL_TRANSACTIONS.PT_HEADER_REF,
PL_TRANSACTIONS.PT_GROSS_BASE2, 
PL_TRANSACTIONS.PT_SUB_LEDGER,
PL_TRANSACTIONS.PT_DUEDATE,
PL_TRANSACTIONS.PT_USER1,
PL_TRANSACTIONS.PT_USER2,
PL_TRANSACTIONS.PT_USER3,
PL_TRANSACTIONS.PT_INTERNAL_REF,
PL_TRANSACTIONS.PT_PRIMARY,
PL_ACCOUNTS.SUCODE, 
PL_ACCOUNTS.SUNAME, 
PL_ACCOUNTS.SUPHONE, 
PL_ACCOUNTS.SUFAX,                       
PL_ACCOUNTS.SUCONTACT, 
PL_ACCOUNTS.SUBALANCE, 
PL_ACCOUNTS.SUSORT, 
PL_ACCOUNTS.SUUSER1,                       
PL_ACCOUNTS.SUUSER2, 
PL_ACCOUNTS.SUUSER3, 
PL_ACCOUNTS.SUTURNOVERYTD, 
PL_ACCOUNTS.SUCURRENCYCODE,                       
CAST (PL_ACCOUNTS.SU_ON_STOP AS BIT) AS SU_ON_STOP, 
PL_ACCOUNTS.SU_CREDIT_LIMIT, 
PL_ACCOUNTS.SU_EMAIL,            
PL_ACCOUNTS.SU_NOTES, 
PL_ACCOUNTS.SU_DATE_INV, 
PL_ACCOUNTS.SU_DATE_PAY, 
PL_ACCOUNTS.SU_USER_PUTIN,                       
PL_ACCOUNTS.SU_DATE_PUTIN, 
PL_ACCOUNTS.SU_DATE_EDITED, 
PL_ACCOUNTS.SU_USER_EDITED,                       
PL_ACCOUNTS.SU_LINE_DISC, 
PL_ACCOUNTS.SU_TOT_DISC, 
PL_ACCOUNTS.SU_SETT_DISC1, 
PL_ACCOUNTS.SU_SETT_DISC2,                       
PL_ACCOUNTS.SU_SETT_DAYS1, 
PL_ACCOUNTS.SU_SETT_DAYS2,                        
PL_ACCOUNTS.SU_TERMS, 
PL_ACCOUNTS.SU_DEL_CHARGE, 
PL_ACCOUNTS.SU_MIN_ORDR, 
PL_ACCOUNTS.SU_DUE_DAYS, 
PL_ACCOUNTS.SU_DEL_CHG_PCNT,
PL_ACCOUNTS.SU_A_P_DAYS,
PL_ACCOUNTS.SU_PRICE_KEY,              
PL_ACCOUNTS.SU_DUEDATE_TYPE

FROM PL_TRANSACTIONS 

  INNER JOIN PL_ACCOUNTS 
  ON PL_TRANSACTIONS.PT_COPYSUPP = PL_ACCOUNTS.SUCODE

WHERE  PT_BATCH_FLAG <> 1 And PT_UNALLOCATED <> 0