CREATE VIEW AA_REP_OUTSTANDING_PURCHASE_TRANS_VIEW
/*
** Written     :  06/10/2005 RV
** Last Amended:  12/10/2005 RV
** Comments    :  Returns all outstanding posted purchase transactions for crystal reports
**
** Used by     :  Purchase Invoices Posted with a Future Date.rpt
**                Supplier Invoices Unpaid and Over 6 Months Old.rpt
*/
AS
SELECT DISTINCT
PL_ACCOUNTS.SUCODE,
PL_ACCOUNTS.SUNAME,
PL_ACCOUNTS.SUSORT,

PL_TRANSACTIONS.PT_DATE,
PL_TRANSACTIONS.PT_YEAR,
PL_TRANSACTIONS.PT_PERIODNUMBER,
PL_TRANSACTIONS.PT_TRANTYPE,
PL_TRANSACTIONS.PT_HEADER_REF,
PL_TRANSACTIONS.PT_NETT,
PL_TRANSACTIONS.PT_VAT,
PL_TRANSACTIONS.PT_GROSS,
PL_TRANSACTIONS.PT_PRIMARY,
CAST (PL_TRANSACTIONS.PT_BATCH_FLAG AS BIT) AS PT_BATCH_FLAG,
PL_TRANSACTIONS.PT_UNALLOCATED,
PL_TRANSACTIONS.PT_ALOC_POINTER,
CAST (PL_TRANSACTIONS.PT_QUERY_FLAG AS BIT) AS PT_QUERY_FLAG,
CAST (PL_TRANSACTIONS.PT_DONOTCHASE AS BIT) AS PT_DONOTCHASE,
PL_TRANSACTIONS.PT_SUB_LEDGER,

PL_ACCOUNTS2.SU_LEVEL,
'ENGLISH' As LANGUAGE_LINK,   --used to link to language view for Dimensions ACR's.

SYS_TAX_AUDIT.TAXAUDIT_REF

FROM PL_ACCOUNTS

  INNER JOIN PL_TRANSACTIONS
  ON PL_ACCOUNTS.SUCODE = PL_TRANSACTIONS.PT_COPYSUPP

  INNER JOIN PL_ACCOUNTS2
  ON PL_ACCOUNTS.SU_PRIMARY = PL_ACCOUNTS2.SU_PRIMARY_2

  INNER JOIN SL_PL_NL_DETAIL
  ON PL_TRANSACTIONS.PT_HEADER_KEY = SL_PL_NL_DETAIL.DET_HEADER_KEY

  LEFT OUTER JOIN SYS_TAX_AUDIT
  ON SL_PL_NL_DETAIL.DET_VAT_RETURN_PRIMARY = SYS_TAX_AUDIT.TAXAUDIT_PRIMARY

WHERE   PT_BATCH_FLAG = 0
   And SL_PL_NL_DETAIL.DET_TYPE = 'INV'

