CREATE VIEW AA_REP_NOMINAL_PROFIT_LOSS_TURNOVER_VIEW
/*
** Written:      01/11/2005 RV   
** Last Amended: 02/11/2005 RV, 05/04/2006 SH
** Comments: Returns Nominal Turnover for Profit and Loss accounts for crystal reports
*/
as

select

N1.NCODE,
N1.NNAME, 
Y.NOMINAL_YEAR, 

N1.NCATEGORYCODE1,
N1.NCATEGORYCODE2,
N1.NCATEGORYCODE3,
N1.NCATEGORYCODE4,
N1.NCATEGORYCODE5,
N1.NCATEGORYCODE6,
N1.NCATEGORYCODE7,
N1.NCATEGORYCODE8,
N1.NMAJORHEADCODE,
N1.NCURRENCYCODE,
1 as HOME_VALUES,

N2.N_LEVEL,

case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C1
   when 1 then N1.NTURNOVER_N1
   else N1.NTURNOVER_L1
end as PERIOD1,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C2
   when 1 then N1.NTURNOVER_N2
   else N1.NTURNOVER_L2
end as PERIOD2,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C3
   when 1 then N1.NTURNOVER_N3
   else N1.NTURNOVER_L3
end as PERIOD3,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C4
   when 1 then N1.NTURNOVER_N4
   else N1.NTURNOVER_L4
end as PERIOD4,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C5
   when 1 then N1.NTURNOVER_N5
   else N1.NTURNOVER_L5
end as PERIOD5,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C6
   when 1 then N1.NTURNOVER_N6
   else N1.NTURNOVER_L6
end as PERIOD6,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C7
   when 1 then N1.NTURNOVER_N7
   else N1.NTURNOVER_L7
end as PERIOD7,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C8
   when 1 then N1.NTURNOVER_N8
   else N1.NTURNOVER_L8
end as PERIOD8,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C9
   when 1 then N1.NTURNOVER_N9
   else N1.NTURNOVER_L9
end as PERIOD9,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C10
   when 1 then N1.NTURNOVER_N10
   else N1.NTURNOVER_L10
end as PERIOD10,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C11
   when 1 then N1.NTURNOVER_N11
   else N1.NTURNOVER_L11
end as PERIOD11,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C12
   when 1 then N1.NTURNOVER_N12
   else N1.NTURNOVER_L12
end as PERIOD12,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C13
   when 1 then N1.NTURNOVER_N13
   else N1.NTURNOVER_L13
end as PERIOD13,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C1 + N1.NTURNOVER_C2 + N1.NTURNOVER_C3 + N1.NTURNOVER_C4 + N1.NTURNOVER_C5 + N1.NTURNOVER_C6 + N1.NTURNOVER_C7 + N1.NTURNOVER_C8 + N1.NTURNOVER_C9 + N1.NTURNOVER_C10 + N1.NTURNOVER_C11 + N1.NTURNOVER_C12 + N1.NTURNOVER_C13
   when 1 then N1.NTURNOVER_N1 + N1.NTURNOVER_N2 + N1.NTURNOVER_N3 + N1.NTURNOVER_N4 + N1.NTURNOVER_N5 + N1.NTURNOVER_N6 + N1.NTURNOVER_N7 + N1.NTURNOVER_N8 + N1.NTURNOVER_N9 + N1.NTURNOVER_N10 + N1.NTURNOVER_N11 + N1.NTURNOVER_N12 + N1.NTURNOVER_N13
   else N1.NTURNOVER_L1 + N1.NTURNOVER_L2 + N1.NTURNOVER_L3 + N1.NTURNOVER_L4 + N1.NTURNOVER_L5 + N1.NTURNOVER_L6 + N1.NTURNOVER_L7 + N1.NTURNOVER_L8 + N1.NTURNOVER_L9 + N1.NTURNOVER_L10 + N1.NTURNOVER_L11 + N1.NTURNOVER_L12 + N1.NTURNOVER_L13
end as TURNOVER_YTD

from NL_ACCOUNTS N1
   inner join NL_ACCOUNTS2 N2 on N1.N_PRIMARY = N2.N_PRIMARY_2 
   cross join (select 0 as NOMINAL_YEAR union select 1 union select 2) Y

where N1.NMAJORHEADCODE <= 6

union all

select

N1.NCODE,
N1.NNAME, 
Y.NOMINAL_YEAR, 

N1.NCATEGORYCODE1,
N1.NCATEGORYCODE2,
N1.NCATEGORYCODE3,
N1.NCATEGORYCODE4,
N1.NCATEGORYCODE5,
N1.NCATEGORYCODE6,
N1.NCATEGORYCODE7,
N1.NCATEGORYCODE8,
N1.NMAJORHEADCODE,
N1.NCURRENCYCODE,
0 as HOME_VALUES,

N2.N_LEVEL,

case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C1_C
   when 1 then N1.NTURNOVER_N1_C
   else N1.NTURNOVER_L1_C
end as PERIOD1,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C2_C
   when 1 then N1.NTURNOVER_N2_C
   else N1.NTURNOVER_L2_C
end as PERIOD2,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C3_C
   when 1 then N1.NTURNOVER_N3_C
   else N1.NTURNOVER_L3_C
end as PERIOD3,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C4_C
   when 1 then N1.NTURNOVER_N4_C
   else N1.NTURNOVER_L4_C
end as PERIOD4,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C5_C
   when 1 then N1.NTURNOVER_N5_C
   else N1.NTURNOVER_L5_C
end as PERIOD5,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C6_C
   when 1 then N1.NTURNOVER_N6_C
   else N1.NTURNOVER_L6_C
end as PERIOD6,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C7_C
   when 1 then N1.NTURNOVER_N7_C
   else N1.NTURNOVER_L7_C
end as PERIOD7,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C8_C
   when 1 then N1.NTURNOVER_N8_C
   else N1.NTURNOVER_L8_C
end as PERIOD8,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C9_C
   when 1 then N1.NTURNOVER_N9_C
   else N1.NTURNOVER_L9_C
end as PERIOD9,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C10_C
   when 1 then N1.NTURNOVER_N10_C
   else N1.NTURNOVER_L10_C
end as PERIOD10,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C11_C
   when 1 then N1.NTURNOVER_N11_C
   else N1.NTURNOVER_L11_C
end as PERIOD11,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C12_C
   when 1 then N1.NTURNOVER_N12_C
   else N1.NTURNOVER_L12_C
end as PERIOD12,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C13_C
   when 1 then N1.NTURNOVER_N13_C
   else N1.NTURNOVER_L13_C
end as PERIOD13,
case Y.NOMINAL_YEAR
   when 0 then N1.NTURNOVER_C1_C + N1.NTURNOVER_C2_C + N1.NTURNOVER_C3_C + N1.NTURNOVER_C4_C + N1.NTURNOVER_C5_C + N1.NTURNOVER_C6_C + N1.NTURNOVER_C7_C + N1.NTURNOVER_C8_C + N1.NTURNOVER_C9_C + N1.NTURNOVER_C10_C + N1.NTURNOVER_C11_C + N1.NTURNOVER_C12_C + N1.NTURNOVER_C13_C
   when 1 then N1.NTURNOVER_N1_C + N1.NTURNOVER_N2_C + N1.NTURNOVER_N3_C + N1.NTURNOVER_N4_C + N1.NTURNOVER_N5_C + N1.NTURNOVER_N6_C + N1.NTURNOVER_N7_C + N1.NTURNOVER_N8_C + N1.NTURNOVER_N9_C + N1.NTURNOVER_N10_C + N1.NTURNOVER_N11_C + N1.NTURNOVER_N12_C + N1.NTURNOVER_N13_C
   else N1.NTURNOVER_L1_C + N1.NTURNOVER_L2_C + N1.NTURNOVER_L3_C + N1.NTURNOVER_L4_C + N1.NTURNOVER_L5_C + N1.NTURNOVER_L6_C + N1.NTURNOVER_L7_C + N1.NTURNOVER_L8_C + N1.NTURNOVER_L9_C + N1.NTURNOVER_L10_C + N1.NTURNOVER_L11_C + N1.NTURNOVER_L12_C + N1.NTURNOVER_L13_C
end as TURNOVER_YTD

from NL_ACCOUNTS N1
   inner join NL_ACCOUNTS2 N2 on N1.N_PRIMARY = N2.N_PRIMARY_2 
   inner join SYS_DATAINFO D with (nolock) on D.SYS_PRIMARY = 1
   cross join (select 0 as NOMINAL_YEAR union select 1 union select 2) Y

where N1.NMAJORHEADCODE <= 6 and N1.NCURRENCYCODE <> D.HOME_CURR_SYMBL