CREATE VIEW AA_REP_WO_OVERDUE_ORDERS_VIEW

/*
** Written     :  06/03/2006 RV
** Last Amended:
**
** Used by     :  Overdue Works Orders Report.rpt
*/
AS

select

WO_ORDER_NUMBER,
WO_TOP_LEVEL_ORDER_NUMBER,
WO_END_DATE,WO_QUANTITY,
WO_QUANTITY_BUILT,
WO_SORT_KEY,
WO_PRIORITY,
WO_START_DATE,
STKCODE,
STKNAME,
WR_ROUTE,
'ENGLISH   ' As LANGUAGE_LINK

from WO_ORDERS

   LEFT OUTER JOIN STK_STOCK
   ON STK_PRIMARY = WO_STOCK_LINK

   LEFT OUTER JOIN WO_ROUTES ON
   WR_PRIMARY = WO_ROUTE_LINK

where  WO_STATUS < 10