create view    AA_REP_PL_STATEMENTS_SEARCH_VIEW

/*
** Written     :  10/08/2005 DB
** Last Amended:  10/08/2005 DB
** Comments    :  Returns selected sales transactions for statement reports
*/

as

select top 100 percent
   PL_ACCOUNTS.SUCODE
,  PL_ACCOUNTS.SUBALANCE
,  PL_ACCOUNTS.SUTURNOVERYTD
,  PL_ACCOUNTS.SUSORT
,  PL_ACCOUNTS.SUUSER1
,  PL_ACCOUNTS.SUUSER2
,  PL_ACCOUNTS.SUUSER3
,  PL_ACCOUNTS.SU_DATE_INV
,  PL_ACCOUNTS.SUCURRENCYCODE
,  PL_ACCOUNTS.SU_CREDIT_LIMIT
,  PL_ACCOUNTS.SU_ON_STOP
,  PL_TRANSACTIONS.PT_PRIMARY
,  PL_TRANSACTIONS.PT_UNALLOCATED
,  PL_TRANSACTIONS.PT_CURRENCYCODE
,  PL_TRANSACTIONS.PT_DUEDATE
,  PL_TRANSACTIONS.PT_ALOC_POINTER
,  PL_TRANSACTIONS.PT_PERIODNUMBER
,  PL_TRANSACTIONS.PT_YEAR
,  PL_TRANSACTIONS.PT_DATE
,  PL_TRANSACTIONS.PT_HEADER_KEY
,  PL_TRANSACTIONS.PT_ALLOC_PERIOD
,  PL_TRANSACTIONS.PT_ALLOC_YEAR
   from
      PL_ACCOUNTS
            inner join PL_TRANSACTIONS on PL_TRANSACTIONS.PT_COPYSUPP   = PL_ACCOUNTS.SUCODE
   where
      isnull(PT_BATCH_FLAG,0)<>1
   order by
      PL_ACCOUNTS.SUCODE
   ,  PT_DATE
   ,  PL_TRANSACTIONS.PT_PRIMARY