CREATE VIEW AA_REP_WO_REQUIREMENT_VIEW

/*
** Written     :  06/03/2006 RV
** Last Amended:  26/04/2006 RV
**
** Used by     :  Works Order Requirement Report.rpt
*/
AS

select

OH_ORDER_NUMBER,
OH_DATE,
OH_REQUIREDDATE,
CUCODE,
CUNAME,
CU_STOCK_ALLOCATION_PRIORITY,
OD_QTYORD,
OD_QTYINVD,
STKCODE,
STKNAME,
STK_SORT_KEY,
STK_PHYSICAL,
STK_RESERVE_OUT,
STK_BACK_ORDER_QTY,
STK_WO_ALLOC_QUANTITY,
STK_WO_UNALLOC_QUANTITY,
STK_ORDER_IN,
STK_WO_FREE_WIP_QUANTITY,
STK_WO_WIP_SOP_QUANTITY,
WR_ROUTE,
case when STK_MULTILOCATN <> 1 then
   case when STK_USR_QTY = 'P' Then STK_PHYSICAL
   else case when STK_FREE_METHOD = 'P' Then
         (STK_PHYSICAL-(STK_RESERVE_OUT+STK_BACK_ORDER_QTY)+STK_ORDER_IN)
           when STK_FREE_METHOD = 'F' Then
         (STK_PHYSICAL-(STK_RESERVE_OUT+STK_BACK_ORDER_QTY))
        when STK_FREE_METHOD = 'O' Then
         (STK_PHYSICAL-STK_RESERVE_OUT+STK_ORDER_IN)
        when STK_FREE_METHOD = 'A' Then
         (STK_PHYSICAL-STK_RESERVE_OUT)
        end
   end

     when STK_MULTILOCATN = 1 then
   case when STK_USR_QTY = 'P' Then LOC_PHYSICAL
   else case when STK_FREE_METHOD = 'P' Then
         (LOC_PHYSICAL-(LOC_RESERVE_OUT+LOC_BACK_ORDER_QTY)+LOC_ORDER_IN)
             when STK_FREE_METHOD = 'F' Then
         (LOC_PHYSICAL-(LOC_RESERVE_OUT+LOC_BACK_ORDER_QTY))
        when STK_FREE_METHOD = 'O' Then
         (LOC_PHYSICAL-LOC_RESERVE_OUT+LOC_ORDER_IN)
        when STK_FREE_METHOD = 'A' Then
         (LOC_PHYSICAL-LOC_RESERVE_OUT)
        end
   end

end STOCK_FREE,

'ENGLISH   ' As LANGUAGE_LINK

from ORD_HEADER

   LEFT OUTER JOIN SL_ACCOUNTS
   ON CUCODE = OH_ACCOUNT_ORDER

   LEFT OUTER JOIN SL_ACCOUNTS2
   ON CU_PRIMARY_2 = CU_PRIMARY

   LEFT OUTER JOIN ORD_DETAIL
   ON OD_ORDER_NUMBER = OH_ORDER_NUMBER

   LEFT OUTER JOIN WO_ORDERS
   ON WO_ORDER_NUMBER = OH_ORDER_NUMBER

   LEFT OUTER JOIN STK_STOCK
   ON STKCODE = OD_STOCK_CODE

   LEFT OUTER JOIN WO_ROUTES
   ON WR_PRIMARY = STK_BOM_ROUTE_LINK

   Left outer join STK_LOCATION
   On LOC_STOCK_CODE = STKCODE And WO_SUB_ANALYSIS_LINK = LOC_PRIMARY

   Join SYS_DATAINFO ON SYS_PRIMARY = 1
   Join SYS_DATAINFO2 ON SYS_PRIMARY_2 = 1

where  isnull(OD_WO_NUMBER,0) = 0 and OD_BATCH_FLAG = 1 and OD_ENTRY_TYPE = 'S' and STK_ASSEMBLY = 'A'

--order by STKCODE

