CREATE VIEW AA_REP_WO_VARIANCE_VIEW

/*
** Written     :  07/03/2006 RV
** Last Amended:
**
** Used by     :  Works Order Variance Report.rpt
*/
AS

select

WO_ORDER_NUMBER,
WO_TOP_LEVEL_ORDER_NUMBER,
WO_QUANTITY,
WO_QUANTITY_BUILT,
WO_MAT_ESTIMATED_COST,
WO_MAT_ACTUAL_COST,
WO_LAB_ESTIMATED_COST,
WO_LAB_ACTUAL_COST,
STKCODE,
STKNAME,

'ENGLISH   ' As LANGUAGE_LINK

from WO_ORDERS

   LEFT OUTER JOIN STK_STOCK
   ON STK_PRIMARY = WO_STOCK_LINK

where isnull(WO_QUANTITY_BUILT,0) > 0

--order by STKCODE

