create view AA_REP_SALES_TRAN_DETAIL_VIEW

/*
** Written:     07/03/2005 RV   
** Last Amended: 29/03/05 RV, 03/06/2005 LM
** Comments: returns all sales transaction details for crystal reports
*/

AS
SELECT     
SL_TRANSACTIONS.ST_COPYCUST, 
SL_TRANSACTIONS.ST_DATE, 
SL_TRANSACTIONS.ST_YEAR, 
SL_TRANSACTIONS.ST_PERIODNUMBER, 
SL_TRANSACTIONS.ST_HEADER_REF,                       
SL_TRANSACTIONS.ST_NETT,
SL_TRANSACTIONS.ST_VAT, 
SL_TRANSACTIONS.ST_GROSS, 
SL_TRANSACTIONS.ST_PRIMARY, 
CAST (SL_TRANSACTIONS.ST_BATCH_FLAG AS BIT) AS ST_BATCH_FLAG, 
SL_TRANSACTIONS.ST_UNALLOCATED, 
SL_TRANSACTIONS.ST_ALOC_POINTER, 
CAST (SL_TRANSACTIONS.ST_QUERY_FLAG AS BIT) AS ST_QUERY_FLAG, 
CAST (SL_TRANSACTIONS.ST_DONOTCHASE AS BIT) AS ST_DONOTCHASE, 
SL_TRANSACTIONS.ST_BATCH_REF, 
SL_TRANSACTIONS.ST_CURRENCYRATE, 
SL_TRANSACTIONS.ST_CURR_TYPE, 
SL_TRANSACTIONS.ST_USER1, 
SL_TRANSACTIONS.ST_USER2, 
SL_TRANSACTIONS.ST_USER3, 
CAST (SL_TRANSACTIONS.ST_CENTRALISED AS BIT) AS ST_CENTRALISED,
SL_TRANSACTIONS.ST_HEADER_KEY, 

SL_ACCOUNTS.CUSORT,   
        
SL_PL_NL_DETAIL.DET_DESCRIPTION, 
SL_PL_NL_DETAIL.DET_STOCK_CODE, 
SL_PL_NL_DETAIL.DET_ANALYSIS,                       
SL_PL_NL_DETAIL.DET_NOMINALDR, 
SL_PL_NL_DETAIL.DET_NOMINALCR, 
SL_PL_NL_DETAIL.DET_NOMINALVAT,                       
SL_PL_NL_DETAIL.DET_CURR_CODE, 
SL_PL_NL_DETAIL.DET_CURR_RATE, 
SL_PL_NL_DETAIL.DET_CURR_NETT, 
SL_PL_NL_DETAIL.DET_CURR_TAX, 
SL_PL_NL_DETAIL.DET_CURR_GROSS, 
SL_PL_NL_DETAIL.DET_TRI_RATE1, 
SL_PL_NL_DETAIL.DET_TRI_RATE2, 
SL_PL_NL_DETAIL.DET_CURR_L_DISC, 
SL_PL_NL_DETAIL.DET_CURR_T_DISC, 
SL_PL_NL_DETAIL.DET_NETT_BASE2, 
SL_PL_NL_DETAIL.DET_VAT_BASE2, 
SL_PL_NL_DETAIL.DET_GROSS_BASE2, 
SL_PL_NL_DETAIL.DET_L_DISC_BASE2, 
SL_PL_NL_DETAIL.DET_T_DISC_BASE2, 
SL_PL_NL_DETAIL.DET_BASE2_RATE, 
SL_PL_NL_DETAIL.DET_CURR_RTEFLG, 
SL_PL_NL_DETAIL.DET_TRI_RATECHNG2, 
SL_PL_NL_DETAIL.DET_NETT, 
SL_PL_NL_DETAIL.DET_VAT, 
SL_PL_NL_DETAIL.DET_VATCODE, 
SL_PL_NL_DETAIL.DET_GROSS, 
SL_PL_NL_DETAIL.DET_PRIMARY,
SL_PL_NL_DETAIL.DET_L_DISCOUNT, 
SL_PL_NL_DETAIL.DET_T_DISCOUNT, 
SL_PL_NL_DETAIL.DET_DIMENSION1,
SL_PL_NL_DETAIL.DET_DIMENSION2, 
SL_PL_NL_DETAIL.DET_DIMENSION3, 
SL_PL_NL_DETAIL.DET_SUB_LEDGER,
SL_PL_NL_DETAIL.DET_TYPE,

SL_ANALYSIS.SACODE, 
SL_ANALYSIS.SANAME, 

STK_STOCK.STKCODE, 
STK_STOCK.STKNAME, 

PRC_PRICE_RECS.PRCODE, 
PRC_PRICE_RECS.PRNAME, 

CST_COSTHEADER.CH_CODE, 
CST_COSTHEADER.CH_NAME, 

CST_COSTCENTRE.CC_CODE, 
CST_COSTCENTRE.CC_NAME, 

NL_DR.NNAME AS DR_NAME, 
NL_DR.N_CENTRALISED AS DR_CENTRAL, 
                      
NL_CR.NNAME AS CR_NAME,
NL_CR.N_CENTRALISED AS CR_CENTRAL,

NL_VAT.NNAME AS VAT_NAME

                     
FROM  SL_TRANSACTIONS 

  INNER JOIN SL_PL_NL_DETAIL with(index(DET_HEADER_KEY)) 
  ON SL_TRANSACTIONS.ST_HEADER_KEY = SL_PL_NL_DETAIL.DET_HEADER_KEY

  INNER JOIN SL_ACCOUNTS 
  ON SL_TRANSACTIONS.ST_COPYCUST = SL_ACCOUNTS.CUCODE

  INNER JOIN SL_ANALYSIS 
  ON SL_PL_NL_DETAIL.DET_ANALYSIS = SL_ANALYSIS.SACODE

  INNER JOIN NL_ACCOUNTS NL_DR
  ON SL_PL_NL_DETAIL.DET_NOMINALDR = NL_DR.NCODE

  INNER JOIN NL_ACCOUNTS NL_CR 
  ON SL_PL_NL_DETAIL.DET_NOMINALCR = NL_CR.NCODE

  LEFT OUTER JOIN NL_ACCOUNTS NL_VAT 
  ON SL_PL_NL_DETAIL.DET_NOMINALVAT = NL_VAT.NCODE

  LEFT OUTER JOIN CST_COSTCENTRE 
  ON CC_CONCAT_CODES = DET_COSTHEADER + SPACE(10 - LEN(DET_COSTHEADER)) + DET_COSTCENTRE 
  
  LEFT OUTER JOIN CST_COSTHEADER
  ON SL_PL_NL_DETAIL.DET_COSTHEADER = CST_COSTHEADER.CH_CODE
  
  LEFT OUTER JOIN PRC_PRICE_RECS 
  ON SL_PL_NL_DETAIL.DET_PRICE_CODE = PRC_PRICE_RECS.PRCODE

  LEFT OUTER JOIN STK_STOCK
  ON SL_PL_NL_DETAIL.DET_STOCK_CODE = STK_STOCK.STKCODE

WHERE (SL_PL_NL_DETAIL.DET_TYPE NOT IN ('MIN', 'MPA', 'MAD', 'MAC', 'MCR'))
