create view AA_REP_PL_STATEMENTS_VIEW
/*
** Written     :  01/08/2005 RV
** Last Amended:  10/08/2005 RV, 11/08/05 RV, 27/09/05 RV, 12/04/2006 RV
** Comments    :  Returns selected purchase transactions for statement reports
*/
as
select top 100 percent
   PL_ACCOUNTS.SUCODE
,  PL_ACCOUNTS.SUNAME
,  PL_ACCOUNTS.SUSORT
,  PL_ACCOUNTS.SUBALANCE
,  PL_ACCOUNTS.SUBALANCE_C
,  PL_ACCOUNTS.SUTURNOVERYTD
,  PL_ACCOUNTS.SUUSER1
,  PL_ACCOUNTS.SUUSER2
,  PL_ACCOUNTS.SUUSER3
,  PL_ACCOUNTS.SU_CREDIT_LIMIT
,  PL_ACCOUNTS.SU_ON_STOP
,  PL_ACCOUNTS.SUPHONE

,  DOC_LEDGER_HEADER.DLH_DOC_DATE
,  DOC_LEDGER_HEADER.DLH_PRIMARY
,  DOC_LEDGER_HEADER.DLH_DOC_TYPE
,  DOC_LEDGER_HEADER.DLH_CURRSYMBOL
,  DOC_LEDGER_HEADER.DLH_FAX_HEADER
,  DOC_LEDGER_HEADER.DLH_COMP_ADDRESS
,  Isnull(DOC_LEDGER_HEADER.DLH_OPTION1,0) as DLH_OPTION1
,  Isnull(DOC_LEDGER_HEADER.DLH_OPTION2,0) as DLH_OPTION2

,  PL_TRANSACTIONS.PT_DATE
,  PL_TRANSACTIONS.PT_TRANTYPE
,  PL_TRANSACTIONS.PT_HEADER_REF
,  PL_TRANSACTIONS.PT_DESCRIPTION
,  PL_TRANSACTIONS.PT_QUERY_FLAG
,  PL_TRANSACTIONS.PT_DUEDATE
,  PL_TRANSACTIONS.PT_CURRENCYCODE
,  PL_TRANSACTIONS.PT_PRIMARY

,  DOC_LEDGER_DETAIL.DLD_AGED_DOC
,  DOC_LEDGER_DETAIL.DLD_AGED2_DOC
,  DOC_LEDGER_DETAIL.DLD_AGED3_DOC
,  DOC_LEDGER_DETAIL.DLD_AGED4_DOC
,  DOC_LEDGER_DETAIL.DLD_AGED5_DOC
,  DOC_LEDGER_DETAIL.DLD_DRVAL_DOC
,  DOC_LEDGER_DETAIL.DLD_CRVAL_DOC
,  DOC_LEDGER_DETAIL.DLD_OSVAL_DOC
,  DOC_LEDGER_DETAIL.DLD_UNALLOC_DOC
,  DOC_LEDGER_DETAIL.DLD_HEADER_LINK

,  PL_ADDRESSES.PL_AD_ADDRESS
,  PL_ADDRESSES.PL_AD_ADDRESS_USER1
,  PL_ADDRESSES.PL_AD_ADDRESS_USER2
,  PL_ADDRESSES.PL_AD_POSTCODE
   from
      DOC_LEDGER_HEADER
         inner join DOC_LEDGER_DETAIL  on DOC_LEDGER_HEADER.DLH_PRIMARY    = DOC_LEDGER_DETAIL.DLD_HEADER_LINK
            inner join PL_TRANSACTIONS    on DOC_LEDGER_DETAIL.DLD_TRAN_LINK  = PL_TRANSACTIONS.PT_PRIMARY
               inner join PL_ACCOUNTS        on PL_TRANSACTIONS.PT_COPYSUPP      = PL_ACCOUNTS.SUCODE
                  inner join PL_ADDRESSES       on   cast(PL_ACCOUNTS.SUCODE as char(10)) + cast(PL_ACCOUNTS.SU_ST_ADD_CODE as varchar(6)) = PL_ADDRESSES.PL_AD_CON_CODE
                     inner join PL_ACCOUNTS2       on PL_ACCOUNTS.SU_PRIMARY           = PL_ACCOUNTS2.SU_PRIMARY_2
   order by
      DOC_LEDGER_HEADER.DLH_PRIMARY