CREATE VIEW AA_REP_PURCHASE_TRAN_HEADER_VIEW
/*
** Written:     12/04/2005 RV   
** Last Amended: 11/05/05 RV.
** Comments: returns all purchase transaction headers for crystal reports
*/
AS
SELECT     
PL_ACCOUNTS.SUCODE, 
PL_ACCOUNTS.SUNAME, 
PL_ACCOUNTS.SUSORT,
 
PL_TRANSACTIONS.PT_DATE, 
PL_TRANSACTIONS.PT_YEAR, 
PL_TRANSACTIONS.PT_PERIODNUMBER, 
PL_TRANSACTIONS.PT_TRANTYPE, 
PL_TRANSACTIONS.PT_HEADER_REF, 
PL_TRANSACTIONS.PT_NETT, 
PL_TRANSACTIONS.PT_VAT, 
PL_TRANSACTIONS.PT_GROSS, 
PL_TRANSACTIONS.PT_PRIMARY, 
CAST (PL_TRANSACTIONS.PT_BATCH_FLAG AS BIT) AS PT_BATCH_FLAG, 
PL_TRANSACTIONS.PT_UNALLOCATED, 
PL_TRANSACTIONS.PT_ALOC_POINTER, 
CAST (PL_TRANSACTIONS.PT_QUERY_FLAG AS BIT) AS PT_QUERY_FLAG, 
CAST (PL_TRANSACTIONS.PT_DONOTCHASE AS BIT) AS PT_DONOTCHASE, 
PL_TRANSACTIONS.PT_BATCH_REF, 
PL_TRANSACTIONS.PT_CURRENCYCODE, 
PL_TRANSACTIONS.PT_CURRENCYRATE, 
PL_TRANSACTIONS.PT_CURR_VALU, 
PL_TRANSACTIONS.PT_TRI_RATE1, 
PL_TRANSACTIONS.PT_TRI_RATE2, 
PL_TRANSACTIONS.PT_CURR_TYPE, 
PL_TRANSACTIONS.PT_CURR_UNAL, 
PL_TRANSACTIONS.PT_CURR_NETT, 
PL_TRANSACTIONS.PT_CURR_TAX, 
PL_TRANSACTIONS.PT_CURRENCYRTCH, 
PL_TRANSACTIONS.PT_TRI_RATECHNG2,                       
PL_TRANSACTIONS.PT_NETT_BASE2, 
PL_TRANSACTIONS.PT_VAT_BASE2, 
PL_TRANSACTIONS.PT_GROSS_BASE2, 
PL_TRANSACTIONS.PT_L_DISC_BASE2, 
PL_TRANSACTIONS.PT_T_DISC_BASE2, 
PL_TRANSACTIONS.PT_BASE2_RATE, 
PL_TRANSACTIONS.PT_USER1, 
PL_TRANSACTIONS.PT_USER2, 
PL_TRANSACTIONS.PT_USER3, 
PL_TRANSACTIONS.PT_SUB_LEDGER, 
PL_TRANSACTIONS.PT_ORDER_NUMBER, 
PL_TRANSACTIONS.PT_DESCRIPTION, 
PL_TRANSACTIONS.PT_USER_PUTIN, 
PL_TRANSACTIONS.PT_DATE_PUTIN, 
PL_TRANSACTIONS.PT_DUEDATE, 
PL_TRANSACTIONS.PT_ANTICPAYDATE,
PL_TRANSACTIONS.PT_HEADER_KEY,
PL_TRANSACTIONS.PT_ACQUISTN_TAX,
PL_TRANSACTIONS.PT_ACQUISTN_BASE2,
PL_TRANSACTIONS.PT_INTERNAL_REF,
 
PL_ACCOUNTS2.SU_LEVEL

FROM PL_ACCOUNTS 

  INNER JOIN PL_TRANSACTIONS 
  ON PL_ACCOUNTS.SUCODE = PL_TRANSACTIONS.PT_COPYSUPP 

  INNER JOIN PL_ACCOUNTS2 
  ON PL_ACCOUNTS.SU_PRIMARY = PL_ACCOUNTS2.SU_PRIMARY_2
