create view AA_REP_BULK_RECEIPTS_VIEW

as

select
   DLH_PRIMARY
,  DLH_DOC_TYPE
,  DLH_DOC_DATE
,  DLH_COMP_ADDRESS
,  DLD_HEADER_LINK
,  DLD_CRVAL_DOC
,  DLD_DRVAL_DOC
,  DLD_SETDISC_DOC
,  DLD_OSVAL_DOC
,  DLD_REMITVAL_DOC
,  ST_TRANTYPE
,  ST_HEADER_REF
,  ST_DATE
,  ST_DESCRIPTION
,  CAST(ST_QUERY_FLAG AS BIT) AS ST_QUERY_FLAG
,  ST_CURRENCYCODE
,  CUCODE
,  CUNAME
,  AD_ACCOUNTNAME
,  AD_ADDRESS
,  AD_ADDRESS_USER1
,  AD_ADDRESS_USER2
,  AD_POSTCODE

from
   DOC_LEDGER_HEADER
      inner join DOC_LEDGER_DETAIL  on DLD_HEADER_LINK=DLH_PRIMARY
         inner join SL_TRANSACTIONS    on ST_PRIMARY=DLD_TRAN_LINK
            inner join SL_ACCOUNTS        on CUCODE=ST_COPYCUST
               inner join SL_ADDRESSES       on (AD_ACC_CODE=CUCODE) and (AD_CODE=CU_STAT_ADD_CDE)
