CREATE VIEW AA_REP_PL_CASH_VAT_VIEW
/*
** Written     :  21/12/2005 RV
** Last Amended:  03/01/2006 RV, 25/01/2006 RV, 27/11/2006 RV, 25/01/2007 RV
** Comments    :  Returns purchase transactions for cash VAT crystal reports
**
** Used by     : Purchase Ledger - Cash VAT Guidance Report.rpt
*/
(
PAY_PT_VAT,
PAY_PT_GROSS,
PAY_PT_UNALLOCATED,
PAY_PT_BATCH_FLAG,
PAY_PT_DATE,
PAY_PT_TRANTYPE,
PAY_PT_COPYSUPP,
PAY_PT_PRIMARY,
PAY_PT_HEADER_KEY,
PAY_PT_HEADER_REF,
PAY_PT_CURRENCYCODE,
PAY_PT_CURR_VALU,
PAY_PT_CURR_UNAL,
PAY_PT_CURR_TAX,
PAY_PT_P_AL_VALUE_HOME,
PAY_PT_P_AL_VALUE_CURR,
PAY_PT_P_AL_REFERENCE,
PAY_PT_P_AL_DATE,
PAY_PT_P_AL_YEAR,
PAY_PT_P_AL_PERIOD,
PAY_P_AL_PRIMARY,

INV_PT_VAT,
INV_PT_GROSS,
INV_PT_UNALLOCATED,
INV_PT_BATCH_FLAG,
INV_PT_DATE,
INV_PT_TRANTYPE,
INV_PT_COPYSUPP,
INV_PT_PRIMARY,
INV_PT_HEADER_KEY,
INV_PT_HEADER_REF,
INV_PT_CURRENCYCODE,
INV_PT_CURR_VALU,
INV_PT_CURR_UNAL,
INV_PT_CURR_TAX,
INV_P_AL_VALUE_HOME,
INV_P_AL_VALUE_CURR,
INV_P_AL_REFERENCE,
INV_P_AL_DATE,
INV_P_AL_YEAR,
INV_P_AL_PERIOD,
VAT_ALERT,
INV_P_AL_PRIMARY
)
AS
Select
PL_PAY.PT_VAT,
PL_PAY.PT_GROSS,
PL_PAY.PT_UNALLOCATED,
PL_PAY.PT_BATCH_FLAG,
PL_PAY.PT_DATE,
PL_PAY.PT_TRANTYPE,
PL_PAY.PT_COPYSUPP,
PL_PAY.PT_PRIMARY,
PL_PAY.PT_HEADER_KEY,
PL_PAY.PT_HEADER_REF,
PL_PAY.PT_CURRENCYCODE,
PL_PAY.PT_CURR_VALU,
PL_PAY.PT_CURR_UNAL,
PL_PAY.PT_CURR_TAX,
ALLOC_PAY.P_AL_VALUE_HOME,
ALLOC_PAY.P_AL_VALUE_CURR,
ALLOC_PAY.P_AL_REFERENCE,
ALLOC_PAY.P_AL_DATE,
ALLOC_PAY.P_AL_YEAR,
ALLOC_PAY.P_AL_PERIOD,
ALLOC_PAY.P_AL_PRIMARY,

'', -- INV_PT_VAT,
'', -- INV_PT_GROSS,
'', -- INV_PT_UNALLOCATED,
'', -- INV_PT_BATCH_FLAG,
'', -- INV_PT_DATE,
'', -- INV_PT_TRANTYPE,
'', -- INV_PT_COPYSUPP,
'', -- INV_PT_PRIMARY,
'', -- INV_PT_HEADER_KEY,
'', -- INV_PT_HEADER_REF,
'', -- INV_PT_CURRENCYCODE,
'', -- INV_PT_CURR_VALU,
'', -- INV_PT_CURR_UNAL,
'', -- INV_PT_CURR_TAX,
'', -- INV_P_AL_VALUE_HOME,
'', -- INV_P_AL_VALUE_CURR,
'', -- INV_P_AL_REFERENCE,
'', -- INV_P_AL_DATE,
'', -- INV_P_AL_YEAR,
'', -- INV_P_AL_PERIOD,
0,
'' -- INV_P_AL_PRIMARY

FROM PL_TRANSACTIONS PL_PAY

   Inner JOIN PL_ALLOC_HISTORY ALLOC_PAY
   ON PL_PAY.PT_HEADER_KEY = ALLOC_PAY.P_AL_HEADER_KEY And (PL_PAY.PT_TRANTYPE = 'PAY'
                         And  PL_PAY.PT_BATCH_FLAG <> 1
                         And  ALLOC_PAY.P_AL_REFERENCE = 0
                         And  PL_PAY.PT_GROSS > 0)


Union all
Select
PL_PAY.PT_VAT,
PL_PAY.PT_GROSS,
PL_PAY.PT_UNALLOCATED,
PL_PAY.PT_BATCH_FLAG,
PL_PAY.PT_DATE,
PL_PAY.PT_TRANTYPE,
PL_PAY.PT_COPYSUPP,
PL_PAY.PT_PRIMARY,
PL_PAY.PT_HEADER_KEY,
PL_PAY.PT_HEADER_REF,
PL_PAY.PT_CURRENCYCODE,
PL_PAY.PT_CURR_VALU,
PL_PAY.PT_CURR_UNAL,
PL_PAY.PT_CURR_TAX,
ALLOC_PAY.P_AL_VALUE_HOME,
ALLOC_PAY.P_AL_VALUE_CURR,
ALLOC_PAY.P_AL_REFERENCE,
ALLOC_PAY.P_AL_DATE,
ALLOC_PAY.P_AL_YEAR,
ALLOC_PAY.P_AL_PERIOD,
ALLOC_PAY.P_AL_PRIMARY,

PL_INV.PT_VAT,
PL_INV.PT_GROSS,
PL_INV.PT_UNALLOCATED,
PL_INV.PT_BATCH_FLAG,
PL_INV.PT_DATE,
Isnull(PL_INV.PT_TRANTYPE,''),
PL_INV.PT_COPYSUPP,
PL_INV.PT_PRIMARY,
PL_INV.PT_HEADER_KEY,
PL_INV.PT_HEADER_REF,
PL_INV.PT_CURRENCYCODE,
PL_INV.PT_CURR_VALU,
PL_INV.PT_CURR_UNAL,
PL_INV.PT_CURR_TAX,
ALLOC_INV.P_AL_VALUE_HOME,
ALLOC_INV.P_AL_VALUE_CURR,
ALLOC_INV.P_AL_REFERENCE,
ALLOC_INV.P_AL_DATE,
ALLOC_INV.P_AL_YEAR,
ALLOC_INV.P_AL_PERIOD,
isnull((select top 1 1 from SL_PL_NL_DETAIL where PL_INV.PT_HEADER_KEY = DET_HEADER_KEY and DET_VATCODE in ('10', '11', '12')),0),

ALLOC_INV.P_AL_PRIMARY

FROM PL_TRANSACTIONS PL_PAY


   Inner JOIN PL_ALLOC_HISTORY ALLOC_PAY
   ON PL_PAY.PT_HEADER_KEY = ALLOC_PAY.P_AL_HEADER_KEY And (PL_PAY.PT_TRANTYPE = 'PAY'
                         And  PL_PAY.PT_BATCH_FLAG <> 1
                         And  ALLOC_PAY.P_AL_REFERENCE <> 0
                         And  PL_PAY.PT_GROSS > 0)

   Inner Join PL_ALLOC_HISTORY ALLOC_INV
   On ALLOC_PAY.P_AL_REFERENCE = ALLOC_INV.P_AL_REFERENCE And (ALLOC_INV.P_AL_ACCOUNT_CODE = ALLOC_PAY.P_AL_ACCOUNT_CODE)
                            And ALLOC_INV.P_AL_REFERENCE <> 0
                            And PL_PAY.PT_UNALLOCATED <> PL_PAY.PT_GROSS

   Inner Join PL_TRANSACTIONS PL_INV
   ON (PL_INV.PT_HEADER_KEY = ALLOC_INV.P_AL_HEADER_KEY And PL_INV.PT_TRANTYPE Not In ('PAY','ADR','ACR')) Or
      (PL_INV.PT_HEADER_KEY = ALLOC_INV.P_AL_HEADER_KEY And PL_INV.PT_TRANTYPE = 'PAY' And PL_INV.PT_GROSS <= 0)

