CREATE VIEW AA_REP_WO_ROUTES_VIEW

/*
** Written     :  01/03/2006 RV
** Last Amended:  11/04/2006 RV
**
** Used by     :  Route List Report.rpt
*/

AS

SELECT
WO_ROUTES.WR_ROUTE,
WO_ROUTES.WR_DESCRIPTION,
WO_ROUTES.WR_NOTES,

WO_STAGES.WS_TEXT,
WO_STAGES.WS_SEQUENCE,
'ENGLISH   ' As LANGUAGE_LINK

FROM WO_ROUTES

   Left Outer JOIN WO_STAGES
   ON WO_ROUTES.WR_PRIMARY = WO_STAGES.WS_ROUTE_LINK



