CREATE VIEW AA_REP_CUSTOMER_TURNOVER_VIEW
/*
** Written:     24/02/2005 RV   
** Last Amended: 01/03/2005 RV. 02/03/05 RV.
**               03/03/2005 RV. 10/03/2005 RV. 23/03/05 RV, 24/03/2005 SH, 29/03/05 RV, 03/05/06 RV
** Comments: returns all turnover and budget revisions for crystal reports
*/
AS
SELECT     
SL_ACCOUNTS.CUCODE, 
SL_ACCOUNTS.CUNAME, 
CAST (SL_ACCOUNTS.CU_ON_STOP AS BIT) AS CU_ON_STOP,
SL_ACCOUNTS.CUSORT, 
SL_ACCOUNTS.CUUSER1, 
SL_ACCOUNTS.CUUSER2, 
SL_ACCOUNTS.CUUSER3,
SL_ACCOUNTS.CUBALANCE, 
SL_ACCOUNTS.CUTURNOVERYTD, 
SL_ACCOUNTS.CUCURRENCYCODE,
SL_ACCOUNTS.CUPOSTCODE,
SL_ACCOUNTS.CU_CREDIT_LIMIT,
SL_ACCOUNTS.CU_ADDRESS_USER2, 
SL_ACCOUNTS.CU_COUNTRY, 
SYS_CURRENCY.CURR_SYMBOL,

SL_ACCOUNTS.CUTURNOVR_L1, 
SL_ACCOUNTS.CUTURNOVR_L2, 
SL_ACCOUNTS.CUTURNOVR_L3, 
SL_ACCOUNTS.CUTURNOVR_L4, 
SL_ACCOUNTS.CUTURNOVR_L5, 
SL_ACCOUNTS.CUTURNOVR_L6, 
SL_ACCOUNTS.CUTURNOVR_L7, 
SL_ACCOUNTS.CUTURNOVR_L8, 
SL_ACCOUNTS.CUTURNOVR_L9, 
SL_ACCOUNTS.CUTURNOVR_L10, 
SL_ACCOUNTS.CUTURNOVR_L11, 
SL_ACCOUNTS.CUTURNOVR_L12, 
SL_ACCOUNTS.CUTURNOVR_L13, 

SL_ACCOUNTS.CUTURNOVR_C1, 
SL_ACCOUNTS.CUTURNOVR_C2, 
SL_ACCOUNTS.CUTURNOVR_C3, 
SL_ACCOUNTS.CUTURNOVR_C4, 
SL_ACCOUNTS.CUTURNOVR_C5, 
SL_ACCOUNTS.CUTURNOVR_C6, 
SL_ACCOUNTS.CUTURNOVR_C7, 
SL_ACCOUNTS.CUTURNOVR_C8,
SL_ACCOUNTS.CUTURNOVR_C9, 
SL_ACCOUNTS.CUTURNOVR_C10, 
SL_ACCOUNTS.CUTURNOVR_C11, 
SL_ACCOUNTS.CUTURNOVR_C12, 
SL_ACCOUNTS.CUTURNOVR_C13, 

SL_ACCOUNTS.CUTURNOVR_O1, 
SL_ACCOUNTS.CUTURNOVR_O2, 
SL_ACCOUNTS.CUTURNOVR_O3, 
SL_ACCOUNTS.CUTURNOVR_O4, 
SL_ACCOUNTS.CUTURNOVR_O5, 
SL_ACCOUNTS.CUTURNOVR_O6, 
SL_ACCOUNTS.CUTURNOVR_O7, 
SL_ACCOUNTS.CUTURNOVR_O8, 
SL_ACCOUNTS.CUTURNOVR_O9, 
SL_ACCOUNTS.CUTURNOVR_O10, 
SL_ACCOUNTS.CUTURNOVR_O11, 
SL_ACCOUNTS.CUTURNOVR_O12, 
SL_ACCOUNTS.CUTURNOVR_O13, 

SL_ACCOUNTS.CUTURNOVR_L1_C, 
SL_ACCOUNTS.CUTURNOVR_L2_C, 
SL_ACCOUNTS.CUTURNOVR_L3_C, 
SL_ACCOUNTS.CUTURNOVR_L4_C, 
SL_ACCOUNTS.CUTURNOVR_L5_C, 
SL_ACCOUNTS.CUTURNOVR_L6_C, 
SL_ACCOUNTS.CUTURNOVR_L7_C, 
SL_ACCOUNTS.CUTURNOVR_L8_C, 
SL_ACCOUNTS.CUTURNOVR_L9_C, 
SL_ACCOUNTS.CUTURNOVR_L10_C, 
SL_ACCOUNTS.CUTURNOVR_L11_C, 
SL_ACCOUNTS.CUTURNOVR_L12_C, 
SL_ACCOUNTS.CUTURNOVR_L13_C, 

SL_ACCOUNTS.CUTURNOVR_C1_C, 
SL_ACCOUNTS.CUTURNOVR_C2_C, 
SL_ACCOUNTS.CUTURNOVR_C3_C, 
SL_ACCOUNTS.CUTURNOVR_C4_C, 
SL_ACCOUNTS.CUTURNOVR_C5_C, 
SL_ACCOUNTS.CUTURNOVR_C6_C, 
SL_ACCOUNTS.CUTURNOVR_C7_C, 
SL_ACCOUNTS.CUTURNOVR_C8_C, 
SL_ACCOUNTS.CUTURNOVR_C9_C, 
SL_ACCOUNTS.CUTURNOVR_C10_C, 
SL_ACCOUNTS.CUTURNOVR_C11_C, 
SL_ACCOUNTS.CUTURNOVR_C12_C, 
SL_ACCOUNTS.CUTURNOVR_C13_C, 

SL_ACCOUNTS.CUTURNOVR_O1_C, 
SL_ACCOUNTS.CUTURNOVR_O2_C, 
SL_ACCOUNTS.CUTURNOVR_O3_C, 
SL_ACCOUNTS.CUTURNOVR_O4_C, 
SL_ACCOUNTS.CUTURNOVR_O5_C, 
SL_ACCOUNTS.CUTURNOVR_O6_C, 
SL_ACCOUNTS.CUTURNOVR_O7_C, 
SL_ACCOUNTS.CUTURNOVR_O8_C, 
SL_ACCOUNTS.CUTURNOVR_O9_C, 
SL_ACCOUNTS.CUTURNOVR_O10_C, 
SL_ACCOUNTS.CUTURNOVR_O11_C, 
SL_ACCOUNTS.CUTURNOVR_O12_C, 
SL_ACCOUNTS.CUTURNOVR_O13_C, 

SL_ACCOUNTS2.CU_USRDATE1, 
SL_ACCOUNTS2.CU_USRDATE2,
SL_ACCOUNTS2.CU_USRDATE3, 
SL_ACCOUNTS2.CU_USRCHAR1, 
SL_ACCOUNTS2.CU_USRCHAR2,
SL_ACCOUNTS2.CU_USRCHAR5,
SL_ACCOUNTS2.CU_USRCHAR6, 
SL_ACCOUNTS2.CU_USRCHAR7, 
SL_ACCOUNTS2.CU_USRCHAR8,
SL_ACCOUNTS2.CU_USRNUM1, 
SL_ACCOUNTS2.CU_USRNUM2, 
SL_ACCOUNTS2.CU_USRNUM3, 
                      
AA_REP_CUSTOMER_BUDGETS_VIEW.REVISION,

isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O1,0) As BUD_O1, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O2,0) As BUD_O2, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O3,0) As BUD_O3, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O4,0) As BUD_O4, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O5,0) As BUD_O5, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O6,0) As BUD_O6, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O7,0) As BUD_O7, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O8,0) As BUD_O8, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O9,0) As BUD_O9, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O10,0) As BUD_O10, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O11,0) As BUD_O11, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O12,0) As BUD_O12, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_O13,0) As BUD_O13, 

isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L1,0) As BUD_L1,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L2,0) As BUD_L2,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L3,0) As BUD_L3,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L4,0) As BUD_L4,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L5,0) As BUD_L5,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L6,0) As BUD_L6,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L7,0) As BUD_L7,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L8,0) As BUD_L8,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L9,0) As BUD_L9,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L10,0) As BUD_L10,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L11,0) As BUD_L11,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L12,0) As BUD_L12,  
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_L13,0) As BUD_L13,  

isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C1,0) As BUD_C1, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C2,0) As BUD_C2, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C3,0) As BUD_C3, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C4,0) As BUD_C4, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C5,0) As BUD_C5, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C6,0) As BUD_C6, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C7,0) As BUD_C7, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C8,0) As BUD_C8, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C9,0) As BUD_C9, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C10,0) As BUD_C10, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C11,0) As BUD_C11, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C12,0) As BUD_C12, 
isnull(AA_REP_CUSTOMER_BUDGETS_VIEW.BUD_C13,0) As BUD_C13,  

isnull( M.MAX_REVISION, 0 ) as MAX_REVISION

FROM SL_ACCOUNTS 
	
   	LEFT OUTER JOIN AA_REP_CUSTOMER_BUDGETS_VIEW 
	ON SL_ACCOUNTS.CUCODE = AA_REP_CUSTOMER_BUDGETS_VIEW.CUSTOMER

	INNER JOIN SL_ACCOUNTS2 
	ON SL_ACCOUNTS.CU_PRIMARY = SL_ACCOUNTS2.CU_PRIMARY_2

   inner join SYS_CURRENCY on SYS_CURRENCY.CURR_CODE = SL_ACCOUNTS.CUCURRENCYCODE

	left join ( select B_ACCOUNT_CODE, max( B_REVISION_NUMBER ) as MAX_REVISION -- Obtain maximum revision number for account
						from SYS_BUDGETS
						where B_RECORD_TYPE = 'S' and B_BUDGET_TYPE = 'B'
						group by B_ACCOUNT_CODE
					) M on M.B_ACCOUNT_CODE = SL_ACCOUNTS.CUCODE

WHERE SL_ACCOUNTS.CUCODE IS NOT NULL AND SL_ACCOUNTS.CUCODE <> ''