create view AA_REP_AGED_CRED_MP_HEADER_VIEW
/*
** Written:       11/5/2005 RL
** Last Amended:  11/7/2005 RL, 12/7/2005 RL, 22/7/2005 RL, 27/09/2005 SB, 27/04/06 SB
** Comments: returns selected sales transaction headers for Multiple Period Aged Debtors crystal reports
*/
as

select
PT_PRIMARY,
PT_TRANTYPE,
PT_GROSS,
CAST (PT_BATCH_FLAG AS BIT) AS PT_BATCH_FLAG,
PT_CURRENCYCODE,
PT_CURR_VALU,
PT_YEAR,
PT_PERIODNUMBER,
PT_PERIODNUMBER + NO_OF_PERIODS * charindex(PT_YEAR,'LCN') as PERIOD_SORT,
PT_DATE,
PT_HEADER_REF,
PT_GROSS_BASE2,
PT_SUB_LEDGER,
PT_DUEDATE,
PT_USER1,
PT_USER2,
PT_USER3,
PT_TRI_RATE1,
PT_TRI_RATE2,
PT_DESCRIPTION,
PT_INTERNAL_REF,
SUCODE,
SUNAME,
SUBALANCE,
SUPHONE,
SUFAX,
SUCONTACT,
SUSORT,
SUUSER1,
SUUSER2,
SUUSER3,
SUCURRENCYCODE,
CAST (SU_ON_STOP AS BIT) AS SU_ON_STOP,
SU_CREDIT_LIMIT,
SU_TERMS,
SU_NOTES,
SU_MULTI_CURR,
SU_CURRENCY_CHANGED,
SUPOSTCODE,
SU_DUE_DAYS,
SU_DUEDATE_TYPE,
SU_A_P_DAYS,
SU_SETT_DISC1,
SU_SETT_DISC2,
SU_SETT_DAYS1,
SU_SETT_DAYS2,
SU_DATE_INV,
P_AL_PRIMARY,
P_AL_DATE,
P_AL_PERIOD,
P_AL_YEAR,
P_AL_VALUE_HOME,
P_AL_VALUE_CURR,
P_AL_REFERENCE,
case PT_GROSS when 0 then 0 else P_AL_VALUE_HOME * PT_GROSS_BASE2/PT_GROSS end as P_AL_VALUE_BASE2,
P_AL_USER_ID,
P_AL_FULLALLOC_PD,
P_AL_FULLALLOC_DATE,
case
   when PT_TRANTYPE in ('INV','ACR') then P_AL_VALUE_HOME
   else 0
end as HOME_DEBIT_VALUE,
case
   when PT_TRANTYPE in ('INV','ACR') then P_AL_VALUE_CURR
   else 0
end as CURR_DEBIT_VALUE,
case
   when PT_TRANTYPE in ('INV','ACR') then
      case PT_GROSS when 0 then 0
         else P_AL_VALUE_HOME * PT_GROSS_BASE2/PT_GROSS
      end
   else 0
end as BASE2_DEBIT_VALUE,
case
   when PT_TRANTYPE in ('CRN','PAY','ADR') then -P_AL_VALUE_HOME
   else 0
end as HOME_CREDIT_VALUE,
case
   when PT_TRANTYPE in ('CRN','PAY','ADR') then -P_AL_VALUE_CURR
   else 0
end as CURR_CREDIT_VALUE,
case
   when PT_TRANTYPE in ('CRN','PAY','ADR') then
      case PT_GROSS when 0 then 0
         else -(P_AL_VALUE_HOME * PT_GROSS_BASE2/PT_GROSS)
      end
   else 0
end as BASE2_CREDIT_VALUE
from
  PL_ALLOC_HISTORY
  inner join PL_TRANSACTIONS on PT_HEADER_KEY = P_AL_HEADER_KEY
  inner join PL_ACCOUNTS     on SUCODE        = P_AL_ACCOUNT_CODE,
  SYS_DATAINFO2
