create view AA_REP_SL_PL_REVALUE_TRANSACTIONS_VIEW
(
   ORIGIN
,  TRANTYPE
,  HEADER_REF
,  UNALLOCATED
,  CURRENCYRATE
,  CURRENCYCODE
,  CURR_UNAL
,  ACCOUNT
,  TRI_RATE1
,  TRI_RATE2
,  CURR_TYPE
,  DATE
)

as

select
   SL_TRANSACTIONS.ST_ORIGIN
,  SL_TRANSACTIONS.ST_TRANTYPE
,  SL_TRANSACTIONS.ST_HEADER_REF
,  SL_TRANSACTIONS.ST_UNALLOCATED
,  SL_TRANSACTIONS.ST_CURRENCYRATE
,  SL_TRANSACTIONS.ST_CURRENCYCODE
,  SL_TRANSACTIONS.ST_CURR_UNAL
,  SL_TRANSACTIONS.ST_COPYCUST
,  SL_TRANSACTIONS.ST_TRI_RATE1
,  SL_TRANSACTIONS.ST_TRI_RATE2
,  SL_TRANSACTIONS.ST_CURR_TYPE
,  SL_TRANSACTIONS.ST_DATE
   from
      SL_TRANSACTIONS
         inner join SYS_DATAINFO on SYS_PRIMARY = 1
   where
            ST_ALOC_POINTER   like  '0%'
      and   ST_CURR_VALU      <>    0
      and   ST_BATCH_FLAG     <>    1
      and   HOME_CURR_SYMBL   <>    ST_CURRENCYCODE

union all

select
   PL_TRANSACTIONS.PT_ORIGIN
,  PL_TRANSACTIONS.PT_TRANTYPE
,  PL_TRANSACTIONS.PT_HEADER_REF
,  PL_TRANSACTIONS.PT_UNALLOCATED
,  PL_TRANSACTIONS.PT_CURRENCYRATE
,  PL_TRANSACTIONS.PT_CURRENCYCODE
,  PL_TRANSACTIONS.PT_CURR_UNAL
,  PL_TRANSACTIONS.PT_COPYSUPP
,  PL_TRANSACTIONS.PT_TRI_RATE1
,  PL_TRANSACTIONS.PT_TRI_RATE2
,  PL_TRANSACTIONS.PT_CURR_TYPE
,  PL_TRANSACTIONS.PT_DATE
   from
      PL_TRANSACTIONS
         inner join SYS_DATAINFO on SYS_PRIMARY = 1
   where
            PT_ALOC_POINTER   like  '0%'
      and   PT_CURR_VALU      <>    0
      and   PT_BATCH_FLAG     <>    1
      and   HOME_CURR_SYMBL   <>    PT_CURRENCYCODE