CREATE VIEW AA_REP_PURCHASE_LANG_VIEW
/*
** Written     :  06/10/2005 RV
** Last Amended:  07/10/2005 RV, 14/10/2005 RV,
** Comments    :  Returns all language labels for dimensions purchase transactions crystal reports
**
** Used by     :  Disproportionate VAT Values - Purchase Transactions.rpt
**                Purchase Invoices Posted with a Future Date.rpt
**                Supplier Invoices Unpaid and Over 6 Months Old.rpt
*/
AS
SELECT

SYS_DATAINFO.COMPANY_NAME,
SYS_DATAINFO.COMP_VATNUMBER,
SYS_DATAINFO.HOME_TAXNAME,
SYS_DATAINFO.VALUE_DPS,
SYS_DATAINFO.PURCHASE_PERIOD,
SYS_DATAINFO.HOME_CURR_SYMBL,

SYS_DATAINFO2.SETT_DISCOUNT_VAT_CALC,

LANG_REPORTS_R.UNALLOCATED_REP,
LANG_REPORTS_R.TOTALFOR_REP,
LANG_REPORTS_R.LANGCODE_REP_1,
LANG_REPORTS_R.REGNO_ABBREV_REP,
LANG_REPORTS_R.KEY_TXT_REP,
LANG_REPORTS_R.INVOICE_REP,
LANG_REPORTS_R.CREDIT_NOTE_REP,

LANG_REPORTS_R3.VAT_RETURN,
LANG_REPORTS_R3.DIFFERENCE_TEXT,

LANG_REPORTS_R4.ACCOUNT_REP,
LANG_REPORTS_R4.AUDIT_NO_REP,
LANG_REPORTS_R4.BALANCE_REP,
LANG_REPORTS_R4.DATE_TEXT_REP,
LANG_REPORTS_R4.DESCRIPTION_REP,
LANG_REPORTS_R4.GROSS_REP,
LANG_REPORTS_R4.NET_REP,
LANG_REPORTS_R4.REFERENCE_REP,
LANG_REPORTS_R4.REF_REP,
LANG_REPORTS_R4.PERIOD_REP,
LANG_REPORTS_R4.RECORDS_REP,
LANG_REPORTS_R4.RATE_REP,

LANG_REPORTS_R5.SUPPLIER_NAME_REP,
LANG_REPORTS_R5.TRANSACTIONS_TEXT_REP,
LANG_REPORTS_R5.TYPE_REP,

LANG_REPORTS_R6.SUPPLIER_CODE_REP

FROM  LANG_REPORTS_R5

INNER JOIN LANG_REPORTS_R3 ON
LANG_REPORTS_R5.LANGCODE_REP5 = LANG_REPORTS_R3.LANGCODE_REP3

INNER JOIN LANG_REPORTS_R4 ON
LANG_REPORTS_R5.LANGCODE_REP5 = LANG_REPORTS_R4.LANGCODE_REP4

INNER JOIN LANG_REPORTS_R6 ON
LANG_REPORTS_R5.LANGCODE_REP5 = LANG_REPORTS_R6.LANGCODE_REP6

INNER JOIN LANG_REPORTS_R ON
LANG_REPORTS_R4.LANGCODE_REP4 = LANG_REPORTS_R.LANGCODE_REP_1

Inner join SYS_DATAINFO with ( nolock ) on SYS_PRIMARY = 1

inner join SYS_DATAINFO2 with ( nolock ) on SYS_DATAINFO2.SYS_PRIMARY_2 = SYS_DATAINFO.SYS_PRIMARY