CREATE VIEW AA_REP_SL_CREDIT_BALS_VIEW
/*
** Written:     16/01/2006 RV   
** Last Amended:  
** Comments: returns selected sales transactions for customer accounts with credit balances crystal reports
*/
AS
SELECT
SL_TRANSACTIONS.ST_PRIMARY,     
SL_TRANSACTIONS.ST_TRANTYPE, 
CAST (SL_TRANSACTIONS.ST_BATCH_FLAG AS BIT) AS ST_BATCH_FLAG,                
SL_TRANSACTIONS.ST_YEAR, 
SL_TRANSACTIONS.ST_PERIODNUMBER,
SL_TRANSACTIONS.ST_DATE,
SL_TRANSACTIONS.ST_HEADER_REF,
SL_TRANSACTIONS.ST_SUB_LEDGER,
SL_TRANSACTIONS.ST_NETT,
SL_TRANSACTIONS.ST_VAT,
SL_TRANSACTIONS.ST_GROSS,
SL_TRANSACTIONS.ST_UNALLOCATED,
SL_TRANSACTIONS.ST_DESCRIPTION,
SL_ACCOUNTS.CUCODE, 
SL_ACCOUNTS.CUNAME,         
SL_ACCOUNTS.CUBALANCE, 
SL_ACCOUNTS.CUSORT, 
SL_ACCOUNTS.CUUSER1,                       
SL_ACCOUNTS.CUUSER2, 
SL_ACCOUNTS.CUUSER3, 
SL_ACCOUNTS.CUCURRENCYCODE,                       
CAST (SL_ACCOUNTS.CU_ON_STOP AS BIT) AS CU_ON_STOP, 
SL_ACCOUNTS.CU_CREDIT_LIMIT,
'ENGLISH   ' AS LANGUAGE_LINK

FROM SL_TRANSACTIONS 

  INNER JOIN SL_ACCOUNTS 
  ON SL_TRANSACTIONS.ST_COPYCUST = SL_ACCOUNTS.CUCODE

WHERE 	ST_BATCH_FLAG <> 1 And
	ST_UNALLOCATED <> 0.00 And
	CUBALANCE < 0.00 