create view AA_REP_SL_STATEMENTS_VIEW

/*
** Written     :  01/08/2005 RV
** Last Amended:  03/08/05 RV, 10/08/05 RV, 11/08/05 RV, 27/09/05 RV, 12/04/2006 RV, 24/1/07 NC
** Comments    :  Returns selected sales transactions for statement reports
*/

as

select top 100 percent
   SL_ACCOUNTS.CUCODE
,  SL_ACCOUNTS.CUNAME
,  SL_ACCOUNTS.CUSORT
,  SL_ACCOUNTS.CUBALANCE
,  SL_ACCOUNTS.CUBALANCE_C
,  SL_ACCOUNTS.CUTURNOVERYTD
,  SL_ACCOUNTS.CU_DATE_INV
,  SL_ACCOUNTS.CUUSER1
,  SL_ACCOUNTS.CUUSER2
,  SL_ACCOUNTS.CUUSER3
,  SL_ACCOUNTS.CU_CREDIT_LIMIT
,  SL_ACCOUNTS.CU_ON_STOP

,  SL_ACCOUNTS2.CU_HEAD_OFFICE_CODE

,  SL_ADDRESSES.AD_ADDRESS
,  SL_ADDRESSES.AD_ADDRESS_USER1
,  SL_ADDRESSES.AD_ADDRESS_USER2
,  SL_ADDRESSES.AD_POSTCODE
,  SL_ADDRESSES.AD_ACCOUNTNAME

,  DOC_LEDGER_HEADER.DLH_DOC_DATE
,  DOC_LEDGER_HEADER.DLH_PRIMARY
,  DOC_LEDGER_HEADER.DLH_DOC_TYPE
,  DOC_LEDGER_HEADER.DLH_CURRSYMBOL
,  DOC_LEDGER_HEADER.DLH_FAX_HEADER
,  DOC_LEDGER_HEADER.DLH_COMP_ADDRESS
,  Isnull(DOC_LEDGER_HEADER.DLH_OPTION1,0) as DLH_OPTION1
,  Isnull(DOC_LEDGER_HEADER.DLH_OPTION2,0) as DLH_OPTION2

,  SL_TRANSACTIONS.ST_DATE
,  SL_TRANSACTIONS.ST_TRANTYPE
,  SL_TRANSACTIONS.ST_HEADER_REF
,  SL_TRANSACTIONS.ST_DESCRIPTION
,  SL_TRANSACTIONS.ST_QUERY_FLAG
,  SL_TRANSACTIONS.ST_DUEDATE
,  SL_TRANSACTIONS.ST_CURRENCYCODE
,  SL_TRANSACTIONS.ST_PRIMARY

,  DOC_LEDGER_DETAIL.DLD_AGED_DOC
,  DOC_LEDGER_DETAIL.DLD_AGED2_DOC
,  DOC_LEDGER_DETAIL.DLD_AGED3_DOC
,  DOC_LEDGER_DETAIL.DLD_AGED4_DOC
,  DOC_LEDGER_DETAIL.DLD_AGED5_DOC
,  DOC_LEDGER_DETAIL.DLD_DRVAL_DOC
,  DOC_LEDGER_DETAIL.DLD_CRVAL_DOC
,  DOC_LEDGER_DETAIL.DLD_OSVAL_DOC
,  DOC_LEDGER_DETAIL.DLD_UNALLOC_DOC
,  DOC_LEDGER_DETAIL.DLD_HEADER_LINK
   from
      DOC_LEDGER_HEADER with (nolock)
         inner join DOC_LEDGER_DETAIL with (nolock)  on DOC_LEDGER_HEADER.DLH_PRIMARY       = DOC_LEDGER_DETAIL.DLD_HEADER_LINK
            inner join SL_TRANSACTIONS with (nolock)    on DOC_LEDGER_DETAIL.DLD_TRAN_LINK     = SL_TRANSACTIONS.ST_PRIMARY
               inner join SL_ACCOUNTS with (nolock)        on SL_TRANSACTIONS.ST_COPYCUST         = SL_ACCOUNTS.CUCODE and SL_ACCOUNTS.CUCODE <> ''
                  inner join SL_ADDRESSES with (nolock)       on   cast(SL_ACCOUNTS.CUCODE as char(10)) + cast(SL_ACCOUNTS.CU_STAT_ADD_CDE as varchar(6)) = SL_ADDRESSES.AD_CON_CODE
                  inner join SL_ACCOUNTS2 with (nolock)       on SL_ACCOUNTS.CU_PRIMARY              = SL_ACCOUNTS2.CU_PRIMARY_2
   order by
      DOC_LEDGER_HEADER.DLH_PRIMARY


