CREATE VIEW AA_REP_PURCHASE_SUGGESTED_PAY_VIEW
AS
SELECT     
PL_TRANSACTIONS.PT_DATE, 
PL_TRANSACTIONS.PT_YEAR, 
PL_TRANSACTIONS.PT_PERIODNUMBER,                       
PL_TRANSACTIONS.PT_TRANTYPE, 
PL_TRANSACTIONS.PT_HEADER_REF, 
PL_TRANSACTIONS.PT_DUEDATE,                       
PL_TRANSACTIONS.PT_SETT_DISC1, 
PL_TRANSACTIONS.PT_SETT_DISC2, 
PL_TRANSACTIONS.PT_SETT_DAYS1,                      
PL_TRANSACTIONS.PT_SETT_DAYS2, 
PL_TRANSACTIONS.PT_NETT,
PL_TRANSACTIONS.PT_UNALLOCATED, 
PL_TRANSACTIONS.PT_GROSS,                      
CAST (PL_TRANSACTIONS.PT_BATCH_FLAG AS BIT) AS PT_BATCH_FLAG, 
CAST (PL_TRANSACTIONS.PT_QUERY_FLAG AS BIT) AS PT_QUERY_FLAG, 
CAST (PL_TRANSACTIONS.PT_DONOTCHASE AS BIT) AS PT_DONOTCHASE,                       
PL_TRANSACTIONS.PT_COPYSUPP, 
PL_TRANSACTIONS.PT_PRIMARY, 
PL_TRANSACTIONS.PT_SUB_LEDGER,                       
PL_TRANSACTIONS.PT_PAYLIST_VALUE, 
PL_TRANSACTIONS.PT_PAYLIST_SETT_DISC, 
PL_TRANSACTIONS.PT_PAYLIST_REF,                      
PL_TRANSACTIONS.PT_PAY_STAGE1_USER, 
PL_TRANSACTIONS.PT_PAY_STAGE2_USER, 
PL_TRANSACTIONS.PT_PAY_STAGE_STATUS, 
PL_TRANSACTIONS.PT_CURR_NETT,                    
PL_TRANSACTIONS.PT_CURR_VALU, 
PL_TRANSACTIONS.PT_CURR_UNAL, 
PL_TRANSACTIONS.PT_CURRENCYCODE,                 
PL_TRANSACTIONS.PT_USER1, 
PL_TRANSACTIONS.PT_USER2,                       
PL_TRANSACTIONS.PT_USER3,

PL_ACCOUNTS.SUNAME, 
PL_ACCOUNTS.SUSORT

FROM PL_TRANSACTIONS
 
  INNER JOIN PL_ACCOUNTS 
  ON PL_TRANSACTIONS.PT_COPYSUPP = PL_ACCOUNTS.SUCODE

WHERE PT_BATCH_FLAG <> 1 AND PT_UNALLOCATED <> 0.00