CREATE VIEW AA_REP_CRM_PIPELINE_VIEW
/*
** Written     :  20/03/2006 RV
** Last Amended:  22/03/2006 RV, 06/04/2006 RV, 12/04/2006 RV
**
** Used by     :  Pipeline Report.rpt
*/
AS

select
CMP_CODE,
CUCODE,
CUPROSCODE,
OH_ORDER_NUMBER,
OH_USER_PUTIN,
OH_CUSORT,
OH_USER1,
OH_USER2,
OH_USER3,
OH_ESTIMATE_DROP_DATE,
OH_NETT,OH_PROBABILITY,
OD_LINE_NUMBER,
OD_DETAIL,
OD_DIMENSION1,
OD_NETT,

isnull((OD_NETT*OH_PROBABILITY)/100,0)  as PipeLineValue,

(case   when CUCODE is null Then CUPROSCODE
   when CUCODE = '' then CUPROSCODE
   else CUCODE
end ) as CustomerorProspect,

'ENGLISH   ' As LANGUAGE_LINK

from ORD_HEADER

   LEFT OUTER JOIN CRM_CAMPAIGN
   ON OH_CAMPAIGN_LINK = CMP_PRIMARY

   LEFT OUTER JOIN SL_ACCOUNTS
   ON OH_ACCOUNT_ORDER = CUCODE or OH_ACCOUNT_ORDER = CUPROSCODE

   LEFT OUTER JOIN ORD_DETAIL
   ON OD_ACCOUNT = OH_ACCOUNT_ORDER and OD_ORDER_NUMBER = OH_ORDER_NUMBER

where OH_PRIORITY = 4

--order by CustomerorProspect

