CREATE VIEW AA_REP_AGED_CREDITORS_VIEW
/*
** Written:     13/04/2005 RV   
** Last Amended: 
** Comments: returns selected purchase transactions for Aged Creditors crystal reports
*/
AS
SELECT
PL_TRANSACTIONS.PT_PRIMARY,     
PL_TRANSACTIONS.PT_TRANTYPE, 
CAST (PL_TRANSACTIONS.PT_BATCH_FLAG AS BIT) AS PT_BATCH_FLAG,                
PL_TRANSACTIONS.PT_CURRENCYCODE,  
PL_TRANSACTIONS.PT_YEAR, 
PL_TRANSACTIONS.PT_PERIODNUMBER,
PL_TRANSACTIONS.PT_DATE,
PL_TRANSACTIONS.PT_HEADER_REF,
PL_TRANSACTIONS.PT_SUB_LEDGER,
PL_ACCOUNTS.SUCODE, 
PL_ACCOUNTS.SUNAME,         
PL_ACCOUNTS.SUBALANCE, 
PL_ACCOUNTS.SUSORT, 
PL_ACCOUNTS.SUUSER1,                       
PL_ACCOUNTS.SUUSER2, 
PL_ACCOUNTS.SUUSER3, 
PL_ACCOUNTS.SUTURNOVERYTD, 
PL_ACCOUNTS.SUCURRENCYCODE,                       
CAST (PL_ACCOUNTS.SU_ON_STOP AS BIT) AS SU_ON_STOP, 
PL_ACCOUNTS.SU_CREDIT_LIMIT 

FROM PL_TRANSACTIONS 

  INNER JOIN PL_ACCOUNTS 
  ON PL_TRANSACTIONS.PT_COPYSUPP = PL_ACCOUNTS.SUCODE

WHERE PT_BATCH_FLAG <> 1
