create view AA_SL_TRANSACTION_EDIT_VIEW
/*
** Written: 24/03/05 SR
** Last Amended: 06/04/05 SR, 13/04/05 SR
*/
as

select
ST_PRIMARY as [PRIMARY]
,(case ST_TRANTYPE
	when 'INV' then 0
	when 'CRN' then 1
	when 'PAY' then 2
	when 'ADR' then 3
	when 'ACR' then 4 end)	as ST_TRANTYPE
,ST_COPYCUST
,isnull(CUNAME,'') as CUNAME
,isnull(ST_HEADER_REF,'') as ST_HEADER_REF
,cast(ST_PRIMARY as int) as ST_AUDIT_NO
,ST_USER_PUTIN
,ST_DATE_PUTIN
,isnull(ST_SUB_LEDGER,'') as ST_SUB_LEDGER
,isnull(ST_ALLOC_XREF,'') as ST_ALLOC_XREF
,isnull(ST_BATCH_REF,'') as ST_BATCH_REF
,isnull(ST_DESCRIPTION,'') as ST_DESCRIPTION
,ST_DUEDATE
,ST_ANTICPAYDATE
,isnull(ST_USER1,'') as ST_USER1
,isnull(ST_USER2,'') as ST_USER2
,isnull(ST_USER3,'') as ST_USER3
,ST_ARCHIVE_FLAG
,ST_QUERY_FLAG
,isnull(STT_USRCHAR1,'') as ST_USRCHAR1
,isnull(ST_USRCHAR2,'') as ST_USRCHAR2
,isnull(ST_USRCHAR3,'') as ST_USRCHAR3
,isnull(ST_USRCHAR4,'') as ST_USRCHAR4
,ST_USRFLAG1
,ST_USRFLAG2
,ST_USRDATE1
,ST_USRDATE2
,dbo.AA_VALUE_DPS_F(ST_USRNUM1)as ST_USRNUM1
,dbo.AA_VALUE_DPS_F(ST_USRNUM2)as ST_USRNUM2
,ST_NOTE
,ST_GROSS
,ST_CURR_VALU
,ST_CURRENCYCODE as ST_CURRENCYSYMBOL

from SL_TRANSACTIONS 
join SL_ACCOUNTS on ST_COPYCUST = CUCODE 
left outer join SL_TRANSACTIONS2 on ST_PRIMARY_2 = ST_PRIMARY
left outer join SL_TRANSACTION_NOTES on ST_COPY_HEADERKEY = 'S' + convert(nvarchar,ST_PRIMARY)