create view AA_SL_TRANSACTION_DD_LAST_ACTION_VIEW
/*
**
** Written     : 15/01/2014 CC
** Last Amended:  
**
*/
as

with History_CTE
AS
(select ST_DDCH_ACTION, ST_DDCH_ACTION_DATE, ST_DDCH_ACTION_USER_ID, ST_DDCH_TRANSACTION_LINK, ST_DDCH_RESPONSE_CODE, ST_DDCH_DD_TYPE,
ROW_NUMBER() over (partition by ST_DDCH_TRANSACTION_LINK order by ST_DDCH_ACTION_DATE desc) rownum
from SL_TRANSACTION_DD_COLLECTION_HISTORY with (nolock) 
) 
select ST_PRIMARY, ST_DATE, ST_DDCH_ACTION,ST_DDCH_ACTION_DATE,ST_DDCH_ACTION_USER_ID,ST_DDCH_RESPONSE_CODE,ST_DDCH_DD_TYPE
from SL_TRANSACTIONS with (nolock) 
left join History_CTE on rownum = 1 and ST_DDCH_TRANSACTION_LINK = ST_PRIMARY
where ST_TRANTYPE='PAY'
