create view AA_SL_ANALYSIS_ADVANCED_VIEW
/*
** Returns a table to be used specifically with AA_SL_ANALYSIS_LIST_S
** Written:      21/02/03 SRB
** Last Amended: 27/02/03 SRB; 13/03/03 ROBB; 02/03/04 DG; 15/04/04 DG; 13/01/05 SR; 24/02/05 SRB, 02/03/2005 SH, 06/04/05 SR, 20/09/05 SRB, 13/12/05 NC
**
*/
as

select
 SA_PRIMARY as [PRIMARY]
,cast(coalesce(SA_ANALYSIS_MATRIX,0) as bit) as SA_ANALYSIS_MATRIX
,SACODE
,coalesce(SANAME,'') as SANAME
,SACURRENCYSYMBL
,coalesce(SASORT,'') as SASORT
,SATYPE_S_B_D
,cast(
   coalesce(
      case SATYPE_S_B_D 
         when 'S' then SADEFAULT_SALES
         when 'B' then SADEFAULT_BANK
         else 0 end
   ,0)
 as bit) as SADEFAULT_S_B
,cast(SADEFAULT_ROUNDING as bit) as SADEFAULT_ROUNDING
,SA_DATE_PUTIN
,SA_DATE_EDITED
,SA_LEVEL as PROFILELEVEL
,coalesce(SANOMINALDR,'') as SANOMINALDR
,dr.NNAME as SANOMINALDRNAME
,coalesce(dr.NCATEGORYCODE1,'') as DEBITNCATCODE1
,coalesce(dr.NCATEGORYCODE2,'') as DEBITNCATCODE2
,coalesce(dr.NCATEGORYCODE3,'') as DEBITNCATCODE3
,coalesce(dr.NCATEGORYCODE4,'') as DEBITNCATCODE4
,coalesce(dr.NCATEGORYCODE5,'') as DEBITNCATCODE5
,coalesce(dr.NCATEGORYCODE6,'') as DEBITNCATCODE6
,coalesce(dr.NCATEGORYCODE7,'') as DEBITNCATCODE7
,coalesce(dr.NCATEGORYCODE8,'') as DEBITNCATCODE8
,coalesce(SANOMINALCR,'') as SANOMINALCR
,cr.NNAME as SANOMINALCRNAME
,coalesce(cr.NCATEGORYCODE1,'') as CREDITNCATCODE1
,coalesce(cr.NCATEGORYCODE2,'') as CREDITNCATCODE2
,coalesce(cr.NCATEGORYCODE3,'') as CREDITNCATCODE3
,coalesce(cr.NCATEGORYCODE4,'') as CREDITNCATCODE4
,coalesce(cr.NCATEGORYCODE5,'') as CREDITNCATCODE5
,coalesce(cr.NCATEGORYCODE6,'') as CREDITNCATCODE6
,coalesce(cr.NCATEGORYCODE7,'') as CREDITNCATCODE7
,coalesce(cr.NCATEGORYCODE8,'') as CREDITNCATCODE8
,SA_USER_PUTIN
,SA_USER_EDITED
,coalesce(sl2.SA_USRCHAR1,'') as SA_USRCHAR1
,coalesce(sl2.SA_USRCHAR2,'') as SA_USRCHAR2
,coalesce(sl2.SA_USRCHAR3,'') as SA_USRCHAR3
,coalesce(sl2.SA_USRCHAR4,'') as SA_USRCHAR4
,coalesce(sl2.SA_USRCHAR5,'') as SA_USRCHAR5
,coalesce(sl2.SA_USRCHAR6,'') as SA_USRCHAR6
,coalesce(sl2.SA_USRCHAR7,'') as SA_USRCHAR7
,coalesce(sl2.SA_USRCHAR8,'') as SA_USRCHAR8
,cast(sl2.SA_USRFLAG1 as bit) as SA_USRFLAG1
,cast(sl2.SA_USRFLAG2 as bit) as SA_USRFLAG2
,cast(sl2.SA_USRFLAG3 as bit) as SA_USRFLAG3
,sl2.SA_USRDATE1
,sl2.SA_USRDATE2
,sl2.SA_USRDATE3
,sl2.SA_USRNUM1
,sl2.SA_USRNUM2
,sl2.SA_USRNUM3
,SA_DO_NOT_USE as EXCLUDED
from SL_ANALYSIS
left join NL_ACCOUNTS cr   on SANOMINALCR = cr.NCODE
left join NL_ACCOUNTS dr   on SANOMINALDR = dr.NCODE
left join SL_ANALYSIS2 sl2 on SA_PRIMARY  = sl2.SA_PRIMARY_2