create view AA_SL_ALLOCATION_TRANSACTION_VIEW
/*
** Returns a table to be used specifically with AA_SL_ALLOCATION_TRANSACTION_LIST_S
** Written:      02/12/2004 SRB
** Last Amended: 13/12/2004 SRB; 16/12/04 SRB; 20/12/04, 04/03/2005 SH, 13/04/2005 SH; 18/05/05 SRB, 16/08/2005 SRB, 27/09/2005 SRB
**
*/
as

select ST_COPYCUST,
	CUNAME,
	CU_MULTI_CURR,
	ST_ALOC_POINTER,
	ST_DATE,
 	ST_YEAR,
	ST_PERIODNUMBER,
	ST_DATE_PUTIN,
	ST_HEADER_REF,
	ST_TRANTYPE,
	case ST_TRANTYPE
		when 'INV' then 0 
		when 'CRN' then 1
		when 'PAY' then 2 
		when 'ADR' then 3 
		when 'ACR' then	4
	end as TRANSACTION_TYPE,
	ST_PRIMARY as [PRIMARY],
	dbo.AA_VALUE_DPS_F(ST_CURR_UNAL) as ST_CURR_UNAL,
	dbo.AA_VALUE_DPS_F(ST_CURR_VALU) as ST_CURR_VALU,
	ST_CURRENCYCODE,
	dbo.AA_VALUE_DPS_F(ST_UNALLOCATED) as ST_UNALLOCATED,
	ST_DESCRIPTION,
	dbo.AA_VALUE_DPS_F(ST_GROSS) as ST_GROSS,
	ST_YEAR + CAST(ST_PERIODNUMBER as varchar(2)) as PERIODYEAR,
	ST_QUERY_FLAG,
	STT_USRCHAR1,
	ST_USRCHAR2,
	ST_USRCHAR3,
	ST_USRCHAR4,
	ST_USRDATE1,
	ST_USRDATE2,
	ST_USRFLAG1,
	ST_USRFLAG2,
	ST_USRNUM1,
	ST_USRNUM2,
	ST_USER1,
	ST_USER2,
	ST_USER3,
	ST_SUB_LEDGER

from SL_TRANSACTIONS S
	left join SL_TRANSACTIONS2 S2 on S2.ST_PRIMARY_2 = S.ST_PRIMARY
	inner join SL_ACCOUNTS C on C.CUCODE = S.ST_COPYCUST

where S.ST_BATCH_FLAG <> 1

