create view AA_STATEMENT_PAYMENTS_VIEW
as
select
max(SUCODE) SUCODE,
max(SUNAME) SUNAME,
max(PL_AD_ADDRESS) PL_AD_ADDRESS,
max(PL_AD_ADDRESS_USER1) PL_AD_ADDRESS_USER1,
max(PL_AD_ADDRESS_USER2) PL_AD_ADDRESS_USER2,
max(PL_AD_POSTCODE) PL_AD_POSTCODE,
max(PL_AD_COUNTRY) PL_AD_COUNTRY,
max(SUPHONE) SUPHONE,
max(SUSORT) SUSORT,
max(SUUSER1) SUUSER1,
max(SUUSER2) SUUSER2,
max(SUUSER3) SUUSER3,
max(isnull(SU_CIS300_NAME,'')) SU_CIS300_NAME,
max(isnull(SU_CIS_TITLE,'')) SU_CIS_TITLE,
max(isnull(SU_CIS_FORENAME1,'')) SU_CIS_FORENAME1,
max(isnull(SU_CIS_FORENAME2,'')) SU_CIS_FORENAME2,
max(isnull(SU_CIS_SURNAME,'')) SU_CIS_SURNAME,
max(isnull(SU_CIS_UTR,'')) SU_CIS_UTR,
case when max(SU_CIS_BUSINESS_TYPE)=1 then isnull(max(Verification_Number),'') else max(isnull(SU_VERIFICATION_NUMBER,'')) end SU_VERIFICATION_NUMBER,
max(PL_AD_EMAIL) PL_AD_EMAIL,
max(PL_AD_CC_EMAIL) PL_AD_CC_EMAIL,
case when min(CIP_TAX_PERCENTAGE) = max(CIP_TAX_PERCENTAGE) then max(CIP_TAX_PERCENTAGE) else -1 end CIP_TAX_PERCENTAGE,
max(CIP_TAX_STATUS) CIP_TAX_STATUS,
sum(case when CIP_USE_GROSS_MINUS_LEVY = 1 then CIP_GROSS-CIP_CITB_LEVY else CIP_GROSS end) CIP_GROSS,
sum(CIP_CITB_LEVY) CIP_CITB_LEVY,
sum(CIP_MATERIALS) CIP_MATERIALS,
sum(CIP_TAX_WITHHELD) CIP_TAX_WITHHELD,
max(CIP_PERIOD) CIP_PERIOD,
max(CIP_PERIOD_END_DATE) CIP_PERIOD_END_DATE,
min(convert(tinyint, CIP_PRINTED)) CIP_PRINTED, -- 1 if all have been printed
max(convert(tinyint,CIP_USE_GROSS_MINUS_LEVY)) CIP_USE_GROSS_MINUS_LEVY,
sum(CIP_GROSS - CIP_CITB_LEVY - CIP_TAX_WITHHELD) CIP_AMOUNT_PAYABLE,
1 As SYSTEM_LINK,
'ENGLISH' As LANGUAGE_LINK
from PL_ACCOUNTS
join CIS_PAYMENTS on CIP_CONTRACTOR_LINK = SU_PRIMARY
join PL_ADDRESSES on PL_AD_ACCCODE=SUCODE and PL_AD_STAT_ADD=1
left join
(Select
max(SU_VERIFICATION_NUMBER) Verification_Number,
substring(Payments.P_AL_HEADER_KEY, 2, 19) as Payment_Primary
from PL_ACCOUNTS
join PL_TRANSACTIONS on SUCODE=PT_PARTNER
join PL_ALLOC_HISTORY  Invoices on PT_HEADER_KEY=Invoices.P_AL_HEADER_KEY
join PL_ALLOC_HISTORY  Payments on Invoices.P_AL_REFERENCE=Payments.P_AL_REFERENCE
where SU_CIS_TAX_STATUS=3 and SU_VERIFICATION_NUMBER !='' and PT_TRANTYPE in ('INV','CRN') and Invoices.P_AL_ACCOUNT_CODE=PT_COPYSUPP and Payments.P_AL_REFERENCE<>'0'
group by Payments.P_AL_HEADER_KEY) Transactions
on CIP_PAYMENT_LINK=Payment_Primary
group by SUCODE, CIP_PERIOD