create view AA_STK_FIFO_ALLOCATION_HISTORY_VIEW 
as
-- SOP Orders
select 
 STK_ALINK_PRIMARY as [Seq]
,MO.SM_REFERENCE as OutMovementRef
,MO.SM_QUANTITY * MO.SM_QTYUNIT as OutMovementQuantity
,MO.SM_COSTPRICE as OutMovementCostPrice
,STK_ALINK_ORIGIN as OutOrigin
,OD_ORDER_NUMBER as OutOrderNo
,OD_Line_number as LineNumber
,OD_COSTPRICE as OutOrderCostprice
,OD_QTYORD * OD_QTYUNIT as OutQtyOrdered
,STK_ALINK_QUANTITY as AllocationQuantity
,MI.SM_QUANTITY * MI.SM_QTYUNIT as InQuantity
,MI.SM_ORIGIN as InOrigin
,MI.SM_REFERENCE as InRef
,CONVERT(DECIMAL(18,2),MI.SM_VALUE/(MI.SM_QUANTITY*MI.SM_QTYUNIT)) as InCostPrice
,MI.SM_PRIMARY as InSeq
,MI.SM_STOCK_CODE as Stkcode
from STK_ALLOCATION_LINK 
join STK_MOVEMENTS MI on MI.SM_PRIMARY = STK_ALINK_MOVEMENT_KEY 
join ORD_DETAIL on OD_PRIMARY = STK_ALINK_ORDER_LINK
join STK_ALLOCATIONS on STK_ALLOC_PRIMARY = STK_ALINK_ALLOCATION_KEY
left outer join STK_MOVEMENTS MO on MO.SM_PRIMARY = STK_ALINK_OUT_MOVEMENT_KEY 
where STK_ALINK_ORIGIN = 'S'

union
-- POP Credit Notes
select 
STK_ALINK_PRIMARY as [Seq]
,MO.SM_REFERENCE as OutMovementRef
,MO.SM_QUANTITY * MO.SM_QTYUNIT as OutMovementQuantity
,MO.SM_COSTPRICE as OutMovementCostPrice
,STK_ALINK_ORIGIN as OutOrigin
,POD_ORDER_NO as OutOrderNo
,POD_Line_number as LineNumber
,POD_QTYORD * POD_QTYUNIT as OutQtyOrdered
,NULL as OutOrderCostprice
,STK_ALINK_QUANTITY as AllocationQuantity
,MI.SM_QUANTITY * MI.SM_QTYUNIT as InQuantity
,MI.SM_ORIGIN as InOrigin
,MI.SM_REFERENCE as InRef
,CONVERT(DECIMAL(18,2),MI.SM_VALUE/(MI.SM_QUANTITY*MI.SM_QTYUNIT)) as CostPrice
, MI.SM_PRIMARY as InSeq
,MI.SM_STOCK_CODE as Stkcode
from STK_ALLOCATION_LINK 
join STK_MOVEMENTS MI on SM_PRIMARY = STK_ALINK_MOVEMENT_KEY
join STK_MOVEMENTS MO on MO.SM_PRIMARY = STK_ALINK_OUT_MOVEMENT_KEY 
join POP_DETAIL on POD_PRIMARY = STK_ALINK_ORDER_LINK
where STK_ALINK_ORIGIN = 'P'

union
-- STK Movements
select 
STK_ALINK_PRIMARY as [Seq]
,MO.SM_REFERENCE as OutMovementRef
,MO.SM_QUANTITY * MO.SM_QTYUNIT as OutMovementQuantity
,MO.SM_COSTPRICE as OutMovementCostPrice
,STK_ALINK_ORIGIN as OutOrigin
,Null as OutOrderNo
,NULL as LineNumber
,NULL as OutQtyOrdered
,NULL as OutOrderCostprice
,STK_ALINK_QUANTITY as AllocationQuantity
,MI.SM_QUANTITY * MI.SM_QTYUNIT as InQuantity
,MI.SM_ORIGIN as InOrigin
,MI.SM_REFERENCE as InRef
,CONVERT(DECIMAL(18,2),MI.SM_VALUE/(MI.SM_QUANTITY*MI.SM_QTYUNIT)) as CostPrice
, MI.SM_PRIMARY as InSeq
,MI.SM_STOCK_CODE as Stkcode
from STK_ALLOCATION_LINK 
join STK_MOVEMENTS MI on MI.SM_PRIMARY = STK_ALINK_MOVEMENT_KEY 
join STK_MOVEMENTS MO on MO.SM_PRIMARY = STK_ALINK_OUT_MOVEMENT_KEY 
where STK_ALINK_ORIGIN = 'M'