create view ARM_CM_CHANGE_LOG_VIEW

/*
** Written     :  16/8/2011 RL
** Last Amended:  
*/
AS
select 
CHL_FIELD_NAME, 
CHL_EVENT_ID_N,
CHL_DATETIME, 
CHL_ACTION, 
CHL_USERID, 
CHL_VALUE_O, 
CHL_VALUE_N, 
CHL_TABLE_NAME
from ARM_CM_CHANGE_LOG_VIEW_O
join ARM_CM_CHANGE_LOG_VIEW_N on CHL_EVENT_ID_O = CHL_EVENT_ID_N

UNION ALL

select 
CHL_FIELD_NAME, 
CHL_EVENT_ID, 
CHL_DATETIME, 
CHL_ACTION, 
CHL_USERID, 
'' 				as CHL_VALUE_O, 
CHL_VALUE		as CHL_VALUE_N, 
CHL_TABLE_NAME
from ARM_CM_CHANGE_LOG
where CHL_TYPE = 'NT' and CHL_ACTION = 'INSERT'

UNION ALL

select 
CHL_FIELD_NAME, 
CHL_EVENT_ID, 
CHL_DATETIME, 
CHL_ACTION, 
CHL_USERID, 
CHL_VALUE		as CHL_VALUE_O, 
''					as CHL_VALUE_N, 
CHL_TABLE_NAME
from ARM_CM_CHANGE_LOG
where CHL_TYPE = 'OT'and CHL_ACTION = 'DELETE'