
CREATE VIEW [dbo].[dhc_JCC_MonthlyClasification]
AS
	
	SELECT top 100 PERCENT STKCODE,
		ISNULL(QUANTITYCLASSIFICATION,'') AS QUANTITYCLASSIFICATION,
		ISNULL(FREQUENCY,0) AS FREQUENCY,
		ISNULL(QUANTITYCLASSIFICATIONPREVIOUS,'') AS QUANTITYCLASSIFICATIONPREVIOUS,
		ISNULL(VALUECLASSICICATION,'') AS VALUECLASSIFICATION,
		ISNULL(ORDERVALUE,0) AS ORDERVALUE,
		ISNULL(VALUECLASSICICATIONPREVIOUS,'') AS VALUECLASSIFICATIONPREVIOUS
	FROM STK_STOCK
		LEFT OUTER JOIN 
		(
			SELECT JSCH_STOCKCODE,
				JSCH_CLASSIFICATION AS QUANTITYCLASSIFICATION,
				JSCH_TRANS_FREQ AS FREQUENCY
			FROM DHC_TBL_JCC_STOCKCLASSHISTORY 
				INNER JOIN DHC_TBL_JCC_STOCKCLASSHISTORYDATES ON JSCH_DATEINDEX_LINK = JSCD_PRIMARY
			WHERE JSCD_TYPE='Q'
				AND JSCD_DATEINDEX = 1
		) Q ON STKCODE = Q.JSCH_STOCKCODE

		LEFT OUTER JOIN 
		(
			SELECT JSCH_STOCKCODE,
				JSCH_CLASSIFICATION AS VALUECLASSICICATION,
				JSCH_DEMAND_VAL AS ORDERVALUE
			FROM DHC_TBL_JCC_STOCKCLASSHISTORY 
				INNER JOIN DHC_TBL_JCC_STOCKCLASSHISTORYDATES ON JSCH_DATEINDEX_LINK = JSCD_PRIMARY
			WHERE JSCD_TYPE='V'
				AND JSCD_DATEINDEX = 1
		) V ON STKCODE = V.JSCH_STOCKCODE

		LEFT OUTER JOIN 
		(
			SELECT JSCH_STOCKCODE,
				JSCH_CLASSIFICATION AS QUANTITYCLASSIFICATIONPREVIOUS
			FROM DHC_TBL_JCC_STOCKCLASSHISTORY 
				INNER JOIN DHC_TBL_JCC_STOCKCLASSHISTORYDATES ON JSCH_DATEINDEX_LINK = JSCD_PRIMARY
			WHERE JSCD_TYPE='Q'
				AND JSCD_DATEINDEX = 2
		) QPREV ON STKCODE = QPREV.JSCH_STOCKCODE

		LEFT OUTER JOIN 
		(
			SELECT JSCH_STOCKCODE,
				JSCH_CLASSIFICATION AS VALUECLASSICICATIONPREVIOUS
			FROM DHC_TBL_JCC_STOCKCLASSHISTORY 
				INNER JOIN DHC_TBL_JCC_STOCKCLASSHISTORYDATES ON JSCH_DATEINDEX_LINK = JSCD_PRIMARY
			WHERE JSCD_TYPE='V'
				AND JSCD_DATEINDEX = 2
		) VPREV ON STKCODE = VPREV.JSCH_STOCKCODE
	ORDER BY STKCODE


