
CREATE VIEW [dbo].[dhc_JCC_WeeklyStockDemand]
AS
	SELECT	STKCODE as WeekDemandStockCode,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-65) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-64) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek65,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-64) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-63) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek64,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-63) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-62) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek63,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-62) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-61) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek62,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-61) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-60) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek61,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-60) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-59) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek60,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-59) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-58) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek59,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-58) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-57) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek58,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-57) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-56) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek57,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-56) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-55) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek56,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-55) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-54) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek55,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-54) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-53) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek54,
		
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-53) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-52) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek53,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-52) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-51) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek52,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-51) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-50) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek51,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-50) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-49) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek50,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-49) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-48) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek49,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-48) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-47) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek48,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-47) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-46) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek47,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-46) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-45) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek46,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-45) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-44) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek45,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-44) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-43) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek44,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-43) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-42) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek43,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-42) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-41) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek42,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-41) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-40) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek41,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-40) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-39) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek40,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-39) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-38) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek39,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-38) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-37) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek38,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-37) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-36) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek37,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-36) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-35) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek36,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-35) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-34) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek35,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-34) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-33) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek34,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-33) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-32) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek33,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-32) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-31) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek32,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-31) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-30) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek31,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-30) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-29) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek30,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-29) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-28) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek29,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-28) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-27) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek28,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-27) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-26) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek27,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-26) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-25) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek26,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-25) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-24) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek25,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-24) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-23) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek24,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-23) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-22) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek23,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-22) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-21) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek22,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-21) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-20) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek21,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-20) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-19) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek20,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-19) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-18) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek19,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-18) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-17) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek18,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-17) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-16) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek17,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-16) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-15) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek16,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-15) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-14) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek15,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-14) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-13) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek14,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-13) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-12) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek13,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-12) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-11) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek12,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-11) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-10) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek11,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-10) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-9) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek10,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-9) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-8) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek9,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-8) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-7) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek8,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-7) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-6) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek7,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-6) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-5) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek6,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-5) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-4) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek5,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-4) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-3) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek4,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-3) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-2) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek3,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-2) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),-1) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek2,
		isnull(sum(case when OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-1) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),0) then (case OD_TYPE when 'O' then OD_QTYORD else -OD_QTYORD end) else 0 end),0) as DemandPrevWeek1

	FROM STK_STOCK
		left outer join dhc_cons_ORD_DETAIL_grouped 
		on OD_STOCK_CODE=STKCODE and OD_DATE>=dbo.dhc_getWeekStartDate(getdate(),-65) and OD_DATE<dbo.dhc_getWeekStartDate(getdate(),0)
	where isnull(STKNAME,'')<>'DISCONTINUED'
		
	GROUP BY STKCODE

