








CREATE VIEW [dbo].[JCC_Quotations_LDL_Data]

/*
** Written     :  19/04/2013 AKT
** Last Amended:  21/06/2016 AKT	
**
*/

AS

SELECT

 proj.[OH_ACCOUNT] as AccountCode
,proj.[OH_ORDER_NUMBER] as OrderNumber
,proj.[OH_DATE] as QuoteDate
,CONVERT(CHAR(4), proj.[OH_DATE], 100) + CONVERT(CHAR(4), proj.[OH_DATE], 120) as QuoteYearMonth
,proj.[OH_ORDER_REF] as CustomerReference
,proj.[OH_GROSS] as OrderGrossValue
,proj.[OH_NETT] as OrderNettValue
,SUBSTRING(proj.[OH_CUSORT],6,255) as ASM
,proj.[OH_BATCH_REF] as ProjectReference
,
CASE
WHEN proj.[OH_SUB_LEDGER] = 'DHPROJECT' THEN 'Daniel Holden'
WHEN proj.[OH_SUB_LEDGER] = 'ITPROJECT' THEN 'Ian Tucker'
WHEN proj.[OH_SUB_LEDGER] = 'JIPROJECT' THEN 'Jason Ingham'
WHEN proj.[OH_SUB_LEDGER] = 'NCPROJECT' THEN 'Noel Cox'
WHEN proj.[OH_SUB_LEDGER] = 'SCPROJECT' THEN 'Sebastiano Crismann'
WHEN proj.[OH_SUB_LEDGER] = 'WJPROJECT' THEN 'Will Jennings'
WHEN proj.[OH_SUB_LEDGER] = 'LWPROJECT' THEN 'Lucy Wilson'
WHEN proj.[OH_SUB_LEDGER] = 'DTPROJECT' THEN 'Danielle Tuck'
WHEN proj.[OH_SUB_LEDGER] = 'ARPROJECT' THEN 'Annelise Roberts'
WHEN proj.[OH_SUB_LEDGER] = 'YHPROJECT' THEN 'Yazmin Hills'
WHEN proj.[OH_SUB_LEDGER] = 'AMPROJECT' THEN 'Anthony McCreadie'
WHEN proj.[OH_SUB_LEDGER] = 'ENPROJECT' THEN 'Ellie Noble'
WHEN proj.[OH_SUB_LEDGER] = 'LGPROJECT' THEN 'Luke Gibson'
WHEN proj.[OH_SUB_LEDGER] = 'RLPROJECT' THEN 'Robert Ljubojev'
ELSE ''
END
as ProjectManager
,
CASE
WHEN proj.[OH_WORK_STATUS] = 'Lighting Design' THEN 'Lighting Design'
WHEN proj.[OH_WORK_STATUS] = 'Spec Bust' THEN 'Spec Bust'
ELSE ''
END as LightingDesign
,proj.[OH_DESCRIPTION] as 'Generated By'
,'Projects' as [Database]
,proj.[OH_USER_PUTIN] as 'Created By'
FROM [JCC_PROJECTS].[dbo].[ORD_HEADER] proj
WHERE proj.[OH_PRIORITY] = 4
AND proj.[OH_DATE] > '2014-07-31 00:00:00.000'


UNION ALL


SELECT
 live.[OH_ACCOUNT] as AccountCode
,live.[OH_ORDER_NUMBER] as OrderNumber
,live.[OH_DATE] as QuoteDate
,CONVERT(CHAR(4), live.[OH_DATE], 100) + CONVERT(CHAR(4), live.[OH_DATE], 120) as QuoteYearMonth
,live.[OH_ORDER_REF] as CustomerReference
,live.[OH_GROSS] as OrderGrossValue
,live.[OH_NETT] as OrderNettValue
,SUBSTRING(live.[OH_CUSORT],6,255) as ASM
,live.[OH_BATCH_REF] as ProjectReference
,
CASE
WHEN live.[OH_SUB_LEDGER] = 'DHPROJECT' THEN 'Daniel Holden'
WHEN live.[OH_SUB_LEDGER] = 'ITPROJECT' THEN 'Ian Tucker'
WHEN live.[OH_SUB_LEDGER] = 'JIPROJECT' THEN 'Jason Ingham'
WHEN live.[OH_SUB_LEDGER] = 'NCPROJECT' THEN 'Noel Cox'
WHEN live.[OH_SUB_LEDGER] = 'SCPROJECT' THEN 'Sebastiano Crismann'
WHEN live.[OH_SUB_LEDGER] = 'WJPROJECT' THEN 'Will Jennings'
WHEN live.[OH_SUB_LEDGER] = 'LWPROJECT' THEN 'Lucy Wilson'
WHEN live.[OH_SUB_LEDGER] = 'DTPROJECT' THEN 'Danielle Tuck'
WHEN live.[OH_SUB_LEDGER] = 'ARPROJECT' THEN 'Annelise Roberts'
WHEN live.[OH_SUB_LEDGER] = 'YHPROJECT' THEN 'Yazmin Hills'
WHEN live.[OH_SUB_LEDGER] = 'AMPROJECT' THEN 'Anthony McCreadie'
WHEN live.[OH_SUB_LEDGER] = 'ENPROJECT' THEN 'Ellie Noble'
WHEN live.[OH_SUB_LEDGER] = 'LGPROJECT' THEN 'Luke Gibson'
WHEN live.[OH_SUB_LEDGER] = 'RLPROJECT' THEN 'Robert Ljubojev'
ELSE ''
END
as ProjectManager
,
CASE
WHEN live.[OH_WORK_STATUS] = 'Lighting Design' THEN 'Lighting Design'
WHEN live.[OH_WORK_STATUS] = 'Spec Bust' THEN 'Spec Bust'
ELSE ''
END as 'LightingDesign'
,live.[OH_DESCRIPTION] as 'Generated By'
,'Live' as [Database]
,live.[OH_USER_PUTIN] as 'Created By'
FROM [JCC_PROD_LIVE].[dbo].[ORD_HEADER] live
WHERE live.[OH_PRIORITY] = 4
AND live.[OH_DATE] > '2014-07-31 00:00:00.000'








