create view STK_ADV_KEY_DRILL

/*
**
** Advanced Price Matrix
**
** Written     :  Plug-Ins Team
** Last Amended:  10/06/2010 SM
**
*/

as
select 
 stkcode,
 stkname,
 stk_sort_key,
 stk_sort_key1,
 stk_sort_key2,
 stk_sort_key3,
 STP_PROD,
 STP_PROD_TYPE,
 STH_PRIMARY,
 STH_NAME,
 STH_EFFECTIVE,
 STH_EFFECTIVE_TO,
 STH_CURRENCY,
 STH_PRIORITY,
 STP_PRIMARY,
 STP_FIXED_OR_QTY,
 STPD_FROM,
 STPD_TO,
 STP_FIXED,
 STP_DISC,
 STP_TYPE,
 STK_BASEPRICE,
 CASE WHEN STH_TYPE='SPL' THEN
  CASE WHEN STP_TYPE=0 THEN 
   STP_FIXED
  WHEN STP_TYPE=3 THEN
      CASE WHEN STP_DISC=0 THEN
         STK_COSTPRICE+STP_DISC_CASH
      ELSE
         STK_COSTPRICE*(1+(STP_DISC/100))
      END
  ELSE 
   CASE WHEN STP_DISC=0 THEN
    CASE WHEN STK_BASEPRICE>STP_DISC_CASH  THEN 
     STK_BASEPRICE-STP_DISC_CASH 
    ELSE 
     STK_BASEPRICE 
    END
   ELSE
    (STK_BASEPRICE/100)*(100-STP_DISC) 
   END 
  END 
 ELSE
  CASE STP_BOGOF_TYPE 
   WHEN 0 THEN 0
   WHEN 1 THEN STP_FIXED
  ELSE
   (STK_BASEPRICE/100)*(100-STP_DISC)
  END
 END AS NEWPRICE,
 STH_CRYSTAL_REP,
 STH_TYPE,
 STH_SUB_FILTER,
 STP_DISC_CASH,
 STP_BUY_QTY,
 STP_FREE_QTY,
 STP_MAX_ALLOW,
 STP_BOGOF_TYPE,
 STP_MIN_QTY,
 STP_CHAIN,
 0 as WOD_QUAL_TYPE,
 0 as WOD_QUAL_VAL,
 0 as WOD_QUAL_QTY,
 0 as WOD_DISC_FIXED,
 0 as WOD_DISC_PERCENT,
 '' as WOD_PRCODE,
 STH_OVERRIDE,
 STH_SHOW_PROMPT,
 STH_USE_SUB_METHODS,
 STP_LOC1,STP_LOC2,STP_LOC3,STP_LOC4,STP_LOC5,STP_LOC6,
 STH_MATCH_ALL_CUST,STH_MATCH_ALL_PROD,
 STP_BGF_SAME_OR_DIF_PROD,STP_BGF_PROD_TYPE,STP_BGF_PROD,STP_IGNORE_DISC,
 STK_COSTPRICE,STK_COSTPRICE_C,STK_STNDRD_COST,0 as WOD_PRIMARY,0 as WOD_SINGLE_OR_MULTI,
 STH_APPLY_TO_SALES_ORDERS,STH_APPLY_TO_CREDIT_NOTES,
 0 as WOD_OFFER_TYPE,
 '' as WOD_PROD_TYPE,
 '' as WOD_PROD,
 0 as WOD_FREE_QTY,
 STH_GROSS_PRICES,
 STH_APPLY_TO_ALL_CUST,
 STH_APPLY_TO_ALL_PROD,
 STP_BGF_INCLUDE_ADD
from
STK_ADV_PRICE_MATRIX_SRCH with(nolock)
INNER JOIN STK_STOCK with(nolock) on  
((stkcode=STP_PROD and STP_PROD_TYPE='C')
 or (stk_sort_key=STP_PROD and STP_PROD_TYPE='S')
 or (stk_sort_key1=STP_PROD and STP_PROD_TYPE='1')
 or (stk_sort_key2=STP_PROD and STP_PROD_TYPE='2')
 or (stk_sort_key3=STP_PROD and STP_PROD_TYPE='3')
 or (STP_PROD_TYPE='X'))
 
and ISNULL(STK_DO_NOT_USE,0)<>1
--(sth_primary not in (select xid from STK_ADV_PROD_EXCLUDE where xcode=stkcode))
--and 


union

select 
 STKCODE,
 STKNAME,
 stk_sort_key,
 stk_sort_key1,
 stk_sort_key2,
 stk_sort_key3,
 stkcode as STP_PROD,
 'C' as STP_PROD_TYPE,
 STH_PRIMARY,
 STH_NAME,
 STH_EFFECTIVE,
 STH_EFFECTIVE_TO,
 STH_CURRENCY,
 STH_PRIORITY,
 STP_PRIMARY,
 WOD_SINGLE_OR_MULTI as STP_FIXED_OR_QTY,
 0 as STPD_FROM,
 0 as STPD_TO,
 0 as STP_FIXED,
 0 as STP_DISC,
 0 as STP_TYPE,
 STK_BASEPRICE,
 STK_BASEPRICE AS NEWPRICE,
 STH_CRYSTAL_REP,
 STH_TYPE,
 STH_SUB_FILTER,
 0 as STP_DISC_CASH,
 0 as STP_BUY_QTY,
 0 as STP_FREE_QTY,
 0 as STP_MAX_ALLOW,
 0 as STP_BOGOF_TYPE,
 0 as STP_MIN_QTY,
 0 as STP_CHAIN,
 WOD_QUAL_TYPE,
 WOD_QUAL_VAL,
 WOD_QUAL_QTY,
 WOD_DISC_FIXED,
 WOD_DISC_PERCENT,
 WOD_PRCODE,
 STH_OVERRIDE,
 STH_SHOW_PROMPT,
 0 as STH_USE_SUB_METHODS,
 '' as STP_LOC1,
 '' as STP_LOC2,
 '' as STP_LOC3,
 '' as STP_LOC4,
 '' as STP_LOC5,
 '' as STP_LOC6,
 STH_MATCH_ALL_CUST,STH_MATCH_ALL_PROD,
 STP_BGF_SAME_OR_DIF_PROD,STP_BGF_PROD_TYPE,STP_BGF_PROD,STP_IGNORE_DISC,
 STK_COSTPRICE,STK_COSTPRICE_C,STK_STNDRD_COST,
 WOD_PRIMARY,WOD_SINGLE_OR_MULTI,
 STH_APPLY_TO_SALES_ORDERS,STH_APPLY_TO_CREDIT_NOTES,
 WOD_OFFER_TYPE,
 WOD_PROD_TYPE,
 WOD_PROD,
 WOD_FREE_QTY,
 STH_GROSS_PRICES,
 STH_APPLY_TO_ALL_CUST,
 STH_APPLY_TO_ALL_PROD,
 0 as STP_BGF_INCLUDE_ADD
from
STK_ADV_MATRIX_SRCH_WOD with(nolock)
INNER JOIN STK_STOCK with(nolock)
on
((STKCODE=isnull(PROD_CODE,stkcode))
 and (stk_sort_key=isnull(prod_sort,stk_sort_key)) 
 and (stk_sort_key1=isnull(prod_sort1,stk_sort_key1)) 
 and (stk_sort_key2=isnull(prod_sort2,stk_sort_key2))
 or STP_PROD_TYPE='X')

 and ISNULL(STK_DO_NOT_USE,0)<>1