create view STK_ADV_PROD_VIEW_LIST

/*
**
** Advanced Price Matrix
**
** Written     :  Plug-Ins Team
** Last Amended:  10/06/2010 SM
**
*/
as

	 select
	      STP_PARENT,
			STOCK_CODE,
			STOCK_SORT,
			STOCK_USER1,
			STOCK_USER2,
			STOCK_USER3,
			CASE	SUBSTRING(PRS_PROD_DEF,1,1)
					WHEN 'C' THEN CASE WHEN ISNULL(STOCK_CODE,'') = '' THEN '' ELSE 'C' END
					WHEN 'S' THEN CASE WHEN ISNULL(STOCK_SORT,'') = '' THEN '' ELSE 'S' END
					WHEN '1' THEN CASE WHEN ISNULL(STOCK_USER1,'') = '' THEN '' ELSE '1' END
					WHEN '2' THEN CASE WHEN ISNULL(STOCK_USER2,'') = '' THEN '' ELSE '2' END
					WHEN '3' THEN CASE WHEN ISNULL(STOCK_USER3,'') = '' THEN '' ELSE '3' END
			END +
			CASE	SUBSTRING(PRS_PROD_DEF,2,1)
					WHEN 'C' THEN CASE WHEN ISNULL(STOCK_CODE,'') = '' THEN '' ELSE 'C' END
					WHEN 'S' THEN CASE WHEN ISNULL(STOCK_SORT,'') = '' THEN '' ELSE 'S' END
					WHEN '1' THEN CASE WHEN ISNULL(STOCK_USER1,'') = '' THEN '' ELSE '1' END
					WHEN '2' THEN CASE WHEN ISNULL(STOCK_USER2,'') = '' THEN '' ELSE '2' END
					WHEN '3' THEN CASE WHEN ISNULL(STOCK_USER3,'') = '' THEN '' ELSE '3' END
			END +
			CASE	SUBSTRING(PRS_PROD_DEF,3,1)
					WHEN 'C' THEN CASE WHEN ISNULL(STOCK_CODE,'') = '' THEN '' ELSE 'C' END
					WHEN 'S' THEN CASE WHEN ISNULL(STOCK_SORT,'') = '' THEN '' ELSE 'S' END
					WHEN '1' THEN CASE WHEN ISNULL(STOCK_USER1,'') = '' THEN '' ELSE '1' END
					WHEN '2' THEN CASE WHEN ISNULL(STOCK_USER2,'') = '' THEN '' ELSE '2' END
					WHEN '3' THEN CASE WHEN ISNULL(STOCK_USER3,'') = '' THEN '' ELSE '3' END
			END +
			CASE	SUBSTRING(PRS_PROD_DEF,4,1)
					WHEN 'C' THEN CASE WHEN ISNULL(STOCK_CODE,'') = '' THEN '' ELSE 'C' END
					WHEN 'S' THEN CASE WHEN ISNULL(STOCK_SORT,'') = '' THEN '' ELSE 'S' END
					WHEN '1' THEN CASE WHEN ISNULL(STOCK_USER1,'') = '' THEN '' ELSE '1' END
					WHEN '2' THEN CASE WHEN ISNULL(STOCK_USER2,'') = '' THEN '' ELSE '2' END
					WHEN '3' THEN CASE WHEN ISNULL(STOCK_USER3,'') = '' THEN '' ELSE '3' END
			END +
			CASE	SUBSTRING(PRS_PROD_DEF,5,1)
					WHEN 'C' THEN CASE WHEN ISNULL(STOCK_CODE,'') = '' THEN '' ELSE 'C' END
					WHEN 'S' THEN CASE WHEN ISNULL(STOCK_SORT,'') = '' THEN '' ELSE 'S' END
					WHEN '1' THEN CASE WHEN ISNULL(STOCK_USER1,'') = '' THEN '' ELSE '1' END
					WHEN '2' THEN CASE WHEN ISNULL(STOCK_USER2,'') = '' THEN '' ELSE '2' END
					WHEN '3' THEN CASE WHEN ISNULL(STOCK_USER3,'') = '' THEN '' ELSE '3' END
			END
			AS STOCK_TYPE,
			STP_PRIMARY
					
	 FROM
	 (
		SELECT	STP_PARENT,
				MAX(CASE WHEN STP_PROD_TYPE='C' THEN STP_PROD ELSE NULL END) as STOCK_CODE,
				MAX(CASE WHEN STP_PROD_TYPE='S' THEN STP_PROD ELSE NULL END) as STOCK_SORT,
				MAX(CASE WHEN STP_PROD_TYPE='1' THEN STP_PROD ELSE NULL END) as STOCK_USER1,
				MAX(CASE WHEN STP_PROD_TYPE='2' THEN STP_PROD ELSE NULL END) as STOCK_USER2,
				MAX(CASE WHEN STP_PROD_TYPE='3' THEN STP_PROD ELSE NULL END) as STOCK_USER3,
				MAX(STP_PRIMARY) as STP_PRIMARY,
				'' as STOCK_TYPE
		FROM	STK_PRICE_MATRIX_ADV with(nolock)
				JOIN STK_PRICE_LISTS with(nolock) on
				STH_PRIMARY=STP_PARENT
		WHERE  STH_MATCH_ALL_PROD = 1
		AND		STH_ACTIVE = 1
		AND		STP_EXCLUDE = 0
		GROUP BY STP_PARENT 
	 ) PROD_VIEW1,
	 STK_PRICE_LIST_SETTINGS WHERE 1=1

	 UNION

	 SELECT	STP_PARENT,
			CASE WHEN STP_PROD_TYPE='C' THEN STP_PROD ELSE NULL END as STOCK_CODE,
			CASE WHEN STP_PROD_TYPE='S' THEN STP_PROD ELSE NULL END as STOCK_SORT,
			CASE WHEN STP_PROD_TYPE='1' THEN STP_PROD ELSE NULL END as STOCK_USER1,
			CASE WHEN STP_PROD_TYPE='2' THEN STP_PROD ELSE NULL END as STOCK_USER2,
			CASE WHEN STP_PROD_TYPE='3' THEN STP_PROD ELSE NULL END as STOCK_USER3,
			STP_PROD_TYPE as STOCK_TYPE,
			STP_PRIMARY
	 FROM	STK_PRICE_MATRIX_ADV with(nolock)
			JOIN STK_PRICE_LISTS with(nolock) on
			STH_PRIMARY=STP_PARENT
	 WHERE  STH_MATCH_ALL_PROD = 0
	 AND	STH_ACTIVE = 1
	 AND	STP_EXCLUDE = 0