create view STK_ADV_PROD_GROUPS_EXCLUDE

/*
**
** Advanced Price Matrix
**
** Written     :  Plug-Ins Team
** Last Amended:  10/06/2010 SM
**
*/
as
SELECT DISTINCT STP_PARENT as XPGROUPID,STP_PROD as XPGROUPCODE,STP_PROD_TYPE as XPGROUPTYPE
	FROM STK_PRICE_MATRIX_ADV with(nolock)
JOIN STK_STOCK with(nolock) ON
		((STKCODE=STP_PROD AND STP_PROD_TYPE='C' and STP_EXCLUDE=1)
	OR	(STK_SORT_KEY=STP_PROD AND STP_PROD_TYPE='S' and STP_EXCLUDE=1)
	OR	(STK_SORT_KEY1=STP_PROD AND STP_PROD_TYPE='1' and STP_EXCLUDE=1)
	OR	(STK_SORT_KEY2=STP_PROD AND STP_PROD_TYPE='2' and STP_EXCLUDE=1)
	OR	(STK_SORT_KEY3=STP_PROD AND STP_PROD_TYPE='3' and STP_EXCLUDE=1))
	AND ISNULL(STKCODE,'')<>''
