create view STK_APM_SUB_ANALYSIS

/*
**
** Advanced Price Matrix
**
** Written     :  Plug-Ins Team
** Last Amended:  10/06/2010 SM
**
*/

as
SELECT	
      SUB_ANA_MAIN.PLSA_PARENT,
		SUB_ANA_1.PLSA_CODE as PLSA_CODE_1,
		SUB_ANA_2.PLSA_CODE as PLSA_CODE_2,
		SUB_ANA_3.PLSA_CODE as PLSA_CODE_3,
		SUB_ANA_4.PLSA_CODE as PLSA_CODE_4,
		SUB_ANA_5.PLSA_CODE as PLSA_CODE_5,
		SUB_ANA_6.PLSA_CODE as PLSA_CODE_6
	 
FROM         (select distinct PLSA_PARENT from STK_PRICE_MATRIX_SUB_ANA with(nolock) where PLSA_PARENT IS NOT NULL) SUB_ANA_MAIN 
			 left join (select PLSA_PRIMARY,PLSA_PARENT,PLSA_TYPE,PLSA_CODE from STK_PRICE_MATRIX_SUB_ANA with(nolock) where PLSA_TYPE=1) SUB_ANA_1
			 ON	SUB_ANA_MAIN.PLSA_PARENT=SUB_ANA_1.PLSA_PARENT 
			 left join (select PLSA_PRIMARY,PLSA_PARENT,PLSA_TYPE,PLSA_CODE from STK_PRICE_MATRIX_SUB_ANA with(nolock) where PLSA_TYPE=2) SUB_ANA_2
			 ON	SUB_ANA_MAIN.PLSA_PARENT=SUB_ANA_2.PLSA_PARENT 
			 left join (select PLSA_PRIMARY,PLSA_PARENT,PLSA_TYPE,PLSA_CODE from STK_PRICE_MATRIX_SUB_ANA with(nolock) where PLSA_TYPE=3) SUB_ANA_3
			 ON	SUB_ANA_MAIN.PLSA_PARENT=SUB_ANA_3.PLSA_PARENT
			 left join (select PLSA_PRIMARY,PLSA_PARENT,PLSA_TYPE,PLSA_CODE from STK_PRICE_MATRIX_SUB_ANA with(nolock) where PLSA_TYPE=4) SUB_ANA_4
			 ON	SUB_ANA_MAIN.PLSA_PARENT=SUB_ANA_4.PLSA_PARENT
			 left join (select PLSA_PRIMARY,PLSA_PARENT,PLSA_TYPE,PLSA_CODE from STK_PRICE_MATRIX_SUB_ANA with(nolock) where PLSA_TYPE=5) SUB_ANA_5
			 ON	SUB_ANA_MAIN.PLSA_PARENT=SUB_ANA_5.PLSA_PARENT
			 left join (select PLSA_PRIMARY,PLSA_PARENT,PLSA_TYPE,PLSA_CODE from STK_PRICE_MATRIX_SUB_ANA with(nolock) where PLSA_TYPE=6) SUB_ANA_6
			 ON	SUB_ANA_MAIN.PLSA_PARENT=SUB_ANA_6.PLSA_PARENT