create view STK_ADV_MATRIX_SRCH_WOD

/*
**
** Advanced Price Matrix
**
** Written     :  Plug-Ins Team
** Last Amended:  10/06/2010 SM
**
*/
as
select
 STK_PRICE_LISTS.STH_PRIMARY, STK_PRICE_LISTS.STH_NAME, STK_PRICE_LISTS.STH_EFFECTIVE,STH_EFFECTIVE_TO, 
 STK_PRICE_LISTS.STH_CURRENCY, STK_PRICE_LISTS.STH_PRIORITY, 
STK_PRICE_LISTS.STH_CRYSTAL_REP,STK_PRICE_LISTS.STH_TYPE,
ISNULL(STK_PRICE_LISTS.STH_SUB_FILTER,0) as STH_SUB_FILTER,
ISNULL(STK_PRICE_MATRIX_WOD.WOD_QUAL_TYPE,0) AS WOD_QUAL_TYPE,
ISNULL(STK_PRICE_MATRIX_WOD.WOD_QUAL_VAL,0) AS WOD_QUAL_VAL,
ISNULL(STK_PRICE_MATRIX_WOD.WOD_QUAL_QTY,0) AS WOD_QUAL_QTY,
ISNULL(STK_PRICE_MATRIX_WOD.WOD_DISC_FIXED,0) AS WOD_DISC_FIXED,
ISNULL(STK_PRICE_MATRIX_WOD.WOD_DISC_PERCENT,0) AS WOD_DISC_PERCENT, 
ISNULL(STK_PRICE_MATRIX_WOD.WOD_PRCODE,'') AS WOD_PRCODE,
MAX(CASE WHEN STP_PROD_TYPE='C' THEN STP_PROD ELSE NULL END) as PROD_CODE,
MAX(CASE WHEN STP_PROD_TYPE='S' THEN STP_PROD ELSE NULL END) as PROD_SORT,
MAX(CASE WHEN STP_PROD_TYPE='1' THEN STP_PROD ELSE NULL END) as PROD_SORT1,
MAX(CASE WHEN STP_PROD_TYPE='2' THEN STP_PROD ELSE NULL END) as PROD_SORT2,
MAX(CASE WHEN STP_PROD_TYPE='3' Then STP_PROD ELSE NULL END) as PROD_SORT3,
ISNULL(STH_OVERRIDE,0) AS STH_OVERRIDE,
ISNULL(STH_SHOW_PROMPT,0) AS STH_SHOW_PROMPT,
STH_MATCH_ALL_CUST,STH_MATCH_ALL_PROD,
STP_BGF_SAME_OR_DIF_PROD,STP_BGF_PROD_TYPE,STP_BGF_PROD,0 AS STP_IGNORE_DISC,
ISNULL(WOD_SINGLE_OR_MULTI,0) as WOD_SINGLE_OR_MULTI,
ISNULL(WOD_PRIMARY,0) as WOD_PRIMARY,
ISNULL(STP_PRIMARY,0) as STP_PRIMARY,
STH_APPLY_TO_SALES_ORDERS,
STH_APPLY_TO_CREDIT_NOTES,
WOD_OFFER_TYPE,
WOD_PROD_TYPE,
WOD_PROD,
WOD_FREE_QTY,
STH_GROSS_PRICES,
STH_APPLY_TO_ALL_CUST,
STH_APPLY_TO_ALL_PROD,
STP_PROD_TYPE
FROM
STK_PRICE_LISTS with(nolock) left OUTER JOIN
STK_PRICE_MATRIX_ADV with(nolock)  ON 
 STK_PRICE_LISTS.STH_PRIMARY = STK_PRICE_MATRIX_ADV.STP_PARENT 
left outer join dbo.STK_PRICE_MATRIX_WOD on STK_PRICE_MATRIX_WOD.WOD_PARENT=STH_PRIMARY
left outer join dbo.STK_PRICE_MATRIX_WOD_DET on STK_PRICE_MATRIX_WOD_DET.WODD_PARENT=WOD_PRIMARY
WHERE     (STK_PRICE_LISTS.STH_ACTIVE = 1) 
AND (STP_EXCLUDE=0)
AND (STH_TYPE='WOD')
GROUP BY
STK_PRICE_LISTS.STH_PRIMARY, STK_PRICE_LISTS.STH_NAME, STK_PRICE_LISTS.STH_EFFECTIVE,STH_EFFECTIVE_TO,
STK_PRICE_LISTS.STH_CURRENCY, STK_PRICE_LISTS.STH_PRIORITY,  
STK_PRICE_LISTS.STH_CRYSTAL_REP,STK_PRICE_LISTS.STH_TYPE,
ISNULL(STK_PRICE_LISTS.STH_SUB_FILTER,0),
ISNULL(STK_PRICE_MATRIX_WOD.WOD_QUAL_TYPE,0),
ISNULL(STK_PRICE_MATRIX_WOD.WOD_QUAL_VAL,0),
ISNULL(STK_PRICE_MATRIX_WOD.WOD_QUAL_QTY,0),
ISNULL(STK_PRICE_MATRIX_WOD.WOD_DISC_FIXED,0),
ISNULL(STK_PRICE_MATRIX_WOD.WOD_DISC_PERCENT,0), 
ISNULL(STK_PRICE_MATRIX_WOD.WOD_PRCODE,''),
STH_OVERRIDE,
STH_SHOW_PROMPT,
STH_MATCH_ALL_CUST,STH_MATCH_ALL_PROD,
STP_BGF_SAME_OR_DIF_PROD,STP_BGF_PROD_TYPE,STP_BGF_PROD,
ISNULL(WOD_SINGLE_OR_MULTI,0),
WOD_PRIMARY,
STP_PRIMARY,
STH_APPLY_TO_SALES_ORDERS,
STH_APPLY_TO_CREDIT_NOTES,
WOD_OFFER_TYPE,
WOD_PROD_TYPE,
WOD_PROD,
WOD_FREE_QTY,
STH_GROSS_PRICES,
STH_APPLY_TO_ALL_CUST,
STH_APPLY_TO_ALL_PROD,
STP_PROD_TYPE