create view STK_ADV_PRICE_MATRIX_SRCH

/*
**
** Advanced Price Matrix
**
** Written     :  Plug-Ins Team
** Last Amended:  10/06/2010 SM
**
*/

as
select     dbo.STK_PRICE_LISTS.STH_PRIMARY, dbo.STK_PRICE_LISTS.STH_NAME, dbo.STK_PRICE_LISTS.STH_EFFECTIVE,STH_EFFECTIVE_TO, STP_PRIMARY,
                      dbo.STK_PRICE_LISTS.STH_CURRENCY, dbo.STK_PRICE_LISTS.STH_PRIORITY,
                      dbo.STK_PRICE_MATRIX_ADV.STP_PROD, dbo.STK_PRICE_MATRIX_ADV.STP_PROD_TYPE, 
                      dbo.STK_PRICE_MATRIX_ADV.STP_FIXED_OR_QTY, dbo.STK_PRICE_MATRIX_DET.STPD_FROM, dbo.STK_PRICE_MATRIX_DET.STPD_TO,
   CASE WHEN STP_FIXED_OR_QTY=0 THEN STP_FIXED ELSE STPD_FIXED END AS STP_FIXED,
   CASE WHEN STP_FIXED_OR_QTY=0 THEN STP_DISC ELSE STPD_DISC END AS STP_DISC,
   CASE WHEN STP_FIXED_OR_QTY=0 THEN STP_TYPE ELSE STPD_TYPE END AS STP_TYPE,
   dbo.STK_PRICE_LISTS.STH_CRYSTAL_REP,dbo.STK_PRICE_LISTS.STH_TYPE,
   ISNULL(dbo.STK_PRICE_LISTS.STH_SUB_FILTER,0) as STH_SUB_FILTER,
   CASE WHEN STP_FIXED_OR_QTY=0 THEN STP_DISC_CASH ELSE STPD_DISC_CASH END AS STP_DISC_CASH,
   ISNULL(dbo.STK_PRICE_MATRIX_ADV.STP_BUY_QTY,0) AS STP_BUY_QTY,
   ISNULL(dbo.STK_PRICE_MATRIX_ADV.STP_FREE_QTY,0) AS STP_FREE_QTY,
   ISNULL(dbo.STK_PRICE_MATRIX_ADV.STP_MAX_ALLOW,0) AS STP_MAX_ALLOW,
   ISNULL(dbo.STK_PRICE_MATRIX_ADV.STP_BOGOF_TYPE,0) AS STP_BOGOF_TYPE,
   ISNULL(dbo.STK_PRICE_MATRIX_ADV.STP_MIN_QTY,0) AS STP_MIN_QTY,
   CASE WHEN STP_FIXED_OR_QTY=0 THEN CASE WHEN ISNULL(STP_CHAIN,0)=0 THEN 0 ELSE STP_CHAIN END ELSE CASE WHEN ISNULL(STPD_CHAIN,0)=0 THEN 0 ELSE STPD_CHAIN END END AS STP_CHAIN,
   0 AS WOD_QUAL_TYPE,
   0 AS WOD_QUAL_VAL,
   0 AS WOD_QUAL_QTY,
   0 AS WOD_DISC_FIXED,
   0 AS WOD_DISC_PERCENT, 
   0 AS WOD_PRCODE,
   ISNULL(STH_OVERRIDE,0) AS STH_OVERRIDE,
   ISNULL(STH_SHOW_PROMPT,0) AS STH_SHOW_PROMPT,
   STH_USE_SUB_METHODS,
   STP_LOC1,STP_LOC2,STP_LOC3,STP_LOC4,STP_LOC5,STP_LOC6,
   STH_MATCH_ALL_CUST,STH_MATCH_ALL_PROD,
   STP_BGF_SAME_OR_DIF_PROD,STP_BGF_PROD_TYPE,STP_BGF_PROD,
CASE WHEN STP_FIXED_OR_QTY=0 THEN STP_IGNORE_DISC ELSE STPD_IGNORE_DISC END AS STP_IGNORE_DISC,
STH_APPLY_TO_SALES_ORDERS,STH_APPLY_TO_CREDIT_NOTES, STP_BGF_INCLUDE_ADD, STH_GROSS_PRICES, STH_APPLY_TO_ALL_CUST,STH_APPLY_TO_ALL_PROD
FROM                  dbo.STK_PRICE_LISTS LEFT OUTER JOIN
                      dbo.STK_PRICE_MATRIX_DET INNER JOIN
                      dbo.STK_PRICE_MATRIX_ADV ON dbo.STK_PRICE_MATRIX_DET.STPD_HEADER = dbo.STK_PRICE_MATRIX_ADV.STP_PRIMARY ON 
                      dbo.STK_PRICE_LISTS.STH_PRIMARY = dbo.STK_PRICE_MATRIX_ADV.STP_PARENT

WHERE     (dbo.STK_PRICE_LISTS.STH_ACTIVE = 1)
AND (STH_TYPE<>'WOD')