CREATE VIEW [TS_CUSTOM_FORM_INBOX] AS 
    SELECT 
    APAL_INSERTED_DATE __ORDER, 
    CFSH_PRIMARY __DEFINITION_ID, 
    APAL_RECORD_LINK __RECORD_ID, 
    __STATUSCODE, 
    __APPROVERID, 
    __STATUSTEXT, 
    __STAGEID, 
    CFSH_NAME 'Type', 
    APAL_RECORD_LINK 'Reference', 
    APAL_INSERTED_DATE 'Date', 
    [Approver], 
    [Status], 
    [Stage], 
    [Previous User] 
    --CFLN_PARENT_TABLE_NAME 'Parent', 
    --CFLN_PARENT_FORM_ID 'Parent ID' 
    FROM TS_APPROVAL_LOG 
    INNER JOIN TS_CUSTOM_FORM_SETUP_HEAD ON APAL_RECORD_TYPE = CFSH_UNIQUE_CODE 
    INNER JOIN TS_CF_APPROVAL_STATUS ON [__RECORDTYPE] = APAL_RECORD_TYPE AND [__RECORDLINK] = APAL_RECORD_LINK 
    LEFT JOIN TS_CUSTOM_FORM_LINK ON CFLN_CHILD_FORM_TYPE_CODE = CFSH_UNIQUE_CODE AND CFLN_CHILD_FORM_ID = APAL_RECORD_LINK 
    WHERE APAL_CURRENT = 1