CREATE VIEW TS_LOOKUP_RESOURCE AS
-- TS_LOOKUP_RESOURCE Version 1
-- Written by Paul McNamara 12/01/2010
-- View used by custom forms resource lookup
-- Version History:
-- v1 – Initial version created by Paul McNamara 12/01/2010 for use with FP version 3.6.06
SELECT
PRCODE 'Code',
PRNAME 'Name',
PR_SORT_KEY 'Sort Key',
PR_SORT_KEY1 'Sort Key 1',
PR_SORT_KEY2 'Sort Key 2',
PR_SORT_KEY3 'Sort Key 3',
PR_SORT_KEY4 'Sort Key 4',
PR_SORT_KEY5 'Sort Key 5',
PR_SORT_KEY6 'Sort Key 6',
PRCODE '__CODE',
PRNAME '__NAME',
PR_SORT_KEY '__SORT_KEY',
PR_SORT_KEY1 '__SORT_KEY1',
PR_SORT_KEY2 '__SORT_KEY2',
PR_SORT_KEY3 '__SORT_KEY3',
PR_SORT_KEY4 '__SORT_KEY4',
PR_SORT_KEY5 '__SORT_KEY5',
PR_SORT_KEY6 '__SORT_KEY6',
PR_USRCHAR1 '__USRCHAR1',
PR_USRCHAR2 '__USRCHAR2',
PR_USRCHAR5 '__USRCHAR5',
PR_USRCHAR6 '__USRCHAR6',
PR_USRCHAR7 '__USRCHAR7',
PR_USRCHAR8 '__USRCHAR8'
FROM PRC_PRICE_RECS
LEFT JOIN PRC_PRICE_RECS2 ON PR_PRIMARY_2 = PR_PRIMARY