CREATE VIEW TS_LOOKUP_NOMINAL AS
SELECT
NCODE 'Code',
NNAME 'Name',
NL_MAJORNAME 'Major Heading',
NCURRENCYCODE '__CURRENCYCODE',
NTYPE '__TYPE',
NCODE '__CODE',
NNAME '__NAME'
FROM NL_ACCOUNTS
INNER JOIN NL_MAJORHEADING ON NL_MAJORCODE = NMAJORHEADCODE