CREATE VIEW TS_LOOKUP_SUPPLIER_CF AS
-- TS_LOOKUP_SUPPLIER_CF Version 1
-- Written by Paul McNamara 12/01/2010
-- View used by custom forms supplier lookup
-- Version History:
-- v1 – Initial version created by Paul McNamara 12/01/2010 for use with FP version 3.6.06
SELECT
SUCODE 'Code',
SUNAME 'Name',
SUSORT 'Sort Key',
SUADDRESS 'Address',
SUPOSTCODE 'Postcode',
SUCODE '__CODE',
SUNAME '__NAME',
SUSORT '__SORT',
SUUSER1 '__USER1',
SUUSER2 '__USER2',
SUUSER3 '__USER3',
SU_USRCHAR1 '__USRCHAR1',
SU_USRCHAR2 '__USRCHAR2',
SU_USRCHAR5 '__USRCHAR5',
SU_USRCHAR6 '__USRCHAR6',
SU_USRCHAR7 '__USRCHAR7',
SU_USRCHAR8 '__USRCHAR8',
SUCURRENCYCODE '__CURR_CODE',
CURR_SYMBOL '__CURR_SYMBOL',
SU_MULTI_CURR '__MULTI_CURR'
FROM PL_ACCOUNTS
LEFT JOIN PL_ACCOUNTS2 ON SUCODE2 = SUCODE
LEFT JOIN SYS_CURRENCY ON SUCURRENCYCODE = CURR_CODE
--WHERE LEN(CUCODE) > 0 AND CU_DO_NOT_USE = 0