CREATE VIEW [dbo].[TS_LOOKUP_CONTRACT] AS
-- TS_LOOKUP_CONTRACT Version 1
-- Written by Stefan Smidak 22/11/2012
-- View used by WFF contract lookup to return contact projects
-- Version History:
-- v1 – Initial version created by Stefan Smidak 22/11/2012 for use with WFF version 2.2.3 and Dim250G
SELECT
CCON_CONTRACT_NUMBER 'Code',
CH_CODE 'Project Code',
CH_NAME 'Name',
CH_DESCRIPTION 'Description',
CH_ACCOUNT + ' - ' + ISNULL(CUNAME,'') 'Account',
CH_SORT 'Sort Key',
CH_USER1 'User Sort 1',
CH_USER2 'User Sort 2',
CH_USER3 'User Sort 3',
CH_USER4 'User Sort 4',
CH_USER5 'User Sort 5',
CH_USER6 'User Sort 6',
CCON_CONTRACT_NUMBER '__CODE',
CH_CODE '__PROJECTCODE',
CH_NAME '__NAME',
CH_SORT '__SORT',
CH_STATUS '__STATUS',
CH_USER1 '__USER1',
CH_USER2 '__USER2',
CH_USER3 '__USER3',
CH_USER4 '__USER4',
CH_USER5 '__USER5',
CH_USER6 '__USER6',
CH_USRCHAR1 '__USRCHAR1',
CH_USRCHAR2 '__USRCHAR2',
CH_USRCHAR5 '__USRCHAR5',
CH_USRCHAR6 '__USRCHAR6',
CH_USRCHAR7 '__USRCHAR7',
CH_USRCHAR8 '__USRCHAR8'
FROM CST_COSTHEADER
LEFT JOIN CST_COSTHEADER2 ON CH_CODE2 = CH_CODE
LEFT JOIN SL_ACCOUNTS ON CUCODE = CH_ACCOUNT AND LEN(CUCODE) > 0
INNER JOIN CST_CONTRACTS on CCON_PRIMARY=CH_CONTRACT_LINK where CH_CODE!='' and CCON_MASTER_PROJECT_LINK=CH_PRIMARY