CREATE VIEW TS_LOOKUP_CUSTOMER_CF AS
-- TS_LOOKUP_CUSTOMER_CF Version 1
-- Written by Paul McNamara 12/01/2010
-- View used by custom forms customer lookup
-- Version History:
-- v1 – Initial version created by Paul McNamara 12/01/2010 for use with FP version 3.6.06
SELECT
CUCODE 'Code',
CUNAME 'Name',
CUSORT 'Sort Key',
CUADDRESS 'Address',
CUPOSTCODE 'Postcode',
CUCODE '__CODE',
CUNAME '__NAME',
CUSORT '__SORT',
CUUSER1 '__USER1',
CUUSER2 '__USER2',
CUUSER3 '__USER3',
CU_USRCHAR1 '__USRCHAR1',
CU_USRCHAR2 '__USRCHAR2',
CU_USRCHAR5 '__USRCHAR5',
CU_USRCHAR6 '__USRCHAR6',
CU_USRCHAR7 '__USRCHAR7',
CU_USRCHAR8 '__USRCHAR8',
CUCURRENCYCODE '__CURR_CODE',
CURR_SYMBOL '__CURR_SYMBOL',
CU_MULTI_CURR '__MULTI_CURR'
FROM SL_ACCOUNTS
LEFT JOIN SL_ACCOUNTS2 ON CUCODE2 = CUCODE
LEFT JOIN SYS_CURRENCY ON CUCURRENCYCODE = CURR_CODE
WHERE LEN(CUCODE) > 0 AND CU_DO_NOT_USE = 0