CREATE VIEW TS_SL_LOOKUP_ANALYSIS_CF AS
-- TS_SL_LOOKUP_ANALYSIS_CF Version 1
-- Written by Paul McNamara 12/01/2010
-- View used by custom forms analysis lookup
-- Version History:
-- v1 – Initial version created by Paul McNamara 12/01/2010 for use with FP version 3.6.06
SELECT
SACODE 'Code',
SANAME 'Name',
SASORT 'Sort Key', 
SA_USRCHAR1 'User Char 1',
SA_USRCHAR2 'User Char 2',
SA_USRCHAR3 'User Char 3', 
SA_USRCHAR4 'User Char 4',
SA_USRCHAR5 'User Char 5', 
SA_USRCHAR6 'User Char 6',
SA_USRCHAR1 '__USRCHAR1',
SA_USRCHAR2 '__USRCHAR2',
SA_USRCHAR5 '__USRCHAR5', 
SA_USRCHAR6 '__USRCHAR6',
SA_USRCHAR7 '__USRCHAR7', 
SA_USRCHAR8 '__USRCHAR8',
SASORT '__SORT',
SACODE '__CODE',
SANAME '__NAME',
SACURRENCYSYMBL '__CURR_SYMBOL',
SA_FORCE_COSTING '__FORCE_COSTING'
FROM SL_ANALYSIS 
LEFT JOIN SL_ANALYSIS2 ON SA_PRIMARY = SA_PRIMARY_2
WHERE (SATYPE_S_B_D = 'S') AND (SADEFAULT_ROUNDING = 0) AND SA_DO_NOT_USE = 0