

CREATE View [dbo].[Udef_WFF_STKENQ_PriceBook]
As
Select
	1 As [FormLink],
	STK_PRIMARY As [Primary],
	STKCODE2 As [Stock Code],
	Case When IsNull(STK_SELLPRICE1,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE1 End As [Price1],
	Case When IsNull(STK_SELLPRICE2,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE2 End As [Price2],
	Case When IsNull(STK_SELLPRICE3,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE3 End As [Price3],
	Case When IsNull(STK_SELLPRICE4,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE4 End As [Price4],
	Case When IsNull(STK_SELLPRICE5,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE5 End As [Price5],
	Case When IsNull(STK_SELLPRICE6,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE6 End As [Price6],
	Case When IsNull(STK_SELLPRICE7,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE7 End As [Price7],
	Case When IsNull(STK_SELLPRICE8,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE8 End As [Price8],
	Case When IsNull(STK_SELLPRICE9,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE9 End As [Price9],
	Case When IsNull(STK_SELLPRICE10,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE10 End As [Price10],
	
		Case When IsNull(STK_SELLPRICE1,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE1 End As [WHOLESALE],
	Case When IsNull(STK_SELLPRICE2,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE2 End As [PRICE BOOK B],
	Case When IsNull(STK_SELLPRICE3,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE3 End As [STOCKIST],
	Case When IsNull(STK_SELLPRICE4,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE4 End As [DEN/WILTS],
	Case When IsNull(STK_SELLPRICE5,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE5 End As [ELECTRIC CENTRE],
	Case When IsNull(STK_SELLPRICE6,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE6 End As [BEW],
	Case When IsNull(STK_SELLPRICE7,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE7 End As [EYRE & ELLISTON],
	Case When IsNull(STK_SELLPRICE8,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE8 End As [MEDLOCK],
	Case When IsNull(STK_SELLPRICE9,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE9 End As [KEW],
	Case When IsNull(STK_SELLPRICE10,0) = 0 Then STK_BASEPRICE Else STK_SELLPRICE10 End As [PRICE BOOK C]
From
	STK_STOCK
	Inner Join STK_STOCK_2 on STKCODE = STKCODE2


