
Create View Udef_WFF_STKENQ_PriceBookLookup
As
Select 1 As [PriceBook Link], STK_USRPRCKEY1 As [PriceBook Name] From dbo.LANG_USERFIELDS
UNION ALL 
Select 2, STK_USRPRCKEY2 From dbo.LANG_USERFIELDS
UNION ALL 
Select 3, STK_USRPRCKEY3 From dbo.LANG_USERFIELDS
UNION ALL 
Select 4, STK_USRPRCKEY4 From dbo.LANG_USERFIELDS
UNION ALL 
Select 5, STK_USRPRCKEY5 From dbo.LANG_USERFIELDS
UNION ALL 
Select 6, STK_USRPRCKEY6 From dbo.LANG_USERFIELDS
UNION ALL 
Select 7, STK_USRPRCKEY7 From dbo.LANG_USERFIELDS
UNION ALL 
Select 8, STK_USRPRCKEY8 From dbo.LANG_USERFIELDS
UNION ALL 
Select 9, STK_USRPRCKEY9 From dbo.LANG_USERFIELDS
UNION ALL 
Select 10, STK_USRPRCKEY10 From dbo.LANG_USERFIELDS
