CREATE VIEW UDEF_POP_ANALYSIS_CHECK
AS
SELECT POH_ORDER_NUMBR AS "ORDER_NO"
	,POH_DATE AS "ORDER_DATE"
	,POH_CURR_CODE AS "HEADER_CCY"
	,POD_LINE_NUMBER AS "LINE_NO"
	,POD_ENTRY_TYPE AS "LINE_TYPE"
	,POD_STOCK_CODE AS "STKCODE"
	,POD_ANALYSIS AS "ANALYSIS_CODE"
	,(
		SELECT PACURRENCYSYMBL
		FROM PL_ANALYSIS
		WHERE PACODE = POD_ANALYSIS
		) AS "DETAIL_CCY"
	,(
		SELECT ISNULL(PANAME, 'NO ANALYSIS CODE FOUND')
		FROM PL_ANALYSIS
		WHERE PACODE = (POD_ANALYSIS + substring(POH_CURR_CODE, 1, 2))
		) AS "SUGGESTED_ANALYSIS"
	,POD_PRIMARY AS "POD_PRIM"
FROM POP_HEADER
INNER JOIN POP_DETAIL ON POD_ORDER_NO = POH_ORDER_NUMBR
WHERE POH_CURR_CODE != '£'
	AND POH_STATUS < 2;