


CREATE VIEW [dbo].[UDEF_WFF_STKENQ_StockDataLink]
As
-- Created By:		Mike Young
-- Created On:		19/11/2014
-- Description:		Used by STKENQ WFF to lookup Stock Code
Select
	STKCODE As [Stock Code],
	STK_PHYSICAL As [Physical],
	STK_RESERVE_OUT As [Allocated Qty],
	SUM([LOC_BACK_ORDER_QTY]) as [Back Order Qty],
	--STK_PHYSICAL - (STK_WO_UNALLOC_QUANTITY + STK_RESERVE_OUT + STK_BACK_ORDER_QTY) As [Free Qty],
	SUM([LOC_PHYSICAL] - (LOC_WO_UNALLOC_QUANTITY + LOC_RESERVE_OUT + LOC_BACK_ORDER_QTY)) As [Free Qty],
	SUM([LOC_PHYSICAL] - (LOC_WO_UNALLOC_QUANTITY + LOC_RESERVE_OUT)) As [Available Stock],
	[STK_WO_ALLOC_QUANTITY] + [STK_WO_UNALLOC_QUANTITY] as [Works Order Demand],
	--[LOC_BACK_ORDER_QTY] as [Back Order Qty],
	STK_ORDER_IN As [Order In Qty]
From
	STK_STOCK With (NoLock)
	LEFT OUTER JOIN [STK_LOCATION] With (NoLock)
	ON [LOC_STOCK_CODE] = [STKCODE]
	WHERE [LOC_CODE] in ('PICK', 'BULK', 'EXT')
	GROUP BY [STKCODE], [STK_PHYSICAL], [STK_RESERVE_OUT], [STK_BACK_ORDER_QTY], [STK_WO_ALLOC_QUANTITY],[STK_WO_UNALLOC_QUANTITY], [STK_ORDER_IN]
	--ORDER BY [STKCODE]



