CREATE FUNCTION [dbo].[AA_ASSIGN_DEFAULT_VALUE_WITH_2_INVALIDS_F]
(@PS_DefaultString NVARCHAR (255) NULL, @PS_Mode NVARCHAR (1) NULL, @PS_DefaultStringCharPos TINYINT NULL, @PS_SuppliedValue SQL_VARIANT NULL, @PS_DefaultValue SQL_VARIANT NULL, @PS_ExistingValue SQL_VARIANT NULL, @PS_InvalidValue1 SQL_VARIANT NULL, @PS_InvalidValue2 SQL_VARIANT NULL)
RETURNS SQL_VARIANT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

