CREATE FUNCTION [dbo].[AA_AOI_INXL2_SYS_BUDGETS_SUM]
(@code1 VARCHAR (25) NULL, @code2 VARCHAR (25) NULL, @year INT NULL, @period INT NULL, @ytd INT NULL, @revision INT NULL, @B_RECORD_TYPE VARCHAR (1) NULL, @B_BUDGET_TYPE VARCHAR (1) NULL, @PROJECT_BUDGET_START_YEAR INT NULL, @PROJECT_BUDGET_START_PERIOD INT NULL, @NBR_OF_NL_PERIODS TINYINT NULL)
RETURNS FLOAT (53)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

