CREATE FUNCTION [dbo].[AA_CST_CENTRE_EDITABLE_F]
(@PF_CC_PRIMARY FLOAT (53) NULL, @PF_CC_COPYHEADER VARCHAR (10) NULL, @PF_CC_CODE VARCHAR (10) NULL)
RETURNS TINYINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

