CREATE FUNCTION [dbo].[AA_NL_LIST_NOMINAL_UPDATE_CODES_F]
(@PS_DET_HEADER_KEY VARCHAR (20) NULL, @PS_DET_PRIMARY FLOAT (53) NULL, @PS_ShowName BIT NULL)
RETURNS NVARCHAR (4000)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

