CREATE FUNCTION [dbo].[AA_NL_CATEGORY_EDITABLE_F]
(@PF_NL_CATCODE VARCHAR (6) NULL, @PF_CheckOption TINYINT NULL)
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

