CREATE FUNCTION [dbo].[AA_NET_BUILD_PROFILELEVEL_SQL_F]
(@PS_User_ID VARCHAR (4) NULL, @RecordList TINYINT NULL, @WhereClause VARCHAR (4000) NULL)
RETURNS VARCHAR (4000)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

