CREATE FUNCTION [dbo].[AA_PL_SUPPLIER_EDITABLE_F]
(@PF_SUCODE VARCHAR (10) NULL, @PF_CheckOption TINYINT NULL)
RETURNS TINYINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

