CREATE FUNCTION [dbo].[AA_SYS_SUB_LEDGER_EDITABLE_F]
(@PF_SUBL_CODE VARCHAR (10) NULL, @PF_CheckOption TINYINT NULL)
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

