CREATE FUNCTION [dbo].[AA_SL_CUSTOMER_EDITABLE_F]
(@PF_CUCODE VARCHAR (10) NULL, @PF_CheckOption TINYINT NULL)
RETURNS TINYINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

