CREATE FUNCTION [dbo].[AA_SYS_CURRENCY_REC_EDITABLE_F]
(@PF_CURREC_SYMBOL VARCHAR (4) NULL)
RETURNS TINYINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

