CREATE FUNCTION [dbo].[AA_SYS_CURRENCY_RATE_EDITABLE_F]
(@PF_CURR_CODE VARCHAR (4) NULL, @PF_CheckOption TINYINT NULL)
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

