CREATE FUNCTION [dbo].[AA_SL_TRN_LOCKED_ERROR_F]
(@PF_ST_PRIMARY INT NULL, @PF_STL_USER_ID VARCHAR (4) NULL, @PF_STL_OPERATION VARCHAR (2) NULL)
RETURNS VARCHAR (MAX)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

