CREATE FUNCTION [dbo].[AA_SL_CUSTOMER_ADDRESS_EDITABLE_F]
(@PF_AD_PRIMARY FLOAT (53) NULL, @PF_CHECK_OPTION TINYINT NULL)
RETURNS TINYINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

