CREATE FUNCTION [dbo].[PSH_WORK_OUT_PRICES_FUNC]
(@PriceDisc VARCHAR (1) NULL, @StockCode VARCHAR (25) NULL, @Key VARCHAR (5) NULL, @Quantity FLOAT (53) NULL, @ProcessPMatrix TINYINT NULL, @Customer VARCHAR (10) NULL, @CSort VARCHAR (20) NULL, @CUser1 VARCHAR (20) NULL, @CUser2 VARCHAR (20) NULL, @CUser3 VARCHAR (20) NULL, @OrderDate DATETIME NULL, @SSort VARCHAR (20) NULL, @SUser1 VARCHAR (20) NULL, @SUser2 VARCHAR (20) NULL, @SUser3 VARCHAR (20) NULL)
RETURNS FLOAT (53)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

