CREATE PROCEDURE [dbo].[AA_SYS_VATRATE_INSERT_EDIT_S]
@PS_Default_String VARCHAR (100) NULL, @PS_Mode VARCHAR (1) NULL, @PS_Validate_Only BIT NULL, @PS_User_Id VARCHAR (4) NULL, @PS_Code VARCHAR (4) NULL, @PS_Rate DECIMAL (24, 8) NULL, @PS_Description VARCHAR (40) NULL, @PS_EC_Type VARCHAR (1) NULL, @PS_Transaction_Type TINYINT NULL, @PS_Primary INT NULL OUTPUT, @PS_US_Sort_Code VARCHAR (4) NULL, @PS_US_Rate_1 DECIMAL (24, 8) NULL, @PS_US_Rate_2 DECIMAL (24, 8) NULL, @PS_US_Rate_3 DECIMAL (24, 8) NULL, @PS_US_Rate_4 DECIMAL (24, 8) NULL, @PS_US_Rate_5 DECIMAL (24, 8) NULL, @PS_US_Rate_6 DECIMAL (24, 8) NULL, @PS_Source VARCHAR (1) NULL, @PS_ErrorHandlingMethod TINYINT NULL, @PS_InstanceID BIGINT NULL OUTPUT, @PS_ObjectGuid UNIQUEIDENTIFIER NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


