CREATE PROCEDURE [dbo].[AA_SYS_CONFIG_CST_TRAN_SUBTYPES_TEMP_INSERT_S]
@PS_UserId VARCHAR (4) NULL, @PS_BatchGuid UNIQUEIDENTIFIER NULL, @PS_Primary INT NULL, @PS_Type VARCHAR (3) NULL, @PS_Name VARCHAR (10) NULL, @PS_Description VARCHAR (40) NULL, @PS_Status INT NULL, @PS_DefaultString VARCHAR (5) NULL, @PS_DeleteFlag BIT NULL, @PS_ErrorInstanceId BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod TINYINT NULL, @PS_ObjectGuid UNIQUEIDENTIFIER NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


