CREATE PROCEDURE [dbo].[AA_SYS_TRANSACTION_TEMPLATE_DEFAULT_TOGGLE_S]
@PS_User_Id NVARCHAR (4) NULL, @PS_Primary INT NULL OUTPUT, @PS_SetAsUserDefault TINYINT NULL, @PS_SetAsSystemDefault TINYINT NULL, @PS_ErrorHandlingMethod TINYINT NULL, @PS_InstanceId BIGINT NULL OUTPUT, @PS_ObjectGuid UNIQUEIDENTIFIER NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


