CREATE PROCEDURE [dbo].[AA_SYS_WINDOW_LAYOUT_INSERT_EDIT_S]
@PS_UserId VARCHAR (4) NULL, @PS_Mode VARCHAR (1) NULL, @PS_ValidateOnly BIT NULL, @PS_LayoutName NVARCHAR (255) NULL, @PS_BatchGuid UNIQUEIDENTIFIER NULL, @PS_Primary INT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_InstanceID BIGINT NULL OUTPUT, @PS_ObjectGuid UNIQUEIDENTIFIER NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


