CREATE PROCEDURE [dbo].[AA_SYS_RETURN_DEFAULT_USER_SEARCHES_S]
@PS_User_Id VARCHAR (4) NULL, @Error_Instance_ID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod TINYINT NULL, @PS_InstanceID BIGINT NULL OUTPUT, @PS_ObjectGuid UNIQUEIDENTIFIER NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


