CREATE PROCEDURE [dbo].[AA_SYS_EDIT_POSTED_TRANS_DETAIL_S]
@PS_DefaultString VARCHAR (50) NULL, @PS_ValidateOnly BIT NULL, @PS_UserID VARCHAR (4) NULL, @PS_Primary INT NULL, @PS_Description VARCHAR (240) NULL, @PS_JournalLineRef VARCHAR (10) NULL, @PS_Archived BIT NULL, @PS_TranUserKey1 NVARCHAR (20) NULL, @PS_TranUserKey2 NVARCHAR (20) NULL, @PS_TranUserKey3 NVARCHAR (20) NULL, @PS_UserChar1 NVARCHAR (20) NULL, @PS_UserChar2 NVARCHAR (20) NULL, @PS_UserChar3 NVARCHAR (100) NULL, @PS_UserChar4 NVARCHAR (100) NULL, @PS_UserFlag1 TINYINT NULL, @PS_UserFlag2 TINYINT NULL, @PS_UserDate1 DATETIME NULL, @PS_UserDate2 DATETIME NULL, @PS_UserNumber1 DECIMAL (24, 8) NULL, @PS_UserNumber2 DECIMAL (24, 8) NULL, @PS_Source VARCHAR (1) NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod BIT NULL, @PS_CO2_ClassificationID CHAR (4) NULL, @PS_CO2_ConsumptionDate DATETIME NULL, @PS_CO2_Year SMALLINT NULL, @PS_CO2_Period TINYINT NULL, @PS_CO2_Quantity DECIMAL (24, 8) NULL, @PS_CO2_FirstCategoryLink INT NULL, @PS_CO2_SecondCategoryLink INT NULL, @PS_CO2_FirstCategoryCode VARCHAR (6) NULL, @PS_CO2_SecondCategoryCode VARCHAR (6) NULL, @PS_CO2_UnitOfMeasure VARCHAR (20) NULL, @PS_CO2_EmissionsGroupID VARCHAR (2) NULL, @PS_CO2_GHG_Scope TINYINT NULL, @PS_CO2_SortKey1 VARCHAR (20) NULL, @PS_CO2_SortKeyCreate1 BIT NULL, @PS_CO2_SortKey2 VARCHAR (20) NULL, @PS_CO2_SortKeyCreate2 BIT NULL, @PS_CO2_SortKey3 VARCHAR (20) NULL, @PS_CO2_SortKeyCreate3 BIT NULL, @PS_CO2_SortKey4 VARCHAR (20) NULL, @PS_CO2_SortKeyCreate4 BIT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


