CREATE PROCEDURE [dbo].[AA_SYS_REPORT_OPTIONS_DEFAULT_INSERT_EDIT_S]
@PS_Primary BIGINT NULL, @PS_UserID VARCHAR (4) NULL, @PS_ErrorHandlingMethod TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ObjectGuid UNIQUEIDENTIFIER NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


