CREATE PROCEDURE [dbo].[AA_SYS_CURR_CODE_LIST_S]
@PS_UserID NVARCHAR (4) NULL, @PS_MaxRecords INT NULL, @PS_CalledFrom INT NULL, @PS_StartValue SQL_VARIANT NULL, @PS_StartPrimary INT NULL, @PS_OrderByDescending TINYINT NULL, @PS_OrderByFieldName [sysname] NULL, @PS_TotalRecordCount INT NULL OUTPUT, @PS_AdvancedResponse TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL, @PS_OutputMode TINYINT NULL, @PS_GetMinPrimary BIT NULL, @PS_MinPrimaryValue INT NULL OUTPUT, @PS_TransactionDate DATETIME NULL, @PS_PrimaryFrom INT NULL, @PS_PrimarySearch TINYINT NULL, @PS_PrimaryTo INT NULL, @PS_CodeFrom NVARCHAR (4) NULL, @PS_CodeSearch TINYINT NULL, @PS_CodeTo NVARCHAR (4) NULL, @PS_SymbolFrom NVARCHAR (4) NULL, @PS_SymbolSearch TINYINT NULL, @PS_SymbolTo NVARCHAR (4) NULL, @PS_RateDateFrom DATETIME NULL, @PS_RateDateSearch TINYINT NULL, @PS_RateDateTo DATETIME NULL, @PS_TypeFrom NVARCHAR (1) NULL, @PS_TypeSearch TINYINT NULL, @PS_TypeTo NVARCHAR (1) NULL, @PS_ModifiedDateFrom DATETIME NULL, @PS_ModifiedDateSearch TINYINT NULL, @PS_ModifiedDateTo DATETIME NULL, @PS_CreatedDateFrom DATETIME NULL, @PS_CreatedDateSearch TINYINT NULL, @PS_CreatedDateTo DATETIME NULL, @PS_ModifiedUserFrom NVARCHAR (4) NULL, @PS_ModifiedUserSearch TINYINT NULL, @PS_ModifiedUserTo NVARCHAR (4) NULL, @PS_CreatedUserFrom NVARCHAR (4) NULL, @PS_CreatedUserSearch TINYINT NULL, @PS_CreatedUserTo NVARCHAR (4) NULL, @PS_CustomerCode NVARCHAR (10) NULL, @PS_SupplierCode NVARCHAR (10) NULL, @PS_NominalCode NVARCHAR (25) NULL, @PS_SalesAnalysisFrom NVARCHAR (25) NULL, @PS_SalesAnalysisSearch TINYINT NULL, @PS_SalesAnalysisTo NVARCHAR (25) NULL, @PS_PurchaseAnalysisFrom NVARCHAR (25) NULL, @PS_PurchaseAnalysisSearch TINYINT NULL, @PS_PurchaseAnalysisTo NVARCHAR (25) NULL, @PS_IncludeEU TINYINT NULL, @PS_IncludeNonEU TINYINT NULL, @PS_Include2ndBase TINYINT NULL, @PS_IncludeDirect TINYINT NULL, @PS_IncludeTriangulated TINYINT NULL, @PS_IncludeExcluded BIT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


