CREATE PROCEDURE [dbo].[AA_SYS_CONFIG_SYS_INSERT_EDIT_S]
@PS_CompulsoryName BIT NULL, @PS_EnableSalesAnalysisMatrix BIT NULL, @PS_EnablePurchaseAnalysisMatrix BIT NULL, @PS_CompulsoryCosting BIT NULL, @PS_CompulsorySubLedger BIT NULL, @PS_DoNotAllowSLRefChange BIT NULL, @PS_DateSensitiveRates BIT NULL, @PS_AllocateLatestTranYear BIT NULL, @PS_MaxRecordListSize INT NULL, @PS_MaxTranListSize INT NULL, @PS_DefaultHelpPath VARCHAR (255) NULL, @PS_RemoteHelpPath VARCHAR (255) NULL, @PS_MaxAttachmentFileSize INT NULL, @PS_AllStationeryUnits TINYINT NULL, @PS_FaxLeftMargin FLOAT (53) NULL, @PS_FaxPageSize TINYINT NULL, @PS_ChequeStationery INT NULL, @PS_LaserCheques BIT NULL, @PS_BulkReceiptStationery INT NULL, @PS_RemittanceStationery INT NULL, @PS_BACSStationery INT NULL, @PS_SLAllocStatementStationery INT NULL, @PS_SLStatementStationery INT NULL, @PS_PLStatementStationery INT NULL, @PS_LinesPerPage TINYINT NULL, @PS_ChequeTopMargin FLOAT (53) NULL, @PS_ChequeLeftMargin FLOAT (53) NULL, @PS_PrePrintedLines BIT NULL, @PS_FinancialYearStartDate DATETIME NULL, @PS_SLPeriod FLOAT (53) NULL, @PS_PLPeriod FLOAT (53) NULL, @PS_NLPeriod FLOAT (53) NULL, @PS_SalesYear VARCHAR (2) NULL, @PS_PurchaseYear VARCHAR (2) NULL, @PS_NoOfPeriods INT NULL, @PS_Period1From DATETIME NULL, @PS_Period2From DATETIME NULL, @PS_Period3From DATETIME NULL, @PS_Period4From DATETIME NULL, @PS_Period5From DATETIME NULL, @PS_Period6From DATETIME NULL, @PS_Period7From DATETIME NULL, @PS_Period8From DATETIME NULL, @PS_Period9From DATETIME NULL, @PS_Period10From DATETIME NULL, @PS_Period11From DATETIME NULL, @PS_Period12From DATETIME NULL, @PS_Period13From DATETIME NULL, @PS_DisableNLAuditCheck BIT NULL, @PS_DisableSLAuditCheck BIT NULL, @PS_DisablePLAuditCheck BIT NULL, @PS_ExportCode BIT NULL, @PS_VATID INT NULL, @PS_VATRegPrefix VARCHAR (4) NULL, @PS_VATRegNo VARCHAR (15) NULL, @PS_EMUMemberCurrency BIT NULL, @PS_Base2Currency VARCHAR (4) NULL, @PS_RoundingDifference VARCHAR (2) NULL, @PS_VATSettlementDiscMethod TINYINT NULL, @PS_HomeCountry VARCHAR (4) NULL, @PS_HomeCurrency VARCHAR (4) NULL, @PS_PreviousSalesPeriod FLOAT (53) NULL, @PS_PreviousPurchasePeriod FLOAT (53) NULL, @PS_PreviousNominalPeriod FLOAT (53) NULL, @PS_PreviousSalesUpdateYear VARCHAR (1) NULL, @PS_PreviousPurchaseUpdateYear VARCHAR (1) NULL, @PS_PreviousSalesUpdateNominal FLOAT (53) NULL, @PS_PreviousPurchUpdateNominal FLOAT (53) NULL, @PS_PeriodsNotSaved BIT NULL OUTPUT, @PS_CompanyEmailDisplayName [sysname] NULL, @PS_SMTPEmailServer [sysname] NULL, @PS_SMTPPassword [sysname] NULL, @PS_SMTPAccountName [sysname] NULL, @PS_SMTPAuthenticationType TINYINT NULL, @PS_CompanyEmailAddress [sysname] NULL, @PS_UserID VARCHAR (4) NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ErrorHandlingMethod INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


