CREATE PROCEDURE [dbo].[AA_SYS_SAVED_SEARCH_CRITERIA_DEFAULT_TOGGLE_S]
@PS_User_Id VARCHAR (4) NULL, @PS_Primary INT NULL OUTPUT, @PS_ErrorHandlingMethod TINYINT NULL, @PS_InstanceId BIGINT NULL OUTPUT, @PS_ObjectGuid UNIQUEIDENTIFIER NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


