CREATE PROCEDURE [dbo].[AA_X_CST_BATCH_DETAIL_S]
@PS_DefaultString VARCHAR (100) NULL, @PS_ValidateOnly BIT NULL, @PS_UserId VARCHAR (4) NULL, @PS_Module VARCHAR (3) NULL, @PS_Primary INT NULL OUTPUT, @PS_TransactionStatus CHAR (1) NULL, @PS_TransactionType VARCHAR (3) NULL, @PS_TransactionReference VARCHAR (10) NULL, @PS_BatchReference VARCHAR (10) NULL, @PS_TransactionDate DATETIME NULL, @PS_WeekNo TINYINT NULL, @PS_Year CHAR (1) NULL, @PS_PeriodNumber TINYINT NULL, @PS_Description VARCHAR (20) NULL, @PS_CostHeader VARCHAR (10) NULL, @PS_CostCentre VARCHAR (10) NULL, @PS_ResourceCode VARCHAR (16) NULL, @PS_ResourceRate INT NULL, @PS_CurrencyCode VARCHAR (4) NULL, @PS_Quantity DECIMAL (24, 8) NULL, @PS_HomePrice DECIMAL (24, 8) NULL, @PS_CurrencyPrice DECIMAL (24, 8) NULL, @PS_HomeValue DECIMAL (24, 8) NULL, @PS_CC_Uplift DECIMAL (24, 8) NULL, @PS_CC_TotalUpliftVal DECIMAL (24, 8) NULL, @PS_CC_TotalUpliftVal_Curr DECIMAL (24, 8) NULL, @PS_ResourcePayrollPaytype VARCHAR (20) NULL, @PS_Detail VARCHAR (240) NULL, @PS_ArchiveFlag TINYINT NULL, @PS_DoNotBatch TINYINT NULL, @PS_ExcludeResourceUplift TINYINT NULL, @PS_Source VARCHAR (1) NULL, @PS_EnterCurrency TINYINT NULL, @PS_UserChar1 VARCHAR (20) NULL, @PS_UserChar2 VARCHAR (20) NULL, @PS_UserChar3 VARCHAR (100) NULL, @PS_UserChar4 VARCHAR (100) NULL, @PS_UserFlag1 TINYINT NULL, @PS_UserFlag2 TINYINT NULL, @PS_UserDate1 DATETIME NULL, @PS_UserDate2 DATETIME NULL, @PS_UserNumber1 DECIMAL (24, 8) NULL, @PS_UserNumber2 DECIMAL (24, 8) NULL, @PS_UserPutin VARCHAR (4) NULL, @PS_HeaderLink VARCHAR (20) NULL OUTPUT, @PS_CalledFrom INT NULL, @PS_UserKey1 VARCHAR (20) NULL, @PS_UserKey2 VARCHAR (20) NULL, @PS_UserKey3 VARCHAR (20) NULL, @PS_TransactionSubType INT NULL, @PS_CustomerCode VARCHAR (10) NULL, @PS_CurrencySymbol VARCHAR (4) NULL, @PS_CurrencyRate DECIMAL (16, 6) NULL, @PS_CurrencyValue DECIMAL (24, 8) NULL, @PS_CC_Markup DECIMAL (24, 8) NULL, @PS_CC_TotalMarkupVal DECIMAL (24, 8) NULL, @PS_CC_TotalMarkupVal_Curr DECIMAL (24, 8) NULL, @PS_SupplierCode VARCHAR (10) NULL, @PS_TimeUnits DECIMAL (24, 8) NULL, @PS_TimeUnitType VARCHAR (1) NULL, @PS_TimeUnitQuantity DECIMAL (24, 8) NULL, @PS_CC_UpliftType TINYINT NULL, @PS_CC_MarkupType TINYINT NULL, @PS_CC_UpliftVal_Curr DECIMAL (24, 8) NULL, @PS_ErrorHandlingMethod TINYINT NULL, @PS_ErrorInstanceID BIGINT NULL OUTPUT, @PS_ObjectGuid UNIQUEIDENTIFIER NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


