CREATE PROCEDURE TSSP_DUPLICATE_DOCUMENTS
 @AccountCode VARCHAR(25),
 @RecordType VARCHAR(25),
 @NewAccountCode VARCHAR(25),
 @UserID VARCHAR(4)
AS
SELECT * INTO #TEMP_DOCS
FROM TS_DOCUMENTS
WHERE TSDOC_ACCOUNT_CODE = @AccountCode
AND TSDOC_RECORD_TYPE = @RecordType

--SELECT COUNT(*) FROM #TEMP_DOCS

DECLARE @TSDOC_PRIMARY FLOAT
DECLARE @NewPrimary FLOAT

DECLARE TempDocCursor CURSOR LOCAL FOR 
SELECT TSDOC_PRIMARY FROM #TEMP_DOCS

OPEN TempDocCursor

FETCH NEXT FROM TempDocCursor INTO @TSDOC_PRIMARY

WHILE @@FETCH_STATUS > -1
BEGIN
    
 EXEC tssp_get_sequence 'TSDC', @NewPrimary OUTPUT

 UPDATE #TEMP_DOCS SET TSDOC_PRIMARY = @NewPrimary WHERE TSDOC_PRIMARY = @TSDOC_PRIMARY

 FETCH NEXT FROM TempDocCursor INTO @TSDOC_PRIMARY

END

CLOSE TempDocCursor
DEALLOCATE TempDocCursor

INSERT INTO
 TS_DOCUMENTS
 (TSDOC_PRIMARY, TSDOC_ACCOUNT_CODE, TSDOC_SECONDARY_CODE, TSDOC_RECORD_TYPE, TSDOC_CONTENT_TYPE, TSDOC_NAME, TSDOC_EXTENSION, TSDOC_DATA, TSDOC_DATE_ENTERED, TSDOC_USERID, TSDOC_DESCRIPTION, TSDOC_SIZE, TSDOC_PATH, TSDOC_SORTKEY, TSDOC_MIGRATED, TSDOC_NOTES)
SELECT
 TSDOC_PRIMARY,
 @NewAccountCode,
 TSDOC_SECONDARY_CODE,
 TSDOC_RECORD_TYPE,
 TSDOC_CONTENT_TYPE,
 TSDOC_NAME,
 TSDOC_EXTENSION,
 TSDOC_DATA,
 GETDATE(),
 @UserID,
 TSDOC_DESCRIPTION,
 TSDOC_SIZE,
 TSDOC_PATH,
 TSDOC_SORTKEY,
 TSDOC_MIGRATED,
 TSDOC_NOTES
FROM #TEMP_DOCS