CREATE TABLE [dbo].[AA_AOI_MANAGEMENT_REPORT] (
    [GUID]                           VARCHAR (36) NOT NULL,
    [ROW_NBR_IN_GUID]                INT          NULL,
    [Dataset]                        VARCHAR (6)  NOT NULL,
    [NominalAccountCode]             VARCHAR (25) NULL,
    [NominalAccountName]             VARCHAR (40) NULL,
    [NominalAccountInactive]         TINYINT      NULL,
    [MajorHeadingCode]               TINYINT      NULL,
    [MajorHeadingName]               VARCHAR (40) NULL,
    [CategoryCode1]                  VARCHAR (10) NULL,
    [CategoryName1]                  VARCHAR (50) NULL,
    [CategoryCode2]                  VARCHAR (10) NULL,
    [CategoryName2]                  VARCHAR (50) NULL,
    [CategoryCode3]                  VARCHAR (10) NULL,
    [CategoryName3]                  VARCHAR (50) NULL,
    [CategoryCode4]                  VARCHAR (10) NULL,
    [CategoryName4]                  VARCHAR (50) NULL,
    [CategoryCode5]                  VARCHAR (10) NULL,
    [CategoryName5]                  VARCHAR (50) NULL,
    [CategoryCode6]                  VARCHAR (10) NULL,
    [CategoryName6]                  VARCHAR (50) NULL,
    [CategoryCode7]                  VARCHAR (10) NULL,
    [CategoryName7]                  VARCHAR (50) NULL,
    [CategoryCode8]                  VARCHAR (10) NULL,
    [CategoryName8]                  VARCHAR (50) NULL,
    [NominalAttributeCode1]          VARCHAR (10) NULL,
    [NominalAttributeDescription1]   VARCHAR (30) NULL,
    [NominalAttributeCode2]          VARCHAR (10) NULL,
    [NominalAttributeDescription2]   VARCHAR (30) NULL,
    [NominalAttributeCode3]          VARCHAR (10) NULL,
    [NominalAttributeDescription3]   VARCHAR (30) NULL,
    [NominalAttributeCode4]          VARCHAR (10) NULL,
    [NominalAttributeDescription4]   VARCHAR (30) NULL,
    [NominalAttributeCode5]          VARCHAR (10) NULL,
    [NominalAttributeDescription5]   VARCHAR (30) NULL,
    [NominalAttributeCode6]          VARCHAR (10) NULL,
    [NominalAttributeDescription6]   VARCHAR (30) NULL,
    [NominalAttributeCode7]          VARCHAR (10) NULL,
    [NominalAttributeDescription7]   VARCHAR (30) NULL,
    [NominalAttributeCode8]          VARCHAR (10) NULL,
    [NominalAttributeDescription8]   VARCHAR (30) NULL,
    [NominalAttributeCode9]          VARCHAR (10) NULL,
    [NominalAttributeDescription9]   VARCHAR (30) NULL,
    [NominalAttributeCode10]         VARCHAR (10) NULL,
    [NominalAttributeDescription10]  VARCHAR (30) NULL,
    [NominalAttributeCode11]         VARCHAR (10) NULL,
    [NominalAttributeDescription11]  VARCHAR (30) NULL,
    [NominalAttributeCode12]         VARCHAR (10) NULL,
    [NominalAttributeDescription12]  VARCHAR (30) NULL,
    [NominalAttributeCode13]         VARCHAR (10) NULL,
    [NominalAttributeDescription13]  VARCHAR (30) NULL,
    [NominalAttributeCode14]         VARCHAR (10) NULL,
    [NominalAttributeDescription14]  VARCHAR (30) NULL,
    [NominalAttributeCode15]         VARCHAR (10) NULL,
    [NominalAttributeDescription15]  VARCHAR (30) NULL,
    [NominalAttributeCode16]         VARCHAR (10) NULL,
    [NominalAttributeDescription16]  VARCHAR (30) NULL,
    [NominalAttributeCode17]         VARCHAR (10) NULL,
    [NominalAttributeDescription17]  VARCHAR (30) NULL,
    [NominalAttributeCode18]         VARCHAR (10) NULL,
    [NominalAttributeDescription18]  VARCHAR (30) NULL,
    [NominalAttributeCode19]         VARCHAR (10) NULL,
    [NominalAttributeDescription19]  VARCHAR (30) NULL,
    [NominalAttributeCode20]         VARCHAR (10) NULL,
    [NominalAttributeDescription20]  VARCHAR (30) NULL,
    [NominalAttributeCode21]         VARCHAR (10) NULL,
    [NominalAttributeDescription21]  VARCHAR (30) NULL,
    [NominalAttributeCode22]         VARCHAR (10) NULL,
    [NominalAttributeDescription22]  VARCHAR (30) NULL,
    [NominalAttributeCode23]         VARCHAR (10) NULL,
    [NominalAttributeDescription23]  VARCHAR (30) NULL,
    [NominalAttributeCode24]         VARCHAR (10) NULL,
    [NominalAttributeDescription24]  VARCHAR (30) NULL,
    [NominalAttributeCode25]         VARCHAR (10) NULL,
    [NominalAttributeDescription25]  VARCHAR (30) NULL,
    [NominalAttributeCode26]         VARCHAR (10) NULL,
    [NominalAttributeDescription26]  VARCHAR (30) NULL,
    [NominalAttributeCode27]         VARCHAR (10) NULL,
    [NominalAttributeDescription27]  VARCHAR (30) NULL,
    [NominalAttributeCode28]         VARCHAR (10) NULL,
    [NominalAttributeDescription28]  VARCHAR (30) NULL,
    [NominalAttributeCode29]         VARCHAR (10) NULL,
    [NominalAttributeDescription29]  VARCHAR (30) NULL,
    [NominalAttributeCode30]         VARCHAR (10) NULL,
    [NominalAttributeDescription30]  VARCHAR (30) NULL,
    [NominalAttributeCode31]         VARCHAR (10) NULL,
    [NominalAttributeDescription31]  VARCHAR (30) NULL,
    [NominalAttributeCode32]         VARCHAR (10) NULL,
    [NominalAttributeDescription32]  VARCHAR (30) NULL,
    [NominalAttributeCode33]         VARCHAR (10) NULL,
    [NominalAttributeDescription33]  VARCHAR (30) NULL,
    [NominalAttributeCode34]         VARCHAR (10) NULL,
    [NominalAttributeDescription34]  VARCHAR (30) NULL,
    [NominalAttributeCode35]         VARCHAR (10) NULL,
    [NominalAttributeDescription35]  VARCHAR (30) NULL,
    [NominalAttributeCode36]         VARCHAR (10) NULL,
    [NominalAttributeDescription36]  VARCHAR (30) NULL,
    [NominalAttributeCode37]         VARCHAR (10) NULL,
    [NominalAttributeDescription37]  VARCHAR (30) NULL,
    [NominalAttributeCode38]         VARCHAR (10) NULL,
    [NominalAttributeDescription38]  VARCHAR (30) NULL,
    [NominalAttributeCode39]         VARCHAR (10) NULL,
    [NominalAttributeDescription39]  VARCHAR (30) NULL,
    [NominalAttributeCode40]         VARCHAR (10) NULL,
    [NominalAttributeDescription40]  VARCHAR (30) NULL,
    [NominalAttributeCode41]         VARCHAR (10) NULL,
    [NominalAttributeDescription41]  VARCHAR (30) NULL,
    [NominalAttributeCode42]         VARCHAR (10) NULL,
    [NominalAttributeDescription42]  VARCHAR (30) NULL,
    [NominalAttributeCode43]         VARCHAR (10) NULL,
    [NominalAttributeDescription43]  VARCHAR (30) NULL,
    [NominalAttributeCode44]         VARCHAR (10) NULL,
    [NominalAttributeDescription44]  VARCHAR (30) NULL,
    [NominalAttributeCode45]         VARCHAR (10) NULL,
    [NominalAttributeDescription45]  VARCHAR (30) NULL,
    [NominalAttributeCode46]         VARCHAR (10) NULL,
    [NominalAttributeDescription46]  VARCHAR (30) NULL,
    [NominalAttributeCode47]         VARCHAR (10) NULL,
    [NominalAttributeDescription47]  VARCHAR (30) NULL,
    [NominalAttributeCode48]         VARCHAR (10) NULL,
    [NominalAttributeDescription48]  VARCHAR (30) NULL,
    [NominalAttributeCode49]         VARCHAR (10) NULL,
    [NominalAttributeDescription49]  VARCHAR (30) NULL,
    [NominalAttributeCode50]         VARCHAR (10) NULL,
    [NominalAttributeDescription50]  VARCHAR (30) NULL,
    [NominalAttributeCode51]         VARCHAR (10) NULL,
    [NominalAttributeDescription51]  VARCHAR (30) NULL,
    [NominalAttributeCode52]         VARCHAR (10) NULL,
    [NominalAttributeDescription52]  VARCHAR (30) NULL,
    [NominalAttributeCode53]         VARCHAR (10) NULL,
    [NominalAttributeDescription53]  VARCHAR (30) NULL,
    [NominalAttributeCode54]         VARCHAR (10) NULL,
    [NominalAttributeDescription54]  VARCHAR (30) NULL,
    [NominalAttributeCode55]         VARCHAR (10) NULL,
    [NominalAttributeDescription55]  VARCHAR (30) NULL,
    [NominalAttributeCode56]         VARCHAR (10) NULL,
    [NominalAttributeDescription56]  VARCHAR (30) NULL,
    [NominalAttributeCode57]         VARCHAR (10) NULL,
    [NominalAttributeDescription57]  VARCHAR (30) NULL,
    [NominalAttributeCode58]         VARCHAR (10) NULL,
    [NominalAttributeDescription58]  VARCHAR (30) NULL,
    [NominalAttributeCode59]         VARCHAR (10) NULL,
    [NominalAttributeDescription59]  VARCHAR (30) NULL,
    [NominalAttributeCode60]         VARCHAR (10) NULL,
    [NominalAttributeDescription60]  VARCHAR (30) NULL,
    [NominalAttributeCode61]         VARCHAR (10) NULL,
    [NominalAttributeDescription61]  VARCHAR (30) NULL,
    [NominalAttributeCode62]         VARCHAR (10) NULL,
    [NominalAttributeDescription62]  VARCHAR (30) NULL,
    [NominalAttributeCode63]         VARCHAR (10) NULL,
    [NominalAttributeDescription63]  VARCHAR (30) NULL,
    [NominalAttributeCode64]         VARCHAR (10) NULL,
    [NominalAttributeDescription64]  VARCHAR (30) NULL,
    [NominalAttributeCode65]         VARCHAR (10) NULL,
    [NominalAttributeDescription65]  VARCHAR (30) NULL,
    [NominalAttributeCode66]         VARCHAR (10) NULL,
    [NominalAttributeDescription66]  VARCHAR (30) NULL,
    [NominalAttributeCode67]         VARCHAR (10) NULL,
    [NominalAttributeDescription67]  VARCHAR (30) NULL,
    [NominalAttributeCode68]         VARCHAR (10) NULL,
    [NominalAttributeDescription68]  VARCHAR (30) NULL,
    [NominalAttributeCode69]         VARCHAR (10) NULL,
    [NominalAttributeDescription69]  VARCHAR (30) NULL,
    [NominalAttributeCode70]         VARCHAR (10) NULL,
    [NominalAttributeDescription70]  VARCHAR (30) NULL,
    [NominalAttributeCode71]         VARCHAR (10) NULL,
    [NominalAttributeDescription71]  VARCHAR (30) NULL,
    [NominalAttributeCode72]         VARCHAR (10) NULL,
    [NominalAttributeDescription72]  VARCHAR (30) NULL,
    [NominalAttributeCode73]         VARCHAR (10) NULL,
    [NominalAttributeDescription73]  VARCHAR (30) NULL,
    [NominalAttributeCode74]         VARCHAR (10) NULL,
    [NominalAttributeDescription74]  VARCHAR (30) NULL,
    [NominalAttributeCode75]         VARCHAR (10) NULL,
    [NominalAttributeDescription75]  VARCHAR (30) NULL,
    [NominalAttributeCode76]         VARCHAR (10) NULL,
    [NominalAttributeDescription76]  VARCHAR (30) NULL,
    [NominalAttributeCode77]         VARCHAR (10) NULL,
    [NominalAttributeDescription77]  VARCHAR (30) NULL,
    [NominalAttributeCode78]         VARCHAR (10) NULL,
    [NominalAttributeDescription78]  VARCHAR (30) NULL,
    [NominalAttributeCode79]         VARCHAR (10) NULL,
    [NominalAttributeDescription79]  VARCHAR (30) NULL,
    [NominalAttributeCode80]         VARCHAR (10) NULL,
    [NominalAttributeDescription80]  VARCHAR (30) NULL,
    [NominalAttributeCode81]         VARCHAR (10) NULL,
    [NominalAttributeDescription81]  VARCHAR (30) NULL,
    [NominalAttributeCode82]         VARCHAR (10) NULL,
    [NominalAttributeDescription82]  VARCHAR (30) NULL,
    [NominalAttributeCode83]         VARCHAR (10) NULL,
    [NominalAttributeDescription83]  VARCHAR (30) NULL,
    [NominalAttributeCode84]         VARCHAR (10) NULL,
    [NominalAttributeDescription84]  VARCHAR (30) NULL,
    [NominalAttributeCode85]         VARCHAR (10) NULL,
    [NominalAttributeDescription85]  VARCHAR (30) NULL,
    [NominalAttributeCode86]         VARCHAR (10) NULL,
    [NominalAttributeDescription86]  VARCHAR (30) NULL,
    [NominalAttributeCode87]         VARCHAR (10) NULL,
    [NominalAttributeDescription87]  VARCHAR (30) NULL,
    [NominalAttributeCode88]         VARCHAR (10) NULL,
    [NominalAttributeDescription88]  VARCHAR (30) NULL,
    [NominalAttributeCode89]         VARCHAR (10) NULL,
    [NominalAttributeDescription89]  VARCHAR (30) NULL,
    [NominalAttributeCode90]         VARCHAR (10) NULL,
    [NominalAttributeDescription90]  VARCHAR (30) NULL,
    [NominalAttributeCode91]         VARCHAR (10) NULL,
    [NominalAttributeDescription91]  VARCHAR (30) NULL,
    [NominalAttributeCode92]         VARCHAR (10) NULL,
    [NominalAttributeDescription92]  VARCHAR (30) NULL,
    [NominalAttributeCode93]         VARCHAR (10) NULL,
    [NominalAttributeDescription93]  VARCHAR (30) NULL,
    [NominalAttributeCode94]         VARCHAR (10) NULL,
    [NominalAttributeDescription94]  VARCHAR (30) NULL,
    [NominalAttributeCode95]         VARCHAR (10) NULL,
    [NominalAttributeDescription95]  VARCHAR (30) NULL,
    [NominalAttributeCode96]         VARCHAR (10) NULL,
    [NominalAttributeDescription96]  VARCHAR (30) NULL,
    [NominalAttributeCode97]         VARCHAR (10) NULL,
    [NominalAttributeDescription97]  VARCHAR (30) NULL,
    [NominalAttributeCode98]         VARCHAR (10) NULL,
    [NominalAttributeDescription98]  VARCHAR (30) NULL,
    [NominalAttributeCode99]         VARCHAR (10) NULL,
    [NominalAttributeDescription99]  VARCHAR (30) NULL,
    [NominalAttributeCode100]        VARCHAR (10) NULL,
    [NominalAttributeDescription100] VARCHAR (30) NULL,
    [UnpostedN]                      FLOAT (53)   NULL,
    [UnpostedC]                      FLOAT (53)   NULL,
    [NominalBalance]                 FLOAT (53)   NULL,
    [NominalOpeningBalance]          FLOAT (53)   NULL,
    [NominalOpeningBalanceLastYear]  FLOAT (53)   NULL,
    [TurnoverL1]                     FLOAT (53)   NULL,
    [TurnoverL2]                     FLOAT (53)   NULL,
    [TurnoverL3]                     FLOAT (53)   NULL,
    [TurnoverL4]                     FLOAT (53)   NULL,
    [TurnoverL5]                     FLOAT (53)   NULL,
    [TurnoverL6]                     FLOAT (53)   NULL,
    [TurnoverL7]                     FLOAT (53)   NULL,
    [TurnoverL8]                     FLOAT (53)   NULL,
    [TurnoverL9]                     FLOAT (53)   NULL,
    [TurnoverL10]                    FLOAT (53)   NULL,
    [TurnoverL11]                    FLOAT (53)   NULL,
    [TurnoverL12]                    FLOAT (53)   NULL,
    [TurnoverL13]                    FLOAT (53)   NULL,
    [TurnoverC1]                     FLOAT (53)   NULL,
    [TurnoverC2]                     FLOAT (53)   NULL,
    [TurnoverC3]                     FLOAT (53)   NULL,
    [TurnoverC4]                     FLOAT (53)   NULL,
    [TurnoverC5]                     FLOAT (53)   NULL,
    [TurnoverC6]                     FLOAT (53)   NULL,
    [TurnoverC7]                     FLOAT (53)   NULL,
    [TurnoverC8]                     FLOAT (53)   NULL,
    [TurnoverC9]                     FLOAT (53)   NULL,
    [TurnoverC10]                    FLOAT (53)   NULL,
    [TurnoverC11]                    FLOAT (53)   NULL,
    [TurnoverC12]                    FLOAT (53)   NULL,
    [TurnoverC13]                    FLOAT (53)   NULL,
    [TurnoverN1]                     FLOAT (53)   NULL,
    [TurnoverN2]                     FLOAT (53)   NULL,
    [TurnoverN3]                     FLOAT (53)   NULL,
    [TurnoverN4]                     FLOAT (53)   NULL,
    [TurnoverN5]                     FLOAT (53)   NULL,
    [TurnoverN6]                     FLOAT (53)   NULL,
    [TurnoverN7]                     FLOAT (53)   NULL,
    [TurnoverN8]                     FLOAT (53)   NULL,
    [TurnoverN9]                     FLOAT (53)   NULL,
    [TurnoverN10]                    FLOAT (53)   NULL,
    [TurnoverN11]                    FLOAT (53)   NULL,
    [TurnoverN12]                    FLOAT (53)   NULL,
    [TurnoverN13]                    FLOAT (53)   NULL,
    [BudgetL1]                       FLOAT (53)   NULL,
    [BudgetL2]                       FLOAT (53)   NULL,
    [BudgetL3]                       FLOAT (53)   NULL,
    [BudgetL4]                       FLOAT (53)   NULL,
    [BudgetL5]                       FLOAT (53)   NULL,
    [BudgetL6]                       FLOAT (53)   NULL,
    [BudgetL7]                       FLOAT (53)   NULL,
    [BudgetL8]                       FLOAT (53)   NULL,
    [BudgetL9]                       FLOAT (53)   NULL,
    [BudgetL10]                      FLOAT (53)   NULL,
    [BudgetL11]                      FLOAT (53)   NULL,
    [BudgetL12]                      FLOAT (53)   NULL,
    [BudgetL13]                      FLOAT (53)   NULL,
    [BudgetC1]                       FLOAT (53)   NULL,
    [BudgetC2]                       FLOAT (53)   NULL,
    [BudgetC3]                       FLOAT (53)   NULL,
    [BudgetC4]                       FLOAT (53)   NULL,
    [BudgetC5]                       FLOAT (53)   NULL,
    [BudgetC6]                       FLOAT (53)   NULL,
    [BudgetC7]                       FLOAT (53)   NULL,
    [BudgetC8]                       FLOAT (53)   NULL,
    [BudgetC9]                       FLOAT (53)   NULL,
    [BudgetC10]                      FLOAT (53)   NULL,
    [BudgetC11]                      FLOAT (53)   NULL,
    [BudgetC12]                      FLOAT (53)   NULL,
    [BudgetC13]                      FLOAT (53)   NULL,
    [BudgetN1]                       FLOAT (53)   NULL,
    [BudgetN2]                       FLOAT (53)   NULL,
    [BudgetN3]                       FLOAT (53)   NULL,
    [BudgetN4]                       FLOAT (53)   NULL,
    [BudgetN5]                       FLOAT (53)   NULL,
    [BudgetN6]                       FLOAT (53)   NULL,
    [BudgetN7]                       FLOAT (53)   NULL,
    [BudgetN8]                       FLOAT (53)   NULL,
    [BudgetN9]                       FLOAT (53)   NULL,
    [BudgetN10]                      FLOAT (53)   NULL,
    [BudgetN11]                      FLOAT (53)   NULL,
    [BudgetN12]                      FLOAT (53)   NULL,
    [BudgetN13]                      FLOAT (53)   NULL,
    [ForecastC1]                     FLOAT (53)   NULL,
    [ForecastC2]                     FLOAT (53)   NULL,
    [ForecastC3]                     FLOAT (53)   NULL,
    [ForecastC4]                     FLOAT (53)   NULL,
    [ForecastC5]                     FLOAT (53)   NULL,
    [ForecastC6]                     FLOAT (53)   NULL,
    [ForecastC7]                     FLOAT (53)   NULL,
    [ForecastC8]                     FLOAT (53)   NULL,
    [ForecastC9]                     FLOAT (53)   NULL,
    [ForecastC10]                    FLOAT (53)   NULL,
    [ForecastC11]                    FLOAT (53)   NULL,
    [ForecastC12]                    FLOAT (53)   NULL,
    [ForecastC13]                    FLOAT (53)   NULL,
    [ForecastN1]                     FLOAT (53)   NULL,
    [ForecastN2]                     FLOAT (53)   NULL,
    [ForecastN3]                     FLOAT (53)   NULL,
    [ForecastN4]                     FLOAT (53)   NULL,
    [ForecastN5]                     FLOAT (53)   NULL,
    [ForecastN6]                     FLOAT (53)   NULL,
    [ForecastN7]                     FLOAT (53)   NULL,
    [ForecastN8]                     FLOAT (53)   NULL,
    [ForecastN9]                     FLOAT (53)   NULL,
    [ForecastN10]                    FLOAT (53)   NULL,
    [ForecastN11]                    FLOAT (53)   NULL,
    [ForecastN12]                    FLOAT (53)   NULL,
    [ForecastN13]                    FLOAT (53)   NULL,
    [NFORCST_Y1]                     FLOAT (53)   NULL,
    [NFORCST_Y2]                     FLOAT (53)   NULL,
    [NFORCST_Y3]                     FLOAT (53)   NULL,
    [NFORCST_Y4]                     FLOAT (53)   NULL,
    [NFORCST_Y5]                     FLOAT (53)   NULL,
    [ZeroBalanceC1]                  TINYINT      NULL,
    [ZeroBalanceC2]                  TINYINT      NULL,
    [ZeroBalanceC3]                  TINYINT      NULL,
    [ZeroBalanceC4]                  TINYINT      NULL,
    [ZeroBalanceC5]                  TINYINT      NULL,
    [ZeroBalanceC6]                  TINYINT      NULL,
    [ZeroBalanceC7]                  TINYINT      NULL,
    [ZeroBalanceC8]                  TINYINT      NULL,
    [ZeroBalanceC9]                  TINYINT      NULL,
    [ZeroBalanceC10]                 TINYINT      NULL,
    [ZeroBalanceC11]                 TINYINT      NULL,
    [ZeroBalanceC12]                 TINYINT      NULL,
    [ZeroBalanceC13]                 TINYINT      NULL,
    [ZeroBalanceN1]                  TINYINT      NULL,
    [ZeroBalanceN2]                  TINYINT      NULL,
    [ZeroBalanceN3]                  TINYINT      NULL,
    [ZeroBalanceN4]                  TINYINT      NULL,
    [ZeroBalanceN5]                  TINYINT      NULL,
    [ZeroBalanceN6]                  TINYINT      NULL,
    [ZeroBalanceN7]                  TINYINT      NULL,
    [ZeroBalanceN8]                  TINYINT      NULL,
    [ZeroBalanceN9]                  TINYINT      NULL,
    [ZeroBalanceN10]                 TINYINT      NULL,
    [ZeroBalanceN11]                 TINYINT      NULL,
    [ZeroBalanceN12]                 TINYINT      NULL,
    [ZeroBalanceN13]                 TINYINT      NULL,
    [ZeroBalanceL1]                  TINYINT      NULL,
    [ZeroBalanceL2]                  TINYINT      NULL,
    [ZeroBalanceL3]                  TINYINT      NULL,
    [ZeroBalanceL4]                  TINYINT      NULL,
    [ZeroBalanceL5]                  TINYINT      NULL,
    [ZeroBalanceL6]                  TINYINT      NULL,
    [ZeroBalanceL7]                  TINYINT      NULL,
    [ZeroBalanceL8]                  TINYINT      NULL,
    [ZeroBalanceL9]                  TINYINT      NULL,
    [ZeroBalanceL10]                 TINYINT      NULL,
    [ZeroBalanceL11]                 TINYINT      NULL,
    [ZeroBalanceL12]                 TINYINT      NULL,
    [ZeroBalanceL13]                 TINYINT      NULL
);

