CREATE TABLE [dbo].[AA_AOI_INXL2_BUDGET_REVISIONS_CALC_VALUES] (
    [AAICRCV_PRIMARY]                                              INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AAICRCV_ACCOUNT_CODE]                                         VARCHAR (25)  NOT NULL,
    [AAICRCV_SECONDARY_CODE]                                       VARCHAR (25)  NULL,
    [AAICRCV_RECORD_TYPE]                                          VARCHAR (2)   NOT NULL,
    [AAICRCV_BUDGET_TYPE]                                          VARCHAR (1)   NOT NULL,
    [AAICRCV_NL_BUDGET_YEAR]                                       INT           NULL,
    [AAICRCV_NL_BUDGET_YEAR_SYS_YEAR_NOMINAL_PRIMARY]              SMALLINT      NULL,
    [AAICRCV_REVISION_NUMBER]                                      SMALLINT      NULL,
    [AAICRCV_LOCKED]                                               TINYINT       NULL,
    [AAICRCV_LOCKED_PASSWORD]                                      VARCHAR (100) NULL,
    [AAICRCV_ACTIVE]                                               TINYINT       NULL,
    [AAICRCV_PROJECTCC_START_DATE]                                 DATE          NULL,
    [AAICRCV_PROJECTCC_BUDGET_START_YEAR]                          INT           NULL,
    [AAICRCV_PROJECTCC_BUDGET_START_YEAR_SYS_YEAR_COSTING_PRIMARY] SMALLINT      NULL,
    [AAICRCV_PROJECTCC_BUDGET_START_PERIOD]                        INT           NULL,
    [AAICRCV_PROJECTCC_NBR_OF_PERIODS]                             INT           NULL,
    [AAICRCV_Total_Qty]                                            FLOAT (53)    NULL,
    [AAICRCV_Total_Value]                                          FLOAT (53)    NULL,
    [AAICRCV_Profile]                                              VARCHAR (50)  NULL,
    [AAICRCV_VolumeBudget_Used]                                    TINYINT       NULL,
    [AAICRCV_Fixed_Price]                                          FLOAT (53)    NULL,
    [AAICRCV_Variable_Price]                                       FLOAT (53)    NULL,
    [AAICRCV_Discount_Percent]                                     FLOAT (53)    NULL,
    [AAICRCV_UserNumber0]                                          FLOAT (53)    NULL,
    [AAICRCV_UserNumber1]                                          FLOAT (53)    NULL,
    [AAICRCV_UserNumber2]                                          FLOAT (53)    NULL,
    [AAICRCV_UserNumber3]                                          FLOAT (53)    NULL,
    [AAICRCV_UserNumber4]                                          FLOAT (53)    NULL,
    [AAICRCV_UserNumber5]                                          FLOAT (53)    NULL,
    [AAICRCV_UserNumber6]                                          FLOAT (53)    NULL,
    [AAICRCV_UserNumber7]                                          FLOAT (53)    NULL,
    [AAICRCV_UserNumber8]                                          FLOAT (53)    NULL,
    [AAICRCV_UserNumber9]                                          FLOAT (53)    NULL,
    CONSTRAINT [AAICRCV_PRIMARY_PK] PRIMARY KEY CLUSTERED ([AAICRCV_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [AAICRCV_UNIQUE] UNIQUE NONCLUSTERED ([AAICRCV_ACCOUNT_CODE] ASC, [AAICRCV_SECONDARY_CODE] ASC, [AAICRCV_RECORD_TYPE] ASC, [AAICRCV_BUDGET_TYPE] ASC, [AAICRCV_NL_BUDGET_YEAR] ASC, [AAICRCV_REVISION_NUMBER] ASC) WITH (FILLFACTOR = 70)
);

