CREATE TABLE [dbo].[AA_AOI_INXL2_NOMINAL_BUDGET] (
    [GUID]             VARCHAR (36) NOT NULL,
    [ROW_NBR_IN_GUID]  INT          NULL,
    [Dataset]          VARCHAR (6)  NOT NULL,
    [NCODE]            VARCHAR (25) NULL,
    [Locked]           TINYINT      NULL,
    [Default]          SMALLINT     NULL,
    [NNAME]            VARCHAR (40) NULL,
    [NMAJORHEADCODE]   TINYINT      NULL,
    [NL_MAJORNAME]     VARCHAR (40) NULL,
    [NCATEGORYCODE1]   VARCHAR (10) NULL,
    [NL_CATEGORYNAME1] VARCHAR (50) NULL,
    [NCATEGORYCODE2]   VARCHAR (10) NULL,
    [NL_CATEGORYNAME2] VARCHAR (50) NULL,
    [NCATEGORYCODE3]   VARCHAR (10) NULL,
    [NL_CATEGORYNAME3] VARCHAR (50) NULL,
    [NCATEGORYCODE4]   VARCHAR (10) NULL,
    [NL_CATEGORYNAME4] VARCHAR (50) NULL,
    [NCATEGORYCODE5]   VARCHAR (10) NULL,
    [NL_CATEGORYNAME5] VARCHAR (50) NULL,
    [NCATEGORYCODE6]   VARCHAR (10) NULL,
    [NL_CATEGORYNAME6] VARCHAR (50) NULL,
    [NCATEGORYCODE7]   VARCHAR (10) NULL,
    [NL_CATEGORYNAME7] VARCHAR (50) NULL,
    [NCATEGORYCODE8]   VARCHAR (10) NULL,
    [NL_CATEGORYNAME8] VARCHAR (50) NULL,
    [Total]            FLOAT (53)   NULL,
    [Profile]          VARCHAR (50) NULL,
    [B1]               FLOAT (53)   NULL,
    [B2]               FLOAT (53)   NULL,
    [B3]               FLOAT (53)   NULL,
    [B4]               FLOAT (53)   NULL,
    [B5]               FLOAT (53)   NULL,
    [B6]               FLOAT (53)   NULL,
    [B7]               FLOAT (53)   NULL,
    [B8]               FLOAT (53)   NULL,
    [B9]               FLOAT (53)   NULL,
    [B10]              FLOAT (53)   NULL,
    [B11]              FLOAT (53)   NULL,
    [B12]              FLOAT (53)   NULL,
    [B13]              FLOAT (53)   NULL,
    [I1]               FLOAT (53)   NULL,
    [I2]               FLOAT (53)   NULL,
    [I3]               FLOAT (53)   NULL,
    [I4]               FLOAT (53)   NULL,
    [I5]               FLOAT (53)   NULL,
    [I6]               FLOAT (53)   NULL,
    [I7]               FLOAT (53)   NULL,
    [I8]               FLOAT (53)   NULL,
    [I9]               FLOAT (53)   NULL,
    [I10]              FLOAT (53)   NULL,
    [I11]              FLOAT (53)   NULL,
    [I12]              FLOAT (53)   NULL,
    [I13]              FLOAT (53)   NULL
);

