CREATE TABLE [dbo].[ACP_EXCH_RATE_SETTINGS] (
    [AERS_PRIMARY]         INT     IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AERS_NEW_CHANGE_RATE] TINYINT NULL,
    CONSTRAINT [AERS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([AERS_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

