CREATE TABLE [dbo].[ACP_SETTINGS_URLS] (
    [ACP_URL_PRIMARY]            INT            NOT NULL,
    [ACP_URL_ACLOUD_URL]         VARCHAR (2000) NULL,
    [ACP_URL_EXCHANGE_RATES_URL] VARCHAR (2000) NULL,
    [ACP_URL_PLATFORM_URL]       VARCHAR (2000) NULL,
    [ACP_URL_POSTCODE_URL]       VARCHAR (2000) NULL,
    CONSTRAINT [ACP_URL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ACP_URL_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

