CREATE TABLE [dbo].[ACP_APP_SETTINGS] (
    [ACP_APP_PRIMARY]             INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ACP_APP_CODE]                VARCHAR (20)   NULL,
    [ACP_APP_ID]                  VARCHAR (100)  NULL,
    [ACP_APP_SUB_ID]              VARCHAR (100)  NULL,
    [ACP_APP_NAME]                VARCHAR (100)  NULL,
    [ACP_APP_DESCRIPTION]         VARCHAR (1000) NULL,
    [ACP_APP_PLATFORM_DATASET_ID] VARCHAR (100)  NULL,
    [ACP_APP_API_KEY]             VARCHAR (8000) NULL,
    CONSTRAINT [ACP_APP_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ACP_APP_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

