CREATE TABLE [dbo].[ACP_EXPENSES_HEADER_SYNC] (
    [ACP_EHS_PRIMARY]              INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ACP_EHS_HEADER_ID]            VARCHAR (100)  NULL,
    [ACP_EHS_USER_ID]              VARCHAR (100)  NULL,
    [ACP_EHS_EXPENSE_DATE]         DATETIME       NULL,
    [ACP_EHS_TYPE]                 VARCHAR (1)    NULL,
    [ACP_EHS_REFERENCE]            VARCHAR (50)   NULL,
    [ACP_EHS_DESCRIPTION]          VARCHAR (MAX)  NULL,
    [ACP_EHS_SUPPLIER_CODE]        VARCHAR (10)   NULL,
    [ACP_EHS_USERNAME]             VARCHAR (200)  NULL,
    [ACP_EHS_USER_EMAIL]           VARCHAR (64)   NULL,
    [ACP_EHS_USER_ISO_CODE]        VARCHAR (3)    NULL,
    [ACP_EHS_EXPENSE_CLAIM_NUMBER] INT            NULL,
    [ACP_EHS_PROCESS_STATUS]       TINYINT        NULL,
    [ACP_EHS_SCHEME_ID]            VARCHAR (100)  NULL,
    [ACP_EHS_SCHEME_NAME]          VARCHAR (500)  NULL,
    [ACP_EHS_CREDIT_CARD_NUMBER]   VARCHAR (50)   NULL,
    [ACP_EHS_IMPORT_DATE]          DATETIME       NULL,
    [ACP_EHS_IMPORT_DESC]          VARCHAR (1000) NULL,
    [ACP_EHS_IMPORT_ID]            VARCHAR (100)  NULL,
    [ACP_EHS_STATEMENT_DATE]       DATETIME       NULL,
    [ACP_EHS_TRAN_NUMBER]          INT            NULL,
    [ACP_EHS_SUB_LEDGER]           VARCHAR (10)   NULL,
    [ACP_EHS_BATCH_REF]            VARCHAR (10)   NULL,
    CONSTRAINT [ACP_EHS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ACP_EHS_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [ACP_EHS_HEADER_ID]
    ON [dbo].[ACP_EXPENSES_HEADER_SYNC]([ACP_EHS_HEADER_ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [ACP_EHS_USER_ID]
    ON [dbo].[ACP_EXPENSES_HEADER_SYNC]([ACP_EHS_USER_ID] ASC) WITH (FILLFACTOR = 70);

