CREATE TABLE [dbo].[ACP_TRAN_COMMENT_SYNC] (
    [ACP_TCS_PRIMARY]            INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ACP_TCS_DATETIME_CREATED]   DATETIME       NULL,
    [ACP_TCS_USER_ID]            VARCHAR (100)  NULL,
    [ACP_TCS_TRAN_PRIMARY]       FLOAT (53)     NULL,
    [ACP_TCS_TRAN_ID]            VARCHAR (100)  NULL,
    [ACP_TCS_COMMENT]            VARCHAR (8000) NULL,
    [ACP_TCS_STATEMENT_ID]       VARCHAR (100)  NULL,
    [ACP_TCS_ORGANISATION_ID]    VARCHAR (100)  NULL,
    [ACP_TCS_PROCESS_STATUS]     TINYINT        NULL,
    [ACP_TCS_NOTE_PRIMARY]       INT            NULL,
    [ACP_TCS_DIRECTION]          TINYINT        NULL,
    [ACP_TCS_TASK_ID]            VARCHAR (100)  NULL,
    [ACP_TCS_USER_FIRST_NAME]    VARCHAR (100)  NULL,
    [ACP_TCS_USER_LAST_NAME]     VARCHAR (100)  NULL,
    [ACP_TCS_USER_EMAIL_ADDRESS] VARCHAR (64)   NULL,
    [ACP_TCS_DIMS_USER_ID]       VARCHAR (4)    NULL,
    CONSTRAINT [ACP_TCS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ACP_TCS_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [ACP_TCS_PROCESS_STATUS]
    ON [dbo].[ACP_TRAN_COMMENT_SYNC]([ACP_TCS_PROCESS_STATUS] ASC)
    INCLUDE([ACP_TCS_TRAN_PRIMARY]) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [ACP_TCS_TRAN_PRIMARY]
    ON [dbo].[ACP_TRAN_COMMENT_SYNC]([ACP_TCS_TRAN_PRIMARY] ASC)
    INCLUDE([ACP_TCS_NOTE_PRIMARY]) WITH (FILLFACTOR = 70);

