CREATE TABLE [dbo].[ACP_EXPENSES_DETAIL_SYNC] (
    [ACP_EDS_PRIMARY]            INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ACP_EDS_DETAIL_ID]          VARCHAR (100) NULL,
    [ACP_EDS_HEADER_ID]          VARCHAR (100) NULL,
    [ACP_EDS_USER_ID]            VARCHAR (100) NULL,
    [ACP_EDS_DESCRIPTION]        VARCHAR (MAX) NULL,
    [ACP_EDS_CLAIM_DATE]         DATETIME      NULL,
    [ACP_EDS_ANALYSIS]           VARCHAR (25)  NULL,
    [ACP_EDS_COSTHEADER]         VARCHAR (25)  NULL,
    [ACP_EDS_COSTCENTRE]         VARCHAR (25)  NULL,
    [ACP_EDS_HOME_ISO_CODE]      VARCHAR (3)   NULL,
    [ACP_EDS_CURRENCY_ISO_CODE]  VARCHAR (3)   NULL,
    [ACP_EDS_HOME_NET]           FLOAT (53)    NULL,
    [ACP_EDS_HOME_VAT]           FLOAT (53)    NULL,
    [ACP_EDS_HOME_GROSS]         FLOAT (53)    NULL,
    [ACP_EDS_VAT_RATE]           FLOAT (53)    NULL,
    [ACP_EDS_CURRENCY_NET]       FLOAT (53)    NULL,
    [ACP_EDS_CURRENCY_TAX]       FLOAT (53)    NULL,
    [ACP_EDS_CURRENCY_GROSS]     FLOAT (53)    NULL,
    [ACP_EDS_CURRENCY_TAX_RATE]  FLOAT (53)    NULL,
    [ACP_EDS_EXCHANGE_RATE]      FLOAT (53)    NULL,
    [ACP_EDS_VAT_CODE]           VARCHAR (4)   NULL,
    [ACP_EDS_CLAIM_NUMBER]       INT           NULL,
    [ACP_EDS_DATE_TIME_APPROVED] DATETIME      NULL,
    [ACP_EDS_PROCESS_STATUS]     TINYINT       NULL,
    CONSTRAINT [ACP_EDS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ACP_EDS_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [ACP_EDS_HEADER_ID]
    ON [dbo].[ACP_EXPENSES_DETAIL_SYNC]([ACP_EDS_HEADER_ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [ACP_EDS_USER_ID]
    ON [dbo].[ACP_EXPENSES_DETAIL_SYNC]([ACP_EDS_USER_ID] ASC) WITH (FILLFACTOR = 70);

