CREATE TABLE [dbo].[ACP_EXCH_RATE_LOG] (
    [AERL_PRIMARY]      INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AERL_DATE_UPDATED] DATETIME     NULL,
    [AERL_USERID]       VARCHAR (10) NULL,
    [AERL_CURR_SYMBOL]  VARCHAR (4)  NULL,
    CONSTRAINT [AERL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([AERL_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

