CREATE TABLE [dbo].[ACP_SYNC_OBJECTS] (
    [ACP_SYNC_OBJ_PRIMARY]     INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ACP_SYNC_OBJ_ID]          VARCHAR (100)  NULL,
    [ACP_SYNC_OBJ_APP_ID_LINK] VARCHAR (100)  NULL,
    [ACP_SYNC_OBJ_NAME]        VARCHAR (100)  NULL,
    [ACP_SYNC_OBJ_DIRECTION]   TINYINT        NULL,
    [ACP_SYNC_OBJ_TOKEN]       VARCHAR (1000) NULL,
    [ACP_SYNC_OBJ_ORDER]       INT            NULL,
    [ACP_SYNC_OBJ_ACLOUD_NAME] VARCHAR (100)  NULL,
    CONSTRAINT [ACP_SYNC_OBJ_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ACP_SYNC_OBJ_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

