CREATE TABLE [dbo].[ACP_ORGANISATIONS] (
    [ACP_ORG_PRIMARY]       INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ACP_ORG_ID]            VARCHAR (100) NULL,
    [ACP_ORG_CUST_CODE]     VARCHAR (20)  NULL,
    [ACP_ORG_STATUS]        INT           NULL,
    [ACP_ORG_INVITED]       BIT           NULL,
    [ACP_ORG_EMAIL_ADDRESS] VARCHAR (64)  NULL,
    CONSTRAINT [ACP_ORG_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ACP_ORG_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

