CREATE TABLE [dbo].[ACR_SEARCH_CRITERIA] (
    [ACR_SRCH_CRT_PRIMARY]          INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ACR_SRCH_CRT_SEARCH_LINK]      INT           DEFAULT ((0)) NULL,
    [ACR_SRCH_CRT_SQL_FIELD_NAME]   VARCHAR (64)  NULL,
    [ACR_SRCH_CRT_DATA1]            VARCHAR (255) NULL,
    [ACR_SRCH_CRT_DATA2]            VARCHAR (255) NULL,
    [ACR_SRCH_CRT_DATA_BOOL]        TINYINT       DEFAULT ((0)) NULL,
    [ACR_SRCH_CRT_OPTION]           TINYINT       DEFAULT ((0)) NULL,
    [ACR_SRCH_CRT_OMNIS_FIELD_NAME] VARCHAR (64)  NULL,
    [ACR_SRCH_CRT_DESCRIPTION]      VARCHAR (128) NULL,
    [ACR_SRCH_CRT_DATA_TYPE]        VARCHAR (8)   NULL,
    CONSTRAINT [ACR_SRCH_CRT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ACR_SRCH_CRT_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACR_SRCH_CRT_SEARCH_LINK]
    ON [dbo].[ACR_SEARCH_CRITERIA]([ACR_SRCH_CRT_SEARCH_LINK] ASC);

