CREATE TABLE [dbo].[ACR_SORT] (
    [ACR_SORT_PRIMARY]      INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ACR_SORT_NAME]         VARCHAR (64)  NULL,
    [ACR_SORT_REPORT_NAME]  VARCHAR (255) NULL,
    [ACR_SORT_MODULE]       VARCHAR (3)   NULL,
    [ACR_SORT_DATE_CREATED] DATETIME      NULL,
    [ACR_SORT_DATE_EDITED]  DATETIME      NULL,
    [ACR_SORT_USER_CREATED] VARCHAR (4)   NULL,
    [ACR_SORT_USER_EDITED]  VARCHAR (4)   NULL,
    [ACR_SORT_PRIVATE]      TINYINT       DEFAULT ((0)) NULL,
    [ACR_SORT_PROTECTED]    TINYINT       DEFAULT ((0)) NULL,
    [ACR_SORT_DEFAULT]      TINYINT       DEFAULT ((0)) NULL,
    CONSTRAINT [ACR_SORT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ACR_SORT_PRIMARY] ASC)
);

