CREATE TABLE [dbo].[ACR_SEARCH] (
    [ACR_SRCH_PRIMARY]      INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ACR_SRCH_SORT_LINK]    INT           DEFAULT ((0)) NULL,
    [ACR_SRCH_NAME]         VARCHAR (64)  NULL,
    [ACR_SRCH_REPORT_NAME]  VARCHAR (255) NULL,
    [ACR_SRCH_MODULE]       VARCHAR (3)   NULL,
    [ACR_SRCH_DATE_CREATED] DATETIME      NULL,
    [ACR_SRCH_DATE_EDITED]  DATETIME      NULL,
    [ACR_SRCH_USER_CREATED] VARCHAR (4)   NULL,
    [ACR_SRCH_USER_EDITED]  VARCHAR (4)   NULL,
    [ACR_SRCH_PRIVATE]      TINYINT       DEFAULT ((0)) NULL,
    [ACR_SRCH_PROTECTED]    TINYINT       DEFAULT ((0)) NULL,
    [ACR_SRCH_DEFAULT]      TINYINT       DEFAULT ((0)) NULL,
    CONSTRAINT [ACR_SRCH_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ACR_SRCH_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACR_SRCH_MODULE]
    ON [dbo].[ACR_SEARCH]([ACR_SRCH_MODULE] ASC, [ACR_SRCH_DEFAULT] ASC);


GO
CREATE NONCLUSTERED INDEX [ACR_SRCH_NAME]
    ON [dbo].[ACR_SEARCH]([ACR_SRCH_NAME] ASC);

