CREATE TABLE [dbo].[ARM_CM_AUDIT_TRAIL] (
    [CM_AUD_PRIMARY]    FLOAT (53)     NOT NULL,
    [CM_AUD_TABLE]      VARCHAR (50)   NULL,
    [CM_AUD_FIELD]      VARCHAR (50)   NULL,
    [CM_AUD_LINK_ID]    FLOAT (53)     NULL,
    [CM_AUD_LINK_FIELD] VARCHAR (50)   NULL,
    [CM_AUD_ACTION]     TINYINT        NULL,
    [CM_AUD_USER_ID]    VARCHAR (4)    NULL,
    [CM_AUD_DATE_TIME]  DATETIME       NULL,
    [CM_AUD_OLD_VALUE]  VARCHAR (1000) NULL,
    [CM_AUD_NEW_VALUE]  VARCHAR (1000) NULL,
    [CM_AUD_REASON]     VARCHAR (1000) NULL,
    CONSTRAINT [CM_AUD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CM_AUD_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

