CREATE TABLE [dbo].[ARM_CM_CST_DETAIL] (
    [CT_NETT]                         FLOAT (53)      NULL,
    [CT_VAT]                          FLOAT (53)      NULL,
    [CT_VATCODE]                      VARCHAR (4)     NULL,
    [CT_GROSS]                        FLOAT (53)      NULL,
    [CT_QUANTITY]                     FLOAT (53)      NULL,
    [CT_PRICE]                        FLOAT (53)      NULL,
    [CT_CENTRE_UPLV]                  FLOAT (53)      NULL,
    [CT_CENTRE_UPLP]                  FLOAT (53)      NULL,
    [CT_CC_UPLTYPE]                   TINYINT         NULL,
    [CT_BATCH_POSTED]                 TINYINT         NULL,
    [CT_BATCH_FLAG]                   TINYINT         NULL,
    [CT_INVOICE_FLAG]                 TINYINT         NULL,
    [CT_BATCH_REF]                    VARCHAR (10)    NULL,
    [CT_ARCHIVE_FLG]                  TINYINT         NULL,
    [CT_UPDATE_USER1]                 TINYINT         NULL,
    [CT_UPDATE_USER2]                 TINYINT         NULL,
    [CT_TRANTYPE]                     VARCHAR (3)     NULL,
    [CT_STATUS]                       VARCHAR (1)     NULL,
    [CT_HEADER_REF]                   VARCHAR (25)    NULL,
    [CT_POSTTYPE]                     VARCHAR (1)     NULL,
    [CT_PUTIN_LEDGER]                 VARCHAR (3)     NULL,
    [CT_SORTTYPE]                     VARCHAR (6)     NULL,
    [CT_DATE]                         DATETIME        NULL,
    [CT_DETAIL]                       VARCHAR (240)   NULL,
    [CT_DESCRIPTION]                  VARCHAR (20)    NULL,
    [CT_BANK_CONTRA]                  TINYINT         NULL,
    [CT_CURR_CODE]                    VARCHAR (4)     NULL,
    [CT_CURR_RATE]                    FLOAT (53)      NULL,
    [CT_CURR_VALUE]                   FLOAT (53)      NULL,
    [CT_CURR_RTEFLG]                  TINYINT         NULL,
    [CT_CURR_PRICE]                   FLOAT (53)      NULL,
    [CT_CURR_CNTUPLV]                 FLOAT (53)      NULL,
    [CT_RES_UPLV]                     FLOAT (53)      NULL,
    [CT_CURR_RESUPLV]                 FLOAT (53)      NULL,
    [CT_RES_UPLP]                     FLOAT (53)      NULL,
    [CT_RESLINE]                      INT             NULL,
    [CT_PERIODNUMBR]                  TINYINT         NULL,
    [CT_YEAR]                         VARCHAR (1)     NULL,
    [CT_WEEK_NO]                      TINYINT         NULL,
    [CT_USER_PUTIN]                   VARCHAR (4)     NULL,
    [CT_DATE_PUTIN]                   DATETIME        NULL,
    [CT_MU_STATUS]                    VARCHAR (1)     NULL,
    [CT_EMPCODE]                      VARCHAR (10)    NULL,
    [CT_PAYTYPE_CODE]                 VARCHAR (20)    NULL,
    [CT_PAYROLL_FLAG]                 TINYINT         NULL,
    [CT_STOCKCODE]                    VARCHAR (25)    NULL,
    [CT_RESOURCE]                     VARCHAR (16)    NULL,
    [CT_NOMINAL]                      VARCHAR (25)    NULL,
    [CT_ACCOUNT]                      VARCHAR (10)    NULL,
    [CT_ANALYSIS]                     VARCHAR (25)    NULL,
    [CT_COSTHEADER]                   VARCHAR (10)    NULL,
    [CT_COSTCENTRE]                   VARCHAR (10)    NULL,
    [CT_TRANSACTION_LINK]             FLOAT (53)      NULL,
    [CT_PRIMARY]                      FLOAT (53)      NOT NULL,
    [CT_SOURCE]                       VARCHAR (1)     NULL,
    [CT_TRAN_OPTIONS]                 VARCHAR (30)    NULL,
    [CT_HEADER_LINK]                  VARCHAR (20)    NULL,
    [CT_YEAR_LINK]                    SMALLINT        NULL,
    [CT_INVOICE_ANALYSIS_LINK]        INT             NULL,
    [CT_TIMETABLE_ANALYSIS_LINK]      INT             NULL,
    [CT_COST_ANALYSIS_LINK]           INT             NULL,
    [CT_TRANSACTION_SUBTYPE_LINK]     INT             NULL,
    [CT_RESOURCE_MARGIN_PC]           FLOAT (53)      NULL,
    [CT_RESOURCE_MARGIN_VALUE]        FLOAT (53)      NULL,
    [CT_CC_MARGIN_PC]                 FLOAT (53)      NULL,
    [CT_CC_MARGIN_VALUE]              FLOAT (53)      NULL,
    [CT_USER_KEY1]                    VARCHAR (20)    NULL,
    [CT_USER_KEY2]                    VARCHAR (20)    NULL,
    [CT_USER_KEY3]                    VARCHAR (20)    NULL,
    [CT_ALLOCATED]                    BIT             NOT NULL,
    [CT_UNRECOV_VALUE]                FLOAT (53)      NULL,
    [CT_EXTRA_WORK_VALUE]             FLOAT (53)      NULL,
    [CT_VALUE_INVOICED]               FLOAT (53)      NULL,
    [CT_TIME_UNITS]                   FLOAT (53)      NULL,
    [CT_TIME_UNIT_TYPE]               VARCHAR (1)     NULL,
    [CT_ORDER_DETAIL_LINK]            INT             NULL,
    [CT_UNRECOV_QUANTITY]             FLOAT (53)      NOT NULL,
    [CT_EXTRA_WORK_QUANTITY]          FLOAT (53)      NOT NULL,
    [CT_QUANTITY_INVOICED]            FLOAT (53)      NOT NULL,
    [CT_UNRECOV_VALUE_C]              FLOAT (53)      NOT NULL,
    [CT_EXTRA_WORK_VALUE_C]           FLOAT (53)      NOT NULL,
    [CT_CURR_CC_MARGIN_VALUE]         FLOAT (53)      NULL,
    [CT_CURR_RESOURCE_MARGIN_VALUE]   FLOAT (53)      NULL,
    [CT_FLAT_RATE]                    BIT             NULL,
    [CT_SALES_PRICE]                  FLOAT (53)      NULL,
    [CT_CURR_SALES_PRICE]             FLOAT (53)      NULL,
    [CT_TIME_UNIT_QUANTITY]           FLOAT (53)      NULL,
    [CT_CC_MARGIN_TYPE]               TINYINT         NULL,
    [CT_CURR_CC_UPLIFT_UNIT_VAL]      FLOAT (53)      NOT NULL,
    [CT_INVOICEABLE_VALUE_CALC_OPT]   BIT             NOT NULL,
    [CT_CURR_CC_MARGIN_UNIT_VAL]      FLOAT (53)      NOT NULL,
    [CT_WFF_APPROVAL_STATUS]          SMALLINT        NULL,
    [CT_UPLIFTED_UNIT_COST]           DECIMAL (28, 2) NULL,
    [CT_UPLIFTED_UNIT_COST_C]         DECIMAL (28, 2) NULL,
    [CT_UPLIFTED_COST]                DECIMAL (28, 2) NULL,
    [CT_UPLIFTED_COST_C]              DECIMAL (28, 2) NULL,
    [CT_ORIGINAL_INVOICEABLE_VALUE]   DECIMAL (30, 2) NULL,
    [CT_ORIGINAL_INVOICEABLE_VALUE_C] DECIMAL (30, 2) NULL
);

