CREATE TABLE [dbo].[ARM_CM_SYSTEM] (
    [ARM_UPDATE_SME]        TINYINT      NULL,
    [ARM_SME_DATABASE]      VARCHAR (50) NULL,
    [ARM_PROMPT_FOR_REASON] TINYINT      NULL,
    [ARM_REASON_MANDATORY]  TINYINT      NULL
);

