CREATE TABLE [dbo].[ARM_CM_CHANGE_LOG_SETTINGS] (
    [ARM_CL_TABLE_NAME]   VARCHAR (100) NULL,
    [ARM_CL_TRIGGER_NAME] VARCHAR (100) NULL,
    [ARM_CL_INSERT]       TINYINT       NULL,
    [ARM_CL_UPDATE]       TINYINT       NULL,
    [ARM_CL_DELETE]       TINYINT       NULL,
    [ARM_CL_COLUMN_NAME]  VARCHAR (100) NULL,
    [ARM_CL_PRIMARY_KEY]  TINYINT       NULL,
    [ARM_CL_TRIGGER]      TINYINT       NULL,
    [ARM_CL_SHOW]         TINYINT       NULL,
    [ARM_CL_ORDER]        INT           NULL
);

