CREATE TABLE [dbo].[ARM_CM_CHANGE_LOG] (
    [CHL_PRIMARY]      FLOAT (53)     NULL,
    [CHL_EVENT_ID]     FLOAT (53)     NULL,
    [CHL_TYPE]         VARCHAR (40)   NULL,
    [CHL_FIELD_NAME]   VARCHAR (255)  NULL,
    [CHL_VALUE]        VARCHAR (8000) NULL,
    [CHL_DATETIME]     DATETIME       NULL,
    [CHL_ACTION]       VARCHAR (40)   NULL,
    [CHL_USERID]       VARCHAR (128)  NULL,
    [CHL_TABLE_NAME]   VARCHAR (255)  NULL,
    [CHL_TRIGGER_NAME] VARCHAR (255)  NULL
);

