CREATE TABLE [dbo].[ARM_CM_SL_TRANSACTIONS] (
    [ST_TRANTYPE]             VARCHAR (3)  NULL,
    [ST_HEADER_REF]           VARCHAR (10) NULL,
    [ST_DESCRIPTION]          VARCHAR (30) NULL,
    [ST_DATE]                 DATETIME     NULL,
    [ST_DUEDATE]              DATETIME     NULL,
    [ST_ANTICPAYDATE]         DATETIME     NULL,
    [ST_SETT_DISC_1]          FLOAT (53)   NULL,
    [ST_SETT_DISC_2]          FLOAT (53)   NULL,
    [ST_SETT_DAYS_1]          FLOAT (53)   NULL,
    [ST_SETT_DAYS_2]          FLOAT (53)   NULL,
    [ST_NETT]                 FLOAT (53)   NULL,
    [ST_VAT]                  FLOAT (53)   NULL,
    [ST_GROSS]                FLOAT (53)   NULL,
    [ST_UNALLOCATED]          FLOAT (53)   NULL,
    [ST_BATCH_FLAG]           TINYINT      NULL,
    [ST_BATCH_REF]            VARCHAR (10) NULL,
    [ST_ARCHIVE_FLAG]         TINYINT      NULL,
    [ST_ALOC_POINTER]         VARCHAR (11) NULL,
    [ST_ORIGIN]               VARCHAR (2)  NULL,
    [ST_REVALUE_RATE]         FLOAT (53)   NULL,
    [ST_CURRENCYRATE]         FLOAT (53)   NULL,
    [ST_CURRENCYCODE]         VARCHAR (4)  NULL,
    [ST_CURR_VALU]            FLOAT (53)   NULL,
    [ST_CURR_UNAL]            FLOAT (53)   NULL,
    [ST_CURRENCYRTCH]         TINYINT      NULL,
    [ST_CURRENCYEXDF]         FLOAT (53)   NULL,
    [ST_EXPORT_CODE]          VARCHAR (1)  NULL,
    [ST_EC_DEL_TERMS]         VARCHAR (3)  NULL,
    [ST_EC_T_NATURE]          VARCHAR (2)  NULL,
    [ST_EC_T_MODE]            VARCHAR (1)  NULL,
    [ST_REVALUED]             FLOAT (53)   NULL,
    [ST_REVALUE_DATE]         DATETIME     NULL,
    [ST_QUERY_FLAG]           TINYINT      NULL,
    [ST_DONOTCHASE]           TINYINT      NULL,
    [ST_CHASE1]               TINYINT      NULL,
    [ST_CHASE2]               TINYINT      NULL,
    [ST_CHASE3]               TINYINT      NULL,
    [ST_PERIODNUMBER]         TINYINT      NULL,
    [ST_YEAR]                 VARCHAR (1)  NULL,
    [ST_ALLOC_USER1]          VARCHAR (4)  NULL,
    [ST_ALLOC_USER2]          VARCHAR (4)  NULL,
    [ST_ALLOC_USER3]          VARCHAR (4)  NULL,
    [ST_ALLOC_DATE1]          DATETIME     NULL,
    [ST_ALLOC_DATE2]          DATETIME     NULL,
    [ST_ALLOC_DATE3]          DATETIME     NULL,
    [ST_ALLOC_VALU1]          FLOAT (53)   NULL,
    [ST_ALLOC_VALU2]          FLOAT (53)   NULL,
    [ST_ALLOC_VALU3]          FLOAT (53)   NULL,
    [ST_ALLOC_REF1]           VARCHAR (10) NULL,
    [ST_ALLOC_REF2]           VARCHAR (10) NULL,
    [ST_ALLOC_REF3]           VARCHAR (10) NULL,
    [ST_ALLOC_PERIOD]         TINYINT      NULL,
    [ST_ALLOC_YEAR]           VARCHAR (1)  NULL,
    [ST_T_DISCVAL]            FLOAT (53)   NULL,
    [ST_T_DISCVAL_C]          FLOAT (53)   NULL,
    [ST_L_DISCVAL]            FLOAT (53)   NULL,
    [ST_L_DISCVAL_C]          FLOAT (53)   NULL,
    [ST_COST_VALUE]           FLOAT (53)   NULL,
    [ST_USER_PUTIN]           VARCHAR (4)  NULL,
    [ST_DATE_PUTIN]           DATETIME     NULL,
    [ST_MU_STATUS]            VARCHAR (1)  NULL,
    [ST_USER1]                VARCHAR (20) NULL,
    [ST_USER2]                VARCHAR (20) NULL,
    [ST_USER3]                VARCHAR (20) NULL,
    [ST_BATCH_POSTED]         VARCHAR (1)  NULL,
    [ST_PRINTED_FLAG]         TINYINT      NULL,
    [ST_CON_REFTYPE]          VARCHAR (11) NULL,
    [ST_ORDER_NUMBER]         FLOAT (53)   NULL,
    [ST_COPYCUST]             VARCHAR (10) NULL,
    [ST_REBUILDNUM]           FLOAT (53)   NULL,
    [ST_PRIMARY]              FLOAT (53)   NOT NULL,
    [ST_HEADER_KEY]           VARCHAR (20) NULL,
    [ST_SUB_LEDGER]           VARCHAR (10) NULL,
    [ST_ALLOC_CBREF]          VARCHAR (10) NULL,
    [ST_CENTRALISED]          TINYINT      NULL,
    [ST_RECONCILED]           TINYINT      NULL,
    [ST_ALLOC_XREF]           VARCHAR (15) NULL,
    [ST_NETT_BASE2]           FLOAT (53)   NULL,
    [ST_VAT_BASE2]            FLOAT (53)   NULL,
    [ST_GROSS_BASE2]          FLOAT (53)   NULL,
    [ST_L_DISC_BASE2]         FLOAT (53)   NULL,
    [ST_T_DISC_BASE2]         FLOAT (53)   NULL,
    [ST_BASE2_RATE]           FLOAT (53)   NULL,
    [ST_TRI_RATE1]            FLOAT (53)   NULL,
    [ST_BASE2_RATECHNG]       TINYINT      NULL,
    [ST_TRI_RATECHNG1]        TINYINT      NULL,
    [ST_RND_DIFF_BASE1]       FLOAT (53)   NULL,
    [ST_COSTVALUE_BASE2]      FLOAT (53)   NULL,
    [ST_CURR_NETT]            FLOAT (53)   NULL,
    [ST_CURR_TAX]             FLOAT (53)   NULL,
    [ST_CURR_TYPE]            VARCHAR (1)  NULL,
    [ST_TRI_RATE2]            FLOAT (53)   NULL,
    [ST_TRI_RATECHNG2]        TINYINT      NULL,
    [ST_RND_DIFF_POSTED]      TINYINT      NULL,
    [ST_SPCL_TRANTYPE]        VARCHAR (20) NULL,
    [ST_SRV_STATUS]           TINYINT      NULL,
    [ST_RND_DIFF_BASE2]       FLOAT (53)   NULL,
    [ST_SOURCE]               VARCHAR (1)  NULL,
    [ST_TRAN_OPTIONS]         VARCHAR (30) NULL,
    [ST_REVERSE_VAT]          FLOAT (53)   NULL,
    [ST_REVERSE_VAT_BASE2]    FLOAT (53)   NULL,
    [ST_CREDIT_CONTROLLER]    VARCHAR (4)  NULL,
    [ST_DEBT_STATUS_LINK]     INT          NULL,
    [ST_WRITE_OFF_STATUS]     TINYINT      NULL,
    [ST_NOM_CAT_LINK]         INT          NULL,
    [ST_YEAR_LINK]            SMALLINT     NULL,
    [ST_ALLOC_YEAR_LINK]      SMALLINT     NULL,
    [ST_WFF_APPROVAL_STATUS]  SMALLINT     NULL,
    [ST_DD_COLLECTION_STATUS] VARCHAR (1)  NULL,
    [ST_QUERIED_IN_ACLOUD]    BIT          NOT NULL
);

