CREATE TABLE [dbo].[ARM_CM_NL_TRANSACTIONS2] (
    [NT_PRIMARY_2] FLOAT (53)    NOT NULL,
    [NT_CHAR1]     VARCHAR (20)  NULL,
    [NT_CHAR2]     VARCHAR (20)  NULL,
    [NT_CHAR3]     VARCHAR (100) NULL,
    [NT_CHAR4]     VARCHAR (100) NULL,
    [NT_FLAG1]     TINYINT       NULL,
    [NT_FLAG2]     TINYINT       NULL,
    [NT_DATE1]     DATETIME      NULL,
    [NT_DATE2]     DATETIME      NULL,
    [NT_NUM1]      FLOAT (53)    NULL,
    [NT_NUM2]      FLOAT (53)    NULL,
    [NT_USRCHAR1]  VARCHAR (20)  NULL,
    [NT_USRCHAR2]  VARCHAR (20)  NULL,
    [NT_USRCHAR3]  VARCHAR (100) NULL,
    [NT_USRCHAR4]  VARCHAR (100) NULL,
    [NT_USRFLAG1]  TINYINT       NULL,
    [NT_USRFLAG2]  TINYINT       NULL,
    [NT_USRDATE1]  DATETIME      NULL,
    [NT_USRDATE2]  DATETIME      NULL,
    [NT_USRNUM1]   FLOAT (53)    NULL,
    [NT_USRNUM2]   FLOAT (53)    NULL
);

