CREATE TABLE [dbo].[ARM_CM_SL_PL_NL_DETAIL] (
    [DET_NETT]               FLOAT (53)    NULL,
    [DET_VAT]                FLOAT (53)    NULL,
    [DET_VATCODE]            VARCHAR (4)   NULL,
    [DET_GROSS]              FLOAT (53)    NULL,
    [DET_UNALLOCATED]        FLOAT (53)    NULL,
    [DET_BATCH_FLAG]         TINYINT       NULL,
    [DET_RECUR_FLAG]         TINYINT       NULL,
    [DET_BATCH_REF]          VARCHAR (10)  NULL,
    [DET_ARCHIVE_FLG]        TINYINT       NULL,
    [DET_ORIGIN]             VARCHAR (3)   NULL,
    [DET_LEDGER]             VARCHAR (2)   NULL,
    [DET_TYPE]               VARCHAR (3)   NULL,
    [DET_DESCRIPTION]        VARCHAR (240) NULL,
    [DET_HEADER_REF]         VARCHAR (26)  NULL,
    [DET_JNL_LINEREF]        VARCHAR (10)  NULL,
    [DET_PL_INTERNAL]        FLOAT (53)    NULL,
    [DET_DATE]               DATETIME      NULL,
    [DET_TAX_SORT]           VARCHAR (4)   NULL,
    [DET_CURR_TAX]           FLOAT (53)    NULL,
    [DET_TAX_WITHHLD]        FLOAT (53)    NULL,
    [DET_PL_ACQ_TAX]         FLOAT (53)    NULL,
    [DET_CURR_CODE]          VARCHAR (4)   NULL,
    [DET_CURR_RATE]          FLOAT (53)    NULL,
    [DET_CURR_NETT]          FLOAT (53)    NULL,
    [DET_CURR_RTEFLG]        TINYINT       NULL,
    [DET_CURR_UNALOC]        FLOAT (53)    NULL,
    [DET_CURR_L_DISC]        FLOAT (53)    NULL,
    [DET_CURR_T_DISC]        FLOAT (53)    NULL,
    [DET_IMPEXP_CODE]        VARCHAR (1)   NULL,
    [DET_COUNTRY_CDE]        VARCHAR (4)   NULL,
    [DET_ECVAT_TYPE]         VARCHAR (1)   NULL,
    [DET_L_DISCOUNT]         FLOAT (53)    NULL,
    [DET_T_DISCOUNT]         FLOAT (53)    NULL,
    [DET_COSTPRICE]          FLOAT (53)    NULL,
    [DET_PERIOD_SORT]        INT           NULL,
    [DET_PERIODNUMBR]        TINYINT       NULL,
    [DET_YEAR]               VARCHAR (1)   NULL,
    [DET_RECONCILED]         TINYINT       NULL,
    [DET_NOM_PERIOD]         TINYINT       NULL,
    [DET_NOM_YEAR]           VARCHAR (1)   NULL,
    [DET_NOM_PERSORT]        INT           NULL,
    [DET_RECON_REF]          VARCHAR (10)  NULL,
    [DT_RECON_ORDER]         FLOAT (53)    NULL,
    [DET_UNIT_PRICE]         FLOAT (53)    NULL,
    [DET_QUANTITY]           FLOAT (53)    NULL,
    [DET_UNT_PRICE_C]        FLOAT (53)    NULL,
    [DET_UNIT_QTY]           FLOAT (53)    NULL,
    [DET_USER_PUTIN]         VARCHAR (4)   NULL,
    [DET_DATE_PUTIN]         DATETIME      NULL,
    [DET_HEADER_KEY]         VARCHAR (20)  NULL,
    [DET_BATCH_POSTD]        TINYINT       NULL,
    [DET_SERIALNO]           VARCHAR (40)  NULL,
    [DET_STKSORTKEY1]        VARCHAR (20)  NULL,
    [DET_PRICE_CODE]         VARCHAR (16)  NULL,
    [DET_NOMINALDR]          VARCHAR (25)  NULL,
    [DET_NOMINALCR]          VARCHAR (25)  NULL,
    [DET_NOMINALVAT]         VARCHAR (25)  NULL,
    [DET_STOCK_CODE]         VARCHAR (25)  NULL,
    [DET_ACCOUNT]            VARCHAR (10)  NULL,
    [DET_ANALYSIS]           VARCHAR (25)  NULL,
    [DET_COSTHEADER]         VARCHAR (10)  NULL,
    [DET_COSTCENTRE]         VARCHAR (10)  NULL,
    [DET_ANALTYPE]           VARCHAR (1)   NULL,
    [DET_PRIMARY]            FLOAT (53)    NOT NULL,
    [DET_EC_T_NATURE]        VARCHAR (2)   NULL,
    [DET_SUB_AUDIT_NO]       FLOAT (53)    NULL,
    [DET_SUB_LEDGER]         VARCHAR (10)  NULL,
    [DET_VAT_RULES]          TINYINT       NULL,
    [DET_VATNONDEDUCT]       FLOAT (53)    NULL,
    [DET_STKSORTKEY2]        VARCHAR (20)  NULL,
    [DET_STKSORTKEY3]        VARCHAR (20)  NULL,
    [DET_STKSORTKEY]         VARCHAR (20)  NULL,
    [DET_LANDED_COST]        VARCHAR (1)   NULL,
    [DET_DIMENSION1]         VARCHAR (20)  NULL,
    [DET_DIMENSION2]         VARCHAR (20)  NULL,
    [DET_DIMENSION3]         VARCHAR (20)  NULL,
    [DET_CHEQUE_PAYEE]       VARCHAR (40)  NULL,
    [DET_NETT_BASE2]         FLOAT (53)    NULL,
    [DET_VAT_BASE2]          FLOAT (53)    NULL,
    [DET_GROSS_BASE2]        FLOAT (53)    NULL,
    [DET_L_DISC_BASE2]       FLOAT (53)    NULL,
    [DET_T_DISC_BASE2]       FLOAT (53)    NULL,
    [DET_BASE2_RATE]         FLOAT (53)    NULL,
    [DET_TRI_RATE1]          FLOAT (53)    NULL,
    [DET_BASE2_RATECHNG]     TINYINT       NULL,
    [DET_TRI_RATECHNG1]      TINYINT       NULL,
    [DET_COSTPRICE_BASE2]    FLOAT (53)    NULL,
    [DET_UNIT_PRICE_BASE2]   FLOAT (53)    NULL,
    [DET_TAX_WITHHLD_BASE2]  FLOAT (53)    NULL,
    [DET_PL_ACQUISTN_BASE2]  FLOAT (53)    NULL,
    [DET_CURR_GROSS]         FLOAT (53)    NULL,
    [DET_TRI_RATE2]          FLOAT (53)    NULL,
    [DET_TRI_RATECHNG2]      TINYINT       NULL,
    [DET_NLCONTRA]           VARCHAR (25)  NULL,
    [DET_HEADER_REF2]        VARCHAR (10)  NULL,
    [DET_SLPL_PRIMARY]       VARCHAR (20)  NULL,
    [DET_SRV_STATUS]         TINYINT       NULL,
    [DET_ORDER_LINK]         INT           NULL,
    [DET_SOURCE]             VARCHAR (1)   NULL,
    [DET_VAT_RETURN_PRIMARY] INT           NULL,
    [DET_DELIVERY_ADDRESS]   VARCHAR (16)  NULL,
    [DET_POSTING_NO]         SMALLINT      NULL,
    [DET_REVERSE_STATUS]     TINYINT       NULL,
    [DET_MOVEMENT_LINK]      INT           NULL,
    [DET_NOM_YEAR_LINK]      SMALLINT      NULL,
    [DET_VAT_RATE]           FLOAT (53)    NULL
);

