CREATE TABLE [dbo].[ARM_CM_PL_TRANSACTIONS] (
    [PT_TRANTYPE]                  VARCHAR (3)  NULL,
    [PT_HEADER_REF]                VARCHAR (25) NULL,
    [PT_INTERNAL_REF]              FLOAT (53)   NULL,
    [PT_DESCRIPTION]               VARCHAR (30) NULL,
    [PT_DATE]                      DATETIME     NULL,
    [PT_DUEDATE]                   DATETIME     NULL,
    [PT_ANTICPAYDATE]              DATETIME     NULL,
    [PT_SETT_DISC1]                FLOAT (53)   NULL,
    [PT_SETT_DISC2]                FLOAT (53)   NULL,
    [PT_SETT_DAYS1]                FLOAT (53)   NULL,
    [PT_SETT_DAYS2]                FLOAT (53)   NULL,
    [PT_NETT]                      FLOAT (53)   NULL,
    [PT_VAT]                       FLOAT (53)   NULL,
    [PT_GROSS]                     FLOAT (53)   NULL,
    [PT_UNALLOCATED]               FLOAT (53)   NULL,
    [PT_BATCH_FLAG]                TINYINT      NULL,
    [PT_BATCH_REF]                 VARCHAR (10) NULL,
    [PT_ARCHIVE_FLAG]              TINYINT      NULL,
    [PT_ALOC_POINTER]              VARCHAR (11) NULL,
    [PT_ORIGIN]                    VARCHAR (2)  NULL,
    [PT_REVALUE_RATE]              FLOAT (53)   NULL,
    [PT_CURRENCYRATE]              FLOAT (53)   NULL,
    [PT_CURRENCYCODE]              VARCHAR (4)  NULL,
    [PT_CURR_VALU]                 FLOAT (53)   NULL,
    [PT_CURR_UNAL]                 FLOAT (53)   NULL,
    [PT_CURRENCYRTCH]              TINYINT      NULL,
    [PT_CURRENCYEXDF]              FLOAT (53)   NULL,
    [PT_ACQUISTN_TAX]              FLOAT (53)   NULL,
    [PT_IMPORT_CODE]               VARCHAR (1)  NULL,
    [PT_REVALUED]                  FLOAT (53)   NULL,
    [PT_EC_DEL_TERMS]              VARCHAR (3)  NULL,
    [PT_EC_T_NATURE]               VARCHAR (2)  NULL,
    [PT_EC_T_MODE]                 VARCHAR (1)  NULL,
    [PT_REVALUE_DATE]              DATETIME     NULL,
    [PT_PAYMENT_FLAG]              VARCHAR (1)  NULL,
    [PT_QUERY_FLAG]                TINYINT      NULL,
    [PT_DONOTCHASE]                TINYINT      NULL,
    [PT_CHASE1]                    TINYINT      NULL,
    [PT_CHASE2]                    TINYINT      NULL,
    [PT_CHASE3]                    TINYINT      NULL,
    [PT_PERIODNUMBER]              TINYINT      NULL,
    [PT_YEAR]                      VARCHAR (1)  NULL,
    [PT_ALLOC_USER1]               VARCHAR (4)  NULL,
    [PT_ALLOC_USER2]               VARCHAR (4)  NULL,
    [PT_ALLOC_USER3]               VARCHAR (4)  NULL,
    [PT_ALLOC_DATE1]               DATETIME     NULL,
    [PT_ALLOC_DATE2]               DATETIME     NULL,
    [PT_ALLOC_DATE3]               DATETIME     NULL,
    [PT_ALLOC_VALU1]               FLOAT (53)   NULL,
    [PT_ALLOC_VALU2]               FLOAT (53)   NULL,
    [PT_ALLOC_VALU3]               FLOAT (53)   NULL,
    [PT_ALLOC_REF1]                VARCHAR (10) NULL,
    [PT_ALLOC_REF2]                VARCHAR (10) NULL,
    [PT_ALLOC_REF3]                VARCHAR (10) NULL,
    [PT_ALLOC_PERIOD]              TINYINT      NULL,
    [PT_ALLOC_YEAR]                VARCHAR (1)  NULL,
    [PT_T_DISCVAL]                 FLOAT (53)   NULL,
    [PT_T_DISCVAL_C]               FLOAT (53)   NULL,
    [PT_L_DISCVAL]                 FLOAT (53)   NULL,
    [PT_L_DISCVAL_C]               FLOAT (53)   NULL,
    [PT_USER_PUTIN]                VARCHAR (4)  NULL,
    [PT_DATE_PUTIN]                DATETIME     NULL,
    [PT_MU_STATUS]                 VARCHAR (1)  NULL,
    [PT_USER1]                     VARCHAR (20) NULL,
    [PT_USER2]                     VARCHAR (20) NULL,
    [PT_USER3]                     VARCHAR (20) NULL,
    [PT_BATCH_POSTED]              VARCHAR (1)  NULL,
    [PT_CON_REFTYPE]               VARCHAR (26) NULL,
    [PT_ORDER_NUMBER]              VARCHAR (10) NULL,
    [PT_COPYSUPP]                  VARCHAR (10) NULL,
    [PT_REBUILDNUM]                FLOAT (53)   NULL,
    [PT_PRIMARY]                   FLOAT (53)   NOT NULL,
    [PT_HEADER_KEY]                VARCHAR (20) NULL,
    [PT_SUB_LEDGER]                VARCHAR (10) NULL,
    [PT_ALLOC_CBREF]               VARCHAR (10) NULL,
    [PT_CENTRALISED]               TINYINT      NULL,
    [PT_PAYLIST_VALUE]             FLOAT (53)   NULL,
    [PT_PAYLIST_SETT_DISC]         FLOAT (53)   NULL,
    [PT_PAYLIST_REF]               VARCHAR (10) NULL,
    [PT_INVREG_FLAG]               TINYINT      NULL,
    [PT_INVREG_STATUS]             VARCHAR (1)  NULL,
    [PT_INVREG_TYPE]               VARCHAR (1)  NULL,
    [PT_INVREG_OVERIDE]            VARCHAR (4)  NULL,
    [PT_INVREG_APPROVER1]          VARCHAR (4)  NULL,
    [PT_INVREG_APPROVER2]          VARCHAR (4)  NULL,
    [PT_INVREG_APPROVER3]          VARCHAR (4)  NULL,
    [PT_INVREG_APPROVEKEY1]        VARCHAR (1)  NULL,
    [PT_INVREG_APPROVEKEY2]        VARCHAR (1)  NULL,
    [PT_INVREG_APPROVEKEY3]        VARCHAR (1)  NULL,
    [PT_INVREG_APPROVEDATE1]       DATETIME     NULL,
    [PT_INVREG_APPROVEDATE2]       DATETIME     NULL,
    [PT_INVREG_APPROVEDATE3]       DATETIME     NULL,
    [PT_INVREG_MATCHEDUSER]        VARCHAR (4)  NULL,
    [PT_INVREG_MATCHEDDATE]        DATETIME     NULL,
    [PT_INVREG_MATCHEDKEY]         VARCHAR (1)  NULL,
    [PT_INVREG_APPROVESTATUS]      VARCHAR (3)  NULL,
    [PT_PAY_STAGE1_USER]           VARCHAR (4)  NULL,
    [PT_PAY_STAGE2_USER]           VARCHAR (4)  NULL,
    [PT_PAY_STAGE_STATUS]          TINYINT      NULL,
    [PT_RECONCILED]                TINYINT      NULL,
    [PT_ALLOC_XREF]                VARCHAR (15) NULL,
    [PT_NETT_BASE2]                FLOAT (53)   NULL,
    [PT_VAT_BASE2]                 FLOAT (53)   NULL,
    [PT_GROSS_BASE2]               FLOAT (53)   NULL,
    [PT_L_DISC_BASE2]              FLOAT (53)   NULL,
    [PT_T_DISC_BASE2]              FLOAT (53)   NULL,
    [PT_BASE2_RATE]                FLOAT (53)   NULL,
    [PT_TRI_RATE1]                 FLOAT (53)   NULL,
    [PT_BASE2_RATECHNG]            TINYINT      NULL,
    [PT_TRI_RATECHNG1]             TINYINT      NULL,
    [PT_ACQUISTN_BASE2]            FLOAT (53)   NULL,
    [PT_RND_DIFF_BASE1]            FLOAT (53)   NULL,
    [PT_CURR_NETT]                 FLOAT (53)   NULL,
    [PT_CURR_TAX]                  FLOAT (53)   NULL,
    [PT_CURR_TYPE]                 VARCHAR (1)  NULL,
    [PT_TRI_RATE2]                 FLOAT (53)   NULL,
    [PT_TRI_RATECHNG2]             TINYINT      NULL,
    [PT_RND_DIFF_POSTED]           TINYINT      NULL,
    [PT_SPCL_TRANTYPE]             VARCHAR (20) NULL,
    [PT_HEADER_REF2]               VARCHAR (10) NULL,
    [PT_SRV_STATUS]                TINYINT      NULL,
    [PT_RND_DIFF_BASE2]            FLOAT (53)   NULL,
    [PT_SOURCE]                    VARCHAR (1)  NULL,
    [PT_TRAN_OPTIONS]              VARCHAR (30) NULL,
    [PT_SURVEYOR]                  VARCHAR (30) NULL,
    [PT_CIS_SENT_TO]               VARCHAR (30) NULL,
    [PT_CIS_SENT_DATE]             DATETIME     NULL,
    [PT_CIS_AUTHORISED]            TINYINT      NULL,
    [PT_CIS_AUTHORISED_DATE]       DATETIME     NULL,
    [PT_CIS_PAYEE_NAME]            VARCHAR (40) NULL,
    [PT_CIS300_FLAG]               TINYINT      NULL,
    [PT_PARTNER]                   VARCHAR (10) NULL,
    [PT_DATE_RECEIVED]             DATETIME     NULL,
    [PT_INVREG_TRAN_OPTIONS]       VARCHAR (6)  NULL,
    [PT_YEAR_LINK]                 SMALLINT     NULL,
    [PT_ALLOC_YEAR_LINK]           SMALLINT     NULL,
    [PT_NOM_CAT_LINK]              INT          NULL,
    [PT_BACS_LAYOUT]               TINYINT      NULL,
    [PT_REVERSE_SERVICE_VAT]       FLOAT (53)   NOT NULL,
    [PT_REVERSE_SERVICE_VAT_BASE2] FLOAT (53)   NOT NULL,
    [PT_WFF_APPROVAL_STATUS]       SMALLINT     NULL,
    [PT_CURR_ACQUISTN]             FLOAT (53)   NOT NULL
);

