CREATE TABLE [dbo].[ARM_CM_PL_TRANSACTIONS2] (
    [PT_PRIMARY_2] FLOAT (53)    NOT NULL,
    [PT_CHAR1]     VARCHAR (20)  NULL,
    [PT_CHAR2]     VARCHAR (20)  NULL,
    [PT_CHAR3]     VARCHAR (100) NULL,
    [PT_CHAR4]     VARCHAR (100) NULL,
    [PT_FLAG1]     TINYINT       NULL,
    [PT_FLAG2]     TINYINT       NULL,
    [PT_DATE1]     DATETIME      NULL,
    [PT_DATE2]     DATETIME      NULL,
    [PT_NUM1]      FLOAT (53)    NULL,
    [PT_NUM2]      FLOAT (53)    NULL,
    [PT_USRCHAR1]  VARCHAR (20)  NULL,
    [PT_USRCHAR2]  VARCHAR (20)  NULL,
    [PT_USRCHAR3]  VARCHAR (100) NULL,
    [PT_USRCHAR4]  VARCHAR (100) NULL,
    [PT_USRFLAG1]  TINYINT       NULL,
    [PT_USRFLAG2]  TINYINT       NULL,
    [PT_USRDATE1]  DATETIME      NULL,
    [PT_USRDATE2]  DATETIME      NULL,
    [PT_USRNUM1]   FLOAT (53)    NULL,
    [PT_USRNUM2]   FLOAT (53)    NULL
);

