CREATE TABLE [dbo].[ARM_CM_SL_ALLOC_HISTORY] (
    [S_AL_PRIMARY]        INT          NOT NULL,
    [S_AL_DATE]           DATETIME     NULL,
    [S_AL_PERIOD]         TINYINT      CONSTRAINT [DF_ARM_CM_SL_ALLOC_HISTORY_S_AL_PERIOD] DEFAULT ((0)) NULL,
    [S_AL_YEAR]           VARCHAR (1)  NULL,
    [S_AL_VALUE_HOME]     FLOAT (53)   CONSTRAINT [DF_ARM_CM_SL_ALLOC_HISTORY_S_AL_VALUE_HOME] DEFAULT ((0)) NULL,
    [S_AL_VALUE_CURR]     FLOAT (53)   CONSTRAINT [DF_ARM_CM_SL_ALLOC_HISTORY_S_AL_VALUE_CURR] DEFAULT ((0)) NULL,
    [S_AL_REFERENCE]      VARCHAR (10) NULL,
    [S_AL_HEADER_KEY]     VARCHAR (20) NULL,
    [S_AL_USER_ID]        VARCHAR (4)  NULL,
    [S_AL_ACCOUNT_CODE]   VARCHAR (10) NULL,
    [S_AL_FULLALLOC_PD]   SMALLINT     CONSTRAINT [DF_ARM_CM_SL_ALLOC_HISTORY_S_AL_FULLALLOC_PD] DEFAULT ((0)) NULL,
    [S_AL_FULLALLOC_DATE] INT          CONSTRAINT [DF_ARM_CM_SL_ALLOC_HISTORY_S_AL_FULLALLOC_DATE] DEFAULT ((0)) NULL,
    [S_AL_YEAR_LINK]      SMALLINT     NULL
);

