CREATE TABLE [dbo].[ARM_CM_NL_TRANSACTIONS] (
    [NT_TRANTYPE]            VARCHAR (3)   NULL,
    [NT_HEADER_REF]          VARCHAR (25)  NULL,
    [NT_DESCRIPTION]         VARCHAR (200) NULL,
    [NT_DATE]                DATETIME      NULL,
    [NT_POST_VALUE]          FLOAT (53)    NULL,
    [NT_LINE_COUNT]          INT           NULL,
    [NT_BATCH_FLAG]          TINYINT       NULL,
    [NT_QUERY_FLAG]          TINYINT       NULL,
    [NT_BATCH_REF]           VARCHAR (10)  NULL,
    [NT_ARCHIVE_FLAG]        TINYINT       NULL,
    [NT_CONTRA_FLAG]         TINYINT       NULL,
    [NT_GROSS_CONTRA]        VARCHAR (25)  NULL,
    [NT_MULTI_CONTRA]        TINYINT       NULL,
    [NT_VAT_CONTRA]          VARCHAR (25)  NULL,
    [NT_CURRENCYRATE]        FLOAT (53)    NULL,
    [NT_CURRENCYSYMB]        VARCHAR (4)   NULL,
    [NT_CURR_VALUE]          FLOAT (53)    NULL,
    [NT_CURRENCYCODE]        VARCHAR (6)   NULL,
    [NT_CURRENCYRTCH]        TINYINT       NULL,
    [NT_IMPEXP_CODE]         VARCHAR (1)   NULL,
    [NT_COUNTRY_CODE]        VARCHAR (4)   NULL,
    [NT_EC_DEL_TERM]         VARCHAR (3)   NULL,
    [NT_EC_T_NATURE]         VARCHAR (2)   NULL,
    [NT_EC_T_MODE]           VARCHAR (1)   NULL,
    [NT_PERIODNUMBER]        TINYINT       NULL,
    [NT_YEAR]                VARCHAR (1)   NULL,
    [NT_RECUR_FLAG]          TINYINT       NULL,
    [NT_REVERSE_FLAG]        TINYINT       NULL,
    [NT_MAX_POSTINGS]        FLOAT (53)    NULL,
    [NT_POSTINGS_CNT]        FLOAT (53)    NULL,
    [NT_POSTINGS_PER]        TINYINT       NULL,
    [NT_POSTINGS_FRQ]        VARCHAR (3)   NULL,
    [NT_POSTED_DATE]         DATETIME      NULL,
    [NT_FIRST_DATE]          DATETIME      NULL,
    [NT_NEXT_DATE]           DATETIME      NULL,
    [NT_USER_PUTIN]          VARCHAR (4)   NULL,
    [NT_DATE_PUTIN]          DATETIME      NULL,
    [NT_MU_STATUS]           VARCHAR (1)   NULL,
    [NT_CON_REFTYPE]         VARCHAR (26)  NULL,
    [NT_REBUILDNUM]          FLOAT (53)    NULL,
    [NT_PRIMARY]             FLOAT (53)    NOT NULL,
    [NT_HEADER_KEY]          VARCHAR (20)  NULL,
    [NT_SUB_LEDGER]          VARCHAR (10)  NULL,
    [NT_CHEQUE_PAYEE]        VARCHAR (40)  NULL,
    [NT_PAYMENT_FLAG]        TINYINT       NULL,
    [NT_BASE2_VALUE]         FLOAT (53)    NULL,
    [NT_BASE2_RATE]          FLOAT (53)    NULL,
    [NT_TRI_RATE1]           FLOAT (53)    NULL,
    [NT_BASE2_RATECHNG]      TINYINT       NULL,
    [NT_TRI_RATECHNG1]       TINYINT       NULL,
    [NT_RND_DIFF_BASE1]      FLOAT (53)    NULL,
    [NT_CURR_TYPE]           VARCHAR (1)   NULL,
    [NT_TRI_RATE2]           FLOAT (53)    NULL,
    [NT_TRI_RATECHNG2]       TINYINT       NULL,
    [NT_RND_DIFF_POSTED]     TINYINT       NULL,
    [NT_SPCL_TRANTYPE]       VARCHAR (20)  NULL,
    [NT_SRV_STATUS]          TINYINT       NULL,
    [NT_SOURCE]              VARCHAR (1)   NULL,
    [NT_TRAN_OPTIONS]        VARCHAR (30)  NULL,
    [NT_PERIOD_MAXC]         FLOAT (53)    NULL,
    [NT_YEAR_LINK]           SMALLINT      NULL,
    [NT_NOM_CAT_LINK]        INT           NULL,
    [NT_WFF_APPROVAL_STATUS] SMALLINT      NULL,
    [NT_LANDED_COST]         BIT           NULL
);

