CREATE TABLE [dbo].[ARM_CM_SECURITY] (
    [ARM_PROFILE_CODE]   VARCHAR (10) NULL,
    [ARM_CODE]           VARCHAR (10) NULL,
    [ARM_ACCESS_ALLOWED] TINYINT      NULL,
    [ARM_OPTIONS]        VARCHAR (50) NULL
);

