CREATE TABLE [dbo].[ARM_CM_SL_PL_NL_DETAIL2] (
    [DET_PRIMARY_2] FLOAT (53)    NOT NULL,
    [DET_CHAR1]     VARCHAR (20)  NULL,
    [DET_CHAR2]     VARCHAR (20)  NULL,
    [DET_CHAR3]     VARCHAR (100) NULL,
    [DET_CHAR4]     VARCHAR (100) NULL,
    [DET_FLAG1]     TINYINT       NULL,
    [DET_FLAG2]     TINYINT       NULL,
    [DET_DATE1]     DATETIME      NULL,
    [DET_DATE2]     DATETIME      NULL,
    [DET_NUM1]      FLOAT (53)    NULL,
    [DET_NUM2]      FLOAT (53)    NULL,
    [DET_USRCHAR1]  VARCHAR (20)  NULL,
    [DET_USRCHAR2]  VARCHAR (20)  NULL,
    [DET_USRCHAR3]  VARCHAR (100) NULL,
    [DET_USRCHAR4]  VARCHAR (100) NULL,
    [DET_USRFLAG1]  TINYINT       NULL,
    [DET_USRFLAG2]  TINYINT       NULL,
    [DET_USRDATE1]  DATETIME      NULL,
    [DET_USRDATE2]  DATETIME      NULL,
    [DET_USRNUM1]   FLOAT (53)    NULL,
    [DET_USRNUM2]   FLOAT (53)    NULL
);

