CREATE TABLE [dbo].[ARM_CM_SL_TRANSACTIONS2] (
    [ST_PRIMARY_2] FLOAT (53)    NOT NULL,
    [ST_CHAR1]     VARCHAR (20)  NULL,
    [ST_CHAR2]     VARCHAR (20)  NULL,
    [ST_CHAR3]     VARCHAR (100) NULL,
    [ST_CHAR4]     VARCHAR (100) NULL,
    [ST_FLAG1]     TINYINT       NULL,
    [ST_FLAG2]     TINYINT       NULL,
    [ST_DATE1]     DATETIME      NULL,
    [ST_DATE2]     DATETIME      NULL,
    [ST_NUM1]      FLOAT (53)    NULL,
    [ST_NUM2]      FLOAT (53)    NULL,
    [STT_USRCHAR1] VARCHAR (20)  NULL,
    [ST_USRCHAR2]  VARCHAR (20)  NULL,
    [ST_USRCHAR3]  VARCHAR (100) NULL,
    [ST_USRCHAR4]  VARCHAR (100) NULL,
    [ST_USRFLAG1]  TINYINT       NULL,
    [ST_USRFLAG2]  TINYINT       NULL,
    [ST_USRDATE1]  DATETIME      NULL,
    [ST_USRDATE2]  DATETIME      NULL,
    [ST_USRNUM1]   FLOAT (53)    NULL,
    [ST_USRNUM2]   FLOAT (53)    NULL
);

