CREATE TABLE [dbo].[CB_AUTOBANKREC_TEMPLATES] (
    [ABRT_PRIMARY]            INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ABRT_CODE]               VARCHAR (20) NOT NULL,
    [ABRT_NAME]               VARCHAR (80) NULL,
    [ABRT_STATEMENT_SEARCH]   TEXT         NULL,
    [ABRT_DIMENSIONS_SEARCH]  TEXT         NULL,
    [ABRT_MATCHING_FORMULA]   TEXT         NULL,
    [ABRT_CREATE_TRANSACTION] BIT          DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ABRT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ABRT_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ABRT_CODE]
    ON [dbo].[CB_AUTOBANKREC_TEMPLATES]([ABRT_CODE] ASC);

