CREATE TABLE [dbo].[CB_AUTOBANKREC_NOTES] (
    [ABRNT_PRIMARY]        INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ABRNT_STATEMENT_LINK] INT          NULL,
    [ABRNT_SOURCE]         VARCHAR (3)  NOT NULL,
    [ABRNT_NOTES]          TEXT         NULL,
    [ABRNT_USER_EDITED]    VARCHAR (4)  NULL,
    [ABRNT_DATE_EDITED]    DATETIME     NULL,
    [ABRNT_CATEGORY]       VARCHAR (20) NULL,
    [ABRNT_USER_PUTIN]     VARCHAR (4)  NOT NULL,
    [ABRNT_DATE_PUTIN]     DATETIME     DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [ABRNT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ABRNT_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [ABRNT_SOURCE_LINK_CK] CHECK ([ABRNT_SOURCE]='STA' AND [ABRNT_STATEMENT_LINK] IS NOT NULL),
    CONSTRAINT [ABRNT_STATEMENT_LINK_FK] FOREIGN KEY ([ABRNT_STATEMENT_LINK]) REFERENCES [dbo].[CB_AUTOBANKREC_STATEMENT] ([ABRS_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [ABRNT_STATEMENT_LINK]
    ON [dbo].[CB_AUTOBANKREC_NOTES]([ABRNT_STATEMENT_LINK] ASC) WITH (FILLFACTOR = 70);

