CREATE TABLE [dbo].[CB_AUTOBANKREC_STATEMENT_TRAN] (
    [ABRST_PRIMARY]        INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ABRST_STATEMENT_LINK] INT           NOT NULL,
    [ABRST_REFERENCE]      VARCHAR (100) NULL,
    [ABRST_DATE]           DATETIME      NULL,
    [ABRST_VALUE]          FLOAT (53)    NULL,
    [ABRST_TYPE]           VARCHAR (5)   NULL,
    [ABRST_DATE_PUTIN]     DATETIME      DEFAULT (getdate()) NOT NULL,
    [ABRST_USER_PUTIN]     VARCHAR (4)   NOT NULL,
    [ABRST_REFERENCE2]     VARCHAR (100) NULL,
    [ABRST_REFERENCE3]     VARCHAR (100) NULL,
    [ABRST_REFERENCE4]     VARCHAR (100) NULL,
    [ABRST_REFERENCE5]     VARCHAR (100) NULL,
    CONSTRAINT [ABRST_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ABRST_PRIMARY] ASC),
    CONSTRAINT [ABRST_STATEMENT_LINK_FK] FOREIGN KEY ([ABRST_STATEMENT_LINK]) REFERENCES [dbo].[CB_AUTOBANKREC_STATEMENT] ([ABRS_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [ABRST_STATEMENT_LINK]
    ON [dbo].[CB_AUTOBANKREC_STATEMENT_TRAN]([ABRST_STATEMENT_LINK] ASC);

