CREATE TABLE [dbo].[CB_AUTOBANKREC_RECONCILED] (
    [ABRR_PRIMARY]             INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ABRR_STATEMENT_TRAN_LINK] INT         NOT NULL,
    [ABRR_DET_LINK]            FLOAT (53)  NOT NULL,
    [ABRR_DIMENSIONS_UPDATED]  DATETIME    NULL,
    [ABRR_USER_UPDATED]        VARCHAR (4) NULL,
    [ABRR_RECONCILED_VALUE]    FLOAT (53)  NOT NULL,
    [ABRR_USER_PUTIN]          VARCHAR (4) NOT NULL,
    [ABRR_DATE_PUTIN]          DATETIME    DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [ABRR_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ABRR_PRIMARY] ASC),
    CONSTRAINT [ABRR_DET_LINK_FK] FOREIGN KEY ([ABRR_DET_LINK]) REFERENCES [dbo].[SL_PL_NL_DETAIL] ([DET_PRIMARY]),
    CONSTRAINT [ABRR_STATEMENT_TRAN_LINK_FK] FOREIGN KEY ([ABRR_STATEMENT_TRAN_LINK]) REFERENCES [dbo].[CB_AUTOBANKREC_STATEMENT_TRAN] ([ABRST_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [ABRR_DET_LINK]
    ON [dbo].[CB_AUTOBANKREC_RECONCILED]([ABRR_DET_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [ABRR_STATEMENT_TRAN_LINK]
    ON [dbo].[CB_AUTOBANKREC_RECONCILED]([ABRR_STATEMENT_TRAN_LINK] ASC);

