CREATE TABLE [dbo].[CB_AUTOBANKREC_TRAN_TEMPLATE] (
    [ABRTT_PRIMARY]        INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ABRTT_UPDATE_TABLE]   VARCHAR (255) NOT NULL,
    [ABRTT_UPDATE_COLUMN]  VARCHAR (255) NOT NULL,
    [ABRTT_UPDATE_TYPE]    TINYINT       NOT NULL,
    [ABRTT_UPDATE_FORMULA] TEXT          NOT NULL,
    [ABRTT_TEMPLATE_LINK]  INT           NOT NULL,
    CONSTRAINT [ABRTT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ABRTT_PRIMARY] ASC),
    CONSTRAINT [ABRTT_UPDATE_TYPE_CK] CHECK ([ABRTT_UPDATE_TYPE]>=(0) AND [ABRTT_UPDATE_TYPE]<=(2)),
    CONSTRAINT [ABRTT_TEMPLATE_LINK_FK] FOREIGN KEY ([ABRTT_TEMPLATE_LINK]) REFERENCES [dbo].[CB_AUTOBANKREC_TEMPLATES] ([ABRT_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [ABRTT_TEMPLATE_LINK]
    ON [dbo].[CB_AUTOBANKREC_TRAN_TEMPLATE]([ABRTT_TEMPLATE_LINK] ASC);

