CREATE TABLE [dbo].[CB_RECONCILE_TEMP] (
    [RECON_ID]          INT NOT NULL,
    [RECON_DET_PRIMARY] INT NOT NULL,
    [RECON_LINE_NUMBER] INT NULL,
    CONSTRAINT [CB_RECONCILE_TEMP_PK] PRIMARY KEY CLUSTERED ([RECON_ID] ASC, [RECON_DET_PRIMARY] ASC)
);

