CREATE TABLE [dbo].[CIS_TAX_RATES] (
    [CIS_PRIMARY]        INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CIS_STANDARD_RATE]  FLOAT (53) DEFAULT ((0)) NULL,
    [CIS_HIGHER_RATE]    FLOAT (53) DEFAULT ((0)) NULL,
    [CIS_CITB_LEVY]      FLOAT (53) DEFAULT ((0)) NULL,
    [CIS_EFFECTIVE_DATE] DATETIME   NULL,
    CONSTRAINT [CIS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CIS_PRIMARY] ASC)
);

