CREATE TABLE [dbo].[CM_PICKLIST] (
    [PK_CON_CODE]     VARCHAR (37) NULL,
    [PK_ITEM]         VARCHAR (20) NULL,
    [PK_ADD_CON_CODE] VARCHAR (16) NULL,
    [PK_CUPROSCODE]   VARCHAR (10) NULL,
    [PK_PRIMARY]      FLOAT (53)   NOT NULL,
    CONSTRAINT [PK_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PK_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PK_CON_CODE]
    ON [dbo].[CM_PICKLIST]([PK_CON_CODE] ASC);

