CREATE TABLE [dbo].[CO2_TURNOVERS] (
    [CTNO_PRIMARY]           INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CTNO_CLASS_LINK]        INT        NOT NULL,
    [CTNO_1ST_CATEGORY_LINK] INT        NULL,
    [CTNO_2ND_CATEGORY_LINK] INT        NULL,
    [CTNO_YEAR]              SMALLINT   NOT NULL,
    [CTNO_PERIOD]            TINYINT    NOT NULL,
    [CTNO_CO2]               FLOAT (53) NOT NULL,
    [CTNO_YEAR_LINK]         SMALLINT   NULL,
    [CTNO_GHG_SCOPE_LINK]    TINYINT    NOT NULL,
    [CTNO_SORT_KEY_1_LINK]   INT        NULL,
    [CTNO_SORT_KEY_2_LINK]   INT        NULL,
    [CTNO_SORT_KEY_3_LINK]   INT        NULL,
    [CTNO_SORT_KEY_4_LINK]   INT        NULL,
    CONSTRAINT [CTNO_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CTNO_PRIMARY] ASC),
    CONSTRAINT [CTNO_YEAR_LINK_CK] CHECK ([CTNO_YEAR] IS NOT NULL AND [CTNO_YEAR_LINK] IS NOT NULL OR [CTNO_YEAR] IS NULL AND [CTNO_YEAR_LINK] IS NULL),
    CONSTRAINT [CTNO_1ST_CATEGORY_LINK_FK] FOREIGN KEY ([CTNO_1ST_CATEGORY_LINK]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_PRIMARY]),
    CONSTRAINT [CTNO_2ND_CATEGORY_LINK_FK] FOREIGN KEY ([CTNO_2ND_CATEGORY_LINK]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_PRIMARY]),
    CONSTRAINT [CTNO_CLASS_LINK_FK] FOREIGN KEY ([CTNO_CLASS_LINK]) REFERENCES [dbo].[CO2_CLASSIFICATIONS] ([CCLS_PRIMARY]),
    CONSTRAINT [CTNO_GHG_SCOPE_LINK_FK] FOREIGN KEY ([CTNO_GHG_SCOPE_LINK]) REFERENCES [dbo].[CO2_GHG_SCOPE] ([CGHGS_PRIMARY]),
    CONSTRAINT [CTNO_SORT_KEY_1_LINK_FK] FOREIGN KEY ([CTNO_SORT_KEY_1_LINK]) REFERENCES [dbo].[CO2_SORT_KEYS_1] ([CSK1_PRIMARY]),
    CONSTRAINT [CTNO_SORT_KEY_2_LINK_FK] FOREIGN KEY ([CTNO_SORT_KEY_2_LINK]) REFERENCES [dbo].[CO2_SORT_KEYS_2] ([CSK2_PRIMARY]),
    CONSTRAINT [CTNO_SORT_KEY_3_LINK_FK] FOREIGN KEY ([CTNO_SORT_KEY_3_LINK]) REFERENCES [dbo].[CO2_SORT_KEYS_3] ([CSK3_PRIMARY]),
    CONSTRAINT [CTNO_SORT_KEY_4_LINK_FK] FOREIGN KEY ([CTNO_SORT_KEY_4_LINK]) REFERENCES [dbo].[CO2_SORT_KEYS_4] ([CSK4_PRIMARY]),
    CONSTRAINT [CTNO_YEAR_LINK_FK] FOREIGN KEY ([CTNO_YEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CTNO_YEAR_PERIOD_CLASS]
    ON [dbo].[CO2_TURNOVERS]([CTNO_YEAR] ASC, [CTNO_PERIOD] ASC, [CTNO_CLASS_LINK] ASC, [CTNO_1ST_CATEGORY_LINK] ASC, [CTNO_2ND_CATEGORY_LINK] ASC, [CTNO_GHG_SCOPE_LINK] ASC, [CTNO_SORT_KEY_1_LINK] ASC, [CTNO_SORT_KEY_2_LINK] ASC, [CTNO_SORT_KEY_3_LINK] ASC, [CTNO_SORT_KEY_4_LINK] ASC)
    INCLUDE([CTNO_CO2], [CTNO_PRIMARY]) WITH (FILLFACTOR = 70);

