CREATE TABLE [dbo].[CO2_CLASSIFICATIONS] (
    [CCLS_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CCLS_GROUP_LINK]  INT          NOT NULL,
    [CCLS_CLASS_ID]    CHAR (4)     NOT NULL,
    [CCLS_DESCRIPTION] VARCHAR (60) NOT NULL,
    [CCLS_USER_PUTIN]  VARCHAR (4)  NOT NULL,
    [CCLS_DATE_PUTIN]  DATETIME     DEFAULT (getdate()) NOT NULL,
    [CCLS_USER_EDITED] VARCHAR (4)  NULL,
    [CCLS_DATE_EDITED] DATETIME     NULL,
    [CCLS_SOURCE]      VARCHAR (1)  NULL,
    CONSTRAINT [CCLS_PRIMARY_PK] PRIMARY KEY NONCLUSTERED ([CCLS_PRIMARY] ASC),
    CONSTRAINT [CCLS_CLASS_ID_CK] CHECK ([CCLS_CLASS_ID]<>''),
    CONSTRAINT [CCLS_DESCRIPTION_CK] CHECK ([CCLS_DESCRIPTION]<>''),
    CONSTRAINT [CCLS_GROUP_LINK_FK] FOREIGN KEY ([CCLS_GROUP_LINK]) REFERENCES [dbo].[CO2_EMISSIONS_GROUPS] ([CGRP_PRIMARY])
);


GO
CREATE UNIQUE CLUSTERED INDEX [CCLS_GROUP_LINK_CCLS_CLASS_ID]
    ON [dbo].[CO2_CLASSIFICATIONS]([CCLS_GROUP_LINK] ASC, [CCLS_CLASS_ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CCLS_GROUP_LINK_CCLS_PRIMARY]
    ON [dbo].[CO2_CLASSIFICATIONS]([CCLS_GROUP_LINK] ASC, [CCLS_PRIMARY] ASC);


GO
CREATE NONCLUSTERED INDEX [CCLS_PRIMARY_CCLS_GROUP_LINK_CCLS_CLASS_ID_CCLS_DESCRIPTION]
    ON [dbo].[CO2_CLASSIFICATIONS]([CCLS_PRIMARY] ASC, [CCLS_GROUP_LINK] ASC, [CCLS_CLASS_ID] ASC, [CCLS_DESCRIPTION] ASC);

