CREATE TABLE [dbo].[CO2_SORT_KEYS_1] (
    [CSK1_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CSK1_DESCRIPTION] VARCHAR (20) NOT NULL,
    [CSK1_SORT_ORDER]  INT          NOT NULL,
    [CSK1_DO_NOT_USE]  BIT          NOT NULL,
    [CSK1_USER_PUTIN]  VARCHAR (4)  NOT NULL,
    [CSK1_DATE_PUTIN]  DATETIME     NOT NULL,
    [CSK1_USER_EDITED] VARCHAR (4)  NULL,
    [CSK1_DATE_EDITED] DATETIME     NULL,
    CONSTRAINT [CSK1_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CSK1_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CSK1_DESCRIPTION]
    ON [dbo].[CO2_SORT_KEYS_1]([CSK1_DESCRIPTION] ASC)
    INCLUDE([CSK1_DO_NOT_USE], [CSK1_SORT_ORDER]) WITH (FILLFACTOR = 70);

