CREATE TABLE [dbo].[CO2_CONVERSION_HISTORY] (
    [CHIS_VERSION]        INT           NOT NULL,
    [CHIS_EFFECTIVE_DATE] DATETIME      NOT NULL,
    [CHIS_FILENAME]       VARCHAR (255) NOT NULL,
    [CHIS_USER_PUTIN]     VARCHAR (4)   NOT NULL,
    [CHIS_DATE_PUTIN]     DATETIME      DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [CHIS_VERSION_PK] PRIMARY KEY NONCLUSTERED ([CHIS_VERSION] ASC) WITH (FILLFACTOR = 70)
);

