CREATE TABLE [dbo].[CO2_SORT_KEYS_3] (
    [CSK3_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CSK3_DESCRIPTION] VARCHAR (20) NOT NULL,
    [CSK3_SORT_ORDER]  INT          NOT NULL,
    [CSK3_DO_NOT_USE]  BIT          NOT NULL,
    [CSK3_USER_PUTIN]  VARCHAR (4)  NOT NULL,
    [CSK3_DATE_PUTIN]  DATETIME     NOT NULL,
    [CSK3_USER_EDITED] VARCHAR (4)  NULL,
    [CSK3_DATE_EDITED] DATETIME     NULL,
    CONSTRAINT [CSK3_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CSK3_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CSK3_DESCRIPTION]
    ON [dbo].[CO2_SORT_KEYS_3]([CSK3_DESCRIPTION] ASC)
    INCLUDE([CSK3_DO_NOT_USE], [CSK3_SORT_ORDER]) WITH (FILLFACTOR = 70);

