CREATE TABLE [dbo].[CO2_GHG_SCOPE] (
    [CGHGS_PRIMARY]     TINYINT       NOT NULL,
    [CGHGS_CODE]        VARCHAR (10)  NOT NULL,
    [CGHGS_DESCRIPTION] VARCHAR (256) NOT NULL,
    CONSTRAINT [CGHGS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CGHGS_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [CGHGS_CODE_CK] CHECK ([CGHGS_CODE]<>'')
);

