CREATE TABLE [dbo].[CO2_SORT_KEYS_4] (
    [CSK4_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CSK4_DESCRIPTION] VARCHAR (20) NOT NULL,
    [CSK4_SORT_ORDER]  INT          NOT NULL,
    [CSK4_DO_NOT_USE]  BIT          NOT NULL,
    [CSK4_USER_PUTIN]  VARCHAR (4)  NOT NULL,
    [CSK4_DATE_PUTIN]  DATETIME     NOT NULL,
    [CSK4_USER_EDITED] VARCHAR (4)  NULL,
    [CSK4_DATE_EDITED] DATETIME     NULL,
    CONSTRAINT [CSK4_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CSK4_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CSK4_DESCRIPTION]
    ON [dbo].[CO2_SORT_KEYS_4]([CSK4_DESCRIPTION] ASC)
    INCLUDE([CSK4_DO_NOT_USE], [CSK4_SORT_ORDER]) WITH (FILLFACTOR = 70);

