CREATE TABLE [dbo].[CO2_EMISSIONS_GROUPS] (
    [CGRP_PRIMARY]                INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CGRP_ID]                     CHAR (2)     NOT NULL,
    [CGRP_DESCRIPTION]            VARCHAR (40) NOT NULL,
    [CGRP_USER_PUTIN]             VARCHAR (4)  NOT NULL,
    [CGRP_DATE_PUTIN]             DATETIME     DEFAULT (getdate()) NOT NULL,
    [CGRP_USER_EDITED]            VARCHAR (4)  NULL,
    [CGRP_DATE_EDITED]            DATETIME     NULL,
    [CGRP_SOURCE]                 VARCHAR (1)  NULL,
    [CGRP_DEFAULT_GHG_SCOPE_LINK] TINYINT      NOT NULL,
    CONSTRAINT [CGRP_PRIMARY_PK] PRIMARY KEY NONCLUSTERED ([CGRP_PRIMARY] ASC),
    CONSTRAINT [CGRP_DESCRIPTION_CK] CHECK ([CGRP_DESCRIPTION]<>''),
    CONSTRAINT [CGRP_ID_CK] CHECK ([CGRP_ID]='09' OR [CGRP_ID]='08' OR [CGRP_ID]='07' OR [CGRP_ID]='06' OR [CGRP_ID]='05' OR [CGRP_ID]='04' OR [CGRP_ID]='03' OR [CGRP_ID]='01')
);


GO
CREATE UNIQUE CLUSTERED INDEX [CGRP_ID]
    ON [dbo].[CO2_EMISSIONS_GROUPS]([CGRP_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [CGRP_PRIMARY_CGRP_ID_CGRP_DESCRIPTION]
    ON [dbo].[CO2_EMISSIONS_GROUPS]([CGRP_PRIMARY] ASC, [CGRP_ID] ASC, [CGRP_DESCRIPTION] ASC);

