CREATE TABLE [dbo].[CRM_CAMPAIGN_STATUS] (
    [CMS_PRIMARY]       INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CMS_CAMPAIGN_LINK] INT          DEFAULT ((0)) NULL,
    [CMS_STATUS]        VARCHAR (30) NULL,
    [CMS_SEQUENCE]      INT          DEFAULT ((0)) NULL,
    CONSTRAINT [CMS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CMS_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CMS_CAMPAIGN_LINK]
    ON [dbo].[CRM_CAMPAIGN_STATUS]([CMS_CAMPAIGN_LINK] ASC);

