CREATE TABLE [dbo].[CRM_LETTER] (
    [CRML_PRIMARY]     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CRML_TYPE]        CHAR (1)      NOT NULL,
    [CRML_VIEW]        VARCHAR (255) NULL,
    [CRML_EMAIL_ADD]   VARCHAR (64)  NULL,
    [CRML_EMAIL_SUBJ]  VARCHAR (80)  NULL,
    [CRML_LOCATION]    VARCHAR (500) NULL,
    [CRML_ACTIVE]      BIT           NULL,
    [CRML_AS_ATTACH]   BIT           NULL,
    [CRML_LEAD_SOURCE] VARCHAR (100) NULL,
    CONSTRAINT [CRML_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CRML_PRIMARY] ASC)
);

