CREATE TABLE [dbo].[CRM_CAMPAIGN] (
    [CMP_PRIMARY]       INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CMP_USRCHAR1]      VARCHAR (20) NULL,
    [CMP_USRCHAR2]      VARCHAR (20) NULL,
    [CMP_USRCHAR3]      VARCHAR (20) NULL,
    [CMP_USRCHAR4]      VARCHAR (20) NULL,
    [CMP_USRCHAR5]      VARCHAR (20) NULL,
    [CMP_USRCHAR6]      VARCHAR (20) NULL,
    [CMP_USRCHAR7]      VARCHAR (20) NULL,
    [CMP_USRCHAR8]      VARCHAR (20) NULL,
    [CMP_USRCHAR9]      VARCHAR (20) NULL,
    [CMP_USRCHAR10]     VARCHAR (20) NULL,
    [CMP_USRCHAR11]     VARCHAR (20) NULL,
    [CMP_USRCHAR12]     VARCHAR (20) NULL,
    [CMP_USRDATE1]      DATETIME     NULL,
    [CMP_USRDATE2]      DATETIME     NULL,
    [CMP_USRDATE3]      DATETIME     NULL,
    [CMP_USRDATE4]      DATETIME     NULL,
    [CMP_USRDATE5]      DATETIME     NULL,
    [CMP_USRNUM1]       FLOAT (53)   DEFAULT ((0)) NULL,
    [CMP_USRNUM2]       FLOAT (53)   DEFAULT ((0)) NULL,
    [CMP_USRNUM3]       FLOAT (53)   DEFAULT ((0)) NULL,
    [CMP_USRNUM4]       FLOAT (53)   DEFAULT ((0)) NULL,
    [CMP_USRNUM5]       FLOAT (53)   DEFAULT ((0)) NULL,
    [CMP_CODE]          VARCHAR (20) NULL,
    [CMP_DESCRIPTION]   VARCHAR (80) NULL,
    [CMP_ACTIVE]        TINYINT      DEFAULT ((0)) NULL,
    [CMP_NOTES]         TEXT         NULL,
    [CMP_STARTDATE]     DATETIME     NULL,
    [CMP_DATE_PUTIN]    DATETIME     NULL,
    [CMP_DATE_EDITED]   DATETIME     NULL,
    [CMP_CAMPAIGN_COST] FLOAT (53)   NULL,
    CONSTRAINT [CMP_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CMP_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CMP_CODE]
    ON [dbo].[CRM_CAMPAIGN]([CMP_CODE] ASC) WITH (FILLFACTOR = 70);

