CREATE TABLE [dbo].[CRM_LOOKUPS] (
    [CRMLK_PRIMARY] INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CRMLK_TEXT]    VARCHAR (40) NULL,
    [CRMLK_TYPE]    VARCHAR (5)  NULL,
    [CRMLK_OPTION]  VARCHAR (10) NULL,
    [CRMLK_VALUE1]  INT          NULL,
    [CRMLK_FLAG1]   TINYINT      DEFAULT ((0)) NULL,
    CONSTRAINT [CRMLK_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CRMLK_PRIMARY] ASC)
);

