CREATE TABLE [dbo].[CRM_FILTERS] (
    [CRMF_PRIMARY]        INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CRMF_FILTERNAME]     VARCHAR (40)  NULL,
    [CRMF_FIELD1]         VARCHAR (50)  NULL,
    [CRMF_FIELD2]         VARCHAR (50)  NULL,
    [CRMF_USER]           VARCHAR (4)   NULL,
    [CRMF_TAB]            VARCHAR (1)   NULL,
    [CRMF_VALUE1]         VARCHAR (100) NULL,
    [CRMF_VALUE2]         VARCHAR (100) NULL,
    [CRMF_CRITERIA_FIELD] VARCHAR (100) NULL,
    CONSTRAINT [CRMF_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CRMF_PRIMARY] ASC)
);

