CREATE TABLE [dbo].[CRM_CAMPAIGN_HISTORY1] (
    [CRH_PRIMARY]           INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CRH_CMS_LINK]          INT         DEFAULT ((0)) NULL,
    [CRH_AD_LINK]           INT         DEFAULT ((0)) NULL,
    [CRH_TYPE]              VARCHAR (1) NULL,
    [CRH_DATE]              DATETIME    NULL,
    [CRH_USER]              VARCHAR (4) NULL,
    [CRH_CMS_NEW]           VARCHAR (1) NULL,
    [CRH_CU_LINK]           INT         DEFAULT ((0)) NULL,
    [CRH_TIME]              DATETIME    NULL,
    [CRH_PREVIOUS_CMS_LINK] INT         DEFAULT ((0)) NULL,
    CONSTRAINT [CRH_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CRH_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CRH_AD_LINK]
    ON [dbo].[CRM_CAMPAIGN_HISTORY1]([CRH_AD_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [CRH_CMS_LINK]
    ON [dbo].[CRM_CAMPAIGN_HISTORY1]([CRH_CMS_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [CRH_CU_LINK]
    ON [dbo].[CRM_CAMPAIGN_HISTORY1]([CRH_CU_LINK] ASC);

