CREATE TABLE [dbo].[CRM_TASKS] (
    [CMT_PRIMARY]      INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CMT_REC_TYPE]     VARCHAR (1)  NULL,
    [CMT_CU_LINK]      INT          DEFAULT ((0)) NULL,
    [CMT_AD_LINK]      INT          DEFAULT ((0)) NULL,
    [CMT_TYPE]         VARCHAR (40) NULL,
    [CMT_DATE_ENTERED] DATETIME     NULL,
    [CMT_USER_ENTERED] VARCHAR (4)  NULL,
    [CMT_REMINDER]     VARCHAR (40) NULL,
    [CMT_REM_USER]     VARCHAR (4)  NULL,
    [CMT_REM_DATE]     DATETIME     NULL,
    [CMT_REM_STATUS]   VARCHAR (40) NULL,
    [CMT_NOTES]        TEXT         NULL,
    [CMT_CONTACT]      VARCHAR (30) NULL,
    [CMT_REM_TIME]     DATETIME     NULL,
    [CMT_DATE_EDITED]  DATETIME     NULL,
    CONSTRAINT [CMT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CMT_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CMT_AD_LINK]
    ON [dbo].[CRM_TASKS]([CMT_AD_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [CMT_CU_LINK]
    ON [dbo].[CRM_TASKS]([CMT_CU_LINK] ASC);

