CREATE TABLE [dbo].[CRM_LOOKUP_TEXT] (
    [CRM_TXT_ORIGIN]      VARCHAR (8)   NULL,
    [CRM_TXT_USER_TEXT]   VARCHAR (100) NULL,
    [CRM_TXT_SORT_ORDER]  INT           NULL,
    [CRM_TXT_PRIMARY]     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CRM_TXT_USER_EDITED] VARCHAR (4)   NULL,
    [CRM_TXT_USER_PUTIN]  VARCHAR (4)   NULL,
    [CRM_TXT_DATE_EDITED] DATETIME      NULL,
    [CRM_TXT_DATE_PUTIN]  DATETIME      NULL,
    [CRM_TXT_ACTIVE]      TINYINT       DEFAULT ((0)) NULL,
    [CRM_TXT_PROS_LINK]   INT           DEFAULT ((0)) NULL,
    [CRM_TXT_CONT_LINK]   INT           DEFAULT ((0)) NULL,
    CONSTRAINT [CRM_TXT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CRM_TXT_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CRM_TXT_CONT_LINK]
    ON [dbo].[CRM_LOOKUP_TEXT]([CRM_TXT_CONT_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [CRM_TXT_PROS_LINK]
    ON [dbo].[CRM_LOOKUP_TEXT]([CRM_TXT_PROS_LINK] ASC);

