CREATE TABLE [dbo].[CST_TRANSACTION_SUBTYPE] (
    [CTT_PRIMARY] INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CTT_TYPE]    VARCHAR (3)  NULL,
    [CTT_NAME]    VARCHAR (10) NULL,
    [CTT_DESC]    VARCHAR (40) NULL,
    [CTT_SYSTEM]  TINYINT      DEFAULT ((0)) NULL,
    CONSTRAINT [CTT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CTT_PRIMARY] ASC)
);

