CREATE TABLE [dbo].[CST_RESOURCE_COST_TURNOVERS] (
    [RCT_YEAR_LINK]     SMALLINT   NOT NULL,
    [RCT_PERIOD]        TINYINT    NOT NULL,
    [RCT_RESOURCE_LINK] INT        NOT NULL,
    [RCT_VALUE]         FLOAT (53) DEFAULT ((0)) NULL,
    [RCT_QUANTITY]      FLOAT (53) NULL,
    CONSTRAINT [RCT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([RCT_RESOURCE_LINK] ASC, [RCT_YEAR_LINK] ASC, [RCT_PERIOD] ASC)
);

