CREATE TABLE [dbo].[CST_PROJECT_STRUCTURE_NODES_TEMP] (
    [CPNT_BATCH_GUID]            UNIQUEIDENTIFIER NULL,
    [CPNT_PRIMARY]               INT              IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CPNT_REAL_PRIMARY]          INT              NOT NULL,
    [CPNT_FAKE_PRIMARY]          INT              NOT NULL,
    [CPNT_REAL_PARENT_NODE_LINK] INT              NULL,
    [CPNT_FAKE_PARENT_NODE_LINK] INT              NULL,
    [CPNT_DELETE]                BIT              NULL,
    [CPNT_CC_MASTER_LINK]        INT              NULL,
    [CPNT_NODE_INDEX]            INT              NULL,
    [CPNT_STATUS]                TINYINT          NULL,
    CONSTRAINT [CPNT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CPNT_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CPNT_CC_MASTER_LINK]
    ON [dbo].[CST_PROJECT_STRUCTURE_NODES_TEMP]([CPNT_CC_MASTER_LINK] ASC, [CPNT_BATCH_GUID] ASC);

