CREATE TABLE [dbo].[CST_BUDGET_REVISION] (
    [CB_PRIMARY]         INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CB_PROJECT_LINK]    INT           NOT NULL,
    [CB_REVISION_NUMBER] SMALLINT      NOT NULL,
    [CB_NOTES]           VARCHAR (240) NULL,
    [CB_SOURCE]          VARCHAR (2)   NULL,
    [CB_USER_PUTIN]      VARCHAR (4)   NOT NULL,
    [CB_DATE_PUTIN]      DATETIME      NOT NULL,
    [CB_YEAR]            SMALLINT      NOT NULL,
    [CB_EXCHANGE_RATE]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [CB_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CB_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CB_PROJECT_YEAR_REVISION]
    ON [dbo].[CST_BUDGET_REVISION]([CB_PROJECT_LINK] ASC, [CB_YEAR] ASC, [CB_REVISION_NUMBER] ASC);

