CREATE TABLE [dbo].[CST_RESOURCE_RATE] (
    [CR_RESOURCE_LINK]  INT        NOT NULL,
    [CR_RATE_NUMBER]    INT        NOT NULL,
    [CR_COST_PRICE]     FLOAT (53) NULL,
    [CR_UPLIFT_P]       FLOAT (53) NULL,
    [CR_UPLIFT_VALUE]   FLOAT (53) NULL,
    [CR_COST_UPLIFT]    FLOAT (53) NULL,
    [CR_MARGIN_P]       FLOAT (53) NULL,
    [CR_MARGIN_VALUE]   FLOAT (53) NULL,
    [CR_FLAT_RATE]      BIT        DEFAULT ((0)) NOT NULL,
    [CR_SALES_PRICE]    FLOAT (53) NULL,
    [CR_CURR_RATE]      FLOAT (53) NULL,
    [CR_CURR_LINK]      INT        NULL,
    [CR_COST_PRICE_C]   FLOAT (53) NULL,
    [CR_UPLIFT_VALUE_C] FLOAT (53) NULL,
    [CR_COST_UPLIFT_C]  FLOAT (53) NULL,
    [CR_MARGIN_VALUE_C] FLOAT (53) NULL,
    [CR_SALES_PRICE_C]  FLOAT (53) NULL,
    CONSTRAINT [CR_RESOURCE_RATE_PK] PRIMARY KEY CLUSTERED ([CR_RESOURCE_LINK] ASC, [CR_RATE_NUMBER] ASC)
);

