CREATE TABLE [dbo].[CST_X_TRN_TEMP] (
    [CST_TRAN_ID]                     INT             DEFAULT ((0)) NOT NULL,
    [CST_USE_DEFAULT]                 VARCHAR (100)   NULL,
    [CST_STATUS_TEMP]                 TINYINT         NOT NULL,
    [CST_USER_ID]                     VARCHAR (5)     NULL,
    [CST_MODULE]                      VARCHAR (3)     NULL,
    [CST_TRAN_STATUS]                 CHAR (1)        NULL,
    [CST_TRAN_TYPE]                   VARCHAR (3)     NULL,
    [CST_TRAN_REFERENCE]              VARCHAR (10)    NULL,
    [CST_BATCH_REFERENCE]             VARCHAR (10)    NULL,
    [CST_TRAN_DATE]                   DATETIME        NULL,
    [CST_WEEK_NO]                     TINYINT         DEFAULT ((0)) NULL,
    [CST_YEAR]                        CHAR (1)        NULL,
    [CST_PERIOD]                      TINYINT         DEFAULT ((0)) NULL,
    [CST_DESCRIPTION]                 VARCHAR (20)    NULL,
    [CST_COSTHEADER]                  VARCHAR (10)    NULL,
    [CST_COSTCENTRE]                  VARCHAR (10)    NULL,
    [CST_RESOURCE]                    VARCHAR (16)    NULL,
    [CST_RESOURCE_RATE]               INT             NULL,
    [CST_CURRENCYCODE]                VARCHAR (4)     NULL,
    [CST_QUANTITY]                    FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_HOME_PRICE]                  FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CURR_PRICE]                  FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_HOME_VALUE]                  FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_UPLIFT_VAL_PRCNT]     FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_UPLIFT_VAL]           FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_CURR_UPLIFT_VAL]      FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_PAYROLL_PAYTYPE]             VARCHAR (20)    NULL,
    [CST_DETAIL]                      VARCHAR (240)   NULL,
    [CST_ARCHIVE_FLAG]                TINYINT         DEFAULT ((0)) NULL,
    [CST_DO_NOT_BATCH]                TINYINT         DEFAULT ((0)) NULL,
    [CST_EXCLUDE_RESORCE_FLAG]        TINYINT         DEFAULT ((0)) NULL,
    [CST_SOURCE]                      VARCHAR (1)     DEFAULT ('   ') NULL,
    [CST_PRIMARY]                     INT             DEFAULT ((0)) NULL,
    [CST_IDENTITY]                    INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CST_DELETE]                      TINYINT         DEFAULT ((0)) NULL,
    [CST_USER_CHAR1]                  VARCHAR (20)    NULL,
    [CST_USER_CHAR2]                  VARCHAR (20)    NULL,
    [CST_USER_CHAR3]                  VARCHAR (100)   NULL,
    [CST_USER_CHAR4]                  VARCHAR (100)   NULL,
    [CST_USER_FLAG1]                  TINYINT         NULL,
    [CST_USER_FLAG2]                  TINYINT         NULL,
    [CST_USER_DATE1]                  DATETIME        NULL,
    [CST_USER_DATE2]                  DATETIME        NULL,
    [CST_USER_NUMBER1]                FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_USER_NUMBER2]                FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_ENTER_CURRENCY]              TINYINT         DEFAULT ((0)) NULL,
    [CST_CALLED_FROM]                 INT             DEFAULT ((0)) NULL,
    [CST_USER_KEY1]                   VARCHAR (20)    NULL,
    [CST_USER_KEY2]                   VARCHAR (20)    NULL,
    [CST_USER_KEY3]                   VARCHAR (20)    NULL,
    [CST_TRAN_SUBTYPE]                INT             NULL,
    [CST_CUSTOMERCODE]                VARCHAR (10)    NULL,
    [CST_CURRENCYSYMBOL]              VARCHAR (4)     NULL,
    [CST_CURRENCYRATE]                DECIMAL (16, 6) NULL,
    [CST_CURRENCYVALUE]               DECIMAL (24, 8) DEFAULT ((0)) NULL,
    [CST_CENTRE_MARKUP_VAL_PRCNT]     FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_MARKUP_VAL]           FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_CURR_MARKUP_VAL]      FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_SUPPLIERCODE]                VARCHAR (10)    NULL,
    [CST_TIME_UNITS]                  FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_TIME_UNIT_TYPE]              VARCHAR (1)     NULL,
    [CST_TIME_UNIT_QUANTITY]          FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_UPLIFT_TYPE]          TINYINT         DEFAULT ((0)) NULL,
    [CST_CENTRE_MARKUP_TYPE]          TINYINT         DEFAULT ((0)) NULL,
    [CST_CENTRE_CURR_UPLIFT_UNIT_VAL] FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_CURR_MARKUP_UNIT_VAL] FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_UPLIFT_UNIT_VAL]      FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_MARKUP_UNIT_VAL]      FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_UPLIFT_PRCNT]         FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_CENTRE_MARKUP_PRCNT]         FLOAT (53)      DEFAULT ((0)) NULL,
    CONSTRAINT [CST_X_TRN_TEMP_PK] PRIMARY KEY CLUSTERED ([CST_TRAN_ID] ASC, [CST_IDENTITY] ASC)
);

