CREATE TABLE [dbo].[CST_RESOURCE_SALES_TURNOVERS] (
    [RST_YEAR_LINK]            SMALLINT   NOT NULL,
    [RST_PERIOD]               TINYINT    NOT NULL,
    [RST_RESOURCE_LINK]        INT        NOT NULL,
    [RST_SALES_VALUE]          FLOAT (53) DEFAULT ((0)) NULL,
    [RST_COSTS_INVOICED_VALUE] FLOAT (53) DEFAULT ((0)) NULL,
    CONSTRAINT [RST_PRIMARY_PK] PRIMARY KEY CLUSTERED ([RST_RESOURCE_LINK] ASC, [RST_YEAR_LINK] ASC, [RST_PERIOD] ASC)
);

