CREATE TABLE [dbo].[CST_WIP_SALES_ORDER_HEADER_TEMP] (
    [SHT_GUID]          UNIQUEIDENTIFIER NOT NULL,
    [SHT_SEQUENCE]      BIGINT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SHT_HEADER_NUMBER] BIGINT           NULL,
    [SHT_STATUS]        TINYINT          NULL,
    [SHT_CUSTOMER_CODE] VARCHAR (10)     NULL,
    [SHT_ORDER_REF]     VARCHAR (20)     NULL,
    [SHT_BATCH_REF]     VARCHAR (10)     NULL,
    [SHT_HEADER_DESC]   VARCHAR (240)    NULL,
    [SHT_ORDER_DATE]    DATETIME         NULL,
    [SHT_USER_SORT1]    VARCHAR (20)     NULL,
    [SHT_USER_SORT2]    VARCHAR (20)     NULL,
    [SHT_USER_SORT3]    VARCHAR (20)     NULL,
    CONSTRAINT [SHT_WIP_SALES_ORDER_HEADER_PK] PRIMARY KEY CLUSTERED ([SHT_SEQUENCE] ASC, [SHT_GUID] ASC)
);

