CREATE TABLE [dbo].[CST_RESOURCE_RATE_CHANGE_RESOURCE_TEMP] (
    [CRR_GUID]          UNIQUEIDENTIFIER NOT NULL,
    [CRR_SEQUENCE]      BIGINT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CRR_STATUS]        TINYINT          NULL,
    [CRR_RESOURCE_LINK] INT              NOT NULL,
    CONSTRAINT [CRR_RESOURCE_PK] PRIMARY KEY CLUSTERED ([CRR_GUID] ASC, [CRR_RESOURCE_LINK] ASC)
);

