CREATE TABLE [dbo].[CST_PROJECT_STRUCTURE_NODES] (
    [CPN_PRIMARY]          INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CPN_STRUCTURE_LINK]   INT NOT NULL,
    [CPN_PARENT_NODE_LINK] INT NULL,
    [CPN_CC_MASTER_LINK]   INT NULL,
    [CPN_NODE_INDEX]       INT NULL,
    [CPN_NODE_LEVEL]       INT NULL,
    CONSTRAINT [CST_PROJECT_STRUCTURE_NODES_PK] PRIMARY KEY CLUSTERED ([CPN_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CPN_CC_MASTER_LINK]
    ON [dbo].[CST_PROJECT_STRUCTURE_NODES]([CPN_CC_MASTER_LINK] ASC, [CPN_STRUCTURE_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [CPN_STRUCTURE_LINK]
    ON [dbo].[CST_PROJECT_STRUCTURE_NODES]([CPN_STRUCTURE_LINK] ASC);

