CREATE TABLE [dbo].[CST_WIP_SALES_ORDER_TEMP] (
    [SOT_GUID]             UNIQUEIDENTIFIER NOT NULL,
    [SOT_SEQUENCE]         BIGINT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SOT_HEADER_LINK]      BIGINT           NULL,
    [SOT_ROLLUP_LINK]      BIGINT           NULL,
    [SOT_STATUS]           TINYINT          NULL,
    [SOT_TRANSACTION_LINK] FLOAT (53)       NULL,
    [SOT_VALUE]            FLOAT (53)       DEFAULT ((0)) NULL,
    [SOT_DEFAULT_STRING]   VARCHAR (20)     NULL,
    CONSTRAINT [SOT_WIP_SALES_ORDER_PK] PRIMARY KEY CLUSTERED ([SOT_SEQUENCE] ASC, [SOT_GUID] ASC)
);

