CREATE TABLE [dbo].[CST_WIP_RELEASE_TEMP] (
    [CWRT_GUID]              UNIQUEIDENTIFIER NOT NULL,
    [CWRT_TRAN_LINK]         INT              NOT NULL,
    [CWRT_ALLOC_HEADER_LINK] INT              NULL,
    [CWRT_STATUS]            TINYINT          DEFAULT ((0)) NOT NULL,
    CONSTRAINT [CST_WIP_RELEASE_TEMP_PK] PRIMARY KEY CLUSTERED ([CWRT_GUID] ASC, [CWRT_TRAN_LINK] ASC)
);

