CREATE TABLE [dbo].[CST_SALES_TURNOVERS] (
    [CTO_YEAR_LINK]    SMALLINT   NOT NULL,
    [CTO_PERIOD]       TINYINT    NOT NULL,
    [CTO_CENTRE_LINK]  INT        NOT NULL,
    [CTO_VALUE]        FLOAT (53) DEFAULT ((0)) NULL,
    [CTO_PROJECT_LINK] INT        NULL,
    CONSTRAINT [CTO_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CTO_CENTRE_LINK] ASC, [CTO_YEAR_LINK] ASC, [CTO_PERIOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CTO_PROJECT_YEAR]
    ON [dbo].[CST_SALES_TURNOVERS]([CTO_PROJECT_LINK] ASC, [CTO_YEAR_LINK] ASC);

