CREATE TABLE [dbo].[CST_RESOURCE_RATE_CHANGE_RATE_TEMP] (
    [CRRT_GUID]          UNIQUEIDENTIFIER NOT NULL,
    [CRRT_SEQUENCE]      BIGINT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CRRT_STATUS]        TINYINT          NULL,
    [CRRT_RESOURCE_LINK] INT              NOT NULL,
    [CRRT_RATE_NUMBER]   INT              NOT NULL,
    [CRRT_FIELD_NUMBER]  TINYINT          NULL,
    [CRRT_VALUE]         FLOAT (53)       NULL,
    [CRRT_METHOD]        TINYINT          NULL,
    [CRRT_TYPE]          BIT              NULL,
    CONSTRAINT [CRRT_RATE_PK] PRIMARY KEY CLUSTERED ([CRRT_GUID] ASC, [CRRT_RESOURCE_LINK] ASC, [CRRT_RATE_NUMBER] ASC)
);

