CREATE TABLE [dbo].[CST_UNRECOVERABLE_EXTRA_WORK_TEMP] (
    [CUET_GUID]      UNIQUEIDENTIFIER NOT NULL,
    [CUET_TRAN_LINK] INT              NOT NULL,
    [CUET_VALUE]     FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CUET_QUANTITY]  FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CUET_STATUS]    TINYINT          DEFAULT ((0)) NOT NULL,
    CONSTRAINT [CST_UNRECOVERABLE_EXTRA_WORK_TEMP_PK] PRIMARY KEY CLUSTERED ([CUET_GUID] ASC, [CUET_TRAN_LINK] ASC)
);

