CREATE TABLE [dbo].[CST_BUDGET_PROFILES] (
    [BUDGET_PROFILE_ID]   INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [BUDGET_PROFILE_NAME] VARCHAR (255) NOT NULL,
    [BUDGET_PROFILE_DATA] IMAGE         NOT NULL,
    [ENTERED_BY]          VARCHAR (4)   NOT NULL,
    [DATE_PUTIN]          DATETIME      NOT NULL,
    [DATE_EDITED]         DATETIME      NULL,
    CONSTRAINT [BUDGET_PROFILE_ID_PK] PRIMARY KEY CLUSTERED ([BUDGET_PROFILE_ID] ASC)
);

