CREATE TABLE [dbo].[CST_PROJECT_STRUCTURE] (
    [CPS_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CPS_CODE]        VARCHAR (10) NOT NULL,
    [CPS_NAME]        VARCHAR (40) NULL,
    [CPS_SORT_KEY]    VARCHAR (20) NULL,
    [CPS_DO_NOT_USE]  BIT          NULL,
    [CPS_DATE_PUTIN]  DATETIME     NULL,
    [CPS_USER_PUTIN]  VARCHAR (4)  NULL,
    [CPS_DATE_EDITED] DATETIME     NULL,
    [CPS_USER_EDITED] VARCHAR (4)  NULL,
    [CPS_SOURCE]      VARCHAR (1)  NULL,
    [CPS_SHARED]      BIT          NULL,
    CONSTRAINT [CST_PROJECT_STRUCTURE_PK] PRIMARY KEY CLUSTERED ([CPS_PRIMARY] ASC)
);

