CREATE TABLE [dbo].[CST_MASTER_RECORD] (
    [CCM_PRIMARY]                INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CCM_CODE]                   VARCHAR (10)  NULL,
    [CCM_NAME]                   VARCHAR (40)  NULL,
    [CCM_CATEGORY]               VARCHAR (1)   NULL,
    [CCM_TYPE]                   TINYINT       NULL,
    [CCM_SALES_ANALYSIS_LINK]    INT           NULL,
    [CCM_PURCHASE_ANALYSIS_LINK] INT           NULL,
    [CCM_SECURITY_LEVEL]         INT           NULL,
    [CCM_SUBTOTAL_SORTKEY]       VARCHAR (20)  DEFAULT ((0)) NULL,
    [CCM_UPLIFT_P]               FLOAT (53)    DEFAULT ((0)) NULL,
    [CCM_UPLIFT_VALUE]           FLOAT (53)    DEFAULT ((0)) NULL,
    [CCM_MARKUP_P]               FLOAT (53)    DEFAULT ((0)) NULL,
    [CCM_MARKUP_VALUE]           FLOAT (53)    DEFAULT ((0)) NULL,
    [CCM_CHRG_LINE]              INT           NULL,
    [CCM_CHRG_RATE]              VARCHAR (1)   NULL,
    [CCM_CHRG_VALUE]             FLOAT (53)    DEFAULT ((0)) NULL,
    [CCM_NOTES]                  VARCHAR (240) NULL,
    [CCM_DATE_PUTIN]             DATETIME      NULL,
    [CCM_USER_PUTIN]             VARCHAR (4)   NULL,
    [CCM_DATE_EDITED]            DATETIME      NULL,
    [CCM_USER_EDITED]            VARCHAR (4)   NULL,
    [CCM_USRCHAR1]               VARCHAR (20)  DEFAULT ('') NULL,
    [CCM_USRCHAR2]               VARCHAR (20)  DEFAULT ('') NULL,
    [CCM_USRCHAR3]               VARCHAR (100) DEFAULT ('') NULL,
    [CCM_USRCHAR4]               VARCHAR (100) DEFAULT ('') NULL,
    [CCM_USRCHAR5]               VARCHAR (20)  DEFAULT ('') NULL,
    [CCM_USRCHAR6]               VARCHAR (30)  DEFAULT ('') NULL,
    [CCM_USRCHAR7]               VARCHAR (30)  DEFAULT ('') NULL,
    [CCM_USRCHAR8]               VARCHAR (30)  DEFAULT ('') NULL,
    [CCM_USRNUM1]                FLOAT (53)    DEFAULT ((0)) NULL,
    [CCM_USRNUM2]                FLOAT (53)    DEFAULT ((0)) NULL,
    [CCM_USRNUM3]                FLOAT (53)    DEFAULT ((0)) NULL,
    [CCM_USRDATE1]               DATETIME      NULL,
    [CCM_USRDATE2]               DATETIME      NULL,
    [CCM_USRDATE3]               DATETIME      NULL,
    [CCM_USRFLAG1]               TINYINT       DEFAULT ((0)) NULL,
    [CCM_USRFLAG2]               TINYINT       DEFAULT ((0)) NULL,
    [CCM_USRFLAG3]               TINYINT       DEFAULT ((0)) NULL,
    [CCM_DO_NOT_USE]             BIT           NULL,
    [CCM_ALLOW_QTY_BUDGETS]      BIT           NULL,
    [CCM_SOURCE]                 VARCHAR (1)   NULL,
    [CCM_UPLIFT_TYPE]            TINYINT       NULL,
    [CCM_MARKUP_TYPE]            TINYINT       NULL,
    CONSTRAINT [CCM_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CCM_PRIMARY] ASC)
);

