CREATE TABLE [dbo].[dhc_JCC_WeeklyStockDemandTBL] (
    [WeekDemandStockCode] VARCHAR (25) NULL,
    [DemandPrevWeek65]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek64]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek63]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek62]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek61]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek60]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek59]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek58]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek57]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek56]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek55]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek54]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek53]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek52]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek51]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek50]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek49]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek48]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek47]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek46]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek45]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek44]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek43]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek42]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek41]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek40]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek39]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek38]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek37]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek36]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek35]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek34]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek33]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek32]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek31]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek30]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek29]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek28]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek27]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek26]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek25]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek24]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek23]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek22]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek21]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek20]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek19]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek18]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek17]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek16]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek15]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek14]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek13]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek12]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek11]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek10]    FLOAT (53)   NOT NULL,
    [DemandPrevWeek9]     FLOAT (53)   NOT NULL,
    [DemandPrevWeek8]     FLOAT (53)   NOT NULL,
    [DemandPrevWeek7]     FLOAT (53)   NOT NULL,
    [DemandPrevWeek6]     FLOAT (53)   NOT NULL,
    [DemandPrevWeek5]     FLOAT (53)   NOT NULL,
    [DemandPrevWeek4]     FLOAT (53)   NOT NULL,
    [DemandPrevWeek3]     FLOAT (53)   NOT NULL,
    [DemandPrevWeek2]     FLOAT (53)   NOT NULL,
    [DemandPrevWeek1]     FLOAT (53)   NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [x_WeekDemandStockCode]
    ON [dbo].[dhc_JCC_WeeklyStockDemandTBL]([WeekDemandStockCode] ASC) WITH (FILLFACTOR = 70);

