CREATE TABLE [dbo].[DHC_CUST_SUMMARY] (
    [SUM_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SUM_CODE]        VARCHAR (50) NULL,
    [SUM_NAME]        VARCHAR (50) NULL,
    [SUM_VALUE]       FLOAT (53)   NULL,
    [SUM_Total_Value] FLOAT (53)   NULL,
    [SUM_ID]          VARCHAR (20) NULL,
    CONSTRAINT [PK_DHC_CUST_SUMMARY] PRIMARY KEY CLUSTERED ([SUM_PRIMARY] ASC)
);

