CREATE TABLE [dbo].[DHC_TBL_JCC_STOCKCLASSHISTORY] (
    [JSCH_PRIMARY]        BIGINT       IDENTITY (1, 1) NOT NULL,
    [JSCH_STOCKCODE]      VARCHAR (25) NOT NULL,
    [JSCH_CLASSIFICATION] VARCHAR (2)  NOT NULL,
    [JSCH_DATEINDEX_LINK] INT          NOT NULL,
    [JSCH_TRANS_FREQ]     FLOAT (53)   NULL,
    [JSCH_DEMAND_VAL]     FLOAT (53)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_DHC_TBL_JCC_STOCKCLASSHISTORY_JSCH_STOCKCODE]
    ON [dbo].[DHC_TBL_JCC_STOCKCLASSHISTORY]([JSCH_STOCKCODE] ASC)
    INCLUDE([JSCH_DATEINDEX_LINK]);


GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
    ON [dbo].[DHC_TBL_JCC_STOCKCLASSHISTORY]([JSCH_DATEINDEX_LINK] ASC)
    INCLUDE([JSCH_STOCKCODE], [JSCH_CLASSIFICATION], [JSCH_DEMAND_VAL]);

