CREATE TABLE [dbo].[DHC_BULK_RECEIPTS] (
    [BLK_PRIMARY]     INT          IDENTITY (1, 1) NOT NULL,
    [BLK_TRAN_CUST]   VARCHAR (10) NULL,
    [BLK_TRAN_TYPE]   VARCHAR (3)  NULL,
    [BLK_TRAN_PRIM]   FLOAT (53)   NULL,
    [BLK_TRAN_VALUE]  FLOAT (53)   NULL,
    [BLK_USER_PUTIN]  VARCHAR (10) NULL,
    [BLK_ALLOC_DIFF]  TINYINT      NULL,
    [BLK_UNALLOCFLAG] INT          CONSTRAINT [DF_DHC_BULK_RECEIPTS_BLK_UNALLOCFLAG] DEFAULT ((0)) NOT NULL
);

