CREATE TABLE [dbo].[DOC_LEDGER_HEADER] (
    [DLH_TRAN_LINK]        FLOAT (53)     DEFAULT ((0)) NULL,
    [DLH_PRIMARY]          INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [DLH_USER_ID]          VARCHAR (4)    NULL,
    [DLH_DOC_TYPE]         VARCHAR (3)    NULL,
    [DLH_DOC_DATE]         DATETIME       NULL,
    [DLH_TEXT]             VARCHAR (80)   NULL,
    [DLH_CHEQUE_NO]        VARCHAR (10)   NULL,
    [DLH_CHEQUE_VALUE]     FLOAT (53)     DEFAULT ((0)) NULL,
    [DLH_CHEQUE_WORD1]     VARCHAR (15)   NULL,
    [DLH_CHEQUE_WORD2]     VARCHAR (15)   NULL,
    [DLH_CHEQUE_WORD3]     VARCHAR (15)   NULL,
    [DLH_CHEQUE_WORD4]     VARCHAR (15)   NULL,
    [DLH_CHEQUE_WORD5]     VARCHAR (15)   NULL,
    [DLH_CHEQUE_WORD6]     VARCHAR (15)   NULL,
    [DLH_CHEQUE_WORD7]     VARCHAR (15)   NULL,
    [DLH_CHEQUE_WORD8]     VARCHAR (15)   NULL,
    [DLH_AGED_TITLE1]      VARCHAR (20)   NULL,
    [DLH_AGED_TITLE2]      VARCHAR (20)   NULL,
    [DLH_AGED_TITLE3]      VARCHAR (20)   NULL,
    [DLH_AGED_TITLE4]      VARCHAR (20)   NULL,
    [DLH_AGED_TITLE5]      VARCHAR (20)   NULL,
    [DLH_SYS_LINK]         FLOAT (53)     DEFAULT ((0)) NULL,
    [DLH_CURRSYMBOL]       VARCHAR (4)    NULL,
    [DLH_EXTRA_ADDRESS]    VARCHAR (250)  NULL,
    [DLH_OPTION1]          VARCHAR (3)    NULL,
    [DLH_OPTION2]          VARCHAR (3)    NULL,
    [DLH_FAX_HEADER]       TEXT           NULL,
    [DLH_COMP_ADDRESS]     TEXT           NULL,
    [DLH_CIS_MONTH_ENDING] DATETIME       NULL,
    [DLH_CIS_GROSS_PAID]   FLOAT (53)     DEFAULT ((0)) NULL,
    [DLH_CIS_CITB_LEVY]    FLOAT (53)     DEFAULT ((0)) NULL,
    [DLH_CIS_MATERIALS]    FLOAT (53)     DEFAULT ((0)) NULL,
    [DLH_CIS_TAX_WITHHELD] FLOAT (53)     DEFAULT ((0)) NULL,
    [DLH_CIS_TAX_PERCENT]  FLOAT (53)     DEFAULT ((0)) NULL,
    [DLH_FAX_FOOTER]       VARCHAR (2048) NULL,
    [DLH_DESTINATION]      VARCHAR (1)    NULL,
    CONSTRAINT [DLH_PRIMARY_PK] PRIMARY KEY CLUSTERED ([DLH_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DLH_USER_ID]
    ON [dbo].[DOC_LEDGER_HEADER]([DLH_USER_ID] ASC);

