CREATE TABLE [dbo].[ERR_LOG_LINK] (
    [ELL_HEADER_LINK]     INT DEFAULT ((0)) NULL,
    [ELL_SUB_HEADER_LINK] INT DEFAULT ((0)) NULL,
    [ELL_DETAIL_LINK]     INT DEFAULT ((0)) NULL,
    [ELL_TAG_LINK]        INT DEFAULT ((0)) NULL,
    [ELL_PRIMARY]         INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    CONSTRAINT [ELL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ELL_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ERR_LOG_LINK_CI]
    ON [dbo].[ERR_LOG_LINK]([ELL_HEADER_LINK] ASC, [ELL_SUB_HEADER_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_ERR_LOG_LINK_ELL_TAG_LINK]
    ON [dbo].[ERR_LOG_LINK]([ELL_TAG_LINK] ASC)
    INCLUDE([ELL_PRIMARY]);


GO
CREATE TRIGGER [dbo].[AA_ERR_LOG_INS_T]
    ON [dbo].[ERR_LOG_LINK]
    WITH ENCRYPTION
    AFTER INSERT
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

