CREATE TABLE [dbo].[ERR_LOG_HEADER] (
    [ELH_PRIMARY]        INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ELH_GENERATED_FROM] VARCHAR (128) NULL,
    [ELH_DATE]           DATETIME      NULL,
    [ELH_MODULE]         VARCHAR (3)   NULL,
    [ELH_HEADER_LINK]    INT           DEFAULT ((0)) NULL,
    [ELH_PROCESS_USERID] VARCHAR (4)   NULL,
    [ELH_ENTERED_USERID] VARCHAR (4)   NULL,
    [ELH_ACCOUNT_CODE]   VARCHAR (25)  NULL,
    CONSTRAINT [ELH_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ELH_PRIMARY] ASC)
);

