CREATE TABLE [dbo].[IR_APPROVER_GROUPS] (
    [IR_AG_PRIMARY]       INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [IR_AG_CODE]          VARCHAR (10) NOT NULL,
    [IR_AG_DESCRIPTION]   VARCHAR (40) NULL,
    [IR_AG_APPROVAL_TYPE] TINYINT      NOT NULL,
    [IR_AG_USER_PUTIN]    VARCHAR (4)  NOT NULL,
    [IR_AG_DATE_PUTIN]    DATETIME     DEFAULT (getdate()) NOT NULL,
    [IR_AG_USER_EDITED]   VARCHAR (4)  NULL,
    [IR_AG_DATE_EDITED]   DATETIME     NULL,
    [IR_AG_SOURCE]        VARCHAR (1)  NULL,
    CONSTRAINT [IR_AG_PRIMARY_PK] PRIMARY KEY CLUSTERED ([IR_AG_PRIMARY] ASC),
    CONSTRAINT [IR_AG_APPROVAL_TYPE_CK] CHECK ([IR_AG_APPROVAL_TYPE]>=(1) AND [IR_AG_APPROVAL_TYPE]<=(3))
);


GO
CREATE NONCLUSTERED INDEX [IR_AG_APPROVAL_TYPE]
    ON [dbo].[IR_APPROVER_GROUPS]([IR_AG_APPROVAL_TYPE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IR_AG_CODE]
    ON [dbo].[IR_APPROVER_GROUPS]([IR_AG_CODE] ASC);

