CREATE TABLE [dbo].[LANG_FAX_ERRORS] (
    [LANGCODE_FAX_ERRORS]        VARCHAR (10)  NOT NULL,
    [LFE_INVALID_SOFTWARE_LINK]  VARCHAR (185) NULL,
    [LFE_LABELS_NOT_DEFINED]     VARCHAR (35)  NULL,
    [LFE_NO_FAX_NUMBER]          VARCHAR (65)  NULL,
    [LFE_PRINT_DRIVER_NOT_FOUND] VARCHAR (115) NULL,
    [LFE_FAX_DISABLED]           VARCHAR (30)  NULL,
    CONSTRAINT [LANGCODE_FAX_ERRORS_PK] PRIMARY KEY CLUSTERED ([LANGCODE_FAX_ERRORS] ASC)
);

