CREATE TABLE [dbo].[LANG_PDF_ERRORS] (
    [LANGCODE_PDF_ERRORS]         VARCHAR (10)  NOT NULL,
    [LPDFE_CALL_FAILED]           VARCHAR (40)  NULL,
    [LPDFE_FAILED_TO_INITIALISE]  VARCHAR (45)  NULL,
    [LPDFE_DRIVER_UNRECOGNISED]   VARCHAR (140) NULL,
    [LPDFE_DRIVER_NOT_FOUND]      VARCHAR (100) NULL,
    [LPDFE_JOB_NOT_STARTED]       VARCHAR (55)  NULL,
    [LPDFE_JOB_ALREADY_STARTED]   VARCHAR (65)  NULL,
    [LPDFE_SELECT_PRINTER_FAILED] VARCHAR (80)  NULL,
    CONSTRAINT [LANGCODE_PDF_ERRORS_PK] PRIMARY KEY CLUSTERED ([LANGCODE_PDF_ERRORS] ASC)
);

