CREATE TABLE [dbo].[LANG_DOCUMENT2] (
    [LANGCODE_DOC2]          VARCHAR (10) NOT NULL,
    [SUPPLIES_TAX_DOC]       VARCHAR (11) NULL,
    [TOTAL_OVERDUE_DOC]      VARCHAR (16) NULL,
    [IF_YOU_PAY_DOC]         VARCHAR (13) NULL,
    [YOURSSINCERLY_DOC]      VARCHAR (50) NULL,
    [YOURSFAITHFLY_DOC]      VARCHAR (50) NULL,
    [ABOVE_BACS_PAID_DOC]    VARCHAR (45) NULL,
    [NOTIFICATION_STOCK_DOC] VARCHAR (40) NULL,
    CONSTRAINT [LANGCODE_DOC2_PK] PRIMARY KEY CLUSTERED ([LANGCODE_DOC2] ASC)
);

