CREATE TABLE [dbo].[LANG_FILE_ERRORS] (
    [LANGCODE_FILE_ERRORS]         VARCHAR (10) NOT NULL,
    [LFE_UNKNOWN_DEFAULT_EXP_LIST] VARCHAR (30) NULL,
    [LFE_UNKNOWN_OLD_EXP_CODE]     VARCHAR (30) NULL,
    [LFE_UNKNOWN_EXP_FORMAT]       VARCHAR (25) NULL,
    [LFE_NO_VALID_EXP_FORMATS]     VARCHAR (40) NULL,
    [LFE_INVALID_PATH]             VARCHAR (25) NULL,
    [LFE_INVALID_FILENAME]         VARCHAR (20) NULL,
    [LFE_CREATE_FOLDER_FAILED]     VARCHAR (25) NULL,
    [LFE_CREATE_FILE_FAILED]       VARCHAR (25) NULL,
    CONSTRAINT [LANGCODE_FILE_ERRORS_PK] PRIMARY KEY CLUSTERED ([LANGCODE_FILE_ERRORS] ASC)
);

