CREATE TABLE [dbo].[LANG_FILE_LABELS] (
    [LANGCODE_FILE_LABELS]           VARCHAR (10) NOT NULL,
    [LFL_EXPFMT_DELIMITED_COMMAS]    VARCHAR (25) NULL,
    [LFL_EXPFMT_DELIMTIED_TABS]      VARCHAR (20) NULL,
    [LFL_EXPFMT_ONE_FIELD_PER_LINE]  VARCHAR (25) NULL,
    [LFL_EXPFMT_OMNIS_DATA_TRANSFER] VARCHAR (30) NULL,
    [LFL_EXPFMT_SYLK]                VARCHAR (10) NULL,
    [LFL_EXPFMT_LOTUS]               VARCHAR (10) NULL,
    [LFL_EXPFMT_DIF]                 VARCHAR (10) NULL,
    [LFL_EXPFMT_DBASE]               VARCHAR (10) NULL,
    [LFL_EXPFMT_PDF]                 VARCHAR (30) NULL,
    [LFL_EXPFMT_XML]                 VARCHAR (40) NULL,
    CONSTRAINT [LANGCODE_FILE_LABELS_PK] PRIMARY KEY CLUSTERED ([LANGCODE_FILE_LABELS] ASC) WITH (FILLFACTOR = 70)
);

