CREATE TABLE [dbo].[LOG_SL_ADDRESSES] (
    [LOG_SADD_FILE_NO]  TINYINT       DEFAULT ((0)) NULL,
    [LOG_SADD_FIELD_NO] INT           DEFAULT ((0)) NULL,
    [LOG_SADD_DBASE_NO] INT           DEFAULT ((0)) NULL,
    [LOG_SADD_USER_ID]  VARCHAR (4)   NULL,
    [LOG_SADD_DATE]     DATETIME      NULL,
    [LOG_SADD_PARENT]   INT           DEFAULT ((0)) NULL,
    [LOG_SADD_PRIMARY]  INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [LOG_SADD_VALUE]    VARCHAR (250) NULL,
    [LOG_SADD_NOTES]    TEXT          NULL,
    CONSTRAINT [LOG_SADD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([LOG_SADD_PRIMARY] ASC)
);

