CREATE TABLE [dbo].[LOG_CONTROL] (
    [LOG_CONTROL_FILE]  VARCHAR (30) NOT NULL,
    [LOG_CONTROL_FIELD] INT          NOT NULL,
    CONSTRAINT [LOG_CONTROL_PK] PRIMARY KEY CLUSTERED ([LOG_CONTROL_FILE] ASC, [LOG_CONTROL_FIELD] ASC)
);

