CREATE TABLE [dbo].[NL_ACCOUNTS] (
    [NCODE]                  VARCHAR (25) NULL,
    [NNAME]                  VARCHAR (40) NULL,
    [NCURRENCYCODE]          VARCHAR (4)  NULL,
    [NTYPE]                  VARCHAR (1)  NULL,
    [NOPENBALMONTH]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NOPENBALYEAR]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NOPENBALMTH_C]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NOPENBALYR_C]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBALANCE]               FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVERPTD]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVERYTD]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVERLY]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBALANCE_C]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVRPTD_C]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVRYTD_C]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVRLY_C]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGETPTD]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGETYTD]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGETLY]              FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGETPTD_C]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGETYTD_C]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGETLY_C]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NCATEGORYCODE5]         VARCHAR (6)  NULL,
    [NCATEGORYCODE6]         VARCHAR (6)  NULL,
    [NCATEGORYCODE7]         VARCHAR (6)  NULL,
    [NCATEGORYCODE8]         VARCHAR (6)  NULL,
    [NNOTES]                 TEXT         NULL,
    [N_EXCLUDE_TRNREP]       TINYINT      DEFAULT ((0)) NULL,
    [N_COUNTRY_CODE]         VARCHAR (4)  NULL,
    [NYEAR_END_CODE]         VARCHAR (25) NULL,
    [NUSED]                  TINYINT      DEFAULT ((0)) NULL,
    [N_PROFILE_REC]          TINYINT      DEFAULT ((0)) NULL,
    [N_PROFILE_NL]           TINYINT      DEFAULT ((0)) NULL,
    [N_PROFILE_SL]           TINYINT      DEFAULT ((0)) NULL,
    [N_PROFILE_PL]           TINYINT      DEFAULT ((0)) NULL,
    [N_PROFILE_WARN]         TINYINT      DEFAULT ((0)) NULL,
    [N_RECON_COUNTER]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NRECONBALANCE]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NRECONBALANCE_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [N_INCOME]               FLOAT (53)   DEFAULT ((0)) NULL,
    [N_INCOME_C]             FLOAT (53)   DEFAULT ((0)) NULL,
    [N_EXPENSES]             FLOAT (53)   DEFAULT ((0)) NULL,
    [N_EXPENSES_C]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NOPENBALANCELY]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NOPENBALANCLY_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L1]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L2]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L3]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L4]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L5]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L6]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L7]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L8]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L9]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L10]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L11]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L12]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L13]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C1]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C2]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C3]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C4]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C5]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C6]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C7]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C8]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C9]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C10]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C11]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C12]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C13]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N1]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N2]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N3]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N4]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N5]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N6]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N7]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N8]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N9]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N10]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N11]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N12]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N13]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L1_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L2_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L3_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L4_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L5_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L6_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L7_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L8_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L9_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L10_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L11_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L12_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_L13_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C1_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C2_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C3_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C4_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C5_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C6_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C7_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C8_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C9_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C10_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C11_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C12_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_C13_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N1_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N2_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N3_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N4_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N5_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N6_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N7_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N8_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N9_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N10_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N11_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N12_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NTURNOVER_N13_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L1]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L2]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L3]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L4]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L5]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L6]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L7]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L8]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L9]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L10]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L11]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L12]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L13]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C1]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C2]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C3]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C4]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C5]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C6]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C7]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C8]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C9]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C10]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C11]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C12]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C13]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N1]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N2]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N3]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N4]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N5]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N6]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N7]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N8]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N9]             FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N10]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N11]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N12]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N13]            FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L1_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L2_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L3_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L4_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L5_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L6_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L7_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L8_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L9_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L10_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L11_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L12_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_L13_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C1_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C2_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C3_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C4_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C5_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C6_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C7_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C8_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C9_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C10_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C11_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C12_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_C13_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N1_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N2_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N3_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N4_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N5_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N6_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N7_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N8_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N9_O]           FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N10_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N11_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N12_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [NBUDGET_N13_O]          FLOAT (53)   DEFAULT ((0)) NULL,
    [N_USER_EDITED]          VARCHAR (4)  NULL,
    [N_USER_PUTIN]           VARCHAR (4)  NULL,
    [N_DATE_PUTIN]           DATETIME     NULL,
    [N_DATE_EDITED]          DATETIME     NULL,
    [N_MU_STATUS]            VARCHAR (1)  NULL,
    [NCATEGORYCODE4]         VARCHAR (6)  NULL,
    [NCOPY_ACCCODE]          VARCHAR (25) NULL,
    [NCATEGORYCODE1]         VARCHAR (6)  NULL,
    [NCATEGORYCODE2]         VARCHAR (6)  NULL,
    [NCATEGORYCODE3]         VARCHAR (6)  NULL,
    [NMAJORHEADCODE]         TINYINT      DEFAULT ((0)) NULL,
    [N_PRIMARY]              FLOAT (53)   NOT NULL,
    [N_LAST_STATEMENT]       FLOAT (53)   DEFAULT ((0)) NULL,
    [N_EXCLUDE_RECREP]       TINYINT      DEFAULT ((0)) NULL,
    [N_CENTRALISED]          TINYINT      DEFAULT ((0)) NULL,
    [N_VATNONDEDUCT]         FLOAT (53)   DEFAULT ((0)) NULL,
    [N_VATCODE]              VARCHAR (4)  NULL,
    [N_FORCE_COSTING]        TINYINT      DEFAULT ((0)) NULL,
    [N_SOURCE]               VARCHAR (1)  NULL,
    [N_USE_ZERO_BUDGET]      TINYINT      DEFAULT ((0)) NULL,
    [N_OVERDRAFT]            FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [N_DO_NOT_USE]           BIT          DEFAULT ((0)) NOT NULL,
    [N_EMISSIONS_GROUP_LINK] INT          NULL,
    [N_CLASSIFICATION_LINK]  INT          NULL,
    [N_ACCOUNT_FOR_CO2]      BIT          DEFAULT ((0)) NOT NULL,
    [N_DEFAULT_COSTCENTRE]   VARCHAR (10) DEFAULT ('') NOT NULL,
    [NREPORTING_CODE]        SMALLINT     NOT NULL,
    CONSTRAINT [N_PRIMARY_PK] PRIMARY KEY CLUSTERED ([N_PRIMARY] ASC),
    CONSTRAINT [N_ACCOUNT_FOR_CO2_CK] CHECK ([N_ACCOUNT_FOR_CO2]=(0) AND [N_EMISSIONS_GROUP_LINK] IS NULL AND [N_CLASSIFICATION_LINK] IS NULL OR [N_ACCOUNT_FOR_CO2]=(1) AND [N_EMISSIONS_GROUP_LINK] IS NOT NULL),
    CONSTRAINT [N_CLASSIFICATION_LINK_FK] FOREIGN KEY ([N_EMISSIONS_GROUP_LINK], [N_CLASSIFICATION_LINK]) REFERENCES [dbo].[CO2_CLASSIFICATIONS] ([CCLS_GROUP_LINK], [CCLS_PRIMARY]),
    CONSTRAINT [N_EMISSIONS_GROUP_LINK_FK] FOREIGN KEY ([N_EMISSIONS_GROUP_LINK]) REFERENCES [dbo].[CO2_EMISSIONS_GROUPS] ([CGRP_PRIMARY]),
    CONSTRAINT [NREPORTING_CODE_FK] FOREIGN KEY ([NREPORTING_CODE]) REFERENCES [dbo].[NL_REPORTING_CODES] ([NRC_CODE])
);


GO
CREATE NONCLUSTERED INDEX [NCATEGORYCODE1]
    ON [dbo].[NL_ACCOUNTS]([NCATEGORYCODE1] ASC, [NMAJORHEADCODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [NCATEGORYCODE2]
    ON [dbo].[NL_ACCOUNTS]([NCATEGORYCODE2] ASC, [NMAJORHEADCODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [NCATEGORYCODE3]
    ON [dbo].[NL_ACCOUNTS]([NCATEGORYCODE3] ASC, [NMAJORHEADCODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [NCATEGORYCODE4]
    ON [dbo].[NL_ACCOUNTS]([NCATEGORYCODE4] ASC, [NMAJORHEADCODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [NCATEGORYCODE5]
    ON [dbo].[NL_ACCOUNTS]([NCATEGORYCODE5] ASC, [NMAJORHEADCODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [NCATEGORYCODE6]
    ON [dbo].[NL_ACCOUNTS]([NCATEGORYCODE6] ASC, [NMAJORHEADCODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [NCATEGORYCODE7]
    ON [dbo].[NL_ACCOUNTS]([NCATEGORYCODE7] ASC, [NMAJORHEADCODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [NCATEGORYCODE8]
    ON [dbo].[NL_ACCOUNTS]([NCATEGORYCODE8] ASC, [NMAJORHEADCODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NCODE]
    ON [dbo].[NL_ACCOUNTS]([NCODE] ASC);


GO
CREATE NONCLUSTERED INDEX [NCURRENCYCODE]
    ON [dbo].[NL_ACCOUNTS]([NCURRENCYCODE] ASC);


GO
CREATE NONCLUSTERED INDEX [NMAJORHEADCODE]
    ON [dbo].[NL_ACCOUNTS]([NMAJORHEADCODE] ASC);


GO
CREATE NONCLUSTERED INDEX [NNAME]
    ON [dbo].[NL_ACCOUNTS]([NNAME] ASC);


GO
CREATE NONCLUSTERED INDEX [NTYPE]
    ON [dbo].[NL_ACCOUNTS]([NTYPE] ASC);


GO
CREATE NONCLUSTERED INDEX [NREPORTING_CODE]
    ON [dbo].[NL_ACCOUNTS]([NREPORTING_CODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE TRIGGER [dbo].[aa_nl_acc_dt]
    ON [dbo].[NL_ACCOUNTS]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


GO
CREATE TRIGGER [dbo].[AA_NL_NCODE_UPD_T]
    ON [dbo].[NL_ACCOUNTS]
    WITH ENCRYPTION
    AFTER UPDATE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

