CREATE TABLE [dbo].[NL_ATTRIBUTE_VALUES_TEMP] (
    [NATVT_ID]                      INT          NOT NULL,
    [NATVT_ATTRIBUTE_VALUE_ORDER]   INT          NULL,
    [NATVT_ATTRIBUTE_VALUE_CODE]    VARCHAR (10) NULL,
    [NATVT_ATTRIBUTE_VALUE_NAME]    VARCHAR (30) NULL,
    [NATVT_ATTRIBUTE_VALUE_PRIMARY] INT          NULL,
    [NATVT_DEFAULT_ORDER]           INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    CONSTRAINT [NL_ATTRIBUTE_VALUES_TEMP_PK] PRIMARY KEY CLUSTERED ([NATVT_ID] ASC, [NATVT_DEFAULT_ORDER] ASC) WITH (FILLFACTOR = 70)
);

