CREATE TABLE [dbo].[NL_ATTRIBUTE_LINKS_TEMP] (
    [NALT_ID]                      INT          NOT NULL,
    [NALT_ORDER]                   INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [NALT_ATTRIBUTE_VALUE_PRIMARY] INT          NULL,
    [NALT_ATTRIBUTE_VALUE_CODE]    VARCHAR (10) NULL,
    [NALT_ATTRIBUTE_TYPE_CODE]     VARCHAR (15) NULL,
    CONSTRAINT [NL_ATTRIBUTE_LINKS_TEMP_PK] PRIMARY KEY CLUSTERED ([NALT_ID] ASC, [NALT_ORDER] ASC) WITH (FILLFACTOR = 70)
);

