CREATE TABLE [dbo].[NL_ATTRIBUTE_VALUE_LINKS] (
    [NAVL_ATTRIBUTE_SOURCE_TYPE_LINK]  INT NOT NULL,
    [NAVL_ATTRIBUTE_SOURCE_VALUE_LINK] INT NOT NULL,
    [NAVL_ATTRIBUTE_LINKED_TYPE_LINK]  INT NOT NULL,
    [NAVL_ATTRIBUTE_LINKED_VALUE_LINK] INT NOT NULL,
    CONSTRAINT [NL_ATTRIBUTE_VALUE_LINKS_PK] PRIMARY KEY CLUSTERED ([NAVL_ATTRIBUTE_SOURCE_VALUE_LINK] ASC, [NAVL_ATTRIBUTE_LINKED_VALUE_LINK] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [NAVL_ATTRIBUTE_LINKED_VALUE_LINK_FK] FOREIGN KEY ([NAVL_ATTRIBUTE_LINKED_VALUE_LINK], [NAVL_ATTRIBUTE_LINKED_TYPE_LINK]) REFERENCES [dbo].[NL_ATTRIBUTE_VALUES] ([NATV_PRIMARY], [NATV_ATTRIBUTE_TYPE_LINK]),
    CONSTRAINT [NAVL_ATTRIBUTE_SOURCE_VALUE_LINK_FK] FOREIGN KEY ([NAVL_ATTRIBUTE_SOURCE_VALUE_LINK], [NAVL_ATTRIBUTE_SOURCE_TYPE_LINK]) REFERENCES [dbo].[NL_ATTRIBUTE_VALUES] ([NATV_PRIMARY], [NATV_ATTRIBUTE_TYPE_LINK]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [NAVL_ATTRIBUTE_LINKED_VALUE_LINK]
    ON [dbo].[NL_ATTRIBUTE_VALUE_LINKS]([NAVL_ATTRIBUTE_LINKED_VALUE_LINK] ASC) WITH (FILLFACTOR = 70);

