CREATE TABLE [dbo].[NL_ATTRIBUTE_CATEGORY_LINKS] (
    [NACL_ATTRIBUTE_VALUE_LINK] INT     NOT NULL,
    [NACL_ATTRIBUTE_TYPE_LINK]  INT     NOT NULL,
    [NACL_CATEGORY_LINK]        INT     NOT NULL,
    [NACL_CATEGORY_NUMBER]      TINYINT NOT NULL,
    CONSTRAINT [NL_ATTRIBUTE_CATEGORY_LINK_PK] PRIMARY KEY CLUSTERED ([NACL_ATTRIBUTE_VALUE_LINK] ASC, [NACL_CATEGORY_LINK] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [NACL_CATEGORY_NUMBER_CK] CHECK ([NACL_CATEGORY_NUMBER] IS NULL OR [NACL_CATEGORY_NUMBER]>=(1) AND [NACL_CATEGORY_NUMBER]<=(8)),
    CONSTRAINT [NACL_ATTRIBUTE_TYPE_LINK_FK] FOREIGN KEY ([NACL_ATTRIBUTE_TYPE_LINK], [NACL_CATEGORY_NUMBER]) REFERENCES [dbo].[NL_ATTRIBUTE_TYPES] ([NATT_PRIMARY], [NATT_CATEGORY_NUMBER]),
    CONSTRAINT [NACL_ATTRIBUTE_VALUE_LINK_FK] FOREIGN KEY ([NACL_ATTRIBUTE_VALUE_LINK], [NACL_ATTRIBUTE_TYPE_LINK]) REFERENCES [dbo].[NL_ATTRIBUTE_VALUES] ([NATV_PRIMARY], [NATV_ATTRIBUTE_TYPE_LINK]) ON DELETE CASCADE,
    CONSTRAINT [NACL_CATEGORY_LINK_FK] FOREIGN KEY ([NACL_CATEGORY_LINK], [NACL_CATEGORY_NUMBER]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_PRIMARY], [NCAT_NUMBER]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NACL_CATEGORY_LINK]
    ON [dbo].[NL_ATTRIBUTE_CATEGORY_LINKS]([NACL_CATEGORY_LINK] ASC, [NACL_ATTRIBUTE_TYPE_LINK] ASC) WITH (FILLFACTOR = 70);

