CREATE TABLE [dbo].[NL_ACCOUNTS2] (
    [N_PRIMARY_2]        FLOAT (53)    NOT NULL,
    [N_CHAR1]            VARCHAR (20)  NULL,
    [N_CHAR2]            VARCHAR (20)  NULL,
    [N_CHAR3]            VARCHAR (100) NULL,
    [N_CHAR4]            VARCHAR (100) NULL,
    [N_FLAG1]            TINYINT       DEFAULT ((0)) NULL,
    [N_FLAG2]            TINYINT       DEFAULT ((0)) NULL,
    [N_DATE1]            DATETIME      NULL,
    [N_DATE2]            DATETIME      NULL,
    [N_NUM1]             FLOAT (53)    DEFAULT ((0)) NULL,
    [N_NUM2]             FLOAT (53)    DEFAULT ((0)) NULL,
    [N_USRCHAR1]         VARCHAR (20)  NULL,
    [N_USRCHAR2]         VARCHAR (20)  NULL,
    [N_USRCHAR3]         VARCHAR (100) NULL,
    [N_USRCHAR4]         VARCHAR (100) NULL,
    [N_USRFLAG1]         TINYINT       DEFAULT ((0)) NULL,
    [N_USRFLAG2]         TINYINT       DEFAULT ((0)) NULL,
    [N_USRDATE1]         DATETIME      NULL,
    [N_USRDATE2]         DATETIME      NULL,
    [N_USRNUM1]          FLOAT (53)    DEFAULT ((0)) NULL,
    [N_USRNUM2]          FLOAT (53)    DEFAULT ((0)) NULL,
    [NCODE2]             VARCHAR (25)  NULL,
    [N_USRCHAR5]         VARCHAR (20)  NULL,
    [N_USRCHAR6]         VARCHAR (30)  NULL,
    [N_USRFLAG3]         TINYINT       DEFAULT ((0)) NULL,
    [N_USRDATE3]         DATETIME      NULL,
    [N_USRNUM3]          FLOAT (53)    DEFAULT ((0)) NULL,
    [N_USRCHAR7]         VARCHAR (30)  NULL,
    [N_USRCHAR8]         VARCHAR (30)  NULL,
    [N_STATS_TOTAL_HOME] FLOAT (53)    DEFAULT ((0)) NULL,
    [N_STATS_TOTAL_EURO] FLOAT (53)    DEFAULT ((0)) NULL,
    [N_BUDGET_HOLDER]    VARCHAR (4)   NULL,
    [N_INSERT_MODULE]    VARCHAR (1)   NULL,
    [N_LEVEL]            INT           DEFAULT ((0)) NULL,
    [N_GROUP]            VARCHAR (10)  NULL,
    [N_PROFILE_BUDGET]   TINYINT       DEFAULT ((0)) NULL,
    [N_DRCR_TYPE]        TINYINT       DEFAULT ((0)) NULL,
    [N_TAXCODE_DR]       VARCHAR (4)   NULL,
    [N_TAXCODE_CR]       VARCHAR (4)   NULL,
    CONSTRAINT [N_PRIMARY_2_PK] PRIMARY KEY CLUSTERED ([N_PRIMARY_2] ASC)
);

