CREATE TABLE [dbo].[NL_BANK_DETAILS] (
    [N_BD_PRIMARY]               INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [N_BD_NL_ACCOUNT_LINK]       FLOAT (53)    NOT NULL,
    [N_BD_NAME]                  VARCHAR (25)  NULL,
    [N_BD_ADDRESS]               VARCHAR (160) NULL,
    [N_BD_TOWN]                  VARCHAR (30)  NULL,
    [N_BD_COUNTY]                VARCHAR (30)  NULL,
    [N_BD_POSTCODE]              VARCHAR (12)  NULL,
    [N_BD_COUNTRY]               VARCHAR (35)  NULL,
    [N_BD_PHONE]                 VARCHAR (20)  NULL,
    [N_BD_FAX]                   VARCHAR (20)  NULL,
    [N_BD_CONTACT]               VARCHAR (30)  NULL,
    [N_BD_BACS_LAYOUT]           TINYINT       NULL,
    [N_BD_BANK_REF]              INT           NULL,
    [N_BD_REMIT_ADVICE]          BIT           DEFAULT ((0)) NOT NULL,
    [N_BD_SORT]                  VARCHAR (10)  NULL,
    [N_BD_AC_NO]                 VARCHAR (15)  NULL,
    [N_BD_AC_NAME]               VARCHAR (25)  NULL,
    [N_BD_AC_DESC]               VARCHAR (40)  NULL,
    [N_BD_AC_IBAN_NO]            VARCHAR (34)  NULL,
    [N_BD_AC_SWIFT_CODE]         VARCHAR (11)  NULL,
    [N_BD_AC_BACSREF]            VARCHAR (18)  NULL,
    [N_BD_DD_CREDITOR_SCHEME_ID] VARCHAR (35)  NULL,
    CONSTRAINT [N_BD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([N_BD_PRIMARY] ASC),
    CONSTRAINT [N_BD_AC_NO_CK] CHECK ([N_BD_AC_NO] IS NOT NULL),
    CONSTRAINT [N_BD_AC_SWIFT_CODE_CK] CHECK (len(isnull([N_BD_AC_SWIFT_CODE],''))=(11) OR len(isnull([N_BD_AC_SWIFT_CODE],''))=(8) OR len(isnull([N_BD_AC_SWIFT_CODE],''))=(0)),
    CONSTRAINT [N_BD_NAME_CK] CHECK ([N_BD_NAME] IS NOT NULL),
    CONSTRAINT [N_BD_NL_ACCOUNT_LINK_FK] FOREIGN KEY ([N_BD_NL_ACCOUNT_LINK]) REFERENCES [dbo].[NL_ACCOUNTS] ([N_PRIMARY]) ON DELETE CASCADE
);

