CREATE TABLE [dbo].[NL_BANK_TRNS] (
    [BANK_COPYNCODE]              VARCHAR (25) NULL,
    [BANK_STMNT_DATE]             DATETIME     NULL,
    [BANK_STMNT_BEGINVAL]         FLOAT (53)   DEFAULT ((0)) NULL,
    [BANK_STMNT_ENDVAL]           FLOAT (53)   DEFAULT ((0)) NULL,
    [BANK_STMNT_NUMBER]           VARCHAR (10) NULL,
    [BANK_USER_PUTIN]             VARCHAR (4)  NULL,
    [BANK_USER_EDITED]            VARCHAR (4)  NULL,
    [BANK_DATE_PUTIN]             DATETIME     NULL,
    [BANK_DATE_EDITED]            DATETIME     NULL,
    [BANK_EXCHANGE_RATE]          FLOAT (53)   DEFAULT ((0)) NULL,
    [BANK_PERIOD]                 TINYINT      DEFAULT ((0)) NULL,
    [BANK_YEAR]                   VARCHAR (1)  NULL,
    [BANK_PRIMARY]                FLOAT (53)   NOT NULL,
    [BANK_CURRENCYSYMBOL]         VARCHAR (4)  NULL,
    [BANK_SUM_OF_RECONCILED]      FLOAT (53)   DEFAULT ((0)) NULL,
    [BANK_SUM_OF_RECONCILED_C]    FLOAT (53)   DEFAULT ((0)) NULL,
    [BANK_OPENING_RECONBALANCE]   FLOAT (53)   DEFAULT ((0)) NULL,
    [BANK_OPENING_RECONBALANCE_C] FLOAT (53)   DEFAULT ((0)) NULL,
    [BANK_STMNT_ENDVAL_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [BANK_RECON_COUNTER]          INT          NULL,
    [BANK_YEAR_LINK]              SMALLINT     NULL,
    CONSTRAINT [BANK_PRIMARY_PK] PRIMARY KEY CLUSTERED ([BANK_PRIMARY] ASC),
    CONSTRAINT [BANK_YEAR_LINK_CK] CHECK ([BANK_YEAR] IS NOT NULL AND (upper([BANK_YEAR])='O' OR upper([BANK_YEAR])='N' OR upper([BANK_YEAR])='C' OR upper([BANK_YEAR])='L') AND [BANK_YEAR_LINK] IS NOT NULL OR ([BANK_YEAR] IS NULL OR (upper([BANK_YEAR])='O' OR upper([BANK_YEAR])='')) AND [BANK_YEAR_LINK] IS NULL),
    CONSTRAINT [BANK_YEAR_LINK_FK] FOREIGN KEY ([BANK_YEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [BANK_STMNT]
    ON [dbo].[NL_BANK_TRNS]([BANK_COPYNCODE] ASC, [BANK_STMNT_NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_NL_BANK_TRNS_BANK_RECON_COUNTER_BANK_COPYNCODE]
    ON [dbo].[NL_BANK_TRNS]([BANK_RECON_COUNTER] ASC, [BANK_COPYNCODE] ASC);

