CREATE TABLE [dbo].[NL_CATEGORY_TEMP] (
    [NLCT_ID]               INT          NOT NULL,
    [NLCT_LINE_NO]          INT          NOT NULL,
    [NLCT_ACTION]           VARCHAR (1)  NULL,
    [NLCT_SOURCE]           VARCHAR (1)  NULL,
    [NLCT_DEFAULT_STRING]   VARCHAR (20) NULL,
    [NLCT_CATEGORY_NO]      TINYINT      NULL,
    [NLCT_CATEGORY_CODE]    VARCHAR (6)  NULL,
    [NLCT_CATEGORY_NAME]    VARCHAR (50) NULL,
    [NLCT_CAT_SHORT_NAME]   VARCHAR (10) NULL,
    [NLCT_STATUS]           TINYINT      NULL,
    [NLCT_CATEGORY_PRIMARY] INT          NULL,
    CONSTRAINT [NL_CATEGORY_TEMP_PK] PRIMARY KEY CLUSTERED ([NLCT_ID] ASC, [NLCT_LINE_NO] ASC)
);

