CREATE TABLE [dbo].[NL_CATEGORY_LANG] (
    [NCATLANG_LANGCODE]  VARCHAR (10) NOT NULL,
    [NCATLANG_CODE]      VARCHAR (6)  NOT NULL,
    [NCATLANG_SHORTNAME] VARCHAR (10) NULL,
    [NCATLANG_LONGNAME]  VARCHAR (50) NULL,
    [NCATLANG_NUMBER]    TINYINT      DEFAULT ((0)) NULL,
    CONSTRAINT [NL_CATEGORY_LANG_PK] PRIMARY KEY CLUSTERED ([NCATLANG_LANGCODE] ASC, [NCATLANG_CODE] ASC)
);

