CREATE TABLE [dbo].[NL_CHART_OF_ACCOUNTS] (
    [NCOA_PRIMARY]                     INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [NCOA_ORDER]                       INT         NOT NULL,
    [NCOA_PARENT_NODE]                 BIT         DEFAULT ((0)) NOT NULL,
    [NCOA_CURR_SYMBOL]                 VARCHAR (4) NULL,
    [NCOA_NOM_CAT1_CODE]               VARCHAR (6) NULL,
    [NCOA_NOM_CAT2_CODE]               VARCHAR (6) NULL,
    [NCOA_NOM_CAT3_CODE]               VARCHAR (6) NULL,
    [NCOA_NOM_CAT4_CODE]               VARCHAR (6) NULL,
    [NCOA_NOM_CAT5_CODE]               VARCHAR (6) NULL,
    [NCOA_NOM_CAT6_CODE]               VARCHAR (6) NULL,
    [NCOA_NOM_CAT7_CODE]               VARCHAR (6) NULL,
    [NCOA_NOM_CAT8_CODE]               VARCHAR (6) NULL,
    [NCOA_NL_ACCOUNT_LINK]             FLOAT (53)  NULL,
    [NCOA_UPDATE_PROFILE_NL]           BIT         DEFAULT ((0)) NOT NULL,
    [NCOA_UPDATE_PROFILE_SL]           BIT         DEFAULT ((0)) NOT NULL,
    [NCOA_UPDATE_PROFILE_PL]           BIT         DEFAULT ((0)) NOT NULL,
    [NCOA_PROFILE_WARN_BEFORE_POSTING] BIT         DEFAULT ((0)) NOT NULL,
    [NCOA_NOM_CAT1_NUMBER]             AS          (CONVERT([tinyint],(1),0)) PERSISTED,
    [NCOA_NOM_CAT2_NUMBER]             AS          (CONVERT([tinyint],(2),0)) PERSISTED,
    [NCOA_NOM_CAT3_NUMBER]             AS          (CONVERT([tinyint],(3),0)) PERSISTED,
    [NCOA_NOM_CAT4_NUMBER]             AS          (CONVERT([tinyint],(4),0)) PERSISTED,
    [NCOA_NOM_CAT5_NUMBER]             AS          (CONVERT([tinyint],(5),0)) PERSISTED,
    [NCOA_NOM_CAT6_NUMBER]             AS          (CONVERT([tinyint],(6),0)) PERSISTED,
    [NCOA_NOM_CAT7_NUMBER]             AS          (CONVERT([tinyint],(7),0)) PERSISTED,
    [NCOA_NOM_CAT8_NUMBER]             AS          (CONVERT([tinyint],(8),0)) PERSISTED,
    CONSTRAINT [NCOA_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NCOA_PRIMARY] ASC),
    CONSTRAINT [NCOA_NOM_CAT1_CODE_CK] CHECK ([NCOA_NOM_CAT1_CODE] IS NULL OR [NCOA_NOM_CAT1_CODE]<>''),
    CONSTRAINT [NCOA_NOM_CAT2_CODE_CK] CHECK ([NCOA_NOM_CAT1_CODE] IS NULL OR [NCOA_NOM_CAT1_CODE]<>''),
    CONSTRAINT [NCOA_NOM_CAT3_CODE_CK] CHECK ([NCOA_NOM_CAT1_CODE] IS NULL OR [NCOA_NOM_CAT1_CODE]<>''),
    CONSTRAINT [NCOA_NOM_CAT4_CODE_CK] CHECK ([NCOA_NOM_CAT1_CODE] IS NULL OR [NCOA_NOM_CAT1_CODE]<>''),
    CONSTRAINT [NCOA_NOM_CAT5_CODE_CK] CHECK ([NCOA_NOM_CAT1_CODE] IS NULL OR [NCOA_NOM_CAT1_CODE]<>''),
    CONSTRAINT [NCOA_NOM_CAT6_CODE_CK] CHECK ([NCOA_NOM_CAT1_CODE] IS NULL OR [NCOA_NOM_CAT1_CODE]<>''),
    CONSTRAINT [NCOA_NOM_CAT7_CODE_CK] CHECK ([NCOA_NOM_CAT1_CODE] IS NULL OR [NCOA_NOM_CAT1_CODE]<>''),
    CONSTRAINT [NCOA_NOM_CAT8_CODE_CK] CHECK ([NCOA_NOM_CAT1_CODE] IS NULL OR [NCOA_NOM_CAT1_CODE]<>''),
    CONSTRAINT [NCOA_CURR_SYMBOL_FK] FOREIGN KEY ([NCOA_CURR_SYMBOL]) REFERENCES [dbo].[SYS_CURRENCY_REC] ([CURREC_SYMBOL]),
    CONSTRAINT [NCOA_NL_ACCOUNT_LINK_FK] FOREIGN KEY ([NCOA_NL_ACCOUNT_LINK]) REFERENCES [dbo].[NL_ACCOUNTS] ([N_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [NCOA_NOM_CAT1_CODE_FK] FOREIGN KEY ([NCOA_NOM_CAT1_NUMBER], [NCOA_NOM_CAT1_CODE]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_NUMBER], [NCAT_CODE]),
    CONSTRAINT [NCOA_NOM_CAT2_CODE_FK] FOREIGN KEY ([NCOA_NOM_CAT2_NUMBER], [NCOA_NOM_CAT2_CODE]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_NUMBER], [NCAT_CODE]),
    CONSTRAINT [NCOA_NOM_CAT3_CODE_FK] FOREIGN KEY ([NCOA_NOM_CAT3_NUMBER], [NCOA_NOM_CAT3_CODE]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_NUMBER], [NCAT_CODE]),
    CONSTRAINT [NCOA_NOM_CAT4_CODE_FK] FOREIGN KEY ([NCOA_NOM_CAT4_NUMBER], [NCOA_NOM_CAT4_CODE]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_NUMBER], [NCAT_CODE]),
    CONSTRAINT [NCOA_NOM_CAT5_CODE_FK] FOREIGN KEY ([NCOA_NOM_CAT5_NUMBER], [NCOA_NOM_CAT5_CODE]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_NUMBER], [NCAT_CODE]),
    CONSTRAINT [NCOA_NOM_CAT6_CODE_FK] FOREIGN KEY ([NCOA_NOM_CAT6_NUMBER], [NCOA_NOM_CAT6_CODE]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_NUMBER], [NCAT_CODE]),
    CONSTRAINT [NCOA_NOM_CAT7_CODE_FK] FOREIGN KEY ([NCOA_NOM_CAT7_NUMBER], [NCOA_NOM_CAT7_CODE]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_NUMBER], [NCAT_CODE]),
    CONSTRAINT [NCOA_NOM_CAT8_CODE_FK] FOREIGN KEY ([NCOA_NOM_CAT8_NUMBER], [NCOA_NOM_CAT8_CODE]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_NUMBER], [NCAT_CODE])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NL_CHART_OF_ACCOUNTS_CURRENCY_CAT_CODES]
    ON [dbo].[NL_CHART_OF_ACCOUNTS]([NCOA_CURR_SYMBOL] ASC, [NCOA_NOM_CAT1_CODE] ASC, [NCOA_NOM_CAT2_CODE] ASC, [NCOA_NOM_CAT3_CODE] ASC, [NCOA_NOM_CAT4_CODE] ASC, [NCOA_NOM_CAT5_CODE] ASC, [NCOA_NOM_CAT6_CODE] ASC, [NCOA_NOM_CAT7_CODE] ASC, [NCOA_NOM_CAT8_CODE] ASC)
    INCLUDE([NCOA_NL_ACCOUNT_LINK]) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NL_CHART_OF_ACCOUNTS_CURRENCY_ORDER]
    ON [dbo].[NL_CHART_OF_ACCOUNTS]([NCOA_CURR_SYMBOL] ASC, [NCOA_ORDER] ASC);


GO
CREATE NONCLUSTERED INDEX [NCOA_NL_ACCOUNT_LINK]
    ON [dbo].[NL_CHART_OF_ACCOUNTS]([NCOA_NL_ACCOUNT_LINK] ASC) WITH (FILLFACTOR = 70);

