CREATE TABLE [dbo].[NL_COMMITTED_BUDGETS] (
    [NLC_CODE]      VARCHAR (25) NULL,
    [NLC_YEAR]      VARCHAR (1)  NULL,
    [NLC_PERIOD]    TINYINT      DEFAULT ((0)) NULL,
    [NLC_BUDGET]    FLOAT (53)   DEFAULT ((0)) NULL,
    [NLC_PRIMARY]   INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [NLC_YEAR_LINK] SMALLINT     NULL,
    CONSTRAINT [NLC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NLC_PRIMARY] ASC),
    CONSTRAINT [NLC_YEAR_LINK_CK] CHECK ([NLC_YEAR] IS NOT NULL AND (upper([NLC_YEAR])='O' OR upper([NLC_YEAR])='N' OR upper([NLC_YEAR])='C' OR upper([NLC_YEAR])='L') AND [NLC_YEAR_LINK] IS NOT NULL OR ([NLC_YEAR] IS NULL OR (upper([NLC_YEAR])='O' OR upper([NLC_YEAR])='')) AND [NLC_YEAR_LINK] IS NULL),
    CONSTRAINT [NLC_YEAR_LINK_FK] FOREIGN KEY ([NLC_YEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [NLC_CODE]
    ON [dbo].[NL_COMMITTED_BUDGETS]([NLC_CODE] ASC, [NLC_YEAR] ASC, [NLC_PERIOD] ASC)
    INCLUDE([NLC_BUDGET]);

