CREATE TABLE [dbo].[NL_CATEGORY_DEFAULTS] (
    [NCD_PRIMARY]           INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [NCD_CODE]              VARCHAR (6) NOT NULL,
    [NCD_CATEGORY_DEFAULTS] VARCHAR (8) NOT NULL,
    CONSTRAINT [NCD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NCD_PRIMARY] ASC),
    CONSTRAINT [NCD_CATEGORY_DEFAULTS_CK] CHECK (patindex('%[^012]%',[NCD_CATEGORY_DEFAULTS])=(0)),
    CONSTRAINT [NCD_CODE_CK] CHECK ([NCD_CODE]='POCRNS' OR [NCD_CODE]='POCRNO' OR [NCD_CODE]='POORDS' OR [NCD_CODE]='POORDO' OR [NCD_CODE]='SOCRNS' OR [NCD_CODE]='SOCRNO' OR [NCD_CODE]='SOORDS' OR [NCD_CODE]='SOORDO' OR [NCD_CODE]='SKMOV' OR [NCD_CODE]='PLACR' OR [NCD_CODE]='PLADR' OR [NCD_CODE]='PLPAY' OR [NCD_CODE]='PLCRN' OR [NCD_CODE]='PLINV' OR [NCD_CODE]='SLACR' OR [NCD_CODE]='SLADR' OR [NCD_CODE]='SLPAY' OR [NCD_CODE]='SLCRN' OR [NCD_CODE]='SLINV')
);

