CREATE TABLE [dbo].[NL_CATEGORIES] (
    [NCAT_PRIMARY]              INT          NOT NULL,
    [NCAT_CODE]                 VARCHAR (6)  NOT NULL,
    [NCAT_NAME]                 VARCHAR (50) NULL,
    [NCAT_SHORTNAME]            VARCHAR (10) NULL,
    [NCAT_NUMBER]               TINYINT      NOT NULL,
    [NCAT_USED]                 BIT          DEFAULT ((0)) NOT NULL,
    [NCAT_DRCR_TYPE]            TINYINT      DEFAULT ((0)) NULL,
    [NCAT_MAJOR_HEADING]        TINYINT      NULL,
    [NCAT_TAXCODE_DR]           VARCHAR (4)  NULL,
    [NCAT_TAXCODE_CR]           VARCHAR (4)  NULL,
    [NCAT_LEVEL]                INT          DEFAULT ((0)) NULL,
    [NCAT_CURR_SYMBOL]          VARCHAR (4)  NULL,
    [NCAT_BANK_ACCOUNT]         BIT          DEFAULT ((0)) NOT NULL,
    [NCAT_PETTY_CASH_ACCOUNT]   BIT          DEFAULT ((0)) NOT NULL,
    [NCAT_COMPULSORY_COSTING]   BIT          DEFAULT ((0)) NOT NULL,
    [NCAT_ACCOUNT_FOR_CO2]      BIT          DEFAULT ((0)) NOT NULL,
    [NCAT_EMISSIONS_GROUP_LINK] INT          NULL,
    [NCAT_CLASSIFICATION_LINK]  INT          NULL,
    [NCAT_INACTIVE]             BIT          DEFAULT ((0)) NOT NULL,
    [NCAT_SORT]                 VARCHAR (20) NULL,
    [NCAT_REPORTING_CODE]       SMALLINT     NULL,
    CONSTRAINT [NCAT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NCAT_PRIMARY] ASC),
    CONSTRAINT [NCAT_ACCOUNT_FOR_CO2_CK] CHECK ([NCAT_ACCOUNT_FOR_CO2]=(1) AND [NCAT_EMISSIONS_GROUP_LINK] IS NOT NULL AND ([NCAT_MAJOR_HEADING]>=(1) AND [NCAT_MAJOR_HEADING]<=(6)) OR [NCAT_ACCOUNT_FOR_CO2]=(0) AND [NCAT_EMISSIONS_GROUP_LINK] IS NULL AND [NCAT_CLASSIFICATION_LINK] IS NULL),
    CONSTRAINT [NCAT_BANK_CASH_ACCOUNT_CK] CHECK (([NCAT_BANK_ACCOUNT]&[NCAT_PETTY_CASH_ACCOUNT])=(0)),
    CONSTRAINT [NCAT_NUMBER_CK] CHECK ([NCAT_NUMBER]>=(1) AND [NCAT_NUMBER]<=(8)),
    CONSTRAINT [NCAT_CLASSIFICATION_LINK_FK] FOREIGN KEY ([NCAT_EMISSIONS_GROUP_LINK], [NCAT_CLASSIFICATION_LINK]) REFERENCES [dbo].[CO2_CLASSIFICATIONS] ([CCLS_GROUP_LINK], [CCLS_PRIMARY]),
    CONSTRAINT [NCAT_EMISSIONS_GROUP_LINK_FK] FOREIGN KEY ([NCAT_EMISSIONS_GROUP_LINK]) REFERENCES [dbo].[CO2_EMISSIONS_GROUPS] ([CGRP_PRIMARY]),
    CONSTRAINT [NCAT_MAJOR_HEADING_FK] FOREIGN KEY ([NCAT_MAJOR_HEADING]) REFERENCES [dbo].[NL_MAJORHEADING] ([NL_MAJORCODE]),
    CONSTRAINT [NCAT_REPORTING_CODE_FK] FOREIGN KEY ([NCAT_REPORTING_CODE]) REFERENCES [dbo].[NL_REPORTING_CODES] ([NRC_CODE])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NL_CATEGORIES_NUMBER_CODE]
    ON [dbo].[NL_CATEGORIES]([NCAT_NUMBER] ASC, [NCAT_CODE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NCAT_PRIMARY_NCAT_NUMBER]
    ON [dbo].[NL_CATEGORIES]([NCAT_PRIMARY] ASC, [NCAT_NUMBER] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [NCAT_REPORTING_CODE]
    ON [dbo].[NL_CATEGORIES]([NCAT_REPORTING_CODE] ASC) WITH (FILLFACTOR = 70);

