CREATE TABLE [dbo].[NL_COA_PROFILE] (
    [NCPR_PRIMARY]          INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [NCPR_PARENT_NCOA_LINK] INT        NOT NULL,
    [NCPR_CHILD_NCOA_LINK]  INT        NOT NULL,
    [NCPR_PERCENTAGE]       FLOAT (53) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [NCPR_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NCPR_PRIMARY] ASC),
    CONSTRAINT [NCPR_CHILD_NCOA_LINK_FK] FOREIGN KEY ([NCPR_CHILD_NCOA_LINK]) REFERENCES [dbo].[NL_CHART_OF_ACCOUNTS] ([NCOA_PRIMARY]),
    CONSTRAINT [NCPR_PARENT_NCOA_LINK_FK] FOREIGN KEY ([NCPR_PARENT_NCOA_LINK]) REFERENCES [dbo].[NL_CHART_OF_ACCOUNTS] ([NCOA_PRIMARY]) ON DELETE CASCADE
);

