CREATE TABLE [dbo].[NL_DETAIL_PLUGINS_VCHAR] (
    [NLDPV_PRIMARY]     INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [NLDPV_DETAIL_LINK] FLOAT (53)     NOT NULL,
    [NLDPV_TAGNAME]     VARCHAR (100)  NOT NULL,
    [NLDPV_TAGVALUE]    VARCHAR (1000) NULL,
    CONSTRAINT [NLDPV_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NLDPV_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [NLDPV_DETAIL_LINK_FK] FOREIGN KEY ([NLDPV_DETAIL_LINK]) REFERENCES [dbo].[SL_PL_NL_DETAIL] ([DET_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NLDPV_DETAIL_LINK]
    ON [dbo].[NL_DETAIL_PLUGINS_VCHAR]([NLDPV_DETAIL_LINK] ASC, [NLDPV_TAGNAME] ASC) WITH (FILLFACTOR = 70);

