CREATE TABLE [dbo].[NL_MAJORHEADING] (
    [NL_MAJORCODE]     TINYINT      DEFAULT ((0)) NULL,
    [NL_MAJORNAME]     VARCHAR (40) NULL,
    [NL_MAJORMARKER]   VARCHAR (1)  NULL,
    [NL_MAJORLEVEL1]   VARCHAR (5)  NULL,
    [NL_MAJORLEVEL2]   VARCHAR (5)  NULL,
    [NL_MAJORLEVEL3]   VARCHAR (5)  NULL,
    [NL_MAJORLINKACC]  VARCHAR (25) NULL,
    [NM_PRIMARY]       FLOAT (53)   NOT NULL,
    [NL_MAJORSORTCODE] INT          DEFAULT ((0)) NULL,
    CONSTRAINT [NM_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NM_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NL_MAJORCODE]
    ON [dbo].[NL_MAJORHEADING]([NL_MAJORCODE] ASC);


GO
CREATE TRIGGER [dbo].[aa_majorheading_dt]
    ON [dbo].[NL_MAJORHEADING]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

