CREATE TABLE [dbo].[NL_MAJHED_LANG] (
    [NMHLANG_LANGCODE] VARCHAR (10) NOT NULL,
    [NMHLANG_CODE]     TINYINT      NOT NULL,
    [NMHLANG_NAME]     VARCHAR (40) NULL,
    CONSTRAINT [NL_MAJHED_LANG_PK] PRIMARY KEY CLUSTERED ([NMHLANG_LANGCODE] ASC, [NMHLANG_CODE] ASC)
);

