CREATE TABLE [dbo].[NL_PROFILE] (
    [NP_COPYNCODE]   VARCHAR (25) NULL,
    [NP_PERCENTAGE]  FLOAT (53)   DEFAULT ((0)) NULL,
    [NP_PROFILECODE] VARCHAR (25) NULL,
    [NP_USER_PUTIN]  VARCHAR (4)  NULL,
    [NP_USER_EDITED] VARCHAR (4)  NULL,
    [NP_DATE_PUTIN]  DATETIME     NULL,
    [NP_DATE_EDITED] DATETIME     NULL,
    [NP_PRIMARY]     FLOAT (53)   NOT NULL,
    CONSTRAINT [NP_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NP_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NP_COPYNCODE]
    ON [dbo].[NL_PROFILE]([NP_COPYNCODE] ASC);


GO
CREATE TRIGGER [dbo].[AA_NOMINAL_PROFILE_DELETE_T]
    ON [dbo].[NL_PROFILE]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

