CREATE TABLE [dbo].[NL_PROFILE_TEMP] (
    [NL_PROFILE_ID] INT          NOT NULL,
    [NL_ACCOUNT]    VARCHAR (25) NOT NULL,
    [NL_PERCENTAGE] FLOAT (53)   NOT NULL,
    [NL_LINE_NO]    INT          NOT NULL,
    CONSTRAINT [NL_PROFILE_ID_NL_LINE_NO_PK] PRIMARY KEY CLUSTERED ([NL_PROFILE_ID] ASC, [NL_LINE_NO] ASC)
);

