CREATE TABLE [dbo].[NL_REPORTING_CODES] (
    [NRC_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [NRC_CODE]        SMALLINT     NOT NULL,
    [NRC_DESCRIPTION] VARCHAR (40) NOT NULL,
    [NRC_TYPE]        VARCHAR (1)  NOT NULL,
    CONSTRAINT [NL_REPORTING_CODES_PK] PRIMARY KEY CLUSTERED ([NRC_CODE] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [NRC_TYPE_CK] CHECK ([NRC_TYPE]='P' OR [NRC_TYPE]='B')
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NL_REPORTING_CODE_PRIMARY]
    ON [dbo].[NL_REPORTING_CODES]([NRC_PRIMARY] ASC) WITH (FILLFACTOR = 70);

