CREATE TABLE [dbo].[NL_RECURJNL_COUNT] (
    [NR_PRIMARY]          FLOAT (53)  NOT NULL,
    [NR_TRANSACTION_LINK] FLOAT (53)  DEFAULT ((0)) NULL,
    [NR_YEAR]             VARCHAR (1) NULL,
    [NR_PERIOD]           TINYINT     DEFAULT ((0)) NULL,
    [NR_COUNT]            INT         DEFAULT ((0)) NULL,
    CONSTRAINT [NR_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NR_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NR_TRANSACTION_LINK]
    ON [dbo].[NL_RECURJNL_COUNT]([NR_TRANSACTION_LINK] ASC, [NR_YEAR] ASC, [NR_PERIOD] ASC)
    INCLUDE([NR_COUNT]);

