CREATE TABLE [dbo].[NL_REPORT_FORMAT] (
    [NL_RF_PRIMARY]   INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [NL_RF_REPTYPE]   TINYINT      DEFAULT ((0)) NULL,
    [NL_RF_ITEMDRCR]  TINYINT      DEFAULT ((0)) NULL,
    [NL_RF_ITEMINFO]  TINYINT      DEFAULT ((0)) NULL,
    [NL_RF_ITEMAMT]   TINYINT      DEFAULT ((0)) NULL,
    [NL_RF_ITEMTYPE]  VARCHAR (1)  NULL,
    [NL_RF_ITEM_LANG] VARCHAR (10) NULL,
    [NL_RF_ITEM_NAME] VARCHAR (40) NULL,
    [NL_RF_RANGE1F]   VARCHAR (25) NULL,
    [NL_RF_RANGE1T]   VARCHAR (25) NULL,
    [NL_RF_RANGE2F]   VARCHAR (25) NULL,
    [NL_RF_RANGE2T]   VARCHAR (25) NULL,
    [NL_RF_RANGE3F]   VARCHAR (25) NULL,
    [NL_RF_RANGE3T]   VARCHAR (25) NULL,
    CONSTRAINT [NL_RF_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NL_RF_PRIMARY] ASC)
);

