CREATE TABLE [dbo].[NL_TRANSACTIONS] (
    [NT_TRANTYPE]            VARCHAR (3)   NULL,
    [NT_HEADER_REF]          VARCHAR (25)  NULL,
    [NT_DESCRIPTION]         VARCHAR (200) NULL,
    [NT_DATE]                DATETIME      NULL,
    [NT_POST_VALUE]          FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_LINE_COUNT]          INT           DEFAULT ((0)) NULL,
    [NT_BATCH_FLAG]          TINYINT       DEFAULT ((0)) NULL,
    [NT_QUERY_FLAG]          TINYINT       DEFAULT ((0)) NULL,
    [NT_BATCH_REF]           VARCHAR (10)  NULL,
    [NT_ARCHIVE_FLAG]        TINYINT       DEFAULT ((0)) NULL,
    [NT_CONTRA_FLAG]         TINYINT       DEFAULT ((0)) NULL,
    [NT_GROSS_CONTRA]        VARCHAR (25)  NULL,
    [NT_MULTI_CONTRA]        TINYINT       DEFAULT ((0)) NULL,
    [NT_VAT_CONTRA]          VARCHAR (25)  NULL,
    [NT_CURRENCYRATE]        FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_CURRENCYSYMB]        VARCHAR (4)   NULL,
    [NT_CURR_VALUE]          FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_CURRENCYCODE]        VARCHAR (6)   NULL,
    [NT_CURRENCYRTCH]        TINYINT       DEFAULT ((0)) NULL,
    [NT_IMPEXP_CODE]         VARCHAR (1)   NULL,
    [NT_COUNTRY_CODE]        VARCHAR (4)   NULL,
    [NT_EC_DEL_TERM]         VARCHAR (3)   NULL,
    [NT_EC_T_NATURE]         VARCHAR (2)   NULL,
    [NT_EC_T_MODE]           VARCHAR (1)   NULL,
    [NT_PERIODNUMBER]        TINYINT       DEFAULT ((0)) NULL,
    [NT_YEAR]                VARCHAR (1)   NULL,
    [NT_RECUR_FLAG]          TINYINT       DEFAULT ((0)) NULL,
    [NT_REVERSE_FLAG]        TINYINT       DEFAULT ((0)) NULL,
    [NT_MAX_POSTINGS]        FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_POSTINGS_CNT]        FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_POSTINGS_PER]        TINYINT       DEFAULT ((0)) NULL,
    [NT_POSTINGS_FRQ]        VARCHAR (3)   NULL,
    [NT_POSTED_DATE]         DATETIME      NULL,
    [NT_FIRST_DATE]          DATETIME      NULL,
    [NT_NEXT_DATE]           DATETIME      NULL,
    [NT_USER_PUTIN]          VARCHAR (4)   NULL,
    [NT_DATE_PUTIN]          DATETIME      NULL,
    [NT_MU_STATUS]           VARCHAR (1)   NULL,
    [NT_CON_REFTYPE]         VARCHAR (26)  NULL,
    [NT_REBUILDNUM]          FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_PRIMARY]             FLOAT (53)    NOT NULL,
    [NT_HEADER_KEY]          VARCHAR (20)  NULL,
    [NT_SUB_LEDGER]          VARCHAR (10)  NULL,
    [NT_CHEQUE_PAYEE]        VARCHAR (40)  NULL,
    [NT_PAYMENT_FLAG]        TINYINT       DEFAULT ((0)) NULL,
    [NT_BASE2_VALUE]         FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_BASE2_RATE]          FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_TRI_RATE1]           FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_BASE2_RATECHNG]      TINYINT       DEFAULT ((0)) NULL,
    [NT_TRI_RATECHNG1]       TINYINT       DEFAULT ((0)) NULL,
    [NT_RND_DIFF_BASE1]      FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_CURR_TYPE]           VARCHAR (1)   NULL,
    [NT_TRI_RATE2]           FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_TRI_RATECHNG2]       TINYINT       DEFAULT ((0)) NULL,
    [NT_RND_DIFF_POSTED]     TINYINT       DEFAULT ((0)) NULL,
    [NT_SPCL_TRANTYPE]       VARCHAR (20)  NULL,
    [NT_SRV_STATUS]          TINYINT       DEFAULT ((0)) NULL,
    [NT_SOURCE]              VARCHAR (1)   NULL,
    [NT_TRAN_OPTIONS]        VARCHAR (30)  NULL,
    [NT_PERIOD_MAXC]         FLOAT (53)    DEFAULT ((0)) NULL,
    [NT_NOM_CAT_LINK]        INT           NULL,
    [NT_YEAR_LINK]           SMALLINT      NULL,
    [NT_WFF_APPROVAL_STATUS] SMALLINT      DEFAULT ((0)) NULL,
    [NT_LANDED_COST]         BIT           DEFAULT ((0)) NULL,
    CONSTRAINT [NT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NT_PRIMARY] ASC),
    CONSTRAINT [NT_YEAR_LINK_CK] CHECK ([NT_YEAR] IS NOT NULL AND (upper([NT_YEAR])='O' OR upper([NT_YEAR])='N' OR upper([NT_YEAR])='C' OR upper([NT_YEAR])='L') AND [NT_YEAR_LINK] IS NOT NULL OR ([NT_YEAR] IS NULL OR (upper([NT_YEAR])='O' OR upper([NT_YEAR])='')) AND [NT_YEAR_LINK] IS NULL),
    CONSTRAINT [NT_NOM_CAT_LINK_FK] FOREIGN KEY ([NT_NOM_CAT_LINK]) REFERENCES [dbo].[NL_CATEGORIES] ([NCAT_PRIMARY]),
    CONSTRAINT [NT_YEAR_LINK_FK] FOREIGN KEY ([NT_YEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [NT_BATCH_FLAG]
    ON [dbo].[NL_TRANSACTIONS]([NT_BATCH_FLAG] ASC);


GO
CREATE NONCLUSTERED INDEX [NT_CON_REFTYPE]
    ON [dbo].[NL_TRANSACTIONS]([NT_CON_REFTYPE] ASC);


GO
CREATE NONCLUSTERED INDEX [NT_HEADER_REF]
    ON [dbo].[NL_TRANSACTIONS]([NT_HEADER_REF] ASC);


GO
CREATE NONCLUSTERED INDEX [NT_RECUR_FLAG]
    ON [dbo].[NL_TRANSACTIONS]([NT_RECUR_FLAG] ASC, [NT_GROSS_CONTRA] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [IX_NL_TRANSACTIONS_NT_HEADER_KEY]
    ON [dbo].[NL_TRANSACTIONS]([NT_HEADER_KEY] ASC)
    INCLUDE([NT_HEADER_REF], [NT_CON_REFTYPE], [NT_PAYMENT_FLAG]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NT_HEADER_KEY]
    ON [dbo].[NL_TRANSACTIONS]([NT_HEADER_KEY] ASC) WITH (FILLFACTOR = 70);


GO
CREATE TRIGGER [dbo].[aa_nl_tran_dt]
    ON [dbo].[NL_TRANSACTIONS]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

