CREATE TABLE [dbo].[NL_TRN_TEMP] (
    [NL_TRAN_ID]                  INT             NOT NULL,
    [NL_DETAIL_LINE_NO]           INT             NOT NULL,
    [NL_STATUS_TEMP]              TINYINT         NULL,
    [NL_USE_DEFAULT]              VARCHAR (150)   NULL,
    [NL_USER_ID]                  VARCHAR (4)     NULL,
    [NL_MODULE]                   VARCHAR (3)     NULL,
    [NL_TRANSACTION_TYPE]         VARCHAR (4)     NULL,
    [NL_IMPORT_EXPORT_CODE]       CHAR (1)        NULL,
    [NL_SUBLEDGER_CODE]           VARCHAR (10)    NULL,
    [NL_GROSS_CONTRA]             VARCHAR (25)    NULL,
    [NL_VAT_CONTRA]               VARCHAR (25)    NULL,
    [NL_TRAN_REFERENCE]           VARCHAR (10)    NULL,
    [NL_EC_DELIVERY_TERMS]        VARCHAR (3)     NULL,
    [NL_EC_TRAN_NATURE]           VARCHAR (2)     NULL,
    [NL_EC_TRANSPORTATION_MODE]   VARCHAR (2)     NULL,
    [NL_CURRENCYSYMBOL]           VARCHAR (4)     NULL,
    [NL_CURRENCYCODE]             VARCHAR (6)     NULL,
    [NL_CURRENCY_TYPE]            CHAR (1)        NULL,
    [NL_CURRENCY_RATE]            DECIMAL (16, 6) NULL,
    [NL_EURO_HOME_RATE]           DECIMAL (16, 6) NULL,
    [NL_BASE2_RATE]               DECIMAL (16, 6) NULL,
    [NL_TRANSACTION_DATE]         DATETIME        NULL,
    [NL_BATCH_REFERENCE]          VARCHAR (10)    NULL,
    [NL_FIRST_POSTING_DATE]       DATETIME        NULL,
    [NL_MAXIMUM_POSTING_NO]       INT             NULL,
    [NL_TRANSACTION_YEAR]         VARCHAR (2)     NULL,
    [NL_TRANSACTION_PERIOD]       TINYINT         NULL,
    [NL_POSTING_FREQUENCY_NO]     TINYINT         NULL,
    [NL_POSTING_FREQUENCY_TYPE]   VARCHAR (3)     NULL,
    [NL_REVERSE_JOURNAL]          TINYINT         NULL,
    [NL_PAYMENT_FLAG]             TINYINT         NULL,
    [NL_CHEQUE_PAYEE]             VARCHAR (40)    NULL,
    [NL_DESCRIPTION]              VARCHAR (200)   NULL,
    [NL_CREDIT_DEBIT_TRANSACTION] VARCHAR (2)     NULL,
    [NL_JOURNAL_ACCOUNT]          VARCHAR (25)    NULL,
    [NL_HOME_TRANSACTION_VALUE]   FLOAT (53)      NULL,
    [NL_VATCODE]                  VARCHAR (4)     NULL,
    [NL_HOME_VAT_VALUE]           FLOAT (53)      NULL,
    [NL_CURRENCY_GROSS]           FLOAT (53)      NULL,
    [NL_CURRENCY_TAX]             FLOAT (53)      NULL,
    [NL_BASE2_GROSS]              FLOAT (53)      NULL,
    [NL_BASE2_VAT]                FLOAT (53)      NULL,
    [NL_DETAIL_DATE]              DATETIME        NULL,
    [NL_DETAIL_JNL_REFERENCE]     VARCHAR (10)    NULL,
    [NL_COSTHEADER]               VARCHAR (10)    NULL,
    [NL_COSTCENTRE]               VARCHAR (10)    NULL,
    [NL_DETAIL_DESCRIPTION]       VARCHAR (240)   NULL,
    [NL_DIMENSION1]               VARCHAR (20)    NULL,
    [NL_DIMENSION2]               VARCHAR (20)    NULL,
    [NL_DIMENSION3]               VARCHAR (20)    NULL,
    [NL_POST_CONTRA]              TINYINT         NULL,
    [NL_MULTIPLE_CONTRAS]         TINYINT         NULL,
    [NL_GROSS_HOME_ENTRY_MODE]    TINYINT         NULL,
    [NL_CURRENCY_ENTRY_MODE]      CHAR (1)        NULL,
    [NL_ARCHIVE_FLAG]             TINYINT         NULL,
    [NL_DO_NOT_BATCH]             TINYINT         NULL,
    [NL_RECURRING_TRANSACTION]    TINYINT         NULL,
    [NL_SOURCE]                   VARCHAR (1)     NULL,
    [NL_DETAIL_PRIMARY]           INT             NULL,
    [NL_DELETE_DETAIL_LINE]       TINYINT         NULL,
    [NL_HEADER_USER_CHAR1]        VARCHAR (20)    NULL,
    [NL_HEADER_USER_CHAR2]        VARCHAR (20)    NULL,
    [NL_HEADER_USER_CHAR3]        VARCHAR (100)   NULL,
    [NL_HEADER_USER_CHAR4]        VARCHAR (100)   NULL,
    [NL_HEADER_USER_FLAG1]        TINYINT         NULL,
    [NL_HEADER_USER_FLAG2]        TINYINT         NULL,
    [NL_HEADER_USER_DATE1]        DATETIME        NULL,
    [NL_HEADER_USER_DATE2]        DATETIME        NULL,
    [NL_HEADER_USER_NUMBER1]      FLOAT (53)      NULL,
    [NL_HEADER_USER_NUMBER2]      FLOAT (53)      NULL,
    [NL_DETAIL_USER_CHAR1]        VARCHAR (20)    NULL,
    [NL_DETAIL_USER_CHAR2]        VARCHAR (20)    NULL,
    [NL_DETAIL_USER_CHAR3]        VARCHAR (100)   NULL,
    [NL_DETAIL_USER_CHAR4]        VARCHAR (100)   NULL,
    [NL_DETAIL_USER_FLAG1]        TINYINT         NULL,
    [NL_DETAIL_USER_FLAG2]        TINYINT         NULL,
    [NL_DETAIL_USER_DATE1]        DATETIME        NULL,
    [NL_DETAIL_USER_DATE2]        DATETIME        NULL,
    [NL_DETAIL_USER_NUMBER1]      FLOAT (53)      NULL,
    [NL_DETAIL_USER_NUMBER2]      FLOAT (53)      NULL,
    [NL_TRAN_OPTIONS]             VARCHAR (30)    NULL,
    [NL_HEADER_PRIMARY]           INT             NULL,
    [NL_RECURRENCES_PER_PERIOD]   INT             NULL,
    [NL_NEXT_POSTING_DATE]        DATETIME        NULL,
    [NL_CO2_CLASSIFICATION_ID]    CHAR (4)        NULL,
    [NL_CO2_CONSUMPTION_DATE]     DATETIME        NULL,
    [NL_CO2_YEAR]                 SMALLINT        NULL,
    [NL_CO2_PERIOD]               TINYINT         NULL,
    [NL_CO2_QUANTITY]             FLOAT (53)      NULL,
    [NL_CO2_1ST_CATEGORY_PRIMARY] INT             NULL,
    [NL_CO2_2ND_CATEGORY_PRIMARY] INT             NULL,
    [NL_CO2_1ST_CATEGORY_CODE]    VARCHAR (6)     NULL,
    [NL_CO2_2ND_CATEGORY_CODE]    VARCHAR (6)     NULL,
    [NL_CO2_UNIT_OF_MEASURE]      VARCHAR (20)    NULL,
    [NL_CO2_XML]                  TEXT            NULL,
    [NL_CO2_EMISSIONS_GROUP_ID]   VARCHAR (2)     NULL,
    [NL_FORCE_VAT_RATE_REFRESH]   BIT             NULL,
    [NL_CO2_GHG_SCOPE]            TINYINT         NULL,
    [NL_CO2_SORT_KEY1]            VARCHAR (20)    NULL,
    [NL_CO2_SORT_KEY1_CREATE]     BIT             NULL,
    [NL_CO2_SORT_KEY2]            VARCHAR (20)    NULL,
    [NL_CO2_SORT_KEY2_CREATE]     BIT             NULL,
    [NL_CO2_SORT_KEY3]            VARCHAR (20)    NULL,
    [NL_CO2_SORT_KEY3_CREATE]     BIT             NULL,
    [NL_CO2_SORT_KEY4]            VARCHAR (20)    NULL,
    [NL_CO2_SORT_KEY4_CREATE]     BIT             NULL,
    [NL_ALLOW_NO_CARBON]          BIT             NULL,
    [NL_QUANTITY]                 FLOAT (53)      NULL,
    CONSTRAINT [NL_TRN_TEMP_PK] PRIMARY KEY CLUSTERED ([NL_TRAN_ID] ASC, [NL_DETAIL_LINE_NO] ASC)
);


GO
CREATE TRIGGER [dbo].[AA_PROCESS_NL_TRN_TEMP_T]
    ON [dbo].[NL_TRN_TEMP]
    WITH ENCRYPTION
    AFTER UPDATE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

