CREATE TABLE [dbo].[NL_YEAR_END_JOURNAL] (
    [YEAR_END_CODE]                  VARCHAR (25) NOT NULL,
    [YEAR_END_DESCRIPTION]           VARCHAR (40) NULL,
    [YEAR_END_JOURNAL_REF]           VARCHAR (8)  NULL,
    [YEAR_END_DATE]                  DATETIME     NOT NULL,
    [YEAR_END_USER_ID]               VARCHAR (4)  NOT NULL,
    [YEAR_END_DEBIT_VALUE]           FLOAT (53)   DEFAULT ((0)) NULL,
    [YEAR_END_CREDIT_VALUE]          FLOAT (53)   DEFAULT ((0)) NULL,
    [YEAR_END_CURRENCY_CODE]         VARCHAR (4)  NOT NULL,
    [YEAR_END_2ND_BASE_RATE]         FLOAT (53)   DEFAULT ((0)) NULL,
    [YEAR_END_YR_END_CODE]           VARCHAR (25) NOT NULL,
    [YEAR_END_CURR_DEBIT_VALUE]      FLOAT (53)   DEFAULT ((0)) NULL,
    [YEAR_END_CURR_CREDIT_VALUE]     FLOAT (53)   DEFAULT ((0)) NULL,
    [YEAR_END_2ND_BASE_DEBIT_VALUE]  FLOAT (53)   DEFAULT ((0)) NULL,
    [YEAR_END_2ND_BASE_CREDIT_VALUE] FLOAT (53)   DEFAULT ((0)) NULL,
    [YEAR_END_YEAR_LINK]             SMALLINT     NULL,
    [YEAR_END_PRIMARY]               INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    CONSTRAINT [YEAR_END_PRIMARY_PK] PRIMARY KEY CLUSTERED ([YEAR_END_PRIMARY] ASC),
    CONSTRAINT [YEAR_END_YEAR_LINK_FK] FOREIGN KEY ([YEAR_END_YEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);

