CREATE TABLE [dbo].[NLB_PROFILES] (
    [NBP_PRIMARY]         INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [NBP_CODE]            VARCHAR (10) NULL,
    [NBP_DESCRIPTION]     VARCHAR (40) NULL,
    [NBP_PERIODVALUE1]    FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE2]    FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE3]    FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE4]    FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE5]    FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE6]    FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE7]    FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE8]    FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE9]    FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE10]   FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE11]   FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE12]   FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_PERIODVALUE13]   FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_DENOMINATOR]     INT          DEFAULT ((0)) NULL,
    [NBP_USER_EDITED]     VARCHAR (4)  NULL,
    [NBP_DATE_EDITED]     DATETIME     NULL,
    [NBP_USER_PUTIN]      VARCHAR (4)  NULL,
    [NBP_DATE_PUTIN]      DATETIME     NULL,
    [NBP_NOTES]           TEXT         NULL,
    [NBP_USRCHAR1]        VARCHAR (20) NULL,
    [NBP_USRCHAR2]        VARCHAR (20) NULL,
    [NBP_USRCHAR3]        VARCHAR (20) NULL,
    [NBP_USRCHAR4]        VARCHAR (30) NULL,
    [NBP_USRCHAR5]        VARCHAR (30) NULL,
    [NBP_USRCHAR6]        VARCHAR (30) NULL,
    [NBP_USRFLAG1]        TINYINT      DEFAULT ((0)) NULL,
    [NBP_USRFLAG2]        TINYINT      DEFAULT ((0)) NULL,
    [NBP_USRFLAG3]        TINYINT      DEFAULT ((0)) NULL,
    [NBP_USRNUM1]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_USRNUM2]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_USRNUM3]         FLOAT (53)   DEFAULT ((0)) NULL,
    [NBP_USRDATE1]        DATETIME     NULL,
    [NBP_USRDATE2]        DATETIME     NULL,
    [NBP_USRDATE3]        DATETIME     NULL,
    [NBP_DEFAULT_PROFILE] TINYINT      DEFAULT ((0)) NULL,
    CONSTRAINT [NBP_PRIMARY_PK] PRIMARY KEY CLUSTERED ([NBP_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NBP_CODE]
    ON [dbo].[NLB_PROFILES]([NBP_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [NBP_DESCRIPTION]
    ON [dbo].[NLB_PROFILES]([NBP_DESCRIPTION] ASC);

