CREATE TABLE [dbo].[ORD_HEADER_CUSTOM_DATE] (
    [OHD_PRIMARY]     INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [OHD_HEADER_LINK] FLOAT (53) NOT NULL,
    [OHD_NUMBER]      TINYINT    NOT NULL,
    [OHD_DATA]        DATETIME   NOT NULL,
    CONSTRAINT [OHD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([OHD_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [OHD_HEADER_LINK_FK] FOREIGN KEY ([OHD_HEADER_LINK]) REFERENCES [dbo].[ORD_HEADER] ([OH_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [OHD_HEADER_LINK_NUMBER]
    ON [dbo].[ORD_HEADER_CUSTOM_DATE]([OHD_HEADER_LINK] ASC, [OHD_NUMBER] ASC)
    INCLUDE([OHD_DATA]) WITH (FILLFACTOR = 70);

