CREATE TABLE [dbo].[ORD_HEADER_NOTE] (
    [OHNT_PRIMARY] FLOAT (53) NOT NULL,
    [OHNT_NOTE]    TEXT       NULL,
    CONSTRAINT [OHNT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([OHNT_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [OHNT_PRIMARY_FK] FOREIGN KEY ([OHNT_PRIMARY]) REFERENCES [dbo].[ORD_HEADER] ([OH_PRIMARY]) ON DELETE CASCADE
);

