CREATE TABLE [dbo].[ORD_DETAIL_ACCRUALS] (
    [ODA_PRIMARY]     FLOAT (53)   NOT NULL,
    [ODA_HEADER_LINK] FLOAT (53)   NOT NULL,
    [ODA_PERIODS]     SMALLINT     NOT NULL,
    [ODA_ACCRUAL_NOM] VARCHAR (25) NOT NULL,
    CONSTRAINT [ODA_PRIMARY_PK] PRIMARY KEY CLUSTERED ([ODA_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [ODA_ACCRUAL_NOM_FK] FOREIGN KEY ([ODA_ACCRUAL_NOM]) REFERENCES [dbo].[NL_ACCOUNTS] ([NCODE]) ON UPDATE CASCADE,
    CONSTRAINT [ODA_PRIMARY_FK] FOREIGN KEY ([ODA_PRIMARY]) REFERENCES [dbo].[ORD_DETAIL] ([OD_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [ODA_ACCRUAL_NOM]
    ON [dbo].[ORD_DETAIL_ACCRUALS]([ODA_ACCRUAL_NOM] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [ODA_HEADER_LINK]
    ON [dbo].[ORD_DETAIL_ACCRUALS]([ODA_HEADER_LINK] ASC) WITH (FILLFACTOR = 70);

