CREATE TABLE [dbo].[ORD_HEADER_CUSTOM_FLAG] (
    [OHF_PRIMARY]     INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [OHF_HEADER_LINK] FLOAT (53) NOT NULL,
    [OHF_NUMBER]      TINYINT    NOT NULL,
    [OHF_DATA]        BIT        NOT NULL,
    CONSTRAINT [OHF_PRIMARY_PK] PRIMARY KEY CLUSTERED ([OHF_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [OHF_HEADER_LINK_FK] FOREIGN KEY ([OHF_HEADER_LINK]) REFERENCES [dbo].[ORD_HEADER] ([OH_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [OHF_HEADER_LINK_NUMBER]
    ON [dbo].[ORD_HEADER_CUSTOM_FLAG]([OHF_HEADER_LINK] ASC, [OHF_NUMBER] ASC)
    INCLUDE([OHF_DATA]) WITH (FILLFACTOR = 70);

