CREATE TABLE [dbo].[ORD_HEADER_CUSTOM_NUMBER] (
    [OHN_PRIMARY]     INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [OHN_HEADER_LINK] FLOAT (53)      NOT NULL,
    [OHN_NUMBER]      TINYINT         NOT NULL,
    [OHN_DATA]        DECIMAL (24, 8) NOT NULL,
    CONSTRAINT [OHN_PRIMARY_PK] PRIMARY KEY CLUSTERED ([OHN_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [OHN_HEADER_LINK_FK] FOREIGN KEY ([OHN_HEADER_LINK]) REFERENCES [dbo].[ORD_HEADER] ([OH_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [OHN_HEADER_LINK_NUMBER]
    ON [dbo].[ORD_HEADER_CUSTOM_NUMBER]([OHN_HEADER_LINK] ASC, [OHN_NUMBER] ASC)
    INCLUDE([OHN_DATA]) WITH (FILLFACTOR = 70);

