CREATE TABLE [dbo].[ORD_HEADER_CUSTOM_CHAR] (
    [OHC_PRIMARY]     INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [OHC_HEADER_LINK] FLOAT (53) NOT NULL,
    [OHC_NUMBER]      TINYINT    NOT NULL,
    [OHC_DATA]        CHAR (30)  NOT NULL,
    CONSTRAINT [OHC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([OHC_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [OHC_HEADER_LINK_FK] FOREIGN KEY ([OHC_HEADER_LINK]) REFERENCES [dbo].[ORD_HEADER] ([OH_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [OHC_HEADER_LINK_NUMBER]
    ON [dbo].[ORD_HEADER_CUSTOM_CHAR]([OHC_HEADER_LINK] ASC, [OHC_NUMBER] ASC)
    INCLUDE([OHC_DATA]) WITH (FILLFACTOR = 70);

