CREATE TABLE [dbo].[PAY_RESOURC_LNK] (
    [PAYRES_RESOURCE] VARCHAR (16) NULL,
    [PAYRES_PAYTYPE]  VARCHAR (20) NULL,
    [PAYRES_PAYRATE]  FLOAT (53)   DEFAULT ((0)) NULL,
    [PAYRES_DEFAULT]  TINYINT      DEFAULT ((0)) NULL,
    [PAYRES_LINE]     INT          DEFAULT ((0)) NULL,
    [PAYRES_PRIMARY]  FLOAT (53)   NOT NULL,
    CONSTRAINT [PAYRES_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PAYRES_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PAYRES_RESOURCE]
    ON [dbo].[PAY_RESOURC_LNK]([PAYRES_RESOURCE] ASC, [PAYRES_PAYTYPE] ASC) WITH (FILLFACTOR = 70);

