CREATE TABLE [dbo].[PL_ALLOC_HISTORY] (
    [P_AL_PRIMARY]        INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [P_AL_DATE]           DATETIME     NULL,
    [P_AL_PERIOD]         TINYINT      DEFAULT ((0)) NULL,
    [P_AL_YEAR]           VARCHAR (1)  NULL,
    [P_AL_VALUE_HOME]     FLOAT (53)   DEFAULT ((0)) NULL,
    [P_AL_VALUE_CURR]     FLOAT (53)   DEFAULT ((0)) NULL,
    [P_AL_REFERENCE]      VARCHAR (10) NULL,
    [P_AL_HEADER_KEY]     VARCHAR (20) NULL,
    [P_AL_USER_ID]        VARCHAR (4)  NULL,
    [P_AL_ACCOUNT_CODE]   VARCHAR (10) NULL,
    [P_AL_FULLALLOC_PD]   SMALLINT     CONSTRAINT [DF_PL_ALLOC_HISTORY_P_AL_FULLALLOC_PD] DEFAULT ((0)) NULL,
    [P_AL_FULLALLOC_DATE] INT          DEFAULT ((0)) NULL,
    [P_AL_YEAR_LINK]      SMALLINT     NULL,
    CONSTRAINT [P_AL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([P_AL_PRIMARY] ASC),
    CONSTRAINT [P_AL_YEAR_LINK_CK] CHECK ([P_AL_YEAR] IS NOT NULL AND (upper([P_AL_YEAR])='O' OR upper([P_AL_YEAR])='N' OR upper([P_AL_YEAR])='C' OR upper([P_AL_YEAR])='L') AND [P_AL_YEAR_LINK] IS NOT NULL OR ([P_AL_YEAR] IS NULL OR (upper([P_AL_YEAR])='O' OR upper([P_AL_YEAR])='')) AND [P_AL_YEAR_LINK] IS NULL),
    CONSTRAINT [P_AL_YEAR_LINK_FK] FOREIGN KEY ([P_AL_YEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [P_AL_ACCOUNT_CODE]
    ON [dbo].[PL_ALLOC_HISTORY]([P_AL_ACCOUNT_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [P_AL_FULLALLOC_PD]
    ON [dbo].[PL_ALLOC_HISTORY]([P_AL_FULLALLOC_PD] ASC, [P_AL_ACCOUNT_CODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [P_AL_HEADER_KEY]
    ON [dbo].[PL_ALLOC_HISTORY]([P_AL_HEADER_KEY] ASC, [P_AL_FULLALLOC_PD] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [P_AL_REFERENCE]
    ON [dbo].[PL_ALLOC_HISTORY]([P_AL_REFERENCE] ASC);

