CREATE TABLE [dbo].[PL_ADDRESSES] (
    [PL_AD_ACCCODE]       VARCHAR (10)  NULL,
    [PL_AD_CODE]          FLOAT (53)    DEFAULT ((0)) NULL,
    [PL_AD_CON_CODE]      VARCHAR (16)  NULL,
    [PL_AD_ADDRESS]       VARCHAR (160) NULL,
    [PL_AD_POSTCODE]      VARCHAR (12)  NULL,
    [PL_AD_ADDRESS_USER1] VARCHAR (30)  NULL,
    [PL_AD_ADDRESS_USER2] VARCHAR (30)  NULL,
    [PL_AD_PHONE]         VARCHAR (20)  NULL,
    [PL_AD_FAX]           VARCHAR (20)  NULL,
    [PL_AD_CONTACT]       VARCHAR (30)  NULL,
    [PL_AD_CONT_SAL]      VARCHAR (20)  NULL,
    [PL_AD_INV_ADD]       TINYINT       DEFAULT ((0)) NULL,
    [PL_AD_DEL_ADD]       TINYINT       DEFAULT ((0)) NULL,
    [PL_AD_STAT_ADD]      TINYINT       DEFAULT ((0)) NULL,
    [PL_AD_REM_ADD]       TINYINT       DEFAULT ((0)) NULL,
    [PL_AD_NOTE]          VARCHAR (240) NULL,
    [PL_AD_CON_TITLE]     VARCHAR (5)   NULL,
    [PL_AD_CON_INITS]     VARCHAR (15)  NULL,
    [PL_AD_CON_SNAME]     VARCHAR (30)  NULL,
    [PL_AD_CON_JOB]       VARCHAR (35)  NULL,
    [PL_AD_USRCHAR1]      VARCHAR (20)  NULL,
    [PL_AD_USRCHAR2]      VARCHAR (20)  NULL,
    [PL_AD_USRCHAR3]      VARCHAR (100) NULL,
    [PL_AD_USRCHAR4]      VARCHAR (100) NULL,
    [PL_AD_USRCHAR5]      VARCHAR (20)  NULL,
    [PL_AD_USRCHAR6]      VARCHAR (30)  NULL,
    [PL_AD_USRCHAR7]      VARCHAR (30)  NULL,
    [PL_AD_USRCHAR8]      VARCHAR (30)  NULL,
    [PL_AD_USRFLAG1]      TINYINT       DEFAULT ((0)) NULL,
    [PL_AD_USRFLAG2]      TINYINT       DEFAULT ((0)) NULL,
    [PL_AD_USRFLAG3]      TINYINT       DEFAULT ((0)) NULL,
    [PL_AD_USRDATE1]      DATETIME      NULL,
    [PL_AD_USRDATE2]      DATETIME      NULL,
    [PL_AD_USRDATE3]      DATETIME      NULL,
    [PL_AD_USRNUM1]       FLOAT (53)    DEFAULT ((0)) NULL,
    [PL_AD_USRNUM2]       FLOAT (53)    DEFAULT ((0)) NULL,
    [PL_AD_USRNUM3]       FLOAT (53)    DEFAULT ((0)) NULL,
    [PL_AD_ANA_NUMBER]    VARCHAR (13)  NULL,
    [PL_AD_PRIMARY]       FLOAT (53)    NOT NULL,
    [PL_AD_ANALYSIS]      VARCHAR (25)  NULL,
    [PL_AD_DEL_ADDRESS_2] TINYINT       DEFAULT ((0)) NULL,
    [PL_AD_SOURCE]        VARCHAR (1)   NULL,
    [PL_AD_EMAIL]         VARCHAR (64)  NULL,
    [PL_AD_CC_EMAIL]      VARCHAR (64)  NULL,
    [PL_AD_COUNTRY]       VARCHAR (35)  NULL,
    [PL_AD_CON_FNAME]     VARCHAR (20)  NULL,
    [PL_AD_DO_NOT_USE]    TINYINT       DEFAULT ((0)) NULL,
    [PL_AD_MOBILE]        VARCHAR (20)  NULL,
    [PL_AD_USER_EDITED]   VARCHAR (4)   NULL,
    [PL_AD_USER_PUTIN]    VARCHAR (4)   NULL,
    [PL_AD_DATE_PUTIN]    DATETIME      NULL,
    [PL_AD_DATE_EDITED]   DATETIME      NULL,
    CONSTRAINT [PL_AD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PL_AD_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PL_AD_ACCCODE]
    ON [dbo].[PL_ADDRESSES]([PL_AD_ACCCODE] ASC, [PL_AD_CODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PL_AD_CON_CODE]
    ON [dbo].[PL_ADDRESSES]([PL_AD_CON_CODE] ASC);


GO
CREATE TRIGGER [dbo].[AA_EDIT_PL_DEF_ADDRESSES_T]
    ON [dbo].[PL_ADDRESSES]
    WITH ENCRYPTION
    AFTER INSERT, UPDATE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


GO
CREATE TRIGGER [dbo].[aa_pl_address_dt]
    ON [dbo].[PL_ADDRESSES]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

