CREATE TABLE [dbo].[PL_ANALYSIS] (
    [PACODE]                VARCHAR (25) NULL,
    [PANAME]                VARCHAR (40) NULL,
    [PAUSED]                TINYINT      DEFAULT ((0)) NULL,
    [PA_COUNTRY_CODE]       VARCHAR (4)  NULL,
    [PATYPE_P_B_D]          VARCHAR (1)  NULL,
    [PADEFAULT_BANK]        TINYINT      DEFAULT ((0)) NULL,
    [PADEFAULT_PURCH]       TINYINT      DEFAULT ((0)) NULL,
    [PANOMINALDR]           VARCHAR (25) NULL,
    [PANOMINALCR]           VARCHAR (25) NULL,
    [PANOMINALVAT]          VARCHAR (25) NULL,
    [PAVATCODE]             VARCHAR (4)  NULL,
    [PANOMINALDISC]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PASORT]                VARCHAR (20) NULL,
    [PAUSER1]               VARCHAR (20) NULL,
    [PAUSER2]               VARCHAR (20) NULL,
    [PAUSER3]               VARCHAR (20) NULL,
    [PATURNOVR_L1]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L2]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L3]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L4]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L5]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L6]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L7]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L8]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L9]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L10]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L11]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L12]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L13]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C1]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C2]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C3]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C4]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C5]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C6]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C7]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C8]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C9]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C10]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C11]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C12]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C13]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O1]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O2]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O3]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O4]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O5]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O6]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O7]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O8]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O9]          FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O10]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O11]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O12]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O13]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVERYTD]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVERPTD]         FLOAT (53)   DEFAULT ((0)) NULL,
    [PACURRENCYSYMBL]       VARCHAR (4)  NULL,
    [PATURNOVR_L1_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L2_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L3_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L4_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L5_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L6_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L7_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L8_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L9_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L10_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L11_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L12_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_L13_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C1_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C2_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C3_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C4_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C5_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C6_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C7_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C8_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C9_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C10_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C11_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C12_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_C13_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O1_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O2_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O3_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O4_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O5_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O6_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O7_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O8_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O9_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O10_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O11_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O12_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_O13_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_PTD_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PATURNOVR_YTD_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PANOTES]               TEXT         NULL,
    [PA_USER_EDITED]        VARCHAR (4)  NULL,
    [PA_USER_PUTIN]         VARCHAR (4)  NULL,
    [PA_DATE_PUTIN]         DATETIME     NULL,
    [PA_DATE_EDITED]        DATETIME     NULL,
    [PA_MU_STATUS]          VARCHAR (1)  NULL,
    [PA_PRIMARY]            FLOAT (53)   NOT NULL,
    [PA_VATNONDEDUCT]       FLOAT (53)   DEFAULT ((0)) NULL,
    [PA_VAT_UPDATE]         TINYINT      DEFAULT ((0)) NULL,
    [PA_ANALYSIS_MATRIX]    TINYINT      DEFAULT ((0)) NULL,
    [PA_1099_TYPE]          VARCHAR (10) NULL,
    [PA_LEVEL]              INT          DEFAULT ((0)) NULL,
    [PA_GROUP]              VARCHAR (10) NULL,
    [PA_FORCE_COSTING]      TINYINT      DEFAULT ((0)) NULL,
    [PADEFAULT_ROUNDING]    TINYINT      DEFAULT ((0)) NULL,
    [PA_SOURCE]             VARCHAR (1)  NULL,
    [PA_DO_NOT_USE]         BIT          DEFAULT ((0)) NOT NULL,
    [PA_CIS_TAXABLE]        TINYINT      DEFAULT ((0)) NULL,
    [PA_ACCRUE]             BIT          DEFAULT ((0)) NOT NULL,
    [PA_ACCRUAL_PERIODS]    INT          DEFAULT ((0)) NOT NULL,
    [PA_DEFAULT_COSTCENTRE] VARCHAR (10) DEFAULT ('') NOT NULL,
    CONSTRAINT [PA_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PA_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PACODE]
    ON [dbo].[PL_ANALYSIS]([PACODE] ASC);


GO
CREATE NONCLUSTERED INDEX [PACURRENCYSYMBL]
    ON [dbo].[PL_ANALYSIS]([PACURRENCYSYMBL] ASC);


GO
CREATE NONCLUSTERED INDEX [PADEFAULT_BANK]
    ON [dbo].[PL_ANALYSIS]([PADEFAULT_BANK] ASC);


GO
CREATE NONCLUSTERED INDEX [PADEFAULT_PURCH]
    ON [dbo].[PL_ANALYSIS]([PADEFAULT_PURCH] ASC);


GO
CREATE NONCLUSTERED INDEX [PANAME]
    ON [dbo].[PL_ANALYSIS]([PANAME] ASC);


GO
CREATE NONCLUSTERED INDEX [PANOMINALCR]
    ON [dbo].[PL_ANALYSIS]([PANOMINALCR] ASC);


GO
CREATE NONCLUSTERED INDEX [PANOMINALDR]
    ON [dbo].[PL_ANALYSIS]([PANOMINALDR] ASC);


GO
CREATE NONCLUSTERED INDEX [PANOMINALVAT]
    ON [dbo].[PL_ANALYSIS]([PANOMINALVAT] ASC);


GO
CREATE NONCLUSTERED INDEX [PASORT]
    ON [dbo].[PL_ANALYSIS]([PASORT] ASC);


GO
CREATE TRIGGER [dbo].[aa_pl_anal_dt]
    ON [dbo].[PL_ANALYSIS]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

