CREATE TABLE [dbo].[PL_BACS_FORMATS] (
    [PLB_PRIMARY]      INT           NOT NULL,
    [PLB_BACS_FORMATS] VARCHAR (MAX) NULL,
    [PLB_SELECTION]    VARCHAR (256) NULL,
    [PLB_NAMES]        VARCHAR (MAX) NULL,
    [PLB_DATE]         DATETIME      NULL,
    CONSTRAINT [PLB_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PLB_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

