CREATE TABLE [dbo].[PL_DETAIL_PLUGINS_DATETIME] (
    [PLDPD_PRIMARY]     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PLDPD_DETAIL_LINK] FLOAT (53)    NOT NULL,
    [PLDPD_TAGNAME]     VARCHAR (100) NOT NULL,
    [PLDPD_TAGVALUE]    DATETIME      NULL,
    CONSTRAINT [PLDPD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PLDPD_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [PLDPD_DETAIL_LINK_FK] FOREIGN KEY ([PLDPD_DETAIL_LINK]) REFERENCES [dbo].[SL_PL_NL_DETAIL] ([DET_PRIMARY]) ON DELETE CASCADE
);

