CREATE TABLE [dbo].[PL_DETAIL_PLUGINS_VCHAR] (
    [PLDPV_PRIMARY]     INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PLDPV_DETAIL_LINK] FLOAT (53)     NOT NULL,
    [PLDPV_TAGNAME]     VARCHAR (100)  NOT NULL,
    [PLDPV_TAGVALUE]    VARCHAR (1000) NULL,
    CONSTRAINT [PLDPV_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PLDPV_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [PLDPV_DETAIL_LINK_FK] FOREIGN KEY ([PLDPV_DETAIL_LINK]) REFERENCES [dbo].[SL_PL_NL_DETAIL] ([DET_PRIMARY]) ON DELETE CASCADE
);

