CREATE TABLE [dbo].[PL_LANDED_SUBANAL_TEMP] (
    [PL_SUB_ALLOC_ID]          INT             NULL,
    [PL_SUB_USER_ID]           VARCHAR (4)     NULL,
    [PL_SUB_LANDED_LINE]       TINYINT         NULL,
    [PL_SUB_STOCK_CODE]        VARCHAR (25)    NOT NULL,
    [PL_SUB_ANALYSIS_CODE]     VARCHAR (25)    NOT NULL,
    [PL_SUB_WEIGHTED_QUANTITY] DECIMAL (24, 8) NULL,
    [PL_SUB_LANDED_TOTAL]      DECIMAL (24, 8) NULL,
    [PL_SUB_UPDATE]            TINYINT         NULL,
    [PL_SUB_ALLOCATION_VALUE]  DECIMAL (24, 8) NULL,
    CONSTRAINT [PL_LANDED_SUB_TEMP_PK] PRIMARY KEY CLUSTERED ([PL_SUB_STOCK_CODE] ASC, [PL_SUB_ANALYSIS_CODE] ASC)
);

