CREATE TABLE [dbo].[PL_LANDED_TRN_TEMP] (
    [PL_LC_ALLOC_ID]       INT             NULL,
    [PL_LC_USER_ID]        VARCHAR (4)     NULL,
    [PL_LC_DET_ANALYSIS]   VARCHAR (25)    NULL,
    [PL_LC_DET_ACCOUNT]    VARCHAR (10)    NULL,
    [PL_LC_DET_DATE]       DATETIME        NULL,
    [PL_LC_DET_HEADER_REF] VARCHAR (26)    NULL,
    [PL_LC_DET_TYPE]       VARCHAR (3)     NULL,
    [PL_LC_STATUS]         TINYINT         NULL,
    [PL_LC_DET_NETT]       DECIMAL (24, 8) NULL,
    [PL_LC_DET_PRIMARY]    INT             NOT NULL,
    CONSTRAINT [PL_LANDED_TRN_TEMP_PK] PRIMARY KEY CLUSTERED ([PL_LC_DET_PRIMARY] ASC)
);

