CREATE TABLE [dbo].[PL_TRN_LOCKS] (
    [PTL_PT_PRIMARY] FLOAT (53)  NOT NULL,
    [PTL_USER_ID]    VARCHAR (4) NOT NULL,
    [PTL_OPERATION]  VARCHAR (2) NOT NULL,
    [PTL_SOURCE]     VARCHAR (1) NOT NULL,
    [PTL_DATE_PUTIN] DATETIME    DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PTL_PT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PTL_PT_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [PTL_PT_PRIMARY_FK] FOREIGN KEY ([PTL_PT_PRIMARY]) REFERENCES [dbo].[PL_TRANSACTIONS] ([PT_PRIMARY]),
    CONSTRAINT [PTL_USER_ID_FK] FOREIGN KEY ([PTL_USER_ID]) REFERENCES [dbo].[SYS_USER] ([USER_ID])
);


GO
CREATE NONCLUSTERED INDEX [PTL_USER_ID]
    ON [dbo].[PL_TRN_LOCKS]([PTL_USER_ID] ASC, [PTL_SOURCE] ASC, [PTL_OPERATION] ASC) WITH (FILLFACTOR = 70);

