CREATE TABLE [dbo].[PL_TRN_TEMP] (
    [PL_TRAN_ID]                        INT             NOT NULL,
    [PL_DETAIL_LINE_NO]                 INT             NOT NULL,
    [PL_STATUS_TEMP]                    TINYINT         NOT NULL,
    [PL_USE_DEFAULT]                    VARCHAR (150)   NULL,
    [PL_USER_ID]                        VARCHAR (4)     NULL,
    [PL_MODULE]                         VARCHAR (3)     NULL,
    [PL_TRANSACTION_TYPE]               VARCHAR (3)     NULL,
    [PL_SUPPLIER_CODE]                  VARCHAR (10)    NULL,
    [PL_SUBLEDGER_CODE]                 VARCHAR (10)    NULL,
    [PL_CURRENCY_TYPE]                  VARCHAR (1)     NULL,
    [PL_CURRENCYCODE]                   VARCHAR (6)     NULL,
    [PL_CURRENCYSYMBOL]                 VARCHAR (4)     NULL,
    [PL_CURRENCY_RATE]                  DECIMAL (16, 6) DEFAULT ((0)) NULL,
    [PL_EURO_HOME_RATE]                 DECIMAL (16, 6) DEFAULT ((0)) NULL,
    [PL_BASE2_RATE]                     DECIMAL (16, 6) DEFAULT ((0)) NULL,
    [PL_CURRENCY_RATE_CHNGED]           TINYINT         DEFAULT ((0)) NULL,
    [PL_EURO_HOME_RATE_CHNGED]          TINYINT         DEFAULT ((0)) NULL,
    [PL_BASE2_RATE_CHNGED]              TINYINT         DEFAULT ((0)) NULL,
    [PL_EC_DELIVERY_TERMS]              VARCHAR (3)     NULL,
    [PL_EC_TRAN_NATURE]                 VARCHAR (2)     NULL,
    [PL_EC_TRANSPORTATN_MODE]           VARCHAR (2)     NULL,
    [PL_TRAN_REFERENCE]                 VARCHAR (25)    NULL,
    [PL_INTERNAL_REFERENCE]             DECIMAL (15)    DEFAULT ((0)) NULL,
    [PL_BATCH_REFERENCE]                VARCHAR (10)    NULL,
    [PL_TRAN_DATE]                      DATETIME        NULL,
    [PL_TRAN_YEAR]                      CHAR (1)        NULL,
    [PL_TRAN_PERIOD]                    TINYINT         DEFAULT ((0)) NULL,
    [PL_DUE_DATE]                       DATETIME        NULL,
    [PL_ANTICIPATED_PAY_DATE]           DATETIME        NULL,
    [PL_TRAN_DESCRIPTION]               VARCHAR (30)    NULL,
    [PL_DETAIL_ANALYSIS_CODE]           VARCHAR (25)    NULL,
    [PL_DETAIL_VATCODE]                 VARCHAR (4)     NULL,
    [PL_DETAIL_HOME_VALUE]              FLOAT (53)      NULL,
    [PL_DETAIL_HOME_TAX]                FLOAT (53)      NULL,
    [PL_DETAIL_CURR_GROSS]              FLOAT (53)      NULL,
    [PL_DETAIL_CURR_TAX]                FLOAT (53)      NULL,
    [PL_DETAIL_BASE2_GROSS]             FLOAT (53)      NULL,
    [PL_DETAIL_BASE2_TAX]               FLOAT (53)      NULL,
    [PL_DETAIL_COSTHEADER]              VARCHAR (10)    NULL,
    [PL_DETAIL_COSTCENTRE]              VARCHAR (10)    NULL,
    [PL_DETAIL_DESCRIPTION]             VARCHAR (240)   NULL,
    [PL_DETAIL_DIMENSION1]              VARCHAR (20)    NULL,
    [PL_DETAIL_DIMENSION2]              VARCHAR (20)    NULL,
    [PL_DETAIL_DIMENSION3]              VARCHAR (20)    NULL,
    [PL_DISPUTED_FLAG]                  TINYINT         NULL,
    [PL_SETTLE_DISCOUNT_1]              FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_SETTLE_DAYS_1]                  INT             DEFAULT ((0)) NULL,
    [PL_SETTLE_DISCOUNT_2]              FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_SETTLE_DAYS2]                   INT             DEFAULT ((0)) NULL,
    [PL_PAYMENT_STATUS]                 CHAR (1)        NULL,
    [PL_ARCHIVE_FLAG]                   TINYINT         NULL,
    [PL_DO_NOT_BATCH]                   TINYINT         NULL,
    [PL_HOME_GROSS_ENTRY_MODE]          TINYINT         NULL,
    [PL_CURRENCY_ENTRY_MODE]            CHAR (1)        NULL,
    [PL_ORDER_NUMBER]                   VARCHAR (20)    NULL,
    [PL_FIRST_APPROVER]                 VARCHAR (4)     NULL,
    [PL_SECOND_APPROVER]                VARCHAR (4)     NULL,
    [PL_THIRD_APPROVER]                 VARCHAR (4)     NULL,
    [PL_SOURCE]                         VARCHAR (1)     DEFAULT ('') NULL,
    [PL_DETAIL_PRIMARY]                 INT             DEFAULT ((0)) NULL,
    [PL_ENTER_DUE_RECEIPT_DATE]         TINYINT         NULL,
    [PL_DELETE_DETAIL_LINE]             TINYINT         DEFAULT ((0)) NULL,
    [PL_HEADER_USER_CHAR1]              VARCHAR (20)    NULL,
    [PL_HEADER_USER_CHAR2]              VARCHAR (20)    NULL,
    [PL_HEADER_USER_CHAR3]              VARCHAR (100)   NULL,
    [PL_HEADER_USER_CHAR4]              VARCHAR (100)   NULL,
    [PL_HEADER_USER_FLAG1]              TINYINT         NULL,
    [PL_HEADER_USER_FLAG2]              TINYINT         NULL,
    [PL_HEADER_USER_DATE1]              DATETIME        NULL,
    [PL_HEADER_USER_DATE2]              DATETIME        NULL,
    [PL_HEADER_USER_NUMBER1]            FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_HEADER_USER_NUMBER2]            FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_DETAIL_USER_CHAR1]              VARCHAR (20)    NULL,
    [PL_DETAIL_USER_CHAR2]              VARCHAR (20)    NULL,
    [PL_DETAIL_USER_CHAR3]              VARCHAR (100)   NULL,
    [PL_DETAIL_USER_CHAR4]              VARCHAR (100)   NULL,
    [PL_DETAIL_USER_FLAG1]              TINYINT         NULL,
    [PL_DETAIL_USER_FLAG2]              TINYINT         NULL,
    [PL_DETAIL_USER_DATE1]              DATETIME        NULL,
    [PL_DETAIL_USER_DATE2]              DATETIME        NULL,
    [PL_DETAIL_USER_NUMBER1]            FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_DETAIL_USER_NUMBER2]            FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_TRAN_OPTIONS]                   VARCHAR (30)    NULL,
    [PL_HEADER_PRIMARY]                 INT             NULL,
    [PL_USER_SORT1]                     VARCHAR (20)    NULL,
    [PL_USER_SORT2]                     VARCHAR (20)    NULL,
    [PL_USER_SORT3]                     VARCHAR (20)    NULL,
    [PL_NOTE]                           TEXT            NULL,
    [PL_SURVEYOR]                       VARCHAR (30)    NULL,
    [PL_CIS_SENT_TO]                    VARCHAR (30)    NULL,
    [PL_CIS_SENT_DATE]                  DATETIME        DEFAULT ('') NULL,
    [PL_CIS_AUTHORISED]                 TINYINT         NULL,
    [PL_CIS_AUTHORISED_DATE]            DATETIME        DEFAULT ('') NULL,
    [PL_PARTNER]                        VARCHAR (10)    NULL,
    [PL_CO2_CLASSIFICATION_ID]          CHAR (4)        NULL,
    [PL_CO2_CONSUMPTION_DATE]           DATETIME        NULL,
    [PL_CO2_YEAR]                       SMALLINT        NULL,
    [PL_CO2_PERIOD]                     TINYINT         NULL,
    [PL_CO2_QUANTITY]                   FLOAT (53)      NULL,
    [PL_CO2_1ST_CATEGORY_PRIMARY]       INT             NULL,
    [PL_CO2_2ND_CATEGORY_PRIMARY]       INT             NULL,
    [PL_CO2_1ST_CATEGORY_CODE]          VARCHAR (6)     NULL,
    [PL_CO2_2ND_CATEGORY_CODE]          VARCHAR (6)     NULL,
    [PL_CO2_UNIT_OF_MEASURE]            VARCHAR (20)    NULL,
    [PL_CO2_XML]                        TEXT            NULL,
    [PL_CO2_EMISSIONS_GROUP_ID]         VARCHAR (2)     NULL,
    [PL_FORCE_VAT_RATE_REFRESH]         BIT             NULL,
    [PL_CO2_GHG_SCOPE]                  TINYINT         NULL,
    [PL_CO2_SORT_KEY1]                  VARCHAR (20)    NULL,
    [PL_CO2_SORT_KEY1_CREATE]           BIT             NULL,
    [PL_CO2_SORT_KEY2]                  VARCHAR (20)    NULL,
    [PL_CO2_SORT_KEY2_CREATE]           BIT             NULL,
    [PL_CO2_SORT_KEY3]                  VARCHAR (20)    NULL,
    [PL_CO2_SORT_KEY3_CREATE]           BIT             NULL,
    [PL_CO2_SORT_KEY4]                  VARCHAR (20)    NULL,
    [PL_CO2_SORT_KEY4_CREATE]           BIT             NULL,
    [PL_ALLOW_NO_CARBON]                BIT             NULL,
    [PL_ACCRUAL_NOMINAL_ACCOUNT]        VARCHAR (25)    NULL,
    [PL_ACCRUAL_NO_OF_PERIODS]          SMALLINT        NULL,
    [PL_ACCRUAL_SCHEDULE_START_DATE]    DATETIME        NULL,
    [PL_ACCRUAL_SCHEDULE_DATES_XML]     XML             NULL,
    [PL_USE_MULTIPLE_DUE_DATES]         BIT             NULL,
    [PL_MULTIPLE_DUE_DATE_DEPOSIT_PERC] DECIMAL (16, 2) NULL,
    [PL_MULTIPLE_DUE_DATE_DEPOSIT_VAL]  FLOAT (53)      NULL,
    [PL_MULTIPLE_DUE_DATE_START_DATE]   DATETIME        NULL,
    [PL_MULTIPLE_DUE_DATE_PAYMENT_NO]   INT             NULL,
    [PL_MULTIPLE_DUE_DATES_XML]         XML             NULL,
    [PL_SETTLE_DISCOUNT_CRN]            BIT             NULL,
    CONSTRAINT [PL_TRN_TEMP_PK] PRIMARY KEY CLUSTERED ([PL_TRAN_ID] ASC, [PL_DETAIL_LINE_NO] ASC)
);


GO
CREATE TRIGGER [dbo].[AA_PROCESS_PL_TRN_TEMP_T]
    ON [dbo].[PL_TRN_TEMP]
    WITH ENCRYPTION
    AFTER UPDATE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

