CREATE TABLE [dbo].[PL_TRANSACTION_NOTES] (
    [PT_NOTE]           TEXT         NULL,
    [PT_COPY_HEADERKEY] VARCHAR (20) NOT NULL,
    CONSTRAINT [PT_COPY_HEADERKEY_PK] PRIMARY KEY CLUSTERED ([PT_COPY_HEADERKEY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PT_COPY_HEADERKEY]
    ON [dbo].[PL_TRANSACTION_NOTES]([PT_COPY_HEADERKEY] ASC);

