CREATE TABLE [dbo].[POP_DETAIL_PLUGINS_DATETIME] (
    [PODPD_PRIMARY]     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PODPD_DETAIL_LINK] FLOAT (53)    NOT NULL,
    [PODPD_TAGNAME]     VARCHAR (100) NOT NULL,
    [PODPD_TAGVALUE]    DATETIME      NULL,
    CONSTRAINT [PODPD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PODPD_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [PODPD_DETAIL_LINK_FK] FOREIGN KEY ([PODPD_DETAIL_LINK]) REFERENCES [dbo].[POP_DETAIL] ([POD_PRIMARY]) ON DELETE CASCADE
);

