CREATE TABLE [dbo].[POP_DETAIL_ACCRUALS] (
    [PDA_PRIMARY]     FLOAT (53)   NOT NULL,
    [PDA_HEADER_LINK] VARCHAR (10) NOT NULL,
    [PDA_PERIODS]     SMALLINT     NOT NULL,
    [PDA_ACCRUAL_NOM] VARCHAR (25) NOT NULL,
    CONSTRAINT [PDA_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PDA_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [PDA_ACCRUAL_NOM_FK] FOREIGN KEY ([PDA_ACCRUAL_NOM]) REFERENCES [dbo].[NL_ACCOUNTS] ([NCODE]) ON UPDATE CASCADE,
    CONSTRAINT [PDA_PRIMARY_FK] FOREIGN KEY ([PDA_PRIMARY]) REFERENCES [dbo].[POP_DETAIL] ([POD_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [PDA_ACCRUAL_NOM]
    ON [dbo].[POP_DETAIL_ACCRUALS]([PDA_ACCRUAL_NOM] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [PDA_HEADER_LINK]
    ON [dbo].[POP_DETAIL_ACCRUALS]([PDA_HEADER_LINK] ASC) WITH (FILLFACTOR = 70);

