CREATE TABLE [dbo].[POP_TRN_TEMP] (
    [POP_ORDER_ID]                                INT             NOT NULL,
    [POP_ORDER_LINE_NO]                           INT             NOT NULL,
    [POP_STATUS_TEMP]                             TINYINT         NULL,
    [POP_SELECT_DEFAULT]                          VARCHAR (200)   NULL,
    [POP_ORDER_TYPE]                              VARCHAR (3)     NULL,
    [POP_ORDER_NUMBER]                            VARCHAR (10)    NULL,
    [POP_ACCOUNT]                                 VARCHAR (10)    NULL,
    [POP_SUBLEDGER]                               VARCHAR (10)    NULL,
    [POP_ORDER_DATE]                              DATETIME        DEFAULT ('') NULL,
    [POP_ORDER_YEAR]                              VARCHAR (1)     NULL,
    [POP_ORDER_PERIOD]                            TINYINT         NULL,
    [POP_DATE_REQUIRED]                           DATETIME        DEFAULT ('') NULL,
    [POP_SUPPLIER_REF]                            VARCHAR (20)    NULL,
    [POP_BATCH_REF]                               VARCHAR (10)    NULL,
    [POP_ORDER_DESCRIPTION]                       VARCHAR (30)    NULL,
    [POP_CURRENCYCODE]                            VARCHAR (6)     NULL,
    [POP_CURRENCYSYMBOL]                          VARCHAR (4)     NULL,
    [POP_CURRENCYTYPE]                            CHAR (1)        NULL,
    [POP_CURRENCY_RATE]                           DECIMAL (16, 6) NULL,
    [POP_EURO_TO_HOME_RATE]                       DECIMAL (16, 6) NULL,
    [POP_BASE2_RATE]                              DECIMAL (16, 6) NULL,
    [POP_EC_DELIVERY_TERMS]                       VARCHAR (3)     NULL,
    [POP_EC_TRANSACTION_NATURE]                   VARCHAR (2)     NULL,
    [POP_EC_TRANSPORT_METHOD]                     VARCHAR (1)     NULL,
    [POP_ORDER_STATUS]                            TINYINT         NULL,
    [POP_PRICE_KEY]                               TINYINT         NULL,
    [POP_TOTALDISC_PERC]                          DECIMAL (16, 2) NULL,
    [POP_HEADER_LINEDISC_PERC]                    DECIMAL (16, 2) NULL,
    [POP_MINIMUM_ORDER_VALUE]                     FLOAT (53)      NULL,
    [POP_SETTLEMENT_DISC1_PERC]                   DECIMAL (16, 2) NULL,
    [POP_SETTLEMENT_DAYS1]                        INT             NULL,
    [POP_SETTLEMENT_DISC2_PERC]                   DECIMAL (16, 2) NULL,
    [POP_SETTLEMENT_DAYS2]                        INT             NULL,
    [POP_DELIVERY_CHARGE]                         FLOAT (53)      NULL,
    [POP_DELIVERY_CHARGE_PERC]                    DECIMAL (16, 2) NULL,
    [POP_DELIVERY_METHOD]                         VARCHAR (20)    NULL,
    [POP_DUE_DAYS]                                INT             NULL,
    [POP_ANTICPATED_PAYMENT_DAYS]                 INT             NULL,
    [POP_ORDER_TERMS]                             VARCHAR (40)    NULL,
    [POP_DELIVERY_ADDRESS_TYPE]                   VARCHAR (2)     NULL,
    [POP_DELIVERY_ADDRESS_NO]                     INT             NULL,
    [POP_DELIVERY_ADDRESS]                        VARCHAR (160)   NULL,
    [POP_DELIVERY_TOWN]                           VARCHAR (30)    NULL,
    [POP_DELIVERY_COUNTY]                         VARCHAR (30)    NULL,
    [POP_DELIVERY_POSTCODE]                       VARCHAR (12)    NULL,
    [POP_DELIVERY_CONTACT]                        VARCHAR (30)    NULL,
    [POP_ORDER_ADDRESS_NO]                        INT             NULL,
    [POP_ORDER_ADDRESS]                           VARCHAR (160)   NULL,
    [POP_ORDER_TOWN]                              VARCHAR (30)    NULL,
    [POP_ORDER_COUNTY]                            VARCHAR (30)    NULL,
    [POP_ORDER_POSTCODE]                          VARCHAR (12)    NULL,
    [POP_ORDER_CONTACT]                           VARCHAR (30)    NULL,
    [POP_SUPPLIER_USER_KEY1]                      VARCHAR (20)    NULL,
    [POP_SUPPLIER_USER_KEY2]                      VARCHAR (20)    NULL,
    [POP_SUPPLIER_USER_KEY3]                      VARCHAR (20)    NULL,
    [POP_UPDATE_STOCK_ON_ORDER]                   BIT             NULL,
    [POP_GROSS_ENTRY_MODE]                        BIT             NULL,
    [POP_CURRENCY_ENTRY_MODE]                     CHAR (1)        NULL,
    [POP_ARCHIVE_FLAG]                            BIT             NULL,
    [POP_ALLOW_EMPTY_SUBANALYSIS]                 BIT             NULL,
    [POP_ALLOW_EMPTY_SERIAL_NO]                   BIT             NULL,
    [POP_ENTRY_TYPE]                              VARCHAR (1)     NULL,
    [POP_ITEM_CODE]                               VARCHAR (25)    NULL,
    [POP_SERIAL_NUMBER]                           VARCHAR (40)    NULL,
    [POP_SUB_ANALYSIS]                            VARCHAR (25)    NULL,
    [POP_QUANTITY]                                FLOAT (53)      NULL,
    [POP_PRICE_LINE]                              TINYINT         NULL,
    [POP_QUANTITY_UNIT]                           FLOAT (53)      NULL,
    [POP_HOME_UNIT_COST]                          FLOAT (53)      NULL,
    [POP_CURRENCY_UNIT_COST]                      FLOAT (53)      NULL,
    [POP_BASE2_UNIT_COST]                         FLOAT (53)      NULL,
    [POP_LINEDISC_PERC]                           DECIMAL (16, 2) NULL,
    [POP_HOME_LINEDISCVAL]                        FLOAT (53)      NULL,
    [POP_CURRENCY_LINEDISCVAL]                    FLOAT (53)      NULL,
    [POP_BASE2_LINEDISCVAL]                       FLOAT (53)      NULL,
    [POP_ANALYSIS]                                VARCHAR (25)    NULL,
    [POP_VAT_CODE]                                VARCHAR (4)     NULL,
    [POP_COSTHEADER]                              VARCHAR (10)    NULL,
    [POP_COSTCENTRE]                              VARCHAR (10)    NULL,
    [POP_LINE_DETAIL]                             VARCHAR (240)   NULL,
    [POP_LINE_REQUIRED_DATE]                      DATETIME        DEFAULT ('') NULL,
    [POP_TRANSACTION_USER_KEY1]                   VARCHAR (20)    NULL,
    [POP_TRANSACTION_USER_KEY2]                   VARCHAR (20)    NULL,
    [POP_TRANSACTION_USER_KEY3]                   VARCHAR (20)    NULL,
    [POP_USER_ID]                                 VARCHAR (4)     NULL,
    [POP_DETAIL_PRIMARY]                          INT             NULL,
    [POP_HEADER_USER_CHAR1]                       VARCHAR (20)    NULL,
    [POP_HEADER_USER_CHAR2]                       VARCHAR (20)    NULL,
    [POP_HEADER_USER_CHAR3]                       VARCHAR (100)   NULL,
    [POP_HEADER_USER_CHAR4]                       VARCHAR (100)   NULL,
    [POP_HEADER_USER_FLAG1]                       TINYINT         NULL,
    [POP_HEADER_USER_FLAG2]                       TINYINT         NULL,
    [POP_HEADER_USER_DATE1]                       DATETIME        DEFAULT ('') NULL,
    [POP_HEADER_USER_DATE2]                       DATETIME        DEFAULT ('') NULL,
    [POP_HEADER_USER_NUMBER1]                     FLOAT (53)      NULL,
    [POP_HEADER_USER_NUMBER2]                     FLOAT (53)      NULL,
    [POP_DETAIL_USER_CHAR1]                       VARCHAR (20)    NULL,
    [POP_DETAIL_USER_CHAR2]                       VARCHAR (20)    NULL,
    [POP_DETAIL_USER_CHAR3]                       VARCHAR (100)   NULL,
    [POP_DETAIL_USER_CHAR4]                       VARCHAR (100)   NULL,
    [POP_DETAIL_USER_FLAG1]                       TINYINT         NULL,
    [POP_DETAIL_USER_FLAG2]                       TINYINT         NULL,
    [POP_DETAIL_USER_DATE1]                       DATETIME        DEFAULT ('') NULL,
    [POP_DETAIL_USER_DATE2]                       DATETIME        DEFAULT ('') NULL,
    [POP_DETAIL_USER_NUMBER1]                     FLOAT (53)      NULL,
    [POP_DETAIL_USER_NUMBER2]                     FLOAT (53)      NULL,
    [POP_DELETE_DETAIL_LINE]                      TINYINT         NULL,
    [POP_DO_NOT_UPDATE_STOCK]                     TINYINT         NULL,
    [POP_SOURCE]                                  VARCHAR (1)     NULL,
    [POP_PRICE_CODE]                              VARCHAR (16)    NULL,
    [POP_TRAN_OPTIONS]                            VARCHAR (30)    NULL,
    [POP_DELIVERY_COUNTRY]                        VARCHAR (35)    NULL,
    [POP_ORDER_COUNTRY]                           VARCHAR (35)    NULL,
    [POP_ACTUAL_LINE_NO]                          INT             NULL,
    [POP_BUDGET_USER]                             VARCHAR (4)     NULL,
    [POP_STOCK_ANALYSIS]                          VARCHAR (25)    NULL,
    [POP_SUPPLIER_DEL_NOTE_NO]                    VARCHAR (15)    NULL,
    [POP_ALLOW_EMPTY_STOCK_ANALYSIS]              BIT             NULL,
    [POP_SERIAL_MULTI_LINK]                       INT             NULL,
    [POP_DELIVERY_CHARGE_LINE]                    BIT             NULL,
    [POP_APPLY_LINKED_ITEMS]                      TINYINT         NULL,
    [POP_SELECT_FIRST_SUB_ANALYSIS]               BIT             NULL,
    [POP_RTP_LINKS]                               TEXT            NULL,
    [POP_SURVEYOR]                                VARCHAR (30)    NULL,
    [POP_CIS_SENT_TO]                             VARCHAR (30)    NULL,
    [POP_CIS_SENT_DATE]                           DATETIME        NULL,
    [POP_CIS_AUTHORISED]                          TINYINT         NULL,
    [POP_CIS_AUTHORISED_DATE]                     DATETIME        NULL,
    [POP_PARTNER]                                 VARCHAR (10)    NULL,
    [POP_ORDER_INTERNAL_NOTES]                    VARCHAR (512)   NULL,
    [POP_DELIVERY_PHONE]                          VARCHAR (20)    NULL,
    [POP_DELIVERY_FAX]                            VARCHAR (20)    NULL,
    [POP_DELIVERY_EMAIL_ADDRESS]                  VARCHAR (64)    NULL,
    [POP_ORDER_PHONE]                             VARCHAR (20)    NULL,
    [POP_ORDER_FAX]                               VARCHAR (20)    NULL,
    [POP_ORDER_EMAIL_ADDRESS]                     VARCHAR (64)    NULL,
    [POP_SERVICE]                                 BIT             NULL,
    [POP_ORDER_STATUS_DESCRIPTION]                VARCHAR (20)    NULL,
    [POP_ACCRUAL_NOMINAL_ACCOUNT]                 VARCHAR (25)    NULL,
    [POP_ACCRUAL_NO_OF_PERIODS]                   SMALLINT        NULL,
    [POP_ACCRUAL_SCHEDULE_START_DATE]             DATETIME        NULL,
    [POP_ACCRUAL_SCHEDULE_DATES_XML]              XML             NULL,
    [POP_USE_MULTIPLE_DUE_DATES]                  BIT             NULL,
    [POP_MULTIPLE_DUE_DATE_DEPOSIT_PERC]          DECIMAL (16, 2) NULL,
    [POP_MULTIPLE_DUE_DATE_DEPOSIT_VAL]           FLOAT (53)      NULL,
    [POP_MULTIPLE_DUE_DATE_START_DATE]            DATETIME        NULL,
    [POP_MULTIPLE_DUE_DATE_PAYMENT_NO]            INT             NULL,
    [POP_MULTIPLE_DUE_DATES_XML]                  XML             NULL,
    [POP_MULTIPLE_DUE_DATES_RELATIVE_TO_TAX_DATE] BIT             NULL,
    [POP_PLUGIN_DETAIL_XML]                       XML             NULL,
    CONSTRAINT [POP_TRN_TEMP_PK] PRIMARY KEY CLUSTERED ([POP_ORDER_ID] ASC, [POP_ORDER_LINE_NO] ASC)
);


GO
CREATE TRIGGER [dbo].[AA_POP_TRN_TEMP_DELETE_T]
    ON [dbo].[POP_TRN_TEMP]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


GO
CREATE TRIGGER [dbo].[AA_PROCESS_POP_TRANS_TEMP_T]
    ON [dbo].[POP_TRN_TEMP]
    WITH ENCRYPTION
    AFTER UPDATE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

