CREATE TABLE [dbo].[POP_DETAIL_PLUGINS_VCHAR] (
    [PODPV_PRIMARY]     INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PODPV_DETAIL_LINK] FLOAT (53)     NOT NULL,
    [PODPV_TAGNAME]     VARCHAR (100)  NOT NULL,
    [PODPV_TAGVALUE]    VARCHAR (1000) NULL,
    CONSTRAINT [PODPV_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PODPV_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [PODPV_DETAIL_LINK_FK] FOREIGN KEY ([PODPV_DETAIL_LINK]) REFERENCES [dbo].[POP_DETAIL] ([POD_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PODPV_DETAIL_LINK]
    ON [dbo].[POP_DETAIL_PLUGINS_VCHAR]([PODPV_DETAIL_LINK] ASC, [PODPV_TAGNAME] ASC) WITH (FILLFACTOR = 70);

