CREATE TABLE [dbo].[PRC_PRICE_REC_PRICES] (
    [PRP_PRIMARY]          INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PRP_PR_LINK]          FLOAT (53)  NULL,
    [PRP_TYPE]             BIT         NULL,
    [PRP_PRICE_LINE]       TINYINT     NULL,
    [PRP_PRICE]            FLOAT (53)  NULL,
    [PRP_CURRENCY]         VARCHAR (4) NULL,
    [PRP_PRICE_C]          FLOAT (53)  NULL,
    [PRP_PRICE_BASE2]      FLOAT (53)  NULL,
    [PRP_PL_ANALYSIS_LINK] FLOAT (53)  NULL,
    [PRP_SL_ANALYSIS_LINK] FLOAT (53)  NULL,
    CONSTRAINT [PRP_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PRP_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [PRP_CURRENCY_FK] FOREIGN KEY ([PRP_CURRENCY]) REFERENCES [dbo].[SYS_CURRENCY_REC] ([CURREC_SYMBOL]),
    CONSTRAINT [PRP_PL_ANALYSIS_LINK_FK] FOREIGN KEY ([PRP_PL_ANALYSIS_LINK]) REFERENCES [dbo].[PL_ANALYSIS] ([PA_PRIMARY]),
    CONSTRAINT [PRP_PR_LINK_FK] FOREIGN KEY ([PRP_PR_LINK]) REFERENCES [dbo].[PRC_PRICE_RECS] ([PR_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [PRP_SL_ANALYSIS_LINK_FK] FOREIGN KEY ([PRP_SL_ANALYSIS_LINK]) REFERENCES [dbo].[SL_ANALYSIS] ([SA_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [PRP_PL_ANALYSIS_LINK]
    ON [dbo].[PRC_PRICE_REC_PRICES]([PRP_PL_ANALYSIS_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PRP_PR_LINK]
    ON [dbo].[PRC_PRICE_REC_PRICES]([PRP_PR_LINK] ASC, [PRP_TYPE] ASC, [PRP_PRICE_LINE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [PRP_SL_ANALYSIS_LINK]
    ON [dbo].[PRC_PRICE_REC_PRICES]([PRP_SL_ANALYSIS_LINK] ASC) WITH (FILLFACTOR = 70);

