CREATE TABLE [dbo].[PRC_PRICE_LANG] (
    [PRCLANG_LANGCODE]  VARCHAR (10)  NOT NULL,
    [PRCLANG_PRICECODE] VARCHAR (16)  NOT NULL,
    [PRCLANG_PRICENAME] VARCHAR (40)  NULL,
    [PRCLANG_PRICETEXT] VARCHAR (240) NULL,
    CONSTRAINT [PRC_PRICE_LANG_PK] PRIMARY KEY CLUSTERED ([PRCLANG_LANGCODE] ASC, [PRCLANG_PRICECODE] ASC)
);

