CREATE TABLE [dbo].[RTP_DETAIL] (
    [RPD_HEADER_REF]        VARCHAR (10)  NULL,
    [RPD_ORDER_REF]         VARCHAR (20)  NULL,
    [RPD_TYPE]              VARCHAR (1)   NULL,
    [RPD_STATUS]            TINYINT       DEFAULT ((0)) NULL,
    [RPD_ENTRY_TYPE]        VARCHAR (1)   NULL,
    [RPD_DATE]              DATETIME      NULL,
    [RPD_REQDATE]           DATETIME      NULL,
    [RPD_DETAIL]            VARCHAR (240) NULL,
    [RPD_QTYORD]            FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_QTYDELVD]          FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_QTYINVD]           FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_QTYUNIT]           FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_QTYRESERVED]       FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_QTYPRINTED]        FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_UNITCST]           FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_UNITCST_C]         FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_NETT]              FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_NETT_C]            FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_VATCODE]           VARCHAR (4)   NULL,
    [RPD_VATAMNT]           FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_TAX_C]             FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_ACQ_TAX]           FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_GROSS]             FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_GROSS_C]           FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_SD_MEMO]           FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_MATRIXCODE]        VARCHAR (20)  NULL,
    [RPD_TABLECODE]         VARCHAR (3)   NULL,
    [RPD_LINEDISC]          FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_L_DISCVAL]         FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_L_DISCVAL_C]       FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_T_DISCVAL]         FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_T_DISCVAL_C]       FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_SERIALTRACK]       TINYINT       DEFAULT ((0)) NULL,
    [RPD_SERIALNO]          VARCHAR (40)  NULL,
    [RPD_LOCATN]            VARCHAR (25)  NULL,
    [RPD_QUERY]             TINYINT       DEFAULT ((0)) NULL,
    [RPD_ARCHIVE]           TINYINT       DEFAULT ((0)) NULL,
    [RPD_PERIOD]            TINYINT       DEFAULT ((0)) NULL,
    [RPD_YEAR]              VARCHAR (1)   NULL,
    [RPD_BATCH_FLAG]        TINYINT       DEFAULT ((0)) NULL,
    [RPD_BATCH_REF]         VARCHAR (10)  NULL,
    [RPD_BATCH_POSTD]       TINYINT       DEFAULT ((0)) NULL,
    [RPD_LEDGER]            VARCHAR (2)   NULL,
    [RPD_LAST_ACTION]       VARCHAR (1)   NULL,
    [RPD_USER_PUTIN]        VARCHAR (4)   NULL,
    [RPD_DATE_PUTIN]        DATETIME      NULL,
    [RPD_MU_STATUS]         VARCHAR (1)   NULL,
    [RPD_ORDER_NO]          VARCHAR (10)  NULL,
    [RPD_ACCOUNT]           VARCHAR (10)  NULL,
    [RPD_ANALYSIS]          VARCHAR (25)  NULL,
    [RPD_STOCK_CODE]        VARCHAR (25)  NULL,
    [RPD_PRICE_CODE]        VARCHAR (16)  NULL,
    [RPD_COSTHEADER]        VARCHAR (10)  NULL,
    [RPD_COSTCENTRE]        VARCHAR (10)  NULL,
    [RPD_PRIMARY]           FLOAT (53)    NOT NULL,
    [RPD_VATNONDEDUCT]      FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_BUDGET_NL]         TINYINT       DEFAULT ((0)) NULL,
    [RPD_BUDGET_CST]        TINYINT       DEFAULT ((0)) NULL,
    [RPD_RTP_USERID]        VARCHAR (4)   NULL,
    [RPD_RTP_EXCEED_BUDGET] TINYINT       DEFAULT ((0)) NULL,
    [RPD_BUDGET_INDICATOR]  TINYINT       DEFAULT ((0)) NULL,
    [RPD_AUTHORISED_BYUSER] VARCHAR (4)   NULL,
    [RPD_OVER_BUDGET]       TINYINT       DEFAULT ((0)) NULL,
    [RPD_GROSS_MEMO]        FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_DIMENSION1]        VARCHAR (20)  NULL,
    [RPD_DIMENSION2]        VARCHAR (20)  NULL,
    [RPD_DIMENSION3]        VARCHAR (20)  NULL,
    [RPD_UNITCST_BASE2]     FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_NETT_BASE2]        FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_VAT_BASE2]         FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_GROSS_BASE2]       FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_L_DISC_BASE2]      FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_T_DISC_BASE2]      FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_ACQUISTN_BASE2]    FLOAT (53)    DEFAULT ((0)) NULL,
    [RPD_PODLINK]           INT           DEFAULT ((0)) NULL,
    [RPD_YEAR_LINK]         SMALLINT      NULL,
    [RPD_SERVICE]           BIT           DEFAULT ((0)) NOT NULL,
    [RPD_LINE_NUMBER]       INT           DEFAULT ((0)) NULL,
    CONSTRAINT [RPD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([RPD_PRIMARY] ASC),
    CONSTRAINT [RPD_YEAR_LINK_CK] CHECK ([RPD_YEAR] IS NOT NULL AND (upper([RPD_YEAR])='O' OR upper([RPD_YEAR])='N' OR upper([RPD_YEAR])='C' OR upper([RPD_YEAR])='L') AND [RPD_YEAR_LINK] IS NOT NULL OR ([RPD_YEAR] IS NULL OR (upper([RPD_YEAR])='O' OR upper([RPD_YEAR])='')) AND [RPD_YEAR_LINK] IS NULL),
    CONSTRAINT [RPD_YEAR_LINK_FK] FOREIGN KEY ([RPD_YEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);


GO
CREATE TRIGGER [dbo].[aa_rtp_detail_dt]
    ON [dbo].[RTP_DETAIL]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

