CREATE TABLE [dbo].[RTP_HEADER] (
    [RPH_TYPE]                VARCHAR (1)  NULL,
    [RPH_STATUS]              TINYINT      DEFAULT ((0)) NULL,
    [RPH_HEADER_REF]          VARCHAR (10) NULL,
    [RPH_ORDER_REF]           VARCHAR (20) NULL,
    [RPH_INV_DATE]            DATETIME     NULL,
    [RPH_INV_PERIOD]          TINYINT      DEFAULT ((0)) NULL,
    [RPH_INV_YEAR]            VARCHAR (1)  NULL,
    [RPH_DESCRIPTION]         VARCHAR (30) NULL,
    [RPH_YEAR]                VARCHAR (1)  NULL,
    [RPH_PERIOD]              TINYINT      DEFAULT ((0)) NULL,
    [RPH_DATE]                DATETIME     NULL,
    [RPH_REQUIRED]            DATETIME     NULL,
    [RPH_COMPLETED]           DATETIME     NULL,
    [RPH_NETT]                FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_NETT_C]              FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_VAT]                 FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_TAX_C]               FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_ACQ_TAX]             FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_GROSS]               FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_GROSS_C]             FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_DISC_LINE_P]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_T_DISCVAL]           FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_T_DISCVAL_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_DISC_TOT_P]          FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_SETT_DISC_1]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_SETT_DISC_2]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_SETT_DAYS_1]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_SETT_DAYS_2]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_L_DISCVAL]           FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_L_DISCVAL_C]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_CURR_RATE]           FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_CURR_CODE]           VARCHAR (4)  NULL,
    [RPH_CURR_RTCH]           TINYINT      DEFAULT ((0)) NULL,
    [RPH_IMPEXP_CODE]         VARCHAR (1)  NULL,
    [RPH_EC_DEL_TERM]         VARCHAR (3)  NULL,
    [RPH_EC_T_NATURE]         VARCHAR (2)  NULL,
    [RPH_EC_T_MODE]           VARCHAR (1)  NULL,
    [RPH_DEL_CHARGE]          FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_DEL_CHG_PCT]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_DEL_METHOD]          VARCHAR (20) NULL,
    [RPH_GRN_NOTE_NO]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_DEL_DATE]            DATETIME     NULL,
    [RPH_MIN_VAL]             FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_DUE_DAYS]            FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_TERMS]               VARCHAR (40) NULL,
    [RPH_A_P_DAYS]            FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_PRICE_KEY]           TINYINT      DEFAULT ((0)) NULL,
    [RPH_INV_ADD]             FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_DEL_ADD]             FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_NO_OF_LINES]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_LINES_INVD]          FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_LINES_DELVD]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_OS_INVVAL]           FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_OS_DELVAL]           FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_OS_INVCVAL]          FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_OS_DELCVAL]          FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_ARCHIVE]             TINYINT      DEFAULT ((0)) NULL,
    [RPH_PRIORITY]            TINYINT      DEFAULT ((0)) NULL,
    [RPH_QUERY_FLAG]          TINYINT      DEFAULT ((0)) NULL,
    [RPH_LAST_ACTION]         VARCHAR (1)  NULL,
    [RPH_USER_PUTIN]          VARCHAR (4)  NULL,
    [RPH_DATE_PUTIN]          DATETIME     NULL,
    [RPH_MU_STATUS]           VARCHAR (1)  NULL,
    [RPH_SUSORT]              VARCHAR (20) NULL,
    [RPH_USER1]               VARCHAR (20) NULL,
    [RPH_USER2]               VARCHAR (20) NULL,
    [RPH_USER3]               VARCHAR (20) NULL,
    [RPH_ACC_STATUS]          VARCHAR (11) NULL,
    [RPH_BATCH_FLAG]          TINYINT      DEFAULT ((0)) NULL,
    [RPH_BATCH_REF]           VARCHAR (10) NULL,
    [RPH_BATCH_POSTD]         VARCHAR (1)  NULL,
    [RPH_INVSTAT]             TINYINT      DEFAULT ((0)) NULL,
    [RPH_DELSTAT]             TINYINT      DEFAULT ((0)) NULL,
    [RPH_ORDUPDATED]          TINYINT      DEFAULT ((0)) NULL,
    [RPH_EQ_STATUS]           VARCHAR (1)  NULL,
    [RPH_GRNUPDATED]          DATETIME     NULL,
    [RPH_ORDER_NUMBR]         VARCHAR (10) NULL,
    [RPH_LEDGER]              VARCHAR (2)  NULL,
    [RPH_ACCOUNT]             VARCHAR (10) NULL,
    [RPH_REBUILDNUM]          FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_PRIMARY]             FLOAT (53)   NOT NULL,
    [RPH_SUB_LEDGER]          VARCHAR (10) NULL,
    [RPH_BUDGET_STATUS]       TINYINT      DEFAULT ((0)) NULL,
    [RPH_ORIGINAL_USER_PUTIN] VARCHAR (4)  NULL,
    [RPH_NETT_BASE2]          FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_VAT_BASE2]           FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_GROSS_BASE2]         FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_L_DISC_BASE2]        FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_T_DISC_BASE2]        FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_BASE2_RATE]          FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_TRI_RATE1]           FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_BASE2_RATECHNG]      TINYINT      DEFAULT ((0)) NULL,
    [RPH_TRI_RATECHNG1]       TINYINT      DEFAULT ((0)) NULL,
    [RPH_ACQUISTN_BASE2]      FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_INV_VAL_BASE2]       FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_DEL_VAL_BASE2]       FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_CURR_TYPE]           VARCHAR (1)  NULL,
    [RPH_TRI_RATE2]           FLOAT (53)   DEFAULT ((0)) NULL,
    [RPH_TRI_RATECHNG2]       TINYINT      DEFAULT ((0)) NULL,
    [RPH_SOURCE]              VARCHAR (1)  NULL,
    [RPH_TRAN_OPTIONS]        VARCHAR (30) NULL,
    [RPH_YEAR_LINK]           SMALLINT     NULL,
    [RPH_WFF_APPROVAL_STATUS] SMALLINT     DEFAULT ((0)) NULL,
    CONSTRAINT [RPH_PRIMARY_PK] PRIMARY KEY CLUSTERED ([RPH_PRIMARY] ASC),
    CONSTRAINT [RPH_YEAR_LINK_CK] CHECK ([RPH_YEAR] IS NOT NULL AND (upper([RPH_YEAR])='O' OR upper([RPH_YEAR])='N' OR upper([RPH_YEAR])='C' OR upper([RPH_YEAR])='L') AND [RPH_YEAR_LINK] IS NOT NULL OR ([RPH_YEAR] IS NULL OR (upper([RPH_YEAR])='O' OR upper([RPH_YEAR])='')) AND [RPH_YEAR_LINK] IS NULL),
    CONSTRAINT [RPH_YEAR_LINK_FK] FOREIGN KEY ([RPH_YEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);


GO
CREATE TRIGGER [dbo].[aa_rtp_header_dt]
    ON [dbo].[RTP_HEADER]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

