CREATE TABLE [dbo].[RTP_DETAIL_PLUGINS_DATETIME] (
    [RPDPD_PRIMARY]     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RPDPD_DETAIL_LINK] FLOAT (53)    NOT NULL,
    [RPDPD_TAGNAME]     VARCHAR (100) NOT NULL,
    [RPDPD_TAGVALUE]    DATETIME      NULL,
    CONSTRAINT [RPDPD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([RPDPD_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [RPDPD_DETAIL_LINK_FK] FOREIGN KEY ([RPDPD_DETAIL_LINK]) REFERENCES [dbo].[RTP_DETAIL] ([RPD_PRIMARY]) ON DELETE CASCADE
);

