CREATE TABLE [dbo].[RTP_DETAIL_PLUGINS_VCHAR] (
    [RPDPV_PRIMARY]     INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RPDPV_DETAIL_LINK] FLOAT (53)     NOT NULL,
    [RPDPV_TAGNAME]     VARCHAR (100)  NOT NULL,
    [RPDPV_TAGVALUE]    VARCHAR (1000) NULL,
    CONSTRAINT [RPDPV_PRIMARY_PK] PRIMARY KEY CLUSTERED ([RPDPV_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [RPDPV_DETAIL_LINK_FK] FOREIGN KEY ([RPDPV_DETAIL_LINK]) REFERENCES [dbo].[RTP_DETAIL] ([RPD_PRIMARY]) ON DELETE CASCADE
);

