CREATE TABLE [dbo].[SDK_PLUGIN_ATTR_LINK] (
    [PIATTR_PRIMARY]        FLOAT (53)  NOT NULL,
    [PIATTR_RBSYST_PRIMARY] FLOAT (53)  NULL,
    [PIATTR_PLUGIN_CODE]    VARCHAR (5) NULL,
    CONSTRAINT [PIATTR_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PIATTR_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [PIATTR_RBSYST_PRIMARY]
    ON [dbo].[SDK_PLUGIN_ATTR_LINK]([PIATTR_PLUGIN_CODE] ASC, [PIATTR_RBSYST_PRIMARY] ASC) WITH (FILLFACTOR = 70);

