CREATE TABLE [dbo].[SDK_WMS_WO_PICK_REQUESTS] (
    [WMWPR_COMPONENT_LINK]      INT          NOT NULL,
    [WMWPR_PICK_REQUEST_NUMBER] INT          NOT NULL,
    [WMWPR_STOCK_LINK]          FLOAT (53)   NOT NULL,
    [WMWPR_QUANTITY]            FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [WMWPR_ALLOCATION_QUANTITY] FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [WMWPR_STATUS]              TINYINT      NULL,
    [WMWPR_SITE]                VARCHAR (10) NULL,
    [WMWPR_QUANTITY_ISSUED]     FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [WMWPR_USER_PUTIN]          VARCHAR (4)  NULL,
    [WMWPR_DATE_PUTIN]          DATETIME     DEFAULT (getdate()) NULL,
    [WMWPR_FILE_NAME]           VARCHAR (50) NULL,
    CONSTRAINT [SDK_WMS_WO_PICK_REQUESTS_PK] PRIMARY KEY CLUSTERED ([WMWPR_COMPONENT_LINK] ASC, [WMWPR_PICK_REQUEST_NUMBER] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_WMSPR_COMPONENT_LINK] FOREIGN KEY ([WMWPR_COMPONENT_LINK]) REFERENCES [dbo].[WO_COMPONENTS] ([WC_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [WMWPR_STOCK_LINK]
    ON [dbo].[SDK_WMS_WO_PICK_REQUESTS]([WMWPR_STOCK_LINK] ASC, [WMWPR_STATUS] ASC)
    INCLUDE([WMWPR_QUANTITY], [WMWPR_ALLOCATION_QUANTITY]) WITH (FILLFACTOR = 70);

