CREATE TABLE [dbo].[SDK_SLPL_TRANSACTION_LINKS] (
    [SLPLTL_PRIMARY]        INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SLPLTL_PT_LINK]        FLOAT (53) NOT NULL,
    [SLPLTL_ST_LINK]        FLOAT (53) NOT NULL,
    [SLPLTL_PT_CREDIT_LINK] FLOAT (53) NULL,
    [SLPLTL_ST_CREDIT_LINK] FLOAT (53) NULL,
    CONSTRAINT [SLPLTL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SLPLTL_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SLPLTL_PT_CREDIT_LINK_FK] FOREIGN KEY ([SLPLTL_PT_CREDIT_LINK]) REFERENCES [dbo].[PL_TRANSACTIONS] ([PT_PRIMARY]) ON DELETE SET NULL,
    CONSTRAINT [SLPLTL_PT_LINK_FK] FOREIGN KEY ([SLPLTL_PT_LINK]) REFERENCES [dbo].[PL_TRANSACTIONS] ([PT_PRIMARY]) ON UPDATE CASCADE,
    CONSTRAINT [SLPLTL_ST_CREDIT_LINK_FK] FOREIGN KEY ([SLPLTL_ST_CREDIT_LINK]) REFERENCES [dbo].[SL_TRANSACTIONS] ([ST_PRIMARY]) ON DELETE SET NULL,
    CONSTRAINT [SLPLTL_ST_LINK_FK] FOREIGN KEY ([SLPLTL_ST_LINK]) REFERENCES [dbo].[SL_TRANSACTIONS] ([ST_PRIMARY]) ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [SLPLTL_PT_LINK]
    ON [dbo].[SDK_SLPL_TRANSACTION_LINKS]([SLPLTL_PT_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SLPLTL_ST_LINK]
    ON [dbo].[SDK_SLPL_TRANSACTION_LINKS]([SLPLTL_ST_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SLPLTL_PT_CREDIT_LINK]
    ON [dbo].[SDK_SLPL_TRANSACTION_LINKS]([SLPLTL_PT_CREDIT_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SLPLTL_ST_CREDIT_LINK]
    ON [dbo].[SDK_SLPL_TRANSACTION_LINKS]([SLPLTL_ST_CREDIT_LINK] ASC) WITH (FILLFACTOR = 70);

