CREATE TABLE [dbo].[SDK_WMS_REVIEW_DETAIL] (
    [WMTD_PRIMARY]              INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMTD_WMTH_PRIMARY]         INT          NULL,
    [WMTD_STKCODE]              VARCHAR (25) NULL,
    [WMTD_PALLET_REF]           VARCHAR (20) NULL,
    [WMTD_LOCATION]             VARCHAR (30) NULL,
    [WMTD_OUTER_QTY]            FLOAT (53)   NULL,
    [WMTD_OUTER_NAME]           VARCHAR (20) NULL,
    [WMTD_INNER_QTY]            FLOAT (53)   NULL,
    [WMTD_INNER_NAME]           VARCHAR (20) NULL,
    [WMTD_PACK_QTY]             FLOAT (53)   NULL,
    [WMTD_PACK_NAME]            VARCHAR (20) NULL,
    [WMTD_ITEM_QTY]             FLOAT (53)   NULL,
    [WMTD_ITEM_NAME]            VARCHAR (20) NULL,
    [WMTD_WEIGHT]               FLOAT (53)   NULL,
    [WMTD_CONDITION]            VARCHAR (5)  NULL,
    [WMTD_COMMENTS]             VARCHAR (50) NULL,
    [WMTD_HOLD_REF]             VARCHAR (20) NULL,
    [WMTD_BATCH]                VARCHAR (20) NULL,
    [WMTD_BATCH2]               VARCHAR (20) NULL,
    [WMTD_SERIAL]               VARCHAR (20) NULL,
    [WMTD_SERIAL2]              VARCHAR (20) NULL,
    [WMTD_DATE1]                DATETIME     NULL,
    [WMTD_DATE2]                DATETIME     NULL,
    [WMTD_DATE3]                DATETIME     NULL,
    [WMTD_DATE4]                DATETIME     NULL,
    [WMTD_CUS_REFERENCE]        VARCHAR (30) NULL,
    [WMTD_ROLL_LENGTH]          FLOAT (53)   NULL,
    [WMTD_ROLL_INFO]            VARCHAR (14) NULL,
    [WMTD_BONDED]               TINYINT      NULL,
    [WMTD_CUSTOMS_REF]          VARCHAR (20) NULL,
    [WMTD_COLOUR]               VARCHAR (20) NULL,
    [WMTD_SIZE]                 VARCHAR (20) NULL,
    [WMTD_VOL_LITRES]           FLOAT (53)   NULL,
    [WMTD_GROSS_WEIGHT]         FLOAT (53)   NULL,
    [WMTD_LENGTH]               FLOAT (53)   NULL,
    [WMTD_HEIGHT]               FLOAT (53)   NULL,
    [WMTD_RANGE_FROM]           FLOAT (53)   NULL,
    [WMTD_RANGE_TO]             FLOAT (53)   NULL,
    [WMTD_COO]                  VARCHAR (3)  NULL,
    [WMTD_CWC]                  VARCHAR (3)  NULL,
    [WMTD_LINE_REF]             VARCHAR (20) NULL,
    [WMTD_REF1]                 VARCHAR (20) NULL,
    [WMTD_REF2]                 VARCHAR (20) NULL,
    [WMTD_REF3]                 VARCHAR (20) NULL,
    [WMTD_REF4]                 VARCHAR (20) NULL,
    [WMTD_REF5]                 VARCHAR (20) NULL,
    [WMTD_REF6]                 VARCHAR (20) NULL,
    [WMTD_REF7]                 VARCHAR (20) NULL,
    [WMTD_REF8]                 VARCHAR (20) NULL,
    [WMTD_REF9]                 VARCHAR (20) NULL,
    [WMTD_REF10]                VARCHAR (20) NULL,
    [WMTD_DATE]                 DATETIME     NULL,
    [WMTD_STATE]                VARCHAR (3)  NULL,
    [WMTD_SUPPLIER]             VARCHAR (10) NULL,
    [WMTD_STATUS]               TINYINT      DEFAULT ((0)) NULL,
    [WMTD_ORIGINAL_DETAIL_LINE] INT          NULL,
    CONSTRAINT [PK_SDK_WMS_REVIEW_DETAIL] PRIMARY KEY CLUSTERED ([WMTD_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [WMTD_WMTH_PRIMARY]
    ON [dbo].[SDK_WMS_REVIEW_DETAIL]([WMTD_WMTH_PRIMARY] ASC, [WMTD_LINE_REF] ASC) WITH (FILLFACTOR = 70);

