CREATE TABLE [dbo].[SDK_WMS_SOP_PICK_REQUEST_SNOS] (
    [WMSPRS_ORDER_DETAIL_LINK]   FLOAT (53)   NOT NULL,
    [WMSPRS_PICK_REQUEST_NUMBER] INT          NOT NULL,
    [WMSPRS_SERIAL_NUMBER]       VARCHAR (40) NOT NULL,
    [WMSPRS_STATUS]              TINYINT      DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SDK_WMS_SOP_PICK_REQUEST_SNOS_PK] PRIMARY KEY CLUSTERED ([WMSPRS_ORDER_DETAIL_LINK] ASC, [WMSPRS_PICK_REQUEST_NUMBER] ASC, [WMSPRS_SERIAL_NUMBER] ASC),
    CONSTRAINT [SDK_WMS_SOP_PICK_REQUEST_SNOS_FK] FOREIGN KEY ([WMSPRS_ORDER_DETAIL_LINK], [WMSPRS_PICK_REQUEST_NUMBER]) REFERENCES [dbo].[SDK_WMS_SOP_PICK_REQUESTS] ([WMSPR_ORDER_DETAIL_LINK], [WMSPR_PICK_REQUEST_NUMBER]) ON DELETE CASCADE
);

