CREATE TABLE [dbo].[SDK_WMS_STOCK_RESERVATION_HISTORY] (
    [WMRH_PRIMARY]           INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMRH_ORDER_NUMBER]      FLOAT (53)   NOT NULL,
    [WMRH_ORDER_DETAIL_LINK] FLOAT (53)   NOT NULL,
    [WMRH_STOCK_LINK]        FLOAT (53)   NOT NULL,
    [WMRH_QUANTITY]          FLOAT (53)   NOT NULL,
    [WMRH_USER_PUTIN]        VARCHAR (4)  NULL,
    [WMRH_DATE_PUTIN]        DATETIME     DEFAULT (getdate()) NULL,
    [WMRH_SITE]              VARCHAR (10) NULL,
    CONSTRAINT [SDK_WMS_STOCK_RESERVATION_HISTORY_PK] PRIMARY KEY CLUSTERED ([WMRH_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [WMRH_STOCK_LINK]
    ON [dbo].[SDK_WMS_STOCK_RESERVATION_HISTORY]([WMRH_STOCK_LINK] ASC, [WMRH_SITE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [WMRH_ORDER_DETAIL_LINK]
    ON [dbo].[SDK_WMS_STOCK_RESERVATION_HISTORY]([WMRH_ORDER_DETAIL_LINK] ASC) WITH (FILLFACTOR = 70);

