CREATE TABLE [dbo].[SDK_WMS_EXPORT_MAP] (
    [WMSF_PRIMARY] INT           IDENTITY (1, 1) NOT NULL,
    [WMSF_TYPE]    VARCHAR (3)   NULL,
    [WMSF_ORDER]   INT           NULL,
    [WMSF_MAPPING] VARCHAR (100) NULL,
    [WMSF_DESC]    VARCHAR (100) NULL,
    [WMSF_LOCKED]  TINYINT       NULL
);

