CREATE TABLE [dbo].[SDK_SL_PL_CONTRA_RECS] (
    [SPC_PRIMARY] INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SPC_CUCODE]  VARCHAR (10) NULL,
    [SPC_SUCODE]  VARCHAR (10) NULL,
    CONSTRAINT [SPC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SPC_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SPC_SUCODE_FK] FOREIGN KEY ([SPC_SUCODE]) REFERENCES [dbo].[PL_ACCOUNTS] ([SUCODE]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [SPC_CUCODE]
    ON [dbo].[SDK_SL_PL_CONTRA_RECS]([SPC_CUCODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SPC_SUCODE]
    ON [dbo].[SDK_SL_PL_CONTRA_RECS]([SPC_SUCODE] ASC) WITH (FILLFACTOR = 70);

