CREATE TABLE [dbo].[SDK_RPTB_SYS_ATTR_DETAIL] (
    [RBSYSD_PRIMARY]        INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RBSYSD_NAME]           VARCHAR (20) NULL,
    [RBSYSD_TYPE]           VARCHAR (1)  NULL,
    [RBSYSD_HEADER]         INT          NULL,
    [RBSYSD_LOOKUP_CONTENT] TEXT         NULL,
    [RBSYSD_WRITE]          TINYINT      NULL,
    [RBSYSD_COMPULSORY]     TINYINT      NULL,
    CONSTRAINT [RBSYSD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([RBSYSD_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

