CREATE TABLE [dbo].[SDK_SLPL_ACCR_HEADER] (
    [SLPLACC_PRIMARY]    INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SLPLACC_USERID]     VARCHAR (5) NULL,
    [SLPLACC_LEDGER]     VARCHAR (2) NOT NULL,
    [SLPLACC_PT_LINK]    FLOAT (53)  NULL,
    [SLPLACC_ST_LINK]    FLOAT (53)  NULL,
    [SLPLACC_POP_LINK]   FLOAT (53)  NULL,
    [SLPLACC_SOP_LINK]   FLOAT (53)  NULL,
    [SLPLACC_NT_LINK]    FLOAT (53)  NULL,
    [SLPLACC_START_DATE] DATETIME    NULL,
    CONSTRAINT [SLPLACC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SLPLACC_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SLPLACC_NT_LINK_FK] FOREIGN KEY ([SLPLACC_NT_LINK]) REFERENCES [dbo].[NL_TRANSACTIONS] ([NT_PRIMARY]),
    CONSTRAINT [SLPLACC_POP_LINK_FK] FOREIGN KEY ([SLPLACC_POP_LINK]) REFERENCES [dbo].[POP_HEADER] ([POH_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [SLPLACC_PT_LINK_FK] FOREIGN KEY ([SLPLACC_PT_LINK]) REFERENCES [dbo].[PL_TRANSACTIONS] ([PT_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [SLPLACC_SOP_LINK_FK] FOREIGN KEY ([SLPLACC_SOP_LINK]) REFERENCES [dbo].[ORD_HEADER] ([OH_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [SLPLACC_ST_LINK_FK] FOREIGN KEY ([SLPLACC_ST_LINK]) REFERENCES [dbo].[SL_TRANSACTIONS] ([ST_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [SLPLACC_NT_LINK]
    ON [dbo].[SDK_SLPL_ACCR_HEADER]([SLPLACC_NT_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SLPLACC_POP_LINK]
    ON [dbo].[SDK_SLPL_ACCR_HEADER]([SLPLACC_POP_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SLPLACC_PT_LINK]
    ON [dbo].[SDK_SLPL_ACCR_HEADER]([SLPLACC_PT_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SLPLACC_SOP_LINK]
    ON [dbo].[SDK_SLPL_ACCR_HEADER]([SLPLACC_SOP_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SLPLACC_ST_LINK]
    ON [dbo].[SDK_SLPL_ACCR_HEADER]([SLPLACC_ST_LINK] ASC) WITH (FILLFACTOR = 70);

