CREATE TABLE [dbo].[SDK_WMS_REVIEW_HEADER] (
    [WMTH_PRIMARY]        INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMTH_TYPE]           VARCHAR (20)  NULL,
    [WMTH_REFERENCE]      VARCHAR (20)  NULL,
    [WMTH_SUBTYPE]        VARCHAR (20)  NULL,
    [WMTH_ACCOUNT]        VARCHAR (10)  NULL,
    [WMTH_SUBTYPE2]       VARCHAR (10)  NULL,
    [WMTH_SITE]           VARCHAR (10)  NULL,
    [WMTH_DATE1]          DATETIME      NULL,
    [WMTH_TIME2]          VARCHAR (40)  NULL,
    [WMTH_DATE2]          DATETIME      NULL,
    [WMTH_LINK]           INT           NULL,
    [WMTH_REF1]           VARCHAR (20)  NULL,
    [WMTH_REF2]           VARCHAR (20)  NULL,
    [WMTH_REF3]           VARCHAR (20)  NULL,
    [WMTH_REF4]           VARCHAR (20)  NULL,
    [WMTH_REF5]           VARCHAR (20)  NULL,
    [WMTH_REF6]           VARCHAR (20)  NULL,
    [WMTH_REF7]           VARCHAR (20)  NULL,
    [WMTH_REF8]           VARCHAR (20)  NULL,
    [WMTH_REF9]           VARCHAR (20)  NULL,
    [WMTH_REF10]          VARCHAR (20)  NULL,
    [WMTH_GETFROM]        VARCHAR (20)  NULL,
    [WMTH_NOTES]          VARCHAR (200) NULL,
    [WMTH_SUPPLIER]       VARCHAR (10)  NULL,
    [WMTH_STATUS]         INT           NULL,
    [WMTH_LOCK]           VARCHAR (10)  NULL,
    [WMTH_HAULIER]        VARCHAR (8)   NULL,
    [WMTH_DATE_IMPORTED]  DATETIME      DEFAULT (getdate()) NULL,
    [WMTH_DATE_PROCESSED] DATETIME      NULL,
    [WMTH_ORIGINAL_REF1]  VARCHAR (20)  NULL,
    [WMTH_CUSTOMER]       VARCHAR (10)  NULL,
    CONSTRAINT [PK_SDK_WMS_REVIEW_HEADER] PRIMARY KEY CLUSTERED ([WMTH_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [WMTH_STATUS]
    ON [dbo].[SDK_WMS_REVIEW_HEADER]([WMTH_STATUS] ASC, [WMTH_TYPE] ASC) WITH (FILLFACTOR = 70);

