CREATE TABLE [dbo].[SDK_WMS_INTEGRATION_BACK_LOG] (
    [WMSI_PRIMARY]   INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMSI_TYPE]      VARCHAR (3)  NULL,
    [WMSI_ID]        INT          NULL,
    [WMSI_STATUS]    TINYINT      CONSTRAINT [df_WMSI_STATUS] DEFAULT ((0)) NULL,
    [WMSI_LOCKED]    VARCHAR (10) CONSTRAINT [df_WMSI_LOCKED] DEFAULT ('') NULL,
    [WMSI_LOCKED_AT] DATETIME     NULL,
    CONSTRAINT [PK_SDK_WMS_INTEGRATION_BACK_LOG] PRIMARY KEY CLUSTERED ([WMSI_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [WMSI_LOCKED]
    ON [dbo].[SDK_WMS_INTEGRATION_BACK_LOG]([WMSI_STATUS] ASC, [WMSI_TYPE] ASC, [WMSI_LOCKED_AT] ASC)
    INCLUDE([WMSI_LOCKED]);

