CREATE TABLE [dbo].[SDK_WMS_SEND_STATUS] (
    [WMSP_PRIMARY]                  INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMSP_TRAN_PRIMARY]             INT           NULL,
    [WMSP_TRAN_TYPE]                VARCHAR (3)   NULL,
    [WMSP_STATUS]                   INT           NULL,
    [WMSP_DELIVERY_INSTRUCTION]     VARCHAR (500) NULL,
    [WMSP_PICK_INSTRUCTION]         VARCHAR (500) NULL,
    [WMSP_AUTO_ALLOCATE_STOCK]      BIT           DEFAULT ((0)) NOT NULL,
    [WMSP_LAST_USER_TO_SEND_TO_WMS] VARCHAR (4)   NULL,
    [WMSP_DATE_OF_LAST_SEND_TO_WMS] DATETIME      NULL,
    CONSTRAINT [PK_SDK_WMS_SEND_STATUS] PRIMARY KEY CLUSTERED ([WMSP_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [WMSP_TRAN_PRIMARY]
    ON [dbo].[SDK_WMS_SEND_STATUS]([WMSP_TRAN_PRIMARY] ASC, [WMSP_TRAN_TYPE] ASC) WITH (FILLFACTOR = 70);

