CREATE TABLE [dbo].[SDK_WMS_SEND_STATUS_DETAIL] (
    [WMSPD_PRIMARY]      INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMSPD_WMSP_PRIMARY] INT          NULL,
    [WMSPD_TRAN_PRIMARY] INT          NULL,
    [WMSPD_ITEM_QTY]     FLOAT (53)   NULL,
    [WMSPD_PACK_QTY]     FLOAT (53)   NULL,
    [WMSPD_INNER_QTY]    FLOAT (53)   NULL,
    [WMSPD_OUTER_QTY]    FLOAT (53)   NULL,
    [WMSPD_SITE]         VARCHAR (10) NULL,
    [WMSPD_COLOUR]       VARCHAR (20) NULL,
    [WMSPD_SIZE]         VARCHAR (20) NULL,
    [WMSPD_BATCH]        VARCHAR (30) NULL,
    [WMSPD_LOC1]         VARCHAR (30) NULL,
    [WMSPD_LOC2]         VARCHAR (30) NULL,
    [WMSPD_LOC3]         VARCHAR (30) NULL,
    [WMSPD_LOC4]         VARCHAR (30) NULL,
    [WMSPD_LOC5]         VARCHAR (30) NULL,
    [WMSPD_LOC6]         VARCHAR (30) NULL,
    [WMSPD_STATUS]       TINYINT      NULL,
    [WMSPD_HOLD_REF]     VARCHAR (20) NULL,
    [WMSPD_CHILD_WO]     BIT          DEFAULT ((0)) NULL,
    CONSTRAINT [PK_SDK_WMS_SEND_STATUS_DETAIL] PRIMARY KEY CLUSTERED ([WMSPD_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [WMSPD_WMSP_PRIMARY]
    ON [dbo].[SDK_WMS_SEND_STATUS_DETAIL]([WMSPD_WMSP_PRIMARY] ASC, [WMSPD_TRAN_PRIMARY] ASC) WITH (FILLFACTOR = 70);

