CREATE TABLE [dbo].[SDK_WMS_PR_MANIFEST_DETAILS] (
    [WMPRMD_POP_DETAIL_LINK]   FLOAT (53) NOT NULL,
    [WMPRMD_MANIFEST_LINK]     INT        NOT NULL,
    [WMPRMD_QUANTITY]          FLOAT (53) DEFAULT ((0)) NOT NULL,
    [WMPRMD_QUANTITY_RECEIVED] FLOAT (53) DEFAULT ((0)) NOT NULL,
    [WMPRMD_STATUS]            TINYINT    DEFAULT ((0)) NOT NULL,
    [WMPRMD_LINE_NO]           INT        NOT NULL,
    CONSTRAINT [SDK_WMS_PR_MANIFEST_DETAILS_PK] PRIMARY KEY CLUSTERED ([WMPRMD_POP_DETAIL_LINK] ASC, [WMPRMD_MANIFEST_LINK] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [WMPRMD_MANIFEST_LINK]
    ON [dbo].[SDK_WMS_PR_MANIFEST_DETAILS]([WMPRMD_MANIFEST_LINK] ASC) WITH (FILLFACTOR = 70);

