CREATE TABLE [dbo].[SDK_WMS_STOCK_WO_RESERVATION_HISTORY] (
    [WMWRH_PRIMARY]         INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMWRH_WO_ORDER_NUMBER] INT          NOT NULL,
    [WMWRH_COMPONENT_LINK]  INT          NOT NULL,
    [WMWRH_STOCK_LINK]      FLOAT (53)   NOT NULL,
    [WMWRH_QUANTITY]        FLOAT (53)   NOT NULL,
    [WMWRH_USER_PUTIN]      VARCHAR (4)  NULL,
    [WMWRH_DATE_PUTIN]      DATETIME     DEFAULT (getdate()) NULL,
    [WMWRH_SITE]            VARCHAR (10) NULL,
    CONSTRAINT [SDK_WMS_STOCK_WO_RESERVATION_HISTORY_PK] PRIMARY KEY CLUSTERED ([WMWRH_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [WMWRH_STOCK_LINK]
    ON [dbo].[SDK_WMS_STOCK_WO_RESERVATION_HISTORY]([WMWRH_STOCK_LINK] ASC, [WMWRH_SITE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [WMWRH_COMPONENT_LINK]
    ON [dbo].[SDK_WMS_STOCK_WO_RESERVATION_HISTORY]([WMWRH_COMPONENT_LINK] ASC) WITH (FILLFACTOR = 70);

