CREATE TABLE [dbo].[SDK_PLUGIN_ATTR_APPLY] (
    [PIAPPLY_PRIMARY]     FLOAT (53)  NOT NULL,
    [PIAPPLY_PLUGIN_CODE] VARCHAR (5) NULL,
    CONSTRAINT [PIAPPLY_PRIMARY] PRIMARY KEY CLUSTERED ([PIAPPLY_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

