CREATE TABLE [dbo].[SDK_WMS_HAULIER_LINK] (
    [WMSHL_PRIMARY]      INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMSHL_HAULIER_ID]   INT         NULL,
    [WMSHL_HAULIER_CODE] VARCHAR (8) NULL,
    [WMSHL_PRICE_ID]     INT         NULL,
    CONSTRAINT [SDK_WMS_HAULIER_LINK_PK] PRIMARY KEY CLUSTERED ([WMSHL_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

