CREATE TABLE [dbo].[SDK_WMS_TEMPLATE] (
    [DELT_PRIMARY]             INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [DELT_NAME]                NVARCHAR (50) NULL,
    [DELT_NOTES]               VARCHAR (50)  NULL,
    [DELT_CUSTOM_ALPHA1]       VARCHAR (50)  NULL,
    [DELT_CUSTOM_ALPHA2]       VARCHAR (50)  NULL,
    [DELT_CUSTOM_ALPHA3]       VARCHAR (50)  NULL,
    [DELT_CUSTOM_NUM1]         VARCHAR (50)  NULL,
    [DELT_CUSTOM_NUM2]         VARCHAR (50)  NULL,
    [DELT_CUSTOM_NUM3]         VARCHAR (50)  NULL,
    [DELT_CUSTOM_DAT1]         VARCHAR (50)  NULL,
    [DELT_CUSTOM_DAT2]         VARCHAR (50)  NULL,
    [DELT_CUSTOM_DAT3]         VARCHAR (50)  NULL,
    [DELT_ITEM_PRICELINE]      INT           NULL,
    [DELT_PACK_PRICELINE]      INT           NULL,
    [DELT_INNER_PRICELINE]     INT           NULL,
    [DELT_OUTER_PRICELINE]     INT           NULL,
    [DELT_ITEM_BARCODE]        VARCHAR (50)  NULL,
    [DELT_PACK_BARCODE]        VARCHAR (50)  NULL,
    [DELT_INNER_BARCODE]       VARCHAR (50)  NULL,
    [DELT_OUTER_BARCODE]       VARCHAR (50)  NULL,
    [DELT_PACK_ACTIVE]         TINYINT       NULL,
    [DELT_INNER_ACTIVE]        TINYINT       NULL,
    [DELT_OUTER_ACTIVE]        TINYINT       NULL,
    [DELT_PROD_CLASS]          VARCHAR (50)  NULL,
    [DELT_BATCH_TRACE]         TINYINT       NULL,
    [DELT_SERIAL_TRACK]        TINYINT       NULL,
    [DELT_COLOUR]              VARCHAR (50)  NULL,
    [DELT_SIZE]                VARCHAR (50)  NULL,
    [DELT_DEFAULT]             TINYINT       NULL,
    [DELT_SITE]                VARCHAR (50)  NULL,
    [DELT_PICKBY]              VARCHAR (10)  NULL,
    [DELT_OPTIMISE]            TINYINT       NULL,
    [DELT_PALLET_TYPE]         VARCHAR (10)  NULL,
    [DELT_GOODS_IN]            TINYINT       NULL,
    [DELT_GOODS_OUT]           TINYINT       NULL,
    [DELT_TRANSFER]            TINYINT       NULL,
    [DELT_ADJUST]              TINYINT       NULL,
    [DELT_CONVERT]             TINYINT       NULL,
    [DELT_STOCK_CHECK]         TINYINT       NULL,
    [DELT_SET_COLOUR]          TINYINT       NULL,
    [DELT_SET_SIZE]            TINYINT       NULL,
    [DELT_HOLD]                TINYINT       NULL,
    [DELT_LOC_TEMPLATE]        VARCHAR (200) NULL,
    [DELT_BATCH_REF]           VARCHAR (50)  NULL,
    [DELT_SERIAL_MIN]          INT           NULL,
    [DELT_SERIAL_MAX]          INT           NULL,
    [DELT_SERIAL_OUT]          INT           NULL,
    [DELT_IN_DATE1]            VARCHAR (50)  NULL,
    [DELT_IN_DATE2]            VARCHAR (50)  NULL,
    [DELT_IN_DATE3]            VARCHAR (50)  NULL,
    [DELT_IN_DATE4]            VARCHAR (50)  NULL,
    [DELT_PO_DO_NOT_UPD_STK]   INT           NULL,
    [DELT_PO_CLOSE_LINE]       INT           NULL,
    [DELT_SERIAL_DO_NOT_SPLIT] BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SDK_DELTA_TEMPLATE] PRIMARY KEY CLUSTERED ([DELT_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

