CREATE TABLE [dbo].[SDK_RPTB_SYS_ATTR_HEADER] (
    [RBSYST_PRIMARY] INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RBSYST_NAME]    VARCHAR (40) NULL,
    CONSTRAINT [RBSYST_PRIMARY_PK] PRIMARY KEY CLUSTERED ([RBSYST_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

