CREATE TABLE [dbo].[SDK_WMS_FILE_HEAD_DEF] (
    [WMSF_PRIMARY]   INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMSF_FILE_TYPE] VARCHAR (50)  NULL,
    [WMSF_UNIQUE]    VARCHAR (50)  NULL,
    [WMSF_TABLE]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_SDK_WMS_FILE_HEAD_DEF] PRIMARY KEY CLUSTERED ([WMSF_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

