CREATE TABLE [dbo].[SDK_SLPL_DATE_HEADER] (
    [SLPLDTE_PRIMARY]    INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SLPLDTE_USERID]     VARCHAR (5) NULL,
    [SLPLDTE_LEDGER]     VARCHAR (2) NULL,
    [SLPLDTE_LOCK]       TINYINT     NULL,
    [SLPLDTE_START_DATE] DATETIME    NULL,
    [SLPLDTE_EXCL_PERC]  FLOAT (53)  NULL,
    [SLPLDTE_EXCL_VALU]  FLOAT (53)  NULL,
    [SLPLDTE_PAY_COUNT]  INT         NULL,
    [SLPLDTE_EXCL_OS]    FLOAT (53)  NULL,
    [SLPLDTE_PT_LINK]    FLOAT (53)  NULL,
    [SLPLDTE_ST_LINK]    FLOAT (53)  NULL,
    [SLPLDTE_POP_LINK]   FLOAT (53)  NULL,
    [SLPLDTE_ORD_LINK]   FLOAT (53)  NULL,
    CONSTRAINT [SLPLDTE_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SLPLDTE_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SLPLDTE_ORD_LINK_FK] FOREIGN KEY ([SLPLDTE_ORD_LINK]) REFERENCES [dbo].[ORD_HEADER] ([OH_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [SLPLDTE_POP_LINK_FK] FOREIGN KEY ([SLPLDTE_POP_LINK]) REFERENCES [dbo].[POP_HEADER] ([POH_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [SLPLDTE_PT_LINK_FK] FOREIGN KEY ([SLPLDTE_PT_LINK]) REFERENCES [dbo].[PL_TRANSACTIONS] ([PT_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [SLPLDTE_ST_LINK_FK] FOREIGN KEY ([SLPLDTE_ST_LINK]) REFERENCES [dbo].[SL_TRANSACTIONS] ([ST_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [SLPLDTE_ORD_LINK]
    ON [dbo].[SDK_SLPL_DATE_HEADER]([SLPLDTE_ORD_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SLPLDTE_POP_LINK]
    ON [dbo].[SDK_SLPL_DATE_HEADER]([SLPLDTE_POP_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SLPLDTE_PT_LINK]
    ON [dbo].[SDK_SLPL_DATE_HEADER]([SLPLDTE_PT_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SLPLDTE_ST_LINK]
    ON [dbo].[SDK_SLPL_DATE_HEADER]([SLPLDTE_ST_LINK] ASC) WITH (FILLFACTOR = 70);

