CREATE TABLE [dbo].[SDK_WMS_STOCK_RESERVATION] (
    [WMR_ORDER_DETAIL_LINK] FLOAT (53)   NOT NULL,
    [WMR_STOCK_LINK]        FLOAT (53)   NOT NULL,
    [WMR_QUANTITY]          FLOAT (53)   NOT NULL,
    [WMR_SITE]              VARCHAR (10) NULL,
    CONSTRAINT [SDK_WMS_STOCK_RESERVATION_PK] PRIMARY KEY CLUSTERED ([WMR_ORDER_DETAIL_LINK] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_WMR_ORDER_DETAIL_LINK] FOREIGN KEY ([WMR_ORDER_DETAIL_LINK]) REFERENCES [dbo].[ORD_DETAIL] ([OD_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [WMR_STOCK_LINK]
    ON [dbo].[SDK_WMS_STOCK_RESERVATION]([WMR_STOCK_LINK] ASC, [WMR_SITE] ASC)
    INCLUDE([WMR_QUANTITY]) WITH (FILLFACTOR = 70);

