CREATE TABLE [dbo].[SDK_WMS_TEMPLATE_ASSIGN] (
    [WMSS_PRIMARY]      INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMSS_STK_PRIMARY]  INT NULL,
    [WMSS_DELT_PRIMARY] INT NULL,
    CONSTRAINT [PK_SDK_WMS_TEMPLATE_ASSIGN] PRIMARY KEY CLUSTERED ([WMSS_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WMSS_STK_PRIMARY]
    ON [dbo].[SDK_WMS_TEMPLATE_ASSIGN]([WMSS_STK_PRIMARY] ASC)
    INCLUDE([WMSS_DELT_PRIMARY]) WITH (FILLFACTOR = 70);

