CREATE TABLE [dbo].[SDK_WMS_PRE_RECEIPT_REQUESTS] (
    [WMPRR_ORDER_DETAIL_LINK] FLOAT (53)   NOT NULL,
    [WMPRR_MANIFEST]          BIT          NOT NULL,
    [WMPRR_REQUEST_NUMBER]    INT          NOT NULL,
    [WMPRR_MANIFEST_ID]       INT          NULL,
    [WMPRR_ORDER_NO]          VARCHAR (10) NOT NULL,
    [WMPRR_STOCK_LINK]        FLOAT (53)   NOT NULL,
    [WMPRR_QUANTITY_SENT]     FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [WMPRR_STATUS]            TINYINT      NULL,
    [WMPRR_SITE]              VARCHAR (10) NULL,
    [WMPRR_QUANTITY_RECEIVED] FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [WMPRR_USER_PUTIN]        VARCHAR (4)  NULL,
    [WMPRR_DATE_PUTIN]        DATETIME     DEFAULT (getdate()) NULL,
    [WMPRR_FILE_NAME]         VARCHAR (50) NULL,
    CONSTRAINT [SDK_WMS_PRE_RECEIPT_REQUESTS_PK] PRIMARY KEY CLUSTERED ([WMPRR_ORDER_DETAIL_LINK] ASC, [WMPRR_MANIFEST] ASC, [WMPRR_REQUEST_NUMBER] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_WMPRR_ORDER_DETAIL_LINK] FOREIGN KEY ([WMPRR_ORDER_DETAIL_LINK]) REFERENCES [dbo].[POP_DETAIL] ([POD_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [WMPRR_MANIFEST_ID_FK] FOREIGN KEY ([WMPRR_MANIFEST_ID]) REFERENCES [dbo].[SDK_WMS_PR_MANIFESTS] ([WMPRM_ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [WMPRR_ORDER_NO]
    ON [dbo].[SDK_WMS_PRE_RECEIPT_REQUESTS]([WMPRR_ORDER_NO] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [WMPRR_MANIFEST_ID]
    ON [dbo].[SDK_WMS_PRE_RECEIPT_REQUESTS]([WMPRR_MANIFEST_ID] ASC) WITH (FILLFACTOR = 70);

