CREATE TABLE [dbo].[SDK_WMS_FILE_DETA_DEF] (
    [WMSD_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMSD_H_PRIMARY]   INT          NULL,
    [WMSD_COL_NO]      INT          NULL,
    [WMSD_DB_COL_NAME] VARCHAR (50) NULL,
    [WMSD_DATATYPE]    VARCHAR (1)  NULL,
    [WMSD_DATASIZE]    INT          NULL,
    CONSTRAINT [PK_SDK_WMS_FILE_DETA_DEF] PRIMARY KEY CLUSTERED ([WMSD_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

