CREATE TABLE [dbo].[SDK_WMS_STOCK_WO_RESERVATION] (
    [WMWR_COMPONENT_LINK] INT          NOT NULL,
    [WMWR_STOCK_LINK]     FLOAT (53)   NOT NULL,
    [WMWR_QUANTITY]       FLOAT (53)   NOT NULL,
    [WMWR_SITE]           VARCHAR (10) NULL,
    CONSTRAINT [SDK_WMS_STOCK_WO_RESERVATION_PK] PRIMARY KEY CLUSTERED ([WMWR_COMPONENT_LINK] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_WMWR_COMPONENT_LINK] FOREIGN KEY ([WMWR_COMPONENT_LINK]) REFERENCES [dbo].[WO_COMPONENTS] ([WC_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [WMWR_STOCK_LINK]
    ON [dbo].[SDK_WMS_STOCK_WO_RESERVATION]([WMWR_STOCK_LINK] ASC, [WMWR_SITE] ASC)
    INCLUDE([WMWR_QUANTITY]) WITH (FILLFACTOR = 70);

