CREATE TABLE [dbo].[SDK_WMS_SOP_RETURN_REQUESTS] (
    [WMSRR_ORDER_DETAIL_LINK] FLOAT (53)   NOT NULL,
    [WMSRR_REQUEST_NUMBER]    INT          NOT NULL,
    [WMSRR_STOCK_LINK]        FLOAT (53)   NOT NULL,
    [WMSRR_QUANTITY]          FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [WMSRR_SITE]              VARCHAR (10) NULL,
    [WMSRR_USER_PUTIN]        VARCHAR (4)  NULL,
    [WMSRR_DATE_PUTIN]        DATETIME     DEFAULT (getdate()) NULL,
    [WMSRR_FILE_NAME]         VARCHAR (50) NULL,
    CONSTRAINT [SDK_WMS_SOP_RETURN_REQUESTS_PK] PRIMARY KEY CLUSTERED ([WMSRR_ORDER_DETAIL_LINK] ASC, [WMSRR_REQUEST_NUMBER] ASC),
    CONSTRAINT [WMSRR_ORDER_DETAIL_LINK_FK] FOREIGN KEY ([WMSRR_ORDER_DETAIL_LINK]) REFERENCES [dbo].[ORD_DETAIL] ([OD_PRIMARY]) ON DELETE CASCADE
);

