CREATE TABLE [dbo].[SDK_RPTB_ATTR_DETAIL] (
    [RBATTR_PRIMARY]      INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RBATTR_TEMP_PRIMARY] INT          NULL,
    [RBATTR_RBD_PRIMARY]  NCHAR (10)   NULL,
    [RBATTR_CHAR]         VARCHAR (50) NULL,
    [RBATTR_DATE]         DATETIME     NULL,
    [RBATTR_VALUE]        FLOAT (53)   NULL,
    CONSTRAINT [RBATTR_PRIMARY_PK] PRIMARY KEY CLUSTERED ([RBATTR_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

