CREATE TABLE [dbo].[SDK_WMS_PR_MANIFESTS] (
    [WMPRM_ID]            INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMPRM_REFERENCE]     VARCHAR (20) NULL,
    [WMPRM_DELIVERY_DATE] DATETIME     NULL,
    [WMPRM_STATUS]        TINYINT      DEFAULT ((0)) NOT NULL,
    [WMPRM_SITE]          VARCHAR (10) NULL,
    [WMPRM_USER_PUTIN]    VARCHAR (4)  NULL,
    [WMPRM_DATE_PUTIN]    DATETIME     NULL,
    [WMPRM_USER_EDITED]   VARCHAR (4)  NULL,
    [WMPRM_DATE_EDITED]   DATETIME     NULL,
    CONSTRAINT [SDK_WMS_PR_MANIFESTS_PK] PRIMARY KEY CLUSTERED ([WMPRM_ID] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [WMPRM_STATUS]
    ON [dbo].[SDK_WMS_PR_MANIFESTS]([WMPRM_STATUS] ASC) WITH (FILLFACTOR = 70);

