CREATE TABLE [dbo].[SDK_WMS_SETTINGS] (
    [WMSS_PRIMARY]                     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WMSS_SUPPLIER_OUT]                VARCHAR (200) NULL,
    [WMSS_DSN]                         VARCHAR (50)  NULL,
    [WMSS_DB]                          VARCHAR (50)  NULL,
    [WMSS_WIN_AUTH]                    TINYINT       NULL,
    [WMSS_USERNAME]                    VARCHAR (50)  NULL,
    [WMSS_PASSWORD]                    VARCHAR (50)  NULL,
    [WMSS_STOCK_OUT]                   VARCHAR (200) NULL,
    [WMSS_PORDERS_OUT]                 VARCHAR (200) NULL,
    [WMSS_SORDERS_OUT]                 VARCHAR (200) NULL,
    [WMSS_SORDERS_IN]                  VARCHAR (200) NULL,
    [WMSS_PORDERS_IN]                  VARCHAR (200) NULL,
    [WMSS_ADJUST_OUT]                  VARCHAR (200) NULL,
    [WMSS_ADJUST_IN]                   VARCHAR (200) NULL,
    [WMSS_ACCOUNT]                     VARCHAR (10)  NULL,
    [WMSS_DEFAULT_SITE]                VARCHAR (10)  NULL,
    [WMSS_SITE_ANALYSIS]               VARCHAR (40)  NULL,
    [WMSS_GRN_KEY]                     VARCHAR (10)  NULL,
    [WMSS_DEL_KEY]                     VARCHAR (10)  NULL,
    [WMSS_PO_STEP1]                    INT           NULL,
    [WMSS_PO_STEP2]                    INT           NULL,
    [WMSS_PO_STEP3]                    INT           NULL,
    [WMSS_SO_STEP1]                    VARCHAR (30)  NULL,
    [WMSS_SO_STEP2]                    VARCHAR (30)  NULL,
    [WMSS_SO_STEP3]                    VARCHAR (30)  NULL,
    [WMSS_SO_DEL_PRICE]                VARCHAR (20)  NULL,
    [WMSS_QI_AREA]                     VARCHAR (20)  NULL,
    [WMSS_GRN_RET_KEY]                 VARCHAR (10)  NULL,
    [WMSS_DEL_RET_KEY]                 VARCHAR (10)  NULL,
    [WMSS_SO_AUTO_OPEN_WAREHOUSE_INFO] BIT           DEFAULT ((1)) NULL,
    [WMSS_PO_AUTO_OPEN_WAREHOUSE_INFO] BIT           DEFAULT ((1)) NULL,
    [WMSS_HOLD_CUSTOMER]               VARCHAR (10)  NULL,
    [WMSS_DELTA_ROUTE]                 VARCHAR (10)  NULL,
    [WMSS_PICK_RESERVED_QUANTITY]      BIT           DEFAULT ((0)) NOT NULL,
    [WMSS_NO_EDITING_OF_AT_WMS_ORDERS] BIT           DEFAULT ((0)) NOT NULL,
    [WMSS_AUTO_EXPORT_SOP]             BIT           DEFAULT ((0)) NOT NULL,
    [WMSS_AUTO_EXPORT_POP]             BIT           DEFAULT ((0)) NOT NULL,
    [WMSS_USING_WMS]                   BIT           DEFAULT ((0)) NOT NULL,
    [WMSS_AUTO_RESERVE_STOCK]          BIT           DEFAULT ((0)) NOT NULL,
    [WMSS_SEND_NO_PARTIAL_ORDERS]      BIT           DEFAULT ((0)) NOT NULL,
    [WMSS_DO_NOT_SEND_ON_STOP_ORDERS]  BIT           DEFAULT ((0)) NOT NULL,
    [WMSS_SYNC_SUPPLIER_DETAILS]       BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SDK_WMS_SETTINGS] PRIMARY KEY CLUSTERED ([WMSS_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

