CREATE TABLE [dbo].[SDK_SL_PL_SETTINGS] (
    [SLPLSYS_PRIMARY]        INT          NOT NULL,
    [SLPLSYS_SL_MULTI_DATES] BIT          DEFAULT ((0)) NOT NULL,
    [SLPLSYS_PL_MULTI_DATES] BIT          DEFAULT ((0)) NOT NULL,
    [SLPLSYS_SL_DEFERRED]    BIT          DEFAULT ((0)) NOT NULL,
    [SLPLSYS_PL_DEFERRED]    BIT          DEFAULT ((0)) NOT NULL,
    [SLPLSYS_SL_NOMINAL]     VARCHAR (25) NULL,
    [SLPLSYS_PL_NOMINAL]     VARCHAR (25) NULL,
    [SLPLSYS_SL_MD_RELATIVE] BIT          DEFAULT ((0)) NOT NULL,
    [SLPLSYS_PL_MD_RELATIVE] BIT          DEFAULT ((0)) NOT NULL,
    [SLPLSYS_PIR_TOLERANCE]  BIT          DEFAULT ((0)) NOT NULL,
    [SLPLSYS_SL_MD_FREQ]     TINYINT      NULL,
    [SLPLSYS_SL_MD_NO]       TINYINT      NULL,
    [SLPLSYS_PL_MD_FREQ]     TINYINT      NULL,
    [SLPLSYS_PL_MD_NO]       TINYINT      NULL,
    [SLPLSYS_SL_DEF_STYLE]   BIT          DEFAULT ((0)) NOT NULL,
    [SLPLSYS_PL_DEF_STYLE]   BIT          DEFAULT ((0)) NOT NULL,
    [SLPLSYS_DEBIT_NOTE]     BIT          DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SLPLSYS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SLPLSYS_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SLPLSYS_PL_NOMINAL_FK] FOREIGN KEY ([SLPLSYS_PL_NOMINAL]) REFERENCES [dbo].[NL_ACCOUNTS] ([NCODE]),
    CONSTRAINT [SLPLSYS_SL_NOMINAL_FK] FOREIGN KEY ([SLPLSYS_SL_NOMINAL]) REFERENCES [dbo].[NL_ACCOUNTS] ([NCODE])
);

