CREATE TABLE [dbo].[SL_ALLOC_HISTORY] (
    [S_AL_PRIMARY]        INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [S_AL_DATE]           DATETIME     NULL,
    [S_AL_PERIOD]         TINYINT      DEFAULT ((0)) NULL,
    [S_AL_YEAR]           VARCHAR (1)  NULL,
    [S_AL_VALUE_HOME]     FLOAT (53)   DEFAULT ((0)) NULL,
    [S_AL_VALUE_CURR]     FLOAT (53)   DEFAULT ((0)) NULL,
    [S_AL_REFERENCE]      VARCHAR (10) NULL,
    [S_AL_HEADER_KEY]     VARCHAR (20) NULL,
    [S_AL_USER_ID]        VARCHAR (4)  NULL,
    [S_AL_ACCOUNT_CODE]   VARCHAR (10) NULL,
    [S_AL_FULLALLOC_PD]   SMALLINT     CONSTRAINT [DF_SL_ALLOC_HISTORY_S_AL_FULLALLOC_PD] DEFAULT ((0)) NULL,
    [S_AL_FULLALLOC_DATE] INT          DEFAULT ((0)) NULL,
    [S_AL_YEAR_LINK]      SMALLINT     NULL,
    CONSTRAINT [S_AL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([S_AL_PRIMARY] ASC),
    CONSTRAINT [S_AL_YEAR_LINK_CK] CHECK ([S_AL_YEAR] IS NOT NULL AND (upper([S_AL_YEAR])='O' OR upper([S_AL_YEAR])='N' OR upper([S_AL_YEAR])='C' OR upper([S_AL_YEAR])='L') AND [S_AL_YEAR_LINK] IS NOT NULL OR ([S_AL_YEAR] IS NULL OR (upper([S_AL_YEAR])='O' OR upper([S_AL_YEAR])='')) AND [S_AL_YEAR_LINK] IS NULL),
    CONSTRAINT [S_AL_YEAR_LINK_FK] FOREIGN KEY ([S_AL_YEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [S_AL_ACCOUNT_CODE]
    ON [dbo].[SL_ALLOC_HISTORY]([S_AL_ACCOUNT_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [S_AL_FULLALLOC_PD]
    ON [dbo].[SL_ALLOC_HISTORY]([S_AL_FULLALLOC_PD] ASC, [S_AL_ACCOUNT_CODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [S_AL_HEADER_KEY]
    ON [dbo].[SL_ALLOC_HISTORY]([S_AL_HEADER_KEY] ASC, [S_AL_FULLALLOC_PD] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [S_AL_REFERENCE]
    ON [dbo].[SL_ALLOC_HISTORY]([S_AL_REFERENCE] ASC);

