CREATE TABLE [dbo].[SL_ACCOUNTS2] (
    [CU_PRIMARY_2]                 FLOAT (53)    NOT NULL,
    [CU_CHAR1]                     VARCHAR (20)  NULL,
    [CU_CHAR2]                     VARCHAR (20)  NULL,
    [CU_CHAR3]                     VARCHAR (100) NULL,
    [CU_CHAR4]                     VARCHAR (100) NULL,
    [CU_FLAG1]                     TINYINT       DEFAULT ((0)) NULL,
    [CU_FLAG2]                     TINYINT       DEFAULT ((0)) NULL,
    [CU_DATE1]                     DATETIME      NULL,
    [CU_DATE2]                     DATETIME      NULL,
    [CU_NUM1]                      FLOAT (53)    DEFAULT ((0)) NULL,
    [CU_NUM2]                      FLOAT (53)    DEFAULT ((0)) NULL,
    [CU_USRCHAR1]                  VARCHAR (20)  NULL,
    [CU_USRCHAR2]                  VARCHAR (20)  NULL,
    [CU_USRCHAR3]                  VARCHAR (100) NULL,
    [CU_USRCHAR4]                  VARCHAR (100) NULL,
    [CU_USRFLAG1]                  TINYINT       DEFAULT ((0)) NULL,
    [CU_USRFLAG2]                  TINYINT       DEFAULT ((0)) NULL,
    [CU_USRDATE1]                  DATETIME      NULL,
    [CU_USRDATE2]                  DATETIME      NULL,
    [CU_USRNUM1]                   FLOAT (53)    DEFAULT ((0)) NULL,
    [CU_USRNUM2]                   FLOAT (53)    DEFAULT ((0)) NULL,
    [CUCODE2]                      VARCHAR (10)  NULL,
    [CU_EDI_ANA]                   VARCHAR (13)  NULL,
    [CU_EDI_CUSTIDN]               VARCHAR (13)  NULL,
    [CU_EDI_FLAG]                  TINYINT       DEFAULT ((0)) NULL,
    [CU_EDI_TEMPLATE]              FLOAT (53)    DEFAULT ((0)) NULL,
    [CU_EDI_FLGN]                  FLOAT (53)    DEFAULT ((0)) NULL,
    [CU_LANG_CODE]                 VARCHAR (10)  NULL,
    [CU_CONTACT_TITLE]             VARCHAR (5)   NULL,
    [CU_CONTACT_INITIALS]          VARCHAR (15)  NULL,
    [CU_CONTACT_SURNAME]           VARCHAR (30)  NULL,
    [CU_CONTACT_JOB]               VARCHAR (35)  NULL,
    [CU_CONTACT_COMPTYPE]          TINYINT       DEFAULT ((0)) NULL,
    [CU_CONTACT_FIRSTNAME]         VARCHAR (20)  NULL,
    [CU_ISDN_NUMBER]               VARCHAR (20)  NULL,
    [CU_WEBSITE_ADDRESS]           VARCHAR (100) NULL,
    [CU_MOBILE_NUMBER]             VARCHAR (20)  NULL,
    [CU_BANK_SORT]                 VARCHAR (10)  NULL,
    [CU_BANK_AC_NO]                VARCHAR (15)  NULL,
    [CU_BANK_AC_NAME]              VARCHAR (25)  NULL,
    [CU_BANK_BACSREF]              VARCHAR (18)  NULL,
    [CU_BANK_BANKNAME]             VARCHAR (25)  NULL,
    [CU_USRCHAR5]                  VARCHAR (20)  NULL,
    [CU_USRCHAR6]                  VARCHAR (30)  NULL,
    [CU_USRFLAG3]                  TINYINT       DEFAULT ((0)) NULL,
    [CU_USRDATE3]                  DATETIME      NULL,
    [CU_USRNUM3]                   FLOAT (53)    DEFAULT ((0)) NULL,
    [CU_USRCHAR7]                  VARCHAR (30)  NULL,
    [CU_USRCHAR8]                  VARCHAR (30)  NULL,
    [CU_LOG_UPDATED]               TINYINT       DEFAULT ((0)) NULL,
    [CU_LEVEL]                     INT           DEFAULT ((0)) NULL,
    [CU_GROUP]                     VARCHAR (10)  NULL,
    [CU_CLOSING_DAYS]              TINYINT       DEFAULT ((0)) NULL,
    [CU_DUE_DAYS_AFTER]            TINYINT       DEFAULT ((0)) NULL,
    [CU_TAX_NOTIFY_TIME]           VARCHAR (1)   NULL,
    [CU_TAX_ROUNDING]              TINYINT       DEFAULT ((0)) NULL,
    [CU_VALUEBORDER1]              FLOAT (53)    DEFAULT ((0)) NULL,
    [CU_VALUEBORDER2]              FLOAT (53)    DEFAULT ((0)) NULL,
    [CU_VALUEBORDER3]              FLOAT (53)    DEFAULT ((0)) NULL,
    [CU_NOTEDATE1]                 INT           DEFAULT ((0)) NULL,
    [CU_NOTEDATE2]                 INT           DEFAULT ((0)) NULL,
    [CU_NOTEDATE3]                 INT           DEFAULT ((0)) NULL,
    [CU_NOTERATE1]                 TINYINT       DEFAULT ((0)) NULL,
    [CU_NOTERATE2]                 TINYINT       DEFAULT ((0)) NULL,
    [CU_NOTERATE3]                 TINYINT       DEFAULT ((0)) NULL,
    [CU_CNF_XML_FORMAT]            VARCHAR (20)  NULL,
    [CU_CNF_EMAIL_SUBJECT]         VARCHAR (100) NULL,
    [CU_CNF_EMAIL_MESSAGE]         TEXT          NULL,
    [CU_OUR_ACCOUNT_CODE]          VARCHAR (20)  NULL,
    [CU_INV_XML_FORMAT]            VARCHAR (20)  NULL,
    [CU_INV_EMAIL_SUBJECT]         VARCHAR (100) NULL,
    [CU_INV_EMAIL_MESSAGE]         TEXT          NULL,
    [CU_STOCK_ALLOCATION_PRIORITY] INT           DEFAULT ((0)) NULL,
    [CU_HEAD_OFFICE]               TINYINT       DEFAULT ((0)) NULL,
    [CU_HEAD_OFFICE_CODE]          VARCHAR (10)  NULL,
    [CU_HEAD_OFFICE_DEFINVADDR]    TINYINT       DEFAULT ((0)) NULL,
    [CU_HEAD_OFFICE_DEFDELADDR]    TINYINT       DEFAULT ((0)) NULL,
    [CU_IBAN_NO]                   VARCHAR (34)  NULL,
    [CU_DO_NOT_FAX]                BIT           DEFAULT ((0)) NOT NULL,
    [CU_DO_NOT_PHONE]              BIT           DEFAULT ((0)) NOT NULL,
    [CU_USRCHAR9]                  VARCHAR (30)  NULL,
    [CU_USRCHAR10]                 VARCHAR (30)  NULL,
    [CU_USRCHAR11]                 VARCHAR (30)  NULL,
    [CU_USRCHAR12]                 VARCHAR (30)  NULL,
    [CU_USRCHAR13]                 VARCHAR (30)  NULL,
    [CU_USRCHAR14]                 VARCHAR (30)  NULL,
    [CU_USRCHAR15]                 VARCHAR (30)  NULL,
    [CU_USRCHAR16]                 VARCHAR (30)  NULL,
    [CU_USRCHAR17]                 VARCHAR (30)  NULL,
    [CU_USRCHAR18]                 VARCHAR (30)  NULL,
    [CU_USRCHAR19]                 VARCHAR (30)  NULL,
    [CU_USRCHAR20]                 VARCHAR (30)  NULL,
    [CU_USRCHAR21]                 VARCHAR (30)  NULL,
    [CU_USRCHAR22]                 VARCHAR (30)  NULL,
    [CU_USRNUM4]                   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM5]                   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM6]                   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM7]                   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM8]                   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM9]                   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM10]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM11]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM12]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM13]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM14]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM15]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM16]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM17]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM18]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM19]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRNUM20]                  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CU_USRDATE4]                  DATETIME      NULL,
    [CU_USRDATE5]                  DATETIME      NULL,
    [CU_USRDATE6]                  DATETIME      NULL,
    [CU_USRDATE7]                  DATETIME      NULL,
    [CU_USRDATE8]                  DATETIME      NULL,
    [CU_USRDATE9]                  DATETIME      NULL,
    [CU_USRDATE10]                 DATETIME      NULL,
    [CU_USRFLAG4]                  BIT           DEFAULT ((0)) NOT NULL,
    [CU_USRFLAG5]                  BIT           DEFAULT ((0)) NOT NULL,
    [CU_USRFLAG6]                  BIT           DEFAULT ((0)) NOT NULL,
    [CU_USRFLAG7]                  BIT           DEFAULT ((0)) NOT NULL,
    [CU_USRFLAG8]                  BIT           DEFAULT ((0)) NOT NULL,
    [CU_USRFLAG9]                  BIT           DEFAULT ((0)) NOT NULL,
    [CU_USRFLAG10]                 BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [CU_PRIMARY_2_PK] PRIMARY KEY CLUSTERED ([CU_PRIMARY_2] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUCODE2]
    ON [dbo].[SL_ACCOUNTS2]([CUCODE2] ASC);


GO
CREATE NONCLUSTERED INDEX [CU_HEAD_OFFICE_CODE]
    ON [dbo].[SL_ACCOUNTS2]([CU_HEAD_OFFICE_CODE] ASC);

