CREATE TABLE [dbo].[SL_ANALYSIS] (
    [SACODE]                VARCHAR (25) NULL,
    [SANAME]                VARCHAR (40) NULL,
    [SAUSED]                TINYINT      DEFAULT ((0)) NULL,
    [SA_COUNTRY_CODE]       VARCHAR (4)  NULL,
    [SATYPE_S_B_D]          VARCHAR (1)  NULL,
    [SADEFAULT_BANK]        TINYINT      DEFAULT ((0)) NULL,
    [SADEFAULT_SALES]       TINYINT      DEFAULT ((0)) NULL,
    [SANOMINALDR]           VARCHAR (25) NULL,
    [SANOMINALCR]           VARCHAR (25) NULL,
    [SANOMINALVAT]          VARCHAR (25) NULL,
    [SAVATCODE]             VARCHAR (4)  NULL,
    [SANOMINALDISC]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SASORT]                VARCHAR (20) NULL,
    [SAUSER1]               VARCHAR (20) NULL,
    [SAUSER2]               VARCHAR (20) NULL,
    [SAUSER3]               VARCHAR (20) NULL,
    [SATURNOVR_L1]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L2]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L3]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L4]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L5]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L6]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L7]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L8]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L9]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L10]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L11]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L12]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L13]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C1]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C2]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C3]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C4]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C5]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C6]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C7]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C8]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C9]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C10]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C11]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C12]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C13]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O1]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O2]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O3]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O4]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O5]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O6]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O7]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O8]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O9]          FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O10]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O11]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O12]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O13]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVERYTD]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVERPTD]         FLOAT (53)   DEFAULT ((0)) NULL,
    [SACURRENCYSYMBL]       VARCHAR (4)  NULL,
    [SATURNOVR_L1_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L2_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L3_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L4_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L5_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L6_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L7_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L8_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L9_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L10_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L11_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L12_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_L13_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C1_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C2_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C3_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C4_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C5_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C6_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C7_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C8_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C9_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C10_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C11_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C12_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_C13_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O1_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O2_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O3_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O4_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O5_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O6_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O7_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O8_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O9_C]        FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O10_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O11_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O12_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_O13_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_PTD_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SATURNOVR_YTD_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [SANOTES]               TEXT         NULL,
    [SA_USER_EDITED]        VARCHAR (4)  NULL,
    [SA_USER_PUTIN]         VARCHAR (4)  NULL,
    [SA_DATE_PUTIN]         DATETIME     NULL,
    [SA_DATE_EDITED]        DATETIME     NULL,
    [SA_MU_STATUS]          VARCHAR (1)  NULL,
    [SA_PRIMARY]            FLOAT (53)   NOT NULL,
    [SA_ANALYSIS_MATRIX]    TINYINT      DEFAULT ((0)) NULL,
    [SA_LEVEL]              INT          DEFAULT ((0)) NULL,
    [SA_GROUP]              VARCHAR (10) NULL,
    [SA_FORCE_COSTING]      TINYINT      DEFAULT ((0)) NULL,
    [SADEFAULT_ROUNDING]    TINYINT      DEFAULT ((0)) NULL,
    [SA_SOURCE]             VARCHAR (1)  NULL,
    [SA_DO_NOT_USE]         BIT          DEFAULT ((0)) NOT NULL,
    [SA_ACCRUE]             BIT          DEFAULT ((0)) NOT NULL,
    [SA_ACCRUAL_PERIODS]    INT          DEFAULT ((0)) NOT NULL,
    [SA_DEFAULT_COSTCENTRE] VARCHAR (10) DEFAULT ('') NOT NULL,
    CONSTRAINT [SA_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SA_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SACODE]
    ON [dbo].[SL_ANALYSIS]([SACODE] ASC);


GO
CREATE NONCLUSTERED INDEX [SACURRENCYSYMBL]
    ON [dbo].[SL_ANALYSIS]([SACURRENCYSYMBL] ASC);


GO
CREATE NONCLUSTERED INDEX [SADEFAULT_BANK]
    ON [dbo].[SL_ANALYSIS]([SADEFAULT_BANK] ASC);


GO
CREATE NONCLUSTERED INDEX [SADEFAULT_SALES]
    ON [dbo].[SL_ANALYSIS]([SADEFAULT_SALES] ASC);


GO
CREATE NONCLUSTERED INDEX [SANAME]
    ON [dbo].[SL_ANALYSIS]([SANAME] ASC);


GO
CREATE NONCLUSTERED INDEX [SANOMINALCR]
    ON [dbo].[SL_ANALYSIS]([SANOMINALCR] ASC);


GO
CREATE NONCLUSTERED INDEX [SANOMINALDR]
    ON [dbo].[SL_ANALYSIS]([SANOMINALDR] ASC);


GO
CREATE NONCLUSTERED INDEX [SANOMINALVAT]
    ON [dbo].[SL_ANALYSIS]([SANOMINALVAT] ASC);


GO
CREATE NONCLUSTERED INDEX [SASORT]
    ON [dbo].[SL_ANALYSIS]([SASORT] ASC);


GO
CREATE TRIGGER [dbo].[aa_sl_anal_dt]
    ON [dbo].[SL_ANALYSIS]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

