CREATE TABLE [dbo].[SL_BUYING_GROUPS] (
    [SBGR_PRIMARY]       INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SBGR_NAME]          VARCHAR (40) NOT NULL,
    [SBGR_USER_PUTIN]    VARCHAR (4)  NULL,
    [SBGR_DATE_PUTIN]    DATETIME     NULL,
    [SBGR_USER_EDITED]   VARCHAR (4)  NULL,
    [SBGR_DATE_EDITED]   DATETIME     NULL,
    [SBGR_SOURCE]        VARCHAR (1)  NULL,
    [SBGR_CUSTOMER_LINK] FLOAT (53)   NOT NULL,
    CONSTRAINT [SBGR_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SBGR_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SBGR_CUSTOMER_LINK_FK] FOREIGN KEY ([SBGR_CUSTOMER_LINK]) REFERENCES [dbo].[SL_ACCOUNTS] ([CU_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [SBGR_CUSTOMER_LINK]
    ON [dbo].[SL_BUYING_GROUPS]([SBGR_CUSTOMER_LINK] ASC) WITH (FILLFACTOR = 70);

