CREATE TABLE [dbo].[SL_BUYING_GROUP_MEMBERS] (
    [SBGM_BUYING_GROUP_LINK]    INT        NOT NULL,
    [SBGM_MEMBER_CUSTOMER_LINK] FLOAT (53) NOT NULL,
    CONSTRAINT [SL_BUYING_GROUP_MEMBERS_PK] PRIMARY KEY CLUSTERED ([SBGM_BUYING_GROUP_LINK] ASC, [SBGM_MEMBER_CUSTOMER_LINK] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SBGM_BUYING_GROUP_LINK_FK] FOREIGN KEY ([SBGM_BUYING_GROUP_LINK]) REFERENCES [dbo].[SL_BUYING_GROUPS] ([SBGR_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [SBGM_MEMBER_CUSTOMER_LINK_FK] FOREIGN KEY ([SBGM_MEMBER_CUSTOMER_LINK]) REFERENCES [dbo].[SL_ACCOUNTS] ([CU_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [SBGM_MEMBER_CUSTOMER_LINK]
    ON [dbo].[SL_BUYING_GROUP_MEMBERS]([SBGM_MEMBER_CUSTOMER_LINK] ASC) WITH (FILLFACTOR = 70);

