CREATE TABLE [dbo].[SL_CAMPAIGN_ASSIGN] (
    [SLC_PRIMARY]         INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SLC_CMP_LINK]        INT         DEFAULT ((0)) NULL,
    [SLC_CMP_STATUS_LINK] INT         DEFAULT ((0)) NULL,
    [SLC_DATE]            DATETIME    NULL,
    [SLC_USER]            VARCHAR (4) NULL,
    [SLC_AD_LINK]         INT         DEFAULT ((0)) NULL,
    [SLC_CU_LINK]         INT         DEFAULT ((0)) NULL,
    [SLC_LOCKED]          INT         DEFAULT ((0)) NULL,
    [SLC_DATE_EDITED]     DATETIME    NULL,
    [SLC_USER_EDITED]     VARCHAR (4) NULL,
    CONSTRAINT [SLC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SLC_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SLC_AD_LINK]
    ON [dbo].[SL_CAMPAIGN_ASSIGN]([SLC_AD_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [SLC_CMP_LINK]
    ON [dbo].[SL_CAMPAIGN_ASSIGN]([SLC_CMP_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [SLC_CMP_STATUS_LINK]
    ON [dbo].[SL_CAMPAIGN_ASSIGN]([SLC_CMP_STATUS_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [SLC_CU_LINK]
    ON [dbo].[SL_CAMPAIGN_ASSIGN]([SLC_CU_LINK] ASC);

