CREATE TABLE [dbo].[SL_DD_SUGGESTED_COLLECTIONS] (
    [SDD_SC_PRIMARY]   INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SDD_SC_REFERENCE] VARCHAR (10) NOT NULL,
    [SDD_SC_USER_ID]   VARCHAR (4)  NOT NULL,
    [SDD_SC_DATE]      DATETIME     DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [SDD_SC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SDD_SC_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SDD_SC_REFERENCE]
    ON [dbo].[SL_DD_SUGGESTED_COLLECTIONS]([SDD_SC_REFERENCE] ASC) WITH (FILLFACTOR = 70);

