CREATE TABLE [dbo].[SL_DD_SUGGESTED_COLLECTION_TRANS] (
    [SDD_SCT_PRIMARY]                   INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SDD_SCT_TRANSACTION_LINK]          FLOAT (53)  NOT NULL,
    [SDD_SCT_SUGGESTED_COLLECTION_LINK] INT         NOT NULL,
    [SDD_SCT_SUGGESTED_VALUE]           FLOAT (53)  NOT NULL,
    [SDD_SCT_SETT_DISC_VALUE]           FLOAT (53)  NOT NULL,
    [SDD_SCT_USER_ID]                   VARCHAR (4) NOT NULL,
    [SDD_SCT_DATE]                      DATETIME    DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [SDD_SCT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SDD_SCT_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SDD_SCT_SUGGESTED_COLLECTION_LINK_FK] FOREIGN KEY ([SDD_SCT_SUGGESTED_COLLECTION_LINK]) REFERENCES [dbo].[SL_DD_SUGGESTED_COLLECTIONS] ([SDD_SC_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [SDD_SCT_TRANSACTION_LINK_FK] FOREIGN KEY ([SDD_SCT_TRANSACTION_LINK]) REFERENCES [dbo].[SL_TRANSACTIONS] ([ST_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [SDD_SCT_SUGGESTED_COLLECTION_LINK]
    ON [dbo].[SL_DD_SUGGESTED_COLLECTION_TRANS]([SDD_SCT_SUGGESTED_COLLECTION_LINK] ASC, [SDD_SCT_TRANSACTION_LINK] ASC)
    INCLUDE([SDD_SCT_SETT_DISC_VALUE], [SDD_SCT_SUGGESTED_VALUE]) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SDD_SCT_TRANSACTION_LINK]
    ON [dbo].[SL_DD_SUGGESTED_COLLECTION_TRANS]([SDD_SCT_TRANSACTION_LINK] ASC, [SDD_SCT_SUGGESTED_COLLECTION_LINK] ASC)
    INCLUDE([SDD_SCT_SETT_DISC_VALUE], [SDD_SCT_SUGGESTED_VALUE]) WITH (FILLFACTOR = 70);

