CREATE TABLE [dbo].[SL_NOTES] (
    [SLN_PRIMARY]                   INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SLN_DATE_PUTIN]                DATETIME      DEFAULT (getdate()) NOT NULL,
    [SLN_USER_PUTIN]                VARCHAR (4)   NOT NULL,
    [SLN_DATE_EDITED]               DATETIME      NULL,
    [SLN_USER_EDITED]               VARCHAR (4)   NULL,
    [SLN_NEXT_CONTACT_DATE]         DATETIME      NULL,
    [SLN_PROMISED_PAYMENT_DATE]     DATETIME      NULL,
    [SLN_PROMISED_PAYMENT_VALUE]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SLN_PROMISED_PAYMENT_CURRENCY] VARCHAR (4)   NOT NULL,
    [SLN_NOTE]                      VARCHAR (MAX) NULL,
    CONSTRAINT [SLN_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SLN_PRIMARY] ASC)
);

