CREATE TABLE [dbo].[SL_PROSPECT_LINK] (
    [PLINK_DEALER]       VARCHAR (10) NULL,
    [PLINK_POSTCODE]     VARCHAR (30) NULL,
    [PLINK_PRIMARY]      FLOAT (53)   NOT NULL,
    [PLINK_ASTERIX]      TINYINT      DEFAULT ((0)) NULL,
    [PLINK_PRODUCT_CODE] VARCHAR (25) NULL,
    [PLINK_USERKEY1]     VARCHAR (20) NULL,
    [PLINK_USERKEY2]     VARCHAR (20) NULL,
    [PLINK_USERKEY3]     VARCHAR (20) NULL,
    CONSTRAINT [PLINK_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PLINK_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PLINK_DEALER]
    ON [dbo].[SL_PROSPECT_LINK]([PLINK_DEALER] ASC);


GO
CREATE NONCLUSTERED INDEX [PLINK_POSTCODE]
    ON [dbo].[SL_PROSPECT_LINK]([PLINK_POSTCODE] ASC);

