CREATE TABLE [dbo].[SL_PL_STATEMENTS_TEMP] (
    [STMNT_GUID]         UNIQUEIDENTIFIER DEFAULT (NULL) NOT NULL,
    [STMNT_TRAN_LINK]    BIGINT           NOT NULL,
    [STMNT_ACCOUNT_CODE] VARCHAR (25)     DEFAULT (NULL) NULL,
    [STMNT_STATUS]       TINYINT          DEFAULT ((0)) NULL,
    [STMNT_DOC_PRIMARY]  BIGINT           DEFAULT (NULL) NULL,
    [STMNT_FAX_NO]       NVARCHAR (64)    DEFAULT (NULL) NULL,
    CONSTRAINT [SL_PL_STATEMENTS_TEMP_PK] PRIMARY KEY CLUSTERED ([STMNT_GUID] ASC, [STMNT_TRAN_LINK] ASC)
);

