CREATE TABLE [dbo].[SL_PL_NL_DETAIL_ACCRUALS] (
    [SPNDA_PRIMARY]     FLOAT (53)   NOT NULL,
    [SPNDA_HEADER_KEY]  VARCHAR (20) NOT NULL,
    [SPNDA_PERIODS]     SMALLINT     NOT NULL,
    [SPNDA_ACCRUAL_NOM] VARCHAR (25) NOT NULL,
    CONSTRAINT [SPNDA_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SPNDA_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SPNDA_ACCRUAL_NOM_FK] FOREIGN KEY ([SPNDA_ACCRUAL_NOM]) REFERENCES [dbo].[NL_ACCOUNTS] ([NCODE]) ON UPDATE CASCADE,
    CONSTRAINT [SPNDA_PRIMARY_FK] FOREIGN KEY ([SPNDA_PRIMARY]) REFERENCES [dbo].[SL_PL_NL_DETAIL] ([DET_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [SPNDA_ACCRUAL_NOM]
    ON [dbo].[SL_PL_NL_DETAIL_ACCRUALS]([SPNDA_ACCRUAL_NOM] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SPNDA_HEADER_KEY]
    ON [dbo].[SL_PL_NL_DETAIL_ACCRUALS]([SPNDA_HEADER_KEY] ASC) WITH (FILLFACTOR = 70);

