CREATE TABLE [dbo].[SL_PL_NL_DETAIL] (
    [DET_NETT]               FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_VAT]                FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_VATCODE]            VARCHAR (4)   NULL,
    [DET_GROSS]              FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_UNALLOCATED]        FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_BATCH_FLAG]         TINYINT       DEFAULT ((0)) NULL,
    [DET_RECUR_FLAG]         TINYINT       DEFAULT ((0)) NULL,
    [DET_BATCH_REF]          VARCHAR (10)  NULL,
    [DET_ARCHIVE_FLG]        TINYINT       DEFAULT ((0)) NULL,
    [DET_ORIGIN]             VARCHAR (3)   NULL,
    [DET_LEDGER]             VARCHAR (2)   NULL,
    [DET_TYPE]               VARCHAR (3)   NULL,
    [DET_DESCRIPTION]        VARCHAR (240) NULL,
    [DET_HEADER_REF]         VARCHAR (26)  NULL,
    [DET_JNL_LINEREF]        VARCHAR (10)  NULL,
    [DET_PL_INTERNAL]        FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_DATE]               DATETIME      NULL,
    [DET_TAX_SORT]           VARCHAR (4)   NULL,
    [DET_CURR_TAX]           FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_TAX_WITHHLD]        FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_PL_ACQ_TAX]         FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_CURR_CODE]          VARCHAR (4)   NULL,
    [DET_CURR_RATE]          FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_CURR_NETT]          FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_CURR_RTEFLG]        TINYINT       DEFAULT ((0)) NULL,
    [DET_CURR_UNALOC]        FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_CURR_L_DISC]        FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_CURR_T_DISC]        FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_IMPEXP_CODE]        VARCHAR (1)   NULL,
    [DET_COUNTRY_CDE]        VARCHAR (4)   NULL,
    [DET_ECVAT_TYPE]         VARCHAR (1)   NULL,
    [DET_L_DISCOUNT]         FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_T_DISCOUNT]         FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_COSTPRICE]          FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_PERIOD_SORT]        INT           DEFAULT ((0)) NULL,
    [DET_PERIODNUMBR]        TINYINT       DEFAULT ((0)) NULL,
    [DET_YEAR]               VARCHAR (1)   NULL,
    [DET_RECONCILED]         TINYINT       DEFAULT ((0)) NULL,
    [DET_NOM_PERIOD]         TINYINT       DEFAULT ((0)) NULL,
    [DET_NOM_YEAR]           VARCHAR (1)   NULL,
    [DET_NOM_PERSORT]        INT           DEFAULT ((0)) NULL,
    [DET_RECON_REF]          VARCHAR (10)  NULL,
    [DT_RECON_ORDER]         FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_UNIT_PRICE]         FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_QUANTITY]           FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_UNT_PRICE_C]        FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_UNIT_QTY]           FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_USER_PUTIN]         VARCHAR (4)   NULL,
    [DET_DATE_PUTIN]         DATETIME      NULL,
    [DET_HEADER_KEY]         VARCHAR (20)  NULL,
    [DET_BATCH_POSTD]        TINYINT       DEFAULT ((0)) NULL,
    [DET_SERIALNO]           VARCHAR (40)  NULL,
    [DET_STKSORTKEY1]        VARCHAR (20)  NULL,
    [DET_PRICE_CODE]         VARCHAR (16)  NULL,
    [DET_NOMINALDR]          VARCHAR (25)  NULL,
    [DET_NOMINALCR]          VARCHAR (25)  NULL,
    [DET_NOMINALVAT]         VARCHAR (25)  NULL,
    [DET_STOCK_CODE]         VARCHAR (25)  NULL,
    [DET_ACCOUNT]            VARCHAR (10)  NULL,
    [DET_ANALYSIS]           VARCHAR (25)  NULL,
    [DET_COSTHEADER]         VARCHAR (10)  NULL,
    [DET_COSTCENTRE]         VARCHAR (10)  NULL,
    [DET_ANALTYPE]           VARCHAR (1)   NULL,
    [DET_PRIMARY]            FLOAT (53)    NOT NULL,
    [DET_EC_T_NATURE]        VARCHAR (2)   NULL,
    [DET_SUB_AUDIT_NO]       FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_SUB_LEDGER]         VARCHAR (10)  NULL,
    [DET_VAT_RULES]          TINYINT       DEFAULT ((0)) NULL,
    [DET_VATNONDEDUCT]       FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_STKSORTKEY2]        VARCHAR (20)  NULL,
    [DET_STKSORTKEY3]        VARCHAR (20)  NULL,
    [DET_STKSORTKEY]         VARCHAR (20)  NULL,
    [DET_LANDED_COST]        VARCHAR (1)   NULL,
    [DET_DIMENSION1]         VARCHAR (20)  NULL,
    [DET_DIMENSION2]         VARCHAR (20)  NULL,
    [DET_DIMENSION3]         VARCHAR (20)  NULL,
    [DET_CHEQUE_PAYEE]       VARCHAR (40)  NULL,
    [DET_NETT_BASE2]         FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_VAT_BASE2]          FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_GROSS_BASE2]        FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_L_DISC_BASE2]       FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_T_DISC_BASE2]       FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_BASE2_RATE]         FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_TRI_RATE1]          FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_BASE2_RATECHNG]     TINYINT       DEFAULT ((0)) NULL,
    [DET_TRI_RATECHNG1]      TINYINT       DEFAULT ((0)) NULL,
    [DET_COSTPRICE_BASE2]    FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_UNIT_PRICE_BASE2]   FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_TAX_WITHHLD_BASE2]  FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_PL_ACQUISTN_BASE2]  FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_CURR_GROSS]         FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_TRI_RATE2]          FLOAT (53)    DEFAULT ((0)) NULL,
    [DET_TRI_RATECHNG2]      TINYINT       DEFAULT ((0)) NULL,
    [DET_NLCONTRA]           VARCHAR (25)  NULL,
    [DET_HEADER_REF2]        VARCHAR (10)  NULL,
    [DET_SLPL_PRIMARY]       VARCHAR (20)  NULL,
    [DET_SRV_STATUS]         TINYINT       DEFAULT ((0)) NULL,
    [DET_ORDER_LINK]         INT           DEFAULT ((0)) NULL,
    [DET_SOURCE]             VARCHAR (1)   NULL,
    [DET_VAT_RETURN_PRIMARY] INT           DEFAULT ((-1)) NULL,
    [DET_DELIVERY_ADDRESS]   VARCHAR (16)  NULL,
    [DET_POSTING_NO]         SMALLINT      DEFAULT ((0)) NULL,
    [DET_REVERSE_STATUS]     TINYINT       DEFAULT ((0)) NULL,
    [DET_MOVEMENT_LINK]      INT           NULL,
    [DET_NOM_YEAR_LINK]      SMALLINT      NULL,
    [DET_VAT_RATE]           FLOAT (53)    NULL,
    CONSTRAINT [DET_PRIMARY_PK] PRIMARY KEY CLUSTERED ([DET_PRIMARY] ASC),
    CONSTRAINT [DET_NOM_YEAR_LINK_CK] CHECK ([DET_NOM_YEAR] IS NOT NULL AND (upper([DET_NOM_YEAR])='O' OR upper([DET_NOM_YEAR])='N' OR upper([DET_NOM_YEAR])='C' OR upper([DET_NOM_YEAR])='L') AND [DET_NOM_YEAR_LINK] IS NOT NULL OR ([DET_NOM_YEAR] IS NULL OR (upper([DET_NOM_YEAR])='O' OR upper([DET_NOM_YEAR])='')) AND [DET_NOM_YEAR_LINK] IS NULL),
    CONSTRAINT [DET_NOM_YEAR_LINK_FK] FOREIGN KEY ([DET_NOM_YEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [DET_ACCOUNT]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_ACCOUNT] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_ANALYSIS]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_ANALYSIS] ASC, [DET_ORIGIN] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_BATCH_FLAG]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_BATCH_FLAG] ASC, [DET_LANDED_COST] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_BATCH_POSTD]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_BATCH_POSTD] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_COSTHEADER]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_COSTHEADER] ASC, [DET_COSTCENTRE] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_CURR_CODE]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_CURR_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_DATE]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_HEADER_KEY]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_HEADER_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_HEADER_REF]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_HEADER_REF] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_MOVEMENT_LINK]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_MOVEMENT_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_NOMINALCR]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_NOMINALCR] ASC, [DET_RECONCILED] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_NOMINALDR]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_NOMINALDR] ASC, [DET_RECONCILED] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_NOMINALVAT]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_NOMINALVAT] ASC, [DET_RECONCILED] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_NOM_PERSORT]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_NOM_PERSORT] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_ORDER_LINK]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_ORDER_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_PERIOD_SORT]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_PERIOD_SORT] ASC);


GO
CREATE NONCLUSTERED INDEX [DET_PRICE_CODE]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_PRICE_CODE] ASC)
    INCLUDE([DET_HEADER_KEY]) WHERE ([DET_PRICE_CODE]<>'');


GO
CREATE NONCLUSTERED INDEX [DET_STOCK_CODE]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_STOCK_CODE] ASC)
    INCLUDE([DET_HEADER_KEY]) WHERE ([DET_STOCK_CODE]<>'');


GO
CREATE NONCLUSTERED INDEX [DET_VAT_RETURN_PRIMARY]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_VAT_RETURN_PRIMARY] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SL_PL_NL_DETAIL_DET_RECONCILED_DET_NOMINALDR_DET_BATCH_FLAG_DET_PRIMARY]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_RECONCILED] ASC, [DET_NOMINALDR] ASC, [DET_BATCH_FLAG] ASC, [DET_PRIMARY] ASC)
    INCLUDE([DET_NETT], [DET_VAT], [DET_GROSS], [DET_RECUR_FLAG], [DET_BATCH_REF], [DET_ORIGIN], [DET_TYPE], [DET_DESCRIPTION], [DET_HEADER_REF], [DET_JNL_LINEREF], [DET_DATE], [DET_CURR_TAX], [DET_CURR_CODE], [DET_CURR_RATE], [DET_CURR_NETT], [DET_NOM_PERIOD], [DET_NOM_YEAR], [DET_NOM_PERSORT], [DET_RECON_REF], [DT_RECON_ORDER], [DET_HEADER_KEY], [DET_ACCOUNT], [DET_ANALYSIS], [DET_ANALTYPE], [DET_CHEQUE_PAYEE], [DET_NETT_BASE2], [DET_VAT_BASE2], [DET_GROSS_BASE2], [DET_TRI_RATE1], [DET_TRI_RATE2]);


GO
CREATE NONCLUSTERED INDEX [IX_SL_PL_NL_DETAIL_DET_RECONCILED_DET_NOMINALCR_DET_BATCH_FLAG_DET_PRIMARY]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_RECONCILED] ASC, [DET_NOMINALCR] ASC, [DET_BATCH_FLAG] ASC, [DET_PRIMARY] ASC)
    INCLUDE([DET_NETT], [DET_VAT], [DET_GROSS], [DET_RECUR_FLAG], [DET_BATCH_REF], [DET_ORIGIN], [DET_TYPE], [DET_DESCRIPTION], [DET_HEADER_REF], [DET_JNL_LINEREF], [DET_DATE], [DET_CURR_TAX], [DET_CURR_CODE], [DET_CURR_RATE], [DET_CURR_NETT], [DET_NOM_PERIOD], [DET_NOM_YEAR], [DET_NOM_PERSORT], [DET_RECON_REF], [DT_RECON_ORDER], [DET_HEADER_KEY], [DET_ACCOUNT], [DET_ANALYSIS], [DET_ANALTYPE], [DET_CHEQUE_PAYEE], [DET_NETT_BASE2], [DET_VAT_BASE2], [DET_GROSS_BASE2], [DET_TRI_RATE1], [DET_TRI_RATE2]);


GO
CREATE NONCLUSTERED INDEX [DET_MISSING_VAT_RATES]
    ON [dbo].[SL_PL_NL_DETAIL]([DET_BATCH_FLAG] ASC, [DET_HEADER_KEY] ASC)
    INCLUDE([DET_VAT_RATE]) WITH (FILLFACTOR = 70);


GO
CREATE TRIGGER [dbo].[aa_sl_pl_nl_detail_dt]
    ON [dbo].[SL_PL_NL_DETAIL]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

