CREATE TABLE [dbo].[SL_TRANSACTION_NOTES] (
    [ST_NOTE]           TEXT         NULL,
    [ST_COPY_HEADERKEY] VARCHAR (20) NOT NULL,
    CONSTRAINT [ST_COPY_HEADERKEY_PK] PRIMARY KEY CLUSTERED ([ST_COPY_HEADERKEY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ST_COPY_HEADERKEY]
    ON [dbo].[SL_TRANSACTION_NOTES]([ST_COPY_HEADERKEY] ASC);

