CREATE TABLE [dbo].[SOP_TRN_TEMP] (
    [SOP_ORDER_ID]                                INT             NOT NULL,
    [SOP_ORDER_LINE_NO]                           INT             NOT NULL,
    [SOP_STATUS_TEMP]                             INT             DEFAULT ((0)) NOT NULL,
    [SOP_SELECT_DEFAULT]                          VARCHAR (250)   NULL,
    [SOP_ORDER_TYPE]                              VARCHAR (3)     NULL,
    [SOP_HEADER_STATUS]                           VARCHAR (20)    NULL,
    [SOP_URGENT_FLAG]                             TINYINT         NULL,
    [SOP_SUBLEDGER]                               VARCHAR (10)    NULL,
    [SOP_ARCHIVE_FLAG]                            TINYINT         NULL,
    [SOP_NO_PART_DELIVERY]                        TINYINT         NULL,
    [SOP_ACCOUNT]                                 VARCHAR (10)    NULL,
    [SOP_CURRENCYCODE]                            VARCHAR (6)     NULL,
    [SOP_CURRENCY_RATE]                           FLOAT (53)      NULL,
    [SOP_EURO_TO_HOME_RATE]                       FLOAT (53)      NULL,
    [SOP_EC_DELIVERY_TERMS]                       VARCHAR (3)     NULL,
    [SOP_EC_TRANS_NATURE]                         VARCHAR (2)     NULL,
    [SOP_EC_TRANSPORT_METHOD]                     VARCHAR (1)     NULL,
    [SOP_PRICE_KEY]                               INT             NULL,
    [SOP_TOTALDISC_PERC]                          FLOAT (53)      NULL,
    [SOP_SETTLEMENT_DISC1_PERC]                   FLOAT (53)      NULL,
    [SOP_SETTLEMENT_DISC2_PERC]                   FLOAT (53)      NULL,
    [SOP_SETTLEMENT_DAYS1]                        INT             NULL,
    [SOP_SETTLEMENT_DAYS2]                        INT             NULL,
    [SOP_HEADER_LINEDISC_PERC]                    FLOAT (53)      NULL,
    [SOP_DELIVERY_CHARGE]                         FLOAT (53)      NULL,
    [SOP_DELIVERY_CHARGE_PERC]                    FLOAT (53)      NULL,
    [SOP_DELIVERY_METHOD]                         VARCHAR (20)    NULL,
    [SOP_MINIMUM_ORDER_VALUE]                     FLOAT (53)      NULL,
    [SOP_ORDER_TERMS]                             VARCHAR (40)    NULL,
    [SOP_ORDER_DATE]                              DATETIME        NULL,
    [SOP_DATE_REQUIRED]                           DATETIME        DEFAULT ('') NULL,
    [SOP_ORDER_YEAR]                              VARCHAR (1)     NULL,
    [SOP_ORDER_PERIOD]                            TINYINT         NULL,
    [SOP_BATCH_REF]                               VARCHAR (10)    NULL,
    [SOP_CUSTOMER_REF]                            VARCHAR (20)    NULL,
    [SOP_USER_KEY1]                               VARCHAR (20)    NULL,
    [SOP_USER_KEY2]                               VARCHAR (20)    NULL,
    [SOP_USER_KEY3]                               VARCHAR (20)    NULL,
    [SOP_ORDER_DESCRIPTION]                       VARCHAR (30)    NULL,
    [SOP_ORDER_INTERNAL_NOTES]                    VARCHAR (512)   NULL,
    [SOP_MAIL_ORDER]                              TINYINT         NULL,
    [SOP_AUTHORISE_CODE]                          VARCHAR (10)    NULL,
    [SOP_CREDIT_CARD_NO]                          VARCHAR (20)    NULL,
    [SOP_CARD_EXPIRY_DATE]                        VARCHAR (5)     NULL,
    [SOP_MAILORDER_BANK_ANALYSIS]                 VARCHAR (25)    NULL,
    [SOP_ENTRYTYPE]                               VARCHAR (1)     NULL,
    [SOP_STOCK_CODE]                              VARCHAR (25)    NULL,
    [SOP_PRICE_CODE]                              VARCHAR (16)    NULL,
    [SOP_SERIAL_NUMBER]                           VARCHAR (40)    NULL,
    [SOP_SUB_ANALYSIS]                            VARCHAR (25)    NULL,
    [SOP_QTY_ORDERED]                             FLOAT (53)      NULL,
    [SOP_ANALYSIS]                                VARCHAR (25)    NULL,
    [SOP_UNITCOST]                                FLOAT (53)      NULL,
    [SOP_CURRENCY_UNITCOST]                       FLOAT (53)      NULL,
    [SOP_COSTPRICE]                               FLOAT (53)      NULL,
    [SOP_VATCODE]                                 VARCHAR (4)     NULL,
    [SOP_TAX_AMOUNT]                              FLOAT (53)      NULL,
    [SOP_CURRENCY_TAX_AMOUNT]                     FLOAT (53)      NULL,
    [SOP_LINE_DISCOUNT]                           FLOAT (53)      NULL,
    [SOP_CURRENCY_LINE_DISCOUNT]                  FLOAT (53)      NULL,
    [SOP_LINE_DISCOUNT_PERC]                      FLOAT (53)      NULL,
    [SOP_COSTHEADER]                              VARCHAR (10)    NULL,
    [SOP_COSTCENTRE]                              VARCHAR (10)    NULL,
    [SOP_LINE_DETAIL]                             VARCHAR (240)   NULL,
    [SOP_RTP_FLAG]                                TINYINT         NULL,
    [SOP_TRN_USER_KEY1]                           VARCHAR (20)    NULL,
    [SOP_TRN_USER_KEY2]                           VARCHAR (20)    NULL,
    [SOP_TRN_USER_KEY3]                           VARCHAR (20)    NULL,
    [SOP_USER_ID]                                 VARCHAR (4)     NOT NULL,
    [SOP_PROBABILITY_PERC]                        FLOAT (53)      NULL,
    [SOP_CURRENCY_ENTRY]                          TINYINT         NULL,
    [SOP_DELIVERY_ADDRESS]                        VARCHAR (160)   NULL,
    [SOP_DELIVERY_TOWN]                           VARCHAR (50)    NULL,
    [SOP_DELIVERY_COUNTY]                         VARCHAR (50)    NULL,
    [SOP_DELIVERY_POSTCODE]                       VARCHAR (50)    NULL,
    [SOP_DELIVERY_CONTACT]                        VARCHAR (50)    NULL,
    [SOP_DELIVERY_ADDRESS_NO]                     INT             NULL,
    [SOP_INVOICE_ADDRESS_NO]                      INT             NULL,
    [SOP_INVOICE_ADDRESS]                         VARCHAR (160)   NULL,
    [SOP_INVOICE_TOWN]                            VARCHAR (50)    NULL,
    [SOP_INVOICE_COUNTY]                          VARCHAR (50)    NULL,
    [SOP_INVOICE_POSTCODE]                        VARCHAR (50)    NULL,
    [SOP_INVOICE_CONTACT]                         VARCHAR (50)    NULL,
    [SOP_INVOICE_EXCLUDE_NAME]                    TINYINT         NULL,
    [SOP_DELIVERY_EXCLUDE_NAME]                   TINYINT         NULL,
    [SOP_GROSS_ENTRY]                             TINYINT         NULL,
    [SOP_RESERVE_STK]                             TINYINT         NULL,
    [SOP_ALLOW_EMPTY_SUBANALYSIS]                 TINYINT         NULL,
    [SOP_ALLOW_EMPTY_SERIAL_NO]                   TINYINT         NULL,
    [SOP_APPLY_LINKED_ITEMS]                      TINYINT         DEFAULT ((0)) NULL,
    [SOP_PRICE_LINE]                              INT             NULL,
    [SOP_HEADER_USER_CHAR1]                       VARCHAR (20)    NULL,
    [SOP_HEADER_USER_CHAR2]                       VARCHAR (20)    NULL,
    [SOP_HEADER_USER_CHAR3]                       VARCHAR (100)   NULL,
    [SOP_HEADER_USER_CHAR4]                       VARCHAR (100)   NULL,
    [SOP_HEADER_USER_FLAG1]                       TINYINT         NULL,
    [SOP_HEADER_USER_FLAG2]                       TINYINT         NULL,
    [SOP_HEADER_USER_DATE1]                       DATETIME        NULL,
    [SOP_HEADER_USER_DATE2]                       DATETIME        NULL,
    [SOP_HEADER_USER_NUMBER1]                     FLOAT (53)      NULL,
    [SOP_HEADER_USER_NUMBER2]                     FLOAT (53)      NULL,
    [SOP_DETAIL_USER_CHAR1]                       VARCHAR (20)    NULL,
    [SOP_DETAIL_USER_CHAR2]                       VARCHAR (20)    NULL,
    [SOP_DETAIL_USER_CHAR3]                       VARCHAR (100)   NULL,
    [SOP_DETAIL_USER_CHAR4]                       VARCHAR (100)   NULL,
    [SOP_DETAIL_USER_FLAG1]                       TINYINT         NULL,
    [SOP_DETAIL_USER_FLAG2]                       TINYINT         NULL,
    [SOP_DETAIL_USER_DATE1]                       DATETIME        NULL,
    [SOP_DETAIL_USER_DATE2]                       DATETIME        NULL,
    [SOP_DETAIL_USER_NUMBER1]                     FLOAT (53)      NULL,
    [SOP_DETAIL_USER_NUMBER2]                     FLOAT (53)      NULL,
    [SOP_DETAIL_PRIMARY]                          INT             NULL,
    [SOP_DETAIL_DATE_REQUIRED]                    DATETIME        DEFAULT ('') NULL,
    [SOP_DO_NOT_UPDATE_STOCK]                     TINYINT         NULL,
    [SOP_DELETE_DETAIL_LINE]                      TINYINT         DEFAULT ((0)) NULL,
    [SOP_ORDER_NUMBER]                            INT             NULL,
    [SOP_SOURCE]                                  VARCHAR (1)     NULL,
    [SOP_TRAN_OPTIONS]                            VARCHAR (30)    NULL,
    [SOP_SWITCH_ISSUE_NO]                         VARCHAR (2)     NULL,
    [SOP_SWITCH_ISSUE_DATE]                       VARCHAR (5)     NULL,
    [SOP_BANK_REF]                                VARCHAR (4)     NULL,
    [SOP_CARD_TYPE]                               VARCHAR (1)     NULL,
    [SOP_DUE_DAYS]                                INT             NULL,
    [SOP_ANTICPATED_PAYMENT_DAYS]                 INT             NULL,
    [SOP_DELIVERY_COUNTRY]                        VARCHAR (35)    NULL,
    [SOP_INVOICE_COUNTRY]                         VARCHAR (35)    NULL,
    [SOP_ACTUAL_LINE_NO]                          INT             NULL,
    [SOP_STOCK_ANALYSIS]                          VARCHAR (25)    NULL,
    [SOP_ORDER_ACCOUNT]                           VARCHAR (10)    NULL,
    [SOP_DELIVERY_ACCOUNT]                        VARCHAR (10)    NULL,
    [SOP_ALLOW_EMPTY_STOCK_ANALYSIS]              TINYINT         NULL,
    [SOP_SERIAL_MULTI_LINK]                       INT             NULL,
    [SOP_DELIVERY_CHARGE_LINE]                    TINYINT         NULL,
    [SOP_DELIVERY_VAT_REG_NO]                     VARCHAR (21)    NULL,
    [SOP_DELIVERY_VAT_STATUS]                     VARCHAR (1)     NULL,
    [SOP_DELIVERY_COUNTRY_CODE]                   VARCHAR (4)     NULL,
    [SOP_DELIVERY_BRANCH_ID]                      VARCHAR (3)     NULL,
    [SOP_SELECT_FIRST_SUB_ANALYSIS]               BIT             NULL,
    [SOP_UPDATE_LANDED_COST]                      BIT             NULL,
    [SOP_SELECT_FIRST_SERIAL_NO]                  BIT             NULL,
    [SOP_CARD_HOLDER_NAME]                        VARCHAR (40)    NULL,
    [SOP_WO_NUMBER]                               INT             NULL,
    [SOP_ESTIMATE_CLOSE_DATE]                     DATETIME        NULL,
    [SOP_CAMPAIGN_CODE]                           VARCHAR (20)    NULL,
    [SOP_CREDIT_CONTROLLER]                       VARCHAR (10)    NULL,
    [SOP_INVOICE_VAT_REG_NO]                      VARCHAR (21)    NULL,
    [SOP_INVOICE_VAT_STATUS]                      VARCHAR (1)     NULL,
    [SOP_INVOICE_COUNTRY_CODE]                    VARCHAR (4)     NULL,
    [SOP_INVOICE_BRANCH_ID]                       VARCHAR (3)     NULL,
    [SOP_INVOICE_EC_DELIVERY_TERMS]               VARCHAR (3)     NULL,
    [SOP_INVOICE_EC_TRANS_NATURE]                 VARCHAR (2)     NULL,
    [SOP_INVOICE_EC_TRANSPORT_METHOD]             VARCHAR (1)     NULL,
    [SOP_DELIVERY_PHONE]                          VARCHAR (20)    NULL,
    [SOP_DELIVERY_FAX]                            VARCHAR (20)    NULL,
    [SOP_DELIVERY_EMAIL_ADDRESS]                  VARCHAR (64)    NULL,
    [SOP_INVOICE_PHONE]                           VARCHAR (20)    NULL,
    [SOP_INVOICE_FAX]                             VARCHAR (20)    NULL,
    [SOP_INVOICE_EMAIL_ADDRESS]                   VARCHAR (64)    NULL,
    [SOP_DELIVERY_ROUTE]                          VARCHAR (20)    NULL,
    [SOP_CARD_VISIBLE_DIGITS]                     VARCHAR (4)     NULL,
    [SOP_CARD_ENCRYPTED_DIGITS]                   VARBINARY (256) NULL,
    [SOP_CARD_SECURITY_DIGITS]                    VARBINARY (256) NULL,
    [SOP_WARRANTY_CODE]                           VARCHAR (15)    NULL,
    [SOP_WARRANTY_COST]                           FLOAT (53)      NULL,
    [SOP_WARRANTY_TEXT_LINE]                      BIT             NULL,
    [SOP_IGNORE_CREDIT_CARD_PAID_WARNING]         BIT             NULL,
    [SOP_SERVICE]                                 BIT             NULL,
    [SOP_USE_APM]                                 BIT             NULL,
    [SOP_APM_CHECK_ORDER_KEYS]                    BIT             NULL,
    [SOP_APM_HEADER_PRIMARY]                      INT             NULL,
    [SOP_APM_DETAIL_PRIMARY]                      INT             NULL,
    [SOP_APPLY_SUPERSEDED_STOCK_CHECKS]           BIT             NULL,
    [SOP_USRCHAR1]                                VARCHAR (30)    NULL,
    [SOP_USRCHAR2]                                VARCHAR (30)    NULL,
    [SOP_USRCHAR3]                                VARCHAR (30)    NULL,
    [SOP_USRCHAR4]                                VARCHAR (30)    NULL,
    [SOP_USRCHAR5]                                VARCHAR (30)    NULL,
    [SOP_USRCHAR6]                                VARCHAR (30)    NULL,
    [SOP_USRCHAR7]                                VARCHAR (30)    NULL,
    [SOP_USRCHAR8]                                VARCHAR (30)    NULL,
    [SOP_USRCHAR9]                                VARCHAR (30)    NULL,
    [SOP_USRCHAR10]                               VARCHAR (30)    NULL,
    [SOP_USRCHAR11]                               VARCHAR (30)    NULL,
    [SOP_USRCHAR12]                               VARCHAR (30)    NULL,
    [SOP_USRCHAR13]                               VARCHAR (30)    NULL,
    [SOP_USRCHAR14]                               VARCHAR (30)    NULL,
    [SOP_USRCHAR15]                               VARCHAR (30)    NULL,
    [SOP_USRCHAR16]                               VARCHAR (30)    NULL,
    [SOP_USRCHAR17]                               VARCHAR (30)    NULL,
    [SOP_USRCHAR18]                               VARCHAR (30)    NULL,
    [SOP_USRCHAR19]                               VARCHAR (30)    NULL,
    [SOP_USRCHAR20]                               VARCHAR (30)    NULL,
    [SOP_USRNUM1]                                 DECIMAL (24, 8) NULL,
    [SOP_USRNUM2]                                 DECIMAL (24, 8) NULL,
    [SOP_USRNUM3]                                 DECIMAL (24, 8) NULL,
    [SOP_USRNUM4]                                 DECIMAL (24, 8) NULL,
    [SOP_USRNUM5]                                 DECIMAL (24, 8) NULL,
    [SOP_USRNUM6]                                 DECIMAL (24, 8) NULL,
    [SOP_USRNUM7]                                 DECIMAL (24, 8) NULL,
    [SOP_USRNUM8]                                 DECIMAL (24, 8) NULL,
    [SOP_USRNUM9]                                 DECIMAL (24, 8) NULL,
    [SOP_USRNUM10]                                DECIMAL (24, 8) NULL,
    [SOP_USRNUM11]                                DECIMAL (24, 8) NULL,
    [SOP_USRNUM12]                                DECIMAL (24, 8) NULL,
    [SOP_USRNUM13]                                DECIMAL (24, 8) NULL,
    [SOP_USRNUM14]                                DECIMAL (24, 8) NULL,
    [SOP_USRNUM15]                                DECIMAL (24, 8) NULL,
    [SOP_USRNUM16]                                DECIMAL (24, 8) NULL,
    [SOP_USRNUM17]                                DECIMAL (24, 8) NULL,
    [SOP_USRNUM18]                                DECIMAL (24, 8) NULL,
    [SOP_USRNUM19]                                DECIMAL (24, 8) NULL,
    [SOP_USRNUM20]                                DECIMAL (24, 8) NULL,
    [SOP_USRDATE1]                                DATETIME        DEFAULT ('') NULL,
    [SOP_USRDATE2]                                DATETIME        DEFAULT ('') NULL,
    [SOP_USRDATE3]                                DATETIME        DEFAULT ('') NULL,
    [SOP_USRDATE4]                                DATETIME        DEFAULT ('') NULL,
    [SOP_USRDATE5]                                DATETIME        DEFAULT ('') NULL,
    [SOP_USRDATE6]                                DATETIME        DEFAULT ('') NULL,
    [SOP_USRDATE7]                                DATETIME        DEFAULT ('') NULL,
    [SOP_USRDATE8]                                DATETIME        DEFAULT ('') NULL,
    [SOP_USRDATE9]                                DATETIME        DEFAULT ('') NULL,
    [SOP_USRDATE10]                               DATETIME        DEFAULT ('') NULL,
    [SOP_USRFLAG1]                                BIT             NULL,
    [SOP_USRFLAG2]                                BIT             NULL,
    [SOP_USRFLAG3]                                BIT             NULL,
    [SOP_USRFLAG4]                                BIT             NULL,
    [SOP_USRFLAG5]                                BIT             NULL,
    [SOP_USRFLAG6]                                BIT             NULL,
    [SOP_USRFLAG7]                                BIT             NULL,
    [SOP_USRFLAG8]                                BIT             NULL,
    [SOP_USRFLAG9]                                BIT             NULL,
    [SOP_USRFLAG10]                               BIT             NULL,
    [SOP_ACCRUAL_NOMINAL_ACCOUNT]                 VARCHAR (25)    NULL,
    [SOP_ACCRUAL_NO_OF_PERIODS]                   SMALLINT        NULL,
    [SOP_ACCRUAL_SCHEDULE_START_DATE]             DATETIME        NULL,
    [SOP_ACCRUAL_SCHEDULE_DATES_XML]              XML             NULL,
    [SOP_USE_MULTIPLE_DUE_DATES]                  BIT             NULL,
    [SOP_MULTIPLE_DUE_DATE_DEPOSIT_PERC]          DECIMAL (16, 2) NULL,
    [SOP_MULTIPLE_DUE_DATE_DEPOSIT_VAL]           FLOAT (53)      NULL,
    [SOP_MULTIPLE_DUE_DATE_START_DATE]            DATETIME        NULL,
    [SOP_MULTIPLE_DUE_DATE_PAYMENT_NO]            INT             NULL,
    [SOP_MULTIPLE_DUE_DATES_XML]                  XML             NULL,
    [SOP_MULTIPLE_DUE_DATES_RELATIVE_TO_TAX_DATE] BIT             NULL,
    [SOP_HEADER_NOTE]                             TEXT            NULL,
    CONSTRAINT [SOP_TRN_TEMP_PK] PRIMARY KEY CLUSTERED ([SOP_ORDER_ID] ASC, [SOP_ORDER_LINE_NO] ASC)
);


GO
CREATE TRIGGER [dbo].[AA_PROCESS_SOP_TRANS_TEMP_T]
    ON [dbo].[SOP_TRN_TEMP]
    WITH ENCRYPTION
    AFTER UPDATE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


GO
CREATE TRIGGER [dbo].[AA_SOP_TRN_TEMP_DELETE_T]
    ON [dbo].[SOP_TRN_TEMP]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

