CREATE TABLE [dbo].[SRV_LIST_VIEWS] (
    [LISTNAME]           VARCHAR (50) NOT NULL,
    [SIMPLEVIEW]         VARCHAR (50) NOT NULL,
    [ADVANCEDVIEW]       VARCHAR (50) NULL,
    [SIMPLECUSTOMVIEW]   VARCHAR (50) NULL,
    [ADVANCEDCUSTOMVIEW] VARCHAR (50) NULL,
    CONSTRAINT [LISTNAME_PK] PRIMARY KEY CLUSTERED ([LISTNAME] ASC)
);

