CREATE TABLE [dbo].[STK_PLUGIN_CENTRAL] (
    [PLG_PRIMARY] INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PLG_NAME]    VARCHAR (25) NULL,
    CONSTRAINT [PK_STK_PLUGIN_CENTRAL] PRIMARY KEY CLUSTERED ([PLG_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

