CREATE TABLE [dbo].[STK_FACET_PRODUCT_GROUP] (
    [SFPG_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SFPG_NAME]        VARCHAR (20) NOT NULL,
    [SFPG_USER_PUTIN]  VARCHAR (4)  NULL,
    [SFPG_DATE_PUTIN]  DATETIME     NULL,
    [SFPG_USER_EDITED] VARCHAR (4)  NULL,
    [SFPG_DATE_EDITED] DATETIME     NULL,
    [SFPG_SOURCE]      VARCHAR (1)  NULL,
    CONSTRAINT [SFPG_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SFPG_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

