CREATE TABLE [dbo].[STK_STOCK_LANG] (
    [STKLANG_LANGCODE]  VARCHAR (10) NOT NULL,
    [STKLANG_STOCKCODE] VARCHAR (25) NOT NULL,
    [STKLANG_STOCKNAME] VARCHAR (80) NULL,
    CONSTRAINT [STK_STOCK_LANG_PK] PRIMARY KEY CLUSTERED ([STKLANG_LANGCODE] ASC, [STKLANG_STOCKCODE] ASC)
);

