CREATE TABLE [dbo].[STK_STOCK4] (
    [STK_PRIMARY_4]    FLOAT (53)   NOT NULL,
    [STKCODE4]         VARCHAR (25) NULL,
    [STK_P_BASE2CST1]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_P_BASE2CST2]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_P_BASE2CST3]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_P_BASE2CST4]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_P_BASE2CST5]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_P_BASE2CST6]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_P_BASE2CST7]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_P_BASE2CST8]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_P_BASE2CST9]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_P_BASE2CST10] FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_S_BASE2PRC1]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_S_BASE2PRC2]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_S_BASE2PRC3]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_S_BASE2PRC4]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_S_BASE2PRC5]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_S_BASE2PRC6]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_S_BASE2PRC7]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_S_BASE2PRC8]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_S_BASE2PRC9]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_S_BASE2PRC10] FLOAT (53)   DEFAULT ((0)) NULL,
    CONSTRAINT [STK_PRIMARY_4_PK] PRIMARY KEY CLUSTERED ([STK_PRIMARY_4] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STK_STOCK4_STKCODE4]
    ON [dbo].[STK_STOCK4]([STKCODE4] ASC);

