CREATE TABLE [dbo].[STK_PRICE_MATRIX_TEMP] (
    [STMP_PRIMARY]           INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [STMP_USERNAME]          VARCHAR (5)  NULL,
    [STMP_STOCKCODE]         VARCHAR (25) NULL,
    [STMP_STOCKNAME]         VARCHAR (80) NULL,
    [STMP_STOCKSORT]         VARCHAR (20) NULL,
    [STMP_STOCKUSER1]        VARCHAR (20) NULL,
    [STMP_STOCKUSER2]        VARCHAR (20) NULL,
    [STMP_STOCKUSER3]        VARCHAR (20) NULL,
    [STMP_STH_PRIMARY]       FLOAT (53)   NULL,
    [STMP_STH_NAME]          VARCHAR (40) NULL,
    [STMP_EFFECTIVE]         DATETIME     NULL,
    [STMP_STH_TYPE]          VARCHAR (3)  NULL,
    [STMP_SUB_FILTER]        TINYINT      NULL,
    [STMP_STH_CURRENCY]      VARCHAR (5)  NULL,
    [STMP_PRIORITY]          INT          NULL,
    [STMP_STP_PRIMARY]       FLOAT (53)   NULL,
    [STMP_CURRPRIORITY]      TINYINT      NULL,
    [STMP_PPRIORITY1]        INT          NULL,
    [STMP_CPRIORITY1]        INT          NULL,
    [STMP_FIXED_OR_QTY]      TINYINT      NULL,
    [STMP_FROM]              FLOAT (53)   NULL,
    [STMP_TO]                FLOAT (53)   NULL,
    [STMP_FIXED]             FLOAT (53)   NULL,
    [STMP_DISC]              FLOAT (53)   NULL,
    [STMP_TYPE]              TINYINT      NULL,
    [STMP_BASEPRICE]         FLOAT (53)   NULL,
    [STMP_CURRPRICE]         FLOAT (53)   NULL,
    [STMP_HOMEPRICE]         FLOAT (53)   NULL,
    [STMP_PROD]              VARCHAR (25) NULL,
    [STMP_PROD_TYPE]         VARCHAR (1)  NULL,
    [STMP_DISC_CASH]         FLOAT (53)   NULL,
    [STMP_BUY_QTY]           FLOAT (53)   NULL,
    [STMP_FREE_QTY]          FLOAT (53)   NULL,
    [STMP_MAX_ALLOW]         FLOAT (53)   NULL,
    [STMP_BOGOF_TYPE]        TINYINT      NULL,
    [STMP_MIN_QTY]           FLOAT (53)   NULL,
    [STMP_CHAIN]             FLOAT (53)   NULL,
    [STMP_OVERRIDE]          TINYINT      NULL,
    [STMP_SHOW_PROMPT]       TINYINT      NULL,
    [STMP_BGF_SAME_OR_DIFF]  TINYINT      NULL,
    [STMP_BGF_PROD_TYPE]     VARCHAR (1)  NULL,
    [STMP_BGF_PROD]          VARCHAR (25) NULL,
    [STMP_LISTORDER]         INT          NULL,
    [STMP_IGNORE_DISC]       TINYINT      NULL,
    [STMP_MATCH_ALL]         TINYINT      NULL,
    [STMP_ORDERBY_PRIORITY1] TINYINT      NULL,
    [STMP_ORDERBY_PRIORITY2] TINYINT      NULL,
    [STMP_ORDERBY_PRIORITY3] TINYINT      NULL,
    [STMP_ORDERBY_PRIORITY4] TINYINT      NULL,
    [STMP_ORDERBY_PRIORITY5] TINYINT      NULL,
    [STMP_BGF_INCLUDE_ADD]   TINYINT      NULL,
    [STMP_GROSS_PRICES]      TINYINT      NULL,
    [STMP_APPLY_TO_ALL_CUST] TINYINT      NULL,
    [STMP_APPLY_TO_ALL_PROD] TINYINT      NULL,
    CONSTRAINT [STMP_PRIMARY_PK] PRIMARY KEY CLUSTERED ([STMP_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [STMP_STH_PRIMARY]
    ON [dbo].[STK_PRICE_MATRIX_TEMP]([STMP_STH_PRIMARY] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [STMP_STP_PRIMARY]
    ON [dbo].[STK_PRICE_MATRIX_TEMP]([STMP_STP_PRIMARY] ASC) WITH (FILLFACTOR = 70);

