CREATE TABLE [dbo].[STK_PRICE_MATRIX_WOD_DET] (
    [WODD_PRIMARY]      FLOAT (53)   NOT NULL,
    [WODD_PARENT]       FLOAT (53)   NULL,
    [WODD_FROM]         FLOAT (53)   NULL,
    [WODD_TO]           FLOAT (53)   NULL,
    [WODD_DISC_FIXED]   FLOAT (53)   NULL,
    [WODD_DISC_PERCENT] FLOAT (53)   NULL,
    [WODD_OFFER_TYPE]   TINYINT      DEFAULT ((0)) NULL,
    [WODD_PRCODE]       VARCHAR (30) NULL,
    [WODD_PROD_TYPE]    VARCHAR (1)  NULL,
    [WODD_PROD]         VARCHAR (25) NULL,
    [WODD_FREE_QTY]     FLOAT (53)   DEFAULT ((0)) NULL,
    CONSTRAINT [WODD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([WODD_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [WODD_PARENT]
    ON [dbo].[STK_PRICE_MATRIX_WOD_DET]([WODD_PARENT] ASC) WITH (FILLFACTOR = 70);

