CREATE TABLE [dbo].[STK_FACETS] (
    [SFCT_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SFCT_DESCRIPTION] VARCHAR (40) NOT NULL,
    [SFCT_USER_PUTIN]  VARCHAR (4)  NULL,
    [SFCT_DATE_PUTIN]  DATETIME     NULL,
    [SFCT_USER_EDITED] VARCHAR (4)  NULL,
    [SFCT_DATE_EDITED] DATETIME     NULL,
    [SFCT_SOURCE]      VARCHAR (1)  NULL,
    CONSTRAINT [SFCT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SFCT_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

