CREATE TABLE [dbo].[STK_LOCATION2] (
    [LOC_CODE2]              VARCHAR (25)  NULL,
    [LOC_LANDED_NAME1]       VARCHAR (20)  NULL,
    [LOC_LANDED_NAME2]       VARCHAR (20)  NULL,
    [LOC_LANDED_NAME3]       VARCHAR (20)  NULL,
    [LOC_LANDED_NAME4]       VARCHAR (20)  NULL,
    [LOC_LANDED_NAME5]       VARCHAR (20)  NULL,
    [LOC_LANDED_NAME6]       VARCHAR (20)  NULL,
    [LOC_LANDED_NAME7]       VARCHAR (20)  NULL,
    [LOC_LANDED_NAME8]       VARCHAR (20)  NULL,
    [LOC_LANDED_NAME9]       VARCHAR (20)  NULL,
    [LOC_LANDED_NAME10]      VARCHAR (20)  NULL,
    [LOC_LANDED_VALUE1]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_VALUE2]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_VALUE3]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_VALUE4]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_VALUE5]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_VALUE6]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_VALUE7]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_VALUE8]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_VALUE9]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_VALUE10]     FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_TOTAL1]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_TOTAL2]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_TOTAL3]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_TOTAL4]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_TOTAL5]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_TOTAL6]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_TOTAL7]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_TOTAL8]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_TOTAL9]      FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_TOTAL10]     FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED1_TYPE1]      TINYINT       DEFAULT ((0)) NULL,
    [LOC_LANDED1_TYPE2]      TINYINT       DEFAULT ((0)) NULL,
    [LOC_LANDED1_TYPE3]      TINYINT       DEFAULT ((0)) NULL,
    [LOC_LANDED1_TYPE4]      TINYINT       DEFAULT ((0)) NULL,
    [LOC_LANDED1_TYPE5]      TINYINT       DEFAULT ((0)) NULL,
    [LOC_LANDED1_TYPE6]      TINYINT       DEFAULT ((0)) NULL,
    [LOC_LANDED1_TYPE7]      TINYINT       DEFAULT ((0)) NULL,
    [LOC_LANDED1_TYPE8]      TINYINT       DEFAULT ((0)) NULL,
    [LOC_LANDED1_TYPE9]      TINYINT       DEFAULT ((0)) NULL,
    [LOC_LANDED1_TYPE10]     TINYINT       DEFAULT ((0)) NULL,
    [LOC_USERDATE1]          DATETIME      NULL,
    [LOC_USERDATE2]          DATETIME      NULL,
    [LOC_USERDATE3]          DATETIME      NULL,
    [LOC_USERTEXT1]          VARCHAR (20)  NULL,
    [LOC_USERTEXT2]          VARCHAR (20)  NULL,
    [LOC_USERTEXT3]          VARCHAR (20)  NULL,
    [LOC_USERVALUE1]         FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_USERVALUE2]         FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_USERVALUE3]         FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_USERFLAG1]          TINYINT       DEFAULT ((0)) NULL,
    [LOC_USERFLAG2]          TINYINT       DEFAULT ((0)) NULL,
    [LOC_USERFLAG3]          TINYINT       DEFAULT ((0)) NULL,
    [LOC_SOPCHECK]           TINYINT       DEFAULT ((0)) NULL,
    [LOC_POPCHECK]           TINYINT       DEFAULT ((0)) NULL,
    [LOC_WOCHECK]            TINYINT       DEFAULT ((0)) NULL,
    [LOC_CONCATCODE2]        VARCHAR (50)  NULL,
    [LOC_STOCKCODE2]         VARCHAR (25)  NULL,
    [LOC_PRIMARY2]           FLOAT (53)    NOT NULL,
    [LOC_LANDED_COST]        FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_COMPLETE]    TINYINT       DEFAULT ((0)) NULL,
    [LOC_LANDED_COMMITTED1]  FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_COMMITTED2]  FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_COMMITTED3]  FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_COMMITTED4]  FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_COMMITTED5]  FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_COMMITTED6]  FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_COMMITTED7]  FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_COMMITTED8]  FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_COMMITTED9]  FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_LANDED_COMMITTED10] FLOAT (53)    DEFAULT ((0)) NULL,
    [LOC_USERTEXT4]          VARCHAR (30)  NULL,
    [LOC_USERTEXT5]          VARCHAR (30)  NULL,
    [LOC_USERTEXT6]          VARCHAR (30)  NULL,
    [LOC_LEVEL]              INT           DEFAULT ((0)) NULL,
    [LOC_USERTEXT7]          VARCHAR (100) NULL,
    [LOC_USERTEXT8]          VARCHAR (100) NULL,
    CONSTRAINT [LOC_PRIMARY2_PK] PRIMARY KEY CLUSTERED ([LOC_PRIMARY2] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [LOC_CONCATCODE2]
    ON [dbo].[STK_LOCATION2]([LOC_CONCATCODE2] ASC);


GO
CREATE NONCLUSTERED INDEX [LOC_SOPINDEX]
    ON [dbo].[STK_LOCATION2]([LOC_STOCKCODE2] ASC, [LOC_SOPCHECK] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_STK_LOCATION2_LOC_CODE2]
    ON [dbo].[STK_LOCATION2]([LOC_CODE2] ASC)
    INCLUDE([LOC_USERTEXT1], [LOC_USERTEXT2], [LOC_STOCKCODE2]);

