CREATE TABLE [dbo].[STK_SERIAL_NUMBERS] (
    [SNO_PRIMARY]          INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SNO_STOCK_CODE]       VARCHAR (25) NULL,
    [SNO_SUBANALYSIS]      VARCHAR (25) NULL,
    [SNO_SERIAL_NUMBER]    VARCHAR (40) NULL,
    [SNO_LOT_NUMBER]       VARCHAR (20) NULL,
    [SNO_RENEW_DATE]       DATETIME     NULL,
    [SNO_SORT_KEY]         VARCHAR (20) NULL,
    [SNO_EXCLUDE_FROM_SOP] TINYINT      DEFAULT ((0)) NULL,
    [SNO_USRDATE1]         DATETIME     NULL,
    [SNO_USRDATE2]         DATETIME     NULL,
    [SNO_USRDATE3]         DATETIME     NULL,
    [SNO_NOTES]            TEXT         NULL,
    [SNO_STATUS]           VARCHAR (1)  NULL,
    [SNO_BATCH_FLAG]       TINYINT      DEFAULT ((0)) NULL,
    [SNO_DATE_EDITED]      DATETIME     NULL,
    [SNO_USER_EDITED]      VARCHAR (4)  NULL,
    [SNO_DATE_RECEIVED]    DATETIME     NULL,
    CONSTRAINT [SNO_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SNO_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SNO_SERIAL_NUMBER]
    ON [dbo].[STK_SERIAL_NUMBERS]([SNO_STOCK_CODE] ASC, [SNO_SERIAL_NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [SNO_STATUS]
    ON [dbo].[STK_SERIAL_NUMBERS]([SNO_STOCK_CODE] ASC, [SNO_STATUS] ASC, [SNO_BATCH_FLAG] ASC);

