CREATE TABLE [dbo].[STK_ALTERNATIVE] (
    [STK_ALTN_PRIMARY] FLOAT (53)   NOT NULL,
    [STK_ALTN_PARENT]  VARCHAR (25) NULL,
    [STK_ALTN_CHILD]   VARCHAR (25) NULL,
    CONSTRAINT [STK_ALTN_PRIMARY_PK] PRIMARY KEY CLUSTERED ([STK_ALTN_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STK_ALTN_PARENT]
    ON [dbo].[STK_ALTERNATIVE]([STK_ALTN_PARENT] ASC);


GO
CREATE TRIGGER [dbo].[AA_STK_ALTERNATIVE_ITEM_DELETE_T]
    ON [dbo].[STK_ALTERNATIVE]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

