CREATE TABLE [dbo].[STK_STOCK3] (
    [STK_PRIMARY_3] FLOAT (53)    NOT NULL,
    [STK_CHAR1]     VARCHAR (20)  NULL,
    [STK_CHAR2]     VARCHAR (20)  NULL,
    [STK_CHAR3]     VARCHAR (100) NULL,
    [STK_CHAR4]     VARCHAR (100) NULL,
    [STK_FLAG1]     TINYINT       DEFAULT ((0)) NULL,
    [STK_FLAG2]     TINYINT       DEFAULT ((0)) NULL,
    [STK_DATE1]     DATETIME      NULL,
    [STK_DATE2]     DATETIME      NULL,
    [STK_NUM1]      FLOAT (53)    DEFAULT ((0)) NULL,
    [STK_NUM2]      FLOAT (53)    DEFAULT ((0)) NULL,
    [STK_USRCHAR1]  VARCHAR (20)  NULL,
    [STK_USRCHAR2]  VARCHAR (20)  NULL,
    [STK_USRCHAR3]  VARCHAR (100) NULL,
    [STK_USRCHAR4]  VARCHAR (100) NULL,
    [STK_USRFLAG1]  TINYINT       DEFAULT ((0)) NULL,
    [STK_USRFLAG2]  TINYINT       DEFAULT ((0)) NULL,
    [STK_USRDATE1]  DATETIME      NULL,
    [STK_USRDATE2]  DATETIME      NULL,
    [STK_USRNUM1]   FLOAT (53)    DEFAULT ((0)) NULL,
    [STK_USRNUM2]   FLOAT (53)    DEFAULT ((0)) NULL,
    [STKCODE3]      VARCHAR (25)  NULL,
    [STK_USRCHAR5]  VARCHAR (20)  NULL,
    [STK_USRCHAR6]  VARCHAR (30)  NULL,
    [STK_USRFLAG3]  TINYINT       DEFAULT ((0)) NULL,
    [STK_USRDATE3]  DATETIME      NULL,
    [STK_USRNUM3]   FLOAT (53)    DEFAULT ((0)) NULL,
    [STK_USRCHAR7]  VARCHAR (30)  NULL,
    [STK_USRCHAR8]  VARCHAR (30)  NULL,
    [STK_USRCHAR9]  VARCHAR (30)  NULL,
    [STK_USRCHAR10] VARCHAR (30)  NULL,
    [STK_USRCHAR11] VARCHAR (30)  NULL,
    [STK_USRCHAR12] VARCHAR (30)  NULL,
    [STK_USRCHAR13] VARCHAR (30)  NULL,
    [STK_USRCHAR14] VARCHAR (30)  NULL,
    [STK_USRCHAR15] VARCHAR (30)  NULL,
    [STK_USRCHAR16] VARCHAR (30)  NULL,
    [STK_USRCHAR17] VARCHAR (30)  NULL,
    [STK_USRCHAR18] VARCHAR (30)  NULL,
    [STK_USRCHAR19] VARCHAR (30)  NULL,
    [STK_USRCHAR20] VARCHAR (30)  NULL,
    [STK_USRCHAR21] VARCHAR (30)  NULL,
    [STK_USRCHAR22] VARCHAR (30)  NULL,
    [STK_USRNUM4]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM5]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM6]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM7]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM8]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM9]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM10]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM11]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM12]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM13]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM14]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM15]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM16]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM17]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM18]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM19]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRNUM20]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [STK_USRDATE4]  DATETIME      NULL,
    [STK_USRDATE5]  DATETIME      NULL,
    [STK_USRDATE6]  DATETIME      NULL,
    [STK_USRDATE7]  DATETIME      NULL,
    [STK_USRDATE8]  DATETIME      NULL,
    [STK_USRDATE9]  DATETIME      NULL,
    [STK_USRDATE10] DATETIME      NULL,
    [STK_USRFLAG4]  BIT           DEFAULT ((0)) NOT NULL,
    [STK_USRFLAG5]  BIT           DEFAULT ((0)) NOT NULL,
    [STK_USRFLAG6]  BIT           DEFAULT ((0)) NOT NULL,
    [STK_USRFLAG7]  BIT           DEFAULT ((0)) NOT NULL,
    [STK_USRFLAG8]  BIT           DEFAULT ((0)) NOT NULL,
    [STK_USRFLAG9]  BIT           DEFAULT ((0)) NOT NULL,
    [STK_USRFLAG10] BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [STK_PRIMARY_3_PK] PRIMARY KEY CLUSTERED ([STK_PRIMARY_3] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STK_STOCK3_STKCODE3]
    ON [dbo].[STK_STOCK3]([STKCODE3] ASC);


GO

CREATE TRIGGER dhc_JCC_tr_DiscontinuedStock
   ON  STK_STOCK3
   AFTER INSERT,UPDATE
AS 
BEGIN

	declare @discontinuedFlag bit,@STKCODE varchar(25)
	select @discontinuedFlag=STK_USRFLAG1,@STKCODE=STKCODE3 from inserted

	if (@discontinuedFlag=1)
	begin
		update dhc_tbl_JCC_StockClassHistory set JSCH_CLASSIFICATION='X'

		from dhc_tbl_JCC_StockClassHistoryDates 
		where JSCD_PRIMARY=JSCH_DATEINDEX_LINK
			and JSCD_DATEINDEX=1
			and JSCH_STOCKCODE=@STKCODE

	end
END
