CREATE TABLE [dbo].[STK_DETAIL_PLUGINS_VCHAR] (
    [STDPV_PRIMARY]     INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [STDPV_DETAIL_LINK] FLOAT (53)     NOT NULL,
    [STDPV_TAGNAME]     VARCHAR (100)  NOT NULL,
    [STDPV_TAGVALUE]    VARCHAR (1000) NULL,
    CONSTRAINT [STDPV_PRIMARY_PK] PRIMARY KEY CLUSTERED ([STDPV_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [STDPV_DETAIL_LINK_FK] FOREIGN KEY ([STDPV_DETAIL_LINK]) REFERENCES [dbo].[STK_MOVEMENTS] ([SM_PRIMARY]) ON DELETE CASCADE
);

