CREATE TABLE [dbo].[STK_SERIAL_LINK] (
    [SNOL_PRIMARY]          INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SNOL_SERIAL_LINK]      INT          DEFAULT ((0)) NULL,
    [SNOL_MOVEMENT_LINK]    INT          DEFAULT ((0)) NULL,
    [SNOL_ORDER_LINK]       VARCHAR (20) NULL,
    [SNOL_DIRECTION]        VARCHAR (1)  NULL,
    [SNOL_DATE_ENTERED]     DATETIME     NULL,
    [SNOL_LOT_NUMBER]       VARCHAR (20) NULL,
    [SNOL_RENEW_DATE]       DATETIME     NULL,
    [SNOL_SORT_KEY]         VARCHAR (20) NULL,
    [SNOL_EXCLUDE_FROM_SOP] TINYINT      DEFAULT ((0)) NULL,
    [SNOL_ACCOUNT_REF]      VARCHAR (10) NULL,
    [SNOL_ORDER_REF]        VARCHAR (10) NULL,
    [SNOL_DETAIL_LINK]      INT          DEFAULT ((0)) NULL,
    [SNOL_RTP_LINK]         INT          DEFAULT ((0)) NULL,
    CONSTRAINT [SNOL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SNOL_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SNOL_MOVEMENT_LINK]
    ON [dbo].[STK_SERIAL_LINK]([SNOL_MOVEMENT_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [SNOL_ORDER_LINK]
    ON [dbo].[STK_SERIAL_LINK]([SNOL_ORDER_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [SNOL_RTP_LINK]
    ON [dbo].[STK_SERIAL_LINK]([SNOL_RTP_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [SNOL_SERIAL_LINK]
    ON [dbo].[STK_SERIAL_LINK]([SNOL_SERIAL_LINK] ASC);


GO
CREATE TRIGGER [dbo].[aa_stk_serial_link_dt]
    ON [dbo].[STK_SERIAL_LINK]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

