CREATE TABLE [dbo].[STK_PICTURE] (
    [PIC_STK_CODE]      VARCHAR (25)  NULL,
    [STK_PICT]          IMAGE         NULL,
    [PIC_PRIMARY]       FLOAT (53)    NOT NULL,
    [PIC_PATHNAME]      VARCHAR (255) NULL,
    [PIC_MIGRATED_ADMS] BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PIC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([PIC_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PIC_STK_CODE]
    ON [dbo].[STK_PICTURE]([PIC_STK_CODE] ASC);

