CREATE TABLE [dbo].[STK_ALLOCATIONS] (
    [STK_ALLOC_PRIMARY]       INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [STK_ALLOC_ORDER_NUMBER]  FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_ALLOC_CUSTOMER]      VARCHAR (10) NULL,
    [STK_ALLOC_STKCODE]       VARCHAR (25) NULL,
    [STK_ALLOC_SUBANALYSIS]   VARCHAR (25) NULL,
    [STK_ALLOC_DATE]          DATETIME     NULL,
    [STK_ALLOC_QTYALLOC]      FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_ALLOC_USERID]        VARCHAR (4)  NULL,
    [STK_ALLOC_DEL_QTY]       FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_ALLOC_SERIAL_NUMBER] VARCHAR (40) NULL,
    [STK_ALLOC_OD_LINK]       INT          DEFAULT ((0)) NULL,
    [STK_ALLOC_COSTPRICE]     FLOAT (53)   DEFAULT ((0)) NULL,
    [STK_ALLOC_ORIGIN]        VARCHAR (1)  NULL,
    CONSTRAINT [STK_ALLOC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([STK_ALLOC_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STK_ALLOC_OD_LINK]
    ON [dbo].[STK_ALLOCATIONS]([STK_ALLOC_OD_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [STK_ALLOC_STKCODE]
    ON [dbo].[STK_ALLOCATIONS]([STK_ALLOC_STKCODE] ASC, [STK_ALLOC_SUBANALYSIS] ASC);


GO
CREATE TRIGGER [dbo].[AA_STK_ALLOCATIONS_DELETE_T]
    ON [dbo].[STK_ALLOCATIONS]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

