CREATE TABLE [dbo].[STK_FACET_VALUES] (
    [SFV_PRIMARY]    INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SFV_FACET_LINK] INT          NOT NULL,
    [SFV_VALUE]      VARCHAR (20) NOT NULL,
    [SFV_ORDER]      INT          NOT NULL,
    CONSTRAINT [SFV_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SFV_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SFV_FACET_LINK_FK] FOREIGN KEY ([SFV_FACET_LINK]) REFERENCES [dbo].[STK_FACETS] ([SFCT_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SFV_FACET_LINK]
    ON [dbo].[STK_FACET_VALUES]([SFV_FACET_LINK] ASC, [SFV_ORDER] ASC) WITH (FILLFACTOR = 70);

