CREATE TABLE [dbo].[STK_PRICE_MATRIX_WOD_TEMP] (
    [STMPW_PRIMARY]           INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [STMPW_USERNAME]          VARCHAR (5)  NULL,
    [STMPW_STH_PRIMARY]       FLOAT (53)   NULL,
    [STMPW_STH_NAME]          VARCHAR (40) NULL,
    [STMPW_EFFECTIVE]         DATETIME     NULL,
    [STMPW_STH_CURRENCY]      VARCHAR (5)  NULL,
    [STMPW_PRIORITY]          INT          NULL,
    [STMPW_STP_PRIMARY]       FLOAT (53)   NULL,
    [STMPW_CURRPRIORITY]      TINYINT      NULL,
    [STMPW_QUAL_TYPE]         TINYINT      NULL,
    [STMPW_QUAL_VAL]          FLOAT (53)   NULL,
    [STMPW_QUAL_QTY]          FLOAT (53)   NULL,
    [STMPW_DISC_FIXED]        FLOAT (53)   NULL,
    [STMPW_DISC_PERCENT]      FLOAT (53)   NULL,
    [STMPW_PRCODE]            VARCHAR (16) NULL,
    [STMPW_SINGLE_OR_MULTI]   TINYINT      NULL,
    [STMPW_OFFER_TYPE]        TINYINT      NULL,
    [STMPW_PROD_TYPE]         VARCHAR (1)  NULL,
    [STMPW_PROD]              VARCHAR (25) NULL,
    [STMPW_FREE_QTY]          FLOAT (53)   NULL,
    [STMPW_GROSS_PRICES]      TINYINT      NULL,
    [STMPW_APPLY_TO_ALL_CUST] TINYINT      NULL,
    [STMPW_APPLY_TO_ALL_PROD] TINYINT      NULL,
    [STMPW_QUANTITY]          FLOAT (53)   NULL,
    [STMPW_VALUE]             FLOAT (53)   NULL,
    [STMPW_WODD_PRIMARY]      FLOAT (53)   NULL,
    [STMPW_VAT_VALUE]         FLOAT (53)   NULL,
    [STMPW_DISCOUNT_TYPE]     TINYINT      NULL,
    CONSTRAINT [STMPW_PRIMARY_PK] PRIMARY KEY CLUSTERED ([STMPW_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE NONCLUSTERED INDEX [STMPW_STH_PRIMARY]
    ON [dbo].[STK_PRICE_MATRIX_WOD_TEMP]([STMPW_STH_PRIMARY] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [STMPW_STP_PRIMARY]
    ON [dbo].[STK_PRICE_MATRIX_WOD_TEMP]([STMPW_STP_PRIMARY] ASC) WITH (FILLFACTOR = 70);

