CREATE TABLE [dbo].[STK_FACET_LINKS] (
    [SFL_STOCK_LINK]       FLOAT (53) NOT NULL,
    [SFL_FACET_LINK]       INT        NOT NULL,
    [SFL_FACET_VALUE_LINK] INT        NOT NULL,
    CONSTRAINT [STK_FACET_LINKS_PK] PRIMARY KEY CLUSTERED ([SFL_STOCK_LINK] ASC, [SFL_FACET_VALUE_LINK] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SFL_FACET_LINK_FK] FOREIGN KEY ([SFL_FACET_LINK]) REFERENCES [dbo].[STK_FACETS] ([SFCT_PRIMARY]),
    CONSTRAINT [SFL_FACET_VALUE_LINK_FK] FOREIGN KEY ([SFL_FACET_VALUE_LINK]) REFERENCES [dbo].[STK_FACET_VALUES] ([SFV_PRIMARY]),
    CONSTRAINT [SFL_STOCK_LINK_FK] FOREIGN KEY ([SFL_STOCK_LINK]) REFERENCES [dbo].[STK_STOCK] ([STK_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SFL_FACET_LINK]
    ON [dbo].[STK_FACET_LINKS]([SFL_FACET_LINK] ASC, [SFL_STOCK_LINK] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [SFL_FACET_VALUE_LINK]
    ON [dbo].[STK_FACET_LINKS]([SFL_FACET_VALUE_LINK] ASC) WITH (FILLFACTOR = 70);

