CREATE TABLE [dbo].[STK_ALLOCATION_LINK] (
    [STK_ALINK_PRIMARY]          INT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [STK_ALINK_ALLOCATION_KEY]   INT         DEFAULT ((0)) NULL,
    [STK_ALINK_MOVEMENT_KEY]     INT         DEFAULT ((0)) NULL,
    [STK_ALINK_QUANTITY]         FLOAT (53)  DEFAULT ((0)) NULL,
    [STK_ALINK_ORIGIN]           VARCHAR (1) NULL,
    [STK_ALINK_ORDER_LINK]       INT         DEFAULT ((0)) NULL,
    [STK_ALINK_OUT_MOVEMENT_KEY] INT         DEFAULT ((0)) NULL,
    CONSTRAINT [STK_ALINK_PRIMARY_PK] PRIMARY KEY CLUSTERED ([STK_ALINK_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STK_ALINK_MOVEMENT_KEY]
    ON [dbo].[STK_ALLOCATION_LINK]([STK_ALINK_MOVEMENT_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [STK_ALINK_ORDER_LINK]
    ON [dbo].[STK_ALLOCATION_LINK]([STK_ALINK_ORDER_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_STK_ALLOCATION_LINK_STK_ALINK_ORIGIN_STK_ALINK_ORDER_LINK]
    ON [dbo].[STK_ALLOCATION_LINK]([STK_ALINK_ORIGIN] ASC, [STK_ALINK_ORDER_LINK] ASC);

