CREATE TABLE [dbo].[STK_DETAIL_PLUGINS_DATETIME] (
    [STDPD_PRIMARY]     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [STDPD_DETAIL_LINK] FLOAT (53)    NOT NULL,
    [STDPD_TAGNAME]     VARCHAR (100) NOT NULL,
    [STDPD_TAGVALUE]    DATETIME      NULL,
    CONSTRAINT [STDPD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([STDPD_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [STDPD_DETAIL_LINK_FK] FOREIGN KEY ([STDPD_DETAIL_LINK]) REFERENCES [dbo].[STK_MOVEMENTS] ([SM_PRIMARY]) ON DELETE CASCADE
);

