CREATE TABLE [dbo].[STK_FACET_VALUES_TEMP] (
    [SFVT_ID]            INT          NOT NULL,
    [SFVT_ORDER]         INT          NULL,
    [SFVT_DEFAULT_ORDER] INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SFVT_VALUE]         VARCHAR (20) NULL,
    [SFVT_VALUE_PRIMARY] INT          NULL,
    CONSTRAINT [STK_FACET_VALUES_TEMP_PK] PRIMARY KEY CLUSTERED ([SFVT_ID] ASC, [SFVT_DEFAULT_ORDER] ASC) WITH (FILLFACTOR = 70)
);

