CREATE TABLE [dbo].[SYS_LOOKUP_CODE] (
    [LCDE_CODE]        VARCHAR (25) NULL,
    [LCDE_DESCRIPTION] VARCHAR (40) NULL,
    [LCDE_ORIGIN]      VARCHAR (8)  NULL,
    [LCDE_TYPE]        INT          DEFAULT ((0)) NULL,
    [LCDE_PRIMARY]     FLOAT (53)   NOT NULL,
    [LCDE_SORT_ORDER]  INT          DEFAULT ((0)) NULL,
    CONSTRAINT [LCDE_PRIMARY_PK] PRIMARY KEY CLUSTERED ([LCDE_PRIMARY] ASC)
);

