CREATE TABLE [dbo].[SYS_VSD_PURCH_INFO] (
    [VSDP_PRIMARY] FLOAT (53) NOT NULL,
    CONSTRAINT [VSDP_PRIMARY_PK] PRIMARY KEY CLUSTERED ([VSDP_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [VSDP_PRIMARY_FK] FOREIGN KEY ([VSDP_PRIMARY]) REFERENCES [dbo].[PL_TRANSACTIONS] ([PT_PRIMARY]) ON DELETE CASCADE
);

