CREATE TABLE [dbo].[SYS_HMRC_SUBMISSIONS] (
    [HMRC_PRIMARY]           INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [HMRC_TYPE]              INT          DEFAULT ((0)) NOT NULL,
    [HMRC_DATE]              DATETIME     NULL,
    [HMRC_PERIOD_END_DATE]   DATETIME     NULL,
    [HMRC_USER]              VARCHAR (4)  NULL,
    [HMRC_CORRELATION_ID]    VARCHAR (40) NULL,
    [HMRC_NIL_RETURN]        BIT          DEFAULT ((0)) NOT NULL,
    [HMRC_REFERENCE]         VARCHAR (10) NULL,
    [HMRC_INCLUDE_GOODS]     BIT          DEFAULT ((0)) NOT NULL,
    [HMRC_INCLUDE_SERVICES]  BIT          DEFAULT ((0)) NOT NULL,
    [HMRC_TEST_SUBMISSION]   BIT          DEFAULT ((0)) NOT NULL,
    [HMRC_PERIOD_START_DATE] DATETIME     NULL,
    [HMRC_PERIOD_TYPE]       TINYINT      NULL,
    [HMRC_SUCCESSFUL]        BIT          DEFAULT ((0)) NOT NULL,
    CONSTRAINT [HMRC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([HMRC_PRIMARY] ASC)
);

