CREATE TABLE [dbo].[SYS_DOCUMENTS] (
    [DOC_PRIMARY]          INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [DOC_MODULEOPTION]     VARCHAR (31)  NULL,
    [DOC_MODULE]           VARCHAR (3)   NULL,
    [DOC_RECORDTYPE]       VARCHAR (6)   NULL,
    [DOC_RECORDCODE]       VARCHAR (25)  NULL,
    [DOC_STATUS]           TINYINT       DEFAULT ((0)) NULL,
    [DOC_DESCRIPTION]      VARCHAR (50)  NULL,
    [DOC_FILENAME]         VARCHAR (255) NULL,
    [DOC_USER_PUTIN]       VARCHAR (4)   NULL,
    [DOC_DATE_PUTIN]       DATETIME      NULL,
    [DOC_USER_EDITED]      VARCHAR (4)   NULL,
    [DOC_DATE_EDITED]      DATETIME      NULL,
    [DOC_REFERENCE]        VARCHAR (25)  NULL,
    [DOC_TRANSACTION_TYPE] VARCHAR (3)   NULL,
    [DOC_DOCUMENT_NUMBER]  VARCHAR (10)  NULL,
    CONSTRAINT [DOC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([DOC_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DOC_MODULEOPTION]
    ON [dbo].[SYS_DOCUMENTS]([DOC_MODULEOPTION] ASC);

