CREATE TABLE [dbo].[SYS_TRAN_SUBTYPES_TEMP] (
    [TT_GUID]           UNIQUEIDENTIFIER NOT NULL,
    [TT_SEQUENCE]       BIGINT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [TT_STATUS]         TINYINT          NULL,
    [TT_PRIMARY]        INT              NULL,
    [TT_TYPE]           VARCHAR (3)      NULL,
    [TT_NAME]           VARCHAR (10)     NULL,
    [TT_DESC]           VARCHAR (40)     NULL,
    [TT_DEFAULT_STRING] VARCHAR (5)      NULL,
    CONSTRAINT [TT_TRAN_SUBTYPES_PK] PRIMARY KEY CLUSTERED ([TT_GUID] ASC, [TT_SEQUENCE] ASC)
);

