CREATE TABLE [dbo].[SYS_DEFAULT_TRANSACTION_TEMPLATE] (
    [USER_ID]        VARCHAR (4) NOT NULL,
    [TRANSACTION_ID] INT         NOT NULL,
    [TEMPLATE_ID]    INT         NOT NULL,
    CONSTRAINT [PK_DEFAULT_TRANSACTION_TEMPLATE] PRIMARY KEY CLUSTERED ([TRANSACTION_ID] ASC, [USER_ID] ASC)
);

