CREATE TABLE [dbo].[SYS_RECORD_TEMPLATE] (
    [TEMPLATE_ID]            INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [TEMPLATE_NAME]          VARCHAR (255) NULL,
    [DISPLAY_LAYOUT]         IMAGE         NOT NULL,
    [TAB_CONFIGURATION]      IMAGE         NOT NULL,
    [RECORD_ID]              INT           NOT NULL,
    [SYSTEM_DEFAULT]         BIT           NULL,
    [ENTERED_BY]             VARCHAR (4)   NOT NULL,
    [DATE_PUTIN]             DATETIME      NULL,
    [DATE_EDITED]            DATETIME      NULL,
    [SPLITTER_CONFIGURATION] IMAGE         NOT NULL,
    CONSTRAINT [PK_SYS_RECORD_TEMPLATE] PRIMARY KEY CLUSTERED ([TEMPLATE_ID] ASC)
);

