CREATE TABLE [dbo].[SYS_USER2] (
    [USER_PRIMARY_2]       FLOAT (53) NOT NULL,
    [USER_NLB_BALCONTRA]   TINYINT    DEFAULT ((0)) NULL,
    [USER_NLB_MULTICONTRA] TINYINT    DEFAULT ((0)) NULL,
    [USER_NLB_ARCHIVE]     TINYINT    DEFAULT ((0)) NULL,
    [USER_NLB_BATCH]       TINYINT    DEFAULT ((0)) NULL,
    [USER_NLB_BYPASSSTATS] TINYINT    DEFAULT ((0)) NULL,
    [USER_NLB_COPYDETAIL]  TINYINT    DEFAULT ((0)) NULL,
    CONSTRAINT [USER_PRIMARY_2_PK] PRIMARY KEY CLUSTERED ([USER_PRIMARY_2] ASC)
);

