CREATE TABLE [dbo].[SYS_USER_WIN_OBJECTS] (
    [UWO_PRIMARY]          INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [UWO_USER_ID]          VARCHAR (4)  NULL,
    [UWO_WINDOW_NAME]      VARCHAR (40) NULL,
    [UWO_OBJECT_ID]        INT          DEFAULT ((0)) NULL,
    [UWO_PARENT_OBJECT_ID] INT          DEFAULT ((0)) NULL,
    [UWO_OBJECT_GROUP]     VARCHAR (2)  NULL,
    [UWO_OBJECT_LEFT]      INT          DEFAULT ((0)) NULL,
    [UWO_OBJECT_WIDTH]     INT          DEFAULT ((0)) NULL,
    CONSTRAINT [UWO_PRIMARY_PK] PRIMARY KEY CLUSTERED ([UWO_PRIMARY] ASC)
);

