CREATE TABLE [dbo].[SYS_DIMENSIONS] (
    [DIM_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [DIM_TEXT]        VARCHAR (20) NULL,
    [DIM_USER_PUTIN]  VARCHAR (4)  NULL,
    [DIM_DATE_PUTIN]  DATETIME     NULL,
    [DIM_USER_EDITED] VARCHAR (4)  NULL,
    [DIM_DATE_EDITED] DATETIME     NULL,
    [DIM_TYPE1]       TINYINT      DEFAULT ((0)) NULL,
    [DIM_TYPE2]       TINYINT      DEFAULT ((0)) NULL,
    [DIM_TYPE3]       TINYINT      DEFAULT ((0)) NULL,
    [DIM_SORTORDER]   INT          DEFAULT ((0)) NULL,
    [DIM_SL]          TINYINT      DEFAULT ((0)) NULL,
    [DIM_PL]          TINYINT      DEFAULT ((0)) NULL,
    [DIM_NL]          TINYINT      DEFAULT ((0)) NULL,
    [DIM_SOP]         TINYINT      DEFAULT ((0)) NULL,
    [DIM_POP]         TINYINT      DEFAULT ((0)) NULL,
    CONSTRAINT [DIM_PRIMARY_PK] PRIMARY KEY CLUSTERED ([DIM_PRIMARY] ASC)
);

