CREATE TABLE [dbo].[SYS_TAX_AUDITDETAIL] (
    [TAXAUDIT_DET_HEADER] FLOAT (53)  NOT NULL,
    [TAXAUDIT_DET_CODE]   VARCHAR (4) NOT NULL,
    [TAXAUDIT_DET_VALUE]  FLOAT (53)  DEFAULT ((0)) NULL,
    CONSTRAINT [SYS_TAX_AUDITDETAIL_PK] PRIMARY KEY CLUSTERED ([TAXAUDIT_DET_HEADER] ASC, [TAXAUDIT_DET_CODE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TAXAUDIT_DET_HEADER]
    ON [dbo].[SYS_TAX_AUDITDETAIL]([TAXAUDIT_DET_HEADER] ASC);

