CREATE TABLE [dbo].[SYS_LANGUAGE_LABEL_TEXT] (
    [LANGUAGE_LABEL_TEXT_PRIMARY] INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [LANGUAGE_TEXT]               NVARCHAR (250) NOT NULL,
    CONSTRAINT [LANGUAGE_LABEL_TEXT_PK] PRIMARY KEY CLUSTERED ([LANGUAGE_LABEL_TEXT_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LANGUAGE_TEXT]
    ON [dbo].[SYS_LANGUAGE_LABEL_TEXT]([LANGUAGE_TEXT] ASC);

