CREATE TABLE [dbo].[SYS_DEL_HISTORY_HEADER] (
    [DHH_ORIGIN]           VARCHAR (3)   NULL,
    [DHH_ORDER_NO]         VARCHAR (15)  NULL,
    [DHH_DELIVERYNOTE_NO]  INT           DEFAULT ((0)) NULL,
    [DHH_SUPP_DELNOTE_NO]  VARCHAR (15)  NULL,
    [DHH_ACCOUNT]          VARCHAR (10)  NULL,
    [DHH_PRIMARY]          INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [DHH_DATE_UPDATED]     DATETIME      NULL,
    [DHH_DELIVERY_ADDRESS] VARCHAR (240) NULL,
    [DHH_INVOICE_ADDRESS]  VARCHAR (240) NULL,
    [DHH_USER]             VARCHAR (4)   NULL,
    [DHH_ORDER_REF]        VARCHAR (20)  NULL,
    [DHH_DEL_METHOD]       VARCHAR (20)  NULL,
    [DHH_DATE_REQUIRED]    DATETIME      NULL,
    CONSTRAINT [DHH_PRIMARY_PK] PRIMARY KEY CLUSTERED ([DHH_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DHH_DELIVERYNOTE_NO]
    ON [dbo].[SYS_DEL_HISTORY_HEADER]([DHH_DELIVERYNOTE_NO] ASC, [DHH_ORIGIN] ASC);


GO
CREATE NONCLUSTERED INDEX [DHH_ORDER_NO]
    ON [dbo].[SYS_DEL_HISTORY_HEADER]([DHH_ORDER_NO] ASC, [DHH_ORIGIN] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SYS_DEL_HISTORY_HEADER_DHH_ORIGIN]
    ON [dbo].[SYS_DEL_HISTORY_HEADER]([DHH_ORIGIN] ASC)
    INCLUDE([DHH_ORDER_NO], [DHH_DELIVERYNOTE_NO], [DHH_PRIMARY], [DHH_DATE_UPDATED], [DHH_DELIVERY_ADDRESS]);


GO
CREATE TRIGGER [dbo].[AA_DEL_HISTORY_HEADER_DELETE_T]
    ON [dbo].[SYS_DEL_HISTORY_HEADER]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

