CREATE TABLE [dbo].[SYS_DOCUMENT_CONFIGURATION] (
    [SDC_TYPE]             INT            NOT NULL,
    [SDC_STATIONARY_LINK]  INT            NOT NULL,
    [SDC_NO_COPIES]        TINYINT        NULL,
    [SDC_COPY_1_DESTN]     TINYINT        NULL,
    [SDC_COPY_1_RECIPIENT] NVARCHAR (255) NULL,
    [SDC_COPY_2_DESTN]     TINYINT        NULL,
    [SDC_COPY_2_RECIPIENT] NVARCHAR (255) NULL,
    [SDC_COPY_3_DESTN]     TINYINT        NULL,
    [SDC_COPY_3_RECIPIENT] NVARCHAR (255) NULL,
    [SDC_ATTACH_PDF]       BIT            NULL,
    [SDC_EMAIL_SUBJECT_1]  NVARCHAR (100) NULL,
    [SDC_EMAIL_MESSAGE_1]  TEXT           NULL,
    [SDC_EMAIL_SUBJECT_2]  NVARCHAR (100) NULL,
    [SDC_EMAIL_MESSAGE_2]  TEXT           NULL,
    [SDC_EMAIL_SUBJECT_3]  NVARCHAR (100) NULL,
    [SDC_EMAIL_MESSAGE_3]  TEXT           NULL,
    [SDC_EDITED_BY]        VARCHAR (4)    NULL,
    [SDC_DATE_EDITED]      DATETIME       NULL,
    CONSTRAINT [SDC_TYPE_PK] PRIMARY KEY CLUSTERED ([SDC_TYPE] ASC)
);

