CREATE TABLE [dbo].[SYS_USER_TOOLBAR] (
    [USER_TOOL_PRIMARY] INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [USER_TOOL_USERID]  VARCHAR (4)   NULL,
    [USER_TOOL_NUMBER]  INT           DEFAULT ((0)) NULL,
    [USER_TOOL_ICONID]  INT           DEFAULT ((0)) NULL,
    [USER_TOOL_OPTION]  VARCHAR (255) NULL,
    [USER_TOOL_TOOLTIP] VARCHAR (30)  NULL,
    [USER_TOOL_LINK]    TINYINT       DEFAULT ((0)) NULL,
    CONSTRAINT [USER_TOOL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([USER_TOOL_PRIMARY] ASC)
);

