CREATE TABLE [dbo].[SYS_SMTP_USERS] (
    [SMTP_USER_PRIMARY]     INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SMTP_USER_SERVER_LINK] INT             NOT NULL,
    [SMTP_USER_NAME]        VARCHAR (128)   NULL,
    [SMTP_USER_PASSWORD]    VARBINARY (256) NULL,
    [SMTP_USER_USE_DEFAULT] BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SMTP_USER_PRIMARY] PRIMARY KEY CLUSTERED ([SMTP_USER_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SMTP_USER_USE_DEFAULT_CK] CHECK ([SMTP_USER_USE_DEFAULT]=(0) AND [SMTP_USER_NAME] IS NOT NULL AND [SMTP_USER_NAME]<>'' OR [SMTP_USER_USE_DEFAULT]=(1) AND ([SMTP_USER_NAME] IS NULL OR [SMTP_USER_NAME]='') AND [SMTP_USER_PASSWORD] IS NULL),
    CONSTRAINT [SMTP_USER_SERVER_LINK_FK] FOREIGN KEY ([SMTP_USER_SERVER_LINK]) REFERENCES [dbo].[SYS_SMTP_SERVERS] ([SMTP_SRVR_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SMTP_USER_SERVER_LINK]
    ON [dbo].[SYS_SMTP_USERS]([SMTP_USER_SERVER_LINK] ASC, [SMTP_USER_USE_DEFAULT] ASC, [SMTP_USER_NAME] ASC) WITH (FILLFACTOR = 70);

