CREATE TABLE [dbo].[SYS_YEAR] (
    [YEAR_PRIMARY]       SMALLINT     NOT NULL,
    [YEAR_COSTING]       SMALLINT     NULL,
    [YEAR_COSTING_CODE]  NVARCHAR (1) NULL,
    [YEAR_SALES]         SMALLINT     NULL,
    [YEAR_SALES_CODE]    NVARCHAR (1) NULL,
    [YEAR_PURCHASE]      SMALLINT     NULL,
    [YEAR_PURCHASE_CODE] NVARCHAR (1) NULL,
    [YEAR_NOMINAL]       SMALLINT     NULL,
    [YEAR_NOMINAL_CODE]  NVARCHAR (1) NULL,
    [YEAR_STARTDATE]     DATETIME     NULL,
    [YEAR_ENDDATE]       DATETIME     NULL,
    [YEAR_LABEL]         VARCHAR (7)  NULL,
    CONSTRAINT [YEAR_PRIMARY_PK] PRIMARY KEY CLUSTERED ([YEAR_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [YEAR_LABEL]
    ON [dbo].[SYS_YEAR]([YEAR_LABEL] ASC);

