CREATE TABLE [dbo].[SYS_RECORD_LIST_SEARCHES] (
    [SRLS_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SRLS_LIST_ID]     VARCHAR (4)  NOT NULL,
    [SRLS_NAME]        VARCHAR (64) NOT NULL,
    [SRLS_DATE_PUTIN]  DATETIME     DEFAULT (getdate()) NOT NULL,
    [SRLS_USER_PUTIN]  VARCHAR (4)  NOT NULL,
    [SRLS_DATE_EDITED] DATETIME     NULL,
    [SRLS_USER_EDITED] VARCHAR (4)  NULL,
    CONSTRAINT [SRLS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SRLS_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SRLS_LIST_ID_CK] CHECK ([SRLS_LIST_ID]<>'')
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SRLS_PRIMARY_SRLS_LIST_ID]
    ON [dbo].[SYS_RECORD_LIST_SEARCHES]([SRLS_PRIMARY] ASC, [SRLS_LIST_ID] ASC)
    INCLUDE([SRLS_NAME]) WITH (FILLFACTOR = 70);

