CREATE TABLE [dbo].[SYS_REPORT_USER_DEFAULTS] (
    [USER_ID]   VARCHAR (4) NOT NULL,
    [OPTION_ID] BIGINT      NOT NULL,
    CONSTRAINT [USER_ID_OPTION_ID_PK] PRIMARY KEY CLUSTERED ([USER_ID] ASC, [OPTION_ID] ASC),
    CONSTRAINT [SYS_REPORT_OPTION_ID_FK] FOREIGN KEY ([OPTION_ID]) REFERENCES [dbo].[SYS_REPORT_OPTIONS] ([OPTION_ID]) ON DELETE CASCADE,
    CONSTRAINT [SYS_REPORT_USER_ID_FK] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[SYS_USER] ([USER_ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [OPTION_ID]
    ON [dbo].[SYS_REPORT_USER_DEFAULTS]([OPTION_ID] ASC);

