CREATE TABLE [dbo].[SYS_WINDOW_LAYOUT_FILES] (
    [WLF_PRIMARY]     INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WLF_LAYOUT_LINK] INT            NOT NULL,
    [WLF_FILE_NAME]   NVARCHAR (255) NOT NULL,
    [WLF_FILE]        IMAGE          NOT NULL,
    CONSTRAINT [WLF_PRIMARY_PK] PRIMARY KEY CLUSTERED ([WLF_PRIMARY] ASC),
    CONSTRAINT [SYS_WINDOW_LAYOUT_FILES_LAYOUT_LINK_FK] FOREIGN KEY ([WLF_LAYOUT_LINK]) REFERENCES [dbo].[SYS_WINDOW_LAYOUTS] ([WL_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WLF_FILE_NAME]
    ON [dbo].[SYS_WINDOW_LAYOUT_FILES]([WLF_FILE_NAME] ASC, [WLF_LAYOUT_LINK] ASC);

