CREATE TABLE [dbo].[SYS_LANGUAGE_MESSAGE_TEXT] (
    [LANGUAGE_MESSAGE_TEXT_PRIMARY] INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [LANGUAGE_MESSAGE_TEXT]         NVARCHAR (250) NOT NULL,
    CONSTRAINT [LANGUAGE_MESSAGE_TEXT_PK] PRIMARY KEY CLUSTERED ([LANGUAGE_MESSAGE_TEXT_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [LANGUAGE_MESSAGE_TEXT]
    ON [dbo].[SYS_LANGUAGE_MESSAGE_TEXT]([LANGUAGE_MESSAGE_TEXT] ASC);

