CREATE TABLE [dbo].[SYS_DOC_CONFIG_TEMP] (
    [SDT_GUID]             UNIQUEIDENTIFIER NOT NULL,
    [SDT_SEQUENCE]         BIGINT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SDT_TYPE]             INT              NOT NULL,
    [SDT_STATIONARY_LINK]  INT              NOT NULL,
    [SDT_NO_COPIES]        TINYINT          NULL,
    [SDT_COPY_1_DESTN]     TINYINT          NULL,
    [SDT_COPY_1_RECIPIENT] NVARCHAR (255)   NULL,
    [SDT_COPY_2_DESTN]     TINYINT          NULL,
    [SDT_COPY_2_RECIPIENT] NVARCHAR (255)   NULL,
    [SDT_COPY_3_DESTN]     TINYINT          NULL,
    [SDT_COPY_3_RECIPIENT] NVARCHAR (255)   NULL,
    [SDT_ATTACH_PDF]       BIT              NULL,
    [SDT_EMAIL_SUBJECT_1]  NVARCHAR (100)   NULL,
    [SDT_EMAIL_MESSAGE_1]  TEXT             NULL,
    [SDT_EMAIL_SUBJECT_2]  NVARCHAR (100)   NULL,
    [SDT_EMAIL_MESSAGE_2]  TEXT             NULL,
    [SDT_EMAIL_SUBJECT_3]  NVARCHAR (100)   NULL,
    [SDT_EMAIL_MESSAGE_3]  TEXT             NULL,
    CONSTRAINT [SYS_DOC_CONFIG_TEMP_PK] PRIMARY KEY CLUSTERED ([SDT_GUID] ASC, [SDT_SEQUENCE] ASC)
);

