CREATE TABLE [dbo].[SYS_LIST_SEARCH_CRITERIA] (
    [SEARCH_CRITERIA_ID]  INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SEARCH_CRITERIA]     IMAGE         NOT NULL,
    [SEARCH_NAME]         VARCHAR (255) NULL,
    [LIST_ID]             INT           NOT NULL,
    [ORDERBYASCENDING]    TINYINT       NOT NULL,
    [ORDER_BY_FIELD_NAME] VARCHAR (128) NOT NULL,
    [ENTERED_BY]          VARCHAR (4)   NOT NULL,
    [DATE_PUTIN]          DATETIME      NULL,
    [DATE_EDITED]         DATETIME      NULL,
    CONSTRAINT [PK_SYS_LIST_SEARCH_CRITERIA] PRIMARY KEY CLUSTERED ([SEARCH_CRITERIA_ID] ASC)
);


GO
CREATE TRIGGER [dbo].[AA_DELETE_SYS_LIST_SEARCH_CRITERIA_T]
    ON [dbo].[SYS_LIST_SEARCH_CRITERIA]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

