CREATE TABLE [dbo].[SYS_DATAINFO] (
    [COMPANY_NAME]                          VARCHAR (40)    NULL,
    [COMP_ADDRESS]                          VARCHAR (160)   NULL,
    [COMP_TELEPHONE]                        VARCHAR (20)    NULL,
    [COMP_TELX]                             VARCHAR (15)    NULL,
    [COMP_FAX]                              VARCHAR (20)    NULL,
    [COMP_VATNUMBER]                        VARCHAR (15)    NULL,
    [COMP_REGNUMBER]                        VARCHAR (20)    NULL,
    [COMP_BRANCHID]                         VARCHAR (3)     NULL,
    [COMP_NOTES]                            TEXT            NULL,
    [COMP_ADDRESS_USER1]                    VARCHAR (30)    NULL,
    [COMP_ADDRESS_USER2]                    VARCHAR (30)    NULL,
    [COMP_POSTCODE]                         VARCHAR (12)    NULL,
    [COMP_FACTORING]                        VARCHAR (240)   NULL,
    [COMP_INVSUB_TXT]                       VARCHAR (80)    NULL,
    [COMPANYDATANAME]                       VARCHAR (30)    NULL,
    [HOME_TAXNAME]                          VARCHAR (10)    NULL,
    [CST_RESORCE_UPD]                       TINYINT         DEFAULT ((0)) NULL,
    [STK_USR_VALUATN]                       VARCHAR (1)     NULL,
    [STK_USR_QTY]                           VARCHAR (1)     NULL,
    [STK_SNAP_FIFO]                         FLOAT (53)      DEFAULT ((0)) NULL,
    [STK_SNAP_AVERAG]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [STK_SNAP_LATEST]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [STK_SNAP_DATE]                         DATETIME        NULL,
    [STK_LOC_COPY]                          VARCHAR (1)     NULL,
    [STK_NEGATIVE]                          TINYINT         DEFAULT ((0)) NULL,
    [NOM_VAT_CNTRL]                         VARCHAR (25)    NULL,
    [NOM_SUSPENSE]                          VARCHAR (25)    NULL,
    [NOM_SALES]                             VARCHAR (25)    NULL,
    [NOM_SALES_CNTRL]                       VARCHAR (25)    NULL,
    [NOM_SALES_DISC]                        VARCHAR (25)    NULL,
    [NOM_MAIN_BANK]                         VARCHAR (25)    NULL,
    [NOM_PURCHASE]                          VARCHAR (25)    NULL,
    [NOM_PURCH_CNTRL]                       VARCHAR (25)    NULL,
    [NOM_PURCH_DISC]                        VARCHAR (25)    NULL,
    [NOM_YEAR_UPDATE]                       VARCHAR (25)    NULL,
    [CST_DEF_TRNSTAT]                       TINYINT         DEFAULT ((0)) NULL,
    [HOME_COUNTRY]                          VARCHAR (4)     NULL,
    [USE_PRE_PRINTED]                       TINYINT         DEFAULT ((0)) NULL,
    [HIDE_ADDRESS]                          TINYINT         DEFAULT ((0)) NULL,
    [POP_ORDER_NO]                          FLOAT (53)      DEFAULT ((0)) NULL,
    [MULTI_PART_STAT]                       TINYINT         DEFAULT ((0)) NULL,
    [SHOW_STOCK_CODE]                       TINYINT         DEFAULT ((0)) NULL,
    [LEAV_BLANK_LINE]                       TINYINT         DEFAULT ((0)) NULL,
    [INV_FULL_ORDER]                        TINYINT         DEFAULT ((0)) NULL,
    [PREPRNT_HEADING]                       TINYINT         DEFAULT ((0)) NULL,
    [ALLOCAT_REF]                           FLOAT (53)      DEFAULT ((0)) NULL,
    [INC_ALLOC_MATCH]                       TINYINT         DEFAULT ((0)) NULL,
    [PRINT_DELIV_ADD]                       TINYINT         DEFAULT ((0)) NULL,
    [STATIONERY_OPTN]                       TINYINT         DEFAULT ((0)) NULL,
    [CST_DEF_RECSTAT]                       TINYINT         DEFAULT ((0)) NULL,
    [CST_HEADER_UPD]                        TINYINT         DEFAULT ((0)) NULL,
    [PREPRINT_LINES]                        TINYINT         DEFAULT ((0)) NULL,
    [STK_AUTO_PRILST]                       TINYINT         DEFAULT ((0)) NULL,
    [POP_GRN_NO]                            FLOAT (53)      DEFAULT ((0)) NULL,
    [HOME_CURR_SYMBL]                       VARCHAR (4)     NULL,
    [SPREDSHT_FORMAT]                       VARCHAR (1)     NULL,
    [P_BLANK_LINE]                          TINYINT         DEFAULT ((0)) NULL,
    [EC_VAT_INSTAL]                         TINYINT         DEFAULT ((0)) NULL,
    [CASHVAT_INSTAL]                        TINYINT         DEFAULT ((0)) NULL,
    [LOGON_INSTAL]                          TINYINT         DEFAULT ((0)) NULL,
    [MENUNAME]                              TINYINT         DEFAULT ((0)) NULL,
    [SHOW_SUP_STKCDE]                       TINYINT         DEFAULT ((0)) NULL,
    [DO_NOT_PRNT_GRN]                       TINYINT         DEFAULT ((0)) NULL,
    [DO_NOT_PRNT_ORD]                       TINYINT         DEFAULT ((0)) NULL,
    [POP_SHOW_STKCDE]                       TINYINT         DEFAULT ((0)) NULL,
    [INV_SUB_OPTION]                        TINYINT         DEFAULT ((0)) NULL,
    [NEXT_JNL_NUMBR]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [NEXT_PL_NUMBR]                         FLOAT (53)      DEFAULT ((0)) NULL,
    [SL_PRINTED_INV]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SL_PRINTED_CRN]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SL_PRINTED_PAY]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SL_PRINTED_ADR]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SL_PRINTED_ACR]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SL_PRINTED_AUD]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [IN_PRINTED_INV]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [IN_PRINTED_CRN]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SL_AUDIT_COUNT]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SL_IGNORE_AUDIT]                       TINYINT         DEFAULT ((0)) NULL,
    [PL_PRINTED_INV]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_PRINTED_CRN]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_PRINTED_PAY]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_PRINTED_ADR]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_PRINTED_ACR]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_PRINTED_AUD]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_AUDIT_COUNT]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_IGNORE_AUDIT]                       TINYINT         DEFAULT ((0)) NULL,
    [AUTO_NUMBR_JNL]                        TINYINT         DEFAULT ((0)) NULL,
    [AUTO_NUMBR_PL]                         TINYINT         DEFAULT ((0)) NULL,
    [NL_PRINTED_AUD]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [NL_AUDIT_COUNT]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SO_CONFM_NYPSEQ]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [STK_PRINTED_MOV]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [CST_PRINTED_TRN]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [SO_PRINTED_AUD]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SO_AUDIT_COUNT]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [PO_PRINTED_AUD]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [PO_AUDIT_COUNT]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SO_MAIL_NYPSEQ]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SL_AGEING_MTHD]                        VARCHAR (1)     NULL,
    [SL_AGEING_DAYS1]                       TINYINT         DEFAULT ((0)) NULL,
    [SL_AGEING_DAYS2]                       TINYINT         DEFAULT ((0)) NULL,
    [SL_AGEING_DAYS3]                       TINYINT         DEFAULT ((0)) NULL,
    [SL_AGEING_DAYS4]                       TINYINT         DEFAULT ((0)) NULL,
    [PL_AGEING_MTHD]                        VARCHAR (1)     NULL,
    [PL_AGEING_DAYS1]                       TINYINT         DEFAULT ((0)) NULL,
    [PL_AGEING_DAYS2]                       TINYINT         DEFAULT ((0)) NULL,
    [PL_AGEING_DAYS3]                       TINYINT         DEFAULT ((0)) NULL,
    [PL_AGEING_DAYS4]                       TINYINT         DEFAULT ((0)) NULL,
    [NL_IGNORE_AUDIT]                       TINYINT         DEFAULT ((0)) NULL,
    [PL_REF_ON_REP]                         TINYINT         DEFAULT ((0)) NULL,
    [NO_OF_USERS_IN]                        TINYINT         DEFAULT ((0)) NULL,
    [SL_BATCH_IN_USE]                       TINYINT         DEFAULT ((0)) NULL,
    [PL_BATCH_IN_USE]                       TINYINT         DEFAULT ((0)) NULL,
    [NL_BATCH_IN_USE]                       TINYINT         DEFAULT ((0)) NULL,
    [SYS_VAT_IN_USE]                        TINYINT         DEFAULT ((0)) NULL,
    [SK_BATCH_IN_USE]                       TINYINT         DEFAULT ((0)) NULL,
    [SO_BATCH_IN_USE]                       TINYINT         DEFAULT ((0)) NULL,
    [PO_BATCH_IN_USE]                       TINYINT         DEFAULT ((0)) NULL,
    [CT_BATCH_IN_USE]                       TINYINT         DEFAULT ((0)) NULL,
    [PL_CHEQS_IN_USE]                       TINYINT         DEFAULT ((0)) NULL,
    [CF_BATCH_IN_USE]                       TINYINT         DEFAULT ((0)) NULL,
    [STK_MAT_STKOPT]                        TINYINT         DEFAULT ((0)) NULL,
    [STK_MAT_CUSTOPT]                       TINYINT         DEFAULT ((0)) NULL,
    [STK_DLRREP_KEY]                        VARCHAR (20)    NULL,
    [SOP_CSTPRC_OPT]                        TINYINT         DEFAULT ((0)) NULL,
    [CHK_LOC_QTY]                           TINYINT         DEFAULT ((0)) NULL,
    [USE_MAX_LIST]                          TINYINT         DEFAULT ((0)) NULL,
    [MAX_LIST_SIZE]                         INT             DEFAULT ((0)) NULL,
    [CF_PERIODS]                            INT             DEFAULT ((0)) NULL,
    [CF_PERTYPE]                            VARCHAR (1)     NULL,
    [RTP_ORDER_NO]                          FLOAT (53)      DEFAULT ((0)) NULL,
    [RTP_ENTER_NO]                          TINYINT         DEFAULT ((0)) NULL,
    [POP_ENTER_NO]                          TINYINT         DEFAULT ((0)) NULL,
    [PEND_LOOP_STATUS]                      FLOAT (53)      DEFAULT ((0)) NULL,
    [PL_CHEQUE_NO]                          VARCHAR (10)    NULL,
    [PERIOD_END_OPTN]                       VARCHAR (2)     NULL,
    [SALES_PERIOD]                          FLOAT (53)      DEFAULT ((0)) NULL,
    [PURCHASE_PERIOD]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [NOMINAL_PERIOD]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SALES_UPDTEYEAR]                       VARCHAR (1)     NULL,
    [PURCH_UPDTEYEAR]                       VARCHAR (1)     NULL,
    [SALES_UPDATENOM]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [PURCH_UPDATENOM]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [COSTING_PERIOD]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [STOCK_PERIOD]                          FLOAT (53)      DEFAULT ((0)) NULL,
    [CO_BANK_SORT]                          VARCHAR (10)    NULL,
    [CO_BANK_AC_NO]                         VARCHAR (15)    NULL,
    [CO_BANK_AC_NAME]                       VARCHAR (25)    NULL,
    [AUTO_CUST_TAB]                         TINYINT         DEFAULT ((0)) NULL,
    [AUTO_CUST_NOTES]                       TINYINT         DEFAULT ((0)) NULL,
    [AUTO_STK_NOTES]                        TINYINT         DEFAULT ((0)) NULL,
    [CST_UPLIFT_TYPE]                       TINYINT         DEFAULT ((0)) NULL,
    [WIND_POS_OPTS]                         FLOAT (53)      DEFAULT ((0)) NULL,
    [WIND_STAGGER_H]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [WIND_STAGGER_W]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [AUTO_NUMBR_JOB]                        TINYINT         DEFAULT ((0)) NULL,
    [AUTO_NUMBR_CUST]                       TINYINT         DEFAULT ((0)) NULL,
    [NEXT_CUST_NUMBR]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [CAPS_CUST_NAME]                        TINYINT         DEFAULT ((0)) NULL,
    [TAB_ACC_SEARCH]                        TINYINT         DEFAULT ((0)) NULL,
    [TAB_STK_SEARCH]                        TINYINT         DEFAULT ((0)) NULL,
    [NEXT_JOB_NUMBR]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [LINE_DISCOUNT]                         FLOAT (53)      DEFAULT ((0)) NULL,
    [TOTAL_DISCOUNT]                        FLOAT (53)      DEFAULT ((0)) NULL,
    [SETTLE_DISC_1]                         FLOAT (53)      DEFAULT ((0)) NULL,
    [SETTLE_DISC_2]                         FLOAT (53)      DEFAULT ((0)) NULL,
    [SETTLE_DAYS_1]                         FLOAT (53)      DEFAULT ((0)) NULL,
    [SETTLE_DAYS_2]                         FLOAT (53)      DEFAULT ((0)) NULL,
    [TERMS]                                 VARCHAR (40)    NULL,
    [DELIV_CHG_FIXED]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [DELIV_CHG_PRCNT]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [DELIV_METHOD]                          VARCHAR (20)    NULL,
    [MIN_ORDER_VALUE]                       FLOAT (53)      DEFAULT ((0)) NULL,
    [DUE_DAYS]                              FLOAT (53)      DEFAULT ((0)) NULL,
    [CREDIT_LIMIT]                          FLOAT (53)      DEFAULT ((0)) NULL,
    [DUE_DATE_TYPE]                         TINYINT         DEFAULT ((0)) NULL,
    [YEAR_START_DATE]                       DATETIME        NULL,
    [FIRSTWEEK_DAYS]                        TINYINT         DEFAULT ((0)) NULL,
    [SOP_SWTCH_DEF]                         TINYINT         DEFAULT ((0)) NULL,
    [NORMAL_DAYS]                           TINYINT         DEFAULT ((0)) NULL,
    [URGENT_DAYS]                           TINYINT         DEFAULT ((0)) NULL,
    [P_NORMAL_DAYS]                         TINYINT         DEFAULT ((0)) NULL,
    [P_URGENT_DAYS]                         TINYINT         DEFAULT ((0)) NULL,
    [CHEQUE_STATNRY]                        TINYINT         DEFAULT ((0)) NULL,
    [PEND_UPDATE_STATUS]                    VARCHAR (10)    NULL,
    [DATE_CREATED]                          DATETIME        NULL,
    [PROGRAMTYPE]                           VARCHAR (3)     NULL,
    [SYS_PRIMARY]                           FLOAT (53)      NOT NULL,
    [NOM_FINDISC_C]                         VARCHAR (25)    NULL,
    [NOM_FINDISC_I]                         VARCHAR (25)    NULL,
    [NOM_PAYDIFF_C]                         VARCHAR (25)    NULL,
    [NOM_PAYDIFF_I]                         VARCHAR (25)    NULL,
    [NOM_BANKCOST]                          VARCHAR (25)    NULL,
    [NOM_DIFFERENCE]                        VARCHAR (25)    NULL,
    [PRICE_DPS]                             TINYINT         DEFAULT ((0)) NULL,
    [QUANTITY_DPS]                          TINYINT         DEFAULT ((0)) NULL,
    [VALUE_DPS]                             TINYINT         DEFAULT ((0)) NULL,
    [VAT_DPS]                               TINYINT         DEFAULT ((2)) NULL,
    [INVREG_ROUTE_MASK]                     VARCHAR (10)    NULL,
    [STK_SNAP_WAPU]                         FLOAT (53)      DEFAULT ((0)) NULL,
    [COMP_EMAIL]                            VARCHAR (64)    NULL,
    [COMP_COUNTRY]                          VARCHAR (35)    NULL,
    [STK_BARCODE_MAPPING]                   VARCHAR (2)     NULL,
    [CUSTOM_DOCUMENT_FIELDS]                VARCHAR (7)     NULL,
    [CO_IBAN_NO]                            VARCHAR (34)    NULL,
    [STK_BARCODE_FONT]                      VARCHAR (100)   NULL,
    [EU_START_DATE]                         DATETIME        NULL,
    [BACS_LAYOUT]                           TINYINT         DEFAULT ((0)) NULL,
    [CO_BANK_AC_BACSREF]                    VARCHAR (18)    NULL,
    [PEND_STEP_SIZE]                        INT             DEFAULT ((0)) NULL,
    [SOP_DELIVERY_NOTE_SUB_OPTION]          TINYINT         DEFAULT ((0)) NULL,
    [CRM_DEALER_FIELD]                      TINYINT         DEFAULT ((3)) NOT NULL,
    [CRM_DLR_FIELD_PREFIX]                  VARCHAR (18)    NULL,
    [CRM_USE_PRODUCT_IN_PC_MATRIX]          BIT             DEFAULT ((0)) NOT NULL,
    [LABEL_RECORD_SPACING]                  FLOAT (53)      DEFAULT ((0)) NOT NULL,
    [LABEL_REPEAT_FACTOR]                   TINYINT         DEFAULT ((0)) NOT NULL,
    [LABEL_LABEL_WIDTH]                     FLOAT (53)      DEFAULT ((0)) NOT NULL,
    [LABEL_LEFT_MARGIN]                     FLOAT (53)      DEFAULT ((0)) NOT NULL,
    [LABEL_TOP_MARGIN]                      FLOAT (53)      DEFAULT ((0)) NOT NULL,
    [LABEL_BOTTOM_MARGIN]                   FLOAT (53)      DEFAULT ((0)) NOT NULL,
    [LABEL_UNITS]                           TINYINT         DEFAULT ((0)) NOT NULL,
    [LABEL_LABELS_ACROSS]                   TINYINT         DEFAULT ((0)) NOT NULL,
    [CO_BANK_REF]                           INT             CONSTRAINT [DF_SYS_DATAINFO_CO_BANK_REF] DEFAULT ((0)) NULL,
    [CO_BACS_REMIT_ADVICE]                  TINYINT         DEFAULT ((0)) NULL,
    [DO_NOT_PRINT_ORD_VIA_REQUESTS]         TINYINT         DEFAULT ((0)) NULL,
    [OS_ITEM_DELNOTE]                       TINYINT         DEFAULT ((0)) NULL,
    [CAPS_SUPP_NAME]                        BIT             DEFAULT ((0)) NOT NULL,
    [BACKGROUND_IMAGE_FILENAME]             VARCHAR (255)   NULL,
    [CALC_STOCK_LEVEL_FROM_SA]              BIT             DEFAULT ((0)) NOT NULL,
    [EXCLUDE_SA_TRANSFERS]                  BIT             DEFAULT ((0)) NOT NULL,
    [ACCOUNT_FOR_CARBON]                    BIT             DEFAULT ((0)) NOT NULL,
    [CARBON_YEAR_PERIOD_FROM_DATE_OPTION]   BIT             DEFAULT ((0)) NOT NULL,
    [CUST_SORT_KEY_RESTRICTION]             TINYINT         DEFAULT ((0)) NOT NULL,
    [CUST_USER_SORT1_RESTRICTION]           TINYINT         DEFAULT ((0)) NOT NULL,
    [CUST_USER_SORT2_RESTRICTION]           TINYINT         DEFAULT ((0)) NOT NULL,
    [CUST_USER_SORT3_RESTRICTION]           TINYINT         DEFAULT ((0)) NOT NULL,
    [SL_USER_SORT1_RESTRICTION]             TINYINT         DEFAULT ((0)) NOT NULL,
    [SL_USER_SORT2_RESTRICTION]             TINYINT         DEFAULT ((0)) NOT NULL,
    [SL_USER_SORT3_RESTRICTION]             TINYINT         DEFAULT ((0)) NOT NULL,
    [SUPP_SORT_KEY_RESTRICTION]             TINYINT         DEFAULT ((0)) NOT NULL,
    [SUPP_USER_SORT1_RESTRICTION]           TINYINT         DEFAULT ((0)) NOT NULL,
    [SUPP_USER_SORT2_RESTRICTION]           TINYINT         DEFAULT ((0)) NOT NULL,
    [SUPP_USER_SORT3_RESTRICTION]           TINYINT         DEFAULT ((0)) NOT NULL,
    [PL_USER_SORT1_RESTRICTION]             TINYINT         DEFAULT ((0)) NOT NULL,
    [PL_USER_SORT2_RESTRICTION]             TINYINT         DEFAULT ((0)) NOT NULL,
    [PL_USER_SORT3_RESTRICTION]             TINYINT         DEFAULT ((0)) NOT NULL,
    [STK_SORT_KEY_RESTRICTION]              TINYINT         DEFAULT ((0)) NOT NULL,
    [STK_USER_SORT1_RESTRICTION]            TINYINT         DEFAULT ((0)) NOT NULL,
    [STK_USER_SORT2_RESTRICTION]            TINYINT         DEFAULT ((0)) NOT NULL,
    [STK_USER_SORT3_RESTRICTION]            TINYINT         DEFAULT ((0)) NOT NULL,
    [SYS_USE_DMS]                           BIT             DEFAULT ((0)) NOT NULL,
    [SYS_DMS_WEBSERVICE_URL]                VARCHAR (255)   NULL,
    [SYS_DMS_WEBSITE_URL]                   VARCHAR (255)   NULL,
    [SYS_DATABASE_PASSWORD]                 VARBINARY (256) NULL,
    [IR_QUERY_WHEN_QTY_INV_MORE_THAN_DEL]   BIT             DEFAULT ((0)) NOT NULL,
    [INVREG_ROUTE_MASK_POP]                 VARCHAR (10)    NULL,
    [NL_USE_ADVANCED]                       BIT             DEFAULT ((0)) NOT NULL,
    [ANL_NOM_SEPARATOR]                     VARCHAR (1)     DEFAULT ('') NULL,
    [ANL_NUMBER_OF_CAT_LEVELS]              TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_DETAIL_LEVEL]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL1_SETUP]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL2_SETUP]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL3_SETUP]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL4_SETUP]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL5_SETUP]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL6_SETUP]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL7_SETUP]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL8_SETUP]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL1_ENTRY]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL2_ENTRY]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL3_ENTRY]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL4_ENTRY]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL5_ENTRY]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL6_ENTRY]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL7_ENTRY]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL8_ENTRY]                  TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL1_LENGTH]                 TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL2_LENGTH]                 TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL3_LENGTH]                 TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL4_LENGTH]                 TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL5_LENGTH]                 TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL6_LENGTH]                 TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL7_LENGTH]                 TINYINT         DEFAULT ((0)) NULL,
    [ANL_CAT_LEVEL8_LENGTH]                 TINYINT         DEFAULT ((0)) NULL,
    [YEAR_LABEL_AS_END_YEAR]                BIT             DEFAULT ((1)) NOT NULL,
    [SUPP_USER_SORT4_RESTRICTION]           TINYINT         DEFAULT ((0)) NOT NULL,
    [DEFAULT_CARBON_INFO_VERSION]           SMALLINT        DEFAULT ((0)) NOT NULL,
    [ANL_CONCATENATE_METHOD]                TINYINT         DEFAULT ((0)) NOT NULL,
    [CO_HMRC_VOS_USER_ID]                   VARCHAR (20)    NULL,
    [CO_HMRC_VOS_PASSWORD]                  VARCHAR (12)    NULL,
    [ECSL_REPORT_FREQUENCY]                 TINYINT         DEFAULT ((0)) NOT NULL,
    [ECSL_REPORT_FORMAT]                    TINYINT         DEFAULT ((0)) NOT NULL,
    [ECSL_BY_DATE]                          BIT             DEFAULT ((0)) NOT NULL,
    [ROUND_ORDER_VAT_TO_5DP]                BIT             DEFAULT ((0)) NOT NULL,
    [SOP_HOLD_ORDERS_OVER_LIMIT]            BIT             DEFAULT ((0)) NOT NULL,
    [SOP_INCLUDE_ESTIMATES_IN_LIMIT_CALC]   BIT             DEFAULT ((0)) NOT NULL,
    [STOCK_FORECASTING_VERSION]             VARCHAR (3)     NULL,
    [LOCK_FAILED_USERS]                     BIT             DEFAULT ((0)) NOT NULL,
    [TOOLBARS_ON_RIBBON]                    BIT             DEFAULT ((1)) NOT NULL,
    [NOMINAL_BUDGETS_HAVE_REVISIONS]        BIT             DEFAULT ((0)) NOT NULL,
    [INVREG_BATCH_INV_AFTER_APPROVALS]      BIT             DEFAULT ((1)) NOT NULL,
    [INVREG_PO_FOCALPOINT_APPROVALS]        BIT             DEFAULT ((0)) NOT NULL,
    [INVREG_PO_FOCALPOINT_MATCH]            BIT             DEFAULT ((0)) NOT NULL,
    [INVREG_PL_FOCALPOINT_APPROVALS]        BIT             DEFAULT ((0)) NOT NULL,
    [INVREG_PL_FOCALPOINT_ENTER_DETAIL]     BIT             DEFAULT ((0)) NOT NULL,
    [DEFAULT_DD_COLLECTION_ELAPSED_DAYS]    TINYINT         DEFAULT ((14)) NOT NULL,
    [RECALC_POP_CURRENCY_ORDERS]            TINYINT         DEFAULT ((2)) NOT NULL,
    [USE_PROFILE_SA_DEFAULTS_IN_TRANS]      BIT             DEFAULT ((0)) NOT NULL,
    [SYS_WFF_WEBSERVICE_URL]                VARCHAR (255)   NULL,
    [INVREG_PO_APPROVE_AFTER_MATCH]         BIT             DEFAULT ((0)) NOT NULL,
    [CST_ALLOW_CONTRACTS_IN_TRANSACTIONS]   BIT             DEFAULT ((0)) NOT NULL,
    [PL_INC_CHQ_NUM_BY_REMIT_PAGES_PRINTED] BIT             DEFAULT ((0)) NOT NULL,
    [AUTO_NUMBER_SUPPLIER]                  BIT             DEFAULT ((0)) NOT NULL,
    [DEFAULT_EMAIL_ADDRESS_NAME]            VARCHAR (128)   NULL,
    [DEFAULT_EMAIL_ADDRESS]                 VARCHAR (128)   NULL,
    [DEFAULT_EMAIL_BCC_ADDRESS]             VARCHAR (128)   NULL,
    [DEFAULT_EMAIL_COPY_TO_BCC]             BIT             DEFAULT ((0)) NOT NULL,
    [DEFAULT_EMAIL_SMTP_USER_LINK]          INT             NULL,
    [EMAIL_ENCRYPTION_PASSWORD]             VARBINARY (256) NULL,
    [ANL_SETUP]                             BIT             DEFAULT ((0)) NOT NULL,
    [SYS_ACD_DOCUMENTS_PATH]                VARCHAR (255)   NULL,
    [ACD_THEME]                             VARCHAR (20)    DEFAULT ('Default') NULL,
    [CO_BANK_BIC_CODE]                      VARCHAR (11)    NULL,
    [STK_USE_FACETS]                        BIT             DEFAULT ((0)) NOT NULL,
    [SL_DD_ONLY_COLLECT_SUGGESTED_TRANS]    BIT             DEFAULT ((0)) NOT NULL,
    [INVREG_PL_APPROVE_AFTER_ENTER_DETAIL]  BIT             DEFAULT ((0)) NOT NULL,
    [DEFAULT_DD_TYPE]                       VARCHAR (1)     DEFAULT ('B') NOT NULL,
    CONSTRAINT [SYS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SYS_PRIMARY] ASC),
    CONSTRAINT [ANL_CAT_DETAIL_LEVEL_CK] CHECK ([ANL_CAT_DETAIL_LEVEL]=[ANL_CAT_LEVEL8_SETUP] OR [ANL_CAT_DETAIL_LEVEL]=[ANL_CAT_LEVEL7_SETUP] OR [ANL_CAT_DETAIL_LEVEL]=[ANL_CAT_LEVEL6_SETUP] OR [ANL_CAT_DETAIL_LEVEL]=[ANL_CAT_LEVEL5_SETUP] OR [ANL_CAT_DETAIL_LEVEL]=[ANL_CAT_LEVEL4_SETUP] OR [ANL_CAT_DETAIL_LEVEL]=[ANL_CAT_LEVEL3_SETUP] OR [ANL_CAT_DETAIL_LEVEL]=[ANL_CAT_LEVEL2_SETUP] OR [ANL_CAT_DETAIL_LEVEL]=[ANL_CAT_LEVEL1_SETUP] OR [ANL_CAT_DETAIL_LEVEL]=(0)),
    CONSTRAINT [ANL_CAT_LEVEL_ENTRY_CK] CHECK (([ANL_CAT_LEVEL1_ENTRY]>=(1) AND [ANL_CAT_LEVEL1_ENTRY]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(1) OR [ANL_CAT_LEVEL1_ENTRY]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]=(0)) AND ([ANL_CAT_LEVEL2_ENTRY]>=(1) AND [ANL_CAT_LEVEL2_ENTRY]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(2) AND NOT [ANL_CAT_LEVEL2_ENTRY]=[ANL_CAT_LEVEL1_ENTRY] OR [ANL_CAT_LEVEL2_ENTRY]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(2)) AND ([ANL_CAT_LEVEL3_ENTRY]>=(1) AND [ANL_CAT_LEVEL3_ENTRY]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(3) AND NOT ([ANL_CAT_LEVEL3_ENTRY]=[ANL_CAT_LEVEL2_ENTRY] OR [ANL_CAT_LEVEL3_ENTRY]=[ANL_CAT_LEVEL1_ENTRY]) OR [ANL_CAT_LEVEL3_ENTRY]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(3)) AND ([ANL_CAT_LEVEL4_ENTRY]>=(1) AND [ANL_CAT_LEVEL4_ENTRY]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(4) AND NOT ([ANL_CAT_LEVEL4_ENTRY]=[ANL_CAT_LEVEL3_ENTRY] OR [ANL_CAT_LEVEL4_ENTRY]=[ANL_CAT_LEVEL2_ENTRY] OR [ANL_CAT_LEVEL4_ENTRY]=[ANL_CAT_LEVEL1_ENTRY]) OR [ANL_CAT_LEVEL4_ENTRY]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(4)) AND ([ANL_CAT_LEVEL5_ENTRY]>=(1) AND [ANL_CAT_LEVEL5_ENTRY]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(5) AND NOT ([ANL_CAT_LEVEL5_ENTRY]=[ANL_CAT_LEVEL4_ENTRY] OR [ANL_CAT_LEVEL5_ENTRY]=[ANL_CAT_LEVEL3_ENTRY] OR [ANL_CAT_LEVEL5_ENTRY]=[ANL_CAT_LEVEL2_ENTRY] OR [ANL_CAT_LEVEL5_ENTRY]=[ANL_CAT_LEVEL1_ENTRY]) OR [ANL_CAT_LEVEL5_ENTRY]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(5)) AND ([ANL_CAT_LEVEL6_ENTRY]>=(1) AND [ANL_CAT_LEVEL6_ENTRY]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(6) AND NOT ([ANL_CAT_LEVEL6_ENTRY]=[ANL_CAT_LEVEL5_ENTRY] OR [ANL_CAT_LEVEL6_ENTRY]=[ANL_CAT_LEVEL4_ENTRY] OR [ANL_CAT_LEVEL6_ENTRY]=[ANL_CAT_LEVEL3_ENTRY] OR [ANL_CAT_LEVEL6_ENTRY]=[ANL_CAT_LEVEL2_ENTRY] OR [ANL_CAT_LEVEL6_ENTRY]=[ANL_CAT_LEVEL1_ENTRY]) OR [ANL_CAT_LEVEL6_ENTRY]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(6)) AND ([ANL_CAT_LEVEL7_ENTRY]>=(1) AND [ANL_CAT_LEVEL7_ENTRY]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(7) AND NOT ([ANL_CAT_LEVEL7_ENTRY]=[ANL_CAT_LEVEL6_ENTRY] OR [ANL_CAT_LEVEL7_ENTRY]=[ANL_CAT_LEVEL5_ENTRY] OR [ANL_CAT_LEVEL7_ENTRY]=[ANL_CAT_LEVEL4_ENTRY] OR [ANL_CAT_LEVEL7_ENTRY]=[ANL_CAT_LEVEL3_ENTRY] OR [ANL_CAT_LEVEL7_ENTRY]=[ANL_CAT_LEVEL2_ENTRY] OR [ANL_CAT_LEVEL7_ENTRY]=[ANL_CAT_LEVEL1_ENTRY]) OR [ANL_CAT_LEVEL7_ENTRY]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(7)) AND ([ANL_CAT_LEVEL8_ENTRY]>=(1) AND [ANL_CAT_LEVEL8_ENTRY]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]=(8) AND NOT ([ANL_CAT_LEVEL8_ENTRY]=[ANL_CAT_LEVEL7_ENTRY] OR [ANL_CAT_LEVEL8_ENTRY]=[ANL_CAT_LEVEL6_ENTRY] OR [ANL_CAT_LEVEL8_ENTRY]=[ANL_CAT_LEVEL5_ENTRY] OR [ANL_CAT_LEVEL8_ENTRY]=[ANL_CAT_LEVEL4_ENTRY] OR [ANL_CAT_LEVEL8_ENTRY]=[ANL_CAT_LEVEL3_ENTRY] OR [ANL_CAT_LEVEL8_ENTRY]=[ANL_CAT_LEVEL2_ENTRY] OR [ANL_CAT_LEVEL8_ENTRY]=[ANL_CAT_LEVEL1_ENTRY]) OR [ANL_CAT_LEVEL8_ENTRY]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(8))),
    CONSTRAINT [ANL_CAT_LEVEL_LENGTH_CK] CHECK ([ANL_SETUP]=(1) AND ([ANL_CAT_LEVEL1_LENGTH]>=(1) AND [ANL_CAT_LEVEL1_LENGTH]<=(6) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(1) OR [ANL_CAT_LEVEL1_LENGTH]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]=(0)) AND ([ANL_CAT_LEVEL2_LENGTH]>=(1) AND [ANL_CAT_LEVEL2_LENGTH]<=(6) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(2) OR [ANL_CAT_LEVEL2_LENGTH]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(2)) AND ([ANL_CAT_LEVEL3_LENGTH]>=(1) AND [ANL_CAT_LEVEL3_LENGTH]<=(6) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(3) OR [ANL_CAT_LEVEL3_LENGTH]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(3)) AND ([ANL_CAT_LEVEL4_LENGTH]>=(1) AND [ANL_CAT_LEVEL4_LENGTH]<=(6) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(4) OR [ANL_CAT_LEVEL4_LENGTH]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(4)) AND ([ANL_CAT_LEVEL5_LENGTH]>=(1) AND [ANL_CAT_LEVEL5_LENGTH]<=(6) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(5) OR [ANL_CAT_LEVEL5_LENGTH]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(5)) AND ([ANL_CAT_LEVEL6_LENGTH]>=(1) AND [ANL_CAT_LEVEL6_LENGTH]<=(6) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(6) OR [ANL_CAT_LEVEL6_LENGTH]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(6)) AND ([ANL_CAT_LEVEL7_LENGTH]>=(1) AND [ANL_CAT_LEVEL7_LENGTH]<=(6) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(7) OR [ANL_CAT_LEVEL7_LENGTH]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(7)) AND ([ANL_CAT_LEVEL8_LENGTH]>=(1) AND [ANL_CAT_LEVEL8_LENGTH]<=(6) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(8) OR [ANL_CAT_LEVEL8_LENGTH]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(8)) OR [ANL_SETUP]=(0) AND ((((((([ANL_CAT_LEVEL1_LENGTH]+[ANL_CAT_LEVEL2_LENGTH])+[ANL_CAT_LEVEL3_LENGTH])+[ANL_CAT_LEVEL4_LENGTH])+[ANL_CAT_LEVEL5_LENGTH])+[ANL_CAT_LEVEL6_LENGTH])+[ANL_CAT_LEVEL7_LENGTH])+[ANL_CAT_LEVEL8_LENGTH])=(0)),
    CONSTRAINT [ANL_CAT_LEVEL_SETUP_CK] CHECK (([ANL_CAT_LEVEL1_SETUP]>=(1) AND [ANL_CAT_LEVEL1_SETUP]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(1) OR [ANL_CAT_LEVEL1_SETUP]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]=(0)) AND ([ANL_CAT_LEVEL2_SETUP]>=(1) AND [ANL_CAT_LEVEL2_SETUP]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(2) AND NOT [ANL_CAT_LEVEL2_SETUP]=[ANL_CAT_LEVEL1_SETUP] OR [ANL_CAT_LEVEL2_SETUP]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(2)) AND ([ANL_CAT_LEVEL3_SETUP]>=(1) AND [ANL_CAT_LEVEL3_SETUP]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(3) AND NOT ([ANL_CAT_LEVEL3_SETUP]=[ANL_CAT_LEVEL2_SETUP] OR [ANL_CAT_LEVEL3_SETUP]=[ANL_CAT_LEVEL1_SETUP]) OR [ANL_CAT_LEVEL3_SETUP]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(3)) AND ([ANL_CAT_LEVEL4_SETUP]>=(1) AND [ANL_CAT_LEVEL4_SETUP]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(4) AND NOT ([ANL_CAT_LEVEL4_SETUP]=[ANL_CAT_LEVEL3_SETUP] OR [ANL_CAT_LEVEL4_SETUP]=[ANL_CAT_LEVEL2_SETUP] OR [ANL_CAT_LEVEL4_SETUP]=[ANL_CAT_LEVEL1_SETUP]) OR [ANL_CAT_LEVEL4_SETUP]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(4)) AND ([ANL_CAT_LEVEL5_SETUP]>=(1) AND [ANL_CAT_LEVEL5_SETUP]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(5) AND NOT ([ANL_CAT_LEVEL5_SETUP]=[ANL_CAT_LEVEL4_SETUP] OR [ANL_CAT_LEVEL5_SETUP]=[ANL_CAT_LEVEL3_SETUP] OR [ANL_CAT_LEVEL5_SETUP]=[ANL_CAT_LEVEL2_SETUP] OR [ANL_CAT_LEVEL5_SETUP]=[ANL_CAT_LEVEL1_SETUP]) OR [ANL_CAT_LEVEL5_SETUP]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(5)) AND ([ANL_CAT_LEVEL6_SETUP]>=(1) AND [ANL_CAT_LEVEL6_SETUP]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(6) AND NOT ([ANL_CAT_LEVEL6_SETUP]=[ANL_CAT_LEVEL5_SETUP] OR [ANL_CAT_LEVEL6_SETUP]=[ANL_CAT_LEVEL4_SETUP] OR [ANL_CAT_LEVEL6_SETUP]=[ANL_CAT_LEVEL3_SETUP] OR [ANL_CAT_LEVEL6_SETUP]=[ANL_CAT_LEVEL2_SETUP] OR [ANL_CAT_LEVEL6_SETUP]=[ANL_CAT_LEVEL1_SETUP]) OR [ANL_CAT_LEVEL6_SETUP]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(6)) AND ([ANL_CAT_LEVEL7_SETUP]>=(1) AND [ANL_CAT_LEVEL7_SETUP]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]>=(7) AND NOT ([ANL_CAT_LEVEL7_SETUP]=[ANL_CAT_LEVEL6_SETUP] OR [ANL_CAT_LEVEL7_SETUP]=[ANL_CAT_LEVEL5_SETUP] OR [ANL_CAT_LEVEL7_SETUP]=[ANL_CAT_LEVEL4_SETUP] OR [ANL_CAT_LEVEL7_SETUP]=[ANL_CAT_LEVEL3_SETUP] OR [ANL_CAT_LEVEL7_SETUP]=[ANL_CAT_LEVEL2_SETUP] OR [ANL_CAT_LEVEL7_SETUP]=[ANL_CAT_LEVEL1_SETUP]) OR [ANL_CAT_LEVEL7_SETUP]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(7)) AND ([ANL_CAT_LEVEL8_SETUP]>=(1) AND [ANL_CAT_LEVEL8_SETUP]<=(8) AND [ANL_NUMBER_OF_CAT_LEVELS]=(8) AND NOT ([ANL_CAT_LEVEL8_SETUP]=[ANL_CAT_LEVEL7_SETUP] OR [ANL_CAT_LEVEL8_SETUP]=[ANL_CAT_LEVEL6_SETUP] OR [ANL_CAT_LEVEL8_SETUP]=[ANL_CAT_LEVEL5_SETUP] OR [ANL_CAT_LEVEL8_SETUP]=[ANL_CAT_LEVEL4_SETUP] OR [ANL_CAT_LEVEL8_SETUP]=[ANL_CAT_LEVEL3_SETUP] OR [ANL_CAT_LEVEL8_SETUP]=[ANL_CAT_LEVEL2_SETUP] OR [ANL_CAT_LEVEL8_SETUP]=[ANL_CAT_LEVEL1_SETUP]) OR [ANL_CAT_LEVEL8_SETUP]=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<(8))),
    CONSTRAINT [ANL_CAT_LEVEL_TOTAL_LENGTH_CK] CHECK (((((((((len([ANL_NOM_SEPARATOR])*([ANL_NUMBER_OF_CAT_LEVELS]-(1))+[ANL_CAT_LEVEL1_LENGTH])+[ANL_CAT_LEVEL2_LENGTH])+[ANL_CAT_LEVEL3_LENGTH])+[ANL_CAT_LEVEL4_LENGTH])+[ANL_CAT_LEVEL5_LENGTH])+[ANL_CAT_LEVEL6_LENGTH])+[ANL_CAT_LEVEL7_LENGTH])+[ANL_CAT_LEVEL8_LENGTH])<=(22)),
    CONSTRAINT [ANL_NOM_SEPARATOR_CK] CHECK (isnull([ANL_NOM_SEPARATOR],'')='' OR isnull([ANL_NOM_SEPARATOR],'')='#' OR isnull([ANL_NOM_SEPARATOR],'')='-' OR isnull([ANL_NOM_SEPARATOR],'')='/'),
    CONSTRAINT [ANL_NUMBER_OF_CAT_LEVELS_CK] CHECK ([ANL_NUMBER_OF_CAT_LEVELS]>=(0) AND [ANL_NUMBER_OF_CAT_LEVELS]<=(8))
);


GO
CREATE TRIGGER [dbo].[aa_datainfo_dt]
    ON [dbo].[SYS_DATAINFO]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

