CREATE TABLE [dbo].[SYS_RESOURCE_RATES_TEMP] (
    [RT_GUID]           UNIQUEIDENTIFIER NOT NULL,
    [RT_SEQUENCE]       BIGINT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RT_STATUS]         TINYINT          NULL,
    [RT_RATE_NUMBER]    INT              NOT NULL,
    [RT_DESCRIPTION]    VARCHAR (40)     NULL,
    [RT_IN_USE]         BIT              NULL,
    [RT_DEFAULT_STRING] VARCHAR (20)     NULL,
    CONSTRAINT [RT_RESOURCE_RATE_PK] PRIMARY KEY CLUSTERED ([RT_GUID] ASC, [RT_SEQUENCE] ASC)
);

