CREATE TABLE [dbo].[SYS_TAXBOX_DETAIL] (
    [TB_TAXBOX_CODE] VARCHAR (4)  NULL,
    [TB_VALUE]       FLOAT (53)   DEFAULT ((0)) NULL,
    [TB_YEAR]        VARCHAR (1)  NULL,
    [TB_PERIOD]      TINYINT      DEFAULT ((0)) NULL,
    [TB_SUB_LEDGER]  VARCHAR (10) NULL,
    [TB_TRANTYPE]    VARCHAR (5)  NULL,
    [TB_HEADER_REF]  VARCHAR (10) NULL,
    [TB_DATE]        DATETIME     NULL,
    [TB_ACCOUNT]     VARCHAR (25) NULL,
    [TB_NET]         FLOAT (53)   DEFAULT ((0)) NULL,
    [TB_VAT]         FLOAT (53)   DEFAULT ((0)) NULL,
    [TB_NET_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [TB_TAX_C]       FLOAT (53)   DEFAULT ((0)) NULL,
    [TB_HEADER_KEY]  VARCHAR (20) NULL,
    [TB_PRIMARY]     FLOAT (53)   NOT NULL,
    CONSTRAINT [TB_PRIMARY_PK] PRIMARY KEY CLUSTERED ([TB_PRIMARY] ASC)
);

