CREATE TABLE [dbo].[SYS_DOCUMENT_LAYOUTS] (
    [SDL_PRIMARY]  INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SDL_DOC_TYPE] VARCHAR (3)   NOT NULL,
    [SDL_OMNIS]    BIT           DEFAULT ((0)) NOT NULL,
    [SDL_DOC_NAME] VARCHAR (255) NOT NULL,
    CONSTRAINT [SDL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SDL_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

