CREATE TABLE [dbo].[SYS_RECORD_LIST_SEARCH_CRITERIA] (
    [SRLSC_PRIMARY]     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SRLSC_SEARCH_LINK] INT           NOT NULL,
    [SRLSC_FIELD_NAME]  VARCHAR (64)  NOT NULL,
    [SRLSC_SEARCH_TYPE] CHAR (1)      DEFAULT ('E') NOT NULL,
    [SRLSC_FROM_VALUE]  VARCHAR (256) NULL,
    [SRLSC_TO_VALUE]    VARCHAR (256) NULL,
    CONSTRAINT [SRLSC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SRLSC_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [SRLSC_FIELD_NAME_CK] CHECK ([SRLSC_FIELD_NAME]<>''),
    CONSTRAINT [SRLSC_SEARCH_TYPE_CK] CHECK (upper([SRLSC_SEARCH_TYPE])='X' OR upper([SRLSC_SEARCH_TYPE])='N' OR upper([SRLSC_SEARCH_TYPE])='E' OR upper([SRLSC_SEARCH_TYPE])='C' OR upper([SRLSC_SEARCH_TYPE])='B' OR upper([SRLSC_SEARCH_TYPE])='R'),
    CONSTRAINT [SRLSC_SEARCH_LINK_FK] FOREIGN KEY ([SRLSC_SEARCH_LINK]) REFERENCES [dbo].[SYS_RECORD_LIST_SEARCHES] ([SRLS_PRIMARY]) ON DELETE CASCADE ON UPDATE CASCADE
);

