CREATE TABLE [dbo].[SYS_WINDOW_LAYOUTS] (
    [WL_PRIMARY]     INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WL_LAYOUT_NAME] NVARCHAR (255) NOT NULL,
    [WL_ENTERED_BY]  VARCHAR (4)    NOT NULL,
    [WL_DATE_PUTIN]  DATETIME       NULL,
    [WL_DATE_EDITED] DATETIME       NULL,
    CONSTRAINT [WL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([WL_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WL_LAYOUT_NAME]
    ON [dbo].[SYS_WINDOW_LAYOUTS]([WL_LAYOUT_NAME] ASC, [WL_ENTERED_BY] ASC);

