CREATE TABLE [dbo].[SYS_SMTP_SERVERS] (
    [SMTP_SRVR_PRIMARY]      INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SMTP_SRVR_NAME]         VARCHAR (128) NOT NULL,
    [SMTP_SRVR_HOST_ADDRESS] VARCHAR (128) NOT NULL,
    [SMTP_SRVR_PORT]         SMALLINT      NOT NULL,
    [SMTP_SRVR_USE_SSL]      BIT           DEFAULT ((0)) NOT NULL,
    [SMTP_SRVR_TIMEOUT]      INT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SMTP_SRVR_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SMTP_SRVR_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SMTP_SRVR_NAME]
    ON [dbo].[SYS_SMTP_SERVERS]([SMTP_SRVR_NAME] ASC) WITH (FILLFACTOR = 70);

