CREATE TABLE [dbo].[SYS_DATAINFO3] (
    [SYS_PRIMARY_3]                      FLOAT (53)    NOT NULL,
    [SYS_CHAR1]                          VARCHAR (20)  NULL,
    [SYS_CHAR2]                          VARCHAR (20)  NULL,
    [SYS_CHAR3]                          VARCHAR (100) NULL,
    [SYS_CHAR4]                          VARCHAR (100) NULL,
    [SYS_FLAG1]                          TINYINT       DEFAULT ((0)) NULL,
    [SYS_FLAG2]                          TINYINT       DEFAULT ((0)) NULL,
    [SYS_DATE1]                          DATETIME      NULL,
    [SYS_DATE2]                          DATETIME      NULL,
    [SYS_NUM1]                           FLOAT (53)    DEFAULT ((0)) NULL,
    [SYS_NUM2]                           FLOAT (53)    DEFAULT ((0)) NULL,
    [SYS_USRCHAR1]                       VARCHAR (20)  NULL,
    [SYS_USRCHAR2]                       VARCHAR (20)  NULL,
    [SYS_USRCHAR3]                       VARCHAR (100) NULL,
    [SYS_USRCHAR4]                       VARCHAR (100) NULL,
    [SYS_USRFLAG1]                       TINYINT       DEFAULT ((0)) NULL,
    [SYS_USRFLAG2]                       TINYINT       DEFAULT ((0)) NULL,
    [SYS_USRDATE1]                       DATETIME      NULL,
    [SYS_USRDATE2]                       DATETIME      NULL,
    [SYS_USRNUM1]                        FLOAT (53)    DEFAULT ((0)) NULL,
    [SYS_USRNUM2]                        FLOAT (53)    DEFAULT ((0)) NULL,
    [NL_AUTO_ANALYSIS_CREATION]          TINYINT       DEFAULT ((0)) NULL,
    [DEFAULT_HELP_PATH]                  VARCHAR (255) NULL,
    [REMOTE_HELP_PATH]                   VARCHAR (255) NULL,
    [REMITTANCE_STATIONERY_LINK]         INT           DEFAULT ((0)) NULL,
    [CHEQUE_STATIONERY_LINK]             INT           DEFAULT ((0)) NULL,
    [BACS_STATIONERY_LINK]               INT           DEFAULT ((0)) NULL,
    [SMTP_USERNAME]                      VARCHAR (128) NULL,
    [SMTP_PASSWORD]                      VARCHAR (128) NULL,
    [SMTP_SERVER]                        VARCHAR (128) NULL,
    [SMTP_EMAIL_DISPLAY_NAME]            VARCHAR (128) NULL,
    [PL_STATEMENT_STATIONERY_LINK]       INT           DEFAULT ((0)) NULL,
    [SL_STATEMENT_STATIONERY_LINK]       INT           DEFAULT ((0)) NULL,
    [BULK_RECEIPTS_STATIONERY_LINK]      INT           DEFAULT ((0)) NULL,
    [SL_ALLOC_STATEMENT_STATIONERY_LINK] INT           DEFAULT ((0)) NULL,
    [PL_ALLOC_STATEMENT_STATIONERY_LINK] INT           DEFAULT ((0)) NULL,
    [SMTP_AUTHENTICATION_TYPE]           TINYINT       DEFAULT ((0)) NULL,
    [CST_WIP_UPD_TO_NOMINAL]             TINYINT       DEFAULT ((0)) NOT NULL,
    [CST_MAIN_TIMESHEET_RATE_TYPE]       VARCHAR (1)   DEFAULT ('R') NOT NULL,
    [CST_INVOICEABLE_VALUE_CALC_OPT]     TINYINT       DEFAULT ((0)) NOT NULL,
    [CST_WORKING_HOURS_IN_DAY]           FLOAT (53)    DEFAULT ((7.5)) NOT NULL,
    [CST_WORKING_DAYS_IN_WEEK]           FLOAT (53)    DEFAULT ((5)) NOT NULL,
    [CST_ANALYSE_BY]                     TINYINT       DEFAULT ((1)) NOT NULL,
    [CST_COSTING_YEAR]                   TINYINT       DEFAULT ((0)) NOT NULL,
    [CST_INIT_CREATE_CENTRES]            TINYINT       DEFAULT ((0)) NOT NULL,
    [CST_MARKUP_TYPE]                    TINYINT       DEFAULT ((0)) NOT NULL,
    [NL_CATEGORY_DISPLAY_STYLE]          TINYINT       DEFAULT ((0)) NOT NULL,
    [ALLOW_AUTO_CUSTOMER_TASK]           BIT           DEFAULT ((1)) NOT NULL,
    [MAX_ATTACHMENT_FILESIZE]            INT           DEFAULT ((1000)) NOT NULL,
    [CST_SALES_SL_ANALYSIS_LINK]         INT           NULL,
    [CST_WIP_SL_ANALYSIS_LINK]           INT           NULL,
    [CST_COST_PL_ANALYSIS_LINK]          INT           NULL,
    [CST_INCOME_SL_ANALYSIS_LINK]        INT           NULL,
    CONSTRAINT [SYS_PRIMARY_3_PK] PRIMARY KEY CLUSTERED ([SYS_PRIMARY_3] ASC)
);

