CREATE TABLE [dbo].[SYS_USER_TRAN_OPTS] (
    [UT_USER_ID]       VARCHAR (4)  NOT NULL,
    [UT_USER_PROFILE]  VARCHAR (10) NULL,
    [UT_MODULE]        VARCHAR (3)  NOT NULL,
    [UT_TRAN_TYPE]     TINYINT      NOT NULL,
    [UT_TRAN_OPTION]   TINYINT      NOT NULL,
    [UT_OPTION_VALUE]  TINYINT      DEFAULT ((0)) NULL,
    [UT_SESSION_VALUE] TINYINT      NULL,
    CONSTRAINT [SYS_USER_TRAN_OPTS_PK] PRIMARY KEY CLUSTERED ([UT_USER_ID] ASC, [UT_MODULE] ASC, [UT_TRAN_TYPE] ASC, [UT_TRAN_OPTION] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UT_USER_PROFILE]
    ON [dbo].[SYS_USER_TRAN_OPTS]([UT_USER_PROFILE] ASC);

