CREATE TABLE [dbo].[SYS_SQL_ERROR_MESSAGE_DATATYPES] (
    [ERROR_ID]         VARCHAR (10) NOT NULL,
    [PARAM_DATA_TYPE0] VARCHAR (10) NULL,
    [PARAM_DATA_TYPE1] VARCHAR (10) NULL,
    [PARAM_DATA_TYPE2] VARCHAR (10) NULL,
    [PARAM_DATA_TYPE3] VARCHAR (10) NULL,
    [PARAM_DATA_TYPE4] VARCHAR (10) NULL,
    CONSTRAINT [PK_SYS_SQL_ERROR_MESSAGE_DATATYPES] PRIMARY KEY CLUSTERED ([ERROR_ID] ASC)
);

