CREATE TABLE [dbo].[SYS_RESOURCE_RATES] (
    [R_RATE_NUMBER] INT          NOT NULL,
    [R_DESCRIPTION] VARCHAR (40) NULL,
    [R_IN_USE]      BIT          NULL,
    CONSTRAINT [R_PRIMARY_PK] PRIMARY KEY CLUSTERED ([R_RATE_NUMBER] ASC)
);

