CREATE TABLE [dbo].[SYS_DEFAULT_RECORD_TEMPLATE] (
    [USER_ID]     VARCHAR (4) NOT NULL,
    [RECORD_ID]   INT         NOT NULL,
    [TEMPLATE_ID] INT         NOT NULL,
    CONSTRAINT [PK_DEFAULT_RECORD_TEMPLATE] PRIMARY KEY CLUSTERED ([RECORD_ID] ASC, [USER_ID] ASC)
);

