CREATE TABLE [dbo].[SYS_LANGUAGE_LABEL_TEXT_LINK] (
    [LANGUAGE_LINK_PRIMARY] INT      IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [LANGUAGE_LABEL_FK]     INT      NOT NULL,
    [LANGUAGE_FK]           INT      NOT NULL,
    [LANGUAGE_TEXT_FK]      INT      NOT NULL,
    [MODIFIED_DATE]         DATETIME NULL,
    CONSTRAINT [LANGUAGE_LINK_PRIMARY_PK] PRIMARY KEY CLUSTERED ([LANGUAGE_LINK_PRIMARY] ASC),
    CONSTRAINT [SYS_LANGUAGE_LABEL_TEXT_LINK_FK] FOREIGN KEY ([LANGUAGE_FK]) REFERENCES [dbo].[SYS_LANGUAGES] ([LANGUAGE_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [SYS_LANGUAGE_LABEL_TEXT_LINK_FK2] FOREIGN KEY ([LANGUAGE_LABEL_FK]) REFERENCES [dbo].[SYS_LANGUAGE_LABELS] ([LANGUAGE_LABEL_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [SYS_LANGUAGE_LABEL_TEXT_LINK_FK3] FOREIGN KEY ([LANGUAGE_TEXT_FK]) REFERENCES [dbo].[SYS_LANGUAGE_LABEL_TEXT] ([LANGUAGE_LABEL_TEXT_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SYS_LANGUAGE_LABEL_TEXT_UC]
    ON [dbo].[SYS_LANGUAGE_LABEL_TEXT_LINK]([LANGUAGE_FK] ASC, [LANGUAGE_LABEL_FK] ASC, [LANGUAGE_TEXT_FK] ASC);

