CREATE TABLE [dbo].[SYS_TAX_BOX] (
    [TAXBOX_CODE]        VARCHAR (4)  NOT NULL,
    [TAXBOX_NAME]        VARCHAR (40) NULL,
    [TAXBOX_CARRIEDFWD]  FLOAT (53)   DEFAULT ((0)) NULL,
    [TAXBOX_MANUAL_EDIT] TINYINT      DEFAULT ((0)) NULL,
    [TAXBOX_SYSTEM]      TINYINT      DEFAULT ((0)) NULL,
    CONSTRAINT [TAXBOX_CODE_PK] PRIMARY KEY CLUSTERED ([TAXBOX_CODE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [TAXBOX_CODE]
    ON [dbo].[SYS_TAX_BOX]([TAXBOX_CODE] ASC);

