CREATE TABLE [dbo].[SYS_USER_PROFILE_REPORT_TEMP] (
    [UPRT_GUID]         UNIQUEIDENTIFIER NOT NULL,
    [UPRT_SEQUENCE]     BIGINT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [UPRT_PROFILE_LINK] VARCHAR (10)     NOT NULL,
    [UPRT_REPORT_LINK]  BIGINT           NOT NULL,
    [UPRT_DELETE]       TINYINT          DEFAULT ((0)) NULL,
    CONSTRAINT [SYS_USER_PROFILE_REPORT_TEMP_PK] PRIMARY KEY CLUSTERED ([UPRT_GUID] ASC, [UPRT_SEQUENCE] ASC)
);

