CREATE TABLE [dbo].[SYS_USER_PROFILE_REPORTS] (
    [UPR_PROFILE_LINK] VARCHAR (10) NOT NULL,
    [UPR_REPORT_LINK]  BIGINT       NOT NULL,
    CONSTRAINT [UPR_PROFILE_LINK_PK] PRIMARY KEY CLUSTERED ([UPR_PROFILE_LINK] ASC, [UPR_REPORT_LINK] ASC),
    CONSTRAINT [SYS_USER_PROFILE_REPORTS_PROFILE_LINK_FK] FOREIGN KEY ([UPR_PROFILE_LINK]) REFERENCES [dbo].[SYS_USER_PROFILE_GLOBAL] ([UPG_CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

