CREATE TABLE [dbo].[SYS_FAX_TEMPLATE] (
    [SFT_PRIMARY]         INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SFT_SFS_LINK]        FLOAT (53) DEFAULT ((0)) NULL,
    [SFT_SFL_LINK]        FLOAT (53) DEFAULT ((0)) NULL,
    [SFT_TEMPLATE1]       TEXT       NULL,
    [SFT_TEMPLATE2]       TEXT       NULL,
    [SFT_COMMAND_ORDER]   TINYINT    DEFAULT ((0)) NOT NULL,
    [SFT_REPORT_POSITION] TINYINT    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SFT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SFT_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SFT_SFS_LINK]
    ON [dbo].[SYS_FAX_TEMPLATE]([SFT_SFS_LINK] ASC, [SFT_REPORT_POSITION] ASC, [SFT_COMMAND_ORDER] ASC);

