CREATE TABLE [dbo].[SYS_LANGUAGES] (
    [LANGUAGE_PRIMARY]      INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [LANGUAGE_CODE]         NVARCHAR (10) NOT NULL,
    [DESCRIPTION]           NVARCHAR (40) NULL,
    [CREATED_DATE]          DATETIME      DEFAULT (getdate()) NOT NULL,
    [MODIFIED_DATE]         DATETIME      NULL,
    [MODIFIED_BY]           NVARCHAR (4)  NULL,
    [CREATED_BY]            NVARCHAR (4)  NOT NULL,
    [LABEL_MODIFIED_DATE]   DATETIME      NULL,
    [MESSAGE_MODIFIED_DATE] DATETIME      NULL,
    [SYSTEM_DEFAULT]        BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [LANGUAGE_PRIMARY_PK] PRIMARY KEY CLUSTERED ([LANGUAGE_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [LANGUAGE_CODE]
    ON [dbo].[SYS_LANGUAGES]([LANGUAGE_CODE] ASC);


GO
CREATE TRIGGER [dbo].[AA_SYS_LANGUAGES_DT]
    ON [dbo].[SYS_LANGUAGES]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

