CREATE TABLE [dbo].[SYS_LOOKUP] (
    [LOOKUP_CODE]   VARCHAR (10)  NULL,
    [LOOKUP_VALUE1] VARCHAR (5)   NULL,
    [LOOKUP_VALUE2] VARCHAR (5)   NULL,
    [LOOK_PRIMARY]  FLOAT (53)    NOT NULL,
    [PRINT_COUNTER] FLOAT (53)    DEFAULT ((0)) NULL,
    [PRINT_FLAG1]   TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG2]   TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG3]   TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG4]   TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG5]   TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG6]   TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG7]   TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG8]   TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG9]   TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG10]  TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG11]  TINYINT       DEFAULT ((0)) NULL,
    [PRINT_FLAG12]  TINYINT       DEFAULT ((0)) NULL,
    [PRINT_PATH]    VARCHAR (240) NULL,
    [BACS_FLAG1]    TINYINT       DEFAULT ((0)) NULL,
    CONSTRAINT [LOOK_PRIMARY_PK] PRIMARY KEY CLUSTERED ([LOOK_PRIMARY] ASC)
);

