CREATE TABLE [dbo].[SYS_CO2_OPTIONS] (
    [CO2_OPT_PRIMARY]            INT     NOT NULL,
    [CO2_OPT_1ST_CATEGORY_GROUP] TINYINT NOT NULL,
    [CO2_OPT_2ND_CATEGORY_GROUP] TINYINT NOT NULL,
    CONSTRAINT [CO2_OPT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CO2_OPT_PRIMARY] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [CO2_OPT_1ST_CATEGORY_GROUP_CK] CHECK ([CO2_OPT_1ST_CATEGORY_GROUP]>=(0) AND [CO2_OPT_1ST_CATEGORY_GROUP]<=(8)),
    CONSTRAINT [CO2_OPT_2ND_CATEGORY_GROUP_CK] CHECK ([CO2_OPT_2ND_CATEGORY_GROUP]>=(0) AND [CO2_OPT_2ND_CATEGORY_GROUP]<=(8)),
    CONSTRAINT [CO2_OPT_CATEGORY_GROUPS_CK] CHECK ([CO2_OPT_1ST_CATEGORY_GROUP]=(0) AND [CO2_OPT_2ND_CATEGORY_GROUP]=(0) OR [CO2_OPT_1ST_CATEGORY_GROUP]<>[CO2_OPT_2ND_CATEGORY_GROUP]),
    CONSTRAINT [CO2_OPT_PRIMARY_CK] CHECK ([CO2_OPT_PRIMARY]=(1))
);

