CREATE TABLE [dbo].[SYS_REPORT_USER_FAVOURITES] (
    [USER_ID]   VARCHAR (4) NOT NULL,
    [REPORT_ID] BIGINT      NOT NULL,
    CONSTRAINT [USER_ID_REPORT_ID_PK] PRIMARY KEY CLUSTERED ([USER_ID] ASC, [REPORT_ID] ASC),
    CONSTRAINT [SYS_REPORT_USER_FAVOURITES_FK] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[SYS_USER] ([USER_ID]) ON DELETE CASCADE
);

