CREATE TABLE [dbo].[SYS_DATAINFO2] (
    [FIELD1]                           VARCHAR (1)   NULL,
    [POP_SWTCH_DEF]                    TINYINT       DEFAULT ((0)) NULL,
    [LOG_IN_USE]                       TINYINT       DEFAULT ((0)) NULL,
    [LOG_RECORD_UPDATE]                VARCHAR (30)  NULL,
    [PERIODEND_FORCE_WIP]              TINYINT       DEFAULT ((0)) NULL,
    [ALLOW_BUDGET_PROFILE]             TINYINT       DEFAULT ((0)) NULL,
    [NLB_MU_STATUS]                    VARCHAR (1)   NULL,
    [LOG_REPORT_PRINT]                 VARCHAR (30)  NULL,
    [LOG_LETTER_PRINT]                 TINYINT       DEFAULT ((0)) NULL,
    [COMP_USERFIELD1]                  VARCHAR (20)  NULL,
    [COMP_USERFIELD2]                  VARCHAR (20)  NULL,
    [COMP_USERFIELD3]                  VARCHAR (20)  NULL,
    [COMP_USRCHAR1]                    VARCHAR (20)  NULL,
    [COMP_USRCHAR2]                    VARCHAR (20)  NULL,
    [COMP_USRCHAR3]                    VARCHAR (20)  NULL,
    [COMP_USRCHAR4]                    VARCHAR (30)  NULL,
    [COMP_USRCHAR5]                    VARCHAR (30)  NULL,
    [COMP_USRCHAR6]                    VARCHAR (30)  NULL,
    [COMP_USRDATE1]                    DATETIME      NULL,
    [COMP_USRDATE2]                    DATETIME      NULL,
    [COMP_USRDATE3]                    DATETIME      NULL,
    [COMP_USRFLAG1]                    TINYINT       DEFAULT ((0)) NULL,
    [COMP_USRFLAG2]                    TINYINT       DEFAULT ((0)) NULL,
    [COMP_USRFLAG3]                    TINYINT       DEFAULT ((0)) NULL,
    [COMP_USRNUM1]                     FLOAT (53)    DEFAULT ((0)) NULL,
    [COMP_USRNUM2]                     FLOAT (53)    DEFAULT ((0)) NULL,
    [COMP_USRNUM3]                     FLOAT (53)    DEFAULT ((0)) NULL,
    [WO_ISSUE_ANALYSIS]                VARCHAR (25)  NULL,
    [WO_WRITE_OFF_MAT_ANALYSIS]        VARCHAR (25)  NULL,
    [WO_SCRAP_ANALYSIS]                VARCHAR (25)  NULL,
    [WO_FINISHED_ANALYSIS]             VARCHAR (25)  NULL,
    [WO_COMP_ISSUE_ANALYSIS]           VARCHAR (25)  NULL,
    [WO_COMP_WRITE_OFF_ANALYSIS]       VARCHAR (25)  NULL,
    [WO_ISSUE_COST_METHOD]             VARCHAR (1)   NULL,
    [CST_OBUDG_REV1_ONLY]              TINYINT       DEFAULT ((0)) NULL,
    [CST_PAY_ANALYSE]                  TINYINT       DEFAULT ((0)) NULL,
    [CST_PAY_USERATE]                  TINYINT       DEFAULT ((0)) NULL,
    [CST_PAY_MAKERSC]                  TINYINT       DEFAULT ((0)) NULL,
    [CST_HIDE_WEEK]                    TINYINT       DEFAULT ((0)) NULL,
    [STK_ASM_MOVES]                    TINYINT       DEFAULT ((0)) NULL,
    [STK_ASM_STNDRD]                   TINYINT       DEFAULT ((0)) NULL,
    [STK_PRN_MOVEDOC]                  TINYINT       DEFAULT ((0)) NULL,
    [PL_REMIT_STNRY]                   TINYINT       DEFAULT ((0)) NULL,
    [LINES_PER_PAGE]                   TINYINT       DEFAULT ((0)) NULL,
    [FILE_USED_DATE]                   DATETIME      NULL,
    [TERMS_OPTION]                     TINYINT       DEFAULT ((0)) NULL,
    [SOP_ORDER_LOCK]                   TINYINT       DEFAULT ((0)) NULL,
    [FORCE_SOPBATREF]                  TINYINT       DEFAULT ((0)) NULL,
    [FORCE_SOPDATE]                    TINYINT       DEFAULT ((0)) NULL,
    [FORCE_SOPREQDTE]                  TINYINT       DEFAULT ((0)) NULL,
    [FORCE_SOPCUSREF]                  TINYINT       DEFAULT ((0)) NULL,
    [FORCE_SOPDESC]                    TINYINT       DEFAULT ((0)) NULL,
    [FORCE_SOPUSRKEY1]                 TINYINT       DEFAULT ((0)) NULL,
    [FORCE_SOPUSRKEY2]                 TINYINT       DEFAULT ((0)) NULL,
    [FORCE_SOPUSRKEY3]                 TINYINT       DEFAULT ((0)) NULL,
    [SOP_PRINT_CONFM]                  TINYINT       DEFAULT ((0)) NULL,
    [SOP_BTCHREF_KEY]                  TINYINT       DEFAULT ((0)) NULL,
    [SOP_EMPTY_LOC]                    TINYINT       DEFAULT ((0)) NULL,
    [SOP_EMPTY_STK]                    TINYINT       DEFAULT ((0)) NULL,
    [ORD_USE_STKPRC]                   TINYINT       DEFAULT ((0)) NULL,
    [RESERVED_CH]                      VARCHAR (1)   NULL,
    [ACD_DOCUMENT_MASK]                VARCHAR (100) NULL,
    [MAIL_ORDER_ON]                    TINYINT       DEFAULT ((0)) NULL,
    [USE_ENHANCED_ENTRY]               TINYINT       DEFAULT ((0)) NULL,
    [STK_FREE_METHOD]                  VARCHAR (1)   NULL,
    [UPDATE_STOCK_TO_NOMINAL]          TINYINT       DEFAULT ((0)) NULL,
    [DEFAULT_STK_MOVE_IN_ANALYSIS]     VARCHAR (25)  NULL,
    [DEFAULT_STK_MOVE_OUT_ANALYSIS]    VARCHAR (25)  NULL,
    [DEFAULT_STK_SOP_ANALYSIS]         VARCHAR (25)  NULL,
    [DEFAULT_STK_POP_ANALYSIS]         VARCHAR (25)  NULL,
    [ASSEMBLY_NON_STOCK_COSTS_NOMINAL] VARCHAR (25)  NULL,
    [LEAVE_BATCH_REFERENCE_EMPTY]      TINYINT       DEFAULT ((0)) NULL,
    [NO_OF_PERIODS]                    INT           DEFAULT ((0)) NULL,
    [CIS_TAX_ANALYSIS]                 VARCHAR (25)  NULL,
    [CIS_CITB_ANALYSIS]                VARCHAR (25)  NULL,
    [CIS_EMPLOYER_REF]                 VARCHAR (14)  NULL,
    [CIS_CONTRACTORS_UTR]              VARCHAR (10)  NULL,
    [CIS_ACCOUNTS_OFFICE_REF]          VARCHAR (13)  NULL,
    [CIS_INVOICE_AUTH_REQD]            TINYINT       DEFAULT ((0)) NULL,
    [CIS_SUBMISSION_METHOD]            TINYINT       DEFAULT ((0)) NULL,
    [CIS_USER_NAME]                    VARCHAR (20)  NULL,
    [CIS_PASSWORD]                     VARCHAR (20)  NULL,
    [CIS_XML_SERVICE]                  TINYINT       DEFAULT ((0)) NULL,
    [DEFAULT_BAD_DEBT_ANALYSIS]        VARCHAR (25)  NULL,
    [OVERDUE_DAYS]                     INT           NULL,
    [ENDDATE_P1]                       DATETIME      NULL,
    [ENDDATE_P2]                       DATETIME      NULL,
    [ENDDATE_P3]                       DATETIME      NULL,
    [ENDDATE_P4]                       DATETIME      NULL,
    [ENDDATE_P5]                       DATETIME      NULL,
    [ENDDATE_P6]                       DATETIME      NULL,
    [ENDDATE_P7]                       DATETIME      NULL,
    [ENDDATE_P8]                       DATETIME      NULL,
    [ENDDATE_P9]                       DATETIME      NULL,
    [ENDDATE_P10]                      DATETIME      NULL,
    [ENDDATE_P11]                      DATETIME      NULL,
    [ENDDATE_P12]                      DATETIME      NULL,
    [ENDDATE_P13]                      DATETIME      NULL,
    [ENDDATE_YR]                       VARCHAR (7)   NULL,
    [DATE_FORMAT]                      TINYINT       DEFAULT ((0)) NULL,
    [DATE_SENSITIVE_CURR]              TINYINT       DEFAULT ((0)) NULL,
    [SYS_DEFAULT_MENU_STYLE]           TINYINT       DEFAULT ((0)) NULL,
    [SYS_EDI_TIMER]                    FLOAT (53)    DEFAULT ((0)) NULL,
    [SYS_EDI_OPTION]                   TINYINT       DEFAULT ((0)) NULL,
    [SYS_EDI_LOCATION]                 VARCHAR (14)  NULL,
    [SYS_EDI_TYPE]                     FLOAT (53)    DEFAULT ((0)) NULL,
    [SYS_EDI_COMPANYID]                VARCHAR (13)  NULL,
    [SYS_EDI_INV_FLVGN]                FLOAT (53)    DEFAULT ((0)) NULL,
    [SYS_EDI_ORD_FLVGN]                FLOAT (53)    DEFAULT ((0)) NULL,
    [SYS_PRIMARY_2]                    FLOAT (53)    NOT NULL,
    [SYS_CB_TYPEFROMSIGN]              TINYINT       DEFAULT ((0)) NULL,
    [SYS_CB_NOSUBLEDGER]               TINYINT       DEFAULT ((0)) NULL,
    [SYS_NL_NUMERIC_ONLY]              TINYINT       DEFAULT ((0)) NULL,
    [SYS_NL_MIN_LENGTH]                TINYINT       DEFAULT ((0)) NULL,
    [ACCOUNTS_VERSION]                 VARCHAR (15)  NULL,
    [MARGIN_IN_CMS]                    TINYINT       DEFAULT ((0)) NULL,
    [CHQ_LEFT_MARGIN]                  FLOAT (53)    DEFAULT ((0)) NULL,
    [CHQ_TOP_MARGIN]                   FLOAT (53)    DEFAULT ((0)) NULL,
    [FAX_LEFT_MARGIN]                  FLOAT (53)    DEFAULT ((0)) NULL,
    [NL_FIX_LENGTH]                    TINYINT       DEFAULT ((0)) NULL,
    [COMPANY_TAX_SYSTEM]               VARCHAR (6)   NULL,
    [SYS_FORCE_SUBLEDGER]              TINYINT       DEFAULT ((0)) NULL,
    [SYS_VAT_ROUNDING]                 TINYINT       DEFAULT ((0)) NULL,
    [SYS_NOCHNG_SUBLREF]               TINYINT       DEFAULT ((0)) NULL,
    [SYS_FORCE_NAMEDESC]               TINYINT       DEFAULT ((0)) NULL,
    [SYS_NODEL_BATCHTRN]               TINYINT       DEFAULT ((0)) NULL,
    [SYS_ANYCURR_CONTROL]              TINYINT       DEFAULT ((0)) NULL,
    [COMP_ISDN_NUMBER]                 VARCHAR (20)  NULL,
    [COMP_WEBSITE_ADDRESS]             VARCHAR (100) NULL,
    [SYS_DECIMAL_CHARACTER]            VARCHAR (1)   NULL,
    [FAX_PAGESIZE]                     TINYINT       DEFAULT ((0)) NULL,
    [SYS_MESSAGE_SWITCH]               VARCHAR (10)  NULL,
    [SYS_SL_ANALYSIS_MATRIX]           TINYINT       DEFAULT ((0)) NULL,
    [SYS_PL_ANALYSIS_MATRIX]           TINYINT       DEFAULT ((0)) NULL,
    [MAX_DRILLDOWN_SIZE]               INT           DEFAULT ((0)) NULL,
    [SETT_DISCOUNT_VAT_CALC]           TINYINT       DEFAULT ((0)) NULL,
    [STK_LOC_SORT1_TYPE]               VARCHAR (1)   NULL,
    [STK_LOC_SORT2_TYPE]               VARCHAR (1)   NULL,
    [STK_LOC_SORT3_TYPE]               VARCHAR (1)   NULL,
    [STK_LOC_SORT4_TYPE]               VARCHAR (1)   NULL,
    [STK_LOC_SORT5_TYPE]               VARCHAR (1)   NULL,
    [STK_LOC_SORT6_TYPE]               VARCHAR (1)   NULL,
    [STK_LOC_SORT1_LENGTH]             TINYINT       DEFAULT ((0)) NULL,
    [STK_LOC_SORT2_LENGTH]             TINYINT       DEFAULT ((0)) NULL,
    [STK_LOC_SORT3_LENGTH]             TINYINT       DEFAULT ((0)) NULL,
    [STK_LOC_SORT4_LENGTH]             TINYINT       DEFAULT ((0)) NULL,
    [STK_LOC_SORT5_LENGTH]             TINYINT       DEFAULT ((0)) NULL,
    [STK_LOC_SORT6_LENGTH]             TINYINT       DEFAULT ((0)) NULL,
    [STK_LOC_CREATE_CODE_TYPE]         TINYINT       DEFAULT ((0)) NULL,
    [STK_SOP_COPY_DESC]                TINYINT       DEFAULT ((0)) NULL,
    [STK_POP_COPY_DESC]                TINYINT       DEFAULT ((0)) NULL,
    [PROFIT_COST_TYPE]                 VARCHAR (1)   NULL,
    [PL_PAYMENT_STAGES]                TINYINT       DEFAULT ((0)) NULL,
    [IR_GROSS_FIRST]                   TINYINT       DEFAULT ((0)) NULL,
    [NOM_BUDG_SUSPENSE]                VARCHAR (25)  NULL,
    [BUDGET_EXTENDED_CALC]             TINYINT       DEFAULT ((0)) NULL,
    [SOPSTATUS_CHECK]                  TINYINT       DEFAULT ((0)) NULL,
    [SYS_SM_DATASET]                   VARCHAR (20)  NULL,
    [RECALC_CURRENCY_ORDERS]           TINYINT       DEFAULT ((0)) NULL,
    [STK_DONOTCOPY_LOC1]               TINYINT       DEFAULT ((0)) NULL,
    [STK_DONOTCOPY_LOC2]               TINYINT       DEFAULT ((0)) NULL,
    [STK_DONOTCOPY_LOC3]               TINYINT       DEFAULT ((0)) NULL,
    [STK_DONOTCOPY_LOC4]               TINYINT       DEFAULT ((0)) NULL,
    [STK_DONOTCOPY_LOC5]               TINYINT       DEFAULT ((0)) NULL,
    [STK_DONOTCOPY_LOC6]               TINYINT       DEFAULT ((0)) NULL,
    [FORCE_DIMENSIONS]                 TINYINT       DEFAULT ((0)) NULL,
    [FORCE_COSTING]                    TINYINT       DEFAULT ((0)) NULL,
    [SYS_1000_CHARACTER]               VARCHAR (1)   NULL,
    [ST_AUTO_ALLOCATE]                 TINYINT       DEFAULT ((0)) NULL,
    [PT_AUTO_ALLOCATE]                 TINYINT       DEFAULT ((0)) NULL,
    [NOM_RND_DIF_BASE1]                VARCHAR (25)  NULL,
    [NOM_RND_DIF_BASE2]                VARCHAR (25)  NULL,
    [POST_RND_DIF_METHOD]              VARCHAR (1)   NULL,
    [BASE2_CURR_SYMBOL]                VARCHAR (4)   NULL,
    [HOME_EURO_CURRENCY]               TINYINT       DEFAULT ((0)) NULL,
    [TRI_VAL_ON_INVOICES]              VARCHAR (1)   NULL,
    [NL_USE_CAT_MH]                    TINYINT       DEFAULT ((0)) NULL,
    [ALLOC_VALID_PERIOD]               TINYINT       DEFAULT ((0)) NULL,
    [NL_USE_DRCR_TYPE]                 TINYINT       DEFAULT ((0)) NULL,
    [NL_USE_CAT1_LENGTH]               TINYINT       DEFAULT ((0)) NULL,
    [SYS_USE_MINUS_SIGN]               TINYINT       DEFAULT ((0)) NULL,
    [SYS_USE_INVERT_CURR]              TINYINT       DEFAULT ((0)) NULL,
    [SYS_NO_TAX_CALCS]                 TINYINT       DEFAULT ((0)) NULL,
    [COMPANY_ID]                       VARCHAR (40)  NULL,
    [COMPANY_NAME2]                    VARCHAR (40)  NULL,
    [COMPANY_ADDRESS2]                 VARCHAR (160) NULL,
    [NOM_TAX1]                         VARCHAR (25)  NULL,
    [NOM_TAX2]                         VARCHAR (25)  NULL,
    [SYS_HOME_NO_OF_DECIMAL]           TINYINT       DEFAULT ((0)) NULL,
    [SYS_CURR_ROUNDING]                TINYINT       DEFAULT ((0)) NULL,
    [NOM_EXDIFF]                       VARCHAR (25)  NULL,
    [NL_USE_EB_JOURNAL]                TINYINT       DEFAULT ((0)) NULL,
    [PL_USE_EB_BACS]                   TINYINT       DEFAULT ((0)) NULL,
    [PL_USE_EB_CBSTATMNT]              TINYINT       DEFAULT ((0)) NULL,
    [PL_EB_BACSDESC_KIND]              TINYINT       DEFAULT ((0)) NULL,
    [SYS_USE_SHOW_YEAR]                TINYINT       DEFAULT ((0)) NULL,
    [SYS_USE_EB_ADDRESS]               TINYINT       DEFAULT ((0)) NULL,
    [IR_CURRENCY_FIRST]                TINYINT       DEFAULT ((0)) NULL,
    [SYS_SP_VERSION]                   INT           DEFAULT ((0)) NULL,
    [SYS_SERVER_TYPE]                  VARCHAR (6)   NULL,
    [SERVICE_PACK_INUSE]               TINYINT       DEFAULT ((0)) NULL,
    [PATCH_VERSION]                    VARCHAR (2)   NULL,
    [IMPORTER_VERSION]                 VARCHAR (15)  NULL,
    [SOP_DELIVERY_PROFIT_COST]         TINYINT       DEFAULT ((0)) NULL,
    [SOP_OVERRIDE_DEFAULT_PRICELINE]   TINYINT       DEFAULT ((0)) NULL,
    [POP_OVERRIDE_DEFAULT_PRICELINE]   TINYINT       DEFAULT ((0)) NULL,
    [MASK_HISTORY]                     VARCHAR (100) NULL,
    [REPORT_CONTROL]                   VARCHAR (10)  NULL,
    [SYS_VERSION_DATA_CREATED]         VARCHAR (6)   NULL,
    [SYS_OLDVAT_UPDATE_DATE]           DATETIME      NULL,
    [AUTO_RECORD_LIST_ON_TRAN]         TINYINT       DEFAULT ((0)) NULL,
    [AUTO_RECORD_LIST_ON_REC]          TINYINT       DEFAULT ((0)) NULL,
    [AUTO_POPULATE_RECORD_LIST]        TINYINT       DEFAULT ((0)) NULL,
    [DOC_LEFT_MARGIN]                  FLOAT (53)    DEFAULT ((0)) NULL,
    [DOC_TOP_MARGIN]                   FLOAT (53)    DEFAULT ((0)) NULL,
    [LASER_CHEQUES]                    TINYINT       DEFAULT ((0)) NULL,
    [EXTERNALDOCS_PATH]                VARCHAR (255) NULL,
    [SYS_HARD_COPY_INV]                TINYINT       DEFAULT ((0)) NULL,
    [POP_AUTHORISATION]                TINYINT       DEFAULT ((0)) NULL,
    [USER_BUDGETS]                     TINYINT       DEFAULT ((0)) NULL,
    [NL_BUDGETS]                       TINYINT       DEFAULT ((0)) NULL,
    [USERBUDGETS_BATCH]                TINYINT       DEFAULT ((0)) NULL,
    [NLBUDGETS_BATCH]                  TINYINT       DEFAULT ((0)) NULL,
    [USERBUDGETS_PERIOD]               TINYINT       DEFAULT ((0)) NULL,
    [NLBUDGETS_PERIOD]                 TINYINT       DEFAULT ((0)) NULL,
    [AUTHORISE_ALL]                    TINYINT       DEFAULT ((0)) NULL,
    [PRINT_UNAUTHORISED_ORDERS]        TINYINT       DEFAULT ((0)) NULL,
    [DO_NOT_BUILD_ADDRESS_LIST]        TINYINT       DEFAULT ((0)) NULL,
    [SYS_FAX_DEFAULT_USE_DRIVER]       TINYINT       DEFAULT ((0)) NULL,
    [SYS_FAX_DEFAULT_PRINT_DRIVER]     VARCHAR (255) NULL,
    [SYS_FAX_DEFAULT_SOFTWARE_LINK]    INT           DEFAULT ((0)) NULL,
    [SYS_FAX_DEFAULT_COVER_PAGE]       VARCHAR (255) NULL,
    [USE_CHARACTER_MAPPING]            TINYINT       DEFAULT ((0)) NULL,
    [SYS_ALTERNATIVE_SOP_MSG]          TINYINT       DEFAULT ((0)) NULL,
    [AUTO_NUMBER_PROSPECT]             TINYINT       DEFAULT ((0)) NULL,
    [NEXT_PROSPECT_NUMBER]             FLOAT (53)    DEFAULT ((0)) NULL,
    [PROSPECT_SAME_SEQUENCE]           TINYINT       DEFAULT ((0)) NULL,
    [USE_PRINTER_ON_CRYSTAL_REPORT]    TINYINT       DEFAULT ((0)) NULL,
    [STK_FIRST_SERIAL_METHOD]          TINYINT       DEFAULT ((0)) NULL,
    [STK_DEFAULT_SERIAL_ENTRY_MODE]    VARCHAR (1)   NULL,
    [CREDIT_CHECK_WEBSITE]             TINYINT       DEFAULT ((0)) NULL,
    [STK_ASM_PROJCOST]                 TINYINT       DEFAULT ((0)) NULL,
    [SYS_BACKGROUND_COLOR]             INT           DEFAULT ((0)) NULL,
    [OLDEST_SUBANALYSIS_DATE_FIELD]    TINYINT       DEFAULT ((0)) NULL,
    [SOP_EXCLUDE_NON_SOP_SUB_QTY]      TINYINT       DEFAULT ((0)) NULL,
    [AUTO_CALC_DEMINIMUS_LIMIT]        TINYINT       DEFAULT ((0)) NULL,
    [CIS_USE_NEW_CITB_LEVY_CALCS]      BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SYS_PRIMARY_2_PK] PRIMARY KEY CLUSTERED ([SYS_PRIMARY_2] ASC)
);


GO
CREATE TRIGGER [dbo].[aa_datainfo2_dt]
    ON [dbo].[SYS_DATAINFO2]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

