CREATE TABLE [dbo].[SYS_TAX_RULES] (
    [TAXRULE_CODE]      VARCHAR (4)  NULL,
    [TAXRULE_TYPE]      VARCHAR (1)  NULL,
    [TAXRULE_PERCENT]   FLOAT (53)   DEFAULT ((0)) NULL,
    [TAXRULE_BOX]       VARCHAR (4)  NULL,
    [TAXRULE_NL_SIGN]   VARCHAR (1)  NULL,
    [TAXRULE_NL]        VARCHAR (25) NULL,
    [TAXRULE_RETURN_ID] VARCHAR (4)  NULL,
    [TAXRULE_PRIMARY]   FLOAT (53)   NOT NULL,
    [TAXRULE_BOX_SIGN]  VARCHAR (1)  NULL,
    CONSTRAINT [TAXRULE_PRIMARY_PK] PRIMARY KEY CLUSTERED ([TAXRULE_PRIMARY] ASC)
);

