CREATE TABLE [dbo].[SYS_DEL_HISTORY_DETAIL] (
    [DHD_PRODUCT_TYPE]      VARCHAR (1)   NULL,
    [DHD_ITEM_CODE]         VARCHAR (25)  NULL,
    [DHD_STOCK_DESCRIPTION] VARCHAR (80)  NULL,
    [DHD_SUPP_STOCK_CODE]   VARCHAR (25)  NULL,
    [DHD_DESCRIPTION]       VARCHAR (240) NULL,
    [DHD_QUANTITY]          FLOAT (53)    DEFAULT ((0)) NULL,
    [DHD_UNITCOST]          FLOAT (53)    DEFAULT ((0)) NULL,
    [DHD_UNITPRICE]         FLOAT (53)    DEFAULT ((0)) NULL,
    [DHD_UNITQUANTITY]      FLOAT (53)    DEFAULT ((0)) NULL,
    [DHD_UNITNAME]          VARCHAR (20)  NULL,
    [DHD_SUBANALYSIS]       VARCHAR (25)  NULL,
    [DHD_SM_AUDIT_NO]       INT           DEFAULT ((0)) NULL,
    [DHD_PRIMARY]           INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [DHD_HEADER_LINK]       INT           DEFAULT ((0)) NULL,
    [DHD_ORDERLINE_LINK]    INT           DEFAULT ((0)) NULL,
    [DHD_SERIAL_NUMBER]     VARCHAR (40)  NULL,
    [DHD_QTY_OUTSTANDING]   FLOAT (53)    DEFAULT ((0)) NULL,
    [DHD_DATE_REQUIRED]     DATETIME      NULL,
    CONSTRAINT [DHD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([DHD_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DHD_HEADER_LINK]
    ON [dbo].[SYS_DEL_HISTORY_DETAIL]([DHD_HEADER_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [DHD_ORDERLINE_LINK]
    ON [dbo].[SYS_DEL_HISTORY_DETAIL]([DHD_ORDERLINE_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SYS_DEL_HISTORY_DETAIL_DHD_SM_AUDIT_NO]
    ON [dbo].[SYS_DEL_HISTORY_DETAIL]([DHD_SM_AUDIT_NO] ASC);


GO
CREATE TRIGGER [dbo].[AA_DEL_HISTORY_DETAIL_DELETE_T]
    ON [dbo].[SYS_DEL_HISTORY_DETAIL]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

