CREATE TABLE [dbo].[SYS_FAX_LABELS] (
    [SFL_PRIMARY] INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SFL_LABEL]   VARCHAR (64) NULL,
    CONSTRAINT [SFL_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SFL_PRIMARY] ASC)
);

