CREATE TABLE [dbo].[SYS_LOOKUP_TEXT] (
    [TXT_ORIGIN]      VARCHAR (8)  NULL,
    [TXT_USER_TEXT]   VARCHAR (20) NULL,
    [TXT_SORT_ORDER]  INT          DEFAULT ((0)) NULL,
    [TXT_PRIMARY]     FLOAT (53)   NOT NULL,
    [TXT_TYPE]        TINYINT      DEFAULT ((0)) NULL,
    [TXT_LEVEL]       FLOAT (53)   DEFAULT ((0)) NULL,
    [TXT_USER_EDITED] VARCHAR (4)  NULL,
    [TXT_USER_PUTIN]  VARCHAR (4)  NULL,
    [TXT_DATE_EDITED] DATETIME     NULL,
    [TXT_DATE_PUTIN]  DATETIME     NULL,
    CONSTRAINT [TXT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([TXT_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [TXT_USER_TEXT]
    ON [dbo].[SYS_LOOKUP_TEXT]([TXT_ORIGIN] ASC, [TXT_USER_TEXT] ASC);


GO
CREATE TRIGGER [dbo].[aa_sop_headerstatus_dt]
    ON [dbo].[SYS_LOOKUP_TEXT]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

