CREATE TABLE [dbo].[SYS_WINDOW_LAYOUT_TEMP] (
    [WLT_GUID]      UNIQUEIDENTIFIER NOT NULL,
    [WLT_SEQUENCE]  BIGINT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WLT_FILE_NAME] NVARCHAR (255)   NOT NULL,
    [WLT_FILE]      IMAGE            NOT NULL,
    CONSTRAINT [SYS_WINDOW_LAYOUT_TEMP_PK] PRIMARY KEY CLUSTERED ([WLT_GUID] ASC, [WLT_SEQUENCE] ASC)
);

