CREATE TABLE [dbo].[SYS_CURRENCY] (
    [CURR_CODE]       VARCHAR (6)  NULL,
    [CURR_SYMBOL]     VARCHAR (4)  NULL,
    [CURR_RATE]       FLOAT (53)   DEFAULT ((0)) NULL,
    [CURR_RATEDATE]   DATETIME     NULL,
    [CYEAR_END_CODE]  VARCHAR (25) NULL,
    [EX_DIFF_SALES]   VARCHAR (25) NULL,
    [EX_DIFF_PURCH]   VARCHAR (25) NULL,
    [CURR_NOTE]       VARCHAR (40) NULL,
    [CURR_USED]       TINYINT      DEFAULT ((0)) NULL,
    [CSALES_DEFAULT]  VARCHAR (25) NULL,
    [CPURCH_DEFAULT]  VARCHAR (25) NULL,
    [CURR_COUNTRY]    VARCHAR (4)  NULL,
    [CUR_USER_EDITED] VARCHAR (4)  NULL,
    [CUR_DATE_EDITED] DATETIME     NULL,
    [CUR_DATE_PUTIN]  DATETIME     NULL,
    [CUR_USER_PUTIN]  VARCHAR (4)  NULL,
    [CUR_PRIMARY]     FLOAT (53)   NOT NULL,
    [CURR_TYPE]       VARCHAR (1)  NULL,
    CONSTRAINT [CUR_PRIMARY_PK] PRIMARY KEY CLUSTERED ([CUR_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CURR_CODE]
    ON [dbo].[SYS_CURRENCY]([CURR_CODE] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [CURR_COUNTRY]
    ON [dbo].[SYS_CURRENCY]([CURR_COUNTRY] ASC);


GO
CREATE NONCLUSTERED INDEX [CURR_SYMBOL]
    ON [dbo].[SYS_CURRENCY]([CURR_SYMBOL] ASC);


GO
CREATE TRIGGER [dbo].[aa_currency_dt]
    ON [dbo].[SYS_CURRENCY]
    WITH ENCRYPTION
    AFTER DELETE
    AS 
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

