CREATE TABLE [dbo].[SYS_SERVICE_PACK] (
    [SP_PRIMARY]           INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SP_VERSION]           VARCHAR (6)   NULL,
    [SP_FORMATNAME]        VARCHAR (60)  NULL,
    [SP_FORMAT]            IMAGE         NULL,
    [SP_FORMATTYPE]        VARCHAR (15)  NULL,
    [SP_FORMATDESCRIPTION] VARCHAR (255) NULL,
    [SP_PATCHVERSION]      VARCHAR (2)   NULL,
    [SP_CHUNKID]           INT           DEFAULT ((0)) NULL,
    [SP_CHUNKCOUNT]        INT           DEFAULT ((0)) NULL,
    [SP_HOTFIX_NUMBER]     INT           DEFAULT ((0)) NULL,
    CONSTRAINT [SP_PRIMARY_PK] PRIMARY KEY CLUSTERED ([SP_PRIMARY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SP_FORMATNAME]
    ON [dbo].[SYS_SERVICE_PACK]([SP_FORMATNAME] ASC);


GO
CREATE NONCLUSTERED INDEX [SP_PATCHVERSION]
    ON [dbo].[SYS_SERVICE_PACK]([SP_PATCHVERSION] ASC);


GO
CREATE NONCLUSTERED INDEX [SP_VERSION]
    ON [dbo].[SYS_SERVICE_PACK]([SP_VERSION] ASC);

