CREATE TABLE [dbo].[SYS_DEFAULT_SEARCH_CRITERIA] (
    [USER_ID]        VARCHAR (4) NOT NULL,
    [DEFAULT_SEARCH] INT         NOT NULL,
    [LIST_ID]        INT         NOT NULL,
    CONSTRAINT [PK_DEFAULT_SEARCH_CRITERIA] PRIMARY KEY CLUSTERED ([LIST_ID] ASC, [USER_ID] ASC)
);

