CREATE TABLE [dbo].[SYS_DATA_NUMBERS] (
    [SDN_CODE]         NVARCHAR (30)  NOT NULL,
    [SDN_DESRIPTION]   NVARCHAR (100) NOT NULL,
    [SDN_NUMBER]       BIGINT         NOT NULL,
    [SDN_FIXED_LENGTH] TINYINT        NULL,
    CONSTRAINT [SDN_CODE_PK] PRIMARY KEY CLUSTERED ([SDN_CODE] ASC)
);

