CREATE TABLE [dbo].[SYS_TAX_AUDIT] (
    [TAXAUDIT_PRIMARY]       INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [TAXAUDIT_DATE]          DATETIME     NULL,
    [TAXAUDIT_FROMYEAR]      VARCHAR (1)  NULL,
    [TAXAUDIT_TOYEAR]        VARCHAR (1)  NULL,
    [TAXAUDIT_FROMPD]        TINYINT      DEFAULT ((0)) NULL,
    [TAXAUDIT_TOPD]          TINYINT      DEFAULT ((0)) NULL,
    [TAXAUDIT_REF]           VARCHAR (10) NULL,
    [TAXAUDIT_USER]          VARCHAR (4)  NULL,
    [TAXAUDIT_PERSORT]       INT          DEFAULT ((0)) NULL,
    [TAXAUDIT_FROMDATE]      DATETIME     NULL,
    [TAXAUDIT_TODATE]        DATETIME     NULL,
    [TAXAUDIT_FROMYEAR_LINK] SMALLINT     NULL,
    [TAXAUDIT_TOYEAR_LINK]   SMALLINT     NULL,
    CONSTRAINT [TAXAUDIT_PRIMARY_PK] PRIMARY KEY CLUSTERED ([TAXAUDIT_PRIMARY] ASC),
    CONSTRAINT [TAXAUDIT_FROMYEAR_LINK_CK] CHECK ([TAXAUDIT_FROMYEAR] IS NOT NULL AND ([TAXAUDIT_FROMYEAR]='O' OR [TAXAUDIT_FROMYEAR]='N' OR [TAXAUDIT_FROMYEAR]='C' OR [TAXAUDIT_FROMYEAR]='L') AND [TAXAUDIT_FROMYEAR_LINK] IS NOT NULL OR ([TAXAUDIT_FROMYEAR] IS NULL OR ([TAXAUDIT_FROMYEAR]='O' OR [TAXAUDIT_FROMYEAR]='')) AND [TAXAUDIT_FROMYEAR_LINK] IS NULL),
    CONSTRAINT [TAXAUDIT_TOYEAR_LINK_CK] CHECK ([TAXAUDIT_TOYEAR] IS NOT NULL AND ([TAXAUDIT_TOYEAR]='O' OR [TAXAUDIT_TOYEAR]='N' OR [TAXAUDIT_TOYEAR]='C' OR [TAXAUDIT_TOYEAR]='L') AND [TAXAUDIT_TOYEAR_LINK] IS NOT NULL OR ([TAXAUDIT_TOYEAR] IS NULL OR ([TAXAUDIT_TOYEAR]='O' OR [TAXAUDIT_TOYEAR]='')) AND [TAXAUDIT_TOYEAR_LINK] IS NULL),
    CONSTRAINT [TAXAUDIT_FROMYEAR_LINK_FK] FOREIGN KEY ([TAXAUDIT_FROMYEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY]),
    CONSTRAINT [TAXAUDIT_TOYEAR_LINK_FK] FOREIGN KEY ([TAXAUDIT_TOYEAR_LINK]) REFERENCES [dbo].[SYS_YEAR] ([YEAR_PRIMARY])
);

