CREATE TABLE [dbo].[TAG_STK_LOCATION] (
    [LOC_CODE]                 VARCHAR (25) NULL,
    [LOC_NAME]                 VARCHAR (30) NULL,
    [LOC_SORT_KEY]             VARCHAR (20) NULL,
    [LOC_QTYPRINTED]           FLOAT (53)   NULL,
    [LOC_MIN_QTY]              FLOAT (53)   NULL,
    [LOC_MAX_QTY]              FLOAT (53)   NULL,
    [LOC_PHYSICAL]             FLOAT (53)   NULL,
    [LOC_RESERVE_OUT]          FLOAT (53)   NULL,
    [LOC_ORDER_IN]             FLOAT (53)   NULL,
    [LOC_AV_VALU]              FLOAT (53)   NULL,
    [LOC_AV_VALU_C]            FLOAT (53)   NULL,
    [LOC_FIFO_VALU]            FLOAT (53)   NULL,
    [LOC_FIFO_VALU_C]          FLOAT (53)   NULL,
    [LOC_COSTPRICE]            FLOAT (53)   NULL,
    [LOC_COSTPRICE_C]          FLOAT (53)   NULL,
    [LOC_BASEPRICE]            FLOAT (53)   NULL,
    [LOC_BASEPRICE_C]          FLOAT (53)   NULL,
    [LOC_RESERVE_ASM]          FLOAT (53)   NULL,
    [LOC_STNDRD_COST]          FLOAT (53)   NULL,
    [LOC_SANALYSIS]            VARCHAR (25) NULL,
    [LOC_PANALYSIS]            VARCHAR (25) NULL,
    [LOC_CONCATCODE]           VARCHAR (50) NULL,
    [LOC_WAPU_VALUE]           FLOAT (53)   NULL,
    [LOC_ACTUAL_LC]            FLOAT (53)   NULL,
    [LOC_FIFO_POINTR]          FLOAT (53)   NULL,
    [LOC_FIFO_QTY]             FLOAT (53)   NULL,
    [LOC_USERSORT1]            VARCHAR (25) NULL,
    [LOC_USERSORT2]            VARCHAR (25) NULL,
    [LOC_USERSORT3]            VARCHAR (25) NULL,
    [LOC_USERSORT4]            VARCHAR (25) NULL,
    [LOC_USERSORT5]            VARCHAR (25) NULL,
    [LOC_USERSORT6]            VARCHAR (25) NULL,
    [LOC_DEFAULT_WO]           TINYINT      NULL,
    [LOC_WO_ALLOC_QUANTITY]    FLOAT (53)   NULL,
    [LOC_WO_UNALLOC_QUANTITY]  FLOAT (53)   NULL,
    [LOC_WO_WIP_SOP_QUANTITY]  FLOAT (53)   NULL,
    [LOC_WO_FREE_WIP_QUANTITY] FLOAT (53)   NULL,
    [LOC_NOTES]                TEXT         NULL,
    [LOC_AN_DEL_DATE]          DATETIME     NULL,
    [LOC_WAPU_QUANTITY]        FLOAT (53)   NULL,
    [LOC_POP_ANALYSIS]         VARCHAR (25) NULL,
    [LOC_ANALYSIS_OUT]         VARCHAR (25) NULL,
    [LOC_ANALYSIS_IN]          VARCHAR (25) NULL,
    [LOC_SOP_ANALYSIS]         VARCHAR (25) NULL,
    [LOC_USER_EDITED]          VARCHAR (4)  NULL,
    [LOC_USER_PUTIN]           VARCHAR (4)  NULL,
    [LOC_DATE_PUTIN]           DATETIME     NULL,
    [LOC_DATE_EDITED]          DATETIME     NULL,
    [LOC_MU_STATUS]            VARCHAR (1)  NULL,
    [LOC_STOCK_CODE]           VARCHAR (25) NULL,
    [LOC_PRIMARY]              FLOAT (53)   NOT NULL,
    [LOC_BIN_NUMBER]           VARCHAR (15) NULL,
    [LOC_SOURCE]               VARCHAR (1)  NULL,
    [LOC_BACK_ORDER_QTY]       FLOAT (53)   NULL,
    [LOC_DEFAULT_INBOUND]      TINYINT      NULL,
    [LOC_DEFAULT_OUTBOUND]     TINYINT      NULL,
    [LOC_DO_NOT_USE]           BIT          NULL,
    [LOC_FIXED_WEIGHTED]       TINYINT      NOT NULL,
    [LOC_ZERO_PHYSICAL]        TINYINT      NOT NULL
);

