CREATE TABLE [dbo].[TAG_STK_STOCK] (
    [STKCODE]                    VARCHAR (25) NULL,
    [STKNAME]                    VARCHAR (80) NULL,
    [STK_OLDCODE]                VARCHAR (25) NULL,
    [STK_NOTES]                  TEXT         NULL,
    [STK_CURRENCY]               VARCHAR (4)  NULL,
    [STK_MIN_QTY]                FLOAT (53)   NULL,
    [STK_MAX_QTY]                FLOAT (53)   NULL,
    [STK_PHYSICAL]               FLOAT (53)   NULL,
    [STK_RESERVE_OUT]            FLOAT (53)   NULL,
    [STK_ORDER_IN]               FLOAT (53)   NULL,
    [STK_QTYPRINTED]             FLOAT (53)   NULL,
    [STK_BASEPRICE]              FLOAT (53)   NULL,
    [STK_BASEPRICE_C]            FLOAT (53)   NULL,
    [STK_COSTPRICE]              FLOAT (53)   NULL,
    [STK_COSTPRICE_C]            FLOAT (53)   NULL,
    [STK_COSTVALUE]              FLOAT (53)   NULL,
    [STK_SALEVALUE]              FLOAT (53)   NULL,
    [STK_AV_VALU]                FLOAT (53)   NULL,
    [STK_AV_VALU_C]              FLOAT (53)   NULL,
    [STK_FIFO_VALU]              FLOAT (53)   NULL,
    [STK_FIFO_VALU_C]            FLOAT (53)   NULL,
    [STK_VALUEMETHOD]            VARCHAR (1)  NULL,
    [STK_AN_DEL_QTY]             FLOAT (53)   NULL,
    [STK_AN_DEL_DATE]            DATETIME     NULL,
    [STK_RESERVE_ASM]            FLOAT (53)   NULL,
    [STK_SERIALTRACK]            TINYINT      NULL,
    [STK_MULTILOCATN]            TINYINT      NULL,
    [STK_ASSEMBLY]               VARCHAR (1)  NULL,
    [STK_PRICEMETHOD]            VARCHAR (1)  NULL,
    [STK_ARCHIVE]                TINYINT      NULL,
    [STK_STNDRD_COST]            FLOAT (53)   NULL,
    [STK_FIFO_POINTR]            FLOAT (53)   NULL,
    [STK_FIFO_QTY]               FLOAT (53)   NULL,
    [STK_MATRIX_KEY]             VARCHAR (20) NULL,
    [STK_SORT_KEY]               VARCHAR (20) NULL,
    [STK_SORT_KEY2]              VARCHAR (20) NULL,
    [STK_SORT_KEY3]              VARCHAR (20) NULL,
    [STK_SORT_KEY1]              VARCHAR (20) NULL,
    [STK_S_WEIGHT]               FLOAT (53)   NULL,
    [STK_P_WEIGHT]               FLOAT (53)   NULL,
    [STK_S_WGHT_NAME]            VARCHAR (20) NULL,
    [STK_P_WGHT_NAME]            VARCHAR (20) NULL,
    [STK_EC_KILOS]               FLOAT (53)   NULL,
    [STK_EC_ORIGIN]              VARCHAR (3)  NULL,
    [STK_EC_COM_CODE]            VARCHAR (8)  NULL,
    [STK_EC_SUP_UNIT]            FLOAT (53)   NULL,
    [STK_MOVEIN_O1]              FLOAT (53)   NULL,
    [STK_MOVEIN_O2]              FLOAT (53)   NULL,
    [STK_MOVEIN_O3]              FLOAT (53)   NULL,
    [STK_MOVEIN_O4]              FLOAT (53)   NULL,
    [STK_MOVEIN_O5]              FLOAT (53)   NULL,
    [STK_MOVEIN_O6]              FLOAT (53)   NULL,
    [STK_MOVEIN_O7]              FLOAT (53)   NULL,
    [STK_MOVEIN_O8]              FLOAT (53)   NULL,
    [STK_MOVEIN_O9]              FLOAT (53)   NULL,
    [STK_MOVEIN_O10]             FLOAT (53)   NULL,
    [STK_MOVEIN_O11]             FLOAT (53)   NULL,
    [STK_MOVEIN_O12]             FLOAT (53)   NULL,
    [STK_MOVEIN_O13]             FLOAT (53)   NULL,
    [STK_MOVEOUT_O1]             FLOAT (53)   NULL,
    [STK_MOVEOUT_O2]             FLOAT (53)   NULL,
    [STK_MOVEOUT_O3]             FLOAT (53)   NULL,
    [STK_MOVEOUT_O4]             FLOAT (53)   NULL,
    [STK_MOVEOUT_O5]             FLOAT (53)   NULL,
    [STK_MOVEOUT_O6]             FLOAT (53)   NULL,
    [STK_MOVEOUT_O7]             FLOAT (53)   NULL,
    [STK_MOVEOUT_O8]             FLOAT (53)   NULL,
    [STK_MOVEOUT_O9]             FLOAT (53)   NULL,
    [STK_MOVEOUT_O10]            FLOAT (53)   NULL,
    [STK_MOVEOUT_O11]            FLOAT (53)   NULL,
    [STK_MOVEOUT_O12]            FLOAT (53)   NULL,
    [STK_MOVEOUT_O13]            FLOAT (53)   NULL,
    [STK_MOVEIN_L1]              FLOAT (53)   NULL,
    [STK_MOVEIN_L2]              FLOAT (53)   NULL,
    [STK_MOVEIN_L3]              FLOAT (53)   NULL,
    [STK_MOVEIN_L4]              FLOAT (53)   NULL,
    [STK_MOVEIN_L5]              FLOAT (53)   NULL,
    [STK_MOVEIN_L6]              FLOAT (53)   NULL,
    [STK_MOVEIN_L7]              FLOAT (53)   NULL,
    [STK_MOVEIN_L8]              FLOAT (53)   NULL,
    [STK_MOVEIN_L9]              FLOAT (53)   NULL,
    [STK_MOVEIN_L10]             FLOAT (53)   NULL,
    [STK_MOVEIN_L11]             FLOAT (53)   NULL,
    [STK_MOVEIN_L12]             FLOAT (53)   NULL,
    [STK_MOVEIN_L13]             FLOAT (53)   NULL,
    [STK_MOVEOUT_L1]             FLOAT (53)   NULL,
    [STK_MOVEOUT_L2]             FLOAT (53)   NULL,
    [STK_MOVEOUT_L3]             FLOAT (53)   NULL,
    [STK_MOVEOUT_L4]             FLOAT (53)   NULL,
    [STK_MOVEOUT_L5]             FLOAT (53)   NULL,
    [STK_MOVEOUT_L6]             FLOAT (53)   NULL,
    [STK_MOVEOUT_L7]             FLOAT (53)   NULL,
    [STK_MOVEOUT_L8]             FLOAT (53)   NULL,
    [STK_MOVEOUT_L9]             FLOAT (53)   NULL,
    [STK_MOVEOUT_L10]            FLOAT (53)   NULL,
    [STK_MOVEOUT_L11]            FLOAT (53)   NULL,
    [STK_MOVEOUT_L12]            FLOAT (53)   NULL,
    [STK_MOVEOUT_L13]            FLOAT (53)   NULL,
    [STK_MOVEIN_C1]              FLOAT (53)   NULL,
    [STK_MOVEIN_C2]              FLOAT (53)   NULL,
    [STK_MOVEIN_C3]              FLOAT (53)   NULL,
    [STK_MOVEIN_C4]              FLOAT (53)   NULL,
    [STK_MOVEIN_C5]              FLOAT (53)   NULL,
    [STK_MOVEIN_C6]              FLOAT (53)   NULL,
    [STK_MOVEIN_C7]              FLOAT (53)   NULL,
    [STK_MOVEIN_C8]              FLOAT (53)   NULL,
    [STK_MOVEIN_C9]              FLOAT (53)   NULL,
    [STK_MOVEIN_C10]             FLOAT (53)   NULL,
    [STK_MOVEIN_C11]             FLOAT (53)   NULL,
    [STK_MOVEIN_C12]             FLOAT (53)   NULL,
    [STK_MOVEIN_C13]             FLOAT (53)   NULL,
    [STK_MOVEOUT_C1]             FLOAT (53)   NULL,
    [STK_MOVEOUT_C2]             FLOAT (53)   NULL,
    [STK_MOVEOUT_C3]             FLOAT (53)   NULL,
    [STK_MOVEOUT_C4]             FLOAT (53)   NULL,
    [STK_MOVEOUT_C5]             FLOAT (53)   NULL,
    [STK_MOVEOUT_C6]             FLOAT (53)   NULL,
    [STK_MOVEOUT_C7]             FLOAT (53)   NULL,
    [STK_MOVEOUT_C8]             FLOAT (53)   NULL,
    [STK_MOVEOUT_C9]             FLOAT (53)   NULL,
    [STK_MOVEOUT_C10]            FLOAT (53)   NULL,
    [STK_MOVEOUT_C11]            FLOAT (53)   NULL,
    [STK_MOVEOUT_C12]            FLOAT (53)   NULL,
    [STK_MOVEOUT_C13]            FLOAT (53)   NULL,
    [STK_COSTVAL_PTD]            FLOAT (53)   NULL,
    [STK_COSTVAL_YTD]            FLOAT (53)   NULL,
    [STK_SALEVAL_PTD]            FLOAT (53)   NULL,
    [STK_SALEVAL_YTD]            FLOAT (53)   NULL,
    [STK_COSTVAL_1]              FLOAT (53)   NULL,
    [STK_COSTVAL_2]              FLOAT (53)   NULL,
    [STK_COSTVAL_3]              FLOAT (53)   NULL,
    [STK_COSTVAL_4]              FLOAT (53)   NULL,
    [STK_COSTVAL_5]              FLOAT (53)   NULL,
    [STK_COSTVAL_6]              FLOAT (53)   NULL,
    [STK_COSTVAL_7]              FLOAT (53)   NULL,
    [STK_COSTVAL_8]              FLOAT (53)   NULL,
    [STK_COSTVAL_9]              FLOAT (53)   NULL,
    [STK_COSTVAL_10]             FLOAT (53)   NULL,
    [STK_COSTVAL_11]             FLOAT (53)   NULL,
    [STK_COSTVAL_12]             FLOAT (53)   NULL,
    [STK_COSTVAL_13]             FLOAT (53)   NULL,
    [STK_SALEVAL_1]              FLOAT (53)   NULL,
    [STK_SALEVAL_2]              FLOAT (53)   NULL,
    [STK_SALEVAL_3]              FLOAT (53)   NULL,
    [STK_SALEVAL_4]              FLOAT (53)   NULL,
    [STK_SALEVAL_5]              FLOAT (53)   NULL,
    [STK_SALEVAL_6]              FLOAT (53)   NULL,
    [STK_SALEVAL_7]              FLOAT (53)   NULL,
    [STK_SALEVAL_8]              FLOAT (53)   NULL,
    [STK_SALEVAL_9]              FLOAT (53)   NULL,
    [STK_SALEVAL_10]             FLOAT (53)   NULL,
    [STK_SALEVAL_11]             FLOAT (53)   NULL,
    [STK_SALEVAL_12]             FLOAT (53)   NULL,
    [STK_SALEVAL_13]             FLOAT (53)   NULL,
    [STK_WAPU_QUANTITY]          FLOAT (53)   NULL,
    [STK_WAPU_VALUE]             FLOAT (53)   NULL,
    [STK_BARCODE]                VARCHAR (20) NULL,
    [STK_ISSUE_ANALYSIS]         VARCHAR (25) NULL,
    [STK_WRITE_OFF_ANALYSIS]     VARCHAR (25) NULL,
    [STK_SCRAP_ANALYSIS]         VARCHAR (25) NULL,
    [STK_FINISHED_ANALYSIS]      VARCHAR (25) NULL,
    [STK_WO_ALLOC_QUANTITY]      FLOAT (53)   NULL,
    [STK_WO_UNALLOC_QUANTITY]    FLOAT (53)   NULL,
    [STK_WO_WIP_SOP_QUANTITY]    FLOAT (53)   NULL,
    [STK_WO_FREE_WIP_QUANTITY]   FLOAT (53)   NULL,
    [STK_BOM_DEFAULT_ACTION]     VARCHAR (1)  NULL,
    [STK_BOM_MIN_BUILD_QUANTITY] FLOAT (53)   NULL,
    [STK_BOM_BATCH_QUANTITY]     FLOAT (53)   NULL,
    [STK_BOM_ROUTE_LINK]         INT          NULL,
    [STK_BOM_DURATION]           FLOAT (53)   NULL,
    [STK_BOM_NOTES]              TEXT         NULL,
    [STK_BOM_COMPLETION_CERT]    VARCHAR (30) NULL,
    [STK_USER_EDITED]            VARCHAR (4)  NULL,
    [STK_USER_PUTIN]             VARCHAR (4)  NULL,
    [STK_DATE_PUTIN]             DATETIME     NULL,
    [STK_DATE_EDITED]            DATETIME     NULL,
    [STK_MU_STATUS]              VARCHAR (1)  NULL,
    [STK_WWW_PUBLISH]            TINYINT      NULL,
    [STK_SPECIAL_PRICE_DATE]     DATETIME     NULL,
    [STK_USED]                   TINYINT      NULL,
    [STK_NO_TAX]                 TINYINT      NULL,
    [STK_PRIMARY]                FLOAT (53)   NOT NULL,
    [STK_RTP_FLAG]               TINYINT      NULL,
    [STK_LINK_FLAG]              TINYINT      NULL,
    [STK_ALTERNATIVE_FLAG]       TINYINT      NULL,
    [STK_LEVEL]                  INT          NULL,
    [STK_GROUP]                  VARCHAR (15) NULL,
    [STK_WARRANTY]               TINYINT      NULL,
    [STK_WARRANTY_TYPE]          VARCHAR (15) NULL,
    [STK_BIN_NUMBER]             VARCHAR (15) NULL,
    [STK_TEMPLATE]               TINYINT      NULL,
    [STK_SOURCE]                 VARCHAR (1)  NULL,
    [STK_BACK_ORDER_QTY]         FLOAT (53)   NULL,
    [STK_POP_ANALYSIS]           VARCHAR (25) NULL,
    [STK_ANALYSIS_OUT]           VARCHAR (25) NULL,
    [STK_ANALYSIS_IN]            VARCHAR (25) NULL,
    [STK_SOP_ANALYSIS]           VARCHAR (25) NULL,
    [STK_MOVEIN_N1]              FLOAT (53)   NULL,
    [STK_MOVEIN_N2]              FLOAT (53)   NULL,
    [STK_MOVEIN_N3]              FLOAT (53)   NULL,
    [STK_MOVEIN_N4]              FLOAT (53)   NULL,
    [STK_MOVEIN_N5]              FLOAT (53)   NULL,
    [STK_MOVEIN_N6]              FLOAT (53)   NULL,
    [STK_MOVEIN_N7]              FLOAT (53)   NULL,
    [STK_MOVEIN_N8]              FLOAT (53)   NULL,
    [STK_MOVEIN_N9]              FLOAT (53)   NULL,
    [STK_MOVEIN_N10]             FLOAT (53)   NULL,
    [STK_MOVEIN_N11]             FLOAT (53)   NULL,
    [STK_MOVEIN_N12]             FLOAT (53)   NULL,
    [STK_MOVEIN_N13]             FLOAT (53)   NULL,
    [STK_MOVEOUT_N1]             FLOAT (53)   NULL,
    [STK_MOVEOUT_N2]             FLOAT (53)   NULL,
    [STK_MOVEOUT_N3]             FLOAT (53)   NULL,
    [STK_MOVEOUT_N4]             FLOAT (53)   NULL,
    [STK_MOVEOUT_N5]             FLOAT (53)   NULL,
    [STK_MOVEOUT_N6]             FLOAT (53)   NULL,
    [STK_MOVEOUT_N7]             FLOAT (53)   NULL,
    [STK_MOVEOUT_N8]             FLOAT (53)   NULL,
    [STK_MOVEOUT_N9]             FLOAT (53)   NULL,
    [STK_MOVEOUT_N10]            FLOAT (53)   NULL,
    [STK_MOVEOUT_N11]            FLOAT (53)   NULL,
    [STK_MOVEOUT_N12]            FLOAT (53)   NULL,
    [STK_MOVEOUT_N13]            FLOAT (53)   NULL,
    [STK_FIXED_WEIGHTED]         TINYINT      NOT NULL,
    [STK_REVERSE_CHRGE_VAT]      TINYINT      NULL,
    [STK_DO_NOT_USE]             TINYINT      NOT NULL,
    [STK_ZERO_PHYSICAL]          TINYINT      NOT NULL,
    [STK_SERVICE]                BIT          NOT NULL
);

