CREATE TABLE [dbo].[TB_LKP_DETAIL] (
    [TLD_PRIMARY] INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [TLD_CODE]    VARCHAR (10)  NULL,
    [TLD_INPUT]   VARCHAR (100) NULL,
    [TLD_OUTPUT]  VARCHAR (100) NULL,
    CONSTRAINT [TLD_PRIMARY_PK] PRIMARY KEY CLUSTERED ([TLD_PRIMARY] ASC)
);

