CREATE TABLE [dbo].[TB_LKP_HEADER] (
    [TLH_PRIMARY]  INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [TLH_CODE]     VARCHAR (10)  NULL,
    [TLH_FALLBACK] TINYINT       DEFAULT ((0)) NULL,
    [TLH_FB_DATA]  VARCHAR (100) NULL,
    [TLH_SYSTEM]   TINYINT       DEFAULT ((0)) NULL,
    CONSTRAINT [TLH_PRIMARY_PK] PRIMARY KEY CLUSTERED ([TLH_PRIMARY] ASC)
);

