CREATE TABLE [dbo].[TS_ALERT_USER_SETUP] (
    [ALSU_PRIMARY]     INT          NOT NULL,
    [ALSU_USERID]      VARCHAR (4)  DEFAULT ('') NOT NULL,
    [ALSU_RECORD_TYPE] VARCHAR (30) DEFAULT ('') NOT NULL,
    [ALSU_RECORD_LINK] INT          DEFAULT ((0)) NOT NULL,
    [ALSU_SCHEDULE]    TINYINT      DEFAULT ((0)) NOT NULL,
    [ALSU_NUM]         INT          DEFAULT ((0)) NOT NULL,
    [ALSU_TIME1]       DATETIME     NULL,
    [ALSU_TIME2]       DATETIME     NULL,
    [ALSU_MON]         TINYINT      DEFAULT ((0)) NOT NULL,
    [ALSU_TUE]         TINYINT      DEFAULT ((0)) NOT NULL,
    [ALSU_WED]         TINYINT      DEFAULT ((0)) NOT NULL,
    [ALSU_THU]         TINYINT      DEFAULT ((0)) NOT NULL,
    [ALSU_FRI]         TINYINT      DEFAULT ((0)) NOT NULL,
    [ALSU_SAT]         TINYINT      DEFAULT ((0)) NOT NULL,
    [ALSU_SUN]         TINYINT      DEFAULT ((0)) NOT NULL,
    [ALSU_LAST_RUN]    DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([ALSU_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

