CREATE TABLE [dbo].[TS_APPROVAL_LOG_USER] (
    [APAU_PRIMARY]         INT         NOT NULL,
    [APAU_APAL_PRIMARY]    INT         DEFAULT ((0)) NOT NULL,
    [APAU_USERID]          VARCHAR (4) DEFAULT ('') NOT NULL,
    [APAU_ORIGINAL_USERID] VARCHAR (4) DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([APAU_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

