CREATE TABLE [dbo].[TS_ALERT_LOG] (
    [ALTL_PRIMARY]          INT           IDENTITY (0, 1) NOT FOR REPLICATION NOT NULL,
    [ALTL_ALSH_PRIMARY]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ALTL_RECORD]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ALTL_USERID]           VARCHAR (4)   DEFAULT ('') NOT NULL,
    [ALTL_RECIPIENT]        VARCHAR (MAX) DEFAULT ('') NOT NULL,
    [ALTL_DATE]             DATETIME      NULL,
    [ALTL_STATUS]           TINYINT       DEFAULT ((0)) NOT NULL,
    [ALTL_ERROR]            VARCHAR (MAX) DEFAULT ('') NOT NULL,
    [ALTL_RECIPIENT_USERID] VARCHAR (4)   DEFAULT ('') NOT NULL,
    [ALTL_FROM_ADDRESS]     VARCHAR (MAX) DEFAULT ('') NOT NULL,
    [ALTL_SUBJECT]          VARCHAR (MAX) DEFAULT ('') NOT NULL,
    [ALTL_BODY]             VARCHAR (MAX) DEFAULT ('') NOT NULL,
    [ALTL_SENT_DATE]        DATETIME      NULL,
    [ALTL_CC]               VARCHAR (MAX) DEFAULT ('') NOT NULL,
    [ALTL_BCC]              VARCHAR (MAX) DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([ALTL_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

