CREATE TABLE [dbo].[TS_BUDGET_REVISIONS] (
    [TSLR_PRIMARY]         FLOAT (53)    NOT NULL,
    [TSLR_ACCOUNT_CODE]    VARCHAR (25)  NOT NULL,
    [TSLR_SECONDARY_CODE]  VARCHAR (25)  NOT NULL,
    [TSLR_RECORD_TYPE]     VARCHAR (2)   NOT NULL,
    [TSLR_BUDGET_TYPE]     VARCHAR (1)   NOT NULL,
    [TSLR_REVISION_NUMBER] TINYINT       NOT NULL,
    [TSLR_DESCRIPTION]     VARCHAR (240) NOT NULL,
    [TSLR_LOCKED]          TINYINT       NOT NULL,
    [TSLR_ACTIVE]          TINYINT       NOT NULL,
    [TSLR_TSPR_PRIMARY]    FLOAT (53)    NOT NULL,
    CONSTRAINT [TS_BUDGET_REVISIONS_PK] PRIMARY KEY CLUSTERED ([TSLR_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

