CREATE TABLE [dbo].[TS_CUSTOM_FORM_SETUP_DETAIL] (
    [CFSD_PRIMARY]                             FLOAT (53)       NOT NULL,
    [CFSD_LOOKUP_TYPE]                         TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_FIELD_TEXT]                          VARCHAR (40)     DEFAULT ('') NOT NULL,
    [CFSD_REGION]                              INT              DEFAULT ((0)) NOT NULL,
    [CFSD_SHOW]                                TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_ENABLE]                              TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_COMPULSARY]                          TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_FILTER_DEFAULT]                      TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_CFSH_PRIMARY]                        FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFSD_COLUMN_NAME]                         VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_COL_TYPE]                            TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_COL_LEN]                             FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFSD_CFST_PRIMARY]                        FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFSD_COND_LINK]                           TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_COND_OPERATOR_TYPE]                  TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_COND_VALUE]                          VARCHAR (25)     DEFAULT ('') NOT NULL,
    [CFSD_SHOW_TYPE]                           TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_SHOW_TYPE_STAGE]                     VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_ENABLE_TYPE]                         TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_ENABLE_TYPE_STAGE]                   VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_COMPULSARY_TYPE]                     TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_COMPULSARY_TYPE_STAGE]               VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_DEFAULT_TYPE]                        TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_DEFAULT_VALUE]                       VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_LOOKUP_METHOD]                       TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LOOKUP_OBJ_NAME]                     VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_POSITION]                            TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_ON_VIEW]                             TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_VIEW_ORDER]                          INT              DEFAULT ((0)) NOT NULL,
    [CFSD_DEFAULT_DL_ID]                       FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFSD_DEAFAULT_DL_COLUMN]                  VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_REFRESH_TYPE]                        TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LOOKUP_CODE_COL_NAME]                VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_LOOKUP_NAME_COL_NAME]                VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_LOOKUP_FILTER_COL_NAME]              VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_LOOKUP_LINK_TYPE]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LOOKUP_LINK_OPERATOR_TYPE]           TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LOOKUP_LINK_VALUE]                   VARCHAR (20)     DEFAULT ('') NOT NULL,
    [CFSD_LOOKUP_LINK_CFSD_COLUMN_TEXT]        VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_LOOKUP_LINK_CFSD_COLUMN_NAME]        VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_IS_UNIQUE]                           TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_FREE_ENTRY]                          TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_VALIDATION_EXPRESSION]               VARCHAR (500)    DEFAULT ('') NOT NULL,
    [CFSD_TOOLTIP]                             VARCHAR (100)    DEFAULT ('') NOT NULL,
    [CFSD_FIELD_SHOW_CONFIG_PROC]              VARCHAR (100)    DEFAULT ('') NOT NULL,
    [CFSD_DEFAULT_VALUE_PROC]                  VARCHAR (100)    DEFAULT ('') NOT NULL,
    [CFSD_FIELD_ENABLE_CONFIG_PROC]            VARCHAR (100)    DEFAULT ('') NOT NULL,
    [CFSD_FIELD_COMP_CONFIG_PROC]              VARCHAR (100)    DEFAULT ('') NOT NULL,
    [CFSD_FORMULA]                             VARCHAR (2000)   NULL,
    [CFSD_SHOW_TOTAL]                          TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_FORMAT]                              VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_DEFAULT_VALUE_REFRESH]               TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_VALIDATION_TYPE]                     TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_VALIDATION_PROC]                     VARCHAR (100)    DEFAULT ('') NOT NULL,
    [CFSD_ORDER]                               FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFSD_COLUMN_WIDTH]                        INT              DEFAULT ((0)) NOT NULL,
    [CFSD_IS_VIEW_COLUMN]                      TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_ENCRYPTED]                           TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_HEIGHT]                              FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFSD_VALIDATION_MESSAGE_TYPE]             TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_FORMULA_ROW_KEY]                     VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_POPUP_IF_INVALID]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LABEL_TEXT]                          VARCHAR (500)    DEFAULT ('') NOT NULL,
    [CFSD_FORCE_LOOKUP_AUTO_POPULATE]          TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_KEEP_PLACEHOLDER]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_DONT_SHOW_TEXT_BOX]                  TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_FORCE_LOOKUP_USE_DROPDOWN]           TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_ALIGNMENT]                           TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LOOKUP_SCRIPT]                       TEXT             DEFAULT ('') NOT NULL,
    [CFSD_LABEL_TYPE]                          TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_DISPLAY_LABEL]                       VARCHAR (40)     DEFAULT ('') NOT NULL,
    [CFSD_ALLOW_LOOKUP_EDIT]                   TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LOOKUP_CUSTOM_LINK_TEXT]             VARCHAR (1000)   DEFAULT ('') NOT NULL,
    [CFSD_INDEXED]                             TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_BOLD]                                TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_ITALIC]                              TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_COLOUR]                              VARCHAR (7)      DEFAULT ('') NOT NULL,
    [CFSD_PR_LINK_FIELD]                       VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_GROUP_ORDER]                         TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_IS_GROUP_COLUMN]                     TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_SYSTEM]                              TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LOOKUP_HIDE_CODE]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_FORCE_UPPER_CASE]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LOOKUP_PRIMARY_COL_NAME]             VARCHAR (30)     DEFAULT ('') NOT NULL,
    [CFSD_LOOKUP_DROPDOWN_SHOW_DEFAULT_OPTION] TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LOOKUP_DROPDOWN_DEFAULT_PROMPT]      VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_UPDATE_SELECTPAY]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_IS_KEY]                              TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_GRID_CELL_MULTILINE]                 TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LABEL_FROM_PROC]                     TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LABEL_PROC]                          VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFSD_VALIDATION_SCRIPT]                   VARCHAR (MAX)    DEFAULT ('') NOT NULL,
    [CFSD_COND_VALUE_TO]                       VARCHAR (25)     DEFAULT ('') NOT NULL,
    [CFSD_HIDE_DISPLAY_NAME]                   TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_GUID]                                UNIQUEIDENTIFIER NULL,
    [CFSD_GRID_CELL_WRAP]                      TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_DO_NOT_VALIDATE_ONLOAD]              TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_HYPERLINK]                           TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_ADDRESS_ONE_LINE]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_ADDRESS_MATCH]                       INT              DEFAULT ((0)) NOT NULL,
    [CFSD_ADDRESS_FIELD_LINK]                  UNIQUEIDENTIFIER NULL,
    [CFSD_ADDRESS_DIMS_FORMAT]                 TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_LIMIT_ADDRESS_LINES]                 TINYINT          DEFAULT ((0)) NOT NULL,
    [CFSD_DISTANCE_METHOD]                     INT              DEFAULT ((0)) NOT NULL,
    [CFSD_ON_FILTER_VIEW]                      INT              DEFAULT ((0)) NOT NULL,
    [CFSD_ENABLE_FILTER]                       TINYINT          DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([CFSD_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

