CREATE TABLE [dbo].[TS_CUSTOM_FORM_BATCH_TEMP] (
    [CFBT_BATCH_ID]      UNIQUEIDENTIFIER NULL,
    [CFBT_CFSH_PRIMARY]  FLOAT (53)       NULL,
    [CFBT_INSERT_USERID] VARCHAR (4)      NULL,
    [CFBT_INSERT_DATE]   DATETIME         NULL,
    [CFBT_ROW_KEY]       SQL_VARIANT      NULL,
    [CFBT_STATUS]        TINYINT          NULL,
    [CFBT_MESSAGE]       VARCHAR (200)    NULL
);

