CREATE TABLE [dbo].[TS_CUSTOM_FORM_USER_PREFS_GRIDS] (
    [PRFG_PRIMARY]      INT          IDENTITY (0, 1) NOT FOR REPLICATION NOT NULL,
    [PRFG_PRFD_PRIMARY] INT          DEFAULT ((0)) NOT NULL,
    [PRFG_COL]          VARCHAR (80) DEFAULT ('') NOT NULL,
    [PRFG_WIDTH]        INT          DEFAULT ((0)) NOT NULL,
    [PRFG_ORDER]        INT          DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([PRFG_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

