CREATE TABLE [dbo].[TS_CUSTOM_FORM_VIEW_COLUMNS] (
    [CFVC_PRIMARY]      FLOAT (53)       NOT NULL,
    [CFVC_CFSH_PRIMARY] FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFVC_COLUMN_NAME]  VARCHAR (100)    DEFAULT ('') NOT NULL,
    [CFVC_DP]           TINYINT          DEFAULT ((0)) NOT NULL,
    [CFVC_FORMAT]       VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFVC_ALIGNMENT]    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFVC_DATATYPE]     VARCHAR (20)     DEFAULT ('') NOT NULL,
    [CFVC_TOTALLED]     TINYINT          DEFAULT ((0)) NOT NULL,
    [CFVC_WIDTH]        FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFVC_HYPERLINK]    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFVC_ON_FILTER]    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFVC_GUID]         UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([CFVC_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

