CREATE TABLE [dbo].[TS_CUSTOM_FORM_USER_PREFS_DETAIL] (
    [PRFD_PRIMARY]       INT          IDENTITY (0, 1) NOT FOR REPLICATION NOT NULL,
    [PRFD_PRFH_PRIMARY]  INT          DEFAULT ((0)) NOT NULL,
    [PRFD_TYPE]          VARCHAR (1)  DEFAULT ('') NOT NULL,
    [PRFD_TB_DOCK]       TINYINT      DEFAULT ((0)) NOT NULL,
    [PRFD_TB_X]          INT          DEFAULT ((0)) NOT NULL,
    [PRFD_TB_Y]          INT          DEFAULT ((0)) NOT NULL,
    [PRFD_TB_WIDTH]      INT          DEFAULT ((0)) NOT NULL,
    [PRFD_TB_HEIGHT]     INT          DEFAULT ((0)) NOT NULL,
    [PRFD_SPLIT1]        INT          DEFAULT ((0)) NOT NULL,
    [PRFD_SPLIT2]        INT          DEFAULT ((0)) NOT NULL,
    [PRFD_SPLIT3]        INT          DEFAULT ((0)) NOT NULL,
    [PRFD_CFST_TAB_CODE] VARCHAR (20) DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([PRFD_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

