CREATE TABLE [dbo].[TS_CUSTOM_FORM_SETUP_HOOKS] (
    [CFHK_PRIMARY]        FLOAT (53)       NOT NULL,
    [CFHK_CFSH_PRIMARY]   FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFHK_DIALOG_FORM_ID] FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFHK_TRIGGER]        TINYINT          DEFAULT ((0)) NOT NULL,
    [CFHK_TYPE]           TINYINT          DEFAULT ((0)) NOT NULL,
    [CFHK_ENABLED]        TINYINT          DEFAULT ((0)) NOT NULL,
    [CFHK_COMMAND]        TEXT             DEFAULT ('') NOT NULL,
    [CFHK_RESULT_TEXT]    VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFHK_RESULT_FIELD]   VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFHK_GUID]           UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([CFHK_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

