CREATE TABLE [dbo].[TS_CUSTOM_FORM_CFC_OPTIONS] (
    [CFC_VERSION]     VARCHAR (30) DEFAULT ('') NOT NULL,
    [CFC_MENU_XML]    TEXT         DEFAULT ('') NULL,
    [CFC_ENABLE_PA]   TINYINT      DEFAULT ((0)) NOT NULL,
    [CFC_PA_ACC_NAME] VARCHAR (50) DEFAULT ('') NOT NULL,
    [CFC_PA_PASSWORD] VARCHAR (50) DEFAULT ('') NOT NULL
);

