CREATE TABLE [dbo].[TS_CUSTOM_FORM_NAV] (
    [NAV_ID]               INT          IDENTITY (0, 1) NOT FOR REPLICATION NOT NULL,
    [NAV_APPLICATION]      VARCHAR (20) DEFAULT ('') NOT NULL,
    [NAV_CFSH_UNIQUE_CODE] VARCHAR (25) DEFAULT ('') NOT NULL,
    [NAV_CODE]             VARCHAR (25) DEFAULT ('') NOT NULL,
    [NAV_PRIORITY]         INT          DEFAULT ((0)) NOT NULL,
    [NAV_RUN_FROM]         VARCHAR (25) DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([NAV_ID] ASC) WITH (FILLFACTOR = 70)
);

