CREATE TABLE [dbo].[TS_CUSTOM_FORM_LINK] (
    [CFLN_PRIMARY]               FLOAT (53)       NOT NULL,
    [CFLN_PARENT_FORM_TYPE_ID]   FLOAT (53)       NULL,
    [CFLN_PARENT_FORM_ID]        FLOAT (53)       NULL,
    [CFLN_CHILD_FORM_TYPE_ID]    FLOAT (53)       NULL,
    [CFLN_CHILD_FORM_ID]         FLOAT (53)       NULL,
    [CFLN_PARENT_FORM_TYPE_CODE] VARCHAR (25)     NULL,
    [CFLN_CHILD_FORM_TYPE_CODE]  VARCHAR (25)     NULL,
    [CFLN_PARENT_TABLE_NAME]     VARCHAR (50)     NULL,
    [CFLN_PARENT_FIELD_NAME]     VARCHAR (50)     NULL,
    [CFLN_LINK_TABLE_NAME]       VARCHAR (50)     NULL,
    [CFLN_LINK_ID]               FLOAT (53)       NULL,
    [CFLN_PARENT_TEMP_ID]        UNIQUEIDENTIFIER NULL,
    [CFLN_ORIGINAL_LINK_TYPE]    VARCHAR (200)    NULL,
    [CFLN_PARENT_ROW_ID]         SQL_VARIANT      NULL,
    PRIMARY KEY CLUSTERED ([CFLN_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

