CREATE TABLE [dbo].[TS_CUSTOM_FORM_SETUP_LOOKUPS] (
    [CFSL_PRIMARY]      FLOAT (53)   NOT NULL,
    [CFSL_NAME]         VARCHAR (30) DEFAULT ('') NOT NULL,
    [CFSL_CFSD_PRIMARY] FLOAT (53)   DEFAULT ((0)) NOT NULL,
    [CFSL_ORDER]        INT          DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([CFSL_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

