CREATE TABLE [dbo].[TS_CUSTOM_FORM_USER_PREFS_HEAD] (
    [PRFH_PRIMARY]          INT          IDENTITY (0, 1) NOT FOR REPLICATION NOT NULL,
    [PRFH_USER]             VARCHAR (4)  DEFAULT ('') NOT NULL,
    [PRFH_APPLICATION]      VARCHAR (4)  DEFAULT ('') NOT NULL,
    [PRFH_CFSH_UNIQUE_CODE] VARCHAR (25) DEFAULT ('') NOT NULL,
    [PRFH_FORM_TYPE]        VARCHAR (1)  DEFAULT ('') NOT NULL,
    [PRFH_WND_MAX]          TINYINT      DEFAULT ((0)) NOT NULL,
    [PRFH_WND_X]            INT          DEFAULT ((0)) NOT NULL,
    [PRFH_WND_Y]            INT          DEFAULT ((0)) NOT NULL,
    [PRFH_WND_WIDTH]        INT          DEFAULT ((0)) NOT NULL,
    [PRFH_WND_HEIGHT]       INT          DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([PRFH_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

