CREATE TABLE [dbo].[TS_CUSTOM_FORM_SETUP_TABS] (
    [CFST_PRIMARY]                         FLOAT (53)       NOT NULL,
    [CFST_TAB_NAME]                        VARCHAR (30)     DEFAULT ('') NOT NULL,
    [CFST_TAB_TYPE]                        TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_CFSH_PRIMARY]                    FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFST_SUB_CFSH_PRIMARY]                FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFST_VISIBLE]                         TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_POSITION]                        TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_VIEW_NAME]                       VARCHAR (200)    DEFAULT ('') NOT NULL,
    [CFST_LINK_VIEW_COLUMN_NAME]           VARCHAR (100)    DEFAULT ('') NOT NULL,
    [CFST_LINK_TYPE]                       TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_LINK_CFSD_COLUMN_NAME]           VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFST_CUSTOM_LINK_TEXT]                VARCHAR (1000)   DEFAULT ('') NOT NULL,
    [CFST_LINK_VALUE]                      VARCHAR (20)     DEFAULT ('') NOT NULL,
    [CFST_LINK_OPERATOR_TYPE]              TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_ALLOW_RT_NOTES]                  TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_SEQ_CODE]                        VARCHAR (50)     NULL,
    [CFST_TABLE_NAME]                      VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFST_LINK_VIEW_PK_COLUMN_NAME]        VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFST_TAB_ORDER]                       FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFST_ALLOW_REFRESH]                   TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_DISPLAY_TOTALS]                  TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_FIXED_FOOTER]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CSFT_AUTO_SAVE_PARENT_ON_NEW]         TINYINT          DEFAULT ((0)) NOT NULL,
    [CSFT_AUTO_SAVE_PARENT_ON_EDIT]        TINYINT          DEFAULT ((0)) NOT NULL,
    [CSFT_FIXED_COLUMNS]                   TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_NUM_FIXED_COLUMNS]               TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_LINK_VIEW_GRP_COLUMN_NAME]       VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFST_LINK_VIEW_SORT_COLUMN_NAME]      VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFST_ALLOW_USER_SORTING]              TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_SORT_TYPE]                       TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_GRID_TAB_DIRECTION]              TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_VISIBLE_TYPE]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_VISIBLE_TYPE_STAGE]              VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFST_VISIBLE_PROC]                    VARCHAR (100)    DEFAULT ('') NOT NULL,
    [CFST_DATA_ENTRY_GRID_TYPE]            TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_SHOW_AS_BUTTON]                  TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_PER_CELL_ENABLED]                TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_MANUAL_LOAD]                     TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_DISABLE_RECALC]                  TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_LINK_VIEW_FR_COLUMN_NAME]        VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFST_PARENT_LINK_COLUMN_NAME]         VARCHAR (50)     DEFAULT ('') NOT NULL,
    [CFST_TAB_CODE]                        VARCHAR (20)     DEFAULT ('') NOT NULL,
    [CFST_PREFIX]                          VARCHAR (25)     DEFAULT ('') NOT NULL,
    [CFST_LINK_VIEW_PK_COLUMN_DATATYPE]    VARCHAR (30)     DEFAULT ('') NOT NULL,
    [CFST_ALWAYS_REFRESH]                  TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_DISABLE_CELL_SELECTION]          TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_CHART_TYPE]                      TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_CHART_X_AXIS_PADDING]            INT              DEFAULT ((0)) NOT NULL,
    [CFST_CHART_Y_AXIS_PADDING]            INT              DEFAULT ((0)) NOT NULL,
    [CFST_CHART_SWAP_ROWS_COLS]            TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_CHART_SHOW_LEGEND]               TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_CHART_HEIGHT]                    INT              DEFAULT ((0)) NOT NULL,
    [CFST_CHART_WIDTH]                     INT              DEFAULT ((0)) NOT NULL,
    [CFST_REFRESH_BEFORE_SAVE]             TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_RECALC_ON_REFRESH]               TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_AUTO_SAVE_PARENT_ON_SAVE]        TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_AUTO_SAVE_PARENT_BEFORE_REFRESH] TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_ICON_NAME]                       VARCHAR (255)    DEFAULT ('') NOT NULL,
    [CFST_INHERIT_USAGE]                   TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_SYSTEM]                          TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_AUTO_LOAD_PARENT_ON_SAVE]        TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_APPEND_NOTES]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_SUB_CFSH_GUID]                   UNIQUEIDENTIFIER NULL,
    [CFST_SAVE_AS_YOU_TYPE]                TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_ROW_HEIGHT]                      TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_SAVE_ON_LINK_CHANGE]             TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_HEADER_HEIGHT]                   INT              DEFAULT ((0)) NOT NULL,
    [CFST_ALLOW_PAGING]                    TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_PAGE_SIZE]                       FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [CFST_ALLOW_REORDERING]                TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_GUID]                            UNIQUEIDENTIFIER NULL,
    [CFST_MAILMERGE_VIEWNAME]              VARCHAR (200)    DEFAULT ('') NOT NULL,
    [CFST_DO_NOT_REBUILD_MAILMERGE_VIEW]   TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_DO_NOT_VALIDATE_ON_LOAD]         TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_DEFAULT_FROM_VIEW]               TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_REFRESH_FROM_VIEW]               TINYINT          DEFAULT ((0)) NOT NULL,
    [CFST_SHOW_IMPORT_BUTTON]              TINYINT          DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([CFST_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

