CREATE TABLE [dbo].[TS_CUSTOM_FORM_HARNESS_LOG] (
    [CFHL_GUID]    UNIQUEIDENTIFIER NULL,
    [CFHL_LOGTIME] DATETIME         NULL,
    [CFHL_USERID]  VARCHAR (4)      DEFAULT ('') NOT NULL,
    [CFHL_TICKET]  VARCHAR (32)     DEFAULT ('') NOT NULL
);

