CREATE TABLE [dbo].[TS_LINK] (
    [LNK_PRIMARY]   FLOAT (53)    NOT NULL,
    [LNK_TYPE]      VARCHAR (100) DEFAULT ('') NOT NULL,
    [LNK_LINK_VAL1] FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [LNK_LINK_VAL2] FLOAT (53)    DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([LNK_PRIMARY] ASC) WITH (FILLFACTOR = 70)
);

