CREATE TABLE [dbo].[UDEF_SL_ACCOUNTS_EXTRA] (
    [USAE_CUSTCODE]      VARCHAR (10)  NOT NULL,
    [USAE_ACC_PAY_NAME]  VARCHAR (100) NULL,
    [USAE_ACC_PAY_EMAIL] VARCHAR (100) NULL,
    [USAE_RETURNS_NAME]  VARCHAR (100) NULL,
    [USAE_RETURNS_EMAIL] VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([USAE_CUSTCODE] ASC) WITH (FILLFACTOR = 70)
);

