CREATE TABLE [dbo].[WO_COMP_SA_ALLOC] (
    [WA_PRIMARY]           INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WA_COMPONENT_LINK]    INT        NOT NULL,
    [WA_SUB_ANALYSIS_LINK] INT        NOT NULL,
    [WA_QUANTITY]          FLOAT (53) NULL,
    CONSTRAINT [WA_PRIMARY_PK] PRIMARY KEY CLUSTERED ([WA_PRIMARY] ASC),
    CONSTRAINT [WO_COMP_SA_ALLOC_COMPONENT_LINK_FK] FOREIGN KEY ([WA_COMPONENT_LINK]) REFERENCES [dbo].[WO_COMPONENTS] ([WC_PRIMARY]) ON DELETE CASCADE
);

