CREATE TABLE [dbo].[WO_COMPONENTS] (
    [WC_PRIMARY]                INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WC_ORDER_NUMBER]           INT          NOT NULL,
    [WC_TYPE]                   VARCHAR (1)  NOT NULL,
    [WC_PART_LINK]              INT          NULL,
    [WC_TEXT]                   VARCHAR (80) NOT NULL,
    [WC_QUANTITY_REQUIRED]      FLOAT (53)   NOT NULL,
    [WC_QUANTITY_ISSUED]        FLOAT (53)   DEFAULT ((0)) NULL,
    [WC_TOP_LEVEL_ORDER_NUMBER] INT          NOT NULL,
    [WC_LEVEL]                  INT          NOT NULL,
    [WC_BACKFLUSH]              TINYINT      DEFAULT ((0)) NULL,
    [WC_LABOUR]                 TINYINT      DEFAULT ((0)) NULL,
    [WC_QUANTITY_ALLOC]         FLOAT (53)   DEFAULT ((0)) NULL,
    [WC_RTP_FLAG]               TINYINT      DEFAULT ((0)) NULL,
    [WC_ORIGINAL_COST_PRICE]    FLOAT (53)   DEFAULT ((0)) NULL,
    [WC_ASM_QUANTITY]           FLOAT (53)   NOT NULL,
    [WC_QUANTITY_UNBUILT]       FLOAT (53)   DEFAULT ((0)) NULL,
    [WC_REMAINING_COST]         FLOAT (53)   DEFAULT ((0)) NULL,
    [WC_QUANTITY_WRITTEN_OFF]   FLOAT (53)   DEFAULT ((0)) NULL,
    [WC_SUB_ANALYSIS_LINK]      INT          NULL,
    [WC_SOURCE]                 VARCHAR (1)  NULL,
    CONSTRAINT [WC_PRIMARY_PK] PRIMARY KEY CLUSTERED ([WC_PRIMARY] ASC),
    CONSTRAINT [WO_COMPONENTS_ORDER_NUMBER_FK] FOREIGN KEY ([WC_ORDER_NUMBER]) REFERENCES [dbo].[WO_ORDERS] ([WO_ORDER_NUMBER]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WC_ORDER_NUMBER]
    ON [dbo].[WO_COMPONENTS]([WC_ORDER_NUMBER] ASC, [WC_PRIMARY] ASC);


GO
CREATE NONCLUSTERED INDEX [WC_PART_LINK]
    ON [dbo].[WO_COMPONENTS]([WC_PART_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [WC_TOP_LEVEL_ORDER_NUMBER]
    ON [dbo].[WO_COMPONENTS]([WC_TOP_LEVEL_ORDER_NUMBER] ASC);

