CREATE TABLE [dbo].[WO_POP_LINK] (
    [WP_PRIMARY]   INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WP_COMP_LINK] INT        DEFAULT ((0)) NULL,
    [WP_POD_LINK]  FLOAT (53) DEFAULT ((0)) NULL,
    CONSTRAINT [WP_PRIMARY_PK] PRIMARY KEY CLUSTERED ([WP_PRIMARY] ASC),
    CONSTRAINT [WO_POP_LINK_COMP_LINK_FK] FOREIGN KEY ([WP_COMP_LINK]) REFERENCES [dbo].[WO_COMPONENTS] ([WC_PRIMARY]) ON DELETE CASCADE,
    CONSTRAINT [WO_POP_LINK_POD_LINK_FK] FOREIGN KEY ([WP_POD_LINK]) REFERENCES [dbo].[POP_DETAIL] ([POD_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [WP_COMP_LINK]
    ON [dbo].[WO_POP_LINK]([WP_COMP_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [WP_POD_LINK]
    ON [dbo].[WO_POP_LINK]([WP_POD_LINK] ASC);

