CREATE TABLE [dbo].[WO_ROUTES] (
    [WR_PRIMARY]     INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WR_ROUTE]       VARCHAR (10) NOT NULL,
    [WR_DESCRIPTION] VARCHAR (40) NULL,
    [WR_NOTES]       TEXT         NULL,
    [WR_USER_PUTIN]  VARCHAR (4)  NULL,
    [WR_DATE_PUTIN]  DATETIME     NULL,
    [WR_USER_EDITED] VARCHAR (4)  NULL,
    [WR_DATE_EDITED] DATETIME     NULL,
    [WR_DEFAULT]     TINYINT      DEFAULT ((0)) NULL,
    [WR_SOURCE]      VARCHAR (1)  NULL,
    [WR_DO_NOT_USE]  TINYINT      DEFAULT ((0)) NULL,
    CONSTRAINT [WR_PRIMARY_PK] PRIMARY KEY CLUSTERED ([WR_PRIMARY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WR_ROUTE]
    ON [dbo].[WO_ROUTES]([WR_ROUTE] ASC);

