CREATE TABLE [dbo].[WO_ROUTES2] (
    [WR_PRIMARY2] INT           NOT NULL,
    [WR_USRCHAR1] VARCHAR (20)  NULL,
    [WR_USRCHAR2] VARCHAR (20)  NULL,
    [WR_USRCHAR3] VARCHAR (100) NULL,
    [WR_USRCHAR4] VARCHAR (100) NULL,
    [WR_USRCHAR5] VARCHAR (20)  NULL,
    [WR_USRCHAR6] VARCHAR (30)  NULL,
    [WR_USRCHAR7] VARCHAR (30)  NULL,
    [WR_USRCHAR8] VARCHAR (30)  NULL,
    [WR_USRDATE1] DATETIME      NULL,
    [WR_USRDATE2] DATETIME      NULL,
    [WR_USRDATE3] DATETIME      NULL,
    [WR_USRFLAG1] TINYINT       DEFAULT ((0)) NULL,
    [WR_USRFLAG2] TINYINT       DEFAULT ((0)) NULL,
    [WR_USRFLAG3] TINYINT       DEFAULT ((0)) NULL,
    [WR_USRNUM1]  FLOAT (53)    DEFAULT ((0)) NULL,
    [WR_USRNUM2]  FLOAT (53)    DEFAULT ((0)) NULL,
    [WR_USRNUM3]  FLOAT (53)    DEFAULT ((0)) NULL,
    CONSTRAINT [WR_PRIMARY2_PK] PRIMARY KEY CLUSTERED ([WR_PRIMARY2] ASC),
    CONSTRAINT [WO_ROUTES2_PRIMARY2_FK] FOREIGN KEY ([WR_PRIMARY2]) REFERENCES [dbo].[WO_ROUTES] ([WR_PRIMARY]) ON DELETE CASCADE
);

