CREATE TABLE [dbo].[WO_STAGES] (
    [WS_PRIMARY]    INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WS_ROUTE_LINK] INT          NOT NULL,
    [WS_SEQUENCE]   INT          NOT NULL,
    [WS_TEXT]       VARCHAR (30) NOT NULL,
    [WS_SOURCE]     VARCHAR (1)  NULL,
    CONSTRAINT [WS_PRIMARY_PK] PRIMARY KEY CLUSTERED ([WS_PRIMARY] ASC),
    CONSTRAINT [WO_STAGES_ROUTE_LINK_FK] FOREIGN KEY ([WS_ROUTE_LINK]) REFERENCES [dbo].[WO_ROUTES] ([WR_PRIMARY]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WS_STAGES_ROUTE_LINK_WS_SEQUENCE]
    ON [dbo].[WO_STAGES]([WS_ROUTE_LINK] ASC, [WS_SEQUENCE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WS_STAGES_ROUTE_LINK_WS_TEXT]
    ON [dbo].[WO_STAGES]([WS_ROUTE_LINK] ASC, [WS_TEXT] ASC);

