CREATE TABLE [dbo].[WO_STAGE_QUANTITIES] (
    [WQ_PRIMARY]      INT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WQ_STAGE_LINK]   INT        NOT NULL,
    [WQ_ORDER_NUMBER] INT        NOT NULL,
    [WQ_QUANTITY]     FLOAT (53) NOT NULL,
    CONSTRAINT [WQ_PRIMARY_PK] PRIMARY KEY CLUSTERED ([WQ_PRIMARY] ASC),
    CONSTRAINT [WO_STAGE_QUANTITIES_ORDER_NUMBER_FK] FOREIGN KEY ([WQ_ORDER_NUMBER]) REFERENCES [dbo].[WO_ORDERS] ([WO_ORDER_NUMBER]) ON DELETE CASCADE,
    CONSTRAINT [WO_STAGE_QUANTITIES_STAGE_LINK_FK] FOREIGN KEY ([WQ_STAGE_LINK]) REFERENCES [dbo].[WO_STAGES] ([WS_PRIMARY])
);


GO
CREATE NONCLUSTERED INDEX [WQ_ORDER_NUMBER]
    ON [dbo].[WO_STAGE_QUANTITIES]([WQ_ORDER_NUMBER] ASC, [WQ_STAGE_LINK] ASC);

