CREATE TABLE [dbo].[WO_STAGES_TEMP] (
    [WST_ID]             INT          NOT NULL,
    [WST_LINE_NUMBER]    INT          DEFAULT ((0)) NOT NULL,
    [WST_AUTO_NUMBER]    INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [WST_STAGE_PRIMARY]  INT          NULL,
    [WST_STAGE_SEQUENCE] INT          NULL,
    [WST_STAGE_TEXT]     VARCHAR (30) NULL,
    [WST_STAGE_QUANTITY] FLOAT (53)   NULL,
    CONSTRAINT [WST_ID_WST_LINE_NUMBER_PK] PRIMARY KEY CLUSTERED ([WST_ID] ASC, [WST_LINE_NUMBER] ASC, [WST_AUTO_NUMBER] ASC)
);

